import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SCALE_QUESTIONS: VocabQuestion[] = [
  q('sca-glo-1', 'scale', 'Global Scale',
    'Scientists report one sea-level number for the whole ocean, not a separate figure for each country. At which scale is this analysis?',
    ['World Scale', 'National Scale', 'Thematic Map'],
    'A process examined across the entire world is Global Scale. World Scale would look at a large world area such as South Asia. National is one country. A thematic map is a map type.'),
  q('sca-glo-2', 'scale', 'Global Scale',
    'A headline states that world temperature rose 1.1°C. That number is not Japan’s temperature or Africa’s temperature. It is one figure for Earth. Which scale of analysis is this?',
    ['World Scale', 'Regional Scale', 'Local Scale'],
    'One Earth-wide figure is Global Scale. World Scale would examine a large world area such as North America. Regional would be a belt of states or countries. Local would be a city.'),
  q('sca-glo-3', 'scale', 'Global Scale',
    'A climate paper treats greenhouse gases as one planetary process: emissions anywhere change the same atmosphere. The unit is Earth as a whole, not South Asia or one country. Which term applies?',
    ['World Scale', 'National Scale', 'Regional Scale'],
    'Patterns across the entire world are Global Scale. World Scale would be a large world area such as South Asia. National Scale is one country. Regional Scale is a particular area within or across countries.'),
  q('sca-glo-4', 'scale', 'Global Scale',
    'A pandemic model treats the virus as one wave in a linked human population, not 200 separate national epidemics and not only North America. Which concept is being demonstrated?',
    ['World Scale', 'Local Scale', 'Formal Region'],
    'A process examined worldwide is Global Scale. World Scale would be a large world area such as North America. Local Scale is one city. A Formal Region is a type of area.'),
  q('sca-glo-5', 'scale', 'Global Scale',
    'A researcher asks how one capitalist economy has operated across the entire planet since the 1500s, not how South Asia compares with Europe. Which scale of analysis is this?',
    ['National Scale', 'Local Scale', 'Cartographic Scale'],
    'The entire world as the frame is Global Scale. France versus Mali as two countries would be closer to National or World Scale. Local Scale is a city. Cartographic Scale is a map fraction.'),

  q('sca-wor-1', 'scale', 'World Scale',
    'A researcher compares rainfall and population across South Asia as one large area, not the entire planet and not a single country. Which scale of analysis is this?',
    ['Global Scale', 'National Scale', 'Local Scale'],
    'A large world area such as South Asia is World Scale. Global Scale would be the entire planet. National Scale is one country. Local Scale is a city or neighborhood.'),
  q('sca-wor-2', 'scale', 'World Scale',
    'A map examines economic change across North America rather than one city or the whole Earth. Which scale is being used?',
    ['Global Scale', 'Local Scale', 'Site'],
    'North America as a large world area is World Scale. Global would be the entire planet. Local would be a city. Site is physical character.'),
  q('sca-wor-3', 'scale', 'World Scale',
    'A textbook chapter treats Latin America as one frame of analysis, comparing several countries there without zooming to one neighborhood or to the entire planet. Which term applies?',
    ['Global Scale', 'Regional Scale', 'Vernacular Region'],
    'A large world area made of multiple countries is World Scale. Global is the entire world. Regional Scale is often a smaller belt such as Appalachia or coastal China. A Vernacular Region is a perceived area.'),
  q('sca-wor-4', 'scale', 'World Scale',
    'A student is asked to compare monsoon climates across South Asia, not to give one Earth average and not to study only India. Which scale of analysis is the assignment using?',
    ['Global Scale', 'National Scale', 'Cartogram'],
    'South Asia as a multi-country world area is World Scale. Global is one planetary figure. National is one country. A cartogram is a map that resizes area.'),
  q('sca-wor-5', 'scale', 'World Scale',
    'Shipping data are mapped for the countries of Southeast Asia as a group so they can be compared with one another, not totaled into one world figure. Which concept is being demonstrated?',
    ['Global Scale', 'Local Scale', 'Functional Region'],
    'Multiple countries in a large world area are World Scale. A Global figure would be total world shipping. Local would be one port neighborhood. A Functional Region is one hub’s hinterland.'),

  q('sca-nat-1', 'scale', 'National Scale',
    'A table lists one well-being score for Japan and one for Nigeria so the two countries can be ranked. Which scale treats each country as a single unit?',
    ['Local Scale', 'Global Scale', 'Dot Distribution Map'],
    'One score per country is National Scale. Local would be city scores. Global would be one world score. A dot map is a symbol type.'),
  q('sca-nat-2', 'scale', 'National Scale',
    'India’s census is used to compute one female labor-force rate for the Republic of India, then compared with Bangladesh’s rate. District gaps inside India are ignored. Which term applies?',
    ['Regional Scale', 'Local Scale', 'World Scale'],
    'One statistic for a whole country is National Scale. Regional would be an Indian state belt. Local would be a district. World Scale would be a large world area such as South Asia.'),
  q('sca-nat-3', 'scale', 'National Scale',
    'A journalist writes “France is secular” because national law limits religious symbols in schools. Marseille neighborhoods look different from Brittany. Which scale is the journalist using?',
    ['Local Scale', 'Regional Scale', 'Global Scale'],
    'The unit is the country and its law — National Scale. Local would be those neighborhoods. Regional would be Brittany. Global would be a worldwide process.'),
  q('sca-nat-4', 'scale', 'National Scale',
    'Income per person is usually one number for Japan or Nigeria so governments can be ranked. The number conceals internal gaps but remains a country-level figure. Which concept is being demonstrated?',
    ['Local Scale', 'Regional Scale', 'Cartographic Scale'],
    'A country-level figure is National Scale. Local and Regional would split the country. Cartographic Scale is how zoomed-in the map is.'),
  q('sca-nat-5', 'scale', 'National Scale',
    'A law applies to every province in Kenya in the same way. The analysis treats Kenya as one unit. Which AP Human Geography term best applies?',
    ['Regional Scale', 'World Scale', 'Sense of Place'],
    'The country as one unit is National Scale. Regional would be one Kenyan province group. World Scale would be a large world area. Sense of Place is meaning.'),

  q('sca-reg-1', 'scale', 'Regional Scale',
    'A paper on United States opioid deaths compares Appalachia, New England, and the Southwest as multi-state belts, not 3,000 counties and not one national average. Which scale is this?',
    ['National Scale', 'Local Scale', 'Global Scale'],
    'A particular area larger than a city but not the whole country is Regional Scale. National would be one U.S. rate. Local would be a county. Global would be the planet.'),
  q('sca-reg-2', 'scale', 'Regional Scale',
    'China looks different if one compares the coastal manufacturing belt with the western interior instead of quoting one national GDP. Which term applies?',
    ['National Scale', 'World Scale', 'Site'],
    'Large areas inside a country are Regional Scale. National is all of China as one number. World Scale would be a large world area such as East Asia. Site is one locality’s physical character.'),
  q('sca-reg-3', 'scale', 'Regional Scale',
    'A study of Italy looks at the south versus the north, not one number for the whole country and not one village. Which scale of analysis is this?',
    ['Local Scale', 'National Scale', 'Formal Region'],
    'Those blocks inside the country are Regional Scale. Local would be a village. National would be Italy as a whole. They may also be formal regions, but the question asks for scale of analysis.'),
  q('sca-reg-4', 'scale', 'Regional Scale',
    'A U.S. map is redrawn to compare the South with the Midwest. That zoom is not local streets and not the whole country as one color. Which concept is being demonstrated?',
    ['Local Scale', 'National Scale', 'World Scale'],
    'South vs Midwest is Regional Scale. Local is streets. National is one U.S. color. World Scale would be North America as a whole.'),
  q('sca-reg-5', 'scale', 'Regional Scale',
    'A drought paper studies the Sahel as a belt across several countries, not as one village and not as the entire world. Which vocabulary term is this zoom?',
    ['Local Scale', 'Global Scale', 'Quaternary Sector'],
    'A particular multi-country belt is Regional Scale. Local is a village. Global is the entire world. Quaternary Sector is information work.'),

  q('sca-loc-1', 'scale', 'Local Scale',
    'A food-access study maps grocery stores by neighborhood instead of using one number for the whole country. Which scale is this?',
    ['Regional Scale', 'National Scale', 'World Systems Theory'],
    'A neighborhood or community is Local Scale. Regional would be a multi-state belt. National would be one U.S. rate. World Systems Theory is a development model.'),
  q('sca-loc-2', 'scale', 'Local Scale',
    'A Brooklyn zoning dispute concerns one neighborhood’s rent and school seats. Citywide bills exist, but this map is drawn block by block. Which term applies?',
    ['Regional Scale', 'National Scale', 'World Scale'],
    'Block- and neighborhood-level analysis is Local Scale. Regional would be a multi-borough belt. National would be U.S. housing policy. World Scale would be a large world area.'),
  q('sca-loc-3', 'scale', 'Local Scale',
    'Lagos appears wealthy in a country ranking, but a researcher maps one unregistered settlement’s tap water and one gated estate’s wells and finds opposite outcomes. Which scale reveals the contrast?',
    ['National Scale', 'Global Scale', 'Vernacular Region'],
    'Comparing neighborhoods inside one city is Local Scale. National Scale hid the contrast in Nigeria’s average. Global would be a worldwide water statistic. A Vernacular Region is a perceived area.'),
  q('sca-loc-4', 'scale', 'Local Scale',
    'After a chemical spill, investigators test wells on three streets. A state-level cancer rate would conceal whether those streets are the problem. Which concept is being demonstrated?',
    ['Regional Scale', 'National Scale', 'Small-Scale Maps'],
    'Streets and households are Local Scale. Regional or National rates would average the spill away. Small-scale maps show large areas with less detail.'),
  q('sca-loc-5', 'scale', 'Local Scale',
    'A national average hides a slum next to a wealthy district. The contrast only appears when analysis zooms to streets and blocks. Which AP Human Geography term best applies?',
    ['World Scale', 'Global Scale', 'Cartographic Scale'],
    'The neighborhood zoom is Local Scale. World and Global are much larger frames. Cartographic Scale is the map’s representative fraction, related but not the social unit.'),
]
