import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SPATIAL_QUESTIONS: VocabQuestion[] = [
  q('spa-spc-1', 'spatial', 'Space',
    'The planner measures how far two stores sit apart, not what either store means to residents.',
    ['Place', 'Sense of Place', 'Human Development Index'],
    'Distance and extent between things is Space. Place is unique character. Sense of Place is feeling. HDI is a development index.'),
  q('spa-spc-2', 'spatial', 'Space',
    'The empty stretch between grain elevators is treated as distance and arrangement, not identity.',
    ['Place', 'Sense of Place', 'Toponyms'],
    'The physical extent between objects is Space. Place is a locality with character. Sense of Place is attachment. Toponyms are names.'),
  q('spa-spc-3', 'spatial', 'Space',
    'Two pharmacies play similar roles. The next question is how far apart they sit and whether their service areas overlap.',
    ['Place', 'Cultural Landscape', 'Vernacular Region'],
    'Distances and extent are Space. Place would be each pharmacy’s meaning. Cultural Landscape is the visible imprint. A vernacular region is a perceived area.'),
  q('spa-spc-4', 'spatial', 'Space',
    '“Near things are more related than distant things” is a claim about a continuous surface, not about one town’s identity.',
    ['Place', 'Site', 'Formal Region'],
    'The area between and around phenomena is Space. Place and Site describe particular localities. A formal region is one way of grouping that surface.'),
  q('spa-spc-5', 'spatial', 'Space',
    'The downtowns feel similar. The second question is how many miles apart the two cities sit.',
    ['Place', 'Toponyms', 'Literacy Rate'],
    'Mileage and separation are Space. Place is the downtown character. Toponyms are names. Literacy Rate is schooling.'),

  q('spa-loc-1', 'spatial', 'Location',
    'Before asking what Cairo is like, the first fact is simply where it is.',
    ['Place', 'Sense of Place', 'Pattern'],
    'The position of something on Earth is Location. Place adds character. Sense of Place adds feeling. Pattern is how several things are arranged.'),
  q('spa-loc-2', 'spatial', 'Location',
    'The contract names a berth, not the city’s food or architecture.',
    ['Place', 'Cultural Landscape', 'Sustainability'],
    'Position on Earth’s surface is Location. Place would be the city’s character. Cultural Landscape would be the portscape. Sustainability is a resource-use idea.'),
  q('spa-loc-3', 'spatial', 'Location',
    'The first map just says cases occurred here and here. Meaning comes later.',
    ['Sense of Place', 'Toponyms', 'Quinary Sector'],
    'Pinning events to positions is Location. Sense of Place is the later feeling. Toponyms would be the names. Quinary Sector is elite jobs.'),
  q('spa-loc-4', 'spatial', 'Location',
    'The missing-person report starts with where, not with what the town means to residents.',
    ['Sense of Place', 'Human Development Index', 'Informal Sector'],
    'The starting “where” is Location. Sense of Place is meaning. HDI is well-being. Informal Sector is unrecorded work.'),
  q('spa-loc-5', 'spatial', 'Location',
    'The report first states where the factory is — on the river, at a set of coordinates.',
    ['Pattern', 'Land Use', 'Gini Coefficient'],
    'Where something sits on Earth is Location. Pattern is arrangement of many things. Land Use is how a parcel is used. Gini is inequality.'),

  q('spa-plc-1', 'spatial', 'Place',
    'The city’s food, streets, history, and buildings make it feel unlike the next city over.',
    ['Location', 'Space', 'Absolute Location'],
    'A spot with distinctive character is Place. Location or Absolute Location would be enough if only the pin mattered. Space would be the gap between cities.'),
  q('spa-plc-2', 'spatial', 'Place',
    'The coordinate is the same, but the market and who feels safe there are gone, so it is not the same.',
    ['Location', 'Site', 'Cartographic Scale'],
    'The unique mix of character is Place. The coordinate is Location. Site is the physical setting. Cartographic Scale is a map ratio.'),
  q('spa-plc-3', 'spatial', 'Place',
    'Tourism boards sell “Tuscany” as something you cannot get by substituting any other coordinate with similar weather.',
    ['Space', 'Friction of Distance', 'Gini Coefficient'],
    'A locality distinguished by unique character is Place. Space is interchangeable geometry. Friction of Distance is movement cost. Gini is inequality.'),
  q('spa-plc-4', 'spatial', 'Place',
    'Two strip malls can have the same parking lot and still not feel like the same town.',
    ['Space', 'Cartogram', 'Formal Sector'],
    'Distinctive town character is Place. Space is the lot geometry. A cartogram is a map type. Formal Sector is taxed work.'),
  q('spa-plc-5', 'spatial', 'Place',
    'The weather is similar, but residents say each town has its own character and story.',
    ['Location', 'Absolute Location', 'Primary Sector'],
    'A spot plus its unique character is Place. A pin alone is Location or Absolute Location. Primary Sector is extraction.'),

  q('spa-sit-1', 'spatial', 'Site',
    'Crops do well here because of the soil, the river, and the climate.',
    ['Situation', 'Location', 'Thematic Map'],
    'Soil, water, and climate are Site. Situation is relative to other places. Location is the broader “where.” A thematic map shows a data theme.'),
  q('spa-sit-2', 'spatial', 'Site',
    'The settlement grew beside a river with fertile soil and a dependable water supply.',
    ['Situation', 'Relative Location', 'Sense of Place'],
    'Those on-the-ground traits are Site. Situation and Relative Location are about connections. Sense of Place is how people feel.'),
  q('spa-sit-3', 'spatial', 'Site',
    'Snow and steep slopes made this a ski town.',
    ['Situation', 'Toponyms', 'Formal Region'],
    'Terrain and climate are Site. Distance from a capital would be situation. Toponyms are names. A formal region is a uniform area.'),
  q('spa-sit-4', 'spatial', 'Site',
    'The downtown parcel is rejected for weak power, shaky bedrock, and impure water, even though the airport is close.',
    ['Situation', 'Time-Space Compression', 'Vernacular Region'],
    'On-parcel physical traits are Site. Airport closeness would be situation. Time-space compression shrinks effective distance. A vernacular region is a mental area.'),
  q('spa-sit-5', 'spatial', 'Site',
    'The city was built on a river-mouth swamp below sea level, with rich soils and a large harbor basin.',
    ['Situation', 'World Scale', 'Remittances'],
    'The physical setting is Site. Sitting on a trade route would be situation. World Scale compares a large world area. Remittances are migrant money.'),

  q('spa-situ-1', 'spatial', 'Situation',
    'The city grew because highways, rail lines, and waterways all meet there.',
    ['Site', 'Space', 'Gini Coefficient'],
    'Position relative to routes and other cities is Situation. Site is the ground itself. Space is the geometric surface. Gini is inequality.'),
  q('spa-situ-2', 'spatial', 'Situation',
    'The soils are swampy. The real advantage is sitting between Great Lakes shipping and the Mississippi–rail system.',
    ['Site', 'Sense of Place', 'Isoline Map'],
    'Connections to transport systems are Situation. The soils are Site. Sense of Place is attachment. An isoline map is a display.'),
  q('spa-situ-3', 'spatial', 'Situation',
    'The river and flat land are unchanged, but the interstate and the container port moved 80 miles away.',
    ['Site', 'Built Environment', 'Literacy Rate'],
    'Lost connections are Situation. Unchanged water and land are Site. Buildings still standing are Built Environment. Literacy Rate is schooling.'),
  q('spa-situ-4', 'spatial', 'Situation',
    'Many harbors are deep. This one became a hub because it sits on a major shipping route.',
    ['Site', 'Absolute Location', 'Primary Sector'],
    'Astride a world route is Situation. Harbor depth is Site. The coordinate is Absolute Location. Primary Sector is extraction.'),
  q('spa-situ-5', 'spatial', 'Situation',
    'The city mattered because it sat between two seas, not only because of its hills.',
    ['Site', 'Pattern', 'Informal Sector'],
    'Position relative to other seas and routes is Situation. Hills are Site. Pattern is arrangement. Informal Sector is unrecorded work.'),

  q('spa-sen-1', 'spatial', 'Sense of Place',
    'Residents fight the glass tower because the street “feels like home,” even though the soil can hold it.',
    ['Site', 'Location', 'Cartogram'],
    'Feelings and attachment are Sense of Place. Site is physical capability. Location is position. A cartogram is a map type.'),
  q('spa-sen-2', 'spatial', 'Sense of Place',
    'A family forced from home and a tourist stand on the same hill. Only one has memory and loss.',
    ['Site', 'Absolute Location', 'Secondary Sector'],
    'Meaning and attachment are Sense of Place. Geology is Site. The coordinate is Absolute Location. Secondary Sector is manufacturing.'),
  q('spa-sen-3', 'spatial', 'Sense of Place',
    'Students say they can “feel” game day downtown. The streets did not move.',
    ['Location', 'Site', 'Choropleth Map'],
    'The feeling is Sense of Place. Location is the pin. Site is the soil. A choropleth shades statistical units.'),
  q('spa-sen-4', 'spatial', 'Sense of Place',
    'The streets are still there, but long-time residents say this is not their neighborhood anymore.',
    ['Absolute Location', 'Cartographic Scale', 'Primary Sector'],
    'Lost attachment is Sense of Place. The coordinate is still Absolute Location. Cartographic Scale is a map ratio. Primary Sector is extraction.'),
  q('spa-sen-5', 'spatial', 'Sense of Place',
    'The town markets “game-day atmosphere” as something visitors say they can feel.',
    ['Formal Region', 'Friction of Distance', 'Gini Coefficient'],
    'A felt atmosphere is Sense of Place. A formal region would need a measurable rule. Friction of Distance is travel cost. Gini is inequality.'),

  q('spa-top-1', 'spatial', 'Toponyms',
    'The city once labeled Bombay is now Mumbai on every official sign. The pin did not move.',
    ['Location', 'Place', 'Formal Region'],
    'The name is a Toponym. Location is the position. Place is the character. A Formal Region is a uniform area.'),
  q('spa-top-2', 'spatial', 'Toponyms',
    'Istanbul, Constantinople, and Byzantium are fights over who may label the city.',
    ['Absolute Location', 'Site', 'Pattern'],
    'The names, and the politics of naming, are Toponyms. The coordinate is Absolute Location. Site is the physical setting. Pattern is arrangement.'),
  q('spa-top-3', 'spatial', 'Toponyms',
    'After independence, the capital and several cities are renamed so maps no longer use colonial labels.',
    ['Site', 'Situation', 'Cartographic Scale'],
    'Rewriting official names is a toponym change. The ground and the connections were not what the law renamed. Cartographic Scale is the map ratio.'),
  q('spa-top-4', 'spatial', 'Toponyms',
    'Spanish saint names and Anglicized Indigenous names still sit on the same map.',
    ['Vernacular Region', 'Cultural Landscape', 'Reference Map'],
    'The names themselves are Toponyms. They hint at cultural landscape, but the vocab word for the names is toponyms. A vernacular region is a perceived area. A reference map is one place the names appear.'),
  q('spa-top-5', 'spatial', 'Toponyms',
    '“Los Angeles,” “New York,” and “St. Louis” tell a colonial story before anyone looks at the skyline.',
    ['Absolute Location', 'Gini Coefficient', 'Remote Sensing'],
    'The words are Toponyms. Absolute Location would be the coordinates. Gini is inequality. Remote Sensing is satellite data.'),

  q('spa-tsc-1', 'spatial', 'Time-Space Compression',
    'A file crosses the ocean in seconds. A flight does it in a day. The kilometers did not shrink.',
    ['Distance Decay', 'Friction of Distance', 'Absolute Location'],
    'Faster connection is Time-Space Compression. Distance Decay is interaction fading with distance. Friction of Distance is the cost being reduced. Absolute Location is unchanged.'),
  q('spa-tsc-2', 'spatial', 'Time-Space Compression',
    'A letter used to take weeks. A video call now happens in seconds.',
    ['Friction of Distance', 'Small-Scale Maps', 'Gini Coefficient'],
    'Less time to connect distant places is Time-Space Compression. Friction of Distance is the cost being reduced. Small-scale maps show large areas. Gini is inequality.'),
  q('spa-tsc-3', 'spatial', 'Time-Space Compression',
    'A family runs a shop whose suppliers are on another continent, using video calls and container ships.',
    ['Distance Decay', 'Absolute Location', 'Primary Sector'],
    'Distant places becoming quicker to connect is Time-Space Compression. Distance Decay is interaction fading with miles. Absolute Location is a pin. Primary Sector is extraction.'),
  q('spa-tsc-4', 'spatial', 'Time-Space Compression',
    'A price shock crosses the Atlantic faster than a nineteenth-century letter crossed a county.',
    ['Distance Decay', 'Site', 'Formal Sector'],
    'The collapse of time-over-distance is Time-Space Compression. Distance Decay would predict less interaction with more miles. Site is local ground. Formal Sector is legal work.'),
  q('spa-tsc-5', 'spatial', 'Time-Space Compression',
    'Container ships, jets, and video calls let a family in Lagos run a shop supplied from Guangzhou.',
    ['Environmental Determinism', 'Literacy Rate', 'Choropleth Map'],
    'Far-flung daily integration is Time-Space Compression. Environmental Determinism would blame climate. Literacy Rate is schooling. A choropleth shades rates.'),

  q('spa-fri-1', 'spatial', 'Friction of Distance',
    'A mountain pass and a toll make the next town expensive to reach, even though it is not far in miles.',
    ['Distance Decay', 'Time-Space Compression', 'Human Development Index'],
    'Extra time, cost, and difficulty is Friction of Distance. Distance Decay is the fading of interaction. Time-space compression fights that difficulty. HDI is well-being.'),
  q('spa-fri-2', 'spatial', 'Friction of Distance',
    'Two villages 8 km apart interact less than two villages 20 km apart on a highway. A river with no bridge sits between the first pair.',
    ['Distance Decay', 'Pattern', 'Choropleth Map'],
    'The river raises the cost of movement: Friction of Distance. Distance Decay would describe the outcome. Pattern is the arrangement of villages. A choropleth is a map type.'),
  q('spa-fri-3', 'spatial', 'Friction of Distance',
    'Steel costs more to ship than software the same number of miles, so steel plants stay nearer mines.',
    ['Time-Space Compression', 'Sense of Place', 'Literacy Rate'],
    'High movement cost is Friction of Distance. Time-space compression is the long-run decline in that cost. Sense of Place and Literacy Rate are not transport-cost ideas.'),
  q('spa-fri-4', 'spatial', 'Friction of Distance',
    'Before railroads, moving grain 100 miles inland was often not worth the time and cost.',
    ['Site', 'Toponyms', 'Gender Gap'],
    'Time and cost rising with distance is Friction of Distance. Site is local physical character. Toponyms are names. Gender Gap is a social difference.'),
  q('spa-fri-5', 'spatial', 'Friction of Distance',
    'A mountain range, a visa, a toll, and a poor road all make the next town farther in time and money.',
    ['Distance Decay', 'Time-Space Compression', 'Absolute Location'],
    'The effort required to move is Friction of Distance. Distance Decay is the resulting drop in interaction. Time-space compression reduces that friction. Absolute Location is the kilometer reading.'),

  q('spa-dd-1', 'spatial', 'Distance Decay',
    'Radio listeners drop off as one drives farther from the tower.',
    ['Time-Space Compression', 'Possibilism', 'Quinary Sector'],
    'Interaction falling as distance rises is Distance Decay. Time-space compression reduces the fade. Possibilism is a human-environment theory. Quinary Sector is elite jobs.'),
  q('spa-dd-2', 'spatial', 'Distance Decay',
    'The new store’s first customers live nearby. Almost no one drives in from the next county.',
    ['Friction of Distance', 'Absolute Location', 'Cartogram'],
    'Connection dropping with greater distance is Distance Decay. Friction of Distance is the cost. Absolute Location is a coordinate. A cartogram resizes area.'),
  q('spa-dd-3', 'spatial', 'Distance Decay',
    'Pizza deliveries and a dialect both thin out as one moves away from the origin.',
    ['Time-Space Compression', 'Friction of Distance', 'Absolute Location'],
    'Interaction declining with distance is Distance Decay. Friction of Distance is the cost that helps cause it. Time-space compression flattens the drop-off. Absolute Location is a pin.'),
  q('spa-dd-4', 'spatial', 'Distance Decay',
    'After the subway opens, customers stretch farther along the line and still fall off quickly away from it.',
    ['Site', 'Toponyms', 'Human Development Index'],
    'Customers thinning with effective distance is Distance Decay. Site is the store’s parcel. Toponyms are names. HDI is a development index.'),
  q('spa-dd-5', 'spatial', 'Distance Decay',
    'The rumor spreads quickly in one city and barely appears in a town 400 km away with no social ties.',
    ['Time-Space Compression', 'Formal Region', 'Secondary Sector'],
    'Influence fading with separation is Distance Decay. Time-space compression would be if social media erased that fade. A Formal Region shares a trait. Secondary Sector is manufacturing.'),

  q('spa-pat-1', 'spatial', 'Pattern',
    'Houses line up in strips along a river. Later suburban homes cluster in loops.',
    ['Place', 'Sense of Place', 'Cartographic Scale'],
    'Linear vs clustered arrangement is Pattern. Place is one locality’s character. Sense of Place is feeling. Cartographic Scale is the map ratio.'),
  q('spa-pat-2', 'spatial', 'Pattern',
    'The crime analyst only says clustered, dispersed, or random.',
    ['Sense of Place', 'Situation', 'Gender Gap'],
    'Those labels are Pattern. Sense of Place would be why an alley feels unsafe. Situation is connections. Gender Gap is a social difference.'),
  q('spa-pat-3', 'spatial', 'Pattern',
    'Wind turbines stand in a straight line. Farmhouses sit in a scattered spread.',
    ['Place', 'Absolute Location', 'Human Development Index'],
    'Linear or dispersed arrangements are Pattern. Place is character. Absolute Location is a coordinate. HDI is a development index.'),
  q('spa-pat-4', 'spatial', 'Pattern',
    'Towns of similar size sit at roughly regular intervals across a uniform plain.',
    ['Location', 'Literacy Rate', 'Quinary Sector'],
    'Regular spacing is Pattern. Location is one town’s position. Literacy Rate is schooling. Quinary Sector is leadership jobs.'),
  q('spa-pat-5', 'spatial', 'Pattern',
    'The crime map is labeled clustered, dispersed, or random. The labels describe how the dots sit.',
    ['Site', 'Remittances', 'Isoline Map'],
    'Geometric arrangement is Pattern. Site is local ground. Remittances are migrant transfers. Isolines could display a surface but are not the arrangement idea.'),
]
