import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_THEORY_QUESTIONS: VocabQuestion[] = [
  q('th-wst-1', 'theories', 'World Systems Theory',
    'Côte d’Ivoire produces cocoa, processing plants in the Netherlands refine the beans, and Swiss firms brand the finished chocolate and retain most of the profit. A geographer interprets these places not as isolated national economies but as core, semi-periphery, and periphery positions within a single capitalist world-economy.',
    ['Dependency Model', 'Commodity Dependence', 'Primary Sector'],
    'One connected world-economy with core, semi-periphery, and periphery roles is World Systems Theory. The Dependency Model is a poorer-country-to-richer-country trap, not the three-tier system. Commodity Dependence only describes a raw-export mix. Primary Sector names farming, not the world hierarchy.'),
  q('th-wst-2', 'theories', 'World Systems Theory',
    'South Korea shifted from low-wage assembly into electronics design and finance, while much of Central America remained specialized in bananas and apparel for United States markets. The model that allows some places to advance into an intermediate semi-periphery role is being applied.',
    ['Dependency Model', 'Possibilism', 'Quinary Sector'],
    'World Systems Theory includes a semi-periphery that can mix cheap production with rising technology. The Dependency Model stresses lasting dependence, not climbing. Possibilism is about environment and choice. Quinary Sector is elite decision jobs.'),
  q('th-wst-3', 'theories', 'World Systems Theory',
    'High-wage finance and design concentrate in the United States, Western Europe, and Japan, while many tropical countries continue to export ores and agricultural commodities. The pattern is explained as one integrated system with differentiated economic roles.',
    ['Human Development Index', 'Formal Region', 'Time-Space Compression'],
    'Core–periphery roles in one world-economy are World Systems Theory. HDI ranks well-being. A formal region shares one trait. Time-space compression is shrinking travel time.'),
  q('th-wst-4', 'theories', 'World Systems Theory',
    'A student treats Zambia, China, and Germany as three unrelated national cases. A more accurate interpretation is that copper extraction, smelting, and branding occupy positions in a single global division of labor.',
    ['Literacy Rate', 'Site', 'Cartogram'],
    'One global division of labor is World Systems Theory. Literacy Rate is schooling. Site is local physical character. A cartogram resizes map area by data.'),
  q('th-wst-5', 'theories', 'World Systems Theory',
    'A free-response item asks why many lower-income countries remain specialized in agricultural and mineral exports while higher-income countries retain high-value services. The expected model classifies the world by economic role rather than by climate.',
    ['Environmental Determinism', 'National Scale', 'Built Environment'],
    'Grouping the world by economic role is World Systems Theory. Environmental Determinism would blame climate. National Scale is one country. Built Environment is human-made structures.'),

  q('th-dep-1', 'theories', 'Dependency Model',
    'A Central American country’s ports and railroads were constructed so that a United States fruit company could export bananas. Decades after political independence, the country still imports machinery and credit from the same partner. Wealthy countries remain wealthy because poorer countries remain structurally tied to them.',
    ['World Systems Theory', 'Commodity Dependence', 'Formal Sector'],
    'That lasting unequal relationship is the Dependency Model. World Systems Theory zooms out to a three-tier world-economy. Commodity Dependence notes the banana export but not the political-economic control. Formal Sector is taxed work.'),
  q('th-dep-2', 'theories', 'Dependency Model',
    'An Andean state nationalizes a mine yet must still sell ore through London brokers and repay loans denominated in dollars. Political independence has not produced economic autonomy.',
    ['Possibilism', 'Remittances', 'Absolute Location'],
    'Needing foreign markets, technology, and credit after independence is the Dependency Model. Possibilism is environmental choice. Remittances are migrant money. Absolute Location is a coordinate.'),
  q('th-dep-3', 'theories', 'Dependency Model',
    'After a West African government reduced tariffs, inexpensive imported cloth displaced local weaving, and cocoa continued to leave the country unprocessed. Critics argue that trade liberalization reproduced an older colonial division of labor.',
    ['World Systems Theory', 'Tertiary Sector', 'Small-Scale Maps'],
    'Opening trade reproduced an unequal role: Dependency Model. World Systems Theory would emphasize core/semi-periphery/periphery positions worldwide. Tertiary Sector is services. Small-scale maps show large areas.'),
  q('th-dep-4', 'theories', 'Dependency Model',
    'Ethiopia exports inexpensive coffee; United States firms roast and brand it at a substantially higher price. Ethiopia’s public budget then fluctuates with a price it does not set. The wealthier country remains wealthy in part through this unequal partnership.',
    ['Purchasing Power Parity', 'Sense of Place', 'Quaternary Sector'],
    'Wealthy states remaining wealthy through a poorer export partner is the Dependency Model. PPP compares prices. Sense of Place is feeling. Quaternary Sector is information work.'),
  q('th-dep-5', 'theories', 'Dependency Model',
    'A textbook states that more developed countries require less developed countries in order to obtain inexpensive raw materials and markets. The claim is not merely that a country exports petroleum.',
    ['Commodity Dependence', 'Gini Coefficient', 'Functional Region'],
    'Richer countries needing a poorer periphery is the Dependency Model. Commodity Dependence is export concentration on one product. Gini measures inequality inside a country. A functional region is organized around a node.'),

  q('th-com-1', 'theories', 'Commodity Dependence',
    'Nigeria’s public budget contracted sharply in 2014 and 2020 when petroleum prices declined, even though Lagos has a substantial services economy. Petroleum still accounts for most export earnings.',
    ['World Systems Theory', 'Informal Sector', 'Primary Sector'],
    'Living off one raw export whose price is set abroad is Commodity Dependence. World Systems Theory is a broader world hierarchy. Informal Sector is unrecorded work. Primary Sector is the type of work, not the dangerous concentration of exports.'),
  q('th-com-2', 'theories', 'Commodity Dependence',
    'Chile’s copper, Zambia’s copper, and Venezuela’s petroleum each produced periods of expansion followed by austerity when the same export price declined. Manufacturing remained a small share of exports.',
    ['Dependency Model', 'Secondary Sector', 'Remittances'],
    'National earnings tied to one raw good is Commodity Dependence. The Dependency Model is the broader rich/poor relationship. Secondary Sector is manufacturing. Remittances are migrant transfers.'),
  q('th-com-3', 'theories', 'Commodity Dependence',
    'A Pacific island’s currency and port traffic fluctuate with a single mineral price. Tourist arrivals remain relatively stable, yet the government cannot fund schools when that price declines.',
    ['Distance Decay', 'Life Expectancy', 'Local Scale'],
    'One export price driving the whole budget is Commodity Dependence. Distance Decay is declining interaction with distance. Life Expectancy is years lived. Local Scale is neighborhood-level analysis.'),
  q('th-com-4', 'theories', 'Commodity Dependence',
    'A free-response item uses Ethiopia and coffee, or Nigeria and petroleum, to illustrate why a country is vulnerable to a world price it does not control.',
    ['Human Development Index', 'Formal Region', 'Cartographic Scale'],
    'Vulnerability to one export price is Commodity Dependence. HDI is a well-being composite. A formal region shares a trait. Cartographic Scale is the map-to-Earth ratio.'),
  q('th-com-5', 'theories', 'Commodity Dependence',
    'A country may possess factories and cities and still remain vulnerable if nearly all of its foreign-exchange earnings derive from a single crop or mineral.',
    ['Quinary Sector', 'Built Environment', 'Relative Location'],
    'Foreign earnings from one raw good is Commodity Dependence, even if other sectors exist. Quinary Sector is top decision-making. Built Environment is buildings and roads. Relative Location is position compared with other places.'),
]
