import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_DATA_QUESTIONS: VocabQuestion[] = [
  q('dat-fld-1', 'data', 'Field Observations',
    'To see why Bogotá riders switched to a new bus line, a researcher stands at stations, counts boardings, and interviews people. Satellites can show the stations but not the “why.” Which method is the researcher using?',
    ['Remote Sensing', 'Geographic Information Systems', 'Global Positioning System'],
    'On-site counting and interviewing is Field Observations. Remote Sensing is imagery from above. GIS later stacks the counts. GPS only records coordinates.'),
  q('dat-fld-2', 'data', 'Field Observations',
    'A geographer walks Fez, sketches guild symbols on doors, and asks shopkeepers when the last tanner left. Census tables just say “manufacturing.” Which method captures that meaning?',
    ['Remote Sensing', 'Choropleth Map', 'Cartographic Scale'],
    'Walking and interviewing is Field Observations. Remote Sensing is distant imagery. A choropleth is a shaded-area map. Cartographic Scale is the map-to-Earth ratio.'),
  q('dat-fld-3', 'data', 'Field Observations',
    'After a Jakarta flood, teams mark high-water stains and photograph walkways that official maps omit. They are checking what a cloudy satellite image might miss. Which method is that?',
    ['Remote Sensing', 'Isoline Map', 'World Systems Theory'],
    'On-the-ground marks and photos are Field Observations used as ground truth. Remote Sensing is the satellite layer. Isolines might later show water depth. World Systems Theory is a development model.'),
  q('dat-fld-4', 'data', 'Field Observations',
    'A student claims satellite images have replaced all on-the-ground work. A teacher replies that interviews and street counts still answer questions images cannot. Which method is the teacher defending?',
    ['Global Positioning System', 'Reference Map', 'Formal Sector'],
    'Interviews and street counts are Field Observations. GPS is a coordinate. A reference map shows location. Formal Sector is taxed work.'),
  q('dat-fld-5', 'data', 'Field Observations',
    'Going to the place — watching land use, talking to residents, or counting traffic in person — is which data method?',
    ['Remote Sensing', 'Thematic Map', 'Quaternary Sector'],
    'Going to the place is Field Observations. Remote Sensing never requires standing there. A thematic map displays a variable. Quaternary Sector is information employment.'),

  q('dat-rs-1', 'data', 'Remote Sensing',
    'A lab compares 1985 and 2020 Landsat scenes to measure Amazon clearing. No researcher visited most of those pixels. Which method produced the change layer?',
    ['Field Observations', 'Global Positioning System', 'Geographic Information Systems'],
    'Satellite images of Earth’s surface are Remote Sensing. Field Observations require being there. GPS is a coordinate. GIS may display the classified images later.'),
  q('dat-rs-2', 'data', 'Remote Sensing',
    'During a Sahel drought, agencies estimate dying pasture from aircraft and satellite vegetation images because ground teams cannot cover the belt in a week. Which method lets them see that area from a distance?',
    ['Field Observations', 'Reference Map', 'Quaternary Sector'],
    'Aircraft and satellite sensors are Remote Sensing. Field teams would be Field Observations. A reference map shows names and roads. Quaternary Sector is the analysts’ job type, not the method.'),
  q('dat-rs-3', 'data', 'Remote Sensing',
    'A city buys a lidar point cloud flown from a plane to measure rooftop area for solar panels instead of climbing every building. Which method created the measurements?',
    ['Geographic Information Systems', 'Field Observations', 'Topographic Map'],
    'Lidar from a plane is Remote Sensing. GIS is how the city analyzes the cloud. Climbing roofs is Field Observations. A topographic map is a finished contour sheet.'),
  q('dat-rs-4', 'data', 'Remote Sensing',
    'Deforestation questions on the AP exam usually expect this method — repeat images from space — not a one-time GPS pin or a single interview. Which method is that?',
    ['Global Positioning System', 'Literacy Rate', 'Vernacular Region'],
    'Repeat images from above are Remote Sensing. A GPS pin is one coordinate. Literacy Rate is schooling. A vernacular region is a perceived area.'),
  q('dat-rs-5', 'data', 'Remote Sensing',
    'Getting data about Earth’s surface from a satellite or aircraft, such as repeat hurricane images from space, is which method?',
    ['Global Positioning System', 'Field Observations', 'Dot Distribution Map'],
    'Long-distance images of Earth are Remote Sensing. GPS reports a receiver’s coordinates. Field Observations are on the ground. A dot map is a symbol type.'),

  q('dat-gps-1', 'data', 'Global Positioning System',
    'A wildlife collar records a path of latitude–longitude points by locking onto satellites. The useful fact is each point’s exact position. Which technology captured those coordinates?',
    ['Geographic Information Systems', 'Remote Sensing', 'Relative Location'],
    'A receiver calculating position from satellites is the Global Positioning System. GIS later plots the path. Remote Sensing would be imagery. Relative Location would be “west of the village.”'),
  q('dat-gps-2', 'data', 'Global Positioning System',
    'Surveyors on a reef use handheld units so a treaty line can be written in coordinates, not “halfway between the two lighthouses.” Which tool is doing the positioning?',
    ['Isoline Map', 'Geographic Information Systems', 'Situation'],
    'Live satellite positioning is GPS. Isolines might later show depth. GIS could store the line. Situation is location relative to other places.'),
  q('dat-gps-3', 'data', 'Global Positioning System',
    'A delivery app says “turn left in 40 meters” because the phone keeps recalculating its coordinates from a satellite constellation. Which system is feeding the live position?',
    ['Geographic Information Systems', 'Cartogram', 'Time-Space Compression'],
    'The live coordinate fix is GPS. GIS is software for stacking layers. A cartogram resizes areas. Time-space compression is the idea that communication shrinks distance.'),
  q('dat-gps-4', 'data', 'Global Positioning System',
    'Two planes cannot both be “near Chicago” safely. Transponders report updating latitude and longitude instead. Which system provides that exact position?',
    ['Relative Location', 'Pattern', 'Cultural Landscape'],
    'Latitude/longitude from satellites is GPS. “Near Chicago” is Relative Location. Pattern is arrangement. Cultural Landscape is the visible human imprint.'),
  q('dat-gps-5', 'data', 'Global Positioning System',
    'A hiker marks a trailhead with a receiver that talks to satellites and reports a precise position. Which system is that?',
    ['Remote Sensing', 'Field Observations', 'Absolute Location'],
    'The satellite positioning system is GPS. Absolute Location is the kind of location it reports, not the technology. Remote Sensing images the surface. Field Observations are watching in person.'),

  q('dat-gis-1', 'data', 'Geographic Information Systems',
    'A county stacks a flood layer, a road network, and census polygons, then asks which blocks are in the floodplain and far from a hospital. The new work is combining layers. Which tool is that?',
    ['Remote Sensing', 'Global Positioning System', 'Dot Distribution Map'],
    'Stacking and querying layers is GIS. Remote Sensing may have made the flood image. GPS may have collected hospital points. A dot map could display the result.'),
  q('dat-gis-2', 'data', 'Geographic Information Systems',
    'Planners test “what if” high-school sites by combining parcel values, bus times, and student addresses. Changing one layer redraws the candidates. Which system makes that overlay possible?',
    ['Field Observations', 'Reference Map', 'Formal Region'],
    'Interactive overlay is GIS. Field Observations might gather inputs. A reference map could show one finished site. A formal region might be an attendance zone.'),
  q('dat-gis-3', 'data', 'Geographic Information Systems',
    'A health department links cholera cases to a piped-water layer and a well layer and finds cases cluster on well blocks. The insight comes from relating datasets collected separately. Which technology did that?',
    ['Remote Sensing', 'Choropleth Map', 'Dependency Model'],
    'Relating spatial layers is GIS. Remote Sensing did not create the case file. A choropleth might show rates later. Dependency Model is a development theory.'),
  q('dat-gis-4', 'data', 'Geographic Information Systems',
    'A student says GPS and this tool are the same thing. The teacher says one drops a pin; the other asks questions of many stacked layers. Which tool is the stacked-layer one?',
    ['Global Positioning System', 'Field Observations', 'Small-Scale Maps'],
    'Stacked-layer analysis is GIS. GPS is the pin. Field Observations are on-site notes. Small-scale maps show large areas with little detail.'),
  q('dat-gis-5', 'data', 'Geographic Information Systems',
    'Layering crime, income, and streetlights on a computer so a city can see which blocks are dark and poor is the stock AP example of which tool?',
    ['Global Positioning System', 'Thematic Map', 'Quinary Sector'],
    'Layered analysis software is GIS. GPS only locates a point. A thematic map is one possible output. Quinary Sector is elite jobs.'),
]
