import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SECTOR_QUESTIONS: VocabQuestion[] = [
  q('sec-pri-1', 'sectors', 'Primary Sector',
    'After the drought, jobs disappear first for people who grow crops and raise animals on the land. Which economic sector is shrinking?',
    ['Secondary Sector', 'Tertiary Sector', 'Informal Sector'],
    'Getting food and animals from the land is Primary. Factories would be Secondary. Shops and hotels would be Tertiary. Informal Sector is about unrecorded work, not what is produced.'),
  q('sec-pri-2', 'sectors', 'Primary Sector',
    'The nickel mine closes, but the hospital and grocery store stay open. Which sector employed the workers who dug ore out of the ground?',
    ['Quaternary Sector', 'Quinary Sector', 'Built Environment'],
    'Extracting ore from Earth is Primary. Quaternary is research and information work. Quinary is top leadership. Built Environment is the physical town, not a job sector.'),
  q('sec-pri-3', 'sectors', 'Primary Sector',
    'The fishing boats return empty, and only later do the canneries shut down. Which sector failed first because it pulls resources directly from nature?',
    ['Secondary Sector', 'Tertiary Sector', 'Commodity Dependence'],
    'Fishing extracts a natural resource, so it is Primary. Canneries that process fish are Secondary. Stores are Tertiary. Commodity Dependence is an export problem, not a sector.'),
  q('sec-pri-4', 'sectors', 'Primary Sector',
    'A wheat field, a copper mine, a fishing boat, and a logging crew all take materials straight from Earth. Which sector includes all four?',
    ['Secondary Sector', 'Land Use', 'Sustainability'],
    'Extracting raw materials from Earth is Primary. Turning logs into boards would be Secondary. Land Use is how land is assigned. Sustainability is whether a resource can last.'),
  q('sec-pri-5', 'sectors', 'Primary Sector',
    'Most workers still make a living by farming crops or mining minerals—not by running factories or serving customers. Which sector dominates?',
    ['Quaternary Sector', 'Quinary Sector', 'Gender Gap'],
    'Farming and mining are Primary. Quaternary is knowledge work. Quinary is top decision-making. Gender Gap is a difference between men and women.'),

  q('sec-sec-1', 'sectors', 'Secondary Sector',
    'Imported aluminum is stamped and painted into phone frames inside a factory. Which sector is this manufacturing work?',
    ['Primary Sector', 'Tertiary Sector', 'Quaternary Sector'],
    'Turning raw metal into a product in a factory is Secondary. Mining the metal would be Primary. Selling phones is Tertiary. Designing software is Quaternary.'),
  q('sec-sec-2', 'sectors', 'Secondary Sector',
    'The city lost jobs at plants that turned steel and glass into cars—not at the mine or the law offices. Which sector collapsed?',
    ['Primary Sector', 'Quinary Sector', 'Formal Sector'],
    'Auto assembly in a plant is Secondary. Iron mining is Primary. Corporate headquarters decisions are Quinary. Formal Sector only means the work was legal and taxed.'),
  q('sec-sec-3', 'sectors', 'Secondary Sector',
    'Workers sew imported fabric into finished shirts for export in a workshop. Which sector adds this manufacturing value?',
    ['Tertiary Sector', 'Quaternary Sector', 'Informal Sector'],
    'Making garments from fabric is Secondary. Selling clothes in a store is Tertiary. Fashion design research is Quaternary. Informal Sector would mean unregistered home sewing.'),
  q('sec-sec-4', 'sectors', 'Secondary Sector',
    'A country that once exported only raw cotton now has thousands of workers in plants that turn it into shirts. Which sector grew?',
    ['Primary Sector', 'Quinary Sector', 'Vernacular Region'],
    'Processing cotton into shirts in a factory is Secondary. Growing cotton is Primary. Quinary is top leadership. A vernacular area is a mental map, not a sector.'),
  q('sec-sec-5', 'sectors', 'Secondary Sector',
    'Logs go into a mill and finished boards come out. The mill turns a raw material into a product. Which sector is this?',
    ['Primary Sector', 'Tertiary Sector', 'Cartographic Scale'],
    'Manufacturing boards from logs is Secondary. Cutting trees is Primary. Selling lumber at a store is Tertiary. Cartographic Scale is a map ratio.'),

  q('sec-ter-1', 'sectors', 'Tertiary Sector',
    'New jobs appear in hotels, buses, restaurants, and shops—not on farms or factory floors. Which sector provides these everyday services?',
    ['Secondary Sector', 'Quaternary Sector', 'Quinary Sector'],
    'Hotels, transport, and retail are Tertiary services. Factories are Secondary. Research labs are Quaternary. Presidents and CEOs are Quinary.'),
  q('sec-ter-2', 'sectors', 'Tertiary Sector',
    'An airport opens and the town hires hotel staff, taxi drivers, and tour guides, while the olive groves stay the same size. Which sector are the new jobs?',
    ['Primary Sector', 'Secondary Sector', 'Cultural Landscape'],
    'Hotels, taxis, and guides sell services to people—that is Tertiary. Olive groves are Primary. A canning plant would be Secondary. Cultural Landscape is the visible human imprint.'),
  q('sec-ter-3', 'sectors', 'Tertiary Sector',
    'A teacher, a nurse, and a truck driver all help people or move things instead of extracting resources or making goods in a factory. Which sector includes them?',
    ['Quaternary Sector', 'Primary Sector', 'Pattern'],
    'Education, health care, and transport services are Tertiary. Quaternary is specialized research. Primary is extraction. Pattern is how things are arranged on a map.'),
  q('sec-ter-4', 'sectors', 'Tertiary Sector',
    'After the port expands, hiring rises in trucking, warehouses, and import shops. Which service sector is growing?',
    ['Primary Sector', 'Quaternary Sector', 'Formal Sector'],
    'Moving and selling goods as a service is Tertiary. Digging ore is Primary. Writing software is Quaternary. Formal Sector only means registered, taxed businesses.'),
  q('sec-ter-5', 'sectors', 'Tertiary Sector',
    'A city bus, a grocery checkout, and a hair salon all provide a service—not a product pulled from Earth or built in a factory. Which sector is this?',
    ['Quaternary Sector', 'Primary Sector', 'Commodity Dependence'],
    'Bus rides, checkout help, and haircuts are everyday Tertiary services. Quaternary is research and information. Primary is extraction. Commodity Dependence is export reliance.'),

  q('sec-qua-1', 'sectors', 'Quaternary Sector',
    'Office towers fill with software engineers and financial analysts who create information and analysis—not hotel stays or factory goods. Which sector is this?',
    ['Tertiary Sector', 'Quinary Sector', 'Secondary Sector'],
    'Research, software, and analysis are Quaternary. Hotels are Tertiary. CEOs are Quinary. Factories are Secondary.'),
  q('sec-qua-2', 'sectors', 'Quaternary Sector',
    'Chemists run drug trials and file patents, while a nearby plant only bottles the medicine. Which sector is the research lab work?',
    ['Secondary Sector', 'Tertiary Sector', 'Quinary Sector'],
    'Research and patents are Quaternary information work. Bottling pills in a plant is Secondary. A clinic visit is Tertiary. The board funding the lab is Quinary.'),
  q('sec-qua-3', 'sectors', 'Quaternary Sector',
    'A data team can work in almost any city because its product is specialized knowledge—not a mine or a storefront. Which sector is this?',
    ['Primary Sector', 'Informal Sector', 'Site'],
    'Knowledge and information work is Quaternary. Primary needs a natural resource on site. Informal Sector is unrecorded work. Site is the physical ground itself.'),
  q('sec-qua-4', 'sectors', 'Quaternary Sector',
    'Routine clerks are replaced by a smaller team of specialists who model financial risk for clients worldwide. Which sector are the remaining jobs?',
    ['Tertiary Sector', 'Primary Sector', 'Human Development Index'],
    'Specialized intellectual and information work is Quaternary. Old clerks did routine Tertiary service. Primary is extraction. HDI is a development score.'),
  q('sec-qua-5', 'sectors', 'Quaternary Sector',
    'One building serves meals to customers; the other writes research software. Which sector is the software lab?',
    ['Tertiary Sector', 'Quinary Sector', 'Literacy Rate'],
    'The software lab is Quaternary. The restaurant is Tertiary. A cabinet secretary would be Quinary. Literacy Rate is a social indicator.'),

  q('sec-qui-1', 'sectors', 'Quinary Sector',
    'A small group of executives decides to close the mill, and thousands of factory jobs disappear. Which sector includes those top decision-makers?',
    ['Quaternary Sector', 'Tertiary Sector', 'Formal Sector'],
    'Presidents, CEOs, and top officials making big calls are Quinary. Analysts who brief them are Quaternary. Factory workers are not the sector asked about. Formal Sector only means legal work.'),
  q('sec-qui-2', 'sectors', 'Quinary Sector',
    'After a hurricane, a president, a central-bank chair, and a grocery-chain CEO set relief funds, interest rates, and food shipments. Which sector are these leaders?',
    ['Quaternary Sector', 'Tertiary Sector', 'Human Environment Interaction'],
    'Top national and corporate leaders are Quinary. Policy analysts are Quaternary. Warehouse staff are Tertiary. Human-environment interaction describes the disaster context, not the job type.'),
  q('sec-qui-3', 'sectors', 'Quinary Sector',
    'A university president and a foundation director choose which city gets a new hospital campus. Architects arrive later. Which sector are the leaders in?',
    ['Quaternary Sector', 'Secondary Sector', 'Functional Region'],
    'Leaders making the final call are Quinary. Architects do Quaternary-style knowledge work. Construction crews are Secondary. A hospital service area would be a functional area.'),
  q('sec-qui-4', 'sectors', 'Quinary Sector',
    'A cabinet and a corporate board decide to move headquarters. The staff who wrote the reports did not make that final choice. Which sector is shown here?',
    ['Quaternary Sector', 'Tertiary Sector', 'World Systems Theory'],
    'Highest-level strategy by top leaders is Quinary. Report writers are Quaternary. Everyday services are Tertiary. World Systems Theory is a development model.'),
  q('sec-qui-5', 'sectors', 'Quinary Sector',
    'Heads of state sign a climate treaty. Scientists wrote the reports, but the signatures change national policy. Which sector includes the signers?',
    ['Quaternary Sector', 'Primary Sector', 'Isoline Map'],
    'Presidents and heads of state signing policy are Quinary. Scientists are Quaternary. Primary is extraction. An isoline map shows lines of equal value.'),
]
