import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_REGION_QUESTIONS: VocabQuestion[] = [
  q(
    'reg-reg-1',
    'regions',
    'Region',
    'A geographer groups “the Sahel,” “the Midwest,” and “Latin America” not because each is a single government, but because each is a chunk of Earth that people treat as having enough internal similarity — or connection — to talk about as a unit. Which concept is the geographer using?',
    ['Place', 'Location', 'Cartographic Scale'],
    'A Region is an area defined by shared traits or connections so it can be studied as a unit. Place is one meaningful location. Location is a position. Cartographic Scale is the map-to-ground ratio, not the act of grouping space.',
  ),
  q(
    'reg-reg-2',
    'regions',
    'Region',
    'News coverage says “the Sun Belt is gaining House seats” and “the Rust Belt is losing factories.” Neither phrase names one city or one official border; each names a multi-place area used to explain a pattern. Which geographic idea makes those phrases possible?',
    ['Site', 'Absolute Location', 'Quinary Sector'],
    'Treating a multi-place area as a meaningful unit is the idea of a Region. Site is local physical character. Absolute Location is coordinates. Quinary Sector is elite decision-making, not a spatial grouping.',
  ),
  q(
    'reg-reg-3',
    'regions',
    'Region',
    'AP Human Geography treats “Europe,” “Southeast Asia,” and “the Corn Belt” as tools for comparison, even though each contains huge internal differences. The point is not that they are perfectly uniform, but that grouping places lets us see patterns we would miss household by household. Which concept is that grouping?',
    ['Pattern', 'Space', 'Small-Scale Maps'],
    'The grouping itself is a Region — a device for organizing spatial comparison. Pattern is the arrangement you might then see. Space is the abstract surface. Small-scale maps can show large regions but are a cartographic choice, not the concept of grouping.',
  ),
  q(
    'reg-for-1',
    'regions',
    'Formal Region',
    'A map of “states where Spanish is an official language,” a map of the Corn Belt by percent of cropland in maize, and a map of Köppen climate type BWh all draw borders where a measurable trait is present. People may disagree about culture, but the membership rule is the same on both sides of the line. Which kind of region are these?',
    ['Functional Region', 'Vernacular Region', 'Relative Location'],
    'A Formal Region is defined by a shared, documentable trait — language status, crop share, climate type. A Functional Region is organized by a node and flows. A Vernacular Region exists in people’s heads (“the South”) without a single official criterion. Relative Location is position compared with other places.',
  ),
  q(
    'reg-for-2',
    'regions',
    'Formal Region',
    'Canada’s province of Quebec can be mapped with a hard legal boundary and a majority-French census result. A trucker’s delivery area radiating from Montreal is a different kind of spatial unit. Which concept fits Quebec as a political-cultural unit with a uniform official criterion?',
    ['Functional Region', 'Vernacular Region', 'Situation'],
    'A province with a legal border and a measurable language majority is a Formal Region. The trucker’s delivery area is Functional (nodal). “The North” as a cultural idea would be Vernacular. Situation is Quebec’s location relative to other places, not its internal uniformity.',
  ),
  q(
    'reg-for-3',
    'regions',
    'Formal Region',
    'The European Union’s Schengen Area can be drawn where a specific legal rule — passport-free movement — applies. That is different from “Southern Europe” as tourists imagine it, and different from the commuter shed of Frankfurt airport. Which regional type is Schengen?',
    ['Vernacular Region', 'Functional Region', 'Sense of Place'],
    'A legally uniform membership rule makes Schengen a Formal Region. “Southern Europe” in the tourist imagination is Vernacular. An airport commuter shed is Functional. Sense of Place is emotional attachment to a location, not a membership rule.',
  ),
  q(
    'reg-fun-1',
    'regions',
    'Functional Region',
    'A newspaper’s circulation, a pizza shop’s delivery radius, and a metro rail system all weaken as you move away from a center. The area exists because of connections to that node, not because everyone inside shares one language or soil type. Which kind of region is this?',
    ['Formal Region', 'Vernacular Region', 'Distance Decay'],
    'A Functional (nodal) Region is organized around a center and the flows that serve it. Formal regions share a trait. Vernacular regions are perceived. Distance Decay helps explain why the newspaper’s sales fall with distance, but the regional type created by those flows is Functional.',
  ),
  q(
    'reg-fun-2',
    'regions',
    'Functional Region',
    'Dallas–Fort Worth International Airport’s passenger and cargo shed includes towns in Oklahoma and Arkansas that do not share Texas laws or a single cultural nickname. Those towns belong to the airport’s region because flights, trucks, and commuters link them to that hub. Which concept is that?',
    ['Formal Region', 'Vernacular Region', 'Absolute Location'],
    'A hinterland defined by links to a hub is a Functional Region. Those towns are not in a formal Texas political unit, and “Texan” as an identity would be Vernacular. Absolute Location would be the airport’s coordinates.',
  ),
  q(
    'reg-fun-3',
    'regions',
    'Functional Region',
    'When a city’s only trauma hospital closes, nearby counties immediately lose a shared emergency system even though their wheat production and local accents have not changed. The region that vanished was defined by service to a node. Which type was it?',
    ['Formal Region', 'Vernacular Region', 'Built Environment'],
    'A hospital service area is a classic Functional Region. Crop belts and accent zones would be Formal if measured, or Vernacular if only imagined. The hospital building is part of the Built Environment, but the region is the service network, not the building.',
  ),
  q(
    'reg-ver-1',
    'regions',
    'Vernacular Region',
    'Americans can point to “the Midwest” or “the South” on a blank map, but they disagree about whether Missouri, Maryland, or Ohio belongs. There is no single official criterion — only a shared mental map. Which kind of region is that?',
    ['Formal Region', 'Functional Region', 'Cartogram'],
    'A Vernacular (perceptual) Region exists because people believe it exists and can sketch it, even when borders disagree. A Formal Region would need one measurable rule. A Functional Region would need a node and flows. A cartogram is a map that resizes area by data.',
  ),
  q(
    'reg-ver-2',
    'regions',
    'Vernacular Region',
    'Tourism ads sell “New England fall” and “the Outback” as if those were official units. Residents argue about the edges, and no census table defines them, yet the names organize identity, marketing, and stereotypes. Which regional type are the ads using?',
    ['Formal Region', 'Functional Region', 'Toponyms'],
    'Marketed, argued-over mental regions are Vernacular. A Formal Region would have a legal or statistical definition. A Functional Region would be something like Boston’s commuter rail shed. Toponyms are the names themselves; the question asks for the type of region the names refer to.',
  ),
  q(
    'reg-ver-3',
    'regions',
    'Vernacular Region',
    'A survey asks Texans to outline “West Texas.” The sketches overlap around Lubbock and Midland but fray near Austin and El Paso. The area is real in people’s heads even though it is not a county and not a single water-district service area. Which concept is that?',
    ['Formal Region', 'Functional Region', 'Pattern'],
    'Overlapping mental maps with fuzzy edges are the signature of a Vernacular Region. A county would be Formal. A water-district service area would be Functional. Pattern would describe how the sketches are arranged, not the kind of region they represent.',
  ),
]
