import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_MAP_QUESTIONS: VocabQuestion[] = [
  q('map-phy-1', 'maps', 'Physical Geography',
    'A researcher studies why mountains form and why deserts are arid, not who inhabits those areas. Which branch of geography is this?',
    ['Human Geography', 'Reference Map', 'Primary Sector'],
    'Natural features and processes are Physical Geography. Human Geography is people. A reference map can show either. Primary Sector is extraction work.'),
  q('map-phy-2', 'maps', 'Physical Geography',
    'Before a port is proposed, engineers measure tides, sediment, and bedrock. Which field answers those questions?',
    ['Human Geography', 'Cultural Landscape', 'Formal Sector'],
    'Tides and bedrock are Physical Geography. Human Geography starts when people occupy the coast. Cultural Landscape is the human imprint. Formal Sector is an economic category.'),
  q('map-phy-3', 'maps', 'Physical Geography',
    'A paper models sea-surface temperature and wind shear. It is not yet asking who can evacuate. Which branch is the paper in?',
    ['Human Geography', 'Remote Sensing', 'Quaternary Sector'],
    'Atmosphere and ocean processes are Physical Geography. Who evacuates is Human Geography. Remote Sensing might supply the data. Quaternary Sector is knowledge work.'),
  q('map-phy-4', 'maps', 'Physical Geography',
    'A question about why monsoon rains arrive in June concerns climate, not language. Which field is this?',
    ['Human Geography', 'Vernacular Region', 'Gini Coefficient'],
    'Climate timing is Physical Geography. Language is Human Geography. A vernacular region is a mental area. Gini is inequality.'),
  q('map-phy-5', 'maps', 'Physical Geography',
    'The class examines why a volcano erupts and why a coastline erodes. Which branch of geography is this?',
    ['Human Geography', 'Thematic Map', 'Possibilism'],
    'Earth’s natural processes are Physical Geography. Human Geography asks how people organize those areas. A thematic map is a display. Possibilism is a theory about choice.'),

  q('map-hum-1', 'maps', 'Human Geography',
    'A researcher asks why cities expand in some areas and why people speak different languages, not why rocks form. Which branch of geography is this?',
    ['Physical Geography', 'Topographic Map', 'Gini Coefficient'],
    'Where and why people organize activities is Human Geography. Rocks are Physical. A topographic map is a tool. Gini is one inequality measure.'),
  q('map-hum-2', 'maps', 'Human Geography',
    'Two towns occupy the same river, yet their religions and commuting differ. The river’s discharge is identical. Which field explains the difference?',
    ['Physical Geography', 'Cartographic Scale', 'Primary Sector'],
    'Religion and commuting are Human Geography. The river’s flow is Physical. Cartographic Scale is a map property. Primary Sector is extraction.'),
  q('map-hum-3', 'maps', 'Human Geography',
    'Why a capital was relocated is not a bedrock question. Which branch studies capitals, migration, and trade?',
    ['Physical Geography', 'Site', 'Small-Scale Maps'],
    'Capitals and politics are Human Geography. Site is one spatial idea used inside it. Physical Geography is nature. Small-scale maps are a map class.'),
  q('map-hum-4', 'maps', 'Human Geography',
    'A paper asks why factories locate near ports and how neighborhoods change as people move in. Which field is this?',
    ['Physical Geography', 'Remote Sensing', 'Formal Sector'],
    'Where and why people do things is Human Geography. Physical Geography is Earth systems. Remote Sensing is a data method. Formal Sector is taxed work.'),
  q('map-hum-5', 'maps', 'Human Geography',
    'Language politics, urban growth, and trade concentrating at a few ports concern people and networks. Which branch is this?',
    ['Physical Geography', 'Isoline Map', 'Life Expectancy'],
    'People and networks are Human Geography. Physical Geography would be currents and climate. An isoline map could display either. Life Expectancy is one social indicator.'),

  q('map-ref-1', 'maps', 'Reference Map',
    'A visitor needs street names, parks, and the city boundary rather than income data. Which type of map is this?',
    ['Thematic Map', 'Quaternary Sector', 'Possibilism'],
    'Finding features is a Reference Map. Showing a variable is thematic. Quaternary Sector is information work. Possibilism is a theory.'),
  q('map-ref-2', 'maps', 'Reference Map',
    'An emergency crew requires creek names, the county line, and the road to the hospital. Which map type do they need?',
    ['Thematic Map', 'Dot Distribution Map', 'Graduated Symbol Map'],
    'Names, lines, and roads are a Reference Map. Poverty shading or dots would be thematic.'),
  q('map-ref-3', 'maps', 'Reference Map',
    'A hiking atlas, a political wall map of African states, and a city street grid are all designed so a user can find features. Which term names these maps?',
    ['Thematic Map', 'Cartogram', 'Choropleth Map'],
    'These are for finding places: Reference Maps. Choropleths and cartograms show a selected data theme.'),
  q('map-ref-4', 'maps', 'Reference Map',
    'A phone’s default map displays streets and labels. Activating last year’s bicycle crashes changes the product. Which type is the original basemap?',
    ['Thematic Map', 'Isoline Map', 'World Scale'],
    'The starting basemap is a Reference Map. Bike crashes would be thematic. Isolines are one thematic form. World Scale is a level of analysis.'),
  q('map-ref-5', 'maps', 'Reference Map',
    'A visitor wants the names of districts in Rome, not a map of income. Which map type is needed?',
    ['Thematic Map', 'Human Development Index', 'Friction of Distance'],
    'Names of districts are a Reference Map. Income would be thematic. HDI is a development index. Friction of Distance is movement cost.'),

  q('map-thm-1', 'maps', 'Thematic Map',
    'A planner already knows the streets and opens a map of childhood asthma rates. Which type of map shows that variable?',
    ['Reference Map', 'Site', 'Quinary Sector'],
    'A map of one variable is Thematic. A street sheet is Reference. Site is local ground. Quinary Sector is elite decisions.'),
  q('map-thm-2', 'maps', 'Thematic Map',
    'A page titled “Percent of adults with a university degree, 2020” will not help a driver reach campus. Which map class is this?',
    ['Reference Map', 'Topographic Map', 'Absolute Location'],
    'A map whose job is a data theme is Thematic. Reference and topographic sheets emphasize location and terrain. Absolute Location is a coordinate.'),
  q('map-thm-3', 'maps', 'Thematic Map',
    'Election colors, an oil-spill track, and a population cartogram all sacrifice street detail to display one topic. Which map class includes all three?',
    ['Reference Map', 'Physical Geography', 'Formal Region'],
    'All three are Thematic. A reference map would privilege streets and names. Physical Geography is a field. A formal region might be what the theme shows.'),
  q('map-thm-4', 'maps', 'Thematic Map',
    'The street atlas is already available. What is needed now is a map of income or language. Which type of map is that?',
    ['Reference Map', 'Field Observations', 'Primary Sector'],
    'A map of one topic is Thematic. A reference map shows location. Field Observations are a data method. Primary Sector is extraction.'),
  q('map-thm-5', 'maps', 'Thematic Map',
    'An atlas page is designed to display one variable rather than help someone find a street. Which term names this map?',
    ['Reference Map', 'Topographic Map', 'National Scale'],
    'Showing a selected variable is a Thematic Map. A topographic sheet is mainly terrain. National Scale is a level of analysis.'),

  q('map-cho-1', 'maps', 'Choropleth Map',
    'Each county is shaded darker as the poverty rate rises, but the counties keep their actual shapes. Which map type uses shaded areas this way?',
    ['Dot Distribution Map', 'Graduated Symbol Map', 'Cartogram'],
    'Shaded areas for a value are a Choropleth Map. Dots are points. Graduated symbols size a circle. A cartogram resizes the counties.'),
  q('map-cho-2', 'maps', 'Choropleth Map',
    'Each state fills with a darker color as unemployment rises; only the color changes. Which map type is this?',
    ['Dot Distribution Map', 'Cartogram', 'Reference Map'],
    'Different shades within areas are a Choropleth Map. Dots use points. A cartogram changes size. A reference map is for finding places.'),
  q('map-cho-3', 'maps', 'Choropleth Map',
    'A student colors whole counties by head count, so empty counties look crowded. The teacher says shade by a percent instead. Which map type is the teacher discussing?',
    ['Graduated Symbol Map', 'Isoline Map', 'Small-Scale Maps'],
    'That shading warning is for Choropleth Maps. Graduated symbols can show totals. Isolines are equal-value lines. Small-scale is a zoom level.'),
  q('map-cho-4', 'maps', 'Choropleth Map',
    'Each municipality is colored according to its official language. Which map type assigns one shade to each bounded unit?',
    ['Dot Distribution Map', 'Isoline Map', 'Graduated Symbol Map'],
    'One shade per official unit is a Choropleth Map. Dots would show speakers as points. Isolines need a continuous field. Graduated symbols size a mark.'),
  q('map-cho-5', 'maps', 'Choropleth Map',
    'Coloring entire countries by raw deaths makes sparsely populated countries look deadly. Which shading technique was used incorrectly?',
    ['Isoline Map', 'Reference Map', 'Topographic Map'],
    'Coloring political units is choropleth technique — misleading for raw counts. Isolines interpolate a surface. Reference and topographic maps are not this shading method.'),

  q('map-dot-1', 'maps', 'Dot Distribution Map',
    'One mark represents every 500 cows, so some states appear densely speckled and others almost empty. Which map type uses repeated points this way?',
    ['Choropleth Map', 'Cartogram', 'Isoline Map'],
    'Repeated point symbols are a Dot Distribution Map. A choropleth would shade whole states. A cartogram would resize states. Isolines connect equal values.'),
  q('map-dot-2', 'maps', 'Dot Distribution Map',
    'Each incident is plotted as a point instead of coloring whole counties. Which map type shows that distribution?',
    ['Choropleth Map', 'Graduated Symbol Map', 'Small-Scale Maps'],
    'One mark per event is a Dot Distribution Map. Choropleth averages the county. A graduated symbol is usually one sized mark. Small-scale is about zoom.'),
  q('map-dot-3', 'maps', 'Dot Distribution Map',
    'Thousands of small marks run along the Nile, while the desert is nearly blank. Which map type reveals that concentration?',
    ['Choropleth Map', 'Cartogram', 'Reference Map'],
    'The speckled Nile is a Dot Distribution Map. A national choropleth would be one color. A cartogram would balloon the country. A reference map emphasizes names.'),
  q('map-dot-4', 'maps', 'Dot Distribution Map',
    'A health office wants to see cases cluster on particular streets, not one average per county. Which map type should they use?',
    ['Choropleth Map', 'Cartographic Scale', 'Formal Region'],
    'Clustered points are a Dot Distribution Map. Choropleth gives a unit average. Cartographic Scale is a ratio. A Formal Region is a type of area.'),
  q('map-dot-5', 'maps', 'Dot Distribution Map',
    'Many same-size marks make dense areas look speckled. Which vocabulary term names this map?',
    ['Choropleth Map', 'Isoline Map', 'Thematic Map'],
    'Same-size marks for concentration are a Dot Distribution Map. Thematic Map is the parent class. Choropleth uses shading. Isolines use lines.'),

  q('map-grd-1', 'maps', 'Graduated Symbol Map',
    'Tokyo receives a large circle and a small town a tiny one, but the country itself is not shaded. Which map type sizes symbols this way?',
    ['Dot Distribution Map', 'Choropleth Map', 'Reference Map'],
    'Symbols sized by a quantity are a Graduated Symbol Map. Dots are equal-sized repeats. Choropleth shades areas. A reference map is for location.'),
  q('map-grd-2', 'maps', 'Graduated Symbol Map',
    'Stronger earthquakes receive larger squares, all drawn at the epicenter. Which map type uses sized symbols for a value at a point?',
    ['Choropleth Map', 'Cartogram', 'Topographic Map'],
    'Sized point symbols are Graduated Symbols. Choropleth needs areal units. A cartogram resizes areas. A topographic map shows terrain.'),
  q('map-grd-3', 'maps', 'Graduated Symbol Map',
    'Each airport gets one disk; busier airports get larger disks, and countries are not colored. Which map type is this?',
    ['Choropleth Map', 'Isoline Map', 'Field Observations'],
    'One sized disk per airport is a Graduated Symbol Map. Country coloring would be choropleth. Isolines imply a continuous surface. Field Observations are a data method.'),
  q('map-grd-4', 'maps', 'Graduated Symbol Map',
    'A major city’s mark is large and a small town’s is small, without filling the country. Which map type is this?',
    ['Cartogram', 'Small-Scale Maps', 'Literacy Rate'],
    'Sized city marks are a Graduated Symbol Map. A cartogram would resize the country. Small-scale is a zoom class. Literacy Rate is an indicator.'),
  q('map-grd-5', 'maps', 'Graduated Symbol Map',
    'Each port has a circle whose size matches container traffic. Which term names this map?',
    ['Choropleth Map', 'Dot Distribution Map', 'Isoline Map'],
    'One symbol sized by a quantity is a Graduated Symbol Map. Choropleth shades the whole unit. Dots repeat same-size marks. Isolines contour a surface.'),

  q('map-iso-1', 'maps', 'Isoline Map',
    'Lines connect every point that shares the same temperature. Which map type uses these equal-value lines?',
    ['Choropleth Map', 'Dot Distribution Map', 'Cartogram'],
    'Lines of equal value are an Isoline Map. Choropleth would fill counties. Dots would mark stations. A cartogram would resize areas.'),
  q('map-iso-2', 'maps', 'Isoline Map',
    'Nested curves show 30, 60, and 90 minutes from a station. Which map type connects equal travel times?',
    ['Graduated Symbol Map', 'Reference Map', 'Formal Region'],
    'Equal-travel-time curves are isolines. Graduated symbols would size stations. A reference map would show tracks. A formal region would be an official zone.'),
  q('map-iso-3', 'maps', 'Isoline Map',
    'A farmer sees a wave of lines for the average last-freeze day across the Midwest. Which map type is this?',
    ['Choropleth Map', 'Dot Distribution Map', 'Thematic Map'],
    'Connecting equal frost dates is an Isoline Map. Thematic Map is the broader class. Choropleth would fill states. Dots would mark stations without connecting them.'),
  q('map-iso-4', 'maps', 'Isoline Map',
    'Temperature and air pressure are shown with connecting lines rather than one color per state. Which map type is this?',
    ['Choropleth Map', 'Dot Distribution Map', 'Gender Gap'],
    'Continuous fields use Isoline Maps. State coloring is choropleth. Dots mark points. Gender Gap is a social difference.'),
  q('map-iso-5', 'maps', 'Isoline Map',
    'A weather chart uses lines of equal value instead of coloring whole counties. Which vocabulary term names this technique?',
    ['Choropleth Map', 'Topographic Map', 'Cartogram'],
    'Weather-style equal-value lines are an Isoline Map. Topographic maps add many other symbols. Choropleth shades political units. A cartogram resizes area.'),

  q('map-topo-1', 'maps', 'Topographic Map',
    'Tight brown lines indicate a steep ridge, and streams and a few buildings are also marked. Which map type shows elevation this way?',
    ['Cartogram', 'Choropleth Map', 'Human Development Index'],
    'Elevation contours plus features are a Topographic Map. A cartogram resizes area by data. Choropleth shades statistical units. HDI is an index.'),
  q('map-topo-2', 'maps', 'Topographic Map',
    'A hiker selects a sheet because the brown lines grow tight on the ridge. Which map type is designed to show landforms and elevation?',
    ['Isoline Map', 'Reference Map', 'Graduated Symbol Map'],
    'Contours for reading terrain are a Topographic Map. Contours are isolines, but “isoline map” alone would also describe a weather chart.'),
  q('map-topo-3', 'maps', 'Topographic Map',
    'A dam team wants 20-foot contours, the floodplain, and existing roads on one sheet. Which map type do they need?',
    ['Choropleth Map', 'Dot Distribution Map', 'World Scale'],
    'Contours plus roads for engineering is a Topographic Map. Income color is choropleth. Dots would not give slope. World Scale is a level of analysis.'),
  q('map-topo-4', 'maps', 'Topographic Map',
    'Does the trail climb 400 feet in half a mile? A world political map will not say. Which detailed elevation map is needed?',
    ['Small-Scale Maps', 'Thematic Map', 'Quaternary Sector'],
    'Detailed elevation is a Topographic Map. Small-scale world maps hide that. Thematic maps show a data theme. Quaternary Sector is information work.'),
  q('map-topo-5', 'maps', 'Topographic Map',
    'Contour lines, spot elevations, streams, and a few buildings make slope readable. Which map type is this?',
    ['Choropleth Map', 'Cartogram', 'Thematic Map'],
    'A contour terrain sheet is a Topographic Map. Choropleths and cartograms are thematic. Calling it only thematic misses that its job is terrain.'),

  q('map-car-1', 'maps', 'Cartogram',
    'India appears huge and Canada tiny because the map is based on population rather than land area. Which map type distorts area this way?',
    ['Choropleth Map', 'Reference Map', 'Formal Region'],
    'Distorting area by a variable is a Cartogram. Choropleth keeps area and changes color. A reference map is for finding places. A Formal Region is a type of area.'),
  q('map-car-2', 'maps', 'Cartogram',
    'Rhode Island becomes large and Montana nearly vanishes because each state’s area now equals its electoral votes. Which map type is this?',
    ['Choropleth Map', 'Graduated Symbol Map', 'Small-Scale Maps'],
    'Resizing units by a data value is a Cartogram. A choropleth keeps land area. Graduated symbols size a mark. Small-scale just means zoomed out.'),
  q('map-car-3', 'maps', 'Cartogram',
    'Empty deserts shrink and industrial countries enlarge because size now matches carbon emissions. Which map type is this?',
    ['Dot Distribution Map', 'Isoline Map', 'Site'],
    'Resizing by emissions is a Cartogram. Dots would speckle the real land. Isolines connect equal values. Site is physical character.'),
  q('map-car-4', 'maps', 'Cartogram',
    'Larger county shapes represent more people, not more land. Which vocabulary term names this map?',
    ['Isoline Map', 'Topographic Map', 'Absolute Location'],
    'Area equal to a data value is a Cartogram. Isolines would contour a surface. Topographic maps show terrain. Absolute Location is a coordinate.'),
  q('map-car-5', 'maps', 'Cartogram',
    'On an ordinary map Canada looks more important than India. A researcher resizes each country so area matches population. Which term applies?',
    ['Choropleth Map', 'Dot Distribution Map', 'Reference Map'],
    'Warping area to match a variable is a Cartogram. Choropleth keeps geographic area. Dots keep area and add marks. A reference map tries to keep shapes.'),

  q('map-csc-1', 'maps', 'Cartographic Scale',
    'One inch represents one mile on the first map and 100 miles on the second. Which concept describes this map-to-Earth relationship?',
    ['Small-Scale Maps', 'Absolute Location', 'World Scale'],
    'Map distance versus Earth distance is Cartographic Scale. Small-scale maps are one category of that property. Absolute Location is a coordinate. World Scale is a social level of analysis.'),
  q('map-csc-2', 'maps', 'Cartographic Scale',
    'One sheet is labeled 1:24,000 and another 1:1,000,000. Which term names those representative fractions?',
    ['Small-Scale Maps', 'Absolute Location', 'Pattern'],
    'The representative fraction is Cartographic Scale. “Small-scale” is one end of that property. Absolute Location is a position. Pattern is an arrangement.'),
  q('map-csc-3', 'maps', 'Cartographic Scale',
    'A wall map of the entire United States is physically large, yet a bicycle-lane width cannot be measured on it. Which concept explains the problem?',
    ['Relative Location', 'Thematic Map', 'Regional Scale'],
    'The map-to-Earth ratio is Cartographic Scale, not paper size. Relative Location is position versus other places. Thematic Map is purpose. Regional Scale is a social zoom.'),
  q('map-csc-4', 'maps', 'Cartographic Scale',
    'A large poster is not automatically a large-scale map; the fraction is what matters. Which vocabulary term is the student confusing?',
    ['Thematic Map', 'Built Environment', 'Remittances'],
    'The fraction, not the paper size, is Cartographic Scale. A thematic map is about data purpose. Built Environment is buildings. Remittances are migrant money.'),
  q('map-csc-5', 'maps', 'Cartographic Scale',
    'Switching from 1:10,000 to 1:250,000 means one centimeter now represents a much longer stretch of Earth. Which concept is being demonstrated?',
    ['Remote Sensing', 'Sense of Place', 'Formal Region'],
    'Changing the representative fraction is Cartographic Scale. Remote Sensing is data collection. Sense of Place is meaning. A Formal Region is a type of area.'),

  q('map-ssm-1', 'maps', 'Small-Scale Maps',
    'A wall map of the entire world shows oceans and country outlines but cannot show a village street. Which map category covers a large area with little detail?',
    ['Topographic Map', 'Isoline Map', 'Literacy Rate'],
    'Little detail over a large area is a Small-Scale Map. Topographic maps are usually detailed. Isolines are a symbol system. Literacy Rate is an indicator.'),
  q('map-ssm-2', 'maps', 'Small-Scale Maps',
    'The classroom world map is a huge poster, yet a single street still will not appear. Which type of map is this?',
    ['Topographic Map', 'Reference Map', 'Cartographic Scale'],
    'A huge area with little detail is a Small-Scale Map. A topographic plat is typically large-scale. It may also be a reference map. Cartographic Scale is the property; this asks for the small-scale category.'),
  q('map-ssm-3', 'maps', 'Small-Scale Maps',
    'To fit all of South Asia on one sheet, most streets must be omitted. Which map class is this?',
    ['Topographic Map', 'Dot Distribution Map', 'Local Scale'],
    'A generalized, large-area sheet is a Small-Scale Map. A topo plat is typically large-scale. Dots are a symbol type. Local Scale is a social zoom.'),
  q('map-ssm-4', 'maps', 'Small-Scale Maps',
    'An airline chart of the whole Earth omits most cities and simplifies the coastlines. Which concept is being demonstrated?',
    ['Choropleth Map', 'Cartogram', 'Field Observations'],
    'Huge area plus heavy generalization is a Small-Scale Map. Choropleth and cartogram are techniques that can appear at any scale. Field Observations are not a map class.'),
  q('map-ssm-5', 'maps', 'Small-Scale Maps',
    'A globe-style world map leaves out most cities and streets. Which vocabulary term names this kind of map?',
    ['Absolute Location', 'Quinary Sector', 'Gender Gap'],
    'The world map is a Small-Scale Map. Absolute Location is a coordinate. Quinary Sector is leadership jobs. Gender Gap is a social difference.'),

  q('map-abs-1', 'maps', 'Absolute Location',
    'A rescue team is given 40.7° N, 74.0° W rather than “near the big city.” Which concept uses these precise coordinates?',
    ['Relative Location', 'Situation', 'Sense of Place'],
    'A coordinate is Absolute Location. “Near the big city” is relative. Situation is connections. Sense of Place is meaning.'),
  q('map-abs-2', 'maps', 'Absolute Location',
    'A ship reports 15.2° N, 23.6° W instead of “west of the storm.” Which term names that exact position?',
    ['Relative Location', 'Place', 'Site'],
    'The exact spot is Absolute Location. Relative Location is compared with other features. Place adds character. Site is physical setting.'),
  q('map-abs-3', 'maps', 'Absolute Location',
    'A court can still identify the same parcel after nearby roads are renamed because it was recorded on a surveyed grid. Which concept is this?',
    ['Relative Location', 'Toponyms', 'Vernacular Region'],
    'A surveyed grid that stays put is Absolute Location. Relative Location would fail when names change. Toponyms are the names. A vernacular region is a mental area.'),
  q('map-abs-4', 'maps', 'Absolute Location',
    'A distress call cannot say only “west of the storm.” Which type of position must it include?',
    ['Relative Location', 'Time-Space Compression', 'Informal Sector'],
    'The exact coordinate is Absolute Location. “West of the storm” is relative. Time-space compression is shrinking travel time. Informal Sector is unrecorded work.'),
  q('map-abs-5', 'maps', 'Absolute Location',
    'Two aircraft cannot both be described as “near Chicago.” Transponders report updating latitude and longitude instead. Which concept is this?',
    ['Relative Location', 'Pattern', 'Cultural Landscape'],
    'Latitude and longitude is Absolute Location. “Near Chicago” is too vague. Pattern is arrangement. Cultural Landscape is the visible human imprint.'),

  q('map-rel-1', 'maps', 'Relative Location',
    'A city is described as sitting at the end of a busy shipping strait rather than by a pair of coordinates. Which concept describes its position compared with other features?',
    ['Absolute Location', 'Space', 'Gini Coefficient'],
    'Position compared with other features is Relative Location. Absolute Location is the exact spot. Space is the geometric surface. Gini is inequality.'),
  q('map-rel-2', 'maps', 'Relative Location',
    'A house is advertised as “15 minutes from downtown and across from the magnet school.” Which concept uses nearby landmarks this way?',
    ['Absolute Location', 'Isoline Map', 'Primary Sector'],
    'Time and landmarks are Relative Location. A coordinate would be absolute. An isoline map might show the 15-minute band. Primary Sector is extraction.'),
  q('map-rel-3', 'maps', 'Relative Location',
    'The town did not move, but a new rail line makes it closer to the capital in travel time. Which concept changed?',
    ['Absolute Location', 'Site', 'Dot Distribution Map'],
    'Travel-time nearness is Relative Location. The coordinate and the ground did not change. A dot map might later show new firms.'),
  q('map-rel-4', 'maps', 'Relative Location',
    '“Chicago lies between the Great Lakes and the Mississippi system.” Which concept is this description?',
    ['Absolute Location', 'Literacy Rate', 'Quaternary Sector'],
    'Between other features is Relative Location. Absolute Location would be the degrees. Literacy Rate is schooling. Quaternary Sector is information work.'),
  q('map-rel-5', 'maps', 'Relative Location',
    'The advantage is stated as “at the outlet of the Strait of Malacca,” not as a pair of degrees. Which concept describes this position versus routes and neighbors?',
    ['Absolute Location', 'Site', 'Cartographic Scale'],
    'Position versus routes and neighbors is Relative Location. The coordinate would be absolute. Site would be harbor depth. Cartographic Scale is a map ratio.'),
]