import { guideMc, type ApHumanGuideQuestion } from './apHumanGuide'

export const APHG_UNIT1_QUESTIONS: ApHumanGuideQuestion[] = [
  guideMc(
    'u1-choropleth-id',
    'maps',
    'The map uses darker shading for higher values of the same statistic in each area. Which map type is shown?',
    [
      'Choropleth map',
      'Dot-density map',
      'Cartogram',
      'Isoline map',
    ],
    0,
    'A choropleth map fills enumeration units (states, counties, census tracts) with a color ramp so darker or more intense colors mean a higher value.',
    'choropleth',
  ),
  guideMc(
    'u1-choropleth-rate',
    'maps',
    'A choropleth of “total number of internet users” by U.S. state will usually look a lot like a population map. What mapping choice would better show how common internet access is?',
    [
      'Map the rate or percent (users per 100 residents) instead of the raw count',
      'Switch to a Mercator projection so states keep true shape',
      'Use a larger map scale so every household is visible',
      'Remove the legend so readers focus on the pattern',
    ],
    0,
    'Raw counts are pulled by population size. Rates, densities, and percents let you compare places that have very different numbers of people.',
  ),
  guideMc(
    'u1-dot-density',
    'maps',
    'On this map, every symbol is the same size and each one stands for the same quantity. Which map type is shown?',
    [
      'Dot-density map',
      'Graduated-symbol map',
      'Choropleth map',
      'Reference map',
    ],
    0,
    'Dot-density maps use many equal-sized dots. Clustering of dots shows where the phenomenon is concentrated; empty space shows where it is rare.',
    'dot-density',
  ),
  guideMc(
    'u1-grad-symbol',
    'maps',
    'Cities A–D are marked with circles whose size changes with the mapped value. Which map type is shown?',
    [
      'Graduated-symbol (proportional-symbol) map',
      'Dot-density map',
      'Isoline map',
      'Cartogram',
    ],
    0,
    'Graduated or proportional symbols keep location and change the size of a marker (usually a circle) to show quantity. City B is the largest value.',
    'graduated-symbol',
  ),
  guideMc(
    'u1-cartogram',
    'maps',
    'The units on this map are stretched or shrunk so their size matches a statistic, not land area. Which map type is shown?',
    [
      'Cartogram',
      'Choropleth map',
      'Topographic map',
      'Plat map',
    ],
    0,
    'A cartogram distorts area on purpose. A unit with more votes, people, or GDP can look huge even if it is small on the ground.',
    'cartogram',
  ),
  guideMc(
    'u1-isoline',
    'maps',
    'The map connects points that share the same value with contour-like lines. Which map type is shown?',
    [
      'Isoline map',
      'Choropleth map',
      'Dot-density map',
      'Flow map',
    ],
    0,
    'Isolines join equal values (elevation, temperature, precipitation). Tight lines mean a steep change; wide spacing means a gradual change.',
    'isoline',
  ),
  guideMc(
    'u1-mercator-distort',
    'maps',
    'On this Mercator map Greenland looks nearly as large as Africa, even though Africa is about 14 times bigger. What does that illustrate?',
    [
      'Area is badly distorted at high latitudes while direction is preserved',
      'The projection is equal-area, so landmasses keep true size',
      'Distance is accurate everywhere, so polar lands look small',
      'Shape is destroyed everywhere, which is why continents look round',
    ],
    0,
    'Mercator preserves local shape and compass direction, which made it useful for sea navigation. To do that it stretches area toward the poles, so Greenland, Canada, and Antarctica look oversized.',
    'mercator-area',
  ),
  guideMc(
    'u1-mercator-use',
    'maps',
    'A ship captain needs a chart on which a constant compass bearing is a straight line. Which projection is designed for that job?',
    [
      'Mercator',
      'Gall-Peters (equal-area)',
      'Orthographic (globe-like view)',
      'Azimuthal equidistant centered on the poles',
    ],
    0,
    'Mercator keeps direction. Equal-area projections (Peters, Mollweide) fix size but warp shape. Polar azimuthal maps are better for polar air routes, not for rhumb-line sailing.',
  ),
  guideMc(
    'u1-cluster',
    'maps',
    'Compare Pattern A and Pattern B. Which statement is correct?',
    [
      'Pattern A is clustered; Pattern B is dispersed',
      'Pattern A is dispersed; Pattern B is clustered',
      'Both patterns are random with no spatial structure',
      'Both patterns show the same density at every location',
    ],
    0,
    'Clustering means objects are packed near each other. Dispersal means they are spread out across the space. Density can still be the same even when the pattern differs.',
    'cluster-disperse',
  ),
  guideMc(
    'u1-relative-distance',
    'maps',
    'Two towns are 40 miles apart, but the trip takes 90 minutes on a winding two-lane road and 35 minutes after a freeway opens. The change is best described as a change in',
    [
      'relative distance (time-distance), not absolute distance',
      'absolute location of both towns',
      'map projection distortion',
      'formal-region boundaries',
    ],
    0,
    'Absolute distance is a measured length (miles, kilometers). Relative distance is friction: time, cost, or effort. Better transport shrinks relative distance even when mileage stays the same.',
  ),
  guideMc(
    'u1-reference-vs-thematic',
    'maps',
    'A highway atlas that shows roads, cities, and borders so you can find your way is mainly a',
    [
      'reference map',
      'thematic map',
      'cartogram',
      'mental map',
    ],
    0,
    'Reference maps emphasize location of features. Thematic maps emphasize a distribution (income, language, election results). Many classroom maps in Unit 1 are thematic.',
  ),
  guideMc(
    'u1-gis-layers',
    'data',
    'A planner stacks roads, land-use parcels, and elevation into one view to see which floodplain lots sit near a highway. Which tool is being used?',
    [
      'Geographic information system (GIS)',
      'A Mercator projection',
      'A vernacular-region sketch',
      'An isoline contour interval',
    ],
    0,
    'GIS stores data as layers you can overlay, query, and analyze. That is different from GPS, which mainly reports a receiver’s coordinates.',
    'gis-layers',
  ),
  guideMc(
    'u1-gis-vs-gps',
    'data',
    'Which statement correctly separates GPS from GIS?',
    [
      'GPS finds a precise location; GIS stores and analyzes spatial layers',
      'GIS finds a precise location; GPS draws choropleth maps',
      'Both only take photographs from aircraft',
      'Both are names for the U.S. Census questionnaire',
    ],
    0,
    'Satellite navigation (GPS and similar systems) answers “where am I?” GIS answers “what is near this, how does it overlap, and what pattern appears?”',
  ),
  guideMc(
    'u1-remote-sensing',
    'data',
    'Geographers track rainforest loss with images captured by satellites that never land on the forest floor. That data-collection method is',
    [
      'remote sensing',
      'a door-to-door census',
      'a travel narrative',
      'participatory mapping in villages only',
    ],
    0,
    'Remote sensing gathers information from a distance—satellites, aircraft, drones. It is fast and repeatable for large areas, but it may miss on-the-ground detail that fieldwork would catch.',
  ),
  guideMc(
    'u1-census',
    'data',
    'Which use of census data is the best example of why governments collect it?',
    [
      'Drawing legislative districts and allocating federal funds by population',
      'Measuring the exact elevation of every hill',
      'Replacing GIS because census tables already include every road',
      'Proving that environmental determinism is true',
    ],
    0,
    'Censuses count people and basic characteristics. In the United States that count is used for House seats, many grant formulas, and a huge amount of social research.',
  ),
  guideMc(
    'u1-fieldwork',
    'data',
    'A student interviews shop owners, sketches the street, and photographs storefronts on one commercial block. Compared with a national census table, this source is',
    [
      'primary, local, and rich in place detail but hard to scale up',
      'more accurate for every county in the country',
      'a form of remote sensing',
      'useless because it is not a map',
    ],
    0,
    'Fieldwork, interviews, and landscape analysis are primary sources at a fine scale. They explain how a place feels and works, but they do not automatically represent the whole country.',
  ),
  guideMc(
    'u1-absolute-loc',
    'spatial',
    'Which of the following is an absolute location?',
    [
      '38.9° N, 77.0° W',
      '“about 20 minutes south of the airport”',
      '“downstream from the steel mill”',
      '“in the Corn Belt”',
    ],
    0,
    'Absolute location is a unique coordinate (or a precise address). Relative location describes a place by its ties to other places.',
  ),
  guideMc(
    'u1-site-situation',
    'spatial',
    'The diagram labels the city’s wet-point confluence as well as arrows to inland markets and ocean trade. Which pair matches those two ideas?',
    [
      'Site is the local physical setting; situation is the city’s connections to other places',
      'Site is the city’s rank in the urban hierarchy; situation is its climate',
      'Site is a vernacular region; situation is a formal region',
      'Site is map scale; situation is projection',
    ],
    0,
    'Site = local characteristics (water, soil, slope, resources). Situation = relative location and linkages (routes, markets, competing cities). A port can have a strong situation even if the site is swampy.',
    'site-situation',
  ),
  guideMc(
    'u1-distance-decay',
    'spatial',
    'The graph shows interaction falling as distance increases. That relationship is called',
    [
      'distance decay',
      'time-space compression',
      'possibilism',
      'a cartogram',
    ],
    0,
    'Distance decay: the farther two places are, the less they usually interact. The curve is not a law of physics—air travel, the internet, and cheap shipping can flatten it.',
    'distance-decay',
  ),
  guideMc(
    'u1-timespace',
    'spatial',
    'Overnight air freight and video calls make a supplier on another continent feel “closer” than a town two hours away by dirt road. Geographers call this shrinking of relative distance',
    [
      'time-space compression',
      'environmental determinism',
      'map-scale enlargement',
      'a formal-region boundary',
    ],
    0,
    'Time-space compression is the idea that better transport and communication reduce the friction of distance. It does not move places on the globe; it changes how long and how costly interaction feels.',
  ),
  guideMc(
    'u1-place',
    'spatial',
    'People describe a downtown plaza as “the heart of the city” because of its monuments, weekend market, and shared memories. That is mainly an example of',
    [
      'sense of place',
      'absolute distance',
      'an equal-area projection',
      'remote sensing',
    ],
    0,
    'Place is location plus meaning. Sense of place is the emotional and cultural attachment people have to a location. Space is more abstract—distance, area, and distribution without that meaning.',
  ),
  guideMc(
    'u1-determinism',
    'environment',
    'A writer claims that a society’s climate “forces” it to be agricultural or industrial and leaves humans no real choice. That claim is an example of',
    [
      'environmental determinism',
      'possibilism',
      'sustainability',
      'time-space compression',
    ],
    0,
    'Environmental determinism argues that the physical environment dictates culture and development. It is largely rejected because it oversimplifies history and has been used to justify racist rankings of places.',
  ),
  guideMc(
    'u1-possibilism',
    'environment',
    'Farmers in a dry valley use drip irrigation and drought-tolerant crops instead of giving up on agriculture. This is the best illustration of',
    [
      'possibilism',
      'environmental determinism',
      'a Mercator distortion',
      'a functional region with no node',
    ],
    0,
    'Possibilism says the environment sets constraints, but people choose technologies, crops, and institutions that open different paths. Culture and decisions matter.',
  ),
  guideMc(
    'u1-sustainability',
    'environment',
    'A city caps groundwater pumping so aquifers can recharge for the next generation, even if that slows housing growth this decade. The policy is aiming at',
    [
      'sustainability (meeting present needs without wrecking future options)',
      'distance decay',
      'vernacular-region identity',
      'equal-area map design',
    ],
    0,
    'Sustainability balances environment, economy, and society over the long run. Natural resources and land-use choices sit at the center of Unit 1’s human–environment questions.',
  ),
  guideMc(
    'u1-nested-scale',
    'scale',
    'The diagram stacks local inside regional inside national inside global. Why does AP Human Geography care about that nesting?',
    [
      'The same pattern can look clustered, mixed, or even reversed depending on the scale you choose',
      'Only the global scale is valid for geographic research',
      'Local scale always produces the same conclusion as national scale',
      'Scale is another word for map projection',
    ],
    0,
    'Scale of analysis is the level at which data are aggregated. A county map, a state map, and a world map of the same topic can tell different stories.',
    'scale-nested',
  ),
  guideMc(
    'u1-scale-misleading',
    'scale',
    'A national choropleth shows high average income, but several inner-city census tracts on a local map are very poor. The best conclusion is that',
    [
      'national averages can hide local variation, so scale of analysis matters',
      'the local map must be wrong because the national map is official',
      'choropleth maps cannot be drawn at more than one scale',
      'income is not a geographic topic',
    ],
    0,
    'This is the classic Unit 1 trap. Always ask: at what scale was the data grouped? A country can look “rich” while neighborhoods inside it are not.',
  ),
  guideMc(
    'u1-local-scale',
    'scale',
    'A map of one city’s neighborhoods, each shaded by percent renting, is operating at which scale of analysis?',
    [
      'Local (or urban/neighborhood) scale',
      'Global scale',
      'Continental scale',
      'World-systems scale only',
    ],
    0,
    'Neighborhood or census-tract maps are local. State maps are regional/national depending on the country. A map of all countries is global. Match the question to the units on the map.',
  ),
  guideMc(
    'u1-formal',
    'regions',
    'The Corn Belt is mapped where a high share of farmland grows corn. That region is best classified as',
    [
      'formal (uniform), because places share a measurable trait',
      'functional, because it has a single downtown node',
      'vernacular, because nobody can measure corn',
      'not a region, because regions cannot overlap crops',
    ],
    0,
    'Formal regions are defined by one or more shared characteristics (language, climate, crop, political border). The trait can fade at the edges, but the idea is uniformity.',
  ),
  guideMc(
    'u1-functional',
    'regions',
    'A metropolitan area is drawn from a central city plus the surrounding counties whose workers commute in. That is a',
    [
      'functional (nodal) region',
      'formal region based on a single crop',
      'vernacular region with no data',
      'map projection, not a region',
    ],
    0,
    'Functional regions are organized around a node: a city, a TV station, a port, a pizza-delivery zone. The surrounding hinterland is tied to that node by flows.',
  ),
  guideMc(
    'u1-vernacular',
    'regions',
    'People argue about whether a town is “in the Midwest” or “in the South,” and no official line settles it. That kind of region is',
    [
      'vernacular (perceptual)',
      'formal and legally surveyed',
      'functional with a single bus hub',
      'not used in human geography',
    ],
    0,
    'Vernacular or perceptual regions live in people’s minds (“the South,” “Silicon Valley,” “upstate”). Boundaries are fuzzy, contested, and based on identity more than a single statistic.',
  ),
  guideMc(
    'u1-three-regions-fig',
    'regions',
    'Which map in the diagram is the functional region?',
    [
      'Map 2, because activity is organized around a node with links',
      'Map 1, because the whole area is one solid color',
      'Map 3, because the outline is dashed and fuzzy',
      'None of them, because regions cannot be drawn',
    ],
    0,
    'Map 1 is formal (shared trait). Map 2 is functional (node and connections). Map 3 is vernacular (a mental, fuzzy outline).',
    'three-regions',
  ),
  guideMc(
    'u1-boundaries',
    'regions',
    'Why can regional boundaries be hard to draw even when the idea of the region is useful?',
    [
      'Traits fade gradually, and different definitions overlap or conflict',
      'Regions are only allowed on Mercator maps',
      'Every region must match a country’s borders exactly',
      'GIS cannot store more than one region at a time',
    ],
    0,
    'Languages, religions, and “the Midwest” do not stop at a sharp fence. Geographers still use regions because they organize the world; they just treat edges as zones, not laser lines.',
  ),
]
