import { mc, multi, type ApHumanPracticeQuestion } from './apHumanStudy'

const D = 'data' as const

export const DATA_QUESTIONS: ApHumanPracticeQuestion[] = [
  mc('d1', D, 'Geographic data may be gathered in the field by', [
    'satellites only',
    'organizations or by individuals',
    'core countries only',
    'cartograms only',
  ], 1, '1.2.1: data may be gathered in the field by organizations or by individuals.'),
  mc('d2', D, 'Fieldwork / field observations means', [
    'only downloading a GIS layer',
    'visiting a location and recording information there',
    'drawing a Mercator map',
    'counting GDP in an office',
  ], 1, 'Fieldwork is visiting a place and recording information there.'),
  multi('d3', D, 'Examples of fieldwork listed in the notes include', [
    'written accounts',
    'travel narratives',
    'media reports',
    'Mercator projection math',
  ], [0, 1, 2], 'Fieldwork examples include written accounts, travel narratives, and media reports.'),
  multi('d4', D, 'Spatial information can come from written accounts in the form of', [
    'field observations',
    'media reports',
    'travel narratives',
    'map projections that never distort',
  ], [0, 1, 2], '1.2.3 includes field observations, media reports, and travel narratives.'),
  multi('d5', D, 'Which of these are also listed as sources of spatial information?', [
    'policy documents',
    'personal interviews',
    'landscape analysis',
    'SADD distortion letters',
  ], [0, 1, 2], 'Policy documents, personal interviews, and landscape analysis are listed in 1.2.3.'),
  mc('d6', D, 'Photographic interpretation is listed as a way to get', [
    'GNI per capita',
    'spatial information',
    'absolute direction only',
    'quinary sector jobs',
  ], 1, '1.2.3 includes photographic interpretation as a source of spatial information.'),
  multi('d7', D, 'Geospatial technologies in the notes include', [
    'geographic information systems (GIS)',
    'satellite navigation systems',
    'remote sensing',
    'the Gini coefficient',
  ], [0, 1, 2], 'GIS, satellite navigation, remote sensing, and online mapping/visualization are the geospatial technologies.'),
  mc('d8', D, 'Online mapping and visualization is grouped with', [
    'primary economic activities',
    'geospatial technologies',
    'the Brandt Line',
    'absolute direction only',
  ], 1, '1.2.2 includes online mapping and visualization with GIS, GPS, and remote sensing.'),
  mc('d9', D, 'Geospatial technologies are used by businesses, organizations, individuals, and government agencies to', [
    'avoid all decision making',
    'make decisions',
    'replace the census forever',
    'end map distortion',
  ], 1, 'They are used to make decisions.'),
  mc('d10', D, 'The U.S. Census is an example of', [
    'a map projection',
    'fieldwork by the U.S. government',
    'the quinary sector only',
    'Gall-Peters',
  ], 1, 'The census is fieldwork by the U.S. government.'),
  mc('d11', D, 'The U.S. Census is mandated by the Constitution', [
    'every year',
    'every 5 years',
    'every 10 years',
    'only when a new state is added',
  ], 2, 'It is mandated every 10 years.'),
  multi('d12', D, 'Census data is used for', [
    'representative districts — voting and democracy',
    'distribution of public funding',
    'personal, government, and business decision making',
    'choosing a Mercator vs Robinson map',
  ], [0, 1, 2], 'Districts, public funding, and decision making are the “point” of the census in the notes.'),
  multi('d13', D, 'Public funding distributed using census data includes money for', [
    'schools and roads',
    'law enforcement and fire department',
    'highways and infrastructure',
    'SADD letters on maps',
  ], [0, 1, 2], 'Those are the funding examples listed.'),
  mc('d14', D, 'Federal spending is moved to places with', [
    'fewer people on purpose',
    'more districts and people',
    'only primary-sector jobs',
    'no GIS data',
  ], 1, 'Spending follows places with more districts and people.'),
  mc('d15', D, 'Each U.S. congressional district has about how many people (2020 census note)?', [
    '76,000',
    '761,169',
    '3.3 million',
    '435',
  ], 1, 'About 761,169 people per district based on the 2020 census.'),
  mc('d16', D, 'The total number of U.S. congressional districts is', [
    '50',
    '100',
    '435',
    '761,169',
  ], 2, 'There are 435 congressional districts.'),
  mc('d17', D, 'The notes give the total U.S. population as roughly', [
    '33 million',
    '330 million',
    '761 million',
    '3.3 billion',
  ], 1, 'Roughly 330 million.'),
  mc('d18', D, 'GIS is a', [
    'satellite that only gives driving directions',
    'computer system/software that stores, analyzes, and displays information from multiple digital maps or data sets',
    'paper atlas only',
    'type of choropleth color',
  ], 1, 'GIS stores, analyzes, and displays layered digital map/data sets.'),
  mc('d19', D, 'GIS uses', [
    'thematic and physical layers',
    'only one handwritten map',
    'no data at all',
    'only verbal directions',
  ], 0, 'GIS can use thematic and physical layers.'),
  multi('d20', D, 'GIS could be used for', [
    'analysis of crime data',
    'effects of pollution',
    'urban planning',
    'replacing all cardinal directions',
  ], [0, 1, 2], 'Crime, pollution, and urban planning are the GIS use examples.'),
  mc('d21', D, 'GPS / satellite navigation systems work because', [
    'cartographers draw every street by hand each day',
    'satellites orbit the Earth and communicate locational information to GPS receivers',
    'the census happens every 10 years',
    'isolines connect equal temperatures',
  ], 1, 'Orbiting satellites send locational information to receivers.'),
  mc('d22', D, 'GPS provides', [
    'relative location only, like “near the store”',
    'absolute location',
    'Gini coefficients',
    'HDI scores',
  ], 1, 'GPS gives absolute location.'),
  multi('d23', D, 'GPS navigation is used for', [
    'ships',
    'cars',
    'aircraft',
    'measuring GII',
  ], [0, 1, 2], 'Navigation examples: ships, cars, aircraft.'),
  mc('d24', D, 'Aerial photography is', [
    'any selfie on the ground',
    'professional images captured from planes or drones',
    'a census interview',
    'a cartogram',
  ], 1, 'Aerial photography = professional images from planes or drones.'),
  mc('d25', D, 'Remote sensing is', [
    'knocking on doors for the census',
    'the use of cameras or other sensors mounted on aircraft or satellites that orbit the Earth above the atmosphere to collect digital images of the Earth’s surface',
    'only a paper road map',
    'interviewing one person',
  ], 1, 'Remote sensing collects digital images from aircraft/satellites above the atmosphere.'),
  multi('d26', D, 'Examples of remote sensing in the notes are', [
    'monitoring environmental changes',
    'weather',
    'counting votes by hand only',
    'drawing political capitals',
  ], [0, 1], 'Environmental change and weather are the remote-sensing examples.'),
  mc('d27', D, 'Amnesty International used remote sensing / satellite imagery to study', [
    'U.S. Interstate Highways',
    'North Korean political prison camps',
    'Amazon Prime warehouses only',
    'Robinson projections',
  ], 1, 'Satellite imagery was used because investigators could not access North Korea.'),
  mc('d28', D, 'The North Korea remote-sensing example was used because authorities were unwilling to', [
    'print choropleth maps',
    'allow human rights investigators access',
    'use GPS in cars',
    'hold a census',
  ], 1, 'Remote sensing circumvented lack of access for investigators.'),
  mc('d29', D, 'GIS vs GPS: GIS is best described as', [
    'satellites giving a receiver its absolute location',
    'geographical data layered to help make a decision for businesses, government, or people',
    'a type of isoline',
    'cardinal directions',
  ], 1, 'GIS layers geographical data for decisions.'),
  mc('d30', D, 'GIS vs GPS: GPS is best described as using satellite navigation to', [
    'layer pollution and crime maps for urban planning',
    'provide location and data',
    'measure HDI',
    'draw a Gall-Peters map',
  ], 1, 'GPS uses satellite navigation to provide location and data.'),
  mc('d31', D, 'Geospatial and geographical data, including census data and satellite imagery, are used', [
    'only in AP Human class',
    'at all scales for personal, business and organizational, and governmental decision-making',
    'only by cartographers in 1569',
    'only to pick map colors',
  ], 1, 'That is essential knowledge 1.3.1.'),
  mc('d32', D, 'Which is the best match?', [
    'GIS = layered computer maps/data; GPS = satellite absolute location',
    'GIS = only paper maps; GPS = only interviews',
    'GIS = fertility rate; GPS = Gini',
    'GIS and GPS are the same software',
  ], 0, 'GIS analyzes/displays layered data; GPS gives locational information from satellites.'),
  mc('d33', D, 'Photographs collected while visiting a place are an example of', [
    'a map projection disadvantage',
    'fieldwork / field observations',
    'the informal economy',
    'Wallerstein’s core',
  ], 1, 'Photographs are listed as a fieldwork example.'),
  mc('d34', D, 'Landscape analysis is listed as', [
    'a way to gather spatial information',
    'a type of map projection',
    'a quinary job title',
    'an isoline',
  ], 0, 'Landscape analysis is a listed source of spatial information.'),
]
