import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_DATA_QUESTIONS: VocabQuestion[] = [
  q('dat-fld-1', 'data', 'Field Observations',
    'A researcher stands at bus stations, counts riders, and interviews passengers to learn why people switched routes. Satellites can show the stations but not the reason for the change. Which data method is this?',
    ['Remote Sensing', 'Geographic Information Systems', 'Global Positioning System'],
    'On-site counting and interviewing is Field Observations. Remote Sensing is imagery from above. GIS later stacks the counts. GPS only records coordinates.'),
  q('dat-fld-2', 'data', 'Field Observations',
    'A geographer walks a market, sketches shop signs, and asks owners why they moved. Census tables only say “retail.” Which concept is being demonstrated?',
    ['Remote Sensing', 'Choropleth Map', 'Cartographic Scale'],
    'Walking and interviewing is Field Observations. Remote Sensing is distant imagery. A choropleth is a shaded-area map. Cartographic Scale is the map-to-Earth ratio.'),
  q('dat-fld-3', 'data', 'Field Observations',
    'After a flood, teams mark high-water stains and photograph walkways that official maps omit. They are verifying what a cloudy satellite image might miss. Which term applies?',
    ['Remote Sensing', 'Isoline Map', 'World Systems Theory'],
    'On-the-ground marks and photos are Field Observations used as ground truth. Remote Sensing is the satellite layer. Isolines might later show water depth. World Systems Theory is a development model.'),
  q('dat-fld-4', 'data', 'Field Observations',
    'A planner counts cars at an intersection and interviews shop owners about parking. No satellite image can answer those questions. Which vocabulary concept explains this method?',
    ['Remote Sensing', 'Thematic Map', 'Quaternary Sector'],
    'Going to the location and recording what happens there is Field Observations. Remote Sensing never requires standing there. A thematic map displays a variable. Quaternary Sector is information employment.'),
  q('dat-fld-5', 'data', 'Field Observations',
    'A student claims images from above have replaced all on-the-ground work. Interviews and street counts still answer questions those images cannot. Which method is the student underestimating?',
    ['Global Positioning System', 'Reference Map', 'Formal Sector'],
    'Interviews and street counts are Field Observations. GPS is a coordinate. A reference map shows location. Formal Sector is taxed work.'),

  q('dat-rs-1', 'data', 'Remote Sensing',
    'Scientists compare satellite images from 1985 and 2020 to measure forest loss without visiting most of those forests. Which method is this?',
    ['Field Observations', 'Global Positioning System', 'Geographic Information Systems'],
    'Images of Earth’s surface from a distance are Remote Sensing. Field Observations require being there. GPS is a coordinate. GIS may display the classified images later.'),
  q('dat-rs-2', 'data', 'Remote Sensing',
    'During a drought, agencies estimate dying pasture from aircraft and satellite vegetation images because ground teams cannot cover the belt in a week. Which concept is being demonstrated?',
    ['Field Observations', 'Reference Map', 'Quaternary Sector'],
    'Aircraft and satellite sensors are Remote Sensing. Field teams would be Field Observations. A reference map shows names and roads. Quaternary Sector is the analysts’ job type, not the method.'),
  q('dat-rs-3', 'data', 'Remote Sensing',
    'A city flies a plane with sensors to measure rooftop size for solar panels instead of climbing every building. Which term applies?',
    ['Geographic Information Systems', 'Field Observations', 'Topographic Map'],
    'Sensors on a plane are Remote Sensing. GIS is how the city analyzes the data. Climbing roofs is Field Observations. A topographic map is a finished contour sheet.'),
  q('dat-rs-4', 'data', 'Remote Sensing',
    'Weather agencies watch a hurricane hour by hour with images taken from satellites, not by standing in the storm. Which AP Human Geography term best applies?',
    ['Global Positioning System', 'Field Observations', 'Dot Distribution Map'],
    'Long-distance images of Earth are Remote Sensing. GPS reports a receiver’s coordinates. Field Observations are on the ground. A dot map is a symbol type.'),
  q('dat-rs-5', 'data', 'Remote Sensing',
    'To measure how much Arctic ice melted over twenty years, scientists compare images taken from above, not a single interview. Which method produced the images?',
    ['Global Positioning System', 'Literacy Rate', 'Vernacular Region'],
    'Repeat images from above are Remote Sensing. A GPS pin is one coordinate. Literacy Rate is schooling. A vernacular region is a perceived area.'),

  q('dat-gps-1', 'data', 'Global Positioning System',
    'A hiker’s device locks onto satellites and reports an exact position on Earth. Which technology is being used?',
    ['Geographic Information Systems', 'Remote Sensing', 'Relative Location'],
    'A receiver calculating position from satellites is the Global Positioning System. GIS later plots the path. Remote Sensing would be imagery. Relative Location would be “west of the village.”'),
  q('dat-gps-2', 'data', 'Global Positioning System',
    'Surveyors on a reef use handheld units so a treaty line can be written in coordinates, not “halfway between the two lighthouses.” Which concept is being demonstrated?',
    ['Isoline Map', 'Geographic Information Systems', 'Situation'],
    'Live satellite positioning is GPS. Isolines might later show depth. GIS could store the line. Situation is location relative to other places.'),
  q('dat-gps-3', 'data', 'Global Positioning System',
    'A delivery application says “turn left in 40 meters” because the telephone keeps recalculating its coordinates from a satellite constellation. Which term applies?',
    ['Geographic Information Systems', 'Cartogram', 'Time-Space Compression'],
    'The live coordinate fix is GPS. GIS is software for stacking layers. A cartogram resizes areas. Time-space compression is the idea that communication shrinks distance.'),
  q('dat-gps-4', 'data', 'Global Positioning System',
    'Two aircraft cannot both be “near Chicago” safely. Transponders report updating latitude and longitude instead. Which system provides those coordinates?',
    ['Relative Location', 'Pattern', 'Cultural Landscape'],
    'Latitude and longitude from satellites is GPS. “Near Chicago” is Relative Location. Pattern is arrangement. Cultural Landscape is the visible human imprint.'),
  q('dat-gps-5', 'data', 'Global Positioning System',
    'A wildlife collar records a path of latitude–longitude points by locking onto satellites. The useful fact is each point’s exact position. Which system collected those points?',
    ['Geographic Information Systems', 'Remote Sensing', 'Absolute Location'],
    'A receiver calculating position from satellites is GPS. GIS later plots the path. Remote Sensing would be imagery. Absolute Location is the kind of location it reports, not the technology.'),

  q('dat-gis-1', 'data', 'Geographic Information Systems',
    'A county stacks flood, road, and census layers on a computer to find which neighborhoods are at risk and far from a hospital. Which system is this?',
    ['Remote Sensing', 'Global Positioning System', 'Dot Distribution Map'],
    'Collecting, storing, analyzing, and displaying stacked geographic layers is GIS. Remote Sensing may have made the flood image. GPS may have collected hospital points. A dot map could display the result.'),
  q('dat-gis-2', 'data', 'Geographic Information Systems',
    'Planners test alternative high-school sites by combining parcel values, bus times, and student addresses. Changing one layer redraws the candidates. Which concept is being demonstrated?',
    ['Field Observations', 'Reference Map', 'Formal Region'],
    'Interactive overlay and analysis is GIS. Field Observations might gather inputs. A reference map could show one finished site. A formal region might be an attendance zone.'),
  q('dat-gis-3', 'data', 'Geographic Information Systems',
    'A health department links cholera cases to a piped-water layer and a well layer and finds cases cluster on well blocks. The insight comes from relating datasets collected separately. Which term applies?',
    ['Remote Sensing', 'Choropleth Map', 'Dependency Model'],
    'Relating spatial layers is GIS. Remote Sensing did not create the case file. A choropleth might show rates later. Dependency Model is a development theory.'),
  q('dat-gis-4', 'data', 'Geographic Information Systems',
    'A student drops a pin on a phone. The teacher wants software that can stack flood, road, and census layers and ask which blocks are at risk. Which system is the teacher describing?',
    ['Global Positioning System', 'Field Observations', 'Small-Scale Maps'],
    'Stacked-layer analysis is GIS. GPS is the pin. Field Observations are on-site notes. Small-scale maps show large areas with little detail.'),
  q('dat-gis-5', 'data', 'Geographic Information Systems',
    'A city stacks crime, income, and streetlight layers on a computer to see which dark blocks are also low-income. Which AP Human Geography term best applies?',
    ['Global Positioning System', 'Thematic Map', 'Quinary Sector'],
    'Layered analysis software is GIS. GPS only locates a point. A thematic map is one possible output. Quinary Sector is elite jobs.'),
]
