import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SCALE_QUESTIONS: VocabQuestion[] = [
  q(
    'sca-glo-1',
    'scale',
    'Global Scale',
    'A climate paper treats greenhouse-gas accumulation as one planetary process: emissions anywhere alter the same atmosphere, so the unit of analysis is Earth as a single system, not a ranked list of countries. Which scale of analysis is that?',
    ['World Scale', 'National Scale', 'Regional Scale'],
    'Global Scale analyzes a phenomenon as one worldwide system. World Scale would compare countries or places across the planet (a world map of emissions per state). National Scale is one country. Regional Scale is a multi-place subset.',
  ),
  q(
    'sca-glo-2',
    'scale',
    'Global Scale',
    'A pandemic model assumes a virus circulating in one interconnected human population, with travel linking outbreaks into a single wave rather than 200 separate national epidemics. The researcher is not first asking which country ranks highest. Which scale is the model using?',
    ['World Scale', 'Local Scale', 'Formal Region'],
    'Treating humanity as one linked system is Global Scale. A World Scale approach would map and compare national case rates. Local Scale would be one city. A Formal Region is a type of area, not this level of analysis.',
  ),
  q(
    'sca-glo-3',
    'scale',
    'Global Scale',
    'Wallerstein-style research asks how one capitalist world-economy has operated since the 1500s. The object is the whole system of core and periphery, not “France versus Mali” as two isolated cases. Which scale of analysis matches that object?',
    ['National Scale', 'Local Scale', 'Cartographic Scale'],
    'The object is the planet as one economic system — Global Scale. Comparing France and Mali as cases would be closer to World or National Scale. Local Scale is a city or neighborhood. Cartographic Scale is the map’s representative fraction, not the social scale of analysis.',
  ),
  q(
    'sca-wor-1',
    'scale',
    'World Scale',
    'An atlas page shows literacy for every UN member, colored so a reader can compare Chad, Chile, and China on one frame. The phenomenon is not treated as a single planetary number; it is a country-by-country pattern across the whole Earth. Which scale of analysis is the atlas using?',
    ['Global Scale', 'Regional Scale', 'National Scale'],
    'World Scale compares places across the entire planet. Global Scale would collapse the planet into one system or one figure. Regional Scale would be one world region, such as Sub-Saharan Africa. National Scale would be literacy inside one country only.',
  ),
  q(
    'sca-wor-2',
    'scale',
    'World Scale',
    'A researcher ranks 190 countries by female parliamentary share to see whether a gap is widespread or concentrated. The question is about variation among states worldwide, not about Earth as one political body. Which scale is that ranking?',
    ['Global Scale', 'Local Scale', 'Vernacular Region'],
    'A worldwide country ranking is World Scale analysis. Global Scale would treat the planet as one unit (“world parliament share”). Local Scale is a city council. A Vernacular Region is a perceived area, not a level of comparison.',
  ),
  q(
    'sca-wor-3',
    'scale',
    'World Scale',
    'Shipping data are mapped so every coastal state’s container throughput can be seen at once, revealing a few giant hubs and many tiny ports. The map’s purpose is cross-national comparison over the whole Earth, not a single global total. Which scale is that?',
    ['Global Scale', 'Regional Scale', 'Functional Region'],
    'Seeing every country’s ports on one comparative frame is World Scale. A Global Scale figure would be total world TEUs. Regional Scale would be, say, only East Asian ports. A Functional Region might describe one hub’s hinterland after you zoom in.',
  ),
  q(
    'sca-nat-1',
    'scale',
    'National Scale',
    'India’s 2011 census is used to compute one female labor-force rate for the Republic of India, which is then compared with Bangladesh’s national rate. District gaps inside India are ignored for this particular chart. Which scale is the chart using?',
    ['Regional Scale', 'Local Scale', 'World Scale'],
    'One statistic for a whole country is National Scale. Regional Scale would be an Indian state or a multi-state belt. Local Scale would be a district or city. World Scale would display many countries at once, not just the India–Bangladesh pair as national totals.',
  ),
  q(
    'sca-nat-2',
    'scale',
    'National Scale',
    'A journalist writes that “France is secular” because national law limits religious symbols in public schools. The claim treats the state as the unit, even though Marseille neighborhoods look different from rural Brittany. Which scale is the journalist using?',
    ['Local Scale', 'Regional Scale', 'Global Scale'],
    'The unit is the country and its law — National Scale. Local Scale would be those Marseille neighborhoods. Regional Scale would be Brittany as a unit. Global Scale would be a worldwide secularization process.',
  ),
  q(
    'sca-nat-3',
    'scale',
    'National Scale',
    'GNI per capita is almost always published as a single number for Japan, Nigeria, or Brazil so governments can be ranked. That number hides Amazon versus São Paulo, but it is still the standard way to talk about a country’s development level. Which scale is that number?',
    ['Local Scale', 'Regional Scale', 'Cartographic Scale'],
    'A country-level development figure is National Scale. Local and Regional scales would split Brazil. Cartographic Scale is how zoomed-in the map is, not the social unit being measured.',
  ),
  q(
    'sca-reg-1',
    'scale',
    'Regional Scale',
    'A paper on U.S. opioid deaths compares Appalachia, New England, and the Southwest as multi-state belts, not as 3,000 counties and not as one U.S. average. Which scale of analysis is that?',
    ['National Scale', 'Local Scale', 'Global Scale'],
    'Multi-state belts are Regional Scale — above local places, below the whole country. National Scale would be one U.S. rate. Local Scale would be a county. Global Scale would be the planet.',
  ),
  q(
    'sca-reg-2',
    'scale',
    'Regional Scale',
    'China’s development looks different if you compare the coastal manufacturing belt with the western interior instead of quoting one national GDP. The analyst is using large sub-national chunks that share economic position. Which scale is that?',
    ['National Scale', 'World Scale', 'Site'],
    'Coast versus interior as large sub-national units is Regional Scale. National Scale would be all of China as one number. World Scale would compare China with other countries. Site is the physical character of one place.',
  ),
  q(
    'sca-reg-3',
    'scale',
    'Regional Scale',
    'The European Union publishes cohesion funds for “southern Italy” and “eastern Poland” as NUTS-2 statistical areas that group many communes but are smaller than the whole member state. Which scale are those funding units?',
    ['Local Scale', 'National Scale', 'Formal Region'],
    'NUTS-2 blocks are Regional Scale analysis units. Local Scale would be a commune. National Scale would be Italy or Poland as a whole. They may also be formal statistical regions, but the question asks for the scale of analysis, not the region type.',
  ),
  q(
    'sca-loc-1',
    'scale',
    'Local Scale',
    'A zoning fight in Brooklyn is about one neighborhood’s rent, noise, and school seats. Citywide and national housing bills exist, but this map is drawn block by block. Which scale of analysis is the fight using?',
    ['Regional Scale', 'National Scale', 'World Scale'],
    'Block- and neighborhood-level analysis is Local Scale. Regional would be a multi-borough or multi-state belt. National would be U.S. housing policy as one story. World Scale would compare cities worldwide.',
  ),
  q(
    'sca-loc-2',
    'scale',
    'Local Scale',
    'Lagos looks “wealthy” in a country ranking, but a researcher maps one informal settlement’s tap water and one gated estate’s private boreholes and finds opposite outcomes on the same island. Which scale revealed that contrast?',
    ['National Scale', 'Global Scale', 'Vernacular Region'],
    'Comparing neighborhoods inside one city is Local Scale. National Scale is why Lagos disappeared into Nigeria’s average. Global Scale would be a worldwide water statistic. A Vernacular Region is a perceived area, not this zoom level.',
  ),
  q(
    'sca-loc-3',
    'scale',
    'Local Scale',
    'After a chemical spill, investigators test wells on three streets and interview the families who use them. A state-level cancer rate would hide whether those streets are the problem. Which scale matches the investigation?',
    ['Regional Scale', 'National Scale', 'Small-Scale Maps'],
    'Streets and households are Local Scale. Regional or National rates would average the spill away. Small-scale maps show large areas with less detail — the opposite of this investigation.',
  ),
]
