import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_THEORY_QUESTIONS: VocabQuestion[] = [
  q('th-wst-1', 'theories', 'World Systems Theory',
    'Ivory Coast grows cocoa, factories in the Netherlands grind the beans, and Swiss companies brand the chocolate and keep most of the profit. A geographer says these places are not separate national stories — they occupy core, semi-periphery, and periphery roles inside one capitalist world-economy. Which model is that?',
    ['Dependency Model', 'Commodity Dependence', 'Primary Sector'],
    'One connected world-economy with core, semi-periphery, and periphery roles is World Systems Theory. The Dependency Model is a poorer-country-to-richer-country trap, not the three-tier system. Commodity Dependence only describes a raw-export mix. Primary Sector names farming, not the world hierarchy.'),
  q('th-wst-2', 'theories', 'World Systems Theory',
    'South Korea moved from cheap assembly into electronics design and finance, while much of Central America stayed locked into bananas and apparel for U.S. buyers. Which theory treats some places as able to climb into a middle “semi-periphery” role rather than staying poor forever?',
    ['Dependency Model', 'Possibilism', 'Quinary Sector'],
    'World Systems Theory includes a semi-periphery that can mix cheap production with rising technology. The Dependency Model stresses lasting dependence, not climbing. Possibilism is about environment and choice. Quinary Sector is elite decision jobs.'),
  q('th-wst-3', 'theories', 'World Systems Theory',
    'On a world map, high-wage finance and design cluster in the United States, Western Europe, and Japan, while many tropical countries still export ores and crops. Which theory explains that pattern as one connected system with different economic roles?',
    ['Human Development Index', 'Formal Region', 'Time-Space Compression'],
    'Core–periphery roles in one world-economy are World Systems Theory. HDI ranks well-being. A formal region shares one trait. Time-space compression is shrinking travel time.'),
  q('th-wst-4', 'theories', 'World Systems Theory',
    'A student claims Zambia, China, and Germany are three isolated national stories. A better AP answer is that copper mining, smelting, and branding are positions inside one global division of labor. Which theory is the student missing?',
    ['Literacy Rate', 'Site', 'Cartogram'],
    'One global division of labor is World Systems Theory. Literacy Rate is schooling. Site is local physical character. A cartogram resizes map area by data.'),
  q('th-wst-5', 'theories', 'World Systems Theory',
    'An FRQ asks why many poorer countries stay in farm and mine exports while richer countries keep high-value services. The expected model groups the world by economic role, not by climate. Which model is that?',
    ['Environmental Determinism', 'National Scale', 'Built Environment'],
    'Grouping the world by economic role is World Systems Theory. Environmental Determinism would blame climate. National Scale is one country. Built Environment is human-made structures.'),

  q('th-dep-1', 'theories', 'Dependency Model',
    'A Central American country’s ports and railroads were built so one U.S. fruit company could export bananas. Decades after independence it still imports machines and credit from the same partner. Which idea says wealthy countries stay rich because poorer ones stay tied to them?',
    ['World Systems Theory', 'Commodity Dependence', 'Formal Sector'],
    'That lasting unequal relationship is the Dependency Model. World Systems Theory zooms out to a three-tier world-economy. Commodity Dependence notes the banana export but not the political-economic control. Formal Sector is taxed work.'),
  q('th-dep-2', 'theories', 'Dependency Model',
    'An Andean state nationalizes a mine, then still has to sell ore through London brokers and repay dollar loans. Political independence did not create economic autonomy. Which theory explains that leftover control?',
    ['Possibilism', 'Remittances', 'Absolute Location'],
    'Needing foreign markets, technology, and credit after independence is the Dependency Model. Possibilism is environmental choice. Remittances are migrant money. Absolute Location is a coordinate.'),
  q('th-dep-3', 'theories', 'Dependency Model',
    'After a West African government cut tariffs, cheap imported cloth wiped out local weaving, and cocoa still left unprocessed. Critics say “free trade” deepened an older colonial division of labor. Which theory are they using?',
    ['World Systems Theory', 'Tertiary Sector', 'Small-Scale Maps'],
    'Opening trade reproduced an unequal role: Dependency Model. World Systems Theory would emphasize core/semi-periphery/periphery positions worldwide. Tertiary Sector is services. Small-scale maps show large areas.'),
  q('th-dep-4', 'theories', 'Dependency Model',
    'Ethiopia sells cheap coffee; U.S. firms roast and brand it for a much higher price. Ethiopia’s budget then swings with a price it does not set. Which theory says the wealthy country needs this cheaper partner to stay wealthy?',
    ['Purchasing Power Parity', 'Sense of Place', 'Quaternary Sector'],
    'Wealthy states remaining wealthy through a poorer export partner is the Dependency Model. PPP compares prices. Sense of Place is feeling. Quaternary Sector is information work.'),
  q('th-dep-5', 'theories', 'Dependency Model',
    'A textbook line says richer countries need poorer countries so they can keep cheap raw materials and markets. That is not just “they export oil.” Which theory is the line stating?',
    ['Commodity Dependence', 'Gini Coefficient', 'Functional Region'],
    'Richer countries needing a poorer periphery is the Dependency Model. Commodity Dependence is export concentration on one product. Gini measures inequality inside a country. A functional region is organized around a node.'),

  q('th-com-1', 'theories', 'Commodity Dependence',
    'Nigeria’s budget froze in 2014 and 2020 when oil prices crashed, even though Lagos has a large services economy. Oil still supplies most export earnings. Which concept names that trap?',
    ['World Systems Theory', 'Informal Sector', 'Primary Sector'],
    'Living off one raw export whose price is set abroad is Commodity Dependence. World Systems Theory is a broader world hierarchy. Informal Sector is unrecorded work. Primary Sector is the type of work, not the dangerous concentration of exports.'),
  q('th-com-2', 'theories', 'Commodity Dependence',
    'Chile’s copper, Zambia’s copper, and Venezuela’s oil each produced boom years followed by austerity when the same export price fell. Manufacturing stayed a small share of exports. Which concept is that?',
    ['Dependency Model', 'Secondary Sector', 'Remittances'],
    'National earnings tied to one raw good is Commodity Dependence. The Dependency Model is the broader rich/poor relationship. Secondary Sector is manufacturing. Remittances are migrant transfers.'),
  q('th-com-3', 'theories', 'Commodity Dependence',
    'A Pacific island’s currency and port traffic rise and fall with one mineral price. Tourist arrivals barely change, but the government still cannot fund schools when that price drops. Which concept best explains the instability?',
    ['Distance Decay', 'Life Expectancy', 'Local Scale'],
    'One export price driving the whole budget is Commodity Dependence. Distance Decay is declining interaction with distance. Life Expectancy is years lived. Local Scale is neighborhood-level analysis.'),
  q('th-com-4', 'theories', 'Commodity Dependence',
    'An FRQ uses Ethiopia and coffee, or Nigeria and oil, to show why a country is vulnerable to a world price it does not control. Which vocab term is that example targeting?',
    ['Human Development Index', 'Formal Region', 'Cartographic Scale'],
    'Vulnerability to one export price is Commodity Dependence. HDI is a well-being composite. A formal region shares a trait. Cartographic Scale is the map-to-Earth ratio.'),
  q('th-com-5', 'theories', 'Commodity Dependence',
    'A country can have factories and cities and still be in this trap if almost all of its foreign earnings come from one crop or mineral. Which term is that?',
    ['Quinary Sector', 'Built Environment', 'Relative Location'],
    'Foreign earnings from one raw good is Commodity Dependence, even if other sectors exist. Quinary Sector is top decision-making. Built Environment is buildings and roads. Relative Location is position compared with other places.'),
]
