import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_MAP_QUESTIONS: VocabQuestion[] = [
  q('map-phy-1', 'maps', 'Physical Geography',
    'A team studies why a desert is dry and why a volcano erupts, not why a city grew or why incomes differ.',
    ['Human Geography', 'Thematic Map', 'Possibilism'],
    'Earth systems, landforms, and climate are Physical Geography. Human Geography asks how people organize those places. A thematic map is a display tool. Possibilism is a theory about choice within environmental limits.'),
  q('map-phy-2', 'maps', 'Physical Geography',
    'Before a port is proposed, engineers measure tides, sediment, and bedrock — questions that would remain relevant even if no city existed.',
    ['Human Geography', 'Cultural Landscape', 'Formal Sector'],
    'Tides and bedrock are Physical Geography. Human Geography and Cultural Landscape start when people occupy the coast. Formal Sector is an economic category.'),
  q('map-phy-3', 'maps', 'Physical Geography',
    'A hurricane paper models sea-surface temperature and wind shear. It is not yet asking who can evacuate.',
    ['Human Geography', 'Remote Sensing', 'Quaternary Sector'],
    'The atmosphere-ocean process is Physical Geography. Who evacuates is Human Geography. Remote Sensing might supply the temperature data. Quaternary Sector is knowledge employment.'),
  q('map-phy-4', 'maps', 'Physical Geography',
    'A question about why monsoons arrive in June concerns climate, not language or urban form.',
    ['Human Geography', 'Vernacular Region', 'Gini Coefficient'],
    'Climate timing is Physical Geography. Language and cities are Human Geography. A vernacular region is a mental area. Gini is inequality.'),
  q('map-phy-5', 'maps', 'Physical Geography',
    'A class studies why mountains form and why some coasts get hurricanes, without asking who lives there.',
    ['Human Geography', 'Reference Map', 'Primary Sector'],
    'Natural systems are Physical Geography. Human Geography is people. A reference map can show either. Primary Sector is extraction employment.'),

  q('map-hum-1', 'maps', 'Human Geography',
    'Why a city grew, why language politics matter, and why trade concentrates at a few ports are questions about people and networks, not ocean chemistry.',
    ['Physical Geography', 'Isoline Map', 'Life Expectancy'],
    'Population, culture, politics, and economic networks are Human Geography. Physical Geography would be currents and climate. An isoline map could display either. Life Expectancy is one social indicator.'),
  q('map-hum-2', 'maps', 'Human Geography',
    'Two towns on the same river have different religions and commuting patterns. The river’s discharge is identical.',
    ['Physical Geography', 'Cartographic Scale', 'Primary Sector'],
    'Religion and commuting are Human Geography. Discharge is Physical Geography. Cartographic Scale is a map property. Primary Sector is extraction.'),
  q('map-hum-3', 'maps', 'Human Geography',
    'A paper asks why people speak different languages and why cities grow, not why rocks form.',
    ['Physical Geography', 'Topographic Map', 'Gini Coefficient'],
    'Those topics are Human Geography. Mineralogy is Physical. A topographic map is a reference tool. Gini is one inequality measure used inside the field.'),
  q('map-hum-4', 'maps', 'Human Geography',
    'A question about why a capital was relocated is not a bedrock question. This branch of the discipline treats capitals, migration, and trade.',
    ['Physical Geography', 'Site', 'Small-Scale Maps'],
    'Capitals, migration, and trade are Human Geography. Site is one spatial concept used inside it. Physical Geography is nature. Small-scale maps are a map class.'),
  q('map-hum-5', 'maps', 'Human Geography',
    'A researcher asks why people move, where factories locate, and how cities grow — not why a river floods.',
    ['Physical Geography', 'Remote Sensing', 'Formal Sector'],
    'This course is Human Geography. Physical Geography is Earth systems. Remote Sensing is a data method. Formal Sector is taxed work.'),

  q('map-ref-1', 'maps', 'Reference Map',
    'A hiking atlas, a political wall map of African states, and a city street grid are constructed so a user can determine location, not to argue a statistical rate.',
    ['Thematic Map', 'Cartogram', 'Choropleth Map'],
    'Maps whose main job is location and navigation are Reference Maps. Thematic maps, including choropleths and cartograms, show a selected data theme.'),
  q('map-ref-2', 'maps', 'Reference Map',
    'An emergency crew requires creek names, the county line, and the road to the hospital, not a shading of poverty rates.',
    ['Thematic Map', 'Dot Distribution Map', 'Graduated Symbol Map'],
    'Names, lines, and roads are a Reference Map. Poverty shading or dots would be thematic products.'),
  q('map-ref-3', 'maps', 'Reference Map',
    'A telephone’s default basemap displays streets, parks, and labels. Activating “bicycle crashes last year” converts it into a different product.',
    ['Thematic Map', 'Isoline Map', 'World Scale'],
    'The unlabeled-for-theme basemap is a Reference Map. Bike crashes would be thematic. Isolines are one thematic form. World Scale is a level of analysis.'),
  q('map-ref-4', 'maps', 'Reference Map',
    'A visitor wants the names of districts in Rome, not a map of income.',
    ['Thematic Map', 'Human Development Index', 'Friction of Distance'],
    'Names of districts are a Reference Map. Income would be thematic. HDI is a development index. Friction of Distance is movement cost.'),
  q('map-ref-5', 'maps', 'Reference Map',
    'A visitor opens a map to find street names and the city park, not to compare income by neighborhood.',
    ['Thematic Map', 'Quaternary Sector', 'Possibilism'],
    'Finding places is a Reference Map. Showing a variable is thematic. Quaternary Sector is information work. Possibilism is a theory.'),

  q('map-thm-1', 'maps', 'Thematic Map',
    'A page titled “Percent of adults with a university degree, 2020” is not intended to help a driver reach campus; it displays the spatial distribution of one variable.',
    ['Reference Map', 'Topographic Map', 'Absolute Location'],
    'A map whose purpose is a data theme is a Thematic Map. A reference or topographic sheet emphasizes location and terrain. Absolute Location is a coordinate.'),
  q('map-thm-2', 'maps', 'Thematic Map',
    'Election-night precinct colors, an oil-spill track, and a population cartogram all sacrifice some street-finding detail in order to display a selected phenomenon.',
    ['Reference Map', 'Physical Geography', 'Formal Region'],
    'All three are Thematic Maps. A reference map would privilege streets and names. Physical Geography is a field. A formal region might be what the theme shows.'),
  q('map-thm-3', 'maps', 'Thematic Map',
    'A planner already knows the streets. She opens a map of childhood asthma rates to decide where to place air monitors.',
    ['Reference Map', 'Site', 'Quinary Sector'],
    'A map of asthma rates is Thematic. A street sheet is Reference. Site is a place’s physical character. Quinary Sector is elite decision-making.'),
  q('map-thm-4', 'maps', 'Thematic Map',
    'Choropleth, dot, graduated symbol, isoline, and cartogram pages in an atlas all display a selected data theme rather than help a driver find a street.',
    ['Reference Map', 'Topographic Map', 'National Scale'],
    'Those pages are all Thematic Maps. A topographic sheet is mainly a specialized reference product. National Scale is a level of analysis.'),
  q('map-thm-5', 'maps', 'Thematic Map',
    'A student already has a street atlas. The student now requires a map whose purpose is to display one data theme, such as income or language.',
    ['Reference Map', 'Field Observations', 'Primary Sector'],
    'A map whose purpose is a data theme is a Thematic Map. A reference map shows location. Field Observations are a data method. Primary Sector is extraction.'),

  q('map-cho-1', 'maps', 'Choropleth Map',
    'A United States map shades each county from light to dark using the percent of households in poverty. The unit is an area, and the variable is a rate.',
    ['Dot Distribution Map', 'Graduated Symbol Map', 'Cartogram'],
    'Shaded enumeration units for a rate are a Choropleth Map. Dots show counts as points. Graduated symbols size a circle. A cartogram resizes the counties themselves.'),
  q('map-cho-2', 'maps', 'Choropleth Map',
    'A student maps “number of deaths” by coloring each country. Small, densely populated places appear safe and large, sparsely populated places appear deadly because area, not risk, is driving the ink. The student used the wrong variable for this shading technique.',
    ['Isoline Map', 'Reference Map', 'Topographic Map'],
    'Coloring political units is choropleth technique — misleading for raw counts. Isolines interpolate a continuous surface. Reference and topographic maps are not this shading method.'),
  q('map-cho-3', 'maps', 'Choropleth Map',
    'Belgium’s language regions can be shown by coloring each municipality by official language. The building block is a bounded unit with one class.',
    ['Dot Distribution Map', 'Isoline Map', 'Graduated Symbol Map'],
    'One class per official unit is a Choropleth Map. Dots would show speakers as points. Isolines need a continuous numeric field. Graduated symbols size a mark by a quantity.'),
  q('map-cho-4', 'maps', 'Choropleth Map',
    'A student colors whole counties by the number of people. Large empty counties look crowded. The teacher says shade by a percent instead.',
    ['Graduated Symbol Map', 'Isoline Map', 'Small-Scale Maps'],
    'The rate-not-count warning is for Choropleth Maps. Graduated symbols can show totals. Isolines are equal-value lines. Small-scale is a zoom level.'),
  q('map-cho-5', 'maps', 'Choropleth Map',
    'An atlas fills each state with a darker color as unemployment rises. The states retain their actual shapes; only the color changes.',
    ['Dot Distribution Map', 'Cartogram', 'Reference Map'],
    'Shaded areas for a statistical variable are a Choropleth Map. Dots use point symbols. A cartogram changes size, not just color. A reference map is for location.'),

  q('map-dot-1', 'maps', 'Dot Distribution Map',
    'A 2020 map places one mark for every 500 dairy cows, so Wisconsin appears densely marked and Nevada almost empty. The reader can observe clustering inside states.',
    ['Choropleth Map', 'Cartogram', 'Isoline Map'],
    'Repeated point symbols for counts are a Dot Distribution Map. A choropleth would shade whole states. A cartogram would resize states. Isolines connect equal values.'),
  q('map-dot-2', 'maps', 'Dot Distribution Map',
    'To show where incidents occurred, an analyst plots each event as a point instead of coloring whole counties.',
    ['Choropleth Map', 'Graduated Symbol Map', 'Small-Scale Maps'],
    'One mark per event is a Dot Distribution Map. Choropleth averages the county. A graduated symbol is usually one sized mark per unit. Small-scale is about zoom.'),
  q('map-dot-3', 'maps', 'Dot Distribution Map',
    'A population map of Egypt places thousands of small marks along the Nile and almost none in the desert, revealing a linear cluster.',
    ['Choropleth Map', 'Cartogram', 'Reference Map'],
    'The speckled Nile is a Dot Distribution Map. A national choropleth would be one color for Egypt. A cartogram would balloon the country by population. A reference map emphasizes names.'),
  q('map-dot-4', 'maps', 'Dot Distribution Map',
    'A health office wants to see where cases cluster on particular streets, not one average rate for each county.',
    ['Choropleth Map', 'Cartographic Scale', 'Formal Region'],
    'Clustered points are a Dot Distribution Map. Choropleth gives a unit average. Cartographic Scale is a ratio. A Formal Region is a type of area.'),
  q('map-dot-5', 'maps', 'Dot Distribution Map',
    'A student wants to show concentration using many same-size marks, so dense places appear speckled.',
    ['Choropleth Map', 'Isoline Map', 'Thematic Map'],
    'Same-size marks for concentration are a Dot Distribution Map. Thematic Map is the parent class. Choropleth uses shading. Isolines use lines.'),

  q('map-grd-1', 'maps', 'Graduated Symbol Map',
    'Each city on a trade map has a circle whose area is proportional to container throughput. Shanghai’s circle is large; a small port is a minute mark. The city’s legal boundary is not shaded.',
    ['Choropleth Map', 'Dot Distribution Map', 'Isoline Map'],
    'One symbol sized by a quantity is a Graduated Symbol Map. Choropleth shades the whole unit. Dots repeat same-size marks. Isolines contour a surface.'),
  q('map-grd-2', 'maps', 'Graduated Symbol Map',
    'A newspaper shows earthquake magnitude with larger squares for stronger events, all at the epicenter. Magnitude is a value at a location, not a county percentage.',
    ['Choropleth Map', 'Cartogram', 'Topographic Map'],
    'Sized point symbols for a magnitude are Graduated Symbols. Choropleth needs areal units. A cartogram resizes areas. A topographic map shows terrain.'),
  q('map-grd-3', 'maps', 'Graduated Symbol Map',
    'To compare airport passenger totals, an atlas draws one disk per airport instead of coloring whole countries.',
    ['Choropleth Map', 'Isoline Map', 'Field Observations'],
    'One sized disk per airport is a Graduated Symbol Map. Country coloring would be choropleth. Isolines would imply a continuous surface. Field Observations are a data method.'),
  q('map-grd-4', 'maps', 'Graduated Symbol Map',
    'City population is often shown this way so Tokyo’s mark is larger than a small town’s, without shading the entire country.',
    ['Cartogram', 'Small-Scale Maps', 'Literacy Rate'],
    'Sized city marks are a Graduated Symbol Map. A cartogram would resize the country. Small-scale is a zoom class. Literacy Rate is an indicator.'),
  q('map-grd-5', 'maps', 'Graduated Symbol Map',
    'Each city gets one circle. Tokyo’s circle is large and a small town’s is tiny, but the country itself is not shaded.',
    ['Dot Distribution Map', 'Choropleth Map', 'Reference Map'],
    'Proportional/sized marks are a Graduated Symbol Map. Dots are equal-sized repeats. Choropleth shades areas. A reference map is for location.'),

  q('map-iso-1', 'maps', 'Isoline Map',
    'A weather chart draws lines through all points with the same barometric pressure, creating closed loops around a low. The variable is a continuous field, not one value per county.',
    ['Choropleth Map', 'Dot Distribution Map', 'Cartogram'],
    'Lines of equal value are an Isoline Map. Choropleth would fill counties. Dots would mark stations. A cartogram would resize areas.'),
  q('map-iso-2', 'maps', 'Isoline Map',
    'A travel-time map around Tokyo draws nested curves for 30, 60, and 90 minutes from a station.',
    ['Graduated Symbol Map', 'Reference Map', 'Formal Region'],
    'Equal-travel-time curves are isolines. Graduated symbols would size stations. A reference map would show tracks and names. A formal region would be an official zone.'),
  q('map-iso-3', 'maps', 'Isoline Map',
    'A frost-date atlas connects places that share the same average last-freeze day, so a farmer sees a wave of lines across the Midwest.',
    ['Choropleth Map', 'Dot Distribution Map', 'Thematic Map'],
    'Connecting equal frost dates is an Isoline Map. Thematic Map is the broader class. Choropleth would fill states. Dots would mark stations without connecting them.'),
  q('map-iso-4', 'maps', 'Isoline Map',
    'Temperature, elevation contours, and air pressure are usually shown with this technique, not with one color per state.',
    ['Choropleth Map', 'Dot Distribution Map', 'Gender Gap'],
    'Continuous fields use Isoline Maps. State coloring is choropleth. Dots mark points. Gender Gap is a social difference.'),
  q('map-iso-5', 'maps', 'Isoline Map',
    'Most weather maps connect equal values with lines instead of coloring whole counties.',
    ['Choropleth Map', 'Topographic Map', 'Cartogram'],
    'Weather-style equal-value lines are an Isoline Map. Topographic maps use contours plus many other symbols. Choropleth shades political units. A cartogram resizes area.'),

  q('map-topo-1', 'maps', 'Topographic Map',
    'A USGS quadrangle shows contour lines, spot elevations, streams, and a few buildings so an engineer can read slope, not poverty.',
    ['Choropleth Map', 'Cartogram', 'Thematic Map'],
    'A contour-based terrain-and-features sheet is a Topographic Map. Choropleths and cartograms are thematic. Calling it only “thematic” misses that its job is terrain location.'),
  q('map-topo-2', 'maps', 'Topographic Map',
    'Hikers select a map because tightly spaced brown lines indicate that a ridge is steep.',
    ['Isoline Map', 'Reference Map', 'Graduated Symbol Map'],
    'Contours plus planimetric features for terrain reading are a Topographic Map. Contours are isolines, but “isoline map” alone would also describe a weather chart without the full topo symbol set.'),
  q('map-topo-3', 'maps', 'Topographic Map',
    'A dam-siting team requests a sheet with 20-foot contours, floodplain, and existing roads together. They need the shape of the land.',
    ['Choropleth Map', 'Dot Distribution Map', 'World Scale'],
    'Contours + hydrography + culture for engineering is a Topographic Map. Income color is choropleth. Dots would not give slope. World Scale is a level of analysis.'),
  q('map-topo-4', 'maps', 'Topographic Map',
    'A student needs to know whether a trail climbs 400 feet in half a mile. A world political map will not suffice.',
    ['Small-Scale Maps', 'Thematic Map', 'Quaternary Sector'],
    'Detailed elevation is a Topographic Map. Small-scale world maps hide that detail. Thematic maps show a data theme. Quaternary Sector is information work.'),
  q('map-topo-5', 'maps', 'Topographic Map',
    'A hiker needs contour lines plus streams, roads, and a few buildings so the shape of the land is clear.',
    ['Cartogram', 'Choropleth Map', 'Human Development Index'],
    'Elevation contours are a Topographic Map. A cartogram resizes area by data. Choropleth shades statistical units. HDI is an index.'),

  q('map-car-1', 'maps', 'Cartogram',
    'On an election graphic, Rhode Island becomes large and Montana nearly vanishes because each state’s area was reset to equal its electoral votes, not its land.',
    ['Choropleth Map', 'Graduated Symbol Map', 'Small-Scale Maps'],
    'Resizing units by a data value is a Cartogram. A choropleth keeps land area and changes color. Graduated symbols keep the base map and size a mark. Small-scale just means zoomed out.'),
  q('map-car-2', 'maps', 'Cartogram',
    'A world population map enlarges India and Nigeria and reduces Canada so that equal ink means equal people. The continents remain recognizable but warped.',
    ['Choropleth Map', 'Dot Distribution Map', 'Reference Map'],
    'Warping area to match a variable is a Cartogram. Choropleth keeps geographic area. Dots keep area and add marks. A reference map tries to keep shapes for location.'),
  q('map-car-3', 'maps', 'Cartogram',
    'A map distorts the sizes of counties so that larger shapes represent more people, not more land.',
    ['Isoline Map', 'Topographic Map', 'Absolute Location'],
    'Area equal to a data value is a Cartogram. Isolines would contour a surface. Topographic maps show terrain. Absolute Location is a coordinate.'),
  q('map-car-4', 'maps', 'Cartogram',
    'A researcher redraws countries so each country’s size matches its carbon emissions, not its land. Empty deserts shrink; busy industrial countries grow.',
    ['Dot Distribution Map', 'Isoline Map', 'Site'],
    'Resizing by emissions is a Cartogram. Dots would speckle the real land. Isolines connect equal values. Site is physical character.'),
  q('map-car-5', 'maps', 'Cartogram',
    'On a regular map, Canada looks more important than India because it has more land. A researcher resizes each country so area matches population.',
    ['Choropleth Map', 'Reference Map', 'Formal Region'],
    'Resizing by population is a Cartogram. Choropleth keeps area and changes color. A reference map is for finding places. A Formal Region is a type of area.'),

  q('map-csc-1', 'maps', 'Cartographic Scale',
    'One map states 1:24,000 and another 1:1,000,000. Those fractions indicate how many ground units one map unit represents.',
    ['Small-Scale Maps', 'Absolute Location', 'Pattern'],
    'The representative fraction is Cartographic Scale. “Small-scale” is one end of that property, not the property itself. Absolute Location is a position. Pattern is an arrangement.'),
  q('map-csc-2', 'maps', 'Cartographic Scale',
    'A planner cannot measure a bicycle-lane width on a wall map of the entire United States because the map-to-Earth ratio is too coarse, even though the poster is physically large.',
    ['Relative Location', 'Thematic Map', 'Regional Scale'],
    'The map-to-Earth ratio is Cartographic Scale — independent of paper size. Relative Location is position versus other places. Thematic Map is purpose. Regional Scale is a social zoom.'),
  q('map-csc-3', 'maps', 'Cartographic Scale',
    'Switching a GIS view from 1:10,000 to 1:250,000 changes which symbols are even permitted, because one centimeter now stands for a much longer stretch of Earth.',
    ['Remote Sensing', 'Sense of Place', 'Formal Region'],
    'Changing the representative fraction is Cartographic Scale. Remote Sensing is data collection. Sense of Place is meaning. A Formal Region is a type of area.'),
  q('map-csc-4', 'maps', 'Cartographic Scale',
    'A student says a large poster is automatically a large-scale map. The useful fact is the fraction, not the paper size.',
    ['Thematic Map', 'Built Environment', 'Remittances'],
    'The fraction, not the paper size, is Cartographic Scale. A thematic map is about data purpose. Built Environment is buildings. Remittances are migrant money.'),
  q('map-csc-5', 'maps', 'Cartographic Scale',
    'One inch on a city map equals one mile on the ground. Another map uses one inch for 100 miles.',
    ['Small-Scale Maps', 'Absolute Location', 'World Scale'],
    'Map distance versus Earth distance is Cartographic Scale. Small-scale maps are one category of that property. Absolute Location is a coordinate. World Scale is a social level of analysis.'),

  q('map-ssm-1', 'maps', 'Small-Scale Maps',
    'A classroom world map shows oceans and country outlines but cannot show a single village street, even though the poster is physically large.',
    ['Topographic Map', 'Reference Map', 'Cartographic Scale'],
    'A tiny representative fraction covering a huge area is a Small-Scale Map. A topographic plat is typically large-scale. It may also be a reference map, but the trick is the small-scale / large-area relationship. Cartographic Scale is the property; this question asks for the small-scale category.'),
  q('map-ssm-2', 'maps', 'Small-Scale Maps',
    'To compare monsoon systems across South Asia, a researcher must accept less street-level detail so the entire peninsula fits.',
    ['Topographic Map', 'Dot Distribution Map', 'Local Scale'],
    'A highly generalized, large-area sheet is a Small-Scale Map. A topo plat is typically large-scale. Dots are a symbol type. Local Scale is a social zoom that usually needs a large-scale map.'),
  q('map-ssm-3', 'maps', 'Small-Scale Maps',
    'Airline route maps of the entire Earth omit most cities and generalize coastlines because the cartographer selected a very small representative fraction.',
    ['Choropleth Map', 'Cartogram', 'Field Observations'],
    'Tiny fraction + huge area + heavy generalization = Small-Scale Maps. Choropleth and cartogram are thematic techniques that can appear at any scale. Field Observations are not a map class.'),
  q('map-ssm-4', 'maps', 'Small-Scale Maps',
    'A globe-style world map covers the whole planet and leaves out most cities and streets.',
    ['Absolute Location', 'Quinary Sector', 'Gender Gap'],
    'The world map is a Small-Scale Map. Absolute Location is a coordinate. Quinary Sector is leadership jobs. Gender Gap is a social difference.'),
  q('map-ssm-5', 'maps', 'Small-Scale Maps',
    'A wall map of the whole world shows little street detail because it covers so much of Earth.',
    ['Topographic Map', 'Isoline Map', 'Literacy Rate'],
    'Little detail / large area is a Small-Scale Map. Topographic maps are usually large-scale and detailed. Isolines are a symbol system. Literacy Rate is an indicator.'),

  q('map-abs-1', 'maps', 'Absolute Location',
    'A rescue team is given 40.7° N, 74.0° W instead of “near the big city.”',
    ['Relative Location', 'Situation', 'Sense of Place'],
    'A coordinate that does not depend on other places is Absolute Location. “Nepal side of the Himalaya” is relative. Situation is a place’s connections. Sense of Place is meaning.'),
  q('map-abs-2', 'maps', 'Absolute Location',
    'A land survey records a parcel on a measured grid so a court can identify the same plot after nearby roads are renamed.',
    ['Relative Location', 'Toponyms', 'Vernacular Region'],
    'A surveyed grid that stays put when names change is Absolute Location. Relative Location would fail when the roads are renamed. Toponyms are the names. A vernacular region is a mental area.'),
  q('map-abs-3', 'maps', 'Absolute Location',
    'Aircraft transponders report a constantly updating latitude and longitude so two aircraft cannot both be described as “near Chicago” in a manner that still permits a collision.',
    ['Relative Location', 'Pattern', 'Cultural Landscape'],
    'Latitude/longitude is Absolute Location. “Near Chicago” is relative and too vague. Pattern is arrangement. Cultural Landscape is the visible human imprint.'),
  q('map-abs-4', 'maps', 'Absolute Location',
    'A ship’s distress call must include this, not “west of the storm.”',
    ['Relative Location', 'Time-Space Compression', 'Informal Sector'],
    'The exact coordinate is Absolute Location. “West of the storm” is relative. Time-space compression is shrinking travel time. Informal Sector is unrecorded work.'),
  q('map-abs-5', 'maps', 'Absolute Location',
    'A ship reports 15.2° N, 23.6° W so rescuers can find the exact spot, not “west of the storm.”',
    ['Relative Location', 'Place', 'Site'],
    'The exact spot is Absolute Location. Relative Location is compared with other features. Place adds character. Site is physical setting.'),

  q('map-rel-1', 'maps', 'Relative Location',
    'Singapore’s advantage is often stated as “at the outlet of the Strait of Malacca,” not as a pair of degrees. The useful fact is position compared with routes and neighbors.',
    ['Absolute Location', 'Site', 'Cartographic Scale'],
    'Position versus other places and routes is Relative Location. The coordinate would be absolute. Site would be harbor depths and land. Cartographic Scale is a map ratio.'),
  q('map-rel-2', 'maps', 'Relative Location',
    'A realtor states that a house is “15 minutes from downtown and across from the magnet school.” Those phrases can remain true even if the GPS coordinate is never mentioned.',
    ['Absolute Location', 'Isoline Map', 'Primary Sector'],
    'Time and neighbor landmarks are Relative Location. The GPS pin would be absolute. An isoline map might show the 15-minute band. Primary Sector is extraction.'),
  q('map-rel-3', 'maps', 'Relative Location',
    'After a new high-speed rail line, a town that did not move is suddenly closer to the capital in travel time. Coordinates were unchanged.',
    ['Absolute Location', 'Site', 'Dot Distribution Map'],
    'Travel-time nearness is Relative Location. Absolute Location and the physical site did not change. A dot map might later show new firms.'),
  q('map-rel-4', 'maps', 'Relative Location',
    '“Chicago lies between the Great Lakes and the Mississippi system” is more useful to a geographer than a raw coordinate.',
    ['Absolute Location', 'Literacy Rate', 'Quaternary Sector'],
    'Between other features is Relative Location (and closely related to situation). Absolute Location would be the degrees. Literacy Rate is schooling. Quaternary Sector is information work.'),
  q('map-rel-5', 'maps', 'Relative Location',
    'A city is described as “at the end of a busy shipping strait,” not by a pair of degrees.',
    ['Absolute Location', 'Space', 'Gini Coefficient'],
    'That comparison is Relative Location. Absolute Location is the exact spot. Space is the geometric surface. Gini is inequality.'),
]
