import { mc, multi, type ApHumanPracticeQuestion } from './apHumanStudy'

const M = 'maps' as const
const P = 'patterns' as const
const J = 'projections' as const

export const MAP_QUESTIONS: ApHumanPracticeQuestion[] = [
  mc('m1', M, 'According to the notes, the two main types of maps are', [
    'political maps and road maps',
    'reference maps and thematic maps',
    'topographic maps and cartograms',
    'navigation maps and weather maps',
  ], 1, '1.1.1 says types of maps include reference maps and thematic maps.'),
  mc('m2', M, 'A reference map is mainly used for', [
    'telling a story about a social phenomenon',
    'general information, navigation, and location',
    'distorting country size to show a variable',
    'showing only weather data',
  ], 1, 'Reference maps show general information, navigation, and location.'),
  mc('m3', M, 'A political reference map would show', [
    'rivers, mountains, and elevation',
    'highways and streets',
    'states, countries, and capitals',
    'average years of schooling',
  ], 2, 'Political maps show states, countries, and capitals.'),
  mc('m4', M, 'A physical reference map focuses on', [
    'natural features',
    'capitals and borders',
    'highways and streets',
    'immigrant groups by state',
  ], 0, 'Physical maps show natural features.'),
  mc('m5', M, 'A road map is a type of reference map that shows', [
    'elevation only',
    'highways, streets, etc.',
    'crime data by neighborhood',
    'GDP per capita',
  ], 1, 'Road maps show highways, streets, and similar routes.'),
  mc('m6', M, 'A thematic map is used to', [
    'show only exact latitude and longitude',
    'help ships navigate using right angles',
    'communicate information about a place — spatial aspects / what it is like there',
    'list every street name in a city',
  ], 2, 'Thematic maps communicate information about a place and what it is like there.'),
  mc('m7', M, 'The class example of a reference map shows', [
    'gun violence in Cincinnati',
    'the location and direction of Interstate Highways',
    'average years of schooling worldwide',
    'soccer stadiums by size',
  ], 1, 'The reference-map example focuses on mapping location/distance of Interstate Highways.'),
  mc('m8', M, 'The class example of a thematic map shows', [
    'Interstate Highways',
    'the second largest immigrant group after Mexican in each state',
    'cardinal directions only',
    'a blank political outline',
  ], 1, 'That immigrant-group map is a thematic map: it maps data to tell a story.'),
  mc('m9', M, 'A thematic map focuses on', [
    'mapping location or showing distance only',
    'mapping data to show a phenomenon — it tells a story',
    'preserving all shapes perfectly',
    'hiding all spatial data',
  ], 1, 'Thematic maps map data to show a phenomenon and tell a story.'),
  mc('m10', M, 'Choropleth maps use', [
    'one dot for each person only',
    'lines that connect points of equal value',
    'various colors, shades of one color, or patterns to show location and distribution of spatial data',
    'country size changed to match a variable',
  ], 2, 'Choropleth maps use colors, shades, or patterns to show spatial data.'),
  mc('m11', M, 'The class example of a choropleth map is', [
    'Gun Violence in Cincinnati, Ohio',
    'Average Years of Schooling, World',
    'Soccer Stadiums',
    'Temperature on January 31st, 2019',
  ], 1, 'Average Years of Schooling is the choropleth example.'),
  mc('m12', M, 'On a dot-density map, each dot', [
    'always means one city',
    'represents a specified quantity of a spatial characteristic',
    'connects points of equal elevation',
    'is randomly sized for decoration',
  ], 1, 'Each dot stands for a set quantity of a spatial characteristic.'),
  mc('m13', M, 'The class example of a dot-density map is', [
    'Average Years of Schooling, World',
    'Gun Violence in Cincinnati, Ohio',
    'Soccer Stadiums',
    'Interstate Highways',
  ], 1, 'Gun Violence in Cincinnati is the dot-density example.'),
  mc('m14', M, 'Graduated / proportional symbol maps', [
    'use symbols of different sizes to indicate different amounts of a variable',
    'always use one color shade only',
    'never show quantity',
    'are only used for weather',
  ], 0, 'Different symbol sizes show different amounts of a variable.'),
  mc('m15', M, 'The class example of a graduated / proportional symbol map is', [
    'Soccer Stadiums',
    'Average Years of Schooling',
    'Gun Violence in Cincinnati',
    'Temperature on January 31st, 2019',
  ], 0, 'Soccer Stadiums is the graduated/proportional symbol example.'),
  mc('m16', M, 'On a cartogram, the sizes of countries are', [
    'always true to actual land area',
    'shown according to a specific variable; area is distorted to show that variable',
    'hidden completely',
    'based only on elevation',
  ], 1, 'Cartograms distort area so country size matches a variable.'),
  mc('m17', M, 'Isoline maps use', [
    'dots of equal size',
    'country outlines filled with one color',
    'lines that connect points of equal value to depict variations in the data across space',
    'random arrows',
  ], 2, 'Isolines connect points of equal value across space.'),
  mc('m18', M, 'Isoline maps are commonly used for', [
    'capitals and borders only',
    'weather and elevation',
    'street names',
    'congressional districts only',
  ], 1, 'The notes say isolines are used for weather and elevation.'),
  mc('m19', M, 'The class example of an isoline map is', [
    'Temperature on January 31st, 2019',
    'Soccer Stadiums',
    'Interstate Highways',
    'Average Years of Schooling',
  ], 0, 'Temperature on January 31st, 2019 is the isoline example.'),
  multi('m20', M, 'Topographic maps can show elevation through', [
    'textured areas of the map',
    'lines and their distance apart',
    'country size distorted by GDP',
    'only satellite photos with no lines',
  ], [0, 1], 'Topographic maps show elevation with textured areas and/or contour lines and how far apart those lines are.'),
  mc('m21', M, 'Which list is the set of thematic map types from the notes?', [
    'political, physical, road',
    'choropleth, dot-density, graduated/proportional symbol, cartogram, isoline & topographic',
    'Mercator, Robinson, Gall-Peters',
    'GIS, GPS, remote sensing',
  ], 1, 'Those five (plus topographic) are the thematic types listed in 1.1.1.'),
  mc('m22', M, 'Which of these is a reference map, not a thematic map?', [
    'choropleth of literacy rates',
    'cartogram of population',
    'political map of countries and capitals',
    'dot-density of gun violence',
  ], 2, 'Political maps are a type of reference map.'),
  mc('m23', M, 'If a map uses darker shades of one color to show higher values in each state, it is most likely a', [
    'reference road map',
    'choropleth map',
    'Mercator projection',
    'dot-density map',
  ], 1, 'Colors/shades showing distribution of spatial data = choropleth.'),
  mc('m24', M, 'If country size is stretched so that bigger countries have more people, the map is a', [
    'physical reference map',
    'isoline map',
    'cartogram',
    'GPS track',
  ], 2, 'Cartograms distort area to show a variable.'),
  mc('m25', M, 'A map of equal-value weather lines is best classified as', [
    'an isoline map',
    'a political map',
    'a road map',
    'a cartogram',
  ], 0, 'Isolines connect points of equal value and are used for weather.'),

  mc('p1', P, 'Absolute location is', [
    'a description using nearby landmarks',
    'exact and precise, such as an address or latitude and longitude',
    'always measured in minutes of travel time',
    'the same as relative direction',
  ], 1, 'Absolute location is exact/precise: address or lat/long.'),
  mc('p2', P, 'Rio de Janeiro’s absolute location in the notes is', [
    '23°N, 43°E',
    '23°S, 43°W',
    '43°S, 23°W',
    '0°, 0°',
  ], 1, 'Rio de Janeiro is located at 23°S, 43°W.'),
  mc('p3', P, 'To find Rio using the notes’ method, you', [
    'look for 23° south of the equator, then move west from the prime meridian to 43°',
    'start at the North Pole and move east 23°',
    'only use a street address',
    'look for 43° north, then 23° east',
  ], 0, 'Find the 23°S parallel, go to the prime meridian, then west to 43°.'),
  mc('p4', P, 'Relative location describes', [
    'exact latitude and longitude only',
    'relationship to another place',
    'miles on a map scale',
    'cardinal directions only',
  ], 1, 'Relative location is a relationship to another place.'),
  mc('p5', P, 'Which is an example of relative location from the notes?', [
    '23°S, 43°W',
    'Oak Hills is 21.3 miles away',
    'Next to my house / between Werk & Lawrence',
    'North, South, East, West',
  ], 2, '“Next to my house” and “between Werk & Lawrence” are relative location.'),
  mc('p6', P, 'Absolute distance is', [
    'how connected two places feel',
    'exact/precise miles, kilometers, or feet',
    'always a left or right turn',
    'the same as clustering',
  ], 1, 'Absolute distance is exact: miles/kilometers/feet.'),
  mc('p7', P, '“Oak Hills is 21.3 miles away from my house” is an example of', [
    'relative location',
    'absolute distance',
    'relative direction',
    'clustering',
  ], 1, 'A measured mileage is absolute distance.'),
  mc('p8', P, 'Map scale is listed in the notes with', [
    'relative direction',
    'absolute distance',
    'thematic map types',
    'GII',
  ], 1, 'Map scale is grouped with absolute distance.'),
  mc('p9', P, 'Relative distance is tied to spatial interaction, which means', [
    'exact feet between two doors',
    'connections, contacts, movement, and flow of things between places',
    'only latitude and longitude',
    'SADD distortion',
  ], 1, 'Spatial interaction = connections, contacts, movement, and flow between places.'),
  mc('p10', P, 'The Amazon/Prime example shows that', [
    'absolute location never changes',
    'Amazon has drastically decreased relative distance between consumers and products',
    'map scale is the only way to measure distance',
    'Rio moved closer to the equator',
  ], 1, 'Two-day Prime delivery decreased relative distance.'),
  mc('p11', P, 'Absolute direction uses', [
    'left and right at landmarks',
    'cardinal directions: N, S, E, W',
    'travel time only',
    'dot density',
  ], 1, 'Absolute direction is exact cardinal directions.'),
  mc('p12', P, '“Turn left at the Target, then right at the second stop-sign” is', [
    'absolute location',
    'absolute direction',
    'relative direction',
    'a cartogram',
  ], 2, 'Relative direction is relationship-based, like left/right at landmarks.'),
  mc('p13', P, 'The notes say to remember that “relative” means', [
    'exact and precise',
    'relationships',
    'always north',
    'only map scale',
  ], 1, 'Remember: relative = relationships.'),
  mc('p14', P, 'Clustering means things are', [
    'far apart',
    'close together',
    'perfectly even worldwide',
    'only found at the poles',
  ], 1, 'Clustering = close together.'),
  mc('p15', P, 'Density is', [
    'the way something is spread out over an area',
    'the number of something in a defined area',
    'always the same as relative direction',
    'a type of map projection',
  ], 1, 'Density = the # of something in a defined area.'),
  mc('p16', P, 'Dispersal / distribution means things are', [
    'close together',
    'far apart',
    'always clustered in one city',
    'measured only in lat/long',
  ], 1, 'Dispersal/distribution = far apart.'),
  mc('p17', P, 'Distribution is', [
    'the way something is spread out over an area',
    'the number of something in one building',
    'exact cardinal direction',
    'GDP per capita',
  ], 0, 'Distribution = how something is spread out over an area.'),
  mc('p18', P, 'Patterns and spatial associations indicate that', [
    'maps never distort Earth',
    'two or more phenomena may be related, associated, or correlated',
    'absolute location is impossible',
    'every map is a cartogram',
  ], 1, 'Spatial association suggests phenomena may be related or correlated.'),
  multi('p19', P, 'The notes list these as pattern ideas to know', [
    'density',
    'concentration',
    'pattern',
    'gross national product',
  ], [0, 1, 2], 'The spatial-pattern slide lists density, concentration, and pattern.'),
  mc('p20', P, 'Which pair is absolute (exact/precise) rather than relative?', [
    'next to my house; turn left at Target',
    'latitude & longitude; miles/kilometers/feet; cardinal directions NSEW',
    'Amazon Prime delivery time; between Werk & Lawrence',
    'clustering and dispersal only',
  ], 1, 'Absolute = exact location, distance, and cardinal direction.'),
  mc('p21', P, 'Spatial patterns on maps in 1.1.2 include', [
    'only choropleth colors',
    'absolute and relative distance and direction, clustering, dispersal, and elevation',
    'only GIS layers',
    'only Brandt Line',
  ], 1, 'That is the essential-knowledge list for spatial patterns on maps.'),

  mc('j1', J, 'All maps are selective in information, and map projections inevitably distort', [
    'only color and font',
    'shape, area, distance, and direction',
    'only country names',
    'only elevation',
  ], 1, 'Projections distort spatial relationships in shape, area, distance, and direction.'),
  mc('j2', J, 'A map projection is', [
    'a GIS software license',
    'the process of a cartographer showing the curved surface of the Earth on a flat surface',
    'a census every 10 years',
    'a type of economic sector',
  ], 1, 'Projection = putting the curved Earth on a flat map.'),
  mc('j3', J, 'Maps are selective in what they portray, so different projections are', [
    'all identical',
    'used for different purposes',
    'illegal to change',
    'only used by GPS',
  ], 1, 'Different projections are used for different purposes.'),
  mc('j4', J, 'Map projections are “S.A.D.D.” because they distort', [
    'Scale, Altitude, Data, Density',
    'Shape, Area, Distance, Direction',
    'States, Areas, Dots, Districts',
    'Soil, Agriculture, Drainage, Dams',
  ], 1, 'SADD = Shape, Area, Distance, Direction.'),
  mc('j5', J, 'The Mercator projection was created in', [
    '1492',
    '1569',
    '1776',
    '2020',
  ], 1, 'Mercator (1569).'),
  mc('j6', J, 'The purpose of the Mercator projection is', [
    'showing equal land area',
    'navigation',
    'a perfect compromise with no distortion',
    'census funding',
  ], 1, 'Mercator’s purpose is navigation.'),
  multi('j7', J, 'Advantages of Mercator listed in the notes are', [
    'direction',
    'shape',
    'accurate area near the poles',
    'no distortion anywhere',
  ], [0, 1], 'Mercator advantages: direction and shape.'),
  mc('j8', J, 'Mercator preserves', [
    'equal area of all countries',
    'right angles of latitude and longitude',
    'only elevation',
    'relative distance for Amazon Prime',
  ], 1, 'It preserves right angles of latitude and longitude.'),
  multi('j9', J, 'Disadvantages of Mercator include', [
    'area distorted near the poles',
    'increases size of high latitude areas',
    'shapes are perfect at the poles',
    'it cannot show direction',
  ], [0, 1], 'Poles are too big: area is distorted and high-latitude areas look larger.'),
  mc('j10', J, 'Gall-Peters is an', [
    'equal-area projection',
    'navigation-only projection with no area goal',
    'isoline weather map',
    'economic theory',
  ], 0, 'The notes call it Gall-Peters Equal Area.'),
  multi('j11', J, 'Advantages of Gall-Peters include', [
    'areas of landmasses are accurate',
    'repositions many countries to their rightful size',
    'shapes are perfect near the poles',
    'no vertical stretch anywhere',
  ], [0, 1], 'Landmass areas are accurate and countries are closer to rightful size.'),
  multi('j12', J, 'Disadvantages of Gall-Peters include', [
    'shapes are inaccurate near the poles',
    'vertically stretched near the equator',
    'direction is its only purpose',
    'it hides all landmasses',
  ], [0, 1], 'Shapes warp near the poles and land looks vertically stretched near the equator.'),
  mc('j13', J, 'The purpose of the Robinson projection is', [
    'navigation with perfect direction',
    'compromise',
    'showing only Antarctica',
    'census redistricting',
  ], 1, 'Robinson’s purpose is compromise.'),
  mc('j14', J, 'An advantage of Robinson is', [
    'no major distortions',
    'perfect area at the poles',
    'zero distortion of every property',
    'it is not a map',
  ], 0, 'Robinson has no major distortions.'),
  mc('j15', J, 'A disadvantage of Robinson is', [
    'only the poles exist',
    'all aspects are slightly distorted',
    'it cannot be used as a compromise',
    'it preserves nothing at all and is blank',
  ], 1, 'All aspects are slightly distorted.'),
  multi('j16', J, 'Other projections named in the notes are', [
    'Conic',
    'Azimuthal',
    'Fuller',
    'Gini',
  ], [0, 1, 2], 'Others listed: Conic, Azimuthal, Fuller.'),
  mc('j17', J, 'The big point of the projection section is that', [
    'one map can show Earth with zero distortion',
    'all maps are selective and distort the earth',
    'only Mercator is ever used',
    'projections do not matter',
  ], 1, 'All maps are selective and distort the earth.'),
  mc('j18', J, 'A cartographer is a', [
    'census worker only',
    'map maker',
    'core-country CEO',
    'remote-sensing satellite',
  ], 1, 'The notes define cartographer as map maker.'),
  mc('j19', J, 'If you need a map for ship navigation that keeps lat/long as right angles, choose', [
    'Gall-Peters',
    'Robinson',
    'Mercator',
    'a cartogram',
  ], 2, 'Mercator is for navigation and preserves right angles of lat/long.'),
  mc('j20', J, 'If you want landmasses shown at accurate area (rightful size), choose', [
    'Mercator',
    'Gall-Peters Equal Area',
    'a road reference map',
    'a dot-density map',
  ], 1, 'Gall-Peters is the equal-area projection in the notes.'),
]
