import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SECTOR_QUESTIONS: VocabQuestion[] = [
  q('sec-pri-1', 'sectors', 'Primary Sector',
    'After the drought, jobs disappear first among people who grow crops and raise livestock.',
    ['Secondary Sector', 'Tertiary Sector', 'Informal Sector'],
    'Taking food from the land is Primary. Mills would be Secondary. Shops would be Tertiary. Informal Sector is whether work is recorded.'),
  q('sec-pri-2', 'sectors', 'Primary Sector',
    'The mine closes. The hospital and grocery stay open.',
    ['Quaternary Sector', 'Quinary Sector', 'Built Environment'],
    'Extracting ore is Primary. Quaternary is information work. Quinary is top decisions. Built Environment is the town itself.'),
  q('sec-pri-3', 'sectors', 'Primary Sector',
    'The boats come back empty, and only then do the canneries go quiet.',
    ['Secondary Sector', 'Tertiary Sector', 'Commodity Dependence'],
    'Fishing is Primary. Canneries are Secondary. Shops are Tertiary. Commodity Dependence would be if fish dominate the whole country’s exports.'),
  q('sec-pri-4', 'sectors', 'Primary Sector',
    'A wheat field, a copper pit, a fishing boat, and a logging crew.',
    ['Secondary Sector', 'Land Use', 'Sustainability'],
    'All four extract raw materials, so they are Primary. Sawing logs into boards would be Secondary. Land Use is how a parcel is assigned. Sustainability is whether the resource can last.'),
  q('sec-pri-5', 'sectors', 'Primary Sector',
    'Most workers still earn a living by growing crops or digging minerals.',
    ['Quaternary Sector', 'Quinary Sector', 'Gender Gap'],
    'Crops and minerals are Primary. Quaternary and Quinary are knowledge and leadership jobs. Gender Gap is a male–female difference.'),

  q('sec-sec-1', 'sectors', 'Secondary Sector',
    'Imported aluminum is stamped into phone frames in a factory.',
    ['Primary Sector', 'Tertiary Sector', 'Quaternary Sector'],
    'Turning metal into a product is Secondary. Mining it would be Primary. Selling phones is Tertiary. Design is Quaternary.'),
  q('sec-sec-2', 'sectors', 'Secondary Sector',
    'The plants that turned steel and glass into cars shut down.',
    ['Primary Sector', 'Quinary Sector', 'Formal Sector'],
    'Auto assembly is Secondary. Iron mining is Primary. Headquarters decisions are Quinary. Formal Sector only means the plants were legal.'),
  q('sec-sec-3', 'sectors', 'Secondary Sector',
    'Imported cloth is sewn into shirts for export.',
    ['Tertiary Sector', 'Quaternary Sector', 'Informal Sector'],
    'Making garments is Secondary. Retail is Tertiary. Design is Quaternary. Informal Sector would be unregistered home sewing.'),
  q('sec-sec-4', 'sectors', 'Secondary Sector',
    'The country used to export only raw cotton. Now thousands work in plants that turn it into shirts.',
    ['Primary Sector', 'Quinary Sector', 'Vernacular Region'],
    'Processing cotton into shirts is Secondary. Growing it is Primary. Quinary is top leadership. A vernacular region is a perceived area.'),
  q('sec-sec-5', 'sectors', 'Secondary Sector',
    'Logs go in one side of the mill. Boards come out the other.',
    ['Primary Sector', 'Tertiary Sector', 'Cartographic Scale'],
    'The mill manufactures a product, so it is Secondary. Cutting trees is Primary. Selling boards is Tertiary. Cartographic Scale is a map ratio.'),

  q('sec-ter-1', 'sectors', 'Tertiary Sector',
    'New jobs appear in hotels, buses, restaurants, and shops.',
    ['Secondary Sector', 'Quaternary Sector', 'Quinary Sector'],
    'Everyday services are Tertiary. Factories are Secondary. Research is Quaternary. Top officials are Quinary.'),
  q('sec-ter-2', 'sectors', 'Tertiary Sector',
    'After the airport opens, the town hires hotel staff, taxi drivers, and guides. The olive groves stay the same size.',
    ['Primary Sector', 'Secondary Sector', 'Cultural Landscape'],
    'Hotels, taxis, and guides are Tertiary. Groves are Primary. A workshop would be Secondary. Cultural Landscape is the visible imprint.'),
  q('sec-ter-3', 'sectors', 'Tertiary Sector',
    'A teacher, a nurse, and a truck driver.',
    ['Quaternary Sector', 'Primary Sector', 'Pattern'],
    'Education, health care, and transport are Tertiary. Quaternary is specialized research. Primary is extraction. Pattern is arrangement.'),
  q('sec-ter-4', 'sectors', 'Tertiary Sector',
    'The port expands, and hiring rises in trucking, warehouses, and import shops.',
    ['Primary Sector', 'Quaternary Sector', 'Formal Sector'],
    'Moving and selling goods is Tertiary. Digging ore is Primary. Writing software is closer to Quaternary. Formal Sector only means the firms are registered.'),
  q('sec-ter-5', 'sectors', 'Tertiary Sector',
    'A city bus, a grocery checkout, and a hair salon.',
    ['Quaternary Sector', 'Primary Sector', 'Commodity Dependence'],
    'These are ordinary services: Tertiary. Quaternary is research. Primary is extraction. Commodity Dependence is export mix.'),

  q('sec-qua-1', 'sectors', 'Quaternary Sector',
    'The office towers fill with software engineers and financial analysts, not hotel staff.',
    ['Tertiary Sector', 'Quinary Sector', 'Secondary Sector'],
    'Information and analysis are Quaternary. Hotels are Tertiary. CEOs are Quinary. Factories are Secondary.'),
  q('sec-qua-2', 'sectors', 'Quaternary Sector',
    'Chemists run trials and file patents. Next door, a plant bottles the medicine.',
    ['Secondary Sector', 'Tertiary Sector', 'Quinary Sector'],
    'Research and patents are Quaternary. Bottling is Secondary. A clinic would be Tertiary. The board funding it is Quinary.'),
  q('sec-qua-3', 'sectors', 'Quaternary Sector',
    'The team can work from almost any city because its product is knowledge, not a mine or a shop.',
    ['Primary Sector', 'Informal Sector', 'Site'],
    'Knowledge work is Quaternary. Primary needs a resource. Informal Sector is unrecorded work. Site is the ground itself.'),
  q('sec-qua-4', 'sectors', 'Quaternary Sector',
    'Routine clerks are replaced by a smaller staff that models risk for clients worldwide.',
    ['Tertiary Sector', 'Primary Sector', 'Human Development Index'],
    'Specialized intellectual work is Quaternary. Old clerks were routine Tertiary service. Primary is extraction. HDI is a development index.'),
  q('sec-qua-5', 'sectors', 'Quaternary Sector',
    'One building serves meals. The other writes research software.',
    ['Tertiary Sector', 'Quinary Sector', 'Literacy Rate'],
    'The lab is Quaternary. The restaurant is Tertiary. A cabinet secretary would be Quinary. Literacy Rate is a social indicator.'),

  q('sec-qui-1', 'sectors', 'Quinary Sector',
    'A handful of executives and officials decide to close the mill. Thousands of factory jobs then disappear.',
    ['Quaternary Sector', 'Tertiary Sector', 'Formal Sector'],
    'The people who made the call are Quinary. Analysts who briefed them are Quaternary. Factory work is not the sector asked. Formal Sector only means the work is legal.'),
  q('sec-qui-2', 'sectors', 'Quinary Sector',
    'After the storm, a president, a bank chair, and a grocery-chain chief decide funds, rates, and food shipments.',
    ['Quaternary Sector', 'Tertiary Sector', 'Human Environment Interaction'],
    'Highest-level leadership is Quinary. Analysts are Quaternary. Warehouse staff are Tertiary. Human-environment interaction is the disaster, not the job type.'),
  q('sec-qui-3', 'sectors', 'Quinary Sector',
    'A university president and a foundation director choose which city gets the new hospital. Architects come later.',
    ['Quaternary Sector', 'Secondary Sector', 'Functional Region'],
    'The leaders making the call are Quinary. Architects are closer to Quaternary. Construction is Secondary. A hospital service area would be a Functional Region.'),
  q('sec-qui-4', 'sectors', 'Quinary Sector',
    'The cabinet and the board choose to move headquarters. The staff who wrote the reports did not.',
    ['Quaternary Sector', 'Tertiary Sector', 'World Systems Theory'],
    'Highest-level strategy is Quinary. Briefing writers are Quaternary. Everyday services are Tertiary. World Systems Theory is a development model.'),
  q('sec-qui-5', 'sectors', 'Quinary Sector',
    'Heads of state sign the climate deal. Scientists wrote the reports; the signatures change policy.',
    ['Quaternary Sector', 'Primary Sector', 'Isoline Map'],
    'The signers are Quinary. Scientists are Quaternary. Primary is extraction. An isoline map could show temperature.'),
]
