import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_THEORY_QUESTIONS: VocabQuestion[] = [
  q('th-wst-1', 'theories', 'World Systems Theory',
    'One country designs electronics and keeps most of the profit, another assembles the parts for lower wages, and a third mainly exports cocoa beans. Which theory explains this unequal global arrangement?',
    ['Dependency Model', 'Commodity Dependence', 'Primary Sector'],
    'Core, semi-periphery, and periphery roles in one global economy are World Systems Theory. The Dependency Model focuses on a poorer country staying tied to a wealthier one. Commodity Dependence is reliance on raw exports. Primary Sector only names extraction work.'),
  q('th-wst-2', 'theories', 'World Systems Theory',
    'A geographer argues that wealthy industrial countries and poorer export countries are connected through one global economy rather than developing separately. Which concept is being applied?',
    ['Dependency Model', 'Human Development Index', 'Formal Region'],
    'Treating countries as linked parts of one unequal global economy is World Systems Theory. The Dependency Model is a related idea about lasting dependence, not the three-tier system. HDI ranks well-being. A formal region shares a measurable trait.'),
  q('th-wst-3', 'theories', 'World Systems Theory',
    'High-profit banking and design stay in a few wealthy countries, while many tropical countries continue to export ores and crops. Which theory groups countries by these economic roles?',
    ['Environmental Determinism', 'Tertiary Sector', 'National Scale'],
    'Grouping the world into core, semi-periphery, and periphery roles is World Systems Theory. Environmental Determinism would blame climate. Tertiary Sector is services. National Scale is one country.'),
  q('th-wst-4', 'theories', 'World Systems Theory',
    'South Korea moved from low-wage factory work into electronics design, while several nearby countries still specialize in cheap assembly and farm exports. Which theory allows some countries to occupy this middle economic role?',
    ['Dependency Model', 'Quinary Sector', 'Possibilism'],
    'A middle, semi-periphery role inside one global economy is World Systems Theory. The Dependency Model stresses lasting dependence more than climbing. Quinary Sector is top leadership jobs. Possibilism is about environment and choice.'),
  q('th-wst-5', 'theories', 'World Systems Theory',
    'Copper is mined in one country, refined in another, and branded by firms in a third. A student treats each country as an isolated case. Which theory instead sees them as positions in one global division of labor?',
    ['Commodity Dependence', 'Site', 'Cartogram'],
    'One connected global division of labor is World Systems Theory. Commodity Dependence would only describe relying on copper exports. Site is local physical character. A cartogram resizes map area by data.'),

  q('th-dep-1', 'theories', 'Dependency Model',
    'After independence, a country still exports raw fruit and imports machinery from the same wealthy partner that once controlled it. Which theory explains why the poorer country remains economically tied to the wealthier one?',
    ['World Systems Theory', 'Commodity Dependence', 'Formal Sector'],
    'Lasting economic ties rooted in unequal and colonial relationships are the Dependency Model. World Systems Theory zooms out to a three-tier world economy. Commodity Dependence notes a raw export but not the control relationship. Formal Sector is taxed work.'),
  q('th-dep-2', 'theories', 'Dependency Model',
    'A former colony nationalizes a mine but must still sell the ore through foreign brokers and repay loans in another country’s currency. Which concept explains why political independence has not produced economic independence?',
    ['World Systems Theory', 'Remittances', 'Possibilism'],
    'Remaining dependent on wealthier countries for markets, credit, and technology is the Dependency Model. World Systems Theory is the broader core–periphery system. Remittances are migrant transfers. Possibilism is environmental choice.'),
  q('th-dep-3', 'theories', 'Dependency Model',
    'Inexpensive imported cloth from a wealthier country replaces local weaving, and cocoa still leaves unprocessed. Critics say trade has reproduced an older colonial division of labor. Which theory is being used?',
    ['World Systems Theory', 'Secondary Sector', 'Small-Scale Maps'],
    'Unequal trade that keeps a poorer country in its old colonial role is the Dependency Model. World Systems Theory would emphasize worldwide core and periphery positions. Secondary Sector is manufacturing. Small-scale maps show large areas.'),
  q('th-dep-4', 'theories', 'Dependency Model',
    'A poor country’s ports were built to ship bananas out. Years later it still buys machines and credit from the same wealthy partner. Which AP Human Geography term best applies to this situation?',
    ['Commodity Dependence', 'Gini Coefficient', 'Functional Region'],
    'A poorer country remaining tied to a wealthier one is the Dependency Model. Commodity Dependence is concentration on one export. Gini measures inequality inside a country. A functional region is organized around a node.'),
  q('th-dep-5', 'theories', 'Dependency Model',
    'Farmers grow inexpensive coffee; foreign firms roast and brand it at a much higher price. The poorer country’s budget then depends on a price it does not set. Which theory explains this unequal partnership?',
    ['Purchasing Power Parity', 'Quaternary Sector', 'Sense of Place'],
    'Wealthier countries remaining in control through an unequal economic relationship is the Dependency Model. PPP compares what money can buy. Quaternary Sector is information work. Sense of Place is attachment to a locality.'),

  q('th-com-1', 'theories', 'Commodity Dependence',
    'A government cannot pay teachers when the world price of its only major mineral falls. Which concept explains this vulnerability?',
    ['World Systems Theory', 'Primary Sector', 'Informal Sector'],
    'Heavy reliance on one raw export whose price can collapse is Commodity Dependence. World Systems Theory is a broader global hierarchy. Primary Sector is the type of work, not the dangerous concentration of exports. Informal Sector is unrecorded work.'),
  q('th-com-2', 'theories', 'Commodity Dependence',
    'Almost all of a country’s foreign earnings come from selling one raw material whose price is set on world markets. Which term describes this economic condition?',
    ['Dependency Model', 'Secondary Sector', 'Remittances'],
    'Relying on raw-material exports is Commodity Dependence. The Dependency Model is the broader rich/poor relationship. Secondary Sector is manufacturing. Remittances are migrant transfers.'),
  q('th-com-3', 'theories', 'Commodity Dependence',
    'Chile, Zambia, and Venezuela each had boom years followed by budget crises when the same export price dropped. Factories remained a small share of exports. Which vocabulary concept explains this pattern?',
    ['World Systems Theory', 'Gini Coefficient', 'Local Scale'],
    'National earnings tied to raw-material prices is Commodity Dependence. World Systems Theory is a world hierarchy. Gini is income inequality. Local Scale is neighborhood-level analysis.'),
  q('th-com-4', 'theories', 'Commodity Dependence',
    'A Pacific island has a growing tourist industry, but the government still cannot fund schools when its main mineral price falls. Which term is represented by this example?',
    ['Life Expectancy', 'Formal Region', 'Distance Decay'],
    'The budget still depends on one raw export, which is Commodity Dependence. Life Expectancy is years lived. A formal region shares a trait. Distance Decay is fading interaction with distance.'),
  q('th-com-5', 'theories', 'Commodity Dependence',
    'A country builds factories and a new capital, but nearly all money from abroad still comes from one crop whose price it does not control. Which concept is being demonstrated?',
    ['Quinary Sector', 'Built Environment', 'Relative Location'],
    'Foreign earnings from one primary product is Commodity Dependence. Quinary Sector is top decision-making. Built Environment is buildings and roads. Relative Location is position compared with other places.'),
]
