import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_REGION_QUESTIONS: VocabQuestion[] = [
  q('reg-reg-1', 'regions', 'Region',
    'A geographer treats the Sahel, the Midwest, and Latin America as portions of Earth that share enough traits to be studied as units. Which concept names this kind of area?',
    ['Place', 'Location', 'Cartographic Scale'],
    'An area distinguished by shared characteristics is a Region. Place is one meaningful locality. Location is a position. Cartographic Scale is a map ratio.'),
  q('reg-reg-2', 'regions', 'Region',
    'News reports that “the Sun Belt is gaining House seats.” That phrase does not name one city or one official border. It names a multi-place area used to explain a pattern. Which term applies?',
    ['Site', 'Absolute Location', 'Quinary Sector'],
    'Treating a multi-place area as a unit is a Region. Site is local physical character. Absolute Location is a coordinate. Quinary Sector is elite decision-making.'),
  q('reg-reg-3', 'regions', 'Region',
    'A student says every study must concern one city or the entire world. The teacher also uses middle-sized units such as “Southeast Asia.” Which vocabulary term names those units?',
    ['Toponyms', 'Life Expectancy', 'Remote Sensing'],
    'Those middle-sized units are regions. Toponyms are names. Life Expectancy is a health measure. Remote Sensing is satellite data.'),
  q('reg-reg-4', 'regions', 'Region',
    'A student studies the Corn Belt, a radio station’s listening area, and “the South” as people imagine it. All three are areas treated as units. Which concept do they share?',
    ['Thematic Map', 'Primary Sector', 'Purchasing Power Parity'],
    'They are types of regions. A thematic map can show them. Primary Sector is extraction. PPP adjusts prices.'),
  q('reg-reg-5', 'regions', 'Region',
    'A geographer talks about Europe and the Corn Belt as portions of Earth that can be studied as units because they share characteristics. Which AP Human Geography term best applies?',
    ['Pattern', 'Space', 'Small-Scale Maps'],
    'The grouping itself is a Region. Pattern is the arrangement you might then see. Space is the abstract surface. Small-scale maps can show large areas but are a map choice.'),

  q('reg-for-1', 'regions', 'Formal Region',
    'Every county in a state uses the same official language on government forms. The shared, measurable trait draws the area. Which type of area is this?',
    ['Functional Region', 'Vernacular Region', 'Cartogram'],
    'A shared measurable characteristic is a Formal Region. Functional is nodal. Vernacular is perceived. A cartogram resizes area by data.'),
  q('reg-for-2', 'regions', 'Formal Region',
    'A map of official-language states and a wheat belt by percent of land in wheat both draw borders where a measurable trait is present. Which term applies?',
    ['Functional Region', 'Vernacular Region', 'Relative Location'],
    'A shared, documentable trait makes a Formal Region. A Functional Region is organized by a node and flows. A Vernacular Region exists in people’s heads. Relative Location is position compared with other places.'),
  q('reg-for-3', 'regions', 'Formal Region',
    'Quebec can be mapped with a legal boundary and a majority-French census result. A trucker’s delivery area around Montreal is a different kind of unit. Which concept describes Quebec in this example?',
    ['Functional Region', 'Vernacular Region', 'Situation'],
    'A legal border plus a measurable language majority is a Formal Region. The delivery area is Functional. “The North” as an identity would be Vernacular. Situation is location relative to other places.'),
  q('reg-for-4', 'regions', 'Formal Region',
    'A climate zone can be drawn where the same rainfall and temperature rules apply. That is not “the South” as tourists imagine it. Which vocabulary term is the climate zone?',
    ['Vernacular Region', 'Functional Region', 'Sense of Place'],
    'A uniform measurable rule makes a Formal Region. Tourist “the South” is Vernacular. An airport commuter shed is Functional. Sense of Place is emotional attachment.'),
  q('reg-for-5', 'regions', 'Formal Region',
    'A shaded map of literacy by country treats each country as one class. The membership rule is a statistic, not a perception and not a delivery route. Which type of area is each country in this map?',
    ['Functional Region', 'Vernacular Region', 'Time-Space Compression'],
    'One measurable class per unit is a Formal Region. Functional needs a node. Vernacular is a mental map. Time-space compression is shrinking travel time.'),

  q('reg-fun-1', 'regions', 'Functional Region',
    'A newspaper’s readers and a pizza shop’s deliveries both weaken as one moves away from a central office. Which type of area is organized this way?',
    ['Formal Region', 'Vernacular Region', 'Distance Decay'],
    'A node plus flows is a Functional Region. Formal areas share a trait. Vernacular areas are perceived. Distance Decay helps explain why sales fall, but the type of area is Functional.'),
  q('reg-fun-2', 'regions', 'Functional Region',
    'Dallas–Fort Worth airport’s passenger shed includes towns in Oklahoma that do not share Texas laws. Those towns belong because flights and trucks link them to the hub. Which term applies?',
    ['Formal Region', 'Vernacular Region', 'Absolute Location'],
    'A hinterland defined by links to a hub is a Functional Region. They are not in a formal Texas political unit. “Texan” identity would be Vernacular. Absolute Location is the airport’s coordinates.'),
  q('reg-fun-3', 'regions', 'Functional Region',
    'When a city’s only trauma hospital closes, nearby counties lose a shared emergency system even though their crops and accents have not changed. Which concept is being demonstrated?',
    ['Formal Region', 'Vernacular Region', 'Built Environment'],
    'A hospital service area is a Functional Region. Crop belts would be Formal if measured. Accents as identity could be Vernacular. The building is Built Environment, not the service area.'),
  q('reg-fun-4', 'regions', 'Functional Region',
    'A commuter rail line creates an area that exists only while people travel to the downtown station. If the line closes, the area disappears. Which vocabulary term is this?',
    ['Formal Region', 'Vernacular Region', 'Primary Sector'],
    'A commuter shed is Functional. Formal would still exist as a political unit. Vernacular would still exist in people’s heads. Primary Sector is extraction.'),
  q('reg-fun-5', 'regions', 'Functional Region',
    'A radio station’s listeners fade as one drives away from the tower. The area exists because of links to that station. Which AP Human Geography term best applies?',
    ['Formal Region', 'Vernacular Region', 'Isoline Map'],
    'Organized around a node = Functional Region. Formal is uniform traits. Vernacular is perceived. Isolines could map signal strength but are a map type.'),

  q('reg-ver-1', 'regions', 'Vernacular Region',
    'People talk about “the South” as part of their identity, but they disagree about which states belong. Which type of area is this?',
    ['Formal Region', 'Functional Region', 'Gini Coefficient'],
    'An area defined by perception and identity is a Vernacular Region. Formal is measurable. Functional is nodal. Gini is income inequality.'),
  q('reg-ver-2', 'regions', 'Vernacular Region',
    'Americans can point to “the Midwest,” but they disagree about Missouri. There is no single official rule — only a shared mental map. Which term applies?',
    ['Formal Region', 'Functional Region', 'Cartogram'],
    'A fuzzy mental map is a Vernacular Region. Formal needs one measurable rule. Functional needs a node. A cartogram resizes area by data.'),
  q('reg-ver-3', 'regions', 'Vernacular Region',
    'Tourism advertisements sell “New England fall” and “the Outback.” Residents argue about the edges, and no census table defines them. Which concept is being demonstrated?',
    ['Formal Region', 'Functional Region', 'Toponyms'],
    'Marketed, argued-over mental areas are Vernacular. Formal would have a legal definition. Functional would be Boston’s rail shed. Toponyms are the names; the question asks for the type of area.'),
  q('reg-ver-4', 'regions', 'Vernacular Region',
    'A survey asks Texans to outline “West Texas.” Sketches overlap around Lubbock and fray near Austin. The area is real in people’s minds, not as a county. Which vocabulary term is this?',
    ['Formal Region', 'Functional Region', 'Pattern'],
    'Overlapping mental maps with fuzzy edges are Vernacular. A county is Formal. A water-district service area is Functional. Pattern is arrangement.'),
  q('reg-ver-5', 'regions', 'Vernacular Region',
    'Two students draw “the Middle East” with different borders. Both drawings are usable in class because the area is defined by belief, not one treaty line. Which term is represented by this example?',
    ['Formal Region', 'Functional Region', 'Remote Sensing'],
    'A believed-in area with disagreed edges is Vernacular. Formal would be a state with a legal border. Functional would be a hub’s hinterland. Remote Sensing is satellite data.'),
]
