import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_REGION_QUESTIONS: VocabQuestion[] = [
  q('reg-reg-1', 'regions', 'Region',
    'The Sahel, the Midwest, and Latin America are treated as portions of Earth that can be studied as units.',
    ['Place', 'Location', 'Cartographic Scale'],
    'An area distinguished by shared characteristics is a Region. Place is one meaningful locality. Location is a position. Cartographic Scale is a map ratio.'),
  q('reg-reg-2', 'regions', 'Region',
    'News says “the Sun Belt is gaining House seats.” That is not one city and not one official border.',
    ['Site', 'Absolute Location', 'Quinary Sector'],
    'A multi-place area used as a unit is a Region. Site is local physical character. Absolute Location is a coordinate. Quinary Sector is elite decision-making.'),
  q('reg-reg-3', 'regions', 'Region',
    'The teacher uses middle-sized units such as “Southeast Asia,” not only one city or the entire world.',
    ['Toponyms', 'Life Expectancy', 'Remote Sensing'],
    'Those middle-sized units are regions. Toponyms are names. Life Expectancy is a health measure. Remote Sensing is satellite data.'),
  q('reg-reg-4', 'regions', 'Region',
    'The Corn Belt, a radio station’s listening area, and “the South” as people imagine it.',
    ['Thematic Map', 'Primary Sector', 'Purchasing Power Parity'],
    'All three are types of regions. A thematic map can show them. Primary Sector is extraction. PPP adjusts prices.'),
  q('reg-reg-5', 'regions', 'Region',
    'Europe and the Corn Belt are talked about as portions of Earth that share characteristics.',
    ['Pattern', 'Space', 'Small-Scale Maps'],
    'The grouping itself is a Region. Pattern is the arrangement you might then see. Space is the abstract surface. Small-scale maps can show large areas.'),

  q('reg-for-1', 'regions', 'Formal Region',
    'Every county in the state uses the same official language on government forms.',
    ['Functional Region', 'Vernacular Region', 'Cartogram'],
    'A shared measurable trait is a Formal Region. Functional is nodal. Vernacular is perceived. A cartogram resizes area by data.'),
  q('reg-for-2', 'regions', 'Formal Region',
    'Official-language states and a wheat belt drawn by percent of land in wheat.',
    ['Functional Region', 'Vernacular Region', 'Relative Location'],
    'A shared, documentable trait is a Formal Region. A Functional Region is organized by a node. A Vernacular Region exists in people’s heads. Relative Location is position compared with other places.'),
  q('reg-for-3', 'regions', 'Formal Region',
    'Quebec can be mapped with a legal boundary and a majority-French census result. A delivery area around Montreal is a different kind of unit.',
    ['Functional Region', 'Vernacular Region', 'Situation'],
    'A legal border plus a measurable language majority is a Formal Region. The delivery area is Functional. Identity would be Vernacular. Situation is relative position.'),
  q('reg-for-4', 'regions', 'Formal Region',
    'A climate zone is drawn where the same rainfall and temperature rules apply. That is not “the South” as tourists imagine it.',
    ['Vernacular Region', 'Functional Region', 'Sense of Place'],
    'A uniform measurable rule is a Formal Region. Tourist “the South” is Vernacular. A commuter shed is Functional. Sense of Place is attachment.'),
  q('reg-for-5', 'regions', 'Formal Region',
    'Each country is one class on a literacy map. The rule is a statistic, not a feeling and not a delivery route.',
    ['Functional Region', 'Vernacular Region', 'Time-Space Compression'],
    'One measurable class per unit is a Formal Region. Functional needs a node. Vernacular is a mental map. Time-space compression is shrinking travel time.'),

  q('reg-fun-1', 'regions', 'Functional Region',
    'Newspaper readers and pizza deliveries both weaken as one moves away from a central office.',
    ['Formal Region', 'Vernacular Region', 'Distance Decay'],
    'A node plus flows is a Functional Region. Formal areas share a trait. Vernacular areas are perceived. Distance Decay helps explain why sales fall.'),
  q('reg-fun-2', 'regions', 'Functional Region',
    'Towns in Oklahoma belong to the Dallas airport’s passenger shed because flights and trucks link them to the hub.',
    ['Formal Region', 'Vernacular Region', 'Absolute Location'],
    'A hinterland defined by links to a hub is a Functional Region. They are not in a Texas political unit. Identity would be Vernacular. Absolute Location is the airport’s coordinates.'),
  q('reg-fun-3', 'regions', 'Functional Region',
    'The trauma hospital closes, and nearby counties lose a shared emergency system. Crops and accents have not changed.',
    ['Formal Region', 'Vernacular Region', 'Built Environment'],
    'A hospital service area is a Functional Region. Crop belts would be Formal if measured. Accents as identity could be Vernacular. The building is Built Environment.'),
  q('reg-fun-4', 'regions', 'Functional Region',
    'The commuter area exists only while people travel to the downtown station. If the line closes, the area disappears.',
    ['Formal Region', 'Vernacular Region', 'Primary Sector'],
    'A commuter shed is Functional. Formal would still exist as a political unit. Vernacular would still exist in people’s heads. Primary Sector is extraction.'),
  q('reg-fun-5', 'regions', 'Functional Region',
    'Radio listeners fade as one drives away from the tower. The area exists because of links to that station.',
    ['Formal Region', 'Vernacular Region', 'Isoline Map'],
    'Organized around a node is a Functional Region. Formal is uniform traits. Vernacular is perceived. Isolines could map signal strength but are a map type.'),

  q('reg-ver-1', 'regions', 'Vernacular Region',
    'People talk about “the South” as part of who they are, but they disagree about which states belong.',
    ['Formal Region', 'Functional Region', 'Gini Coefficient'],
    'An area defined by perception and identity is a Vernacular Region. Formal is measurable. Functional is nodal. Gini is income inequality.'),
  q('reg-ver-2', 'regions', 'Vernacular Region',
    'Americans can point to “the Midwest,” but they argue about Missouri. There is no single official rule.',
    ['Formal Region', 'Functional Region', 'Cartogram'],
    'A fuzzy mental map is a Vernacular Region. Formal needs one measurable rule. Functional needs a node. A cartogram resizes area by data.'),
  q('reg-ver-3', 'regions', 'Vernacular Region',
    'Ads sell “New England fall” and “the Outback.” Residents argue about the edges. No census table defines them.',
    ['Formal Region', 'Functional Region', 'Toponyms'],
    'Marketed, argued-over mental areas are Vernacular. Formal would have a legal definition. Functional would be Boston’s rail shed. Toponyms are the names.'),
  q('reg-ver-4', 'regions', 'Vernacular Region',
    'Texans sketch “West Texas.” The drawings overlap around Lubbock and fray near Austin.',
    ['Formal Region', 'Functional Region', 'Pattern'],
    'Overlapping mental maps with fuzzy edges are Vernacular. A county is Formal. A water-district service area is Functional. Pattern is arrangement.'),
  q('reg-ver-5', 'regions', 'Vernacular Region',
    'Two students draw “the Middle East” with different borders. Both drawings are usable because the area is defined by belief.',
    ['Formal Region', 'Functional Region', 'Remote Sensing'],
    'A believed-in area with disagreed edges is Vernacular. Formal would be a state with a legal border. Functional would be a hub’s hinterland. Remote Sensing is satellite data.'),
]
