import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SPATIAL_QUESTIONS: VocabQuestion[] = [
  q('spa-spc-1', 'spatial', 'Space',
    'A geographer studies the empty stretch between grain elevators and the interval between cell towers as a geometric problem — how features are arranged and separated — before asking what any one stop means.',
    ['Place', 'Sense of Place', 'Toponyms'],
    'The abstract, measurable surface of distances and arrangements is Space. Place is a location with character. Sense of Place is emotional attachment. Toponyms are names.'),
  q('spa-spc-2', 'spatial', 'Space',
    'Two pharmacies can occupy similar neighborhood roles, yet a modeler still asks how far apart they sit and whether service areas overlap. That second question treats the city as distances and areas.',
    ['Place', 'Cultural Landscape', 'Vernacular Region'],
    'Distances and overlap are questions about Space. Place would be each pharmacy’s meaning. Cultural Landscape is the visible imprint. A vernacular region is a perceived area.'),
  q('spa-spc-3', 'spatial', 'Space',
    '“Near things are more related than distant things” is a claim about how interaction behaves across a continuous surface, not about one town’s identity.',
    ['Place', 'Site', 'Formal Region'],
    'A continuous surface on which near and far can be measured is Space. Place and Site describe particular locations. A formal region is one way of grouping that surface.'),
  q('spa-spc-4', 'spatial', 'Space',
    'Two cities have a similar downtown character. A second question is how many miles apart they sit.',
    ['Place', 'Toponyms', 'Literacy Rate'],
    'Mileage and separation are Space. Place is the downtown character. Toponyms are names. Literacy Rate is schooling.'),
  q('spa-spc-5', 'spatial', 'Space',
    'A planner measures how far two stores sit apart and whether their service areas overlap, without asking what either store means to residents.',
    ['Place', 'Sense of Place', 'Human Development Index'],
    'Geometric arrangement is Space. Place is unique character. Sense of Place is feeling. HDI is a development index.'),

  q('spa-loc-1', 'spatial', 'Location',
    'Before a geographer asks what Cairo is like, the first fact is simply where it is — on the Nile, at a set of coordinates.',
    ['Place', 'Sense of Place', 'Pattern'],
    'The “where” of something is Location. Place adds distinctive character. Sense of Place adds feeling. Pattern is how several things are arranged.'),
  q('spa-loc-2', 'spatial', 'Location',
    'A shipping contract specifies a berth, not a description of the city’s food or architecture. The legal fact that matters is the position of the cargo.',
    ['Place', 'Cultural Landscape', 'Sustainability'],
    'Position of the cargo is Location. Place would be the city’s character. Cultural Landscape would be the visible portscape. Sustainability is a resource-use idea.'),
  q('spa-loc-3', 'spatial', 'Location',
    'Epidemics are mapped first as “cases occurred here and here,” which is a statement of position, and only later as “this neighborhood feels abandoned.”',
    ['Sense of Place', 'Toponyms', 'Quinary Sector'],
    'Pinning events to positions is Location. Sense of Place is the later feeling. Toponyms would be the neighborhood names. Quinary Sector is elite jobs.'),
  q('spa-loc-4', 'spatial', 'Location',
    'A missing-person report begins with this, not with “what the town means to residents.”',
    ['Sense of Place', 'Human Development Index', 'Informal Sector'],
    'The starting “where” is Location. Sense of Place is meaning. HDI is well-being. Informal Sector is unrecorded work.'),
  q('spa-loc-5', 'spatial', 'Location',
    'A report first states where a factory is — on the river, at a set of coordinates — before describing the town’s character.',
    ['Pattern', 'Land Use', 'Gini Coefficient'],
    'Where something is — exact or compared — is Location. Pattern is arrangement of many things. Land Use is how a parcel is used. Gini is inequality.'),

  q('spa-plc-1', 'spatial', 'Place',
    'A city is not just a pin on a map. Its streets, food, history, and buildings make it feel unlike the next city over.',
    ['Location', 'Space', 'Absolute Location'],
    'A location plus its distinctive character is Place. Location or Absolute Location would be enough if only the pin mattered. Space would be the abstract gap between cities.'),
  q('spa-plc-2', 'spatial', 'Place',
    'A refugee says, “I can return to the same coordinate, but the market and who feels safe there are gone, so it is not the same.” The coordinate survived; something else did not.',
    ['Location', 'Site', 'Cartographic Scale'],
    'The unique ensemble of meanings and characteristics is Place. The coordinate is Location. Site (physical setting) may also have survived. Cartographic Scale is a map ratio.'),
  q('spa-plc-3', 'spatial', 'Place',
    'Tourism boards sell “Tuscany” as an experience that cannot be obtained by substituting any other coordinate with similar weather. They are selling uniqueness.',
    ['Space', 'Friction of Distance', 'Gini Coefficient'],
    'Uniqueness of a locality is Place. Space is interchangeable geometry. Friction of Distance is the cost of movement. Gini is inequality.'),
  q('spa-plc-4', 'spatial', 'Place',
    'Two strip malls can have the same style of parking lot and still not feel like the same town.',
    ['Space', 'Cartogram', 'Formal Sector'],
    'The distinctive town character is Place. Space is the lot geometry. A cartogram is a map type. Formal Sector is taxed work.'),
  q('spa-plc-5', 'spatial', 'Place',
    'Two towns share similar weather, but residents say each one has its own character and story.',
    ['Location', 'Absolute Location', 'Primary Sector'],
    'Location plus character is Place. A pin alone is Location or Absolute Location. Primary Sector is extraction.'),

  q('spa-sit-1', 'spatial', 'Site',
    'New Orleans was built on a river-mouth swamp below sea level with rich soils and a large harbor basin — facts about the ground itself.',
    ['Situation', 'Relative Location', 'Sense of Place'],
    'Local physical characteristics are Site. Situation and Relative Location are about connections to other places. Sense of Place is how people feel about it.'),
  q('spa-sit-2', 'spatial', 'Site',
    'A semiconductor firm rejects an attractive downtown because the parcel lacks stable power, vibration-free bedrock, and ultra-pure water, regardless of airport proximity.',
    ['Situation', 'Time-Space Compression', 'Vernacular Region'],
    'On-parcel physical and infrastructural traits are Site. Airport closeness would be situation. Time-space compression is shrinking effective distance. A vernacular region is a mental area.'),
  q('spa-sit-3', 'spatial', 'Site',
    'A ski town exists because of steep slopes and reliable snow. Being far from a capital is a different kind of fact.',
    ['Situation', 'Toponyms', 'Formal Region'],
    'The ridge, terraces, and springs are Site. “Remote from Spanish power” is situation. Toponyms are names. A formal region is a uniform area.'),
  q('spa-sit-4', 'spatial', 'Site',
    'Singapore has a deep harbor. That fact would remain true if no other city existed.',
    ['Situation', 'World Scale', 'Remittances'],
    'The harbor itself is Site. Sitting on the Malacca route is situation. World Scale compares countries. Remittances are migrant money.'),
  q('spa-sit-5', 'spatial', 'Site',
    'Farmers chose a valley because of its soil, rainfall, and a river for irrigation — facts about the ground itself.',
    ['Situation', 'Location', 'Thematic Map'],
    'Physical character is Site. Situation is relative to other places. Location is the broader “where.” A thematic map shows a data theme.'),

  q('spa-situ-1', 'spatial', 'Situation',
    'Chicago’s rise is difficult to explain from swampy soils alone. The decisive fact was its position between Great Lakes shipping and the Mississippi–rail system.',
    ['Site', 'Sense of Place', 'Isoline Map'],
    'Location relative to transport systems and other cities is Situation. The swampy soils are Site. Sense of Place is attachment. An isoline map is a display technique.'),
  q('spa-situ-2', 'spatial', 'Situation',
    'Singapore’s harbor depths are favorable, but many other harbors are also deep. What made it a hub is sitting astride the Malacca route.',
    ['Site', 'Absolute Location', 'Primary Sector'],
    'Astride a world route is Situation. Harbor depth is Site. The coordinate is Absolute Location. Primary Sector is extraction.'),
  q('spa-situ-3', 'spatial', 'Situation',
    'A factory town declines after the interstate and the container port shift 80 miles away, even though its river water and flat land are unchanged. The local ground did not fail; its connections did.',
    ['Site', 'Built Environment', 'Literacy Rate'],
    'Connections to markets and networks are Situation. Unchanged water and land are Site. Buildings still standing are Built Environment. Literacy Rate is schooling.'),
  q('spa-situ-4', 'spatial', 'Situation',
    'Istanbul mattered because it sat between the Black Sea and the Mediterranean, not only because of its hills.',
    ['Site', 'Pattern', 'Informal Sector'],
    'Between other places is Situation. Hills are Site. Pattern is arrangement. Informal Sector is unrecorded work.'),
  q('spa-situ-5', 'spatial', 'Situation',
    'A town’s advantage is sitting between two rail lines and a large market, not the quality of its soil.',
    ['Site', 'Space', 'Gini Coefficient'],
    'Relative to other places is Situation. Site is the ground itself. Space is the geometric surface. Gini is inequality.'),

  q('spa-sen-1', 'spatial', 'Sense of Place',
    'Residents oppose a glass tower not because the coordinate is incorrect or the soil cannot support it, but because the street “feels like home.”',
    ['Site', 'Location', 'Cartogram'],
    'Emotional and cultural attachment is Sense of Place. Site is physical capability. Location is position. A cartogram is a map type.'),
  q('spa-sen-2', 'spatial', 'Sense of Place',
    'A displaced family and a tourist can stand on the same hill and not share the same meaning: one has memory and loss, the other has a viewpoint. The hill’s geology is identical.',
    ['Site', 'Absolute Location', 'Secondary Sector'],
    'Meaning and attachment are Sense of Place. Geology is Site. The coordinate is Absolute Location. Secondary Sector is manufacturing.'),
  q('spa-sen-3', 'spatial', 'Sense of Place',
    'College towns market “game-day atmosphere” as something visitors report they can feel.',
    ['Formal Region', 'Friction of Distance', 'Gini Coefficient'],
    'A felt atmosphere tied to a locality is Sense of Place. A formal region would need a measurable rule. Friction of Distance is travel cost. Gini is inequality.'),
  q('spa-sen-4', 'spatial', 'Sense of Place',
    'After urban renewal, the streets remain but long-time residents say “this is not our neighborhood anymore.”',
    ['Absolute Location', 'Cartographic Scale', 'Primary Sector'],
    'Lost attachment is Sense of Place. The coordinate is still Absolute Location. Cartographic Scale is a map ratio. Primary Sector is extraction.'),
  q('spa-sen-5', 'spatial', 'Sense of Place',
    'College students say they can “feel” game day downtown. The streets did not move; the meaning did.',
    ['Location', 'Site', 'Choropleth Map'],
    'The feeling is Sense of Place. Location is the pin. Site is the soil. A choropleth shades statistical units.'),

  q('spa-top-1', 'spatial', 'Toponyms',
    'Istanbul / Constantinople / Byzantium and Mumbai / Bombay are contests over who may label a location. The coordinate did not change; the name did.',
    ['Absolute Location', 'Site', 'Pattern'],
    'Place-names, and the politics of naming, are Toponyms. The coordinate is Absolute Location. Site is the physical setting. Pattern is arrangement.'),
  q('spa-top-2', 'spatial', 'Toponyms',
    'A United States map still shows Spanish saint names and Anglicized Indigenous names, each layer recording a different power at the moment of labeling.',
    ['Vernacular Region', 'Cultural Landscape', 'Reference Map'],
    'The names themselves are Toponyms. They are a clue to cultural landscape, but the vocab word for the names is toponyms. A vernacular region is a perceived area. A reference map is one place the names appear.'),
  q('spa-top-3', 'spatial', 'Toponyms',
    'After independence, a country changes the names of its capital and several cities so maps no longer use colonial labels.',
    ['Site', 'Situation', 'Cartographic Scale'],
    'Rewriting official names is a toponym change. The ground (site) and the region’s connections (situation) were not what the law renamed. Cartographic Scale is the map ratio.'),
  q('spa-top-4', 'spatial', 'Toponyms',
    '“Los Angeles,” “New York,” and “St. Louis” tell a migration and colonial story before one even looks at the skyline.',
    ['Absolute Location', 'Gini Coefficient', 'Remote Sensing'],
    'The words are Toponyms. Absolute Location would be the coordinates. Gini is inequality. Remote Sensing is satellite data.'),
  q('spa-top-5', 'spatial', 'Toponyms',
    'A city once labeled Bombay is now Mumbai on every official sign. The pin on the map did not move.',
    ['Location', 'Place', 'Formal Region'],
    'The name is a Toponym. Location is the position. Place is the character. A Formal Region is a uniform area.'),

  q('spa-tsc-1', 'spatial', 'Time-Space Compression',
    'A designer in Milan can send a file to a factory in Shenzhen in seconds and fly there in a day. The kilometers did not shrink; the time and cost did.',
    ['Distance Decay', 'Friction of Distance', 'Absolute Location'],
    'Technology making far places feel nearer is Time-Space Compression. Distance Decay is the usual drop-off of interaction with distance. Friction of Distance is the cost that compression reduces. Absolute Location is unchanged.'),
  q('spa-tsc-2', 'spatial', 'Time-Space Compression',
    'New York and London share overlapping trading hours and fiber-optic links, so a price shock crosses the Atlantic faster than a nineteenth-century letter crossed a county.',
    ['Distance Decay', 'Site', 'Formal Sector'],
    'The collapse of time-over-distance is Time-Space Compression. Distance Decay would predict less interaction with more miles. Site is local ground. Formal Sector is legal work.'),
  q('spa-tsc-3', 'spatial', 'Time-Space Compression',
    'Container ships, jet aircraft, and video calls allow a family in Lagos to operate a shop whose suppliers are in Guangzhou.',
    ['Environmental Determinism', 'Literacy Rate', 'Choropleth Map'],
    'Far-flung daily integration is Time-Space Compression. Environmental Determinism would say climate decides the economy. Literacy Rate is schooling. A choropleth shades rates.'),
  q('spa-tsc-4', 'spatial', 'Time-Space Compression',
    'A family in one city runs a shop whose suppliers are on another continent, using video calls and container ships.',
    ['Distance Decay', 'Absolute Location', 'Primary Sector'],
    'The world feeling smaller is Time-Space Compression. Distance Decay is interaction fading with miles. Absolute Location is a pin. Primary Sector is extraction.'),
  q('spa-tsc-5', 'spatial', 'Time-Space Compression',
    'It used to take weeks to send a letter across the ocean. Now a video call happens in seconds, so far cities feel closer.',
    ['Friction of Distance', 'Small-Scale Maps', 'Gini Coefficient'],
    'That shrinking of effective distance is Time-Space Compression. Friction of Distance is the cost being reduced. Small-scale maps show large areas. Gini is inequality.'),

  q('spa-fri-1', 'spatial', 'Friction of Distance',
    'A mountain range, a visa, a toll, and a poor road all make the next town farther in time and money even when the kilometer reading is modest.',
    ['Distance Decay', 'Time-Space Compression', 'Absolute Location'],
    'The effort, time, and money required to move is Friction of Distance. Distance Decay is the resulting drop in interaction. Time-space compression is the historical reduction of that friction. Absolute Location is the kilometer reading.'),
  q('spa-fri-2', 'spatial', 'Friction of Distance',
    'Two villages 8 km apart interact less than two villages 20 km apart on a highway because a river with no bridge lies between the first pair. Kilometers are not the real barrier.',
    ['Distance Decay', 'Pattern', 'Choropleth Map'],
    'The river is raising the cost of movement — Friction of Distance. Distance Decay would describe the interaction outcome. Pattern is the arrangement of villages. A choropleth is a map type.'),
  q('spa-fri-3', 'spatial', 'Friction of Distance',
    'A firm pays more to ship steel than to ship software the same number of miles, so steel plants remain nearer mines while software teams disperse.',
    ['Time-Space Compression', 'Sense of Place', 'Literacy Rate'],
    'Steel still has high movement cost — high Friction of Distance. Time-space compression is the long-run decline in that cost. Sense of Place and Literacy Rate are not transport-cost concepts.'),
  q('spa-fri-4', 'spatial', 'Friction of Distance',
    'Before railroads, moving grain 100 miles inland was often not worthwhile.',
    ['Site', 'Toponyms', 'Gender Gap'],
    'The cost of those miles is Friction of Distance. Site is local physical character. Toponyms are names. Gender Gap is a social difference.'),
  q('spa-fri-5', 'spatial', 'Friction of Distance',
    'A mountain pass and a toll road make the next town expensive to reach even though it is not many miles away.',
    ['Distance Decay', 'Time-Space Compression', 'Human Development Index'],
    'Difficulty increasing with distance is Friction of Distance. Distance Decay is the fading of the phenomenon. Time-space compression fights that difficulty. HDI is well-being.'),

  q('spa-dd-1', 'spatial', 'Distance Decay',
    'A radio station’s listeners, a pizza shop’s deliveries, and a dialect’s features all thin out as one moves away from the origin, even when no wall intervenes.',
    ['Time-Space Compression', 'Friction of Distance', 'Absolute Location'],
    'Interaction declining with distance is Distance Decay. Friction of Distance is the cost that helps cause it. Time-space compression flattens the drop-off. Absolute Location is a pin.'),
  q('spa-dd-2', 'spatial', 'Distance Decay',
    'After a new subway line, a grocery’s customer map stretches farther along the line and still declines quickly perpendicular to it.',
    ['Site', 'Toponyms', 'Human Development Index'],
    'Customers thinning with effective distance is Distance Decay. Site is the store’s parcel. Toponyms are names. HDI is a development index.'),
  q('spa-dd-3', 'spatial', 'Distance Decay',
    'A vaccine rumor spreads quickly in one city and barely appears in a town 400 km away with no social ties.',
    ['Time-Space Compression', 'Formal Region', 'Secondary Sector'],
    'Influence fading with separation is Distance Decay. Time-space compression would be if social media erased that fade. A Formal Region shares a trait. Secondary Sector is manufacturing.'),
  q('spa-dd-4', 'spatial', 'Distance Decay',
    'A new store opens across town. Its first customers live nearby; almost no one drives in from the next county.',
    ['Friction of Distance', 'Absolute Location', 'Cartogram'],
    'The drop is Distance Decay. Friction of Distance is the cost. Absolute Location is a coordinate. A cartogram resizes area.'),
  q('spa-dd-5', 'spatial', 'Distance Decay',
    'A radio station’s listeners drop off as one drives away from the tower.',
    ['Time-Space Compression', 'Possibilism', 'Quinary Sector'],
    'That fade is Distance Decay. Time-space compression reduces the fade. Possibilism is a human-environment theory. Quinary Sector is elite jobs.'),

  q('spa-pat-1', 'spatial', 'Pattern',
    'Houses on a long-lot farm system line up in strips to a river; later suburban cul-de-sacs cluster in loops. Each arrangement is a recognizable geometry.',
    ['Place', 'Sense of Place', 'Cartographic Scale'],
    'How features are arranged — linear, clustered, regular — is Pattern. Place is one locality’s character. Sense of Place is feeling. Cartographic Scale is the map ratio.'),
  q('spa-pat-2', 'spatial', 'Pattern',
    'A crime analyst says incidents are “clustered,” “dispersed,” or “random,” which is a statement about arrangement, not about why any one alley feels unsafe.',
    ['Sense of Place', 'Situation', 'Gender Gap'],
    'Clustered/dispersed/random is Pattern. Sense of Place would be the alley’s meaning. Situation is connections. Gender Gap is a social difference.'),
  q('spa-pat-3', 'spatial', 'Pattern',
    'Central-place ideas predict towns of similar size at roughly regular intervals on a uniform plain. Whether the real map matches that is a question about arrangement.',
    ['Location', 'Literacy Rate', 'Quinary Sector'],
    'Regular spacing is a spatial Pattern. Location is one town’s position. Literacy Rate is schooling. Quinary Sector is leadership jobs.'),
  q('spa-pat-4', 'spatial', 'Pattern',
    'Wind turbines stand in a straight line along a ridge, while farmhouses sit in a scattered spread. Both are recognizable arrangements.',
    ['Place', 'Absolute Location', 'Human Development Index'],
    'Linear/clustered/dispersed are types of Pattern. Place is character. Absolute Location is a coordinate. HDI is a development index.'),
  q('spa-pat-5', 'spatial', 'Pattern',
    'A crime map is labeled clustered, dispersed, or random. The labels describe how the dots sit, not why one alley feels unsafe.',
    ['Site', 'Remittances', 'Isoline Map'],
    'Geometric arrangement is Pattern. Site is local ground. Remittances are migrant transfers. Isolines could display a surface but are not the arrangement idea.'),
]
