import { mc, multi, type ApHumanPracticeQuestion } from './apHumanStudy'

const V = 'measures' as const
const T = 'theories' as const

export const DEVELOPMENT_QUESTIONS: ApHumanPracticeQuestion[] = [
  mc('v1', V, 'Development is defined as', [
    'any country that uses GIS',
    'a specified state of growth or advancement',
    'only GDP above $1 million',
    'owning a Mercator map',
  ], 1, 'Development = a specified state of growth or advancement.'),
  mc('v2', V, 'Variations in development can be seen on', [
    'only the global scale',
    'global, regional, and local scales',
    'map projections only',
    'absolute direction only',
  ], 1, 'Development varies on global, regional, and local scales.'),
  multi('v3', V, 'Ways the notes name levels of development include', [
    'Least Developed Countries / LDCs (less developed countries)',
    'Developed countries / MDCs (more developed countries)',
    'Newly Industrialized Countries',
    'SADD countries',
  ], [0, 1, 2], 'LDCs, MDCs, NICs, developing/developed are the labels used.'),
  mc('v4', V, 'When writing about development, the notes say do NOT', [
    'use indicators',
    'assess value (this country is good / that country is bad)',
    'mention job sectors',
    'use HDI',
  ], 1, 'Do not say a country is “good” or “bad.” Focus on level of development and indicators.'),
  mc('v5', V, 'A good development sentence from the notes is', [
    'This country is good and that country is bad',
    'This country is newly industrialized due to the changing job sectors from primary to secondary',
    'This country has a nicer culture',
    'This country is evil',
  ], 1, 'Focus on level of development and supporting indicators, such as sector change.'),
  mc('v6', V, '“Per capita” means', [
    'per country only',
    'per person; divide the data by the country’s population',
    'per factory',
    'per map',
  ], 1, 'Per capita = per person.'),
  mc('v7', V, 'In these measures, “gross” means', [
    'illegal',
    'total',
    'per person',
    'informal only',
  ], 1, 'Gross = total.'),
  mc('v8', V, 'GDP is the', [
    'number of infants who die per 1,000 births',
    'total value of officially recorded goods and services by the citizens and corporations within a country’s borders in a given year',
    'share of income going to the richest 1%',
    'percent of people who can read',
  ], 1, 'GDP = officially recorded goods and services within a country’s borders in a year.'),
  mc('v9', V, 'The notes summarize GDP as', [
    'goods + services = GDP',
    'exports only = GDP',
    'HDI + GII = GDP',
    'miles + feet = GDP',
  ], 0, 'goods + services = GDP.'),
  mc('v10', V, 'GNP is the', [
    'total value of goods and services by the citizens and corporations of a country as well as foreign investments in a given year',
    'number of doctors per person',
    'same as TFR',
    'only informal sales',
  ], 0, 'GNP includes citizens/corporations plus foreign investments.'),
  mc('v11', V, 'The notes summarize GNP as', [
    'goods + services = GNP',
    'domestic + international goods + services = GNP',
    'only imports = GNP',
    'Gini + HDI = GNP',
  ], 1, 'domestic + international goods + services = GNP.'),
  mc('v12', V, 'GNI is described as the most accurate measure of wealth because it', [
    'ignores trade',
    'accounts for the impacts of trade',
    'only counts garage sales',
    'is always 0',
  ], 1, 'GNI accounts for the impacts of trade.'),
  mc('v13', V, 'The notes’ GNI formula is', [
    'GDP − population',
    'GDP + (exports − imports) = GNI',
    'TFR × IMR',
    'HDI − GII',
  ], 1, 'GDP + (exports − imports) = GNI.'),
  mc('v14', V, 'Another GNI definition in the notes: GNI is the value of output of goods and services produced in a country in a year,', [
    'not counting any money that leaves or enters',
    'including money that leaves and enters the country',
    'only from primary jobs',
    'only from illegal sales',
  ], 1, 'GNI includes money that leaves and enters the country.'),
  mc('v15', V, 'GDP is different from GNI because GDP', [
    'includes money that leaves and enters the country',
    'does not include the money that leaves and enters the country',
    'is only a social indicator',
    'measures infant deaths',
  ], 1, 'GDP does not include money that leaves and enters; GNI does.'),
  mc('v16', V, '“I’m an American company, so I count toward the USA’s ___.”', [
    'GDP only, never GNP',
    'GNP',
    'Gini',
    'IMR',
  ], 1, 'An American company counts toward the USA’s GNP.'),
  mc('v17', V, '“I’m inside Japan’s borders so I’m part of their ___.”', [
    'GNP only',
    'GDP',
    'TFR',
    'Brandt Line',
  ], 1, 'Production inside Japan’s borders counts in Japan’s GDP.'),
  multi('v18', V, 'Items NOT included in GNP, GDP, or GNI', [
    'second-hand sales — garage sale, used car, pawn shop',
    'illegal products — drugs',
    'intermediate products — tires on a new car, flour in baked bread',
    'officially recorded new goods and services',
  ], [0, 1, 2], 'Used goods, illegal products, and intermediate products are excluded.'),
  mc('v19', V, 'The formal economy is the', [
    'illegal economy governments do not monitor or tax',
    'legal economy regulated by governments',
    'only primary sector',
    'only Gini',
  ], 1, 'Formal = legal and government-regulated.'),
  mc('v20', V, 'The informal economy is the', [
    'legal taxed economy',
    'illegal economy that governments do not monitor or tax',
    'only quaternary research',
    'census',
  ], 1, 'Informal = not monitored or taxed (illegal economy in the notes).'),
  mc('v21', V, 'A country with a larger formal economy is generally', [
    'less developed',
    'more developed',
    'always a periphery country',
    'unable to measure HDI',
  ], 1, 'Larger formal economy → generally more developed.'),
  mc('v22', V, 'The Gini coefficient measures', [
    'map distortion',
    'the distribution of income within a population',
    'absolute location',
    'literacy only',
  ], 1, 'Gini measures income distribution within a population.'),
  mc('v23', V, 'Gini values are between 0 and 1. The higher the number,', [
    'the lower the income inequality',
    'the higher the income inequality',
    'the higher the HDI automatically',
    'the more tertiary jobs',
  ], 1, 'Higher Gini = higher income inequality.'),
  mc('v24', V, 'Generally, MDCs have ___ Gini scores and LDCs have ___ Gini scores.', [
    'higher; lower',
    'lower; higher',
    'the same; the same',
    'no; no',
  ], 1, 'MDCs generally have lower Ginis; LDCs have higher Ginis.'),
  mc('v25', V, 'Energy consumption: MDCs have the', [
    'lowest per capita consumption of energy',
    'highest per capita consumption of energy',
    'same consumption as all LDCs',
    'no fossil fuel use ever',
  ], 1, 'MDCs have the highest per capita energy consumption.'),
  mc('v26', V, 'Demand for fossil fuels is', [
    'falling to zero in all developing countries',
    'increasing in DCs',
    'unrelated to development',
    'only a map type',
  ], 1, 'Demand for fossil fuels is increasing in DCs.'),
  mc('v27', V, 'Nuclear energy is increasing in', [
    'only the informal economy',
    'MDCs',
    'no countries',
    'cartograms',
  ], 1, 'Nuclear energy is increasing in MDCs.'),
  mc('v28', V, 'Hydroelectric energy is higher in', [
    'only failed states',
    'DCs',
    'no developed country',
    'Mercator maps',
  ], 1, 'Hydroelectric is higher in DCs.'),
  mc('v29', V, 'Annual GDP per capita averages over $20,000 in most developed countries but', [
    'over $50,000 in most LDCs',
    'under $5,000 in most less developed countries',
    'exactly $20,000 everywhere',
    'is not used as an indicator',
  ], 1, 'Most LDCs are under $5,000 GDP per capita in that figure.'),
  multi('v30', V, 'Social indicators of development in the notes include', [
    'fertility rates',
    'infant mortality rate (IMR)',
    'access to healthcare',
    'Mercator advantages',
  ], [0, 1, 2], 'Social indicators include fertility, IMR, healthcare, life expectancy, literacy, GII, and HDI.'),
  multi('v31', V, 'Which are also social indicators listed in the notes?', [
    'life expectancy',
    'literacy rates',
    'Gender Inequality Index (GII)',
    'road maps',
  ], [0, 1, 2], 'Life expectancy, literacy, GII, and HDI are listed as social measures.'),
  mc('v32', V, 'Total Fertility Rate (TFR) is the', [
    'number of infant deaths per 1,000 live births',
    'average number of children per woman',
    'percent who can read',
    'Gini score',
  ], 1, 'TFR = average number of children per woman.'),
  mc('v33', V, 'TFR is generally', [
    'high in LDCs and low in MDCs',
    'high in MDCs and low in LDCs',
    'the same in every country',
    'not related to development',
  ], 0, 'High in LDCs, low in MDCs.'),
  mc('v34', V, 'The TFR examples in the notes are', [
    'Niger 7.29 and Spain 1.25',
    'Japan 2 and Australia 83.4',
    'Yemen .77 and Germany .07',
    'Afghanistan 111 and Japan 2',
  ], 0, 'Niger 7.29 (high LDC) and Spain 1.25 (low MDC).'),
  mc('v35', V, 'Infant Mortality Rate (IMR) is the', [
    'average children per woman',
    'number of deaths of infants under one year old in a given year per 1,000 live births',
    'percent of adults who can read',
    'GDP + (exports − imports)',
  ], 1, 'IMR = deaths of infants under age 1 per 1,000 live births.'),
  mc('v36', V, 'The IMR examples in the notes are', [
    'Niger 7.29 and Spain 1.25',
    'Afghanistan 111 (high LDC) and Japan 2 (low MDC)',
    'CAR 50.9 and Australia 83.4',
    'Yemen .77 and Germany .07',
  ], 1, 'Afghanistan 111; Japan 2.'),
  mc('v37', V, 'Access to healthcare is generally', [
    'low in LDCs and high in MDCs',
    'high in LDCs and low in MDCs',
    'unrelated to development',
    'the same as TFR',
  ], 0, 'Healthcare access is low in LDCs and high in MDCs.'),
  mc('v38', V, 'Life expectancy is the', [
    'number of years a person is expected to live based on mortality rates when they were born',
    'number of infant deaths per 1,000',
    'percent in the informal economy',
    'size of a cartogram',
  ], 0, 'Average years expected to live based on mortality rates at birth.'),
  mc('v39', V, 'The life-expectancy examples are', [
    'Central African Republic 50.9 years (low LDC) and Australia 83.4 years (high MDC)',
    'Niger 19% and Spain 1.25',
    'Afghanistan 111 and Japan 2',
    'Yemen .77 and Germany .07',
  ], 0, 'CAR 50.9; Australia 83.4.'),
  mc('v40', V, 'Literacy rates are', [
    'high in all LDCs',
    'low in LDCs; Niger is 19%, and almost widespread for most other countries',
    'not a social indicator',
    'the same as Gini',
  ], 1, 'Literacy is low in LDCs (Niger 19%) and almost widespread elsewhere.'),
  mc('v41', V, 'The Human Development Index (HDI) is scored', [
    'from 0 to 1000',
    'between 0 and 1; low score = low development, high score = high development',
    'only as “good” or “bad”',
    'in miles',
  ], 1, 'HDI is 0–1; low = low development, high = high development.'),
  mc('v42', V, 'HDI is more accurate because it is a combination of indicators. It combines', [
    'only map colors',
    'social + economic',
    'only fossil fuels',
    'only informal jobs',
  ], 1, 'HDI combines social + economic.'),
  mc('v43', V, 'HDI is a composite measure used to show', [
    'SADD distortion',
    'spatial variation among states in levels of development',
    'only one city’s streets',
    'absolute direction',
  ], 1, 'That is the 7.3 essential-knowledge line about HDI.'),
  mc('v44', V, 'The Gender Inequality Index (GII) is scored between 0 and 1.', [
    'High value = high inequality; low value = low inequality',
    'High value = high development',
    'It only measures GDP',
    '0 means no women exist',
  ], 0, 'High GII = high inequality; low GII = low inequality.'),
  mc('v45', V, 'The GII examples in the notes are', [
    'Yemen .77 (high inequality) and Germany .07 (low inequality)',
    'Niger 7.29 and Spain 1.25',
    'Afghanistan 111 and Japan 2',
    'CAR 50.9 and Australia 83.4',
  ], 0, 'Yemen .77; Germany .07.'),
  mc('v46', V, 'GII is another combo measure, so it is more accurate. It combines', [
    'only economic data',
    'social + economic + political',
    'only map projections',
    'only primary jobs',
  ], 1, 'GII = social + economic + political.'),
  multi('v47', V, 'GII includes measures of', [
    'reproductive health',
    'indices of empowerment',
    'labor-market participation',
    'Mercator direction',
  ], [0, 1, 2], 'Those three are the official GII components in the objectives.'),
  multi('v48', V, 'Specific GII pieces listed on the slide include', [
    'maternal mortality',
    'adolescent fertility',
    'political representation',
    'isoline weather',
  ], [0, 1, 2], 'Also listed: educational attainment and labor force participation.'),
  mc('v49', V, 'Although more women are in the workforce, they do not have', [
    'any social indicators',
    'equity in wages or employment opportunities',
    'a GII score',
    'access to maps',
  ], 1, 'Women still lack equity in wages and job opportunities.'),
  mc('v50', V, 'Microloans have provided opportunities for women to', [
    'run core-country militaries',
    'create small local businesses, which have improved standards of living',
    'replace HDI',
    'end all informal work',
  ], 1, 'Microloans → small local businesses → improved standards of living.'),
  mc('v51', V, 'In 2010, the most prominent energy users in the world were', [
    'Niger and Spain',
    'the United States and China',
    'only Iceland',
    'Afghanistan and Peru',
  ], 1, 'The United States and China were the most prominent energy users in 2010.'),
  mc('v52', V, 'Like many developed nations, the United States has had high but relatively ___ rates of energy consumption for the last 30 years.', [
    'collapsing',
    'stable',
    'zero',
    'unmeasured',
  ], 1, 'U.S. consumption has been high but relatively stable.'),
  mc('v53', V, 'Many developing or emerging nations have relatively low energy consumption rates but, like China, are', [
    'rapidly increasing their use',
    'using no energy',
    'only using paper maps',
    'banning electricity',
  ], 0, 'Emerging nations are rapidly increasing energy use.'),
  mc('v54', V, 'Renewable energy sources listed include', [
    'coal, oil, and natural gas only',
    'wind, solar, geothermal, and hydroelectric',
    'only gasoline',
    'only informal charcoal',
  ], 1, 'Wind, solar, geothermal, and hydroelectric are listed.'),
  mc('v55', V, 'Developed nations tend to generate', [
    'less of their electricity from renewables',
    'more of their electricity from renewables',
    'no electricity',
    'only informal energy',
  ], 1, 'Developed nations generate more electricity from renewables.'),
  mc('v56', V, 'Iceland generates a lot of electricity from geothermal energy because of', [
    'its HDI score',
    'its unusual geology / abundant access to geothermal energy',
    'the census',
    'the Brandt Line only',
  ], 1, 'Iceland has abundant geothermal energy due to unusual geology.'),
  mc('v57', V, 'Literacy and the other social/economic rates', [
    'never match each other',
    'correspond to each other: if one is low/high in a country, it will reflect another indicator in the same country',
    'only measure maps',
    'are random',
  ], 1, 'The indicators tend to move together in the same country.'),
  multi('v58', V, 'Economic indicators listed in the notes include', [
    'GDP, GNP, and GNI',
    'sectoral structure; informal & formal',
    'income distribution / Gini; fossil fuels & renewable energy',
    'Robinson projection purpose',
  ], [0, 1, 2], 'Those are the economic-indicator bullets.'),

  mc('t1', T, 'Wallerstein’s World System Theory is also called the', [
    'Brandt Line only',
    'Core-Periphery Model',
    'Gini coefficient',
    'Mercator model',
  ], 1, 'World Systems Theory aka Core-Periphery Model.'),
  mc('t2', T, 'Theories used to explain variations in development include', [
    'only choropleth maps',
    'Wallerstein’s World Systems Theory, Dependency Theory, Brandt Line, and NICs & BRICS',
    'only GPS',
    'only SADD',
  ], 1, 'Those are the 7.5 theories/models listed.'),
  mc('t3', T, 'Wallerstein says there is a world economic system —', [
    'many totally separate economies with no links',
    'one large interconnected economy',
    'only informal garage sales',
    'only one country’s GDP',
  ], 1, 'One large interconnected economy; interdependence.'),
  mc('t4', T, 'Wallerstein explains', [
    'how to draw isolines',
    'relationships and uneven economic development',
    'only absolute location',
    'how to take the census',
  ], 1, 'He explains relationships and uneven economic development.'),
  multi('t5', T, 'What characterizes Wallerstein in the notes?', [
    'legacy of colonialism',
    'competition between core countries for colonies and trade',
    'military strength',
    'SADD map letters',
  ], [0, 1, 2], 'Colonialism, core competition for colonies/trade, and military strength.'),
  mc('t6', T, 'A key Wallerstein question in the notes is: how can a country develop when', [
    'it has too many tertiary jobs',
    'its resources are controlled by a few industrialized countries',
    'it uses GIS',
    'it has a low Gini',
  ], 1, 'Resources controlled by a few industrialized countries block development.'),
  multi('t7', T, 'Characteristics of the CORE include', [
    'economically and politically dominant',
    'strong military and allies',
    'highly interconnected transportation and communication infrastructure',
    'weak laws to protect workers',
  ], [0, 1, 2], 'Core is dominant, militarized, and highly interconnected.'),
  multi('t8', T, 'The core also', [
    'controls the global market; businesses are headquartered there',
    'includes former colonial powers',
    'has higher-skill, capital-intensive production',
    'only exports raw materials and has low wages',
  ], [0, 1, 2], 'HQs, former colonial powers, high-skill capital-intensive production.'),
  multi('t9', T, 'Core countries listed are', [
    'US',
    'UK',
    'Japan',
    'Afghanistan',
  ], [0, 1, 2], 'Core list: US, UK, Japan, Australia, Germany.'),
  mc('t10', T, 'Which country is listed as CORE, not periphery?', [
    'Kenya',
    'Peru',
    'Australia',
    'Afghanistan',
  ], 2, 'Australia is in the core list with US, UK, Japan, and Germany.'),
  mc('t11', T, 'Semi-periphery countries are described as', [
    'the poorest with no industry',
    '“middle income” countries with aspects of the core and the periphery',
    'only former colonial powers in Europe',
    'countries with no exports',
  ], 1, 'Semi-periphery = middle income, mix of core and periphery.'),
  multi('t12', T, 'Semi-periphery countries are', [
    'in the process of industrialization',
    'active in manufacturing and exporting goods and raw materials',
    'better in transportation and communication than the periphery',
    'always the most dominant militaries',
  ], [0, 1, 2], 'Industrializing, manufacturing/exporting, better infrastructure than the periphery.'),
  mc('t13', T, 'NICs and BRICS are placed in the', [
    'core only',
    'semi-periphery',
    'only the periphery',
    'SADD category',
  ], 1, 'NICs & BRICS are listed under semi-periphery.'),
  multi('t14', T, 'Semi-periphery countries listed include', [
    'Brazil',
    'Russia',
    'India',
    'Kenya',
  ], [0, 1, 2], 'Brazil, Russia, India, China, South Africa, Mexico.'),
  mc('t15', T, 'Mexico is listed as', [
    'core',
    'semi-periphery',
    'only a map type',
    'not discussed',
  ], 1, 'Mexico is in the semi-periphery list with the BRICS.'),
  multi('t16', T, 'Periphery characteristics include', [
    'often unstable governments',
    'less wealth and lower levels of education than the core',
    'export natural resources to core and semi-periphery',
    'control of the global market',
  ], [0, 1, 2], 'Unstable governments, less wealth/education, export resources.'),
  multi('t17', T, 'The periphery also has', [
    'not reliable transportation or communication infrastructure',
    'former colonies',
    'low-skill, labor-intensive jobs and low wages',
    'business headquarters of the global market',
  ], [0, 1, 2], 'Weak infrastructure, former colonies, low-skill/low-wage work.'),
  mc('t18', T, 'Periphery countries have', [
    'the strongest worker-protection laws',
    'weak laws to protect workers',
    'only quinary CEOs',
    'HDI of 1 always',
  ], 1, 'Weak laws to protect workers.'),
  multi('t19', T, 'Periphery countries listed are', [
    'Afghanistan',
    'Peru',
    'Kenya',
    'Germany',
  ], [0, 1, 2], 'Afghanistan, Peru, Kenya.'),
  mc('t20', T, 'In Dependency Theory, the periphery', [
    'sells expensive consumer goods to the core',
    'sends cheap labor and natural resources to the semi-periphery and core',
    'controls the global market',
    'has all the HQs',
  ], 1, 'Periphery sends cheap labor and natural resources upward.'),
  mc('t21', T, 'In Dependency Theory, the core', [
    'only farms',
    'buys raw materials, pays for cheap labor, and sells consumer goods for high prices',
    'has no money flow',
    'is always an LDC',
  ], 1, 'Core buys cheap inputs and sells expensive consumer goods.'),
  mc('t22', T, 'The periphery pays high prices for consumer goods, which', [
    'creates extra investment money',
    'depletes money supply and opportunities for investment',
    'turns it into the core immediately',
    'has no economic effect',
  ], 1, 'High prices drain money and investment opportunities.'),
  mc('t23', T, 'The core also sells consumer goods and provides money flow to the', [
    'Moon',
    'semi-periphery and periphery',
    'only Antarctica',
    'SADD projections',
  ], 1, 'Money and consumer goods flow from core to SP and P.'),
  mc('t24', T, 'The Brandt Line is also called the', [
    'East-West railroad',
    'North-South Divide',
    'Mercator grid',
    'Gini line',
  ], 1, 'Brandt Line aka the North-South Divide.'),
  mc('t25', T, 'Generally, according to the Brandt Line,', [
    'MDCs are in the south and LDCs are in the north',
    'MDCs are in the north and LDCs are in the south',
    'every country is an MDC',
    'development has no spatial pattern',
  ], 1, 'MDCs north; LDCs south.'),
  mc('t26', T, 'Recently, many NICs (newly industrialized countries) emerged in the', [
    'north only',
    'south',
    'Arctic only',
    'core of the US and UK only',
  ], 1, 'Many NICs have emerged in the south.'),
  mc('t27', T, 'BRICS originally refers to', [
    'Belgium, Romania, Italy, Canada, Spain',
    'Brazil, Russia, India, China, and South Africa',
    'Britain, Rwanda, Iran, Cuba, Sudan',
    'only the US and Japan',
  ], 1, 'Originally Brazil, Russia, India, China, and South Africa.'),
  mc('t28', T, 'BRICS countries want to', [
    'keep western-dominated trade unchanged',
    'oppose western-dominated trade relationships',
    'ban all industry',
    'end the census',
  ], 1, 'They want to oppose western-dominated trade relationships.'),
  mc('t29', T, 'BRICS countries are considered the countries most likely to', [
    'leave the world economy',
    'move into the core',
    'become only primary economies',
    'stop using maps',
  ], 1, 'Most likely to move into the core.'),
  mc('t30', T, 'NIC stands for', [
    'National Isoline Cartogram',
    'Newly Industrialized Country',
    'Northern Income Cartogram',
    'Nuclear Informal Census',
  ], 1, 'Newly Industrialized Country.'),
  mc('t31', T, 'Wallerstein’s theory is used in the standards to explain', [
    'types of reference maps',
    'spatial variations in development',
    'how to take aerial photos',
    'SADD letters only',
  ], 1, '7.5: Wallerstein’s World System Theory explains spatial variations in development.'),
  mc('t32', T, 'Gender inequality as an indicator of development includes', [
    'only GDP',
    'reproductive health, indices of empowerment, and labor-market participation',
    'only Mercator shape',
    'only clustering',
  ], 1, 'Those three are the gender-inequality measures in the 7.5 notes.'),
]
