import { mc, multi, type ApHumanPracticeQuestion } from './apHumanStudy'

const S = 'sectors' as const

export const SECTOR_QUESTIONS: ApHumanPracticeQuestion[] = [
  mc('e1', S, 'Primary economic activities are the', [
    'service sector that sells products',
    'extraction of raw materials and natural resources from the earth’s surface',
    'highest levels of government decision-making',
    'knowledge-based research sector',
  ], 1, 'Primary = extracting raw materials and natural resources from Earth’s surface.'),
  multi('e2', S, 'Examples of primary activities include', [
    'mining',
    'fishing',
    'agriculture',
    'software development',
  ], [0, 1, 2], 'Primary examples: mining, fishing, agriculture, and forestry.'),
  mc('e3', S, 'Forestry / lumbering is a', [
    'primary activity',
    'secondary activity',
    'quaternary activity',
    'quinary activity',
  ], 0, 'Harvest from the Earth — farming, mining, fishing, lumbering — is primary.'),
  mc('e4', S, 'Secondary economic activities are', [
    'retail and restaurants',
    'processing and manufacturing raw materials into a finished product',
    'CEOs and Congress',
    'only interviews',
  ], 1, 'Secondary = factories and manufacturing raw materials into finished products.'),
  mc('e5', S, 'Factories and manufacturing are examples of the', [
    'primary sector',
    'secondary sector',
    'tertiary sector',
    'quinary sector',
  ], 1, 'Factories & manufacturing = secondary.'),
  mc('e6', S, 'Logs turned into tables is an example of', [
    'primary only',
    'secondary (manufacturing a primary product into a new product)',
    'quinary decision-making',
    'a cartogram',
  ], 1, 'Manufacturing primary products into new products is secondary.'),
  mc('e7', S, 'Diamonds turned into rings is an example of the', [
    'primary sector',
    'secondary sector',
    'quaternary sector',
    'informal economy only',
  ], 1, 'Processing plant: uncut diamond → ring is secondary.'),
  mc('e8', S, 'Tertiary economic activities are the', [
    'extraction of raw materials',
    'service sector that focuses on moving, selling, and trading products in the primary and secondary sectors',
    'highest political offices only',
    'census every 10 years',
  ], 1, 'Tertiary = service sector: moving, selling, and trading products.'),
  multi('e9', S, 'Examples of tertiary activities include', [
    'retail',
    'marketing',
    'restaurants',
    'Congress',
  ], [0, 1, 2], 'Tertiary examples: retail, marketing, design, restaurants, shipping.'),
  mc('e10', S, 'Design and shipping are listed as', [
    'primary',
    'secondary',
    'tertiary',
    'quinary',
  ], 2, 'Design and shipping are tertiary examples.'),
  mc('e11', S, 'The tertiary sector is the service industry that', [
    'harvests from the Earth',
    'connects producers to consumers or facilitates trade',
    'only writes HDI scores',
    'is always informal',
  ], 1, 'Tertiary connects producers to consumers / facilitates trade.'),
  mc('e12', S, 'A storefront is an example of', [
    'primary',
    'secondary',
    'tertiary',
    'quinary',
  ], 2, 'Storefront is listed under tertiary.'),
  mc('e13', S, 'Quaternary economic activities are the', [
    'farming sector',
    'knowledge-based sector, focusing on research and information creation and transfer',
    'only illegal jobs',
    'political map type',
  ], 1, 'Quaternary = knowledge-based research and information.'),
  multi('e14', S, 'Examples of quaternary activities include', [
    'investment banking',
    'real estate',
    'college professors / education',
    'mining coal',
  ], [0, 1, 2], 'Quaternary examples include investment banking, real estate, college professors, education, software developers, and logistics.'),
  mc('e15', S, 'Software developers and logistics are listed as', [
    'primary',
    'secondary',
    'quaternary',
    'only informal',
  ], 2, 'Software developers and logistics are quaternary examples.'),
  mc('e16', S, 'Research & development and “logistics and data” are grouped with', [
    'primary',
    'secondary',
    'quaternary',
    'reference maps',
  ], 2, 'R&D / logistics and data = quaternary.'),
  mc('e17', S, 'Quinary economic activities are', [
    'fishing and forestry',
    'the highest levels of decision-making, including top officials in government and business',
    'only retail clerks',
    'dot-density mapping',
  ], 1, 'Quinary = highest decision-making (government and business).'),
  multi('e18', S, 'Examples of quinary activities include', [
    'Congress',
    'CEOs',
    'farming',
    'factory assembly only',
  ], [0, 1], 'Congress and CEOs are the quinary examples.'),
  mc('e19', S, 'Quinary decisions', [
    'never affect anyone',
    'impact millions',
    'only affect one farm',
    'are the same as primary extraction',
  ], 1, 'Decisions impact millions.'),
  mc('e20', S, 'In the IKEA-style chain, timber reserves are', [
    'primary',
    'secondary',
    'tertiary',
    'quinary',
  ], 0, 'Timber reserves = harvest from the Earth = primary.'),
  mc('e21', S, 'In that chain, the factory & mill is', [
    'primary',
    'secondary',
    'quaternary',
    'quinary',
  ], 1, 'Factory & mill = manufacturing = secondary.'),
  mc('e22', S, 'A distribution hub / supply chain and storefront are', [
    'primary',
    'mostly tertiary (service / connecting producers to consumers)',
    'only quinary',
    'map projections',
  ], 1, 'Storefront, shipping, and distribution are tertiary services.'),
  mc('e23', S, 'CEO & IKEA decision-makers are', [
    'primary',
    'secondary',
    'tertiary',
    'quinary',
  ], 3, 'CEOs are quinary.'),
  mc('e24', S, 'In the diamond example, the diamond mine is', [
    'primary',
    'secondary',
    'tertiary',
    'quinary',
  ], 0, 'Raw uncut diamond / mine = primary (“closest to the ground”).'),
  mc('e25', S, 'The processing plant in the diamond example is', [
    'primary',
    'secondary',
    'quaternary',
    'quinary',
  ], 1, 'Processing plant manufactures the primary product into a new product.'),
  mc('e26', S, 'Primary activities are described as', [
    'highest decision-making',
    'closest to the ground',
    'only digital jobs',
    'always in MDCs',
  ], 1, 'Primary is “closest to the ground.”'),
  mc('e27', S, 'The higher the percent of jobs in tertiary, the country is generally', [
    'less developed',
    'more developed',
    'always a periphery country',
    'unable to use GIS',
  ], 1, 'Higher % in tertiary jobs = more developed.'),
  mc('e28', S, 'The higher the percent of jobs in primary, the country is generally', [
    'more developed',
    'less developed',
    'always a core country',
    'using only nuclear energy',
  ], 1, 'Higher % in primary jobs = less developed.'),
  mc('e29', S, 'As a country becomes more developed, the primary sector', [
    'grows forever',
    'declines due to an increase in industrialization, and the tertiary sector increases',
    'replaces all tertiary jobs',
    'becomes quinary',
  ], 1, 'Development: primary declines with industrialization; tertiary increases.'),
  mc('e30', S, 'In less developed countries, the economy is mostly made up of', [
    'quinary CEOs',
    'primary economic activities',
    'only software developers',
    'only Congress',
  ], 1, 'LDC economies are mostly primary activities.'),
  mc('e31', S, 'Economic development is described as the journey of workers moving', [
    'from offices, to factories, to fields',
    'from the fields, to the factories, and into the office/digital space',
    'only from quinary to primary',
    'from GPS to GIS',
  ], 1, 'Fields → factories → office/digital space.'),
  mc('e32', S, 'The five economic sectors listed are', [
    'formal, informal, illegal, used, intermediate',
    'primary, secondary, tertiary, quaternary, and quinary',
    'core, semi-periphery, periphery, NIC, MDC',
    'choropleth, dot, symbol, cartogram, isoline',
  ], 1, 'Those five sectors are the 7.2 list.'),
  mc('e33', S, 'Quaternary and quinary are shown as parts of the broader', [
    'primary sector',
    'tertiary sector',
    'census',
    'Mercator projection',
  ], 1, 'The notes nest quaternary and quinary under the tertiary sector heading.'),
  mc('e34', S, 'A college professor is', [
    'primary',
    'secondary',
    'quaternary',
    'a physical map',
  ], 2, 'College professors / education = quaternary.'),
  mc('e35', S, 'Enduring understanding SPS-7: industrialization has facilitated improvements in standards of living, but it has also', [
    'ended all uneven development',
    'contributed to geographically uneven development',
    'removed the primary sector worldwide',
    'made every country a core country',
  ], 1, 'Industrialization improved living standards but also created geographically uneven development.'),
]
