import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_HEI_QUESTIONS: VocabQuestion[] = [
  q('hei-hei-1', 'hei', 'Human Environment Interaction',
    'Farmers cut trees for fuel, then face more drought as the soil dries.',
    ['Distance Decay', 'Choropleth Map', 'Quaternary Sector'],
    'People change Earth, and Earth changes what they can do: Human Environment Interaction. Distance Decay is fading interaction with miles. A choropleth is a map type. Quaternary Sector is information work.'),
  q('hei-hei-2', 'hei', 'Human Environment Interaction',
    'After the flood, the city rebuilds levees and also raises insurance rates.',
    ['Sustainability', 'Site', 'Formal Region'],
    'People change the river, and the river changes behavior: Human Environment Interaction. Sustainability is whether the rebuild can last. Site is the floodplain. A Formal Region is a uniform area.'),
  q('hei-hei-3', 'hei', 'Human Environment Interaction',
    'Wetlands are drained to farm. Trees are cut for fuel. Air conditioning runs in a hot city.',
    ['Built Environment', 'Environmental Determinism', 'Cultural Landscape'],
    'The exchange between people and nature is Human Environment Interaction. Built Environment is the constructed result. Environmental Determinism is one theory. Cultural Landscape is the visible imprint.'),
  q('hei-hei-4', 'hei', 'Human Environment Interaction',
    'The unit covers irrigation, air pollution, and earthquake-resistant housing together.',
    ['Possibilism', 'Land Use', 'Physical Geography'],
    'How societies use, modify, and adapt to Earth is Human Environment Interaction. Possibilism is one interpretation. Land Use is one piece. Physical Geography would stop at Earth systems.'),
  q('hei-hei-5', 'hei', 'Human Environment Interaction',
    'Terraces hold the hillside. If they fail, landslides increase.',
    ['Built Environment', 'Environmental Determinism', 'World Scale'],
    'People change slopes, and slopes affect people: Human Environment Interaction. The terrace is Built Environment. Determinism would say climate caused the culture. World Scale compares a large world area.'),

  q('hei-sus-1', 'hei', 'Sustainability',
    'This year’s catch is limited so next year’s breeding stock still exists.',
    ['Possibilism', 'Primary Sector', 'Gini Coefficient'],
    'Meeting present needs without wrecking the future is Sustainability. Possibilism is choice among options. Primary Sector is fishing as a job. Gini is inequality.'),
  q('hei-sus-2', 'hei', 'Sustainability',
    'The city can empty the aquifer in twenty years, or meter water now so it lasts.',
    ['Environmental Determinism', 'Time-Space Compression', 'Quaternary Sector'],
    'Keeping a resource for later generations is Sustainability. Environmental Determinism would say the aquifer decides fate no matter the policy. Time-space compression is shrinking distance. Quaternary Sector is knowledge work.'),
  q('hei-sus-3', 'hei', 'Sustainability',
    'Cut every old-growth tree this decade, or leave enough forest for children still to have timber and clean water.',
    ['Life Expectancy', 'Reference Map', 'Primary Sector'],
    'The future-generations choice is Sustainability. Life Expectancy is years lived. A reference map shows location. Primary Sector is the extraction job.'),
  q('hei-sus-4', 'hei', 'Sustainability',
    'Groundwater is pumped faster than rain replaces it.',
    ['Site', 'Formal Sector', 'World Systems Theory'],
    'Failing the future-generations test is a Sustainability problem. Site is the aquifer’s setting. Formal Sector is taxed work. World Systems Theory is a world hierarchy.'),
  q('hei-sus-5', 'hei', 'Sustainability',
    'The company advertises “no net deforestation” so the forest can still function later.',
    ['Commodity Dependence', 'Cultural Landscape', 'Absolute Location'],
    'Not erasing future function is a Sustainability claim. Commodity Dependence would be living on palm-oil exports. Cultural Landscape is the visible plantation. Absolute Location is a coordinate.'),

  q('hei-lu-1', 'hei', 'Land Use',
    'The field switches from corn to a solar farm. The ground did not move.',
    ['Pattern', 'Absolute Location', 'Quinary Sector'],
    'The new purpose of the field is Land Use. Pattern is how uses are arranged. Absolute Location is a coordinate. Quinary Sector is leadership jobs.'),
  q('hei-lu-2', 'hei', 'Land Use',
    'The same hectare could be a rice paddy, a parking garage, a temple garden, or a reserve.',
    ['Site', 'Built Environment', 'Formal Region'],
    'How people organize land for different purposes is Land Use. Site is the hectare’s physical traits. Built Environment is the structures. A formal region might later group similar hectares.'),
  q('hei-lu-3', 'hei', 'Land Use',
    'Zoning turns an industrial waterfront into apartments and a park.',
    ['Situation', 'Remote Sensing', 'Literacy Rate'],
    'The permitted activity changed: Land Use. Situation is the waterfront’s connections. Remote Sensing might detect the change. Literacy Rate is schooling.'),
  q('hei-lu-4', 'hei', 'Land Use',
    'Dairy sits near the city, grain farther out, and ranching even farther.',
    ['Sense of Place', 'Toponyms', 'Gender Gap'],
    'Different purposes for the land are Land Use. Sense of Place is attachment. Toponyms are names. Gender Gap is a social difference.'),
  q('hei-lu-5', 'hei', 'Land Use',
    'The rainforest is cleared and that surface becomes cattle pasture.',
    ['Remote Sensing', 'Human Development Index', 'Isoline Map'],
    'The new purpose is Land Use. Remote Sensing might detect the clearing. HDI is well-being. Isolines are a map type.'),

  q('hei-blt-1', 'hei', 'Built Environment',
    'Highways, levees, and skyscrapers that later generations inherit.',
    ['Cultural Landscape', 'Land Use', 'Site'],
    'Human-made surroundings are the Built Environment. Cultural Landscape is broader, including fields and meanings. Land Use is the activity assigned. Site is original physical character.'),
  q('hei-blt-2', 'hei', 'Built Environment',
    'Downtown concrete and asphalt run hotter than the nearby woodland.',
    ['Physical Geography', 'Possibilism', 'Vernacular Region'],
    'Poured materials making up the city are Built Environment. Physical Geography would be the woodland without the city. Possibilism is a theory of choice. A vernacular region is a mental area.'),
  q('hei-blt-3', 'hei', 'Built Environment',
    'After the earthquake, inspectors walk the buildings and bridges, not the religion or the names.',
    ['Toponyms', 'Gender Inequality Index', 'Dot Distribution Map'],
    'Buildings and bridges are the Built Environment. Toponyms are names. GII is a gender index. A dot map is a symbol type.'),
  q('hei-blt-4', 'hei', 'Built Environment',
    'A downtown of glass towers and parking decks.',
    ['Sense of Place', 'Formal Sector', 'World Scale'],
    'That constructed fabric is Built Environment. Sense of Place is meaning. Formal Sector is legal work. World Scale is a level of analysis.'),
  q('hei-blt-5', 'hei', 'Built Environment',
    'After the fire, the streets and houses remain as poured materials. The woodland they replaced does not.',
    ['Physical Geography', 'Relative Location', 'Remittances'],
    'Streets and houses are Built Environment. Physical Geography is the natural side. Relative Location is position compared with other features. Remittances are migrant money.'),

  q('hei-cl-1', 'hei', 'Cultural Landscape',
    'Rice terraces, a mosque skyline, and suburban cul-de-sacs.',
    ['Built Environment', 'Site', 'Absolute Location'],
    'The visible imprint of culture is Cultural Landscape. Built Environment is the constructed subset. Site is original physical setting. Absolute Location is a coordinate.'),
  q('hei-cl-2', 'hei', 'Cultural Landscape',
    'A battlefield monument, a fence line, and house types let a visitor read who lived there.',
    ['Environmental Determinism', 'Pattern', 'Reference Map'],
    'The humanized surface is Cultural Landscape. Environmental Determinism would say climate wrote the area. Pattern is arrangement without the cultural reading. A reference map might depict it.'),
  q('hei-cl-3', 'hei', 'Cultural Landscape',
    'From the air, street plan, barn type, and church placement distinguish two farming towns.',
    ['Vernacular Region', 'Quinary Sector', 'Gross National Income'],
    'Those signatures are Cultural Landscape. The towns may sit in a vernacular region, but the thing being read from the air is the landscape.'),
  q('hei-cl-4', 'hei', 'Cultural Landscape',
    'Fields, barns, and a church steeple mark the surface, not just one building.',
    ['Land Use', 'Site', 'Purchasing Power Parity'],
    'That fashioned surface is Cultural Landscape. Land Use is the activity assigned. Site is original physical character. PPP adjusts prices.'),
  q('hei-cl-5', 'hei', 'Cultural Landscape',
    'The human imprint you can see, not a feeling in someone’s mind.',
    ['Sense of Place', 'Built Environment', 'Formal Sector'],
    'The visible cultural imprint is Cultural Landscape. Sense of Place is the feeling. Built Environment is the constructed subset. Formal Sector is taxed work.'),

  q('hei-ed-1', 'hei', 'Environmental Determinism',
    'An old textbook said tropical heat made societies lazy and temperate climates produced civilization.',
    ['Possibilism', 'Sustainability', 'World Systems Theory'],
    'Climate deciding culture is Environmental Determinism. Possibilism is the opposing view. Sustainability is long-term resource use. World Systems Theory blames a political-economic hierarchy.'),
  q('hei-ed-2', 'hei', 'Environmental Determinism',
    'A commentator says mountain people will always be isolated and poor because of the slopes.',
    ['Possibilism', 'Human Development Index', 'Functional Region'],
    'Nature as destiny is Environmental Determinism. Possibilism rejected it. HDI is a development index. A functional region is a nodal area.'),
  q('hei-ed-3', 'hei', 'Environmental Determinism',
    'A writer claims climate made an entire culture the way it is.',
    ['Possibilism', 'Time-Space Compression', 'Choropleth Map'],
    'One-way climate cause is Environmental Determinism. Possibilism is the accepted alternative. Time-space compression is shrinking distance. A choropleth is a map type.'),
  q('hei-ed-4', 'hei', 'Environmental Determinism',
    '“That dry grassland will always be poor because the rain is unreliable.”',
    ['Possibilism', 'Commodity Dependence', 'Dependency Model'],
    'The environment as the controlling cause is Environmental Determinism. Possibilism leaves room for policy. Commodity Dependence and Dependency Model offer economic explanations.'),
  q('hei-ed-5', 'hei', 'Environmental Determinism',
    'An old map tried to match “warm climate” with “less civilization.”',
    ['Possibilism', 'Site', 'Literacy Rate'],
    'Climate writing achievement is Environmental Determinism. Possibilism rejected that. Site describes climate as a local trait, not as destiny. Literacy Rate is schooling.'),

  q('hei-pos-1', 'hei', 'Possibilism',
    'The same dry climate produced irrigated vineyards in one country and herding in another.',
    ['Environmental Determinism', 'Time-Space Compression', 'Formal Sector'],
    'Limits plus different human choices is Possibilism. Environmental Determinism would predict one “arid personality.” Time-space compression is about distance. Formal Sector is legal work.'),
  q('hei-pos-2', 'hei', 'Possibilism',
    'One flood-prone country builds dikes and pumps. Another uses embankments and stilt housing.',
    ['Environmental Determinism', 'Site', 'Gini Coefficient'],
    'Different answers to similar limits is Possibilism. Determinism would expect the same outcome. Site describes the water risk. Gini measures inequality.'),
  q('hei-pos-3', 'hei', 'Possibilism',
    'People invent air conditioning and live in a hot desert, but they still need water and power.',
    ['Environmental Determinism', 'World Systems Theory', 'Dot Distribution Map'],
    'Options widened by technology, with limits still there, is Possibilism. Environmental Determinism is what it replaced. World Systems Theory is about the world-economy. A dot map is a symbol type.'),
  q('hei-pos-4', 'hei', 'Possibilism',
    'The environment offers a range of options. Technology widens the range but does not erase every constraint.',
    ['Environmental Determinism', 'Absolute Location', 'Informal Sector'],
    'A range of options is Possibilism, not “anything is possible.” Determinism says climate decides everything. Absolute Location is a coordinate. Informal Sector is unrecorded work.'),
  q('hei-pos-5', 'hei', 'Possibilism',
    'Flood risk is answered with stilt housing in one country and with dikes in another.',
    ['Environmental Determinism', 'Cartographic Scale', 'Quinary Sector'],
    'Limits plus choice is Possibilism. Environmental Determinism is the rejected opposite. Cartographic Scale is a map ratio. Quinary Sector is elite jobs.'),
]
