import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_HEI_QUESTIONS: VocabQuestion[] = [
  q('hei-hei-1', 'hei', 'Human Environment Interaction',
    'Farmers cut trees for firewood, then suffer more drought as the soil dries out—people changed nature, and nature hit back. Which concept describes this two-way relationship between people and the natural environment?',
    ['Distance Decay', 'Choropleth Map', 'Quaternary Sector'],
    'People change Earth, and Earth changes what they can do: Human Environment Interaction. Distance Decay is fading interaction with miles. A choropleth is a map type. Quaternary Sector is information work.'),
  q('hei-hei-2', 'hei', 'Human Environment Interaction',
    'After a flood, a city builds taller levees and also raises insurance rates because the river keeps threatening homes. Which concept covers both changing the river and being changed by it?',
    ['Sustainability', 'Site', 'Formal Region'],
    'People change the river, and the river changes behavior: Human Environment Interaction. Sustainability is whether the rebuild can last. Site is the floodplain. A Formal Region is a uniform area.'),
  q('hei-hei-3', 'hei', 'Human Environment Interaction',
    'Wetlands are drained for crops, forests are cut for fuel, and air conditioners hum in a hot city—all showing how societies and nature affect each other. Which concept names this mutual connection with the natural environment?',
    ['Built Environment', 'Environmental Determinism', 'Cultural Landscape'],
    'The two-way exchange between people and nature is Human Environment Interaction. Built Environment is the constructed result. Environmental Determinism is one theory. Cultural Landscape is the visible imprint.'),
  q('hei-hei-4', 'hei', 'Human Environment Interaction',
    'A unit combines irrigation, air pollution, and earthquake-safe buildings—how people use, change, and adapt to Earth. Which concept covers how societies interact with the natural environment?',
    ['Possibilism', 'Land Use', 'Physical Geography'],
    'How societies use, modify, and adapt to Earth is Human Environment Interaction. Possibilism is one interpretation. Land Use is one piece. Physical Geography would stop at Earth systems.'),
  q('hei-hei-5', 'hei', 'Human Environment Interaction',
    'Farmers build terraces on a hillside; when terraces fail, landslides worsen downhill homes. Which concept says people alter slopes and slopes alter people’s lives?',
    ['Built Environment', 'Environmental Determinism', 'World Scale'],
    'People change slopes, and slopes affect people: Human Environment Interaction. The terrace is Built Environment. Determinism would say climate caused the culture. World Scale compares a large multi-country area.'),

  q('hei-sus-1', 'hei', 'Sustainability',
    'Fishermen limit this year’s catch so fish can breed and next year’s harvest still exists. Which concept means meeting today’s needs without ruining resources for future generations?',
    ['Possibilism', 'Primary Sector', 'Gini Coefficient'],
    'Meeting present needs without wrecking the future is Sustainability. Possibilism is choice among options. Primary Sector is fishing as a job. Gini is inequality.'),
  q('hei-sus-2', 'hei', 'Sustainability',
    'A city can drain its aquifer dry in twenty years, or meter water now so later generations still have drinking water. Which concept is choosing the second path?',
    ['Environmental Determinism', 'Time-Space Compression', 'Quaternary Sector'],
    'Keeping a resource for later generations is Sustainability. Environmental Determinism would say the aquifer decides fate no matter the policy. Time-space compression is shrinking distance. Quaternary Sector is knowledge work.'),
  q('hei-sus-3', 'hei', 'Sustainability',
    'A town can cut every old-growth tree now, or leave enough forest so children still have timber and clean water. Which concept is the responsible second choice?',
    ['Life Expectancy', 'Reference Map', 'Primary Sector'],
    'The future-generations choice is Sustainability. Life Expectancy is years lived. A reference map shows location. Primary Sector is the extraction job.'),
  q('hei-sus-4', 'hei', 'Sustainability',
    'Farmers pump groundwater faster than rain refills it, stealing water from people who will live here fifty years from now. Which concept is being broken?',
    ['Site', 'Formal Sector', 'World Systems Theory'],
    'Failing the future-generations test is a Sustainability problem. Site is the aquifer’s setting. Formal Sector is taxed work. World Systems Theory is a world hierarchy.'),
  q('hei-sus-5', 'hei', 'Sustainability',
    'A company promises “no net deforestation” so the forest still works for people in the future. Which concept is that promise about?',
    ['Commodity Dependence', 'Cultural Landscape', 'Absolute Location'],
    'Not erasing future function is a Sustainability claim. Commodity Dependence would be living on palm-oil exports. Cultural Landscape is the visible plantation. Absolute Location is a coordinate.'),

  q('hei-lu-1', 'hei', 'Land Use',
    'A farmer switches a field from corn to a solar panel farm—the land stays in the same spot but serves a new purpose. Which concept is what a piece of land is used for?',
    ['Pattern', 'Absolute Location', 'Quinary Sector'],
    'The new purpose of the field is Land Use. Pattern is how uses are arranged. Absolute Location is a coordinate. Quinary Sector is leadership jobs.'),
  q('hei-lu-2', 'hei', 'Land Use',
    'One hectare could become a rice paddy, a parking lot, a temple garden, or a nature reserve—the choice is about purpose. Which concept is the decision about what that land is for?',
    ['Site', 'Built Environment', 'Formal Region'],
    'How people organize land for different purposes is Land Use. Site is the hectare’s physical traits. Built Environment is the structures. A formal region might later group similar hectares.'),
  q('hei-lu-3', 'hei', 'Land Use',
    'Zoning changes an old factory waterfront into apartments and a park—new activities are now allowed there. Which concept describes what activities a parcel of land is used for?',
    ['Situation', 'Remote Sensing', 'Literacy Rate'],
    'The permitted activity changed: Land Use. Situation is the waterfront’s connections. Remote Sensing might detect the change. Literacy Rate is schooling.'),
  q('hei-lu-4', 'hei', 'Land Use',
    'Dairy farms sit near the city, grain fields farther out, and cattle ranches even farther—each patch has a different purpose. Which concept describes these different purposes for land?',
    ['Sense of Place', 'Toponyms', 'Gender Gap'],
    'Different purposes for the land are Land Use. Sense of Place is attachment. Toponyms are names. Gender Gap is a social difference.'),
  q('hei-lu-5', 'hei', 'Land Use',
    'A rainforest is bulldozed and the same surface becomes a cattle pasture. Which concept describes this new purpose for that land?',
    ['Remote Sensing', 'Human Development Index', 'Isoline Map'],
    'The new purpose is Land Use. Remote Sensing might detect the clearing. HDI is well-being. Isolines are a map type.'),

  q('hei-blt-1', 'hei', 'Built Environment',
    'Highways, levees, and skyscrapers are human-built structures that the next generation inherits. Which concept names this human-made constructed fabric of buildings and roads?',
    ['Cultural Landscape', 'Land Use', 'Site'],
    'Human-made buildings and roads are the Built Environment. Cultural Landscape is broader, including fields and meanings. Land Use is the activity assigned. Site is original physical character.'),
  q('hei-blt-2', 'hei', 'Built Environment',
    'Downtown concrete and asphalt bake hotter than a nearby forest because of all the poured and paved surfaces. Which concept refers to those human-made buildings, roads, and materials?',
    ['Physical Geography', 'Possibilism', 'Vernacular Region'],
    'Poured materials making up the city are Built Environment. Physical Geography would be the woodland without the city. Possibilism is a theory of choice. A vernacular region is a mental area.'),
  q('hei-blt-3', 'hei', 'Built Environment',
    'After an earthquake, inspectors check buildings and bridges—not local religion or street names. Which concept are they surveying as the human-made physical surroundings?',
    ['Toponyms', 'Gender Inequality Index', 'Dot Distribution Map'],
    'Buildings and bridges are the Built Environment. Toponyms are names. GII is a gender index. A dot map is a symbol type.'),
  q('hei-blt-4', 'hei', 'Built Environment',
    'A downtown of glass towers and parking garages is the human-constructed cityscape future residents inherit. Which term names these human-built structures?',
    ['Sense of Place', 'Formal Sector', 'World Scale'],
    'That constructed fabric is Built Environment. Sense of Place is meaning. Formal Sector is legal work. World Scale is a level of analysis.'),
  q('hei-blt-5', 'hei', 'Built Environment',
    'After a wildfire, paved streets and rebuilt houses remain where woodland once stood. Which concept is this human-made constructed surroundings?',
    ['Physical Geography', 'Relative Location', 'Remittances'],
    'Streets and houses are Built Environment. Physical Geography is the natural side. Relative Location is position compared with other features. Remittances are migrant money.'),

  q('hei-cl-1', 'hei', 'Cultural Landscape',
    'Rice terraces, mosque minarets, and suburban cul-de-sacs show how a culture has visibly shaped the land’s surface. Which concept is this visible imprint of culture on the land?',
    ['Built Environment', 'Site', 'Absolute Location'],
    'The visible imprint of culture is Cultural Landscape. Built Environment is the constructed subset. Site is original physical setting. Absolute Location is a coordinate.'),
  q('hei-cl-2', 'hei', 'Cultural Landscape',
    'A war monument, a fence line, and house styles let a visitor read who lived here before. Which concept is this readable cultural mark on the earth’s surface?',
    ['Environmental Determinism', 'Pattern', 'Reference Map'],
    'The humanized surface is Cultural Landscape. Environmental Determinism would say climate wrote the area. Pattern is arrangement without the cultural reading. A reference map might depict it.'),
  q('hei-cl-3', 'hei', 'Cultural Landscape',
    'From an airplane, street grids, barn shapes, and church placement tell you which farming culture shaped each town. Which concept is read from those visible cultural features?',
    ['Vernacular Region', 'Quinary Sector', 'Gross National Income'],
    'Those signatures are Cultural Landscape. The towns may sit in a vernacular region, but the thing being read from the air is the imprint on the land.'),
  q('hei-cl-4', 'hei', 'Cultural Landscape',
    'Crop fields, barns, and a church steeple together mark the land—not just one building alone. Which concept names this visibly fashioned surface shaped by culture?',
    ['Land Use', 'Site', 'Purchasing Power Parity'],
    'That fashioned surface is Cultural Landscape. Land Use is the activity assigned. Site is original physical character. PPP adjusts prices.'),
  q('hei-cl-5', 'hei', 'Cultural Landscape',
    'The visible mark humans leave on the land is more than one building and not just a feeling in someone’s heart. Which concept is this visible cultural imprint on the land?',
    ['Sense of Place', 'Built Environment', 'Formal Sector'],
    'The visible cultural imprint is Cultural Landscape. Sense of Place is the feeling. Built Environment is the constructed subset. Formal Sector is taxed work.'),

  q('hei-ed-1', 'hei', 'Environmental Determinism',
    'An old textbook claimed tropical heat made people lazy and mild climates built great civilizations—nature controls culture. Which rejected belief says the environment controls human development?',
    ['Possibilism', 'Sustainability', 'World Systems Theory'],
    'Climate deciding culture is Environmental Determinism. Possibilism is the opposing view. Sustainability is long-term resource use. World Systems Theory blames a political-economic hierarchy.'),
  q('hei-ed-2', 'hei', 'Environmental Determinism',
    'A TV pundit says mountain people will always be poor and isolated because steep slopes control their fate. Which concept treats the physical environment as human destiny?',
    ['Possibilism', 'Human Development Index', 'Functional Region'],
    'Nature as destiny is Environmental Determinism. Possibilism rejected it. HDI is a development index. A functional region is a nodal area.'),
  q('hei-ed-3', 'hei', 'Environmental Determinism',
    'A writer argues that climate alone made an entire society the way it is—one-way cause from nature to people. Which rejected theory is this?',
    ['Possibilism', 'Time-Space Compression', 'Choropleth Map'],
    'One-way climate cause is Environmental Determinism. Possibilism is the accepted alternative. Time-space compression is shrinking distance. A choropleth is a map type.'),
  q('hei-ed-4', 'hei', 'Environmental Determinism',
    'A commentator says a dry grassland will always stay poor because rain is unreliable—ignoring policies and history. Which concept says nature alone controls outcomes?',
    ['Possibilism', 'Commodity Dependence', 'Dependency Model'],
    'The environment as the controlling cause is Environmental Determinism. Possibilism leaves room for policy. Commodity Dependence and Dependency Model offer economic explanations.'),
  q('hei-ed-5', 'hei', 'Environmental Determinism',
    'An old map linked “warm climates” with “less civilization” as if temperature decided achievement. Which rejected concept treats nature as the controlling force?',
    ['Possibilism', 'Site', 'Literacy Rate'],
    'Climate writing achievement is Environmental Determinism. Possibilism rejected that. Site describes climate as a local trait, not as destiny. Literacy Rate is schooling.'),

  q('hei-pos-1', 'hei', 'Possibilism',
    'Two countries share the same dry climate—one grows irrigated grapes and the other raises sheep. Which view says the environment sets limits but people can choose different responses?',
    ['Environmental Determinism', 'Time-Space Compression', 'Formal Sector'],
    'Limits plus different human choices is Possibilism. Environmental Determinism would predict one “arid personality.” Time-space compression is about distance. Formal Sector is legal work.'),
  q('hei-pos-2', 'hei', 'Possibilism',
    'One flood-prone nation builds dikes and pumps; another uses raised embankments and stilt houses for the same water risk. Which concept explains different human choices within similar environmental limits?',
    ['Environmental Determinism', 'Site', 'Gini Coefficient'],
    'Different answers to similar limits is Possibilism. Determinism would expect the same outcome. Site describes the water risk. Gini measures inequality.'),
  q('hei-pos-3', 'hei', 'Possibilism',
    'People use air conditioning to live in a hot desert, but they still need water and electricity—the environment still limits them. Which concept says nature offers options that people can pick among?',
    ['Environmental Determinism', 'World Systems Theory', 'Dot Distribution Map'],
    'Options widened by technology, with limits still there, is Possibilism. Environmental Determinism is what it replaced. World Systems Theory is about the world-economy. A dot map is a symbol type.'),
  q('hei-pos-4', 'hei', 'Possibilism',
    'Technology opens new choices in a harsh environment, but mountains and deserts still impose some limits. Which theory says the environment allows a range of options for human choice?',
    ['Environmental Determinism', 'Absolute Location', 'Informal Sector'],
    'A range of options is Possibilism, not “anything is possible.” Determinism says climate decides everything. Absolute Location is a coordinate. Informal Sector is unrecorded work.'),
  q('hei-pos-5', 'hei', 'Possibilism',
    'One country meets flood risk with stilt houses; another builds dikes—same hazard, different human answers. Which concept combines environmental limits with human freedom to choose?',
    ['Environmental Determinism', 'Cartographic Scale', 'Quinary Sector'],
    'Limits plus choice is Possibilism. Environmental Determinism is the rejected opposite. Cartographic Scale is a map ratio. Quinary Sector is elite jobs.'),
]
