import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SCALE_QUESTIONS: VocabQuestion[] = [
  q('sca-glo-1', 'scale', 'Global Scale',
    'Scientists report one sea-level number for the whole ocean, not a figure for each country.',
    ['World Scale', 'National Scale', 'Thematic Map'],
    'The entire world as one process is Global Scale. World Scale would be a large world area such as South Asia. National is one country. A thematic map is a map type.'),
  q('sca-glo-2', 'scale', 'Global Scale',
    'The headline is that Earth warmed 1.1°C, not that Japan or Africa did.',
    ['World Scale', 'Regional Scale', 'Local Scale'],
    'One Earth-wide figure is Global Scale. World Scale would be North America or South Asia. Regional would be a belt of states. Local would be a city.'),
  q('sca-glo-3', 'scale', 'Global Scale',
    'Emissions anywhere change the same atmosphere. The unit is Earth as a whole.',
    ['World Scale', 'National Scale', 'Regional Scale'],
    'A planetary process is Global Scale. World Scale would be South Asia. National Scale is one country. Regional Scale is a particular area within or across countries.'),
  q('sca-glo-4', 'scale', 'Global Scale',
    'The virus is treated as one wave in a linked human population, not 200 separate national epidemics.',
    ['World Scale', 'Local Scale', 'Formal Region'],
    'A worldwide process is Global Scale. World Scale would be North America. Local Scale is one city. A Formal Region is a type of area.'),
  q('sca-glo-5', 'scale', 'Global Scale',
    'The question is how one economy has operated across the entire planet, not how South Asia compares with Europe.',
    ['National Scale', 'Local Scale', 'Cartographic Scale'],
    'The entire world as the frame is Global Scale. Comparing two world areas would be World Scale. Local Scale is a city. Cartographic Scale is a map fraction.'),

  q('sca-wor-1', 'scale', 'World Scale',
    'Rainfall and population are compared across South Asia, not for the whole planet and not for one country.',
    ['Global Scale', 'National Scale', 'Local Scale'],
    'South Asia as a large world area is World Scale. Global is the entire planet. National is one country. Local is a city or neighborhood.'),
  q('sca-wor-2', 'scale', 'World Scale',
    'The map looks at economic change across North America, not one city and not the whole Earth.',
    ['Global Scale', 'Local Scale', 'Site'],
    'North America as a large world area is World Scale. Global is the entire planet. Local is a city. Site is physical character.'),
  q('sca-wor-3', 'scale', 'World Scale',
    'The chapter treats Latin America as one frame and compares several countries there.',
    ['Global Scale', 'Regional Scale', 'Vernacular Region'],
    'A large world area made of multiple countries is World Scale. Global is the entire world. Regional Scale is often a smaller belt such as Appalachia. A Vernacular Region is a perceived area.'),
  q('sca-wor-4', 'scale', 'World Scale',
    'Compare monsoon climates across South Asia. Do not give one Earth average, and do not study only India.',
    ['Global Scale', 'National Scale', 'Cartogram'],
    'South Asia as a multi-country world area is World Scale. Global is one planetary figure. National is one country. A cartogram resizes area.'),
  q('sca-wor-5', 'scale', 'World Scale',
    'Shipping is mapped for the countries of Southeast Asia as a group, not totaled into one world figure.',
    ['Global Scale', 'Local Scale', 'Functional Region'],
    'Multiple countries in a large world area are World Scale. A Global figure would be total world shipping. Local would be one port neighborhood. A Functional Region is one hub’s hinterland.'),

  q('sca-nat-1', 'scale', 'National Scale',
    'The table lists one well-being score for Japan and one for Nigeria.',
    ['Local Scale', 'Global Scale', 'Dot Distribution Map'],
    'One score per country is National Scale. Local would be city scores. Global would be one world score. A dot map is a symbol type.'),
  q('sca-nat-2', 'scale', 'National Scale',
    'India gets one female labor-force rate. Bangladesh gets another. District gaps inside India are ignored.',
    ['Regional Scale', 'Local Scale', 'World Scale'],
    'One statistic for a whole country is National Scale. Regional would be an Indian state belt. Local would be a district. World Scale would be South Asia.'),
  q('sca-nat-3', 'scale', 'National Scale',
    'The journalist writes “France is secular” because of a nationwide school law.',
    ['Local Scale', 'Regional Scale', 'Global Scale'],
    'The country and its law are National Scale. Local would be neighborhoods. Regional would be Brittany. Global would be a worldwide process.'),
  q('sca-nat-4', 'scale', 'National Scale',
    'Income per person is one number for Japan or Nigeria so governments can be ranked.',
    ['Local Scale', 'Regional Scale', 'Cartographic Scale'],
    'A country-level figure is National Scale. Local and Regional would split the country. Cartographic Scale is how zoomed-in the map is.'),
  q('sca-nat-5', 'scale', 'National Scale',
    'The law applies to every province in Kenya the same way. Kenya is treated as one unit.',
    ['Regional Scale', 'World Scale', 'Sense of Place'],
    'The country as one unit is National Scale. Regional would be one Kenyan province group. World Scale would be a large world area. Sense of Place is meaning.'),

  q('sca-reg-1', 'scale', 'Regional Scale',
    'Opioid deaths are compared for Appalachia, New England, and the Southwest, not for 3,000 counties and not as one U.S. average.',
    ['National Scale', 'Local Scale', 'Global Scale'],
    'A particular area larger than a city but not the whole country is Regional Scale. National would be one U.S. rate. Local would be a county. Global would be the planet.'),
  q('sca-reg-2', 'scale', 'Regional Scale',
    'Coastal manufacturing China is compared with the western interior, not quoted as one national GDP.',
    ['National Scale', 'World Scale', 'Site'],
    'Large areas inside a country are Regional Scale. National is all of China as one number. World Scale would be East Asia as a whole. Site is one locality’s physical character.'),
  q('sca-reg-3', 'scale', 'Regional Scale',
    'The study looks at southern Italy versus northern Italy, not one number for the whole country and not one village.',
    ['Local Scale', 'National Scale', 'Formal Region'],
    'Those blocks inside the country are Regional Scale. Local would be a village. National would be Italy as a whole. They may also be formal regions, but the question asks for scale.'),
  q('sca-reg-4', 'scale', 'Regional Scale',
    'The U.S. map compares the South with the Midwest. It is not local streets and not the whole country as one color.',
    ['Local Scale', 'National Scale', 'World Scale'],
    'South vs Midwest is Regional Scale. Local is streets. National is one U.S. color. World Scale would be North America as a whole.'),
  q('sca-reg-5', 'scale', 'Regional Scale',
    'The drought paper studies the Sahel as a belt across several countries, not as one village and not as the entire world.',
    ['Local Scale', 'Global Scale', 'Quaternary Sector'],
    'A particular multi-country belt is Regional Scale. Local is a village. Global is the entire world. Quaternary Sector is information work.'),

  q('sca-loc-1', 'scale', 'Local Scale',
    'Grocery stores are mapped by neighborhood, not as one number for the whole country.',
    ['Regional Scale', 'National Scale', 'World Systems Theory'],
    'A neighborhood is Local Scale. Regional would be a multi-state belt. National would be one U.S. rate. World Systems Theory is a development model.'),
  q('sca-loc-2', 'scale', 'Local Scale',
    'The zoning fight is about one neighborhood’s rent and school seats, drawn block by block.',
    ['Regional Scale', 'National Scale', 'World Scale'],
    'Block- and neighborhood-level analysis is Local Scale. Regional would be a multi-borough belt. National would be U.S. housing policy. World Scale would be a large world area.'),
  q('sca-loc-3', 'scale', 'Local Scale',
    'The country ranking makes Lagos look wealthy. One unregistered settlement and one gated estate have opposite water access.',
    ['National Scale', 'Global Scale', 'Vernacular Region'],
    'Comparing neighborhoods inside one city is Local Scale. National Scale hid the contrast. Global would be a worldwide water statistic. A Vernacular Region is a perceived area.'),
  q('sca-loc-4', 'scale', 'Local Scale',
    'After the spill, wells on three streets are tested. A state cancer rate would hide those streets.',
    ['Regional Scale', 'National Scale', 'Small-Scale Maps'],
    'Streets and households are Local Scale. Regional or National rates would average the spill away. Small-scale maps show large areas with less detail.'),
  q('sca-loc-5', 'scale', 'Local Scale',
    'A national average hides a slum next to a wealthy district. The contrast only appears on streets and blocks.',
    ['World Scale', 'Global Scale', 'Cartographic Scale'],
    'The neighborhood zoom is Local Scale. World and Global are much larger frames. Cartographic Scale is the map’s representative fraction.'),
]
