import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_SECTOR_QUESTIONS: VocabQuestion[] = [
  q('sec-pri-1', 'sectors', 'Primary Sector',
    'After a drought, jobs disappear first among people who grow crops and raise livestock, even though nearby mills and shops stay open. Which part of the economy is shrinking?',
    ['Secondary Sector', 'Tertiary Sector', 'Informal Sector'],
    'Taking crops and livestock from the land is the Primary Sector. Mills are Secondary. Shops are Tertiary. Informal Sector is whether work is recorded.'),
  q('sec-pri-2', 'sectors', 'Primary Sector',
    'A nickel mine closes. The hospital and grocery in town remain open, but the displaced workers had been paid to extract ore from the ground. Which sector did those workers belong to?',
    ['Quaternary Sector', 'Quinary Sector', 'Built Environment'],
    'Mining is Primary Sector extraction. Quaternary is information work. Quinary is top decision-making. Built Environment is the physical town.'),
  q('sec-pri-3', 'sectors', 'Primary Sector',
    'A coastal town’s boats return empty after fish stocks collapse. Canneries become idle only after there is nothing left to process. Which sector failed first?',
    ['Secondary Sector', 'Tertiary Sector', 'Commodity Dependence'],
    'Fishing extracts a natural resource, so it is Primary. Canneries are Secondary. Shops and banks are Tertiary. Commodity Dependence would be if fish dominate the whole country’s exports.'),
  q('sec-pri-4', 'sectors', 'Primary Sector',
    'A class is shown a wheat field, a copper mine, a fishing boat, and a logging crew. Which economic sector includes all four of these jobs?',
    ['Secondary Sector', 'Land Use', 'Sustainability'],
    'Farming, mining, fishing, and forestry extract raw materials, which is the Primary Sector. Turning logs into lumber is Secondary. Land Use is how a parcel is allocated. Sustainability is whether the resource can last.'),
  q('sec-pri-5', 'sectors', 'Primary Sector',
    'Most workers in a poorer export country still earn a living by growing crops or digging minerals rather than making products or providing services. Which sector dominates employment?',
    ['Quaternary Sector', 'Quinary Sector', 'Gender Gap'],
    'Crop and mineral extraction is Primary. Quaternary and Quinary are knowledge and leadership jobs. Gender Gap is a male–female difference.'),

  q('sec-sec-1', 'sectors', 'Secondary Sector',
    'Imported aluminum is stamped and painted into phone frames in a factory. Design work stays in another country. Which sector is represented by the factory work?',
    ['Primary Sector', 'Tertiary Sector', 'Quaternary Sector'],
    'Turning raw metal into a product is Secondary manufacturing. Mining the metal would be Primary. Selling phones is Tertiary. Design is Quaternary.'),
  q('sec-sec-2', 'sectors', 'Secondary Sector',
    'A city’s decline is not mainly the end of iron mining or downtown law offices. It is the closure of plants that turned steel and glass into automobiles. Which sector collapsed?',
    ['Primary Sector', 'Quinary Sector', 'Formal Sector'],
    'Auto assembly is Secondary. Iron mining is Primary. Headquarters decisions are Quinary. Formal Sector only means the plants were legal workplaces.'),
  q('sec-sec-3', 'sectors', 'Secondary Sector',
    'Workers sew imported fabric into export clothing. The value added on site is turning cloth into finished garments. Which concept is being demonstrated?',
    ['Tertiary Sector', 'Quaternary Sector', 'Informal Sector'],
    'Garment assembly is Secondary. Retail would be Tertiary. Design would be Quaternary. Informal Sector would be unregistered home sewing, not a factory.'),
  q('sec-sec-4', 'sectors', 'Secondary Sector',
    'A country that once exported only raw cotton now employs thousands in plants that turn cotton into shirts. Which part of the economy has grown?',
    ['Primary Sector', 'Quinary Sector', 'Vernacular Region'],
    'Processing raw cotton into shirts is Secondary. Growing cotton is Primary. Quinary is top leadership. A vernacular region is a perceived area.'),
  q('sec-sec-5', 'sectors', 'Secondary Sector',
    'A sawmill converts logs into boards. Forest crews cut the trees; the mill changes those trees into a usable product. Which sector is the mill?',
    ['Primary Sector', 'Tertiary Sector', 'Cartographic Scale'],
    'The mill manufactures a product, so it is Secondary. The forest work is Primary. Selling the boards is Tertiary. Cartographic Scale is a map-to-Earth ratio.'),

  q('sec-ter-1', 'sectors', 'Tertiary Sector',
    'New jobs appear in hotels, bus driving, restaurants, and shops rather than on farms or factory floors. Which sector is expanding?',
    ['Secondary Sector', 'Quaternary Sector', 'Quinary Sector'],
    'Ordinary services are Tertiary. Factories are Secondary. Specialized research is Quaternary. Top officials are Quinary.'),
  q('sec-ter-2', 'sectors', 'Tertiary Sector',
    'After an airport opens, a town hires hotel staff, taxi drivers, and tour guides. The nearby olive groves stay the same size. Which concept best describes the new jobs?',
    ['Primary Sector', 'Secondary Sector', 'Cultural Landscape'],
    'Hotels, taxis, and guides provide services, so they are Tertiary. Groves are Primary. A workshop would be Secondary. Cultural Landscape is the visible human imprint.'),
  q('sec-ter-3', 'sectors', 'Tertiary Sector',
    'A teacher, a nurse, and a truck driver all serve people or businesses instead of extracting resources or making a product. Which sector includes these jobs?',
    ['Quaternary Sector', 'Primary Sector', 'Pattern'],
    'Education, health care, and transportation are Tertiary services. Quaternary is specialized information work. Primary is extraction. Pattern is a spatial arrangement.'),
  q('sec-ter-4', 'sectors', 'Tertiary Sector',
    'After a port expands, hiring rises in trucking, warehouses, and import shops. Workers move and sell goods rather than build ships. Which term is represented by this example?',
    ['Primary Sector', 'Quaternary Sector', 'Formal Sector'],
    'Freight and retail are Tertiary. Digging ore is Primary. Writing logistics software is closer to Quaternary. Formal Sector only means the firms are registered.'),
  q('sec-ter-5', 'sectors', 'Tertiary Sector',
    'A municipal bus system, a grocery checkout, and a hair salon all provide a service rather than a manufactured good. Which AP Human Geography term best applies?',
    ['Quaternary Sector', 'Primary Sector', 'Commodity Dependence'],
    'Everyday services are Tertiary. Quaternary is research and information. Primary is extraction. Commodity Dependence is export mix.'),

  q('sec-qua-1', 'sectors', 'Quaternary Sector',
    'Office towers fill with software engineers and financial analysts who produce information rather than hotel stays or hardware. Which sector is this?',
    ['Tertiary Sector', 'Quinary Sector', 'Secondary Sector'],
    'Research, software, and analysis are Quaternary. Hotels and shops are Tertiary. A handful of CEOs would be Quinary. Factories are Secondary.'),
  q('sec-qua-2', 'sectors', 'Quaternary Sector',
    'Chemists run trials and file patents on a campus. Nearby, a plant bottles medicine and a clinic dispenses it. Which sector is the research work?',
    ['Secondary Sector', 'Tertiary Sector', 'Quinary Sector'],
    'Research and patents are Quaternary. Bottling is Secondary. The clinic is Tertiary. The board that funds the campus is Quinary.'),
  q('sec-qua-3', 'sectors', 'Quaternary Sector',
    'A data-science team can work from almost any city because its product is knowledge rather than a mine or a storefront. Which concept is being demonstrated?',
    ['Primary Sector', 'Informal Sector', 'Site'],
    'Information and knowledge work is Quaternary. Primary needs a resource. Informal Sector is unrecorded work. Site is the physical character of a parcel.'),
  q('sec-qua-4', 'sectors', 'Quaternary Sector',
    'An insurance firm replaces routine clerks with a smaller staff of actuaries who model risk for clients worldwide. Which sector are the remaining jobs?',
    ['Tertiary Sector', 'Primary Sector', 'Human Development Index'],
    'Specialized intellectual modeling is Quaternary. Old clerks were routine Tertiary service. Primary is extraction. HDI is a development index.'),
  q('sec-qua-5', 'sectors', 'Quaternary Sector',
    'A restaurant serves meals, while a nearby lab writes research software. Only one of these jobs is based on specialized knowledge. Which sector is the lab?',
    ['Tertiary Sector', 'Quinary Sector', 'Literacy Rate'],
    'Knowledge and research work is Quaternary. A restaurant is Tertiary. A cabinet secretary is Quinary. Literacy Rate is a social indicator.'),

  q('sec-qui-1', 'sectors', 'Quinary Sector',
    'A small group of executives and government officials decides to close a steel mill, and thousands of factory jobs then disappear. Which sector includes the people who made that decision?',
    ['Quaternary Sector', 'Tertiary Sector', 'Formal Sector'],
    'Highest-level leadership is Quinary. The analysts who briefed them are Quaternary. Routine services are Tertiary. Formal Sector only means the work is legal.'),
  q('sec-qui-2', 'sectors', 'Quinary Sector',
    'After a hurricane, a president, a central-bank chair, and a grocery-chain chief executive decide relief funds, interest rates, and food shipments. Warehouse staff carry out the plan. Which sector are the decision-makers?',
    ['Quaternary Sector', 'Tertiary Sector', 'Human Environment Interaction'],
    'Heads of government, banks, and major firms are Quinary. Analysts are Quaternary. Warehouse staff are Tertiary. Human-environment interaction is the disaster theme, not the job sector.'),
  q('sec-qui-3', 'sectors', 'Quinary Sector',
    'A university president and a foundation director choose which city receives a new hospital campus. Architects will design it later. Which term best describes these leadership roles?',
    ['Quaternary Sector', 'Secondary Sector', 'Functional Region'],
    'Institutional leaders making the call are Quinary. Architects are closer to Quaternary. Construction is Secondary. A hospital service area would later be a Functional Region.'),
  q('sec-qui-4', 'sectors', 'Quinary Sector',
    'A cabinet and a corporate board choose to move headquarters to another country. The staff who prepared the reports did not make that call. Which concept is being demonstrated?',
    ['Quaternary Sector', 'Tertiary Sector', 'World Systems Theory'],
    'Highest-level strategy is Quinary. The briefing writers are Quaternary. Everyday services are Tertiary. World Systems Theory is a development model.'),
  q('sec-qui-5', 'sectors', 'Quinary Sector',
    'Heads of state sign a climate agreement. Scientists supplied the reports, but the signatures changed policy. Which sector includes the signers?',
    ['Quaternary Sector', 'Primary Sector', 'Isoline Map'],
    'Top political leadership is Quinary. Scientists are Quaternary. Primary is extraction. An isoline map could show temperature, not the decision sector.'),
]
