import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_DATA_QUESTIONS: VocabQuestion[] = [
  q('dat-fld-1', 'data', 'Field Observations',
    'A student walks to a bus stop, counts riders, and asks passengers why they changed routes—all while standing on the ground in person. Which method means collecting data by being there and observing directly?',
    ['Remote Sensing', 'Geographic Information Systems', 'Global Positioning System'],
    'Walking, counting, and interviewing on the ground is Field Observations. Remote Sensing uses images from above. GIS stacks layers on a computer. GPS gets coordinates from satellites.'),
  q('dat-fld-2', 'data', 'Field Observations',
    'A geographer visits a market, talks to shop owners face to face, and writes down what she sees with her own eyes. Which method is this hands-on, on-the-ground data collection?',
    ['Remote Sensing', 'Choropleth Map', 'Cartographic Scale'],
    'Being there to walk, see, and interview is Field Observations. Remote Sensing uses distant imagery. A choropleth is a shaded map. Cartographic Scale is the map-to-Earth ratio.'),
  q('dat-fld-3', 'data', 'Field Observations',
    'After a flood, workers walk house to house marking water lines and taking photos that no satellite ever captured. Which method requires people physically present on the ground?',
    ['Remote Sensing', 'Isoline Map', 'World Systems Theory'],
    'On-the-ground marks and photos are Field Observations. Remote Sensing is imagery from far away. Isolines might later show depth. World Systems Theory is a development model.'),
  q('dat-fld-4', 'data', 'Field Observations',
    'A planner stands at an intersection counting cars and interviewing shop owners about parking—work no camera in space can do. Which on-the-ground method is this?',
    ['Remote Sensing', 'Thematic Map', 'Quaternary Sector'],
    'Going there to count and interview is Field Observations. Remote Sensing does not require standing at the site. A thematic map displays one variable. Quaternary Sector is information work.'),
  q('dat-fld-5', 'data', 'Field Observations',
    'A researcher says you cannot learn why riders switched buses from a picture taken from above—you need to walk, count, and talk to people on the ground. Which method is that?',
    ['Global Positioning System', 'Reference Map', 'Formal Sector'],
    'Walking, counting, and interviewing on the ground is Field Observations. GPS records coordinates from satellites. A reference map shows location. Formal Sector is taxed work.'),

  q('dat-rs-1', 'data', 'Remote Sensing',
    'Scientists compare satellite pictures from 1985 and 2020 to measure forest loss without sending anyone into the woods. Which method collects data from far away using images from above?',
    ['Field Observations', 'Global Positioning System', 'Geographic Information Systems'],
    'Images from satellites far above Earth are Remote Sensing. Field Observations require being on the ground. GPS gives coordinates. GIS may display the images later.'),
  q('dat-rs-2', 'data', 'Remote Sensing',
    'An airplane with special cameras photographs dying grass across a huge area in one day—no teams walking the ground. Which method uses aircraft or satellite imagery from a distance?',
    ['Field Observations', 'Reference Map', 'Quaternary Sector'],
    'Aircraft and satellite sensors from above are Remote Sensing. Walking the belt would be Field Observations. A reference map shows names. Quaternary Sector is knowledge work.'),
  q('dat-rs-3', 'data', 'Remote Sensing',
    'A city uses a plane flying overhead to measure every rooftop for solar panels instead of climbing each building. Which method gets data from above using sensors on aircraft?',
    ['Geographic Information Systems', 'Field Observations', 'Topographic Map'],
    'Sensors on a plane taking images from above are Remote Sensing. GIS is how the city analyzes the data. Climbing roofs is Field Observations. A topographic map shows contours.'),
  q('dat-rs-4', 'data', 'Remote Sensing',
    'Weather trackers watch a hurricane using pictures beamed down from orbit, not by standing in the storm. Which method uses images taken from satellites far above Earth?',
    ['Global Positioning System', 'Field Observations', 'Dot Distribution Map'],
    'Long-distance images from satellites are Remote Sensing. GPS reports a receiver’s coordinates. Field Observations are on the ground. A dot map is a symbol type.'),
  q('dat-rs-5', 'data', 'Remote Sensing',
    'Researchers study twenty years of Arctic ice by comparing photos shot from high above the pole. Which method collects geographic data from a distance using imagery?',
    ['Global Positioning System', 'Literacy Rate', 'Vernacular Region'],
    'Repeat images from above are Remote Sensing. GPS is one coordinate fix. Literacy Rate is schooling. A vernacular region is a perceived area.'),

  q('dat-gps-1', 'data', 'Global Positioning System',
    'A hiker’s phone talks to satellites and shows exact latitude and longitude coordinates on a map. Which technology uses satellite signals to find your precise position?',
    ['Geographic Information Systems', 'Remote Sensing', 'Relative Location'],
    'A receiver calculating latitude and longitude from satellites is GPS. GIS later plots the path. Remote Sensing is imagery from above. Relative Location is “west of the village.”'),
  q('dat-gps-2', 'data', 'Global Positioning System',
    'Surveyors mark a border using satellite-fed coordinate numbers instead of measuring from a nearby tree. Which system gives latitude and longitude by locking onto satellites?',
    ['Isoline Map', 'Geographic Information Systems', 'Situation'],
    'Live satellite positioning that reports coordinates is GPS. Isolines might later show depth. GIS could store the line. Situation is location relative to other places.'),
  q('dat-gps-3', 'data', 'Global Positioning System',
    'A navigation app says “turn left in 40 meters” because the phone keeps getting fresh coordinates from satellites overhead. Which satellite-based system tracks your exact location?',
    ['Geographic Information Systems', 'Cartogram', 'Time-Space Compression'],
    'The live coordinate fix from satellites is GPS. GIS stacks map layers. A cartogram resizes areas. Time-space compression is faster connection.'),
  q('dat-gps-4', 'data', 'Global Positioning System',
    'Air traffic control needs exact latitude and longitude from each plane’s transponder linked to satellites—not just “near Chicago.” Which system supplies those coordinate fixes?',
    ['Relative Location', 'Pattern', 'Cultural Landscape'],
    'Latitude and longitude from satellites is GPS. “Near Chicago” is Relative Location. Pattern is arrangement. Cultural Landscape is the visible human imprint.'),
  q('dat-gps-5', 'data', 'Global Positioning System',
    'A wildlife collar stores a trail of latitude–longitude points by talking to satellites in the sky. Which technology records position using satellite signals?',
    ['Geographic Information Systems', 'Remote Sensing', 'Absolute Location'],
    'A receiver getting coordinates from satellites is GPS. GIS later plots the path. Remote Sensing is imagery from above. Absolute Location is the kind of location reported, not the technology.'),

  q('dat-gis-1', 'data', 'Geographic Information Systems',
    'On a computer, flood zones, roads, and population layers are stacked on top of each other to find risky neighborhoods. Which system is map software that combines many geographic layers?',
    ['Remote Sensing', 'Global Positioning System', 'Dot Distribution Map'],
    'Stacked geographic layers on a computer are GIS. Remote Sensing may have made the flood image. GPS may have collected hospital points. A dot map could display the result.'),
  q('dat-gis-2', 'data', 'Geographic Information Systems',
    'A planner clicks one layer off and the list of good high-school sites changes instantly on the computer map. Which system lets you overlay and analyze stacked map layers?',
    ['Field Observations', 'Reference Map', 'Formal Region'],
    'Interactive overlay of map layers is GIS. Field Observations might gather inputs. A reference map could show one finished site. A formal region might be an attendance zone.'),
  q('dat-gis-3', 'data', 'Geographic Information Systems',
    'Cholera cases are plotted on a map next to well locations and piped-water pipes—and sick people cluster near wells. Which computer system links and stacks those map layers?',
    ['Remote Sensing', 'Choropleth Map', 'Dependency Model'],
    'Relating and stacking spatial layers on a computer is GIS. Remote Sensing did not create the case file. A choropleth might show rates later. Dependency Model is a development theory.'),
  q('dat-gis-4', 'data', 'Geographic Information Systems',
    'A teacher needs software—not just a pin drop—that can pile flood, road, and census layers together for analysis. Which system stacks geographic data layers on a computer?',
    ['Global Positioning System', 'Field Observations', 'Small-Scale Maps'],
    'Stacked-layer map analysis on a computer is GIS. GPS is the pin. Field Observations are on-site notes. Small-scale maps show large areas with little detail.'),
  q('dat-gis-5', 'data', 'Geographic Information Systems',
    'Police stack crime, income, and streetlight maps on a computer to see dark, poor blocks at once. Which system is computer software for layering and analyzing maps?',
    ['Global Positioning System', 'Thematic Map', 'Quinary Sector'],
    'Layered map analysis software is GIS. GPS only locates a point. A thematic map is one possible output. Quinary Sector is elite jobs.'),
]
