import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_HEI_QUESTIONS: VocabQuestion[] = [
  q(
    'hei-hei-1',
    'hei',
    'Human Environment Interaction',
    'Dutch polders, Sahel fuelwood cutting, and Phoenix air-conditioning are all examples of people changing Earth and Earth shaping what people can do. The topic is the two-way relationship, not a single building or a single theory. Which concept names that relationship?',
    ['Built Environment', 'Environmental Determinism', 'Cultural Landscape'],
    'The two-way relationship between societies and Earth systems is Human Environment Interaction. Built Environment is the human-made physical result. Environmental Determinism is one (outdated) theory about that relationship. Cultural Landscape is the visible cultural imprint.',
  ),
  q(
    'hei-hei-2',
    'hei',
    'Human Environment Interaction',
    'A unit on irrigation, air pollution, and earthquake-proof housing is not “physical geography only” and not “culture only”; it is about how societies use, modify, and adapt to Earth. Which heading covers that set?',
    ['Possibilism', 'Land Use', 'Physical Geography'],
    'Use, modify, and adapt is the definition of Human Environment Interaction. Possibilism is one interpretation. Land Use is one piece (how the surface is allocated). Physical Geography would stop at the Earth systems.',
  ),
  q(
    'hei-hei-3',
    'hei',
    'Human Environment Interaction',
    'After a flood, a city both rebuilds levees (changing the river) and raises insurance rates (changing behavior because of the river). Neither action alone is the whole story. Which concept includes both directions?',
    ['Sustainability', 'Site', 'Formal Region'],
    'People changing the river and the river changing people is Human Environment Interaction. Sustainability is a judgment about whether the rebuild can last. Site is the floodplain’s physical character. A formal region is a uniform area.',
  ),
  q(
    'hei-sus-1',
    'hei',
    'Sustainability',
    'A fishery is managed so this year’s catch does not destroy next year’s breeding stock, even though a bigger catch would raise today’s GDP. The policy is judging present use against future capacity. Which concept is that judgment?',
    ['Possibilism', 'Primary Sector', 'Gini Coefficient'],
    'Meeting present needs without wrecking future capacity is Sustainability. Possibilism says humans can choose among environmental options; it does not require a long-term constraint. Primary Sector is fishing as employment. Gini is inequality.',
  ),
  q(
    'hei-sus-2',
    'hei',
    'Sustainability',
    'A city can pump an aquifer cheaply for twenty years and then watch the wells fail, or it can meter water now so the aquifer lasts. Both are technically possible. The second choice is trying to keep the resource available across generations. Which concept names that goal?',
    ['Environmental Determinism', 'Time-Space Compression', 'Quaternary Sector'],
    'Cross-generational resource availability is Sustainability. Environmental Determinism would say the aquifer decides the city’s fate no matter the policy. Time-space compression is shrinking distance. Quaternary Sector is knowledge work.',
  ),
  q(
    'hei-sus-3',
    'hei',
    'Sustainability',
    'Palm-oil firms advertise “no net deforestation” because buyers want production that does not permanently erase the forest’s ability to provide habitat and carbon storage. Which concept is the advertising trying to claim?',
    ['Commodity Dependence', 'Cultural Landscape', 'Absolute Location'],
    'Not permanently erasing future environmental function is a Sustainability claim. Commodity Dependence would be if the country lived on palm-oil exports. Cultural Landscape is the visible plantation pattern. Absolute Location is a coordinate.',
  ),
  q(
    'hei-lu-1',
    'hei',
    'Land Use',
    'A single hectare can be a rice paddy, a parking garage, a temple garden, or a conservation reserve. The legal and economic decision about what that hectare is for — not the soil chemistry alone — is which concept?',
    ['Site', 'Built Environment', 'Formal Region'],
    'Allocation of the Earth’s surface to farming, housing, sacred space, or conservation is Land Use. Site is the hectare’s physical traits. Built Environment is the structures if it is developed. A formal region might later group similar hectares.',
  ),
  q(
    'hei-lu-2',
    'hei',
    'Land Use',
    'Zoning that converts an industrial waterfront into condos and a park does not move the parcel and may not change the bedrock. It changes the permitted activity on that parcel. Which concept changed?',
    ['Situation', 'Remote Sensing', 'Literacy Rate'],
    'Permitted activity on a parcel is Land Use. Situation is the waterfront’s connections. Remote Sensing might detect the change. Literacy Rate is schooling.',
  ),
  q(
    'hei-lu-3',
    'hei',
    'Land Use',
    'The von Thünen model is a theory of why dairy, forest, grain, and ranching occupy successive rings around a market. The thing being arranged in rings is not “culture” or “feelings”; it is how the surface is put to work. Which concept is being arranged?',
    ['Sense of Place', 'Toponyms', 'Gender Gap'],
    'How the surface is put to work is Land Use — von Thünen’s subject. Sense of Place is attachment. Toponyms are names. Gender Gap is a social difference.',
  ),
  q(
    'hei-blt-1',
    'hei',
    'Built Environment',
    'Highways, levees, skyscrapers, and irrigation canals are the human-made physical world that later generations inherit, as opposed to the forest or the river channel they replaced. Which concept names that human-made physical world?',
    ['Cultural Landscape', 'Land Use', 'Site'],
    'The human-constructed physical surroundings are the Built Environment. Cultural Landscape is broader: buildings plus the cultural meanings, fields, and sacred sites. Land Use is the activity assigned to the land. Site is original physical character.',
  ),
  q(
    'hei-blt-2',
    'hei',
    'Built Environment',
    'A heat-island study compares downtown concrete and asphalt with a nearby woodland. The temperature gap is produced by materials people poured, not by a change in latitude. Which concept is the concrete-and-asphalt side?',
    ['Physical Geography', 'Possibilism', 'Vernacular Region'],
    'Poured materials that now make up the city are Built Environment. Physical Geography would be the woodland’s climate without the city. Possibilism is a theory of choice. A vernacular region is a mental area.',
  ),
  q(
    'hei-blt-3',
    'hei',
    'Built Environment',
    'After an earthquake, inspectors walk “the buildings and bridges,” not “the religion or the toponyms.” They are inventorying constructed fabric. Which concept is that fabric?',
    ['Sense of Place', 'Formal Sector', 'World Scale'],
    'Buildings and bridges are the Built Environment. Sense of Place is meaning. Formal Sector is legal work. World Scale is a level of analysis.',
  ),
  q(
    'hei-cl-1',
    'hei',
    'Cultural Landscape',
    'Rice terraces, a mosque’s skyline, suburban cul-de-sacs, and a battlefield monument are all Earth’s surface as people have marked it with work, belief, and memory — more than just “the buildings.” Which concept is that marked surface?',
    ['Built Environment', 'Site', 'Absolute Location'],
    'The visible imprint of a culture on Earth — fields, sacred architecture, monuments, street patterns — is the Cultural Landscape. Built Environment is the constructed subset. Site is original physical setting. Absolute Location is a coordinate.',
  ),
  q(
    'hei-cl-2',
    'hei',
    'Cultural Landscape',
    'Carl Sauer argued that you can read a region’s history in its fences, field shapes, and house types, the way you read a text. Which concept is that readable imprint?',
    ['Environmental Determinism', 'Pattern', 'Reference Map'],
    'The humanized, historically layered surface is Cultural Landscape. Environmental Determinism would say climate wrote the region. Pattern is arrangement without the cultural-reading idea. A reference map might depict it.',
  ),
  q(
    'hei-cl-3',
    'hei',
    'Cultural Landscape',
    'A geographer can tell a Mormon village from a New England common-and-green town from the air by street plan, barn type, and church placement, even before hearing anyone speak. Which concept is the geographer reading?',
    ['Vernacular Region', 'Quinary Sector', 'Purchasing Power Parity (PPP)'],
    'Street plan, barns, and churches as a cultural signature are Cultural Landscape. Those villages may sit in a vernacular region, but the thing being read from the air is the landscape. Quinary Sector and PPP are economic ideas.',
  ),
  q(
    'hei-ed-1',
    'hei',
    'Environmental Determinism',
    'A 19th-century textbook claimed that tropical heat made societies “lazy” and that temperate climates produced “civilization,” treating climate as the cause of culture and development. Which theory is that?',
    ['Possibilism', 'Sustainability', 'World Systems Theory'],
    'Climate (or nature) as the cause of culture and development is Environmental Determinism. Possibilism is the opposing view that people choose among options. Sustainability is about long-term resource use. World Systems Theory blames a political-economic hierarchy, not climate.',
  ),
  q(
    'hei-ed-2',
    'hei',
    'Environmental Determinism',
    'A commentator says “the Sahel will always be poor because the rainfall is unreliable,” as if policy, trade, and colonial history cannot matter. Which outdated geographic idea is the commentator repeating?',
    ['Possibilism', 'Commodity Dependence', 'Dependency Model'],
    'Nature as destiny is Environmental Determinism. Possibilism would leave room for irrigation, migration, or trade policy. Commodity Dependence and Dependency Model offer economic explanations, not a climate-is-fate claim.',
  ),
  q(
    'hei-ed-3',
    'hei',
    'Environmental Determinism',
    'Ellsworth Huntington’s maps tried to match “climatic energy” with “civilization,” implying that latitude wrote human achievement. Modern AP Human Geography treats that as a rejected theory. Which theory was it?',
    ['Possibilism', 'Human Development Index (HDI)', 'Functional Region'],
    'Latitude writing achievement is Environmental Determinism. Possibilism rejected that one-way cause. HDI is a development index. A functional region is a nodal area.',
  ),
  q(
    'hei-pos-1',
    'hei',
    'Possibilism',
    'The same arid climate produced a drip-irrigated export vineyard in Israel, a pastoral economy in parts of Kenya, and a solar-desalination experiment in Australia. Nature set limits; technology and culture chose different responses. Which theory is that?',
    ['Environmental Determinism', 'Time-Space Compression', 'Formal Sector'],
    'Limits plus human choice among options is Possibilism. Environmental Determinism would have predicted one “arid personality.” Time-space compression is about distance. Formal Sector is legal work.',
  ),
  q(
    'hei-pos-2',
    'hei',
    'Possibilism',
    'The Netherlands did not “become a swamp culture”; it built dikes and pumps. Bangladesh, with a similar flood risk, uses a different mix of embankments, stilt housing, and migration. Which theory explains those different answers to similar water?',
    ['Environmental Determinism', 'Site', 'Gini Coefficient'],
    'Different cultural-technical answers to similar physical limits is Possibilism. Determinism would expect the same outcome. Site describes the water risk. Gini measures inequality.',
  ),
  q(
    'hei-pos-3',
    'hei',
    'Possibilism',
    'A student says geography is useless because “people can just invent air conditioning and live anywhere.” A more precise AP statement is that environments offer a range of options, and technology widens that range without erasing every constraint. Which theory is the precise statement?',
    ['Environmental Determinism', 'Cartographic Scale', 'Quinary Sector'],
    'A range of options widened by technology is Possibilism — not “anything is possible,” and not “climate decides everything.” Cartographic Scale is a map ratio. Quinary Sector is elite decision jobs.',
  ),
]
