import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_MEASURE_QUESTIONS: VocabQuestion[] = [
  q('mea-gnp-1', 'measures', 'Gross National Product',
    'A Japanese automaker’s factory in Tennessee builds cars on U.S. soil. A researcher wants a total that follows Japan’s own companies, not the factory’s street address. Which measure is that?',
    ['Gross National Income', 'Purchasing Power Parity', 'Formal Sector'],
    'Gross National Product totals output belonging to a nation’s people and firms, even abroad. Gross National Income tracks income received. Purchasing Power Parity only adjusts prices. Formal Sector is regulated work.'),
  q('mea-gnp-2', 'measures', 'Gross National Product',
    'Ireland’s factory output looks huge because foreign tech firms book sales there. A researcher who wants “what Irish nationals produce,” not “what happens inside the border,” needs which older national-product measure?',
    ['Human Development Index', 'Gini Coefficient', 'Remittances'],
    '“Nationals’ production” is Gross National Product. Human Development Index adds health and school. Gini is inequality. Remittances are household transfers.'),
  q('mea-gnp-3', 'measures', 'Gross National Product',
    'The vocab list defines this as the total market value of goods and services produced by a nation in a period. It follows the nation, not just the border. Which measure is that?',
    ['Life Expectancy', 'Secondary Sector', 'Cartogram'],
    'That definition is Gross National Product. Life Expectancy is years lived. Secondary Sector is manufacturing. A cartogram resizes map area.'),
  q('mea-gnp-4', 'measures', 'Gross National Product',
    'A U.S. consulting firm bills clients from a London office. That work still counts toward the U.S. “national” product total. Which measure includes it?',
    ['Literacy Rate', 'Relative Location', 'Built Environment'],
    'Output by a nation’s firms abroad is Gross National Product. Literacy Rate is schooling. Relative Location is position compared with other places. Built Environment is buildings and roads.'),
  q('mea-gnp-5', 'measures', 'Gross National Product',
    'Students mix this up with income received and with a price adjustment. This one is about production by a nation’s people and companies. Which measure is that?',
    ['Gross National Income', 'Purchasing Power Parity', 'Gender Inequality Index'],
    'Production by a nation’s people and companies is Gross National Product. Gross National Income is income received. Purchasing Power Parity equalizes prices. Gender Inequality Index is a gender composite.'),

  q('mea-gni-1', 'measures', 'Gross National Income',
    'The UN development index uses a wealth piece that includes wages and profits residents receive, even from foreign investments. It is not just factory output inside the border. Which measure is that wealth piece?',
    ['Gross National Product', 'Purchasing Power Parity', 'Formal Sector'],
    'The UN income series is Gross National Income. Gross National Product is a related production idea. Purchasing Power Parity is the price adjustment often applied to it. Formal Sector is legal work.'),
  q('mea-gni-2', 'measures', 'Gross National Income',
    'The Philippines receives large overseas-worker transfers and some shipping profits from abroad. Which national total is built to capture money residents receive from the rest of the world?',
    ['Literacy Rate', 'Commodity Dependence', 'Cartogram'],
    'Income received, including from abroad, is Gross National Income. Literacy Rate is schooling. Commodity Dependence is export concentration. A cartogram is a map type.'),
  q('mea-gni-3', 'measures', 'Gross National Income',
    'Luxembourg’s per-person income looks far above what is physically made inside the duchy because residents own capital that pays them from other countries. Which total is inflated by that incoming income?',
    ['Gini Coefficient', 'Gender Gap', 'Primary Sector'],
    'Incoming property and labor income is Gross National Income. Gini describes how income is shared. Gender Gap is a male–female difference. Primary Sector is farming or mining.'),
  q('mea-gni-4', 'measures', 'Gross National Income',
    'AP tables of development almost always show this “per capita,” not a factory-output total. Which income measure is that?',
    ['Remittances', 'Isoline Map', 'Quinary Sector'],
    'The standard per-person income in AP is Gross National Income. Remittances are one kind of transfer that can enter it. An isoline map is weather-style lines. Quinary Sector is top leadership.'),
  q('mea-gni-5', 'measures', 'Gross National Income',
    'A student says “money produced inside the country.” The teacher says AP wants income residents actually receive. Which measure is the teacher naming?',
    ['Gross National Product', 'Formal Sector', 'Site'],
    'Income residents receive is Gross National Income. Gross National Product is production by nationals. Formal Sector is taxed work. Site is physical character.'),

  q('mea-rem-1', 'measures', 'Remittances',
    'In a Salvadoran town, new concrete houses appear after harvest season in California, though no factory opened locally. Families spend money a member earned abroad and wired home. Which flow is that?',
    ['Gross National Income', 'Formal Sector', 'Quaternary Sector'],
    'Household transfers from migrants are Remittances. Those transfers later enter Gross National Income, but the flow itself is remittances. Formal Sector is taxed work. Quaternary Sector is knowledge work.'),
  q('mea-rem-2', 'measures', 'Remittances',
    'Nepal’s central bank watches October inflows from Malaysia and the Gulf because school fees are paid with money migrants send, not with a matching rise in Himalayan factory output. Which income stream is that?',
    ['Purchasing Power Parity', 'Commodity Dependence', 'Time-Space Compression'],
    'Migrant-to-household transfers are Remittances. Purchasing Power Parity compares prices. Commodity Dependence is one-export reliance. Time-space compression is faster connection, not the money itself.'),
  q('mea-rem-3', 'measures', 'Remittances',
    'A Mexican village chapel is financed by a U.S. hometown association. Nearby factory profits go to a Delaware corporate account. Only the first is a migrant-to-home transfer. Which term names that first flow?',
    ['Gross National Product', 'Informal Sector', 'Functional Region'],
    'Hometown and family wires are Remittances. Corporate profit sent abroad is not. Gross National Product is a national total. Informal Sector is unrecorded work. A Functional Region is nodal.'),
  q('mea-rem-4', 'measures', 'Remittances',
    'AP migration items often ask how families in Kerala or Oaxaca raise living standards without a new local mill. The answer is money sent home. Which term is that?',
    ['Secondary Sector', 'Absolute Location', 'Possibilism'],
    'Money sent home is Remittances. Secondary Sector is manufacturing. Absolute Location is a coordinate. Possibilism is environmental choice.'),
  q('mea-rem-5', 'measures', 'Remittances',
    'A country can have a modest factory sector and still see villages improve because of this migrant money. Which term is that money?',
    ['Life Expectancy', 'Choropleth Map', 'World Scale'],
    'Migrant money is Remittances. Life Expectancy is years lived. A choropleth shades areas by a rate. World Scale compares countries.'),

  q('mea-ppp-1', 'measures', 'Purchasing Power Parity',
    'A nurse in Mumbai earns far fewer dollars than a nurse in Boston, but food and rent also cost much less. Converting at the market exchange rate makes India look poorer than daily life. Which adjustment compares what salaries can actually buy?',
    ['Gini Coefficient', 'Gross National Income', 'Literacy Rate'],
    'Equalizing what money buys is Purchasing Power Parity. Gini is inequality. Gross National Income is the income being adjusted. Literacy Rate is schooling.'),
  q('mea-ppp-2', 'measures', 'Purchasing Power Parity',
    'Two countries report the same income per person in U.S. dollars. In one, a grocery basket costs three times as much. Researchers refuse to call them equally rich until they apply which conversion?',
    ['Human Development Index', 'Remittances', 'Absolute Location'],
    'Equalizing a basket of goods is Purchasing Power Parity. Human Development Index also mixes health and school. Remittances are migrant transfers. Absolute Location is a coordinate.'),
  q('mea-ppp-3', 'measures', 'Purchasing Power Parity',
    'The “Big Mac Index” jokes about this official idea: market exchange rates swing, but a haircut cannot be traded across borders. Which statistical idea is that?',
    ['Formal Sector', 'Gender Inequality Index', 'World Systems Theory'],
    'Comparing a standard good to reveal price-level differences is Purchasing Power Parity. Formal Sector is legal work. Gender Inequality Index is gender. World Systems Theory is core and periphery.'),
  q('mea-ppp-4', 'measures', 'Purchasing Power Parity',
    'The vocab list defines this as an estimate of the exchange rate that would equalize purchasing power given local prices. Which measure is that?',
    ['Gross National Product', 'Gini Coefficient', 'Reference Map'],
    'That definition is Purchasing Power Parity. Gross National Product is a production total. Gini is inequality. A reference map shows location.'),
  q('mea-ppp-5', 'measures', 'Purchasing Power Parity',
    'AP development charts often label income “per capita, this adjustment.” Without it, poor countries look even poorer because services are cheap there. Which adjustment is that?',
    ['Literacy Rate', 'Distance Decay', 'Quinary Sector'],
    'The price-level adjustment is Purchasing Power Parity. Literacy Rate is schooling. Distance Decay is fading interaction. Quinary Sector is top leadership.'),

  q('mea-for-1', 'measures', 'Formal Sector',
    'A Nairobi accountant pays income tax, contributes to a hospital fund, and can sue on a written contract. A street vendor two blocks away sells the same snacks with none of that. Which sector is the accountant in?',
    ['Informal Sector', 'Quinary Sector', 'Tertiary Sector'],
    'Regulated, taxed work is the Formal Sector. The vendor is Informal. Both can be Tertiary services. Quinary is top decision-making.'),
  q('mea-for-2', 'measures', 'Formal Sector',
    'Official manufacturing output counts plants in tax files. Unregistered backyard workshops are missing. Which part of the economy is the official series built to see?',
    ['Informal Sector', 'Primary Sector', 'Vernacular Region'],
    'What tax files see is the Formal Sector. Informal work is what they miss. Primary Sector is extraction. A vernacular region is a perceived area.'),
  q('mea-for-3', 'measures', 'Formal Sector',
    'A hospital nurse is in labor statistics and a collective agreement. A cousin paid cash to care for a neighbor is not. Which sector is the hospital job?',
    ['Informal Sector', 'Quaternary Sector', 'Functional Region'],
    'The hospital job is Formal. Cash care is Informal. Nursing is not Quaternary research. A Functional Region is a nodal area.'),
  q('mea-for-4', 'measures', 'Formal Sector',
    'AP contrasts this with street vending: this work is legal, taxed, and on the books. A factory with payroll taxes is the example. Which sector is that factory?',
    ['Informal Sector', 'Secondary Sector', 'Site'],
    'On-the-books work is Formal Sector. The factory is also Secondary manufacturing, but the question is about being taxed and recorded. Informal is the opposite. Site is physical character.'),
  q('mea-for-5', 'measures', 'Formal Sector',
    'When GDP looks “too small” in a city full of shops, the missing piece is usually not this sector. This sector is already in the books. Which sector is already counted?',
    ['Informal Sector', 'Life Expectancy', 'Pattern'],
    'Already-counted legal work is the Formal Sector. The missing shops are Informal. Life Expectancy is health. Pattern is arrangement.'),

  q('mea-inf-1', 'measures', 'Informal Sector',
    'In Lima, much clothing is sewn in unregistered homes and sold in street markets that do not appear on tax rolls. GDP understates how many people are working. Which sector is that unrecorded production?',
    ['Formal Sector', 'Quaternary Sector', 'Secondary Sector'],
    'Unregistered production is the Informal Sector. It can still be manufacturing. Formal Sector is the opposite. Quaternary is specialized information work.'),
  q('mea-inf-2', 'measures', 'Informal Sector',
    'After a currency crash, more Cairo residents drive unlicensed taxis. Official unemployment barely moves, but the streets fill with new earners. Which sector absorbed them?',
    ['Formal Sector', 'Quinary Sector', 'Life Expectancy'],
    'Unlicensed work is the Informal Sector. Formal hiring froze. Quinary jobs did not suddenly multiply. Life Expectancy is a health measure.'),
  q('mea-inf-3', 'measures', 'Informal Sector',
    'A critic says India’s “services boom” is overstated because millions of new retail jobs are unregistered stalls with no pension. Which concept names those stalls?',
    ['Tertiary Sector', 'Formal Sector', 'Human Development Index'],
    'Unregistered stalls are the Informal Sector. They are also Tertiary, but that label does not explain why they miss the tax base. Formal Sector is what they are not. HDI is a well-being composite.'),
  q('mea-inf-4', 'measures', 'Informal Sector',
    'AP examples include street food, unlicensed cabs, and cash construction. Official GDP often misses them. Which sector is that?',
    ['Formal Sector', 'Primary Sector', 'Isoline Map'],
    'Unrecorded work is Informal. Formal is on the books. Primary is extraction, which those jobs may not be. Isolines are a map type.'),
  q('mea-inf-5', 'measures', 'Informal Sector',
    'A country can look “unemployed” on paper while people still earn money this way. Which sector explains that gap?',
    ['Formal Sector', 'Cartographic Scale', 'World Systems Theory'],
    'Off-the-books earning is the Informal Sector. Formal jobs would appear in the rate. Cartographic Scale is a map ratio. World Systems Theory is a world hierarchy.'),

  q('mea-gin-1', 'measures', 'Gini Coefficient',
    'Country A and Country B have the same average income, but in A the top tenth takes most of the payroll. A 0-to-1 score shows that difference. Which measure is that score?',
    ['Human Development Index', 'Gender Inequality Index', 'Gross National Income'],
    'How evenly income is spread is the Gini Coefficient. HDI averages health, school, and income. GII is gender. GNI is the size of income, not its distribution.'),
  q('mea-gin-2', 'measures', 'Gini Coefficient',
    'Brazil’s average income rose while a distribution score moved closer to zero because cash transfers lifted the bottom fifth. Which score captured the fairness change?',
    ['Literacy Rate', 'Purchasing Power Parity', 'Commodity Dependence'],
    'A move toward 0 is a falling Gini Coefficient. Literacy Rate is reading. PPP adjusts prices. Commodity Dependence is export mix.'),
  q('mea-gin-3', 'measures', 'Gini Coefficient',
    'A city can have a high average wage and still be unequal if tech salaries sit beside informal settlements. Planners want a statistic that rises when that gap widens. Which statistic is that?',
    ['Life Expectancy', 'Formal Sector', 'Absolute Location'],
    'Income-distribution inequality is the Gini Coefficient. Life Expectancy could be high for everyone. Formal Sector share is a different slice. Absolute Location is a coordinate.'),
  q('mea-gin-4', 'measures', 'Gini Coefficient',
    'AP remembers: closer to 0 is more equal; closer to 1 is more unequal. Which development measure uses that 0–1 scale for income shares?',
    ['Human Development Index', 'Gender Inequality Index', 'Literacy Rate'],
    'That 0–1 inequality scale is the Gini Coefficient. HDI and GII are different composites. Literacy Rate is a percent who can read.'),
  q('mea-gin-5', 'measures', 'Gini Coefficient',
    'Two oil states can have similar income per person and very different gaps between rich and poor. Which measure shows that gap?',
    ['Gross National Product', 'Remittances', 'Reference Map'],
    'The gap is the Gini Coefficient. GNP is production size. Remittances are migrant money. A reference map shows location.'),

  q('mea-lif-1', 'measures', 'Life Expectancy',
    'Japan outranks some oil-rich states on development tables because a newborn there is projected to live into the 80s. Which social indicator is doing that work?',
    ['Gross National Income', 'Gini Coefficient', 'Literacy Rate'],
    'Years a newborn is expected to live is Life Expectancy. GNI is money. Gini is inequality. Literacy Rate is schooling.'),
  q('mea-lif-2', 'measures', 'Life Expectancy',
    'The HIV peak pulled southern African rankings down even where school enrollment was rising, because the average person was dying younger. Which indicator registered that collapse most directly?',
    ['Gender Gap', 'Remittances', 'Secondary Sector'],
    'A fall in expected years of life is Life Expectancy. Gender Gap is a male–female difference. Remittances are migrant money. Secondary Sector is manufacturing.'),
  q('mea-lif-3', 'measures', 'Life Expectancy',
    'A U.S. county with high medical spending can still show a shorter average lifespan than a poorer county with less fentanyl. Which measure revealed that?',
    ['Human Development Index', 'Purchasing Power Parity', 'Quinary Sector'],
    'Years of life is Life Expectancy. HDI blends that with school and income. PPP compares prices. Quinary Sector is elite jobs.'),
  q('mea-lif-4', 'measures', 'Life Expectancy',
    'This is the health piece inside the Human Development Index. Which indicator is that piece?',
    ['Literacy Rate', 'Gini Coefficient', 'Formal Sector'],
    'The health piece is Life Expectancy. Literacy Rate is the education idea in older lists. Gini is inequality. Formal Sector is taxed work.'),
  q('mea-lif-5', 'measures', 'Life Expectancy',
    'AP uses this as a social measure of development, not a money total. “People live longer here” is the claim. Which indicator is that?',
    ['Gross National Product', 'Cartogram', 'Friction of Distance'],
    'Living longer is Life Expectancy. GNP is production. A cartogram resizes area. Friction of Distance is the cost of movement.'),

  q('mea-lit-1', 'measures', 'Literacy Rate',
    'Kerala’s income is closer to other Indian states than to Europe, yet a much higher share of adults can read a newspaper. Which social indicator is Kerala famous for?',
    ['Gini Coefficient', 'Formal Sector', 'Site'],
    'The share who can read and write is Literacy Rate. Gini is income shares. Formal Sector is regulated jobs. Site is physical character.'),
  q('mea-lit-2', 'measures', 'Literacy Rate',
    'A factory in Bangladesh rejects applicants who cannot read a safety card, so districts with more adults who never learned to read stay in casual day labor. Which social measure is screening those applicants?',
    ['Life Expectancy', 'Commodity Dependence', 'Relative Location'],
    'Being able to read the card is Literacy Rate. Life Expectancy is years lived. Commodity Dependence is export concentration. Relative Location is position compared with other places.'),
  q('mea-lit-3', 'measures', 'Literacy Rate',
    'Colonial schooling left some African coastal cities with far more adults who can fill out a ballot than inland districts of the same country. Income maps do not match that pattern. Which indicator would?',
    ['Gross National Product', 'Graduated Symbol Map', 'Friction of Distance'],
    'The ballot-and-form skill is Literacy Rate. GNP is a production total. A graduated symbol map could display the rate but is not the indicator. Friction of Distance is movement cost.'),
  q('mea-lit-4', 'measures', 'Literacy Rate',
    'The vocab and older development lists treat this percent as a key social measure. “More adults can read” raises it. Which measure is that?',
    ['Gender Inequality Index', 'Primary Sector', 'Isoline Map'],
    'Percent who can read is Literacy Rate. GII is a gender composite. Primary Sector is extraction. Isolines connect equal values.'),
  q('mea-lit-5', 'measures', 'Literacy Rate',
    'A student says development is only factories. A better AP reply includes this school-outcome percent. Which indicator is that?',
    ['Secondary Sector', 'Toponyms', 'World Scale'],
    'The school-outcome percent is Literacy Rate. Secondary Sector is manufacturing. Toponyms are place names. World Scale compares countries.'),

  q('mea-gg-1', 'measures', 'Gender Gap',
    'In several Gulf states, women outnumber men in universities but remain far less likely to hold paid jobs or parliamentary seats. Which concept names that unevenness?',
    ['Gender Inequality Index', 'Life Expectancy', 'Vernacular Region'],
    'A systematic male–female difference is a Gender Gap. Gender Inequality Index is one UN composite of several gaps. Life Expectancy might not differ. A vernacular region is a mental area.'),
  q('mea-gg-2', 'measures', 'Gender Gap',
    'U.S. girls now finish high school at slightly higher rates than boys in many districts, while women still earn less in the same jobs. Both are male–female differences. Which term covers that?',
    ['Human Development Index', 'Formal Sector', 'Pattern'],
    'Any systematic male–female difference is a Gender Gap. HDI is a three-part composite. Formal Sector is legal work. Pattern is a spatial arrangement.'),
  q('mea-gg-3', 'measures', 'Gender Gap',
    'A Sahelian study finds women grow much of the food but hold little titled land, so they cannot use plots as loan collateral. Which concept is that unequal control?',
    ['Gender Inequality Index', 'Possibilism', 'Quaternary Sector'],
    'Unequal land control by sex is a Gender Gap. GII might later summarize several gaps. Possibilism is a human-environment theory. Quaternary Sector is knowledge work.'),
  q('mea-gg-4', 'measures', 'Gender Gap',
    'AP uses this everyday phrase for differences in school, work, or politics between males and females. It is not yet the UN’s 0–1 composite. Which term is the difference itself?',
    ['Gender Inequality Index', 'Gini Coefficient', 'Site'],
    'The difference itself is a Gender Gap. GII is the composite index. Gini is income inequality, not gender. Site is physical character.'),
  q('mea-gg-5', 'measures', 'Gender Gap',
    'A map of “percent of parliament that is female” is showing this kind of difference, not life expectancy and not a region type. Which concept is that?',
    ['Formal Region', 'Life Expectancy', 'Remote Sensing'],
    'A male–female political difference is a Gender Gap. A Formal Region is a uniform area. Life Expectancy is years lived. Remote Sensing is satellite data.'),

  q('mea-gii-1', 'measures', 'Gender Inequality Index',
    'The UN publishes a 0-to-1 composite that gets worse when maternal mortality is high, teen births are common, women hold few parliamentary seats, and female labor-force participation lags. Which index is that?',
    ['Human Development Index', 'Gender Gap', 'Gini Coefficient'],
    'That reproductive-health + empowerment + labor composite is the Gender Inequality Index. HDI mixes life expectancy, schooling, and income for everyone. Gender Gap is a looser term for one difference. Gini is income inequality.'),
  q('mea-gii-2', 'measures', 'Gender Inequality Index',
    'Qatar can look developed on income and schooling yet score poorly on a UN gender composite because political representation and labor-force gaps remain wide. Which index shows that contradiction?',
    ['Human Development Index', 'Gross National Income', 'Literacy Rate'],
    'The gender composite is the Gender Inequality Index. HDI and GNI can still look strong. Literacy Rate is only one education measure.'),
  q('mea-gii-3', 'measures', 'Gender Inequality Index',
    'Rwanda reserved parliamentary seats for women, which improved one UN score even while maternal-health challenges remained. Which index moves when empowerment, health, and labor inputs change together?',
    ['Gini Coefficient', 'Purchasing Power Parity', 'World Systems Theory'],
    'A composite that includes parliamentary share plus health and labor is the Gender Inequality Index. Gini moves with income shares. PPP is prices. World Systems Theory is not an index.'),
  q('mea-gii-4', 'measures', 'Gender Inequality Index',
    'AP remembers: a high score on this index is bad (more inequality), the opposite of HDI. Which index is that?',
    ['Human Development Index', 'Literacy Rate', 'Choropleth Map'],
    'High = more gender inequality is the Gender Inequality Index. High HDI is good. Literacy Rate is a percent. A choropleth is a map type.'),
  q('mea-gii-5', 'measures', 'Gender Inequality Index',
    'A student lists “women in parliament” as a Gender Gap. The teacher wants the official UN composite name used on the exam. Which index is that?',
    ['Gender Gap', 'Gini Coefficient', 'Formal Sector'],
    'The official composite is the Gender Inequality Index. Gender Gap is the everyday difference. Gini is income. Formal Sector is taxed work.'),

  q('mea-hdi-1', 'measures', 'Human Development Index',
    'Equatorial Guinea’s oil income can look “high income,” but years of schooling and expected lifespan lag. The UN’s best-known composite is designed to stop researchers from treating money as development. Which composite is that?',
    ['Gender Inequality Index', 'Gini Coefficient', 'Gross National Income'],
    'HDI combines life expectancy, education, and income so oil money alone cannot carry the ranking. GII is gender-specific. Gini is inequality. GNI is the income piece HDI refuses to use by itself.'),
  q('mea-hdi-2', 'measures', 'Human Development Index',
    'Cuba has long ranked closer to much richer countries on a UN development score than its income would predict, because health and schooling are strong. Which index is doing that re-ranking?',
    ['Gross National Product', 'Commodity Dependence', 'Isoline Map'],
    'A composite that can lift a country with good health and school outcomes is the Human Development Index. GNP is only production. Commodity Dependence is export mix. An isoline map is a cartographic form.'),
  q('mea-hdi-3', 'measures', 'Human Development Index',
    'A student says “development = factories.” A better AP reply is the standard UN ranking that also asks how long people live and how long they stay in school. Which ranking is that?',
    ['Formal Sector', 'Cartographic Scale', 'Quinary Sector'],
    'That three-part UN ranking is the Human Development Index. Formal Sector is legal work. Cartographic Scale is a map ratio. Quinary Sector is elite jobs.'),
  q('mea-hdi-4', 'measures', 'Human Development Index',
    'The vocab list describes this as a comparative measure of well-being using literacy, education, life expectancy, and related factors. Which index is that?',
    ['Gini Coefficient', 'Gender Inequality Index', 'Purchasing Power Parity'],
    'That well-being composite is the Human Development Index. Gini is income shares. GII is gender. PPP is a price adjustment.'),
  q('mea-hdi-5', 'measures', 'Human Development Index',
    'Norway usually sits near the top of AP development tables because this score is high, not because it has the most factories. Which score is that?',
    ['Primary Sector', 'Dot Distribution Map', 'Friction of Distance'],
    'The UN well-being score is the Human Development Index. Primary Sector is extraction. A dot map is a symbol type. Friction of Distance is movement cost.'),
]
