import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_MEASURE_QUESTIONS: VocabQuestion[] = [
  q('mea-gnp-1', 'measures', 'Gross National Product',
    'Honda builds cars in Ohio, but Japan still counts them as Japanese output because Honda is a Japanese company. Which measure counts production by a nation\'s own companies, even when factories are in another country?',
    ['Gross National Income', 'Purchasing Power Parity', 'Formal Sector'],
    'Production by a country\'s own firms—even abroad—is Gross National Product. GNI is income residents receive. PPP compares buying power. Formal Sector is taxed, on-the-books work.'),
  q('mea-gnp-2', 'measures', 'Gross National Product',
    'A U.S. clothing brand owns factories in Bangladesh. Economists still add those shirts to U.S. production totals because the company is American. Which measure is this?',
    ['Human Development Index', 'Gini Coefficient', 'Remittances'],
    'Output by a nation\'s own businesses, including overseas factories, is Gross National Product. HDI mixes health, school, and income. Gini measures inequality. Remittances are money migrants send home.'),
  q('mea-gnp-3', 'measures', 'Gross National Product',
    'Toyota\'s Kentucky plant makes Camrys. Japan includes those cars in its national output because Toyota is Japanese. Which production measure follows a country\'s own firms, not just factories inside its borders?',
    ['Literacy Rate', 'Relative Location', 'Built Environment'],
    'Production by a nation\'s own companies worldwide is Gross National Product. Literacy Rate is the share who can read and write. Relative Location is position compared with other places. Built Environment is human-made surroundings.'),
  q('mea-gnp-4', 'measures', 'Gross National Product',
    'An Irish tech firm has programmers in India, but Ireland counts that software as Irish output because the firm is Irish. Which measure tracks production by a nation\'s own businesses, even abroad?',
    ['Gross National Income', 'Purchasing Power Parity', 'Gender Inequality Index'],
    'Goods and services from a country\'s own firms abroad count toward Gross National Product. GNI is money residents receive. PPP compares what money buys. GII is a UN gender composite.'),
  q('mea-gnp-5', 'measures', 'Gross National Product',
    'GDP counts everything made inside a country\'s borders. Another total follows a country\'s own companies instead—including factories they own overseas. Which measure is that second total?',
    ['Life Expectancy', 'Secondary Sector', 'Cartogram'],
    'Following a nation\'s own companies—even abroad—is Gross National Product. Life Expectancy is how long people typically live. Secondary Sector is manufacturing. A cartogram resizes map area by data.'),

  q('mea-gni-1', 'measures', 'Gross National Income',
    'Citizens own companies overseas and receive large dividend checks from them, even though little is produced at home. Which measure totals the income residents receive, including money earned abroad?',
    ['Gross National Product', 'Gini Coefficient', 'Primary Sector'],
    'All income residents receive—including from abroad—is Gross National Income. GNP is production by a nation\'s own firms. Gini measures inequality. Primary Sector is farming and mining.'),
  q('mea-gni-2', 'measures', 'Gross National Income',
    'Kuwait has few factories at home, but citizens earn huge profits from oil companies abroad. Officials want the total money Kuwaiti residents actually take in, including from overseas. Which measure is that?',
    ['Remittances', 'Isoline Map', 'Quinary Sector'],
    'Income residents receive, including from foreign investments, is Gross National Income. Remittances are one kind of transfer migrants send home. Isolines are a map type. Quinary Sector is top leadership work.'),
  q('mea-gni-3', 'measures', 'Gross National Income',
    'Factory output inside the border is the wrong total for this chart. The teacher wants money residents actually take in—wages, profits, and investment income from overseas. Which measure is that?',
    ['Gross National Product', 'Formal Sector', 'Site'],
    'Income residents receive—including from overseas—is Gross National Income. GNP counts production by national firms. Formal Sector is taxed, licensed work. Site is a place\'s physical features.'),
  q('mea-gni-4', 'measures', 'Gross National Income',
    'A small country has little production inside its borders, but its citizens own profitable businesses worldwide. Which measure adds up all income those residents receive, including from abroad?',
    ['Literacy Rate', 'Commodity Dependence', 'Cartogram'],
    'Total income received by residents, including from overseas, is Gross National Income. Literacy Rate is the share who can read and write. Commodity Dependence is reliance on one export. A cartogram is a map type.'),
  q('mea-gni-5', 'measures', 'Gross National Income',
    'GDP measures production inside borders. Another statistic counts every dollar a country\'s residents actually receive—including paychecks and profits earned in other countries. Which measure is that?',
    ['Gross National Product', 'Purchasing Power Parity', 'Formal Sector'],
    'Income residents receive from anywhere is Gross National Income. GNP is output by a nation\'s own firms. PPP compares what money buys. Formal Sector is on-the-books employment.'),

  q('mea-rem-1', 'measures', 'Remittances',
    'Maria works in Texas and wires $200 every month to her mother in Mexico for groceries. Which term describes money a migrant worker sends home to family?',
    ['Gross National Income', 'Formal Sector', 'Quaternary Sector'],
    'Money migrants send home to family is Remittances. That money can later count in GNI, but the transfer itself is remittances. Formal Sector is taxed work. Quaternary Sector is information-based work.'),
  q('mea-rem-2', 'measures', 'Remittances',
    'Village families build new roofs after sons working in Gulf states send cash home each month. Which concept names this flow of money from workers abroad to their families?',
    ['Purchasing Power Parity', 'Commodity Dependence', 'Time-Space Compression'],
    'Family money sent home by migrants is Remittances. PPP compares what money buys. Commodity Dependence is reliance on one export. Time-Space Compression is faster global connection.'),
  q('mea-rem-3', 'measures', 'Remittances',
    'A student in Seoul pays tuition with money her dad sends from his job in Australia. Which vocabulary term describes money a migrant sends back to relatives at home?',
    ['Gross National Product', 'Informal Sector', 'Functional Region'],
    'Money wired home by a worker abroad is Remittances. GNP is a production total. Informal Sector is unlicensed, untaxed work. A Functional Region is organized around a central node.'),
  q('mea-rem-4', 'measures', 'Remittances',
    'Carlos picks fruit in California and sends half his paycheck to his parents in Guatemala every month. Which concept is this money migrants send home?',
    ['Secondary Sector', 'Absolute Location', 'Possibilism'],
    'Money sent home by a migrant worker is Remittances. Secondary Sector is manufacturing. Absolute Location is a fixed coordinate. Possibilism is human choice within environmental limits.'),
  q('mea-rem-5', 'measures', 'Remittances',
    'Philippine shops boom even without new factories, because overseas workers mail money to relatives back home. Which term describes those family transfers?',
    ['Life Expectancy', 'Choropleth Map', 'World Scale'],
    'Money migrants send to family at home is Remittances. Life Expectancy is how long people typically live. A choropleth shades areas by a rate. World Scale is global-level analysis.'),

  q('mea-ppp-1', 'measures', 'Purchasing Power Parity',
    'You earn $3,000 a month. In one city that buys a full grocery cart; in another it buys only a few bags because prices are much higher. Which measure compares what the same money can actually buy in different countries?',
    ['Gini Coefficient', 'Gross National Income', 'Literacy Rate'],
    'Comparing what the same money can buy—using a basket of goods—is Purchasing Power Parity. Gini measures inequality. GNI is income received. Literacy Rate is the share who can read and write.'),
  q('mea-ppp-2', 'measures', 'Purchasing Power Parity',
    'Researchers build a standard basket of bread, rent, and bus fares to see whether $100 goes further in Mexico or Germany. Which adjustment compares buying power across countries?',
    ['Human Development Index', 'Remittances', 'Absolute Location'],
    'A shared basket of goods used to compare prices is Purchasing Power Parity. HDI mixes health, school, and income. Remittances are migrant transfers. Absolute Location is a coordinate.'),
  q('mea-ppp-3', 'measures', 'Purchasing Power Parity',
    'Two nurses earn the same salary in dollars, but one lives where lunch costs $2 and the other where lunch costs $15. Which concept compares how far the same paycheck stretches in different places?',
    ['Formal Sector', 'Gender Inequality Index', 'World Systems Theory'],
    'Seeing how far the same money goes locally is Purchasing Power Parity. Formal Sector is taxed work. GII is a UN gender composite. World Systems Theory describes core and periphery.'),
  q('mea-ppp-4', 'measures', 'Purchasing Power Parity',
    'Exchange rates make India look very poor, but a typical meal there costs pennies compared to Europe. Which measure accounts for what money can actually buy in each country?',
    ['Gross National Product', 'Gini Coefficient', 'Reference Map'],
    'Adjusting for local prices with a basket of goods is Purchasing Power Parity. GNP is a production total. Gini measures inequality. A reference map shows basic location.'),
  q('mea-ppp-5', 'measures', 'Purchasing Power Parity',
    'The World Bank compares how many goods a typical worker\'s wage could buy in each country using the same shopping list. Which measure is this price comparison?',
    ['Literacy Rate', 'Distance Decay', 'Quinary Sector'],
    'Comparing buying power with a standard basket is Purchasing Power Parity. Literacy Rate is reading and writing ability. Distance Decay is fading interaction over distance. Quinary Sector is top decision-making work.'),

  q('mea-for-1', 'measures', 'Formal Sector',
    'Juan gets a taxed paycheck, pays income tax, and his hospital job appears on government labor records. Which part of the economy is this legal, licensed, on-the-books work?',
    ['Informal Sector', 'Secondary Sector', 'Site'],
    'Taxed, licensed jobs recorded in official files are Formal Sector. Home sewing for cash is Informal Sector. Secondary Sector is manufacturing. Site is physical place characteristics.'),
  q('mea-for-2', 'measures', 'Formal Sector',
    'A teacher\'s salary is taxed and listed in official employment statistics. A neighbor babysits for cash with no license or tax forms. Which sector is the teacher\'s job in?',
    ['Informal Sector', 'Quaternary Sector', 'Functional Region'],
    'The recorded, taxed job is Formal Sector. Cash babysitting with no paperwork is Informal Sector. Quaternary Sector is knowledge work. A Functional Region is nodal.'),
  q('mea-for-3', 'measures', 'Formal Sector',
    'Government statisticians count only jobs that are licensed, taxed, and recorded in official tax files. Which sector are they measuring?',
    ['Informal Sector', 'Primary Sector', 'Vernacular Region'],
    'What tax records and licenses capture is Formal Sector. Unregistered backyard work is Informal Sector. Primary Sector is extraction. A vernacular region is a perceived area.'),
  q('mea-for-4', 'measures', 'Formal Sector',
    'An accountant pays tax and has a written contract; a street vendor selling similar snacks has no permit and keeps all cash off the books. Which sector is the accountant in?',
    ['Informal Sector', 'Quinary Sector', 'Tertiary Sector'],
    'Regulated, taxed, documented work is Formal Sector. The unlicensed vendor is Informal Sector. Both can be services, but only the accountant is on the books. Quinary is top leadership.'),
  q('mea-for-5', 'measures', 'Formal Sector',
    'The nurse\'s job shows up in tax records and official production statistics because the employer files paperwork and withholds taxes. Which concept is this?',
    ['Informal Sector', 'Life Expectancy', 'Pattern'],
    'Jobs already counted in tax and labor records are Formal Sector. Cash jobs with no records are Informal Sector. Life Expectancy is how long people live. Pattern is spatial arrangement.'),

  q('mea-inf-1', 'measures', 'Informal Sector',
    'Rosa sells tacos from a cart with no business license and keeps all cash—nothing appears on tax forms. Which sector is this unlicensed, untaxed work?',
    ['Formal Sector', 'Primary Sector', 'Isoline Map'],
    'Cash work with no license or tax records is Informal Sector. Taxed hospital jobs are Formal Sector. Primary Sector is extraction. Isolines are a map type.'),
  q('mea-inf-2', 'measures', 'Informal Sector',
    'After a recession, many people earn money cutting hair in homes or driving unlicensed taxis that the government does not track. Which sector is this hidden work?',
    ['Formal Sector', 'Quinary Sector', 'Life Expectancy'],
    'Unlicensed, unrecorded work is Informal Sector. Registered jobs are Formal Sector. Quinary Sector is elite leadership. Life Expectancy is a health measure.'),
  q('mea-inf-3', 'measures', 'Informal Sector',
    'Street vendors accept only cash, have no permits, and never appear in official unemployment or tax records. Which part of the economy is this?',
    ['Formal Sector', 'Quaternary Sector', 'Secondary Sector'],
    'Off-the-books, untaxed stalls are Informal Sector. Licensed shops on tax rolls are Formal Sector. Quaternary is information work. Secondary is manufacturing.'),
  q('mea-inf-4', 'measures', 'Informal Sector',
    'A tailor sews clothes in an unregistered home workshop and sells them at a market stall with no receipt or tax payment. Which sector describes this cash, unlicensed work?',
    ['Tertiary Sector', 'Formal Sector', 'Human Development Index'],
    'Unregistered, untaxed production is Informal Sector. It may still be a service, but it is not on the books. Formal Sector is the opposite. HDI is a well-being composite.'),
  q('mea-inf-5', 'measures', 'Informal Sector',
    'Official job counts miss millions of people who work for cash tips with no employer paperwork or tax withholding. Which sector includes those off-the-books jobs?',
    ['Formal Sector', 'Cartographic Scale', 'World Systems Theory'],
    'Cash jobs the government neither licenses nor taxes are Informal Sector. Registered jobs are Formal Sector. Cartographic Scale is a map ratio. World Systems Theory is a global hierarchy model.'),

  q('mea-gin-1', 'measures', 'Gini Coefficient',
    'Country A and Country B have the same average income, but in Country A three billionaires own almost everything while most people are poor. Which 0-to-1 measure shows how unequally income is spread between rich and poor?',
    ['Human Development Index', 'Gender Inequality Index', 'Literacy Rate'],
    'How unevenly income is shared is the Gini Coefficient—a wider rich-poor gap means a higher score. HDI and GII are different composites. Literacy Rate is who can read and write.'),
  q('mea-gin-2', 'measures', 'Gini Coefficient',
    'After taxes on the wealthy, the gap between the richest families and the poorest families gets smaller. Which inequality measure moved toward equality?',
    ['Literacy Rate', 'Purchasing Power Parity', 'Commodity Dependence'],
    'A shrinking rich-poor income gap lowers the Gini Coefficient. Literacy Rate is schooling. PPP compares prices. Commodity Dependence is export concentration.'),
  q('mea-gin-3', 'measures', 'Gini Coefficient',
    'A few families control most of the nation\'s paycheck while millions struggle—planners want a statistic that rises when that income gap widens. Which measure is that?',
    ['Life Expectancy', 'Formal Sector', 'Absolute Location'],
    'The spread of income between rich and poor is the Gini Coefficient. Life Expectancy is years lived. Formal Sector is taxed work. Absolute Location is a coordinate.'),
  q('mea-gin-4', 'measures', 'Gini Coefficient',
    'Norway and Nigeria have similar average incomes, but Nigeria\'s rich live in mansions while most citizens are very poor. Which measure captures how unequal income distribution is?',
    ['Gross National Product', 'Remittances', 'Reference Map'],
    'Unequal sharing of income is the Gini Coefficient. GNP is total production. Remittances are migrant money sent home. A reference map shows location.'),
  q('mea-gin-5', 'measures', 'Gini Coefficient',
    'The top 10% of earners take home 70% of all wages in one country, even though average income looks normal. Which measure records how unevenly income is spread?',
    ['Human Development Index', 'Gender Inequality Index', 'Gross National Income'],
    'Uneven income shares between rich and poor are the Gini Coefficient. HDI averages health, school, and income. GII is gender. GNI is total income received, not its spread.'),

  q('mea-lif-1', 'measures', 'Life Expectancy',
    'Babies born in Japan today are expected to live to about 84; babies born in some poorer countries may only reach 55. Which health statistic compares how long people typically live?',
    ['Gross National Income', 'Gini Coefficient', 'Literacy Rate'],
    'How long people typically live from birth is Life Expectancy. GNI is money received. Gini is inequality. Literacy Rate is reading and writing ability.'),
  q('mea-lif-2', 'measures', 'Life Expectancy',
    'Clean water and vaccines help people survive longer, raising the average number of years a newborn can expect to live. Which development indicator measures that?',
    ['Gender Gap', 'Remittances', 'Secondary Sector'],
    'Average years a person is expected to live is Life Expectancy. Gender Gap is a male–female difference. Remittances are migrant transfers. Secondary Sector is manufacturing.'),
  q('mea-lif-3', 'measures', 'Life Expectancy',
    'A UN table ranks countries by how many years the average person lives from birth—Japan ranks high; some conflict zones rank low. Which measure is this table showing?',
    ['Human Development Index', 'Purchasing Power Parity', 'Quinary Sector'],
    'Years people typically live is Life Expectancy. HDI blends that with school and income. PPP compares prices. Quinary Sector is elite jobs.'),
  q('mea-lif-4', 'measures', 'Life Expectancy',
    'Smoking and disease outbreaks cause many people to die in their 50s instead of their 80s. Which indicator drops when people die younger on average?',
    ['Gross National Product', 'Cartogram', 'Friction of Distance'],
    'Dying younger lowers Life Expectancy. GNP is production. A cartogram resizes area. Friction of Distance is movement cost.'),
  q('mea-lif-5', 'measures', 'Life Expectancy',
    'Doctors track how long residents typically survive from birth in each country—often shown as a number like 72 or 83 years. Which health measure is this?',
    ['Literacy Rate', 'Gini Coefficient', 'Formal Sector'],
    'Typical years lived from birth is Life Expectancy. Literacy Rate is who can read and write. Gini is inequality. Formal Sector is taxed work.'),

  q('mea-lit-1', 'measures', 'Literacy Rate',
    'In one province 95% of adults can read a newspaper; in another only 40% can. Which statistic measures the share of people who can read and write?',
    ['Gini Coefficient', 'Formal Sector', 'Site'],
    'The percent who can read and write is Literacy Rate. Gini is income inequality. Formal Sector is regulated jobs. Site is physical character.'),
  q('mea-lit-2', 'measures', 'Literacy Rate',
    'A job application requires reading safety instructions—many applicants are rejected because they never learned to read. Which development measure relates to reading and writing ability?',
    ['Life Expectancy', 'Commodity Dependence', 'Relative Location'],
    'Being able to read and write is Literacy Rate. Life Expectancy is years lived. Commodity Dependence is export concentration. Relative Location is position compared with other places.'),
  q('mea-lit-3', 'measures', 'Literacy Rate',
    'UNESCO reports that 88% of adults in one country and 52% in another can read and write basic sentences. Which indicator is this percentage?',
    ['Gender Inequality Index', 'Primary Sector', 'Isoline Map'],
    'Percent of adults who can read and write is Literacy Rate. GII is a gender composite. Primary Sector is extraction. Isolines connect equal values.'),
  q('mea-lit-4', 'measures', 'Literacy Rate',
    'Elections fail when most voters cannot read the ballot. Which social measure tracks the percentage of adults who can read and write?',
    ['Secondary Sector', 'Toponyms', 'World Scale'],
    'The reading-and-writing percentage is Literacy Rate. Secondary Sector is manufacturing. Toponyms are place names. World Scale is global-level analysis.'),
  q('mea-lit-5', 'measures', 'Literacy Rate',
    'City adults easily fill out job forms, but rural adults often cannot read a medicine label. Which statistic measures who can read and write in a population?',
    ['Gross National Product', 'Graduated Symbol Map', 'Friction of Distance'],
    'Share of people who can read and write is Literacy Rate. GNP is a production total. A graduated symbol map could display the rate. Friction of Distance is movement cost.'),

  q('mea-gg-1', 'measures', 'Gender Gap',
    'Women graduate from college at the same rate as men but earn 70 cents for every dollar men make in the same jobs. Which concept describes this measurable difference between men and women?',
    ['Gender Inequality Index', 'Human Development Index', 'Formal Sector'],
    'A measurable male–female difference in pay or opportunity is a Gender Gap. GII bundles several gaps into one UN index. HDI is overall well-being. Formal Sector is legal work.'),
  q('mea-gg-2', 'measures', 'Gender Gap',
    'Men hold 90% of farmland titles even though women do most of the farming work. Which term describes this male–female difference in land ownership?',
    ['Gender Inequality Index', 'Possibilism', 'Quaternary Sector'],
    'Unequal land control by sex is a Gender Gap. GII is a UN composite of several measures. Possibilism is environmental choice. Quaternary Sector is knowledge work.'),
  q('mea-gg-3', 'measures', 'Gender Gap',
    'Girls and boys attend school equally, but almost no women sit in Parliament. Which concept names the difference between men and women in political power?',
    ['Gender Inequality Index', 'Gini Coefficient', 'Site'],
    'The male–female difference in office holding is a Gender Gap. GII is the official composite index. Gini is income inequality. Site is physical character.'),
  q('mea-gg-4', 'measures', 'Gender Gap',
    'More women finish university than men, yet far fewer women hold paid jobs afterward. Which vocabulary term describes this contrast between the sexes?',
    ['Formal Region', 'Life Expectancy', 'Remote Sensing'],
    'A systematic male–female difference in employment is a Gender Gap. A Formal Region is a uniform area. Life Expectancy is years lived. Remote Sensing is satellite data.'),
  q('mea-gg-5', 'measures', 'Gender Gap',
    'Men and women study side by side in school, but women rarely own businesses or property. Which concept describes measurable differences in outcomes between men and women?',
    ['Gender Inequality Index', 'Life Expectancy', 'Vernacular Region'],
    'Measurable male–female differences in jobs, land, or school are a Gender Gap. GII is a UN composite index. Life Expectancy may be similar for both sexes. A vernacular region is a mental area.'),

  q('mea-gii-1', 'measures', 'Gender Inequality Index',
    'The UN combines three scores—maternal deaths, women in parliament, and women in paid work—into one index where a higher number means worse conditions for women. Which index is this?',
    ['Human Development Index', 'Gender Gap', 'Gini Coefficient'],
    'Maternal health plus women in politics plus paid work—in one score where higher is worse—is the Gender Inequality Index. HDI is overall well-being. Gender Gap is one difference. Gini is income inequality.'),
  q('mea-gii-2', 'measures', 'Gender Inequality Index',
    'A country looks wealthy, but many mothers die in childbirth, few women hold office, and most women do not earn wages. The UN gives it a bad score on which gender composite index?',
    ['Human Development Index', 'Literacy Rate', 'Choropleth Map'],
    'Higher score = worse on the Gender Inequality Index. High HDI is good. Literacy Rate is a percent. A choropleth is a map type.'),
  q('mea-gii-3', 'measures', 'Gender Inequality Index',
    'Norway ranks low (good) and Yemen ranks high (bad) on a UN table mixing maternal health, female political power, and women\'s employment. Which index is this?',
    ['Human Development Index', 'Gross National Income', 'Literacy Rate'],
    'That UN composite of maternal health, politics, and paid work is the Gender Inequality Index. HDI and GNI can still look strong. Literacy Rate is only one education measure.'),
  q('mea-gii-4', 'measures', 'Gender Inequality Index',
    'Policy makers track maternal mortality, share of women in government, and female labor participation in a single 0-to-1 UN score—higher means more inequality. Which index is this?',
    ['Gini Coefficient', 'Purchasing Power Parity', 'World Systems Theory'],
    'Combining maternal health, empowerment, and labor into one score is the Gender Inequality Index. Gini measures income shares. PPP is prices. World Systems Theory is not an index.'),
  q('mea-gii-5', 'measures', 'Gender Inequality Index',
    'The UN penalizes countries where mothers die young, women hold few elected seats, and women rarely work for pay—all rolled into one official ranking. Which composite measure is this?',
    ['Gender Gap', 'Gini Coefficient', 'Formal Sector'],
    'That official UN composite is the Gender Inequality Index. Gender Gap is a single everyday difference. Gini is income inequality. Formal Sector is taxed work.'),

  q('mea-hdi-1', 'measures', 'Human Development Index',
    'The UN ranks Norway near the top because people live long, stay in school many years, and earn high incomes—a mix of health, education, and wealth. Which well-being index is this?',
    ['Gender Inequality Index', 'Gini Coefficient', 'Gross National Income'],
    'Long life plus schooling plus income in one UN ranking is the Human Development Index. GII is gender. Gini is inequality. GNI is income alone.'),
  q('mea-hdi-2', 'measures', 'Human Development Index',
    'A country has oil wealth but people die young and few finish school, so its UN well-being score stays low despite high income. Which composite index combines long life, schooling, and income?',
    ['Gender Inequality Index', 'Gini Coefficient', 'Gross National Income'],
    'Health, education, and income blended together is the Human Development Index. GII is gender. Gini is inequality. GNI is income alone.'),
  q('mea-hdi-3', 'measures', 'Human Development Index',
    'Switzerland ranks above a richer oil state because residents live longer and attend school longer, not because it has more factories. Which UN ranking measures overall human well-being this way?',
    ['Formal Sector', 'Cartographic Scale', 'Quinary Sector'],
    'A ranking mixing life span, schooling, and income is the Human Development Index. Formal Sector is legal work. Cartographic Scale is a map ratio. Quinary Sector is elite jobs.'),
  q('mea-hdi-4', 'measures', 'Human Development Index',
    'Students compare countries using a UN table that blends average years of life, years of schooling, and income per person—not factory output alone. Which index is this?',
    ['Gini Coefficient', 'Gender Inequality Index', 'Purchasing Power Parity'],
    'That well-being mix is the Human Development Index. Gini is income shares. GII is gender. PPP is a price adjustment.'),
  q('mea-hdi-5', 'measures', 'Human Development Index',
    'Cuba ranks higher than wealth alone would predict because strong health care and schooling boost its UN score. Which measure mixes life span, education, and income into one well-being ranking?',
    ['Primary Sector', 'Dot Distribution Map', 'Friction of Distance'],
    'Long life, schooling, and income combined is the Human Development Index. Primary Sector is extraction. A dot map is a symbol type. Friction of Distance is movement cost.'),
]
