import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_MEASURE_QUESTIONS: VocabQuestion[] = [
  q('mea-gnp-1', 'measures', 'Gross National Product',
    'A Japanese automaker’s factory in Tennessee manufactures automobiles on United States soil. A researcher wants a total that follows Japan’s own firms, not the factory’s street address.',
    ['Gross National Income', 'Purchasing Power Parity', 'Formal Sector'],
    'Gross National Product totals output belonging to a nation’s people and firms, even abroad. Gross National Income tracks income received. Purchasing Power Parity only adjusts prices. Formal Sector is regulated work.'),
  q('mea-gnp-2', 'measures', 'Gross National Product',
    'Foreign companies record huge sales in a small country. A researcher wants “what that country’s own firms produce,” not “what happens inside the border.”',
    ['Human Development Index', 'Gini Coefficient', 'Remittances'],
    '“Nationals’ production” is Gross National Product. Human Development Index adds health and school. Gini is inequality. Remittances are household transfers.'),
  q('mea-gnp-3', 'measures', 'Gross National Product',
    'A United States consulting firm bills clients from a London office. That work still counts toward the United States national product total because it belongs to a United States company.',
    ['Literacy Rate', 'Relative Location', 'Built Environment'],
    'Output by a nation’s firms abroad is Gross National Product. Literacy Rate is schooling. Relative Location is position compared with other places. Built Environment is buildings and roads.'),
  q('mea-gnp-4', 'measures', 'Gross National Product',
    'A U.S. clothing brand designs shirts in New York and sews them in factories it owns in Vietnam. A researcher wants a production total that still counts those overseas factories as American output.',
    ['Gross National Income', 'Purchasing Power Parity', 'Gender Inequality Index'],
    'Production by a nation’s people and companies is Gross National Product. Gross National Income is income received. Purchasing Power Parity equalizes prices. Gender Inequality Index is a gender composite.'),
  q('mea-gnp-5', 'measures', 'Gross National Product',
    'A Japanese car company builds vehicles in Ohio. A second table follows the company, not the factory address, and still counts those cars as Japan’s output.',
    ['Life Expectancy', 'Secondary Sector', 'Cartogram'],
    'That production total is Gross National Product. Life Expectancy is years lived. Secondary Sector is manufacturing. A cartogram resizes map area.'),

  q('mea-gni-1', 'measures', 'Gross National Income',
    'The United Nations development index uses a wealth component that includes wages and profits residents receive, even from foreign investments. It is not merely factory output inside the border.',
    ['Gross National Product', 'Purchasing Power Parity', 'Formal Sector'],
    'The UN income series is Gross National Income. Gross National Product is a related production idea. Purchasing Power Parity is the price adjustment often applied to it. Formal Sector is legal work.'),
  q('mea-gni-2', 'measures', 'Gross National Income',
    'The Philippines receives substantial overseas-worker transfers and some shipping profits from abroad. This national total is constructed to capture money residents receive from the rest of the world.',
    ['Literacy Rate', 'Commodity Dependence', 'Cartogram'],
    'Income received, including from abroad, is Gross National Income. Literacy Rate is schooling. Commodity Dependence is export concentration. A cartogram is a map type.'),
  q('mea-gni-3', 'measures', 'Gross National Income',
    'A small European country produces little inside its borders, but residents own companies overseas and receive large payments from them. Income per person looks very high.',
    ['Gini Coefficient', 'Gender Gap', 'Primary Sector'],
    'Incoming property and labor income is Gross National Income. Gini describes how income is shared. Gender Gap is a male–female difference. Primary Sector is farming or mining.'),
  q('mea-gni-4', 'measures', 'Gross National Income',
    'A development chart compares countries by the average income residents receive, including money earned from investments abroad, not by how many factories sit inside the border.',
    ['Remittances', 'Isoline Map', 'Quinary Sector'],
    'The standard per-person income in AP is Gross National Income. Remittances are one kind of transfer that can enter it. An isoline map is weather-style lines. Quinary Sector is top leadership.'),
  q('mea-gni-5', 'measures', 'Gross National Income',
    'A student looks at factory output inside one country. The teacher wants a different total: income residents actually receive, including wages and profits that arrive from other countries.',
    ['Gross National Product', 'Formal Sector', 'Site'],
    'Income residents receive is Gross National Income. Gross National Product is production by nationals. Formal Sector is taxed work. Site is physical character.'),

  q('mea-rem-1', 'measures', 'Remittances',
    'In a Salvadoran town, new concrete houses appear after the California harvest season, although no factory opened locally. Households spend money a member earned abroad and transferred home.',
    ['Gross National Income', 'Formal Sector', 'Quaternary Sector'],
    'Household transfers from migrants are Remittances. Those transfers later enter Gross National Income, but the flow itself is remittances. Formal Sector is taxed work. Quaternary Sector is knowledge work.'),
  q('mea-rem-2', 'measures', 'Remittances',
    'In a mountain village, school fees are paid in October when family members working abroad send money home. No new factory opened nearby.',
    ['Purchasing Power Parity', 'Commodity Dependence', 'Time-Space Compression'],
    'Migrant-to-household transfers are Remittances. Purchasing Power Parity compares prices. Commodity Dependence is one-export reliance. Time-space compression is faster connection, not the money itself.'),
  q('mea-rem-3', 'measures', 'Remittances',
    'A family chapel is paid for with money relatives send from jobs abroad. Factory profits sent to a corporate account in another country do not count as the same thing.',
    ['Gross National Product', 'Informal Sector', 'Functional Region'],
    'Hometown and family wires are Remittances. Corporate profit sent abroad is not. Gross National Product is a national total. Informal Sector is unrecorded work. A Functional Region is nodal.'),
  q('mea-rem-4', 'measures', 'Remittances',
    'A family in Mexico adds rooms to its house with money a relative sends from a job in the United States. No mill opened in the village.',
    ['Secondary Sector', 'Absolute Location', 'Possibilism'],
    'Money sent home is Remittances. Secondary Sector is manufacturing. Absolute Location is a coordinate. Possibilism is environmental choice.'),
  q('mea-rem-5', 'measures', 'Remittances',
    'A country has few factories, yet many villages add new houses and shops after workers abroad send money home.',
    ['Life Expectancy', 'Choropleth Map', 'World Scale'],
    'Migrant money is Remittances. Life Expectancy is years lived. A choropleth shades areas by a rate. World Scale compares countries.'),

  q('mea-ppp-1', 'measures', 'Purchasing Power Parity',
    'A nurse in Mumbai earns far fewer dollars than a nurse in Boston, but food and rent also cost much less. Converting at the market exchange rate makes India appear poorer than daily life indicates. This adjustment compares what salaries can actually purchase.',
    ['Gini Coefficient', 'Gross National Income', 'Literacy Rate'],
    'Equalizing what money buys is Purchasing Power Parity. Gini is inequality. Gross National Income is the income being adjusted. Literacy Rate is schooling.'),
  q('mea-ppp-2', 'measures', 'Purchasing Power Parity',
    'Two countries report the same income per person in United States dollars. In one, a grocery basket costs three times as much. Researchers refuse to call them equally affluent until they apply this conversion.',
    ['Human Development Index', 'Remittances', 'Absolute Location'],
    'Equalizing a basket of goods is Purchasing Power Parity. Human Development Index also mixes health and school. Remittances are migrant transfers. Absolute Location is a coordinate.'),
  q('mea-ppp-3', 'measures', 'Purchasing Power Parity',
    'A haircut costs $5 in one country and $25 in another, even when official incomes look similar in dollars. Researchers adjust so they compare what money actually buys.',
    ['Formal Sector', 'Gender Inequality Index', 'World Systems Theory'],
    'Comparing a standard good to reveal price-level differences is Purchasing Power Parity. Formal Sector is legal work. Gender Inequality Index is gender. World Systems Theory is core and periphery.'),
  q('mea-ppp-4', 'measures', 'Purchasing Power Parity',
    'Two countries report the same income in U.S. dollars, but a haircut and a bag of rice cost far less in one of them. Researchers adjust the numbers so they compare what money can actually buy.',
    ['Literacy Rate', 'Distance Decay', 'Quinary Sector'],
    'The price-level adjustment is Purchasing Power Parity. Literacy Rate is schooling. Distance Decay is fading interaction. Quinary Sector is top leadership.'),
  q('mea-ppp-5', 'measures', 'Purchasing Power Parity',
    'A researcher wants to know whether $1,000 a month in Hanoi purchases a similar standard of living to $1,000 a month in Houston.',
    ['Gross National Product', 'Gini Coefficient', 'Reference Map'],
    'Comparing what money buys locally is Purchasing Power Parity. Gross National Product is a production total. Gini is inequality. A reference map shows location.'),

  q('mea-for-1', 'measures', 'Formal Sector',
    'A Nairobi accountant pays income tax, contributes to a hospital fund, and can sue on a written contract. A street vendor two blocks away sells the same snacks with none of those protections.',
    ['Informal Sector', 'Quinary Sector', 'Tertiary Sector'],
    'Regulated, taxed work is the Formal Sector. The vendor is Informal. Both can be Tertiary services. Quinary is top decision-making.'),
  q('mea-for-2', 'measures', 'Formal Sector',
    'Official manufacturing output counts plants recorded in tax files. Unregistered backyard workshops are omitted. The official series is constructed to observe this part of the economy.',
    ['Informal Sector', 'Primary Sector', 'Vernacular Region'],
    'What tax files see is the Formal Sector. Informal work is what they miss. Primary Sector is extraction. A vernacular region is a perceived area.'),
  q('mea-for-3', 'measures', 'Formal Sector',
    'A hospital nurse appears in labor statistics and a collective agreement. A relative paid in cash to care for a neighbor does not.',
    ['Informal Sector', 'Quaternary Sector', 'Functional Region'],
    'The hospital job is Formal. Cash care is Informal. Nursing is not Quaternary research. A Functional Region is a nodal area.'),
  q('mea-for-4', 'measures', 'Formal Sector',
    'A clothing plant issues pay stubs, withholds taxes, and can be inspected by the government. A neighbor sewing the same shirts at home for cash appears in no official file.',
    ['Informal Sector', 'Secondary Sector', 'Site'],
    'On-the-books work is Formal Sector. The factory is also Secondary manufacturing, but the question is about being taxed and recorded. Informal is the opposite. Site is physical character.'),
  q('mea-for-5', 'measures', 'Formal Sector',
    'A hospital nurse appears in tax files and a labor contract. A neighbor paid in cash to watch children does not. Official GDP already includes the nurse.',
    ['Informal Sector', 'Life Expectancy', 'Pattern'],
    'Already-counted legal work is the Formal Sector. The missing shops are Informal. Life Expectancy is health. Pattern is arrangement.'),

  q('mea-inf-1', 'measures', 'Informal Sector',
    'In Lima, much clothing is sewn in unregistered homes and sold in street markets that do not appear on tax rolls. Gross domestic product understates how many people are working.',
    ['Formal Sector', 'Quaternary Sector', 'Secondary Sector'],
    'Unregistered production is the Informal Sector. It can still be manufacturing. Formal Sector is the opposite. Quaternary is specialized information work.'),
  q('mea-inf-2', 'measures', 'Informal Sector',
    'After a currency collapse, more Cairo residents operate unlicensed taxis. Official unemployment scarcely changes, yet the streets fill with new earners.',
    ['Formal Sector', 'Quinary Sector', 'Life Expectancy'],
    'Unlicensed work is the Informal Sector. Formal hiring froze. Quinary jobs did not suddenly multiply. Life Expectancy is a health measure.'),
  q('mea-inf-3', 'measures', 'Informal Sector',
    'A critic argues that India’s services expansion is overstated because millions of new retail jobs are unregistered stalls with no pension.',
    ['Tertiary Sector', 'Formal Sector', 'Human Development Index'],
    'Unregistered stalls are the Informal Sector. They are also Tertiary, but that label does not explain why they miss the tax base. Formal Sector is what they are not. HDI is a well-being composite.'),
  q('mea-inf-4', 'measures', 'Informal Sector',
    'In a large city, many people sell food from street stalls, operate vehicles without licenses, and receive cash wages that never appear in tax records. Official unemployment appears high, yet people continue to work.',
    ['Formal Sector', 'Primary Sector', 'Isoline Map'],
    'Unrecorded, untaxed work is Informal. Formal is on the books. Primary is extraction, which those jobs may not be. Isolines are a map type.'),
  q('mea-inf-5', 'measures', 'Informal Sector',
    'A country can appear unemployed in official statistics while people still earn income through occupations the government neither regulates nor taxes.',
    ['Formal Sector', 'Cartographic Scale', 'World Systems Theory'],
    'Off-the-books earning is the Informal Sector. Formal jobs would appear in the rate. Cartographic Scale is a map ratio. World Systems Theory is a world hierarchy.'),

  q('mea-gin-1', 'measures', 'Gini Coefficient',
    'Country A and Country B have the same average income, but in A the top tenth receives most of the payroll. A 0-to-1 score records that difference.',
    ['Human Development Index', 'Gender Inequality Index', 'Gross National Income'],
    'How evenly income is spread is the Gini Coefficient. HDI averages health, school, and income. GII is gender. GNI is the size of income, not its distribution.'),
  q('mea-gin-2', 'measures', 'Gini Coefficient',
    'Brazil’s average income rose while a distribution score moved closer to zero because cash transfers lifted the bottom fifth.',
    ['Literacy Rate', 'Purchasing Power Parity', 'Commodity Dependence'],
    'A move toward 0 is a falling Gini Coefficient. Literacy Rate is reading. PPP adjusts prices. Commodity Dependence is export mix.'),
  q('mea-gin-3', 'measures', 'Gini Coefficient',
    'A city can have a high average wage and still be unequal if technology salaries stand beside unregistered settlements. Planners want a statistic that rises when that gap widens.',
    ['Life Expectancy', 'Formal Sector', 'Absolute Location'],
    'Income-distribution inequality is the Gini Coefficient. Life Expectancy could be high for everyone. Formal Sector share is a different slice. Absolute Location is a coordinate.'),
  q('mea-gin-4', 'measures', 'Gini Coefficient',
    'Two countries have the same average income. In one, a few families hold most of the money. A 0-to-1 score is higher in that country.',
    ['Human Development Index', 'Gender Inequality Index', 'Literacy Rate'],
    'That 0–1 inequality scale is the Gini Coefficient. HDI and GII are different composites. Literacy Rate is a percent who can read.'),
  q('mea-gin-5', 'measures', 'Gini Coefficient',
    'Two petroleum-exporting states can have similar income per person and very different gaps between rich and poor.',
    ['Gross National Product', 'Remittances', 'Reference Map'],
    'The gap is the Gini Coefficient. GNP is production size. Remittances are migrant money. A reference map shows location.'),

  q('mea-lif-1', 'measures', 'Life Expectancy',
    'Japan outranks some petroleum-rich states on development tables because a newborn there is projected to live into the 80s.',
    ['Gross National Income', 'Gini Coefficient', 'Literacy Rate'],
    'Years a newborn is expected to live is Life Expectancy. GNI is money. Gini is inequality. Literacy Rate is schooling.'),
  q('mea-lif-2', 'measures', 'Life Expectancy',
    'School enrollment rose, but a disease outbreak meant people were dying much younger, so the country’s health ranking fell.',
    ['Gender Gap', 'Remittances', 'Secondary Sector'],
    'A fall in expected years of life is Life Expectancy. Gender Gap is a male–female difference. Remittances are migrant money. Secondary Sector is manufacturing.'),
  q('mea-lif-3', 'measures', 'Life Expectancy',
    'A wealthy county spends a great deal on hospitals, yet people there die younger than in a poorer county nearby.',
    ['Human Development Index', 'Purchasing Power Parity', 'Quinary Sector'],
    'Years of life is Life Expectancy. HDI blends that with school and income. PPP compares prices. Quinary Sector is elite jobs.'),
  q('mea-lif-4', 'measures', 'Life Expectancy',
    'An oil-rich country has high income, but a newborn there is expected to live only into the 50s. A poorer country where people typically live into the 80s ranks higher on health.',
    ['Literacy Rate', 'Gini Coefficient', 'Formal Sector'],
    'The health piece is Life Expectancy. Literacy Rate is the education idea in older lists. Gini is inequality. Formal Sector is taxed work.'),
  q('mea-lif-5', 'measures', 'Life Expectancy',
    'A data table ranks countries by how many years a newborn is expected to live. Japan sits near the top; some richer oil states sit lower.',
    ['Gross National Product', 'Cartogram', 'Friction of Distance'],
    'Living longer is Life Expectancy. GNP is production. A cartogram resizes area. Friction of Distance is the cost of movement.'),

  q('mea-lit-1', 'measures', 'Literacy Rate',
    'Two regions have similar income. In one, almost every adult can read a newspaper and fill out a job form. In the other, many adults cannot.',
    ['Gini Coefficient', 'Formal Sector', 'Site'],
    'The share who can read and write is Literacy Rate. Gini is income shares. Formal Sector is regulated jobs. Site is physical character.'),
  q('mea-lit-2', 'measures', 'Literacy Rate',
    'A factory in Bangladesh rejects applicants who cannot read a safety card, so districts with more adults who never learned to read remain in casual day labor.',
    ['Life Expectancy', 'Commodity Dependence', 'Relative Location'],
    'Being able to read the card is Literacy Rate. Life Expectancy is years lived. Commodity Dependence is export concentration. Relative Location is position compared with other places.'),
  q('mea-lit-3', 'measures', 'Literacy Rate',
    'Coastal cities have far more adults who can fill out a job form than inland districts of the same country. Income maps do not match that pattern.',
    ['Gross National Product', 'Graduated Symbol Map', 'Friction of Distance'],
    'The ballot-and-form skill is Literacy Rate. GNP is a production total. A graduated symbol map could display the rate but is not the indicator. Friction of Distance is movement cost.'),
  q('mea-lit-4', 'measures', 'Literacy Rate',
    'A government counts how many adults can read and write. One region scores 95 percent; a poorer inland region scores 40 percent.',
    ['Gender Inequality Index', 'Primary Sector', 'Isoline Map'],
    'Percent who can read is Literacy Rate. GII is a gender composite. Primary Sector is extraction. Isolines connect equal values.'),
  q('mea-lit-5', 'measures', 'Literacy Rate',
    'A country builds many factories but most adults still cannot read a ballot or a medicine label. A social development table would rank it lower than income alone suggests.',
    ['Secondary Sector', 'Toponyms', 'World Scale'],
    'The school-outcome percent is Literacy Rate. Secondary Sector is manufacturing. Toponyms are place names. World Scale compares countries.'),

  q('mea-gg-1', 'measures', 'Gender Gap',
    'In several Gulf states, women outnumber men in universities but remain far less likely to hold paid employment or parliamentary seats.',
    ['Gender Inequality Index', 'Life Expectancy', 'Vernacular Region'],
    'A systematic male–female difference is a Gender Gap. Gender Inequality Index is one UN composite of several gaps. Life Expectancy might not differ. A vernacular region is a mental area.'),
  q('mea-gg-2', 'measures', 'Gender Gap',
    'United States girls now complete high school at slightly higher rates than boys in many districts, while women still earn less in the same occupations. Both are male–female differences.',
    ['Human Development Index', 'Formal Sector', 'Pattern'],
    'Any systematic male–female difference is a Gender Gap. HDI is a three-part composite. Formal Sector is legal work. Pattern is a spatial arrangement.'),
  q('mea-gg-3', 'measures', 'Gender Gap',
    'Women grow most of the food in a farming region but hold almost none of the land titles, so they cannot borrow money against a field.',
    ['Gender Inequality Index', 'Possibilism', 'Quaternary Sector'],
    'Unequal land control by sex is a Gender Gap. GII might later summarize several gaps. Possibilism is a human-environment theory. Quaternary Sector is knowledge work.'),
  q('mea-gg-4', 'measures', 'Gender Gap',
    'A map shows that men hold most seats in parliament even though women make up half the population.',
    ['Gender Inequality Index', 'Gini Coefficient', 'Site'],
    'The difference itself is a Gender Gap. GII is the composite index. Gini is income inequality, not gender. Site is physical character.'),
  q('mea-gg-5', 'measures', 'Gender Gap',
    'Girls in one district attend school at the same rate as boys, but almost no women own farmland.',
    ['Formal Region', 'Life Expectancy', 'Remote Sensing'],
    'Unequal landholding by sex is a Gender Gap. A Formal Region is a uniform area. Life Expectancy is years lived. Remote Sensing is satellite data.'),

  q('mea-gii-1', 'measures', 'Gender Inequality Index',
    'The United Nations publishes one 0-to-1 score that gets worse when maternal deaths are high, few women sit in parliament, and fewer women hold paid jobs.',
    ['Human Development Index', 'Gender Gap', 'Gini Coefficient'],
    'That reproductive-health + empowerment + labor composite is the Gender Inequality Index. HDI mixes life expectancy, schooling, and income for everyone. Gender Gap is a looser term for one difference. Gini is income inequality.'),
  q('mea-gii-2', 'measures', 'Gender Inequality Index',
    'Qatar can appear developed on income and schooling yet score poorly on a United Nations gender composite because political representation and labor-force gaps remain wide.',
    ['Human Development Index', 'Gross National Income', 'Literacy Rate'],
    'The gender composite is the Gender Inequality Index. HDI and GNI can still look strong. Literacy Rate is only one education measure.'),
  q('mea-gii-3', 'measures', 'Gender Inequality Index',
    'Rwanda reserved parliamentary seats for women, which improved one United Nations score even while maternal-health challenges remained. This index moves when empowerment, health, and labor inputs change together.',
    ['Gini Coefficient', 'Purchasing Power Parity', 'World Systems Theory'],
    'A composite that includes parliamentary share plus health and labor is the Gender Inequality Index. Gini moves with income shares. PPP is prices. World Systems Theory is not an index.'),
  q('mea-gii-4', 'measures', 'Gender Inequality Index',
    'A wealthy country ranks poorly when maternal deaths are common, few women sit in parliament, and fewer women than men hold paid jobs. A higher score here means a worse result.',
    ['Human Development Index', 'Literacy Rate', 'Choropleth Map'],
    'High = more gender inequality is the Gender Inequality Index. High HDI is good. Literacy Rate is a percent. A choropleth is a map type.'),
  q('mea-gii-5', 'measures', 'Gender Inequality Index',
    'The United Nations combines maternal health, women in parliament, and female job rates into one 0-to-1 score. A country can look rich and still rank poorly on that score.',
    ['Gender Gap', 'Gini Coefficient', 'Formal Sector'],
    'The official composite is the Gender Inequality Index. Gender Gap is the everyday difference. Gini is income. Formal Sector is taxed work.'),

  q('mea-hdi-1', 'measures', 'Human Development Index',
    'A country looks rich from oil exports, but people die young and few finish school. A United Nations ranking that mixes health, education, and income places it well below other high-income states.',
    ['Gender Inequality Index', 'Gini Coefficient', 'Gross National Income'],
    'HDI combines life expectancy, education, and income so oil money alone cannot carry the ranking. GII is gender-specific. Gini is inequality. GNI is the income piece HDI refuses to use by itself.'),
  q('mea-hdi-2', 'measures', 'Human Development Index',
    'Cuba has long ranked closer to much wealthier countries on a United Nations development score than its income would predict, because health and schooling are strong.',
    ['Gross National Product', 'Commodity Dependence', 'Isoline Map'],
    'A composite that can lift a country with good health and school outcomes is the Human Development Index. GNP is only production. Commodity Dependence is export mix. An isoline map is a cartographic form.'),
  q('mea-hdi-3', 'measures', 'Human Development Index',
    'A student says a country is developed because it has factories. A United Nations table ranks another country higher because people live longer and stay in school longer, even with fewer factories.',
    ['Formal Sector', 'Cartographic Scale', 'Quinary Sector'],
    'That three-part UN ranking is the Human Development Index. Formal Sector is legal work. Cartographic Scale is a map ratio. Quinary Sector is elite jobs.'),
  q('mea-hdi-4', 'measures', 'Human Development Index',
    'In a United Nations data table, Switzerland typically ranks among the highest because residents live long, remain in school, and earn high incomes — not because the country has the most factories.',
    ['Gini Coefficient', 'Gender Inequality Index', 'Purchasing Power Parity'],
    'That well-being composite is the Human Development Index. Gini is income shares. GII is gender. PPP is a price adjustment. Switzerland ranks near the top of HDI tables.'),
  q('mea-hdi-5', 'measures', 'Human Development Index',
    'Norway sits near the top of a United Nations table that ranks countries by a mix of long life, years in school, and income, not by factory count alone.',
    ['Primary Sector', 'Dot Distribution Map', 'Friction of Distance'],
    'The UN well-being score is the Human Development Index. Primary Sector is extraction. A dot map is a symbol type. Friction of Distance is movement cost.'),
]
