import { q, type VocabQuestion } from './apHumanVocab'

export const VOCAB_MAP_QUESTIONS: VocabQuestion[] = [
  q(
    'map-phy-1',
    'maps',
    'Physical Geography',
    'A team explaining why the Atacama is dry, why the Ganges floods, and why Iceland has geothermal power is asking about climate, landforms, water, and Earth systems — not about borders, languages, or income. Which branch of geography is that?',
    ['Human Geography', 'Thematic Map', 'Possibilism'],
    'Earth systems, landforms, climate, and water are Physical Geography. Human Geography would ask how people organize those places. A thematic map is a display tool. Possibilism is a theory about human choice within environmental limits.',
  ),
  q(
    'map-phy-2',
    'maps',
    'Physical Geography',
    'Before a port is even proposed, engineers measure tidal range, longshore drift, and bedrock — questions that would still matter if no city existed. Which geographic tradition is asking those questions?',
    ['Human Geography', 'Cultural Landscape', 'Formal Sector'],
    'Tides, sediment, and bedrock are Physical Geography. Human Geography and Cultural Landscape start when people occupy and mark the coast. Formal Sector is an economic category.',
  ),
  q(
    'map-phy-3',
    'maps',
    'Physical Geography',
    'A hurricane paper models sea-surface temperature and wind shear to forecast storm intensity. It is not yet asking who can evacuate or how insurance markets price risk. Which side of the discipline is the model on?',
    ['Human Geography', 'Remote Sensing', 'Quaternary Sector'],
    'The atmosphere-ocean process is Physical Geography. Who evacuates is Human Geography. Remote Sensing might supply the SST data. Quaternary Sector is knowledge employment.',
  ),
  q(
    'map-hum-1',
    'maps',
    'Human Geography',
    'Why Lagos grew, why Hausa and Yoruba politics matter, and why container traffic concentrates at a few West African ports are questions about people, power, and economic networks, not about the chemistry of the Gulf of Guinea. Which branch is that?',
    ['Physical Geography', 'Isoline Map', 'Life Expectancy'],
    'Population, culture, politics, and economic networks are Human Geography. Physical Geography would be the gulf’s currents and climate. An isoline map could display either. Life Expectancy is one social indicator, not the whole branch.',
  ),
  q(
    'map-hum-2',
    'maps',
    'Human Geography',
    'A researcher asks why two towns on the same river have different religions, legal systems, and commuting patterns. The river’s discharge is identical; the difference is how people have organized the valley. Which field is the researcher in?',
    ['Physical Geography', 'Cartographic Scale', 'Primary Sector'],
    'Religion, law, and commuting are Human Geography. Discharge is Physical Geography. Cartographic Scale is a map property. Primary Sector is extraction employment.',
  ),
  q(
    'map-hum-3',
    'maps',
    'Human Geography',
    'AP exam prompts about language families, supranationalism, and megacity slums are testing how societies occupy and rearrange Earth, not the mineralogy of the crust. Which half of geography is that?',
    ['Physical Geography', 'Topographic Map', 'Gini Coefficient'],
    'Those topics are Human Geography. Mineralogy is Physical. A topographic map is a reference tool. Gini is one inequality measure used inside human geography, not the name of the field.',
  ),
  q(
    'map-ref-1',
    'maps',
    'Reference Map',
    'A hiking atlas, a political wall map of African states, and a city street grid are built so a user can find “where is this?” — names, boundaries, and routes — not to argue a rate or a density. Which map class is that?',
    ['Thematic Map', 'Cartogram', 'Choropleth Map'],
    'Maps whose main job is location and navigation are Reference Maps. Thematic maps (including choropleths and cartograms) exist to show a selected data theme.',
  ),
  q(
    'map-ref-2',
    'maps',
    'Reference Map',
    'An emergency crew needs the names of creeks, the county line, and the road to the hospital, not a shading of poverty rates. Which kind of map should be in the truck?',
    ['Thematic Map', 'Dot Distribution Map', 'Graduated Symbol Map'],
    'Names, lines, and roads for finding places are a Reference Map. Poverty shading or dots would be thematic products that do not help the driver turn.',
  ),
  q(
    'map-ref-3',
    'maps',
    'Reference Map',
    'Google’s default basemap shows streets, parks, and labels so you can navigate. Switching on “bike crashes last year” turns it into something else. What was the default product?',
    ['Thematic Map', 'Isoline Map', 'World Scale'],
    'The unlabeled-for-theme basemap is a Reference Map. Bike crashes would be a thematic layer. Isolines are one thematic form. World Scale is a level of analysis.',
  ),
  q(
    'map-thm-1',
    'maps',
    'Thematic Map',
    'A page titled “Percent of adults with a university degree, 2020” is not trying to help you drive to the university; it is trying to show a spatial distribution of one variable. Which map class is that page?',
    ['Reference Map', 'Topographic Map', 'Absolute Location'],
    'A map whose purpose is a data theme is a Thematic Map. A reference or topographic sheet would emphasize location, terrain, and names. Absolute Location is a coordinate, not a map class.',
  ),
  q(
    'map-thm-2',
    'maps',
    'Thematic Map',
    'Election-night graphics that color precincts by winner, ship-track maps of oil spills, and a cartogram of electoral votes all sacrifice some “find my street” detail to show a selected phenomenon. Which class includes all three?',
    ['Reference Map', 'Physical Geography', 'Formal Region'],
    'All three are Thematic Maps: they display a chosen variable or event. A reference map would privilege streets and names. Physical Geography is a field. A formal region might be what the theme is showing.',
  ),
  q(
    'map-thm-3',
    'maps',
    'Thematic Map',
    'A planner already knows where the streets are. She opens a map of childhood asthma rates to decide where to put air monitors. She is using the map as an argument about a variable, not as a gazetteer. Which map class is that?',
    ['Reference Map', 'Site', 'Quinary Sector'],
    'A map of asthma rates is Thematic. A gazetteer-style street sheet is Reference. Site is a place’s physical character. Quinary Sector is elite decision-making.',
  ),
  q(
    'map-cho-1',
    'maps',
    'Choropleth Map',
    'A U.S. map shades each county from light to dark using the percent of households below the poverty line. The unit is an enumeration area, and the variable is a rate, not a raw count of poor people. Which map type is that?',
    ['Dot Distribution Map', 'Graduated Symbol Map', 'Cartogram'],
    'Shaded enumeration units for a ratio or percentage are a Choropleth Map. Dots would show counts as point symbols. Graduated symbols would size a circle by a value. A cartogram would resize the counties themselves.',
  ),
  q(
    'map-cho-2',
    'maps',
    'Choropleth Map',
    'A student maps “number of COVID deaths” by filling each country with a color. Tiny, dense places look “safe” and giant, sparse places look “deadly” because area, not risk, is driving the ink. The student used the wrong variable type for this technique. Which technique was it?',
    ['Isoline Map', 'Reference Map', 'Topographic Map'],
    'Coloring political units is choropleth technique — and it is misleading for raw counts. Isolines would interpolate a continuous surface. Reference and topographic maps are not this shading method.',
  ),
  q(
    'map-cho-3',
    'maps',
    'Choropleth Map',
    'Belgium’s language regions can be shown by coloring each municipality according to its official language regime. The map’s building block is a bounded unit with one class, not a dot for each speaker. Which map type is that?',
    ['Dot Distribution Map', 'Isoline Map', 'Graduated Symbol Map'],
    'One class per official unit is a Choropleth (or chorochromatic) map of a qualitative/formal attribute. Dots would show speakers as points. Isolines need a continuous numeric field. Graduated symbols would size a mark by a quantity.',
  ),
  q(
    'map-dot-1',
    'maps',
    'Dot Distribution Map',
    'A 2020 map places one dot for every 500 dairy cows, so Wisconsin looks speckled and Nevada almost empty. The reader can see clustering inside states, not just one statewide average. Which map type is that?',
    ['Choropleth Map', 'Cartogram', 'Isoline Map'],
    'Repeated point symbols for counts are a Dot Distribution Map. A choropleth would shade whole states. A cartogram would resize states. Isolines would connect equal values on a surface.',
  ),
  q(
    'map-dot-2',
    'maps',
    'Dot Distribution Map',
    'To show where hate-crime incidents occurred, an analyst plots each event as a point instead of coloring whole counties, because a county average would hide whether incidents sat on one street. Which map type preserves those locations?',
    ['Choropleth Map', 'Graduated Symbol Map', 'Small-Scale Maps'],
    'One mark per event (or per n events) is a Dot Distribution Map. Choropleth averages the county. A graduated symbol would usually be one sized mark per unit. Small-scale maps are about zoom level, not the symbol system.',
  ),
  q(
    'map-dot-3',
    'maps',
    'Dot Distribution Map',
    'A population map of Egypt puts thousands of tiny marks along the Nile and almost none in the Western Desert, revealing a linear cluster that a single national density shade would erase. Which technique creates that visual?',
    ['Choropleth Map', 'Cartogram', 'Reference Map'],
    'The speckled Nile is a Dot Distribution (or dot-density) pattern. A national choropleth would be one color for Egypt. A cartogram would balloon the country by population. A reference map would emphasize names and borders.',
  ),
  q(
    'map-grd-1',
    'maps',
    'Graduated Symbol Map',
    'Each city on a trade map has a circle whose area is proportional to container throughput. Shanghai’s circle is huge; a small Baltic port is a pinhead. The city’s legal boundary is not shaded. Which map type is that?',
    ['Choropleth Map', 'Dot Distribution Map', 'Isoline Map'],
    'One symbol sized by a quantity is a Graduated (or proportional) Symbol Map. Choropleth shades the whole unit. Dots repeat same-size marks. Isolines contour a surface.',
  ),
  q(
    'map-grd-2',
    'maps',
    'Graduated Symbol Map',
    'A newspaper shows earthquake magnitude with larger squares for stronger events and smaller squares for weaker ones, all at the epicenter points. Magnitude is a value at a location, not a county percentage. Which map type is that?',
    ['Choropleth Map', 'Cartogram', 'Topographic Map'],
    'Sized point symbols for a magnitude are Graduated Symbols. Choropleth needs areal units. A cartogram resizes areas. A topographic map shows terrain with contours or shading.',
  ),
  q(
    'map-grd-3',
    'maps',
    'Graduated Symbol Map',
    'To compare airport passenger totals, an atlas draws one disk per airport instead of coloring whole countries, because a country shade would hide that Atlanta outranks many national systems. Which technique is the atlas using?',
    ['Choropleth Map', 'Isoline Map', 'Field Observations'],
    'One sized disk per airport is a Graduated Symbol Map. Country coloring would be choropleth. Isolines would imply a continuous passenger “surface.” Field Observations are a data method, not a symbol system.',
  ),
  q(
    'map-iso-1',
    'maps',
    'Isoline Map',
    'A weather chart draws lines through all points with the same barometric pressure, creating closed loops around a low. The variable is treated as a continuous field, not as one value per county. Which map type is that?',
    ['Choropleth Map', 'Dot Distribution Map', 'Cartogram'],
    'Lines of equal value are an Isoline Map (isobars here). Choropleth would fill counties. Dots would mark stations. A cartogram would resize areas.',
  ),
  q(
    'map-iso-2',
    'maps',
    'Isoline Map',
    'A travel-time map around Tokyo draws nested curves for “30 minutes,” “60 minutes,” and “90 minutes” from a station. The lines are interpolated between measured points. Which map type is that?',
    ['Graduated Symbol Map', 'Reference Map', 'Formal Region'],
    'Equal-travel-time curves are isochrones — a type of Isoline Map. Graduated symbols would size stations. A reference map would show tracks and names. A formal region would be an official zone, not an interpolated time surface.',
  ),
  q(
    'map-iso-3',
    'maps',
    'Isoline Map',
    'A frost-date atlas connects places that share the same average last-freeze day, so a farmer sees a wave of lines across the Midwest rather than one color per state. Which technique produced those lines?',
    ['Choropleth Map', 'Dot Distribution Map', 'Thematic Map'],
    'Connecting equal frost dates is isoline mapping. “Thematic Map” is the broader class; the distinctive technique is isolines. Choropleth would fill states. Dots would mark stations without connecting them.',
  ),
  q(
    'map-topo-1',
    'maps',
    'Topographic Map',
    'A USGS 7.5-minute quadrangle shows contour lines, spot elevations, streams, and a few buildings so an engineer can read slope and drainage, not poverty or election results. Which map type is that sheet?',
    ['Choropleth Map', 'Cartogram', 'Thematic Map'],
    'A contour-based terrain-and-features sheet is a Topographic Map — a specialized reference product. Choropleths and cartograms are thematic. Calling it only “thematic” misses that its job is terrain location, not a socioeconomic variable.',
  ),
  q(
    'map-topo-2',
    'maps',
    'Topographic Map',
    'Hikers choose a map because tightly packed brown lines tell them a ridge is steep, and the blue lines tell them where water sits, even if no census variable is shown. Which map type are they reading?',
    ['Isoline Map', 'Reference Map', 'Graduated Symbol Map'],
    'The combination of contours plus planimetric features for terrain reading is a Topographic Map. Contours are isolines, but “isoline map” alone would also describe a weather chart without the full topo symbol set. Graduated symbols would size towns, not show slope.',
  ),
  q(
    'map-topo-3',
    'maps',
    'Topographic Map',
    'A dam siting team rejects a colorful income map and asks for a sheet that shows 20-foot contours, floodplain, and existing roads together. They need the shape of the land. Which map type is that request?',
    ['Choropleth Map', 'Dot Distribution Map', 'World Scale'],
    'Contours + hydrography + culture for engineering is a Topographic Map. Income color is choropleth. Dots would not give slope. World Scale is a level of analysis.',
  ),
  q(
    'map-car-1',
    'maps',
    'Cartogram',
    'On an election graphic, Rhode Island becomes huge and Montana nearly vanishes because each state’s area was reset to equal its electoral votes, not its land. Which map type is that?',
    ['Choropleth Map', 'Graduated Symbol Map', 'Small-Scale Maps'],
    'Resizing enumeration units by a data value is a Cartogram. A choropleth would keep land area and change color. Graduated symbols would keep the base map and size a mark. Small-scale just means a zoomed-out map.',
  ),
  q(
    'map-car-2',
    'maps',
    'Cartogram',
    'A world population map inflates India and Nigeria and shrinks Canada and Russia so that equal ink means equal people. The continents are still recognizable but badly warped. Which technique did that?',
    ['Choropleth Map', 'Dot Distribution Map', 'Reference Map'],
    'Warping area to match a variable is a Cartogram. Choropleth keeps geographic area. Dots keep area and add marks. A reference map would try to keep shapes for location.',
  ),
  q(
    'map-car-3',
    'maps',
    'Cartogram',
    'To fight the visual lie that “empty” Australia is as important as Java in a GHG debate, a researcher redraws countries so area equals emissions. Which map type is the researcher building?',
    ['Isoline Map', 'Topographic Map', 'Absolute Location'],
    'Area equal to emissions is a Cartogram. Isolines would contour an emissions surface. Topographic maps show terrain. Absolute Location is a coordinate.',
  ),
  q(
    'map-csc-1',
    'maps',
    'Cartographic Scale',
    'One map states “1:24,000” and another “1:1,000,000.” Those fractions tell you how many ground units one map unit represents, which decides whether a building can even be drawn. Which property is being stated?',
    ['Small-Scale Maps', 'Absolute Location', 'Pattern'],
    'The representative fraction is Cartographic Scale. “Small-scale” is one end of that property, not the property itself. Absolute Location is a position. Pattern is an arrangement of features.',
  ),
  q(
    'map-csc-2',
    'maps',
    'Cartographic Scale',
    'A planner cannot measure a proposed bike-lane width on a wall map of the whole United States because the map-to-Earth ratio is too coarse, even though the wall map is physically large. The problem is the ratio, not the paper size. Which concept is that?',
    ['Relative Location', 'Thematic Map', 'Regional Scale'],
    'The map-to-Earth ratio is Cartographic Scale — independent of how big the poster is. Relative Location is position versus other places. Thematic Map is purpose. Regional Scale is a social/analytic zoom, related but not the representative fraction.',
  ),
  q(
    'map-csc-3',
    'maps',
    'Cartographic Scale',
    'Switching a GIS view from 1:10,000 to 1:250,000 does not just “zoom out”; it changes what symbols are even allowed, because one centimeter now stands for a much longer stretch of Earth. Which map property changed?',
    ['Remote Sensing', 'Sense of Place', 'Formal Region'],
    'Changing the representative fraction is a change in Cartographic Scale. Remote Sensing is data collection. Sense of Place is meaning. A formal region is a type of area.',
  ),
  q(
    'map-ssm-1',
    'maps',
    'Small-Scale Maps',
    'A 1:30,000,000 world wall map can show ocean currents and country outlines but cannot show a village street. Students often call it “large” because the paper is big, but in cartography the fraction is small and the area covered is huge. Which map category is that wall map?',
    ['Topographic Map', 'Large-scale map', 'Reference Map'],
    'A tiny representative fraction covering a huge area is a Small-Scale Map. A large-scale map (e.g., 1:10,000) shows a small area in detail. It may also be a reference map, but the trick being tested is the small-scale / large-area relationship.',
  ),
  q(
    'map-ssm-2',
    'maps',
    'Small-Scale Maps',
    'To compare monsoon systems across South Asia, a researcher must accept less street-level detail so the whole peninsula fits in one frame. The resulting sheet is the opposite of a city engineering plat. Which cartographic category is the monsoon sheet?',
    ['Topographic Map', 'Dot Distribution Map', 'Local Scale'],
    'A highly generalized, large-area sheet is a Small-Scale Map. A topo plat is typically large-scale. Dots are a symbol type. Local Scale is a social zoom that would usually need a large-scale map.',
  ),
  q(
    'map-ssm-3',
    'maps',
    'Small-Scale Maps',
    'Airline route maps of the whole Earth hide most cities and smooth coastlines because the cartographer chose a tiny representative fraction. Which map class is defined by that choice?',
    ['Choropleth Map', 'Cartogram', 'Field Observations'],
    'Tiny RF + huge area + heavy generalization = Small-Scale Maps. Choropleth and cartogram are thematic techniques that can appear at any scale. Field Observations are not a map class.',
  ),
  q(
    'map-abs-1',
    'maps',
    'Absolute Location',
    'A search-and-rescue ping is issued as 27.9881° N, 86.9250° E — a unique coordinate — rather than “on the Nepal side of the high Himalaya.” Which kind of location is the ping using?',
    ['Relative Location', 'Situation', 'Sense of Place'],
    'A coordinate (or address) that does not depend on other places is Absolute Location. “Nepal side of the Himalaya” is relative. Situation is a place’s connections. Sense of Place is meaning.',
  ),
  q(
    'map-abs-2',
    'maps',
    'Absolute Location',
    'A cadastral survey records a parcel as a measured township-range-section so a court can find the same plot after every nearby road is renamed. Which locational idea makes that permanence possible?',
    ['Relative Location', 'Toponyms', 'Vernacular Region'],
    'A surveyed grid that stays put when names change is Absolute Location. Relative Location would fail when the roads are renamed. Toponyms are the names. A vernacular region is a mental area.',
  ),
  q(
    'map-abs-3',
    'maps',
    'Absolute Location',
    'Aircraft transponders report a constantly updating latitude and longitude so two planes cannot “both be near Chicago” in a way that still lets them collide. Which locational concept is the transponder using?',
    ['Relative Location', 'Pattern', 'Cultural Landscape'],
    'Latitude/longitude is Absolute Location. “Near Chicago” is relative and too vague for separation. Pattern is arrangement. Cultural Landscape is the visible human imprint.',
  ),
  q(
    'map-rel-1',
    'maps',
    'Relative Location',
    'Singapore’s advantage is often stated as “at the outlet of the Strait of Malacca between the Indian and Pacific trades,” not as 1.35° N, 103.82° E. The useful fact is position compared with routes and neighbors. Which locational concept is that?',
    ['Absolute Location', 'Site', 'Cartographic Scale'],
    'Position described versus other places and routes is Relative Location (closely related to situation). The coordinate would be absolute. Site would be Singapore’s own harbor depths and land. Cartographic Scale is a map ratio.',
  ),
  q(
    'map-rel-2',
    'maps',
    'Relative Location',
    'A realtor says a house is “15 minutes from downtown and across from the magnet school.” Those phrases can stay true even if the GPS pin is never mentioned. Which locational idea is the realtor selling?',
    ['Absolute Location', 'Isoline Map', 'Primary Sector'],
    'Time and neighbor landmarks are Relative Location. The GPS pin would be absolute. An isoline map might show the 15-minute band. Primary Sector is unrelated employment.',
  ),
  q(
    'map-rel-3',
    'maps',
    'Relative Location',
    'After a new high-speed rail line, a town that did not move an inch is suddenly “closer” to the capital in travel time, and firms relocate there. Coordinates were unchanged. Which concept did the rail line alter?',
    ['Absolute Location', 'Site', 'Dot Distribution Map'],
    'Travel-time nearness is Relative Location. Absolute Location and the physical site did not change. A dot map might later show the new firms, but the concept that changed is relative position.',
  ),
]
