import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'membrane' as const

export const MEMBRANE_QUESTIONS: BioPracticeQuestion[] = [
  mc('m1', T, 'The plasma membrane is called a "fluid mosaic" because', [
    'it is a rigid, unchanging crystal lattice of one lipid',
    'its parts can drift, and many kinds of molecules make it up',
    'it is built from a single repeating molecule with no variation',
    'cholesterol welds every phospholipid permanently in place',
  ], 1, '"Fluid" = components can drift. "Mosaic" = many different molecules piece the sheet together.', 'fluid-mosaic'),
  mc('m2', T, 'A phospholipid is amphipathic, meaning it has', [
    'two hydrophilic tails and a hydrophobic head',
    'both a polar head and nonpolar tails',
    'no charge anywhere on the molecule',
    'the same four-ring shape as cholesterol',
  ], 1, 'Amphipathic = both water-loving and water-fearing regions in one molecule.', 'bilayer'),
  mc('m3', T, 'Phospholipids form a bilayer with heads out and tails in mainly because', [
    'the tails are pulled toward water on both sides',
    'polar heads bond with water while nonpolar tails avoid it',
    'cholesterol pushes the tails to the surface',
    'the heads are repelled by the surrounding fluid',
  ], 1, 'Water surrounds both membrane surfaces, so heads face out while tails cluster away from it.', 'bilayer'),
  mc('m4', T, 'A membrane rich in unsaturated fatty acid tails, versus one rich in saturated tails at the same temperature, will be', [
    'stiffer, since kinks slow lateral movement',
    'more fluid, since kinks block tight packing',
    'equally fluid either way',
    'gradually turned into a rigid wall',
  ], 1, 'Double-bond kinks prevent unsaturated tails from packing tightly, keeping the bilayer fluid.'),
  mc('m5', T, 'Cholesterol acts as a membrane buffer because it', [
    'only ever raises fluidity and does nothing else at all',
    'limits movement in the heat and blocks tight packing in the cold',
    'has no measurable effect on the bilayer whatsoever',
    'fully replaces the phospholipids near body temperature',
  ], 1, 'Cholesterol moderates fluidity both ways: less runny when warm, less stiff when cold.', 'fluid-mosaic'),
  mc('m6', T, 'A cell that made zero cholesterol would most likely show which change in cold weather?', [
    'Unusually high fluidity',
    'Unusually tight packing and rigidity',
    'No noticeable change at all',
    'A sudden switch to a cellulose wall',
  ], 1, 'Without cholesterol wedged among the tails, phospholipids pack closer together than normal in the cold.'),
  mc('m7', T, 'An integral protein differs from a peripheral protein in that an integral protein', [
    'spans the whole bilayer instead of sitting on one face',
    'is made only of carbohydrate rather than protein',
    'never takes part in any kind of transport at all',
    'is found only in prokaryotic membranes, never eukaryotic',
  ], 0, 'Integral proteins cross from head to head; peripheral proteins attach to just one surface.'),
  mc('m8', T, 'A channel protein moves a solute by providing', [
    'a continuous pore to pass through',
    'a shape change that carries the cargo',
    'a pump cycle powered by ATP',
    'a sugar tag the solute must bind first',
  ], 0, 'Channel = pore. A carrier, by contrast, changes shape to move its cargo.', 'channel-carrier'),
  mc('m9', T, 'A carrier protein moves its solute by', [
    'staying open like a rigid tunnel',
    'changing shape to ferry the solute across',
    'spending ATP no matter the direction',
    'binding hormones and nothing else',
  ], 1, 'Carrier proteins change conformation to move cargo; channels provide an open pore instead.', 'channel-carrier'),
  mc('m10', T, 'A membrane receptor protein lets a cell', [
    'bind a specific hormone and trigger a response',
    'anchor the cytoskeleton to the matrix',
    'pump ions uphill using ATP',
    'let water cross without any pore',
  ], 0, 'Receptors recognize and bind a ligand whose shape matches the binding site.'),
  mc('m11', T, 'TRACIE stands for transport, receptors, anchorage, cell recognition, intercellular joining, and enzyme activity. Which pairing below is wrong?', [
    'Transport — channels and pumps move substances across',
    'Anchorage — proteins attach the membrane to the cytoskeleton',
    'Intercellular joining — proteins turn light into ATP',
    'Enzyme activity — some proteins speed up reactions',
  ], 2, 'Intercellular joining means junctions linking neighboring cells, not light-driven energy conversion.'),
  mc('m12', T, 'Tight junctions binding neighboring cells together fall under which TRACIE category?', [
    'Enzyme activity',
    'Receptor binding',
    'Intercellular joining',
    'Passive transport',
  ], 2, 'Interlocking proteins that hold adjacent cells together are intercellular joining.'),
  mc('m13', T, 'Two cells identify each other as "self" instead of triggering an immune response. This depends mainly on', [
    'cholesterol buried in the core',
    'sugar chains displayed on the surface',
    'phosphate heads on the inner leaflet',
    'integral proteins that only move ions',
  ], 1, 'Carbohydrate chains on lipids or proteins act as identity tags the immune system reads.'),
  mc('m14', T, 'A glycolipid and a glycoprotein both carry a sugar chain. The only real difference is', [
    'whether the chain sits on a lipid or a protein',
    'that one is only found in plants',
    'that glycoproteins play no role in recognition',
    'that a glycolipid is just another name for cholesterol',
  ], 0, '"Glyco-" signals a carbohydrate attachment. What differs is only what it attaches to.'),
  mc('m15', T, 'Selective permeability means the membrane', [
    'lets every molecule cross at one identical rate',
    'lets some substances cross more easily than others',
    'never lets anything cross without a vesicle',
    'only ever lets water through',
  ], 1, 'Size, polarity, and charge decide which substances cross the hydrophobic core easily.'),
  mc('m16', T, 'Rank these from fastest to slowest straight through the bilayer, unaided: a Cl⁻ ion, an O₂ molecule, a glucose molecule.', [
    'Cl⁻, then O₂, then glucose',
    'O₂, then glucose, then Cl⁻',
    'Glucose, then Cl⁻, then O₂',
    'All three cross equally fast',
  ], 1, 'Small nonpolar O₂ crosses fastest; glucose is slower; charged Cl⁻ is blocked almost entirely.'),
  mc('m17', T, 'A drug that is small, uncharged, and strongly nonpolar would most likely', [
    'need a specific carrier protein',
    'diffuse straight through the bilayer unaided',
    'be blocked by the polar head groups',
    'enter only by receptor-mediated endocytosis',
  ], 1, 'Nonpolar, lipid-soluble molecules move through the hydrophobic core with no protein help.'),
  mc('m18', T, 'A fully charged potassium ion cannot simply diffuse through the bilayer mainly because', [
    'K⁺ is too small to interact with the membrane',
    'the nonpolar core repels its charge',
    'K⁺ only exists as a gas at body temperature',
    'the membrane lacks phosphate heads',
  ], 1, 'Charged particles are strongly repelled by the nonpolar core, so ions need a channel or pump.'),
  mc('m19', T, 'If every integral protein vanished but the bilayer and cholesterol stayed intact, the first function lost would be', [
    'the bilayer\'s separation of cytoplasm from the outside',
    'transport of glucose and ions that cannot cross the core alone',
    'the hydrophobic character of the tails themselves',
    'the amphipathic nature of the phospholipid molecules',
  ], 1, 'Without channel and carrier proteins, protein-dependent solutes could no longer cross, though the barrier remains.'),
  mc('m20', T, 'Which of the following is NOT a job of the plasma membrane in this unit?', [
    'Acting as a selective barrier',
    'Anchoring the cytoskeleton',
    'Turning light energy into glucose',
    'Providing binding sites for enzymes',
  ], 2, 'Turning light into glucose is photosynthesis, a chloroplast job, not a membrane function.'),
  mc('m21', T, 'Cellular homeostasis depends most directly on the membrane\'s ability to', [
    'produce ATP through respiration',
    'regulate what enters and exits',
    'store genetic information',
    'replicate DNA before division',
  ], 1, 'Controlling traffic in and out keeps internal conditions stable.'),
  mc('m22', T, 'Which is the accurate statement about which cells have a plasma membrane?', [
    'Only eukaryotes have one',
    'All cells have one, wall or no wall',
    'Only wall-free cells have one',
    'Only plants and fungi have one',
  ], 1, 'A wall, when present, sits outside the membrane and never replaces it.'),
  mc('m23', T, 'By mass, a typical plasma membrane is mostly made of', [
    'nucleic acids and carbohydrates',
    'lipids and proteins',
    'carbohydrates alone',
    'peptidoglycan and cellulose',
  ], 1, 'The bilayer is lipid, studded with proteins; carbohydrates are a smaller add-on.'),
  mc('m24', T, 'In a membrane diagram, a visible bend partway down one fatty acid tail most likely marks', [
    'a peptide bond',
    'a double bond in an unsaturated tail',
    'a hydrogen bond between water molecules',
    'a glycosidic linkage between sugars',
  ], 1, 'A kink in a tail is the visual mark of a C=C double bond.', 'phospholipid'),
  mc('m25', T, 'Four fused carbon rings sitting among the tails in a cross-section represent', [
    'a channel protein',
    'cholesterol',
    'a triglyceride',
    'an oligosaccharide chain',
  ], 1, 'Cholesterol is a steroid, four fused rings inserted among the fatty acid tails.', 'steroid'),
  multi('m26', T, 'Select ALL reasons the membrane is selectively permeable rather than fully open or fully sealed.', [
    'The hydrophobic core blocks polar and charged solutes',
    'Transport proteins give regulated paths for solutes that cannot cross alone',
    'Every solute crosses at an identical rate no matter its size or charge',
    'A lipid barrier plus specific proteins let the cell fine-tune what crosses',
  ], [0, 1, 3], 'Selective permeability comes from a lipid barrier blocking some things while proteins let others through, not from uniform permeability.'),
  mc('m27', T, 'A protein that speeds water across the membrane tenfold, using no ATP, is best classified as', [
    'a sodium-potassium pump',
    'an aquaporin',
    'a receptor protein',
    'a peripheral protein',
  ], 1, 'Aquaporins speed water movement, but water still moves down its own gradient at no energy cost, so this stays passive.'),
  mc('m28', T, 'Peripheral proteins typically handle a different role than most integral proteins because peripheral proteins commonly do', [
    'surface recognition rather than transport',
    'ion pumping, which integral proteins never do',
    'exactly the same job as integral proteins',
    'nothing, since they bind nothing at all',
  ], 0, 'Sitting on one surface, peripheral proteins often serve recognition roles, while many integral proteins carry out transport.'),
  mc('m29', T, 'A protein spanning the membrane changes shape to shuttle amino acids in, down their gradient. This is a', [
    'peripheral recognition protein',
    'carrier protein doing facilitated diffusion',
    'channel protein doing simple diffusion',
    'phospholipid doing osmosis',
  ], 1, 'A shape-changing integral protein moving a solute downhill, with no ATP, is a carrier in facilitated diffusion.', 'channel-carrier'),
  mc('m30', T, 'A student claims facilitated diffusion must need ATP since it uses a protein. The flaw is that', [
    'the student\'s claim is actually entirely correct',
    'a protein helper is not the same as an energy source',
    'facilitated diffusion never actually uses any protein',
    'active transport never involves a protein either',
  ], 1, 'ATP use depends on direction relative to the gradient, not on whether a protein is involved.'),
  mc('m31', T, 'A large, folded, hydrophilic protein like insulin cannot simply diffuse out of a cell because it is', [
    'a small gas molecule',
    'too large and polar for the hydrophobic core',
    'a steroid hormone',
    'built the same way as cholesterol',
  ], 1, 'Large hydrophilic molecules cannot cross the nonpolar interior, which is one reason cells use exocytosis instead.'),
  mc('m32', T, 'A membrane engineered with much longer tails, but no change in saturation, would most likely be', [
    'more fluid, since long tails move freely',
    'less fluid, since long tails pack more tightly',
    'unchanged, since tail length does not matter',
    'converted into a rigid cell wall',
  ], 1, 'Longer chains give neighboring tails more surface area to interact with, tightening the packing.'),
  mc('m33', T, 'Would a bacterial membrane and an animal cell membrane both show selective permeability based on size, charge, and polarity?', [
    'No, only eukaryotic membranes are selective',
    'Yes, every bilayer follows the same physical rules',
    'No, only prokaryotic membranes are selective',
    'Only membranes built in a lab show this',
  ], 1, 'Every cell is bounded by a bilayer that follows the same size/charge/polarity rules.'),
  mc('m34', T, '"Fluid mosaic" beats "rigid wall" as a description of the membrane because it captures', [
    'movement of parts plus a mix of different molecules',
    'proteins that are permanently fixed in place',
    'a membrane built from one repeating substance',
    'a model proposed before phospholipids were known',
  ], 0, 'The term captures two ideas at once: fluidity and a mosaic of different lipids, proteins, and carbohydrates.', 'fluid-mosaic'),
]
