import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const H = 'history' as const
const E = 'prok-euk' as const
const P = 'plant-animal' as const
const S = 'surfaces' as const

export const HISTORY_QUESTIONS: BioPracticeQuestion[] = [
  mc('h1', H, 'In 1665, Robert Hooke examined thin slices of cork under a primitive microscope and observed small, box-like compartments. His major historical contribution was that he', [
    'proved that all cells arise from pre-existing cells',
    'coined the term "cells" for the compartments he observed, though they were actually the walls of dead plant cells',
    'discovered that all plants are made of cells',
    'was the first person to observe a living, moving microorganism',
  ], 1, 'Hooke gave the structure its name based on the boxy chambers resembling monastery cells, but the material he viewed was dead cork tissue, not living cells, and he did not formulate the rest of cell theory.'),
  mc('h2', H, 'Antonie van Leeuwenhoek is historically significant mainly because he', [
    'proposed the three parts of cell theory',
    'built improved lenses and was the first to observe living microorganisms, which he called "animalcules"',
    'discovered that cells only come from other cells',
    'proposed that all animals are made of cells',
  ], 1, 'His refined lenses let him observe living, moving microbes for the first time — a major advance beyond Hooke\'s static dead tissue.'),
  mc('h3', H, 'Which scientist is correctly matched with his contribution?', [
    'Matthias Schleiden — all animals are made of cells',
    'Theodor Schwann — all plants are made of cells',
    'Matthias Schleiden — all plants are made of cells',
    'Rudolf Virchow — all plants are made of cells',
  ], 2, 'Schleiden studied plant tissue and concluded all plants are made of cells; Schwann independently reached the same conclusion for animals.'),
  mc('h4', H, 'Rudolf Virchow\'s specific contribution to cell theory was the idea that', [
    'living things can spontaneously generate from non-living matter',
    'all cells arise only from other, pre-existing cells',
    'all plants are made of cells',
    'microorganisms exist and can be observed with lenses',
  ], 1, 'Virchow\'s principle directly rejected spontaneous generation at the cellular level: cells reproduce to make more cells.'),
  mc('h5', H, 'Which combination of scientists\' work most completely underlies the modern statement "all living things are composed of cells"?', [
    'Hooke alone',
    'Leeuwenhoek alone',
    'The combined observations of Hooke (naming cells), Leeuwenhoek (microorganisms), Schleiden (plants), and Schwann (animals)',
    'Virchow alone, since he came last chronologically',
  ], 2, 'No single scientist established the universality of cells; it emerged from combining observations across plant tissue, animal tissue, and microorganisms over roughly two centuries.'),
  mc('h6', H, 'The three parts of modern cell theory are', [
    'all cells have chloroplasts; all cells have walls; all cells are prokaryotic',
    'all living things are made of cells; the cell is the basic unit of life; all cells come from pre-existing cells',
    'only plants and animals are made of cells; bacteria are excluded; viruses are included',
    'cells appear spontaneously; cells never divide; cells lack genetic material',
  ], 1, 'These three statements together define cell theory as taught in this unit, and all three must be memorized precisely.'),
  mc('h7', H, 'Saying "the cell is the basic unit of life" means that', [
    'atoms are larger and more fundamental than cells',
    'the cell is the smallest unit that can independently carry out all the functions necessary for life',
    'organs can exist and function without being composed of cells',
    'only single-celled organisms are considered truly alive',
  ], 1, 'Tissues, organs, and organ systems are built from cells; the cell itself is the smallest unit capable of independently performing life\'s processes.'),
  mc('h8', H, 'A biologist observes a new bacterial cell forming immediately after an existing bacterial cell divides in two. This observation is most directly consistent with which tenet of cell theory?', [
    '"All living things are made of cells"',
    '"The cell is the basic unit of life"',
    '"All cells come from pre-existing cells"',
    'None of cell theory applies to bacteria',
  ], 2, 'A new cell arising directly from division of an existing cell is precisely what Virchow\'s "cells from cells" principle describes — and it applies to all cells, prokaryotic or eukaryotic.'),
  mc('h9', H, 'Why does cell theory NOT classify a virus as a living cell, even though a virus contains genetic material?', [
    'Because cell theory has no rules about genetic material',
    'Because cell theory concerns cells specifically, and a virus lacks the cellular structure (cytoplasm, ribosomes, its own metabolism) required to be classified as a cell',
    'Because viruses are too large to be considered cells',
    'Because cell theory was written after viruses were discovered and deliberately excludes them',
  ], 1, 'Cell theory is about cells as self-sufficient units of life. A virus, lacking cytoplasm, ribosomes, and independent metabolism, does not meet the structural bar to be classified as a cell.'),
  mc('h10', H, 'If a historian wanted to credit the single scientist who FIRST gave a name to the structures now called "cells," the correct answer is', [
    'Virchow',
    'Hooke',
    'Schwann',
    'Leeuwenhoek',
  ], 1, 'Hooke coined the term "cells" in 1665, well before the rest of cell theory was formulated by later scientists.'),
  mc('h11', H, 'A common error is assuming that any one historical scientist single-handedly proved all three parts of cell theory. Why is this incorrect?', [
    'It is not incorrect — Hooke proved all three parts alone',
    'Cell theory was built up gradually, with different scientists (Hooke, Leeuwenhoek, Schleiden, Schwann, Virchow) each contributing a separate piece over roughly two centuries',
    'Cell theory was proposed all at once by a single vote of scientists',
    'None of the historical scientists contributed anything to cell theory',
  ], 1, 'This unit emphasizes that cell theory is a synthesis of multiple scientists\' work spread out over time, not one person\'s discovery.'),
  mc('h12', H, 'Which statement about Hooke\'s original observation is most accurate?', [
    'He observed living, dividing plant cells actively growing',
    'He observed the empty cell walls of dead cork tissue, which is why the "cells" he saw appeared as hollow boxes',
    'He observed bacteria swimming in pond water',
    'He used an electron microscope to see individual organelles',
  ], 1, 'Cork is dead plant tissue (bark), so what Hooke actually saw were the leftover cell walls, not living, functioning cells.'),
  multi('h13', H, 'Select ALL statements that are part of the three tenets of cell theory.', [
    'All living things are made of cells',
    'The cell is the basic unit of life',
    'All cells come from pre-existing cells',
    'All cells must be eukaryotic',
  ], [0, 1, 2], 'Cell theory applies to prokaryotic and eukaryotic cells alike; there is no requirement that cells be eukaryotic.'),
  mc('h14', H, 'Leeuwenhoek\'s term "animalcules" specifically referred to', [
    'dead plant cell walls in cork',
    'the microorganisms he observed swimming in water samples',
    'the three parts of cell theory',
    'a type of virus particle',
  ], 1, '"Little animals" was his description for the moving microorganisms he was the first to observe.'),
  mc('h15', H, 'Cell theory\'s claim that all living things are made of cells applies to which of the following groups?', [
    'Animals and plants only',
    'Animals, plants, fungi, protists, and bacteria/archaea — all cellular life',
    'Only organisms visible without a microscope',
    'Only organisms discovered before 1900',
  ], 1, 'Cell theory is universal across all domains of cellular life, including single-celled prokaryotes, not just the plants and animals originally studied by Schleiden and Schwann.'),
]

export const PROK_EUK_QUESTIONS: BioPracticeQuestion[] = [
  mc('e1', E, 'Eukaryotic organisms include which of the following groups?', [
    'Bacteria and archaea only',
    'Plants, animals, fungi, and protists',
    'Only multicellular organisms',
    'Viruses and bacteria',
  ], 1, '"Eu" (true) + "karyon" (nucleus) — any organism whose cells have a true, membrane-bound nucleus is eukaryotic, spanning these four kingdoms/groups.'),
  mc('e2', E, 'Prokaryotic organisms, as covered in this unit, include', [
    'plants and fungi',
    'bacteria and archaea',
    'protists only',
    'all single-celled eukaryotes',
  ], 1, 'Bacteria and archaea both lack a true nucleus and are classified as prokaryotes.'),
  multi('e3', E, 'Select ALL structures/features found in every cell, whether prokaryotic or eukaryotic.', [
    'Cytoplasm',
    'Ribosomes',
    'A plasma membrane',
    'A true, membrane-bound nucleus',
  ], [0, 1, 2], 'A true nucleus is exclusive to eukaryotic cells. All cells share cytoplasm, ribosomes, a plasma membrane, and genetic material (DNA or RNA).'),
  mc('e4', E, 'Ribosomes are correctly described as', [
    'membrane-bound organelles present only in eukaryotes',
    'protein-synthesizing structures found in all cells that are not classified as membrane-bound organelles',
    'structures found only in prokaryotic cells',
    'the site of photosynthesis in plant cells',
  ], 1, 'Ribosomes make proteins in both prokaryotes and eukaryotes, and this unit specifically distinguishes them from "organelles" since they lack a surrounding membrane.'),
  mc('e5', E, 'A key reason prokaryotes are classified as structurally simpler than eukaryotes is that prokaryotes lack', [
    'a plasma membrane',
    'a nucleus and membrane-bound organelles',
    'ribosomes',
    'any genetic material',
  ], 1, 'Prokaryotes still have all four universal cell components, but they lack the internal compartmentalization (nucleus, membrane-bound organelles) that defines eukaryotic complexity.'),
  mc('e6', E, 'A region of a bacterial cell containing a single circular strand of DNA, not enclosed by a membrane, is called the', [
    'nucleus',
    'nucleoid',
    'nucleolus',
    'capsid',
  ], 1, 'The nucleoid is a defined region, not a membrane-bound compartment — that distinction is exactly why prokaryotes are said to lack a "true" nucleus.', 'prok-cell'),
  mc('e7', E, 'Bacterial cell walls, which lie outside the plasma membrane, are made primarily of', [
    'cellulose',
    'chitin',
    'peptidoglycan',
    'cholesterol',
  ], 2, 'Peptidoglycan is specific to bacterial cell walls, distinct from the cellulose of plants and chitin of fungi.'),
  mc('e8', E, 'Comparing ribosome types, which statement is accurate?', [
    'Prokaryotes have larger (80S) ribosomes; eukaryotes have smaller (70S) ribosomes',
    'Prokaryotes have smaller (70S) ribosomes; eukaryotes have larger (80S) ribosomes',
    'Both domains have identical ribosome sizes',
    'Only eukaryotes have ribosomes at all',
  ], 1, 'This size difference (70S vs. 80S) is a classic distinguishing feature tested at the honors/AP level and is even exploited by some antibiotics that target only 70S ribosomes.'),
  mc('e9', E, 'Prokaryotic cells reproduce by', [
    'mitosis, using a spindle apparatus',
    'binary fission, a simpler division process without a mitotic spindle',
    'meiosis exclusively',
    'exocytosis of daughter cells',
  ], 1, 'Without a nucleus or the internal machinery for mitosis, prokaryotes divide by the simpler process of binary fission.'),
  mc('e10', E, 'A structure that helps some prokaryotic cells move through their environment is the', [
    'flagellum',
    'centriole',
    'chloroplast',
    'nucleolus',
  ], 0, 'Many motile bacteria use a whip-like flagellum to propel themselves.'),
  mc('e11', E, 'A eukaryotic cell is characterized by all of the following EXCEPT', [
    'a true, membrane-bound nucleus containing linear DNA',
    'membrane-bound organelles',
    'the possibility of being either unicellular or multicellular',
    'reproduction exclusively by binary fission',
  ], 3, 'Eukaryotes reproduce via mitosis (and meiosis for sex cells), not binary fission, which is specific to prokaryotes.'),
  mc('e12', E, 'Which comparison of typical cell sizes is correct?', [
    'Most bacteria: 1–10 micrometers; most eukaryotic cells: 10–100 micrometers',
    'Most bacteria: 100–1000 micrometers; most eukaryotic cells: 1–10 micrometers',
    'Bacteria and eukaryotic cells are typically the same size',
    'Eukaryotic cells are always smaller than bacteria',
  ], 0, 'Eukaryotic cells are roughly one order of magnitude larger than typical bacterial cells.'),
  mc('e13', E, 'A human hair is roughly 0.016 to 0.05 mm thick. Given that most eukaryotic cells are 10–100 micrometers (0.01–0.1 mm) across, which conclusion is most accurate?', [
    'A single eukaryotic cell is far too small to be seen without a powerful electron microscope',
    'A single eukaryotic cell is roughly comparable in scale to the width of a human hair, and several could fit across that width',
    'A human hair is much smaller than a single bacterial cell',
    'A single eukaryotic cell is thousands of times larger than a human hair',
  ], 1, 'Since both values fall in a similar micrometer/millimeter range, a eukaryotic cell is on the same general scale as hair width, though multiple cells could still span the hair\'s thickness.'),
  mc('e14', E, 'If a bacterial cell is roughly 2 micrometers across, this is equal to approximately how many millimeters?', [
    '2 mm',
    '0.002 mm',
    '20 mm',
    '0.2 mm',
  ], 1, '1 micrometer = 0.001 millimeter, so 2 micrometers = 2 × 0.001 = 0.002 mm.'),
  mc('e15', E, 'A cell is found to have circular DNA located in a nucleoid region, no membrane-bound organelles, and a peptidoglycan wall. This cell is most likely', [
    'a plant cell',
    'a prokaryote (bacterium)',
    'a fungal cell',
    'an animal cell',
  ], 1, 'Circular DNA, a nucleoid (not a true nucleus), no membrane-bound organelles, and peptidoglycan are all defining prokaryotic traits.', 'prok-cell'),
  mc('e16', E, 'A cell is found to be 60 micrometers across, contains a nucleolus inside a membrane-bound nucleus, and has linear chromosomes. This cell is most likely', [
    'a typical bacterium',
    'a eukaryotic cell',
    'a virus particle',
    'impossible to classify without a cell wall present',
  ], 1, 'Size (well within the 10–100 µm eukaryotic range), a true nucleus with a nucleolus, and linear DNA are all defining eukaryotic traits.'),
  mc('e17', E, 'The three main jobs shared by essentially all cells are to', [
    'make energy, make proteins, and make more cells',
    'make cellulose, make chitin, and make peptidoglycan',
    'perform photosynthesis, digestion, and excretion only',
    'perform mitosis, meiosis, and binary fission simultaneously',
  ], 0, 'Every cell must generate usable energy, synthesize the proteins that do its work, and be capable of producing new cells for growth or repair/reproduction.'),
  mc('e18', E, 'Which structure or process is responsible for carrying out the "make proteins" job common to all cells?', [
    'The cell wall',
    'Ribosomes',
    'The nucleoid alone, with no other structures',
    'The contractile vacuole',
  ], 1, 'Ribosomes translate genetic information into functional proteins in every cell type, prokaryotic or eukaryotic.'),
  multi('e19', E, 'Select ALL traits that are characteristic of prokaryotic cells.', [
    'No membrane-bound nucleus',
    'Circular DNA, sometimes including plasmids',
    '70S ribosomes',
    'Reproduction by mitosis',
  ], [0, 1, 2], 'Mitosis is a eukaryotic process; prokaryotes reproduce by binary fission instead.'),
  multi('e20', E, 'Select ALL traits that are characteristic of eukaryotic cells.', [
    'A membrane-bound nucleus with a nucleolus',
    'Membrane-bound organelles',
    '80S ribosomes',
    'A peptidoglycan cell wall in every cell type',
  ], [0, 1, 2], 'Peptidoglycan is specific to bacteria. Eukaryotic walls, when present (plants, fungi), are made of cellulose or chitin instead.'),
  mc('e21', E, 'A structure found in BOTH a typical bacterial cell and a typical animal cell is the', [
    'nucleus',
    'mitochondrion',
    'plasma membrane',
    'chloroplast',
  ], 2, 'Every cell, regardless of complexity, is bounded by a plasma membrane. Nuclei, mitochondria, and chloroplasts are eukaryotic structures.'),
  mc('e22', E, 'Which of the following is NOT one of the four features shared by all cells (both domains)?', [
    'Cytoplasm',
    'Ribosomes',
    'A nucleus',
    'Genetic material (DNA or RNA)',
  ], 2, 'A true nucleus is unique to eukaryotic cells; prokaryotes instead store DNA in an unbound nucleoid region.'),
  mc('e23', E, 'A researcher discovers extra small circular DNA molecules, separate from the main chromosome, inside a bacterial cell. These are called', [
    'nucleoli',
    'plasmids',
    'centrioles',
    'capsids',
  ], 1, 'Plasmids are small, separate circular DNA molecules commonly found in prokaryotic cells, in addition to their main circular chromosome.'),
  mc('e24', E, 'Compared to eukaryotic cell walls, a defining feature of bacterial cell walls is that they', [
    'are made of cellulose, just like plant cell walls',
    'are made of peptidoglycan, a material unique to bacteria, and are often further surrounded by a protective capsule',
    'are entirely absent in all prokaryotes',
    'are made of chitin, just like fungal cell walls',
  ], 1, 'Peptidoglycan and an outer capsule are characteristic of many bacteria, structurally distinct from any eukaryotic wall material.'),
  mc('e25', E, 'A student claims "all eukaryotic organisms are multicellular." What is the flaw in this claim?', [
    'There is no flaw; the claim is correct',
    'Many protists and some fungi (like yeast) are unicellular eukaryotes, so eukaryotic does not imply multicellular',
    'All eukaryotes are actually prokaryotic',
    'Multicellularity is exclusive to prokaryotes',
  ], 1, 'Eukaryotic cells can be organized as unicellular organisms (many protists, yeast) or multicellular organisms (plants, animals, most fungi) — the two properties are independent.'),
  mc('e26', E, 'Archaea are grouped together with which type of cellular organization?', [
    'Eukaryotic, alongside protists',
    'Prokaryotic, alongside bacteria',
    'A separate, non-cellular category like viruses',
    'Eukaryotic, alongside fungi',
  ], 1, 'Archaea, like bacteria, lack a membrane-bound nucleus and are classified structurally as prokaryotes, even though they are genetically distinct from bacteria.'),
  mc('e27', E, 'If an antibiotic is designed to bind specifically to 70S ribosomes and disrupt protein synthesis, which cells would be most directly affected, and why might this be relatively safe for a human patient?', [
    'Human (eukaryotic) cells, because they only have 70S ribosomes',
    'Bacterial (prokaryotic) cells, because they have 70S ribosomes, while human cells have the structurally different 80S ribosomes',
    'Both equally, since ribosome size does not differ between domains',
    'Neither, since antibiotics cannot target ribosomes',
  ], 1, 'This reasoning reflects real antibiotic design: targeting the structural difference between 70S (bacterial) and 80S (human/eukaryotic) ribosomes allows selective harm to bacteria.'),
  mc('e28', E, 'Which pairing of a structural feature with the correct domain is INCORRECT?', [
    'Prokaryote — circular DNA in a nucleoid',
    'Eukaryote — linear DNA in a membrane-bound nucleus',
    'Prokaryote — reproduces via mitosis',
    'Eukaryote — may have membrane-bound organelles',
  ], 2, 'Prokaryotes reproduce via binary fission, not mitosis, since they lack the nuclear membrane and mitotic spindle apparatus mitosis depends on.'),
  mc('e29', E, 'A cell is unicellular, about 3 micrometers long, has no nucleus, and divides by binary fission. Which additional feature would you also expect this cell to have?', [
    'A true, membrane-bound nucleolus',
    'A nucleoid region with a single circular chromosome',
    'Mitochondria and a Golgi apparatus',
    '80S ribosomes',
  ], 1, 'All of these clues (size, no nucleus, binary fission) point to a prokaryote, which stores its DNA in a nucleoid rather than a membrane-bound nucleus and lacks membrane-bound organelles like mitochondria.', 'prok-cell'),
  mc('e30', E, 'Which statement best explains why eukaryotic cells can generally support more complex, specialized functions than prokaryotic cells?', [
    'Eukaryotic cells are smaller and therefore simpler',
    'Membrane-bound organelles let eukaryotic cells compartmentalize different functions (energy production, digestion, protein modification) in separate, specialized spaces',
    'Prokaryotic cells contain more types of organelles than eukaryotic cells',
    'Eukaryotic cells lack ribosomes, freeing up space for other functions',
  ], 1, 'Compartmentalization via membrane-bound organelles allows different biochemical processes to occur simultaneously in optimized, separate environments — a major advantage of eukaryotic complexity.'),
]

export const PLANT_ANIMAL_QUESTIONS: BioPracticeQuestion[] = [
  mc('pa1', P, 'Which set of structures is unique to plant cells and not typically found in animal cells?', [
    'Lysosomes, centrioles, and small vacuoles',
    'A cellulose cell wall, one large central vacuole, and chloroplasts',
    'A nucleus, ribosomes, and a plasma membrane',
    'Mitochondria and a Golgi apparatus',
  ], 1, 'Both cell types share the general eukaryotic organelles (nucleus, ribosomes, mitochondria), but the wall, giant central vacuole, and chloroplasts are the plant-specific structures highlighted in this unit.', 'plant-animal-cells'),
  mc('pa2', P, 'Which set of structures is characteristic of typical animal cells but absent in typical plant cells?', [
    'Chloroplasts and a cellulose wall',
    'Lysosomes and centrioles',
    'A large central vacuole and cell wall',
    'A nucleus and cytoplasm',
  ], 1, 'Lysosomes (digestion/cleanup) and centrioles (organizing cell division) are specialized animal-cell structures not typically found in plant cells.', 'plant-animal-cells'),
  mc('pa3', P, 'Lysosomes function primarily in', [
    'converting sunlight into chemical energy',
    'breaking down and digesting cellular waste, damaged organelles, and engulfed material',
    'providing rigid structural support to the cell',
    'storing large volumes of water',
  ], 1, 'Lysosomes contain digestive enzymes used for breaking down waste and recycling cellular components — sometimes called the cell\'s "cleanup crew."'),
  mc('pa4', P, 'Centrioles are structures involved in', [
    'photosynthesis',
    'organizing the process of cell division',
    'storing water and maintaining turgor pressure',
    'forming the rigid outer wall of the cell',
  ], 1, 'Centrioles help organize the spindle apparatus during cell division, a role specific to animal cells in this unit\'s comparison.'),
  mc('pa5', P, 'Chloroplasts are the organelles responsible for', [
    'breaking down waste products',
    'converting light energy into chemical energy (sugar), which also gives plant tissue its green color',
    'organizing cell division',
    'providing rigid support outside the membrane',
  ], 1, 'Chloroplasts carry out photosynthesis, producing food for the plant cell and containing the pigment that gives plants their green color.'),
  mc('pa6', P, 'The plant cell wall is best described as', [
    'located inside the plasma membrane, made of protein',
    'located outside the plasma membrane, made of cellulose, providing structural support and a fixed shape',
    'identical in composition to a bacterial cell wall',
    'a feature shared equally by plant and animal cells',
  ], 1, 'Position (outside the membrane), composition (cellulose), and function (rigid support/shape) are the three defining features of the plant cell wall.'),
  mc('pa7', P, 'A fungal cell wall differs from a plant cell wall in that the fungal wall is made of', [
    'cellulose, exactly like a plant wall',
    'chitin, rather than cellulose',
    'peptidoglycan, like a bacterial wall',
    'cholesterol embedded in a lipid layer',
  ], 1, 'Even though both plants and fungi have eukaryotic cell walls, the carbohydrate that makes up each wall differs: cellulose in plants, chitin in fungi.'),
  mc('pa8', P, 'The single large central vacuole in a mature plant cell serves which combination of functions?', [
    'Photosynthesis and cell division only',
    'Storing water, food, and waste while also maintaining turgor pressure and helping resist bursting in a hypotonic environment',
    'Digesting bacteria engulfed by phagocytosis',
    'Producing the plant\'s genetic material',
  ], 1, 'The central vacuole is a storage reservoir and also plays the key structural role of generating turgor pressure that keeps the plant rigid.'),
  mc('pa9', P, 'Which best contrasts vacuoles in typical plant cells versus typical animal cells?', [
    'Plant cells have many small vacuoles; animal cells have one large central vacuole',
    'Plant cells typically have one large central vacuole; animal cells typically have several smaller vacuoles',
    'Neither cell type has vacuoles',
    'Both cell types have an identical number and size of vacuoles',
  ], 1, 'Size and number differ by cell type: one dominant central vacuole in plants versus multiple smaller vacuoles for various storage roles in animal cells.'),
  mc('pa10', P, 'A contractile vacuole, found in freshwater protists rather than typical plant or animal cells, functions to', [
    'store starch reserves for later energy use',
    'actively expel excess water that enters the cell by osmosis in a hypotonic environment, preventing cytolysis',
    'carry out photosynthesis using chlorophyll',
    'anchor the cell to a substrate',
  ], 1, 'This organelle connects directly back to osmotic principles: in a hypotonic freshwater environment, a protist must actively remove the water constantly entering by osmosis.'),
  mc('pa11', P, 'Why do plant cells maintain a fixed, regular shape while animal cells tend to have irregular, flexible shapes?', [
    'Plant cells lack a plasma membrane, while animal cells have one',
    'The rigid cellulose cell wall constrains and defines the plant cell\'s shape, while animal cells lack this external constraint',
    'Animal cells contain chloroplasts that force a round shape',
    'Plant cells are always smaller than animal cells',
  ], 1, 'The wall\'s rigidity is the direct structural cause of the plant cell\'s fixed shape; without a wall, the flexible animal cell membrane allows irregular shapes.'),
  mc('pa12', P, 'A cell viewed under a microscope shows a rigid rectangular shape, one enormous central compartment taking up most of the cell\'s volume, and small green ovals near the edges. This cell is most likely', [
    'an animal cell',
    'a plant cell',
    'a prokaryote',
    'a virus',
  ], 1, 'The rigid, boxy shape (wall), the single dominant vacuole, and the green organelles (chloroplasts) together are diagnostic of a plant cell.', 'plant-animal-cells'),
  mc('pa13', P, 'A cell viewed under a microscope shows an irregular, rounded shape with no visible rigid boundary, several small vesicle-like structures, and no green organelles. This cell is most likely', [
    'a plant cell',
    'an animal cell',
    'a bacterium',
    'a fungal cell',
  ], 1, 'The lack of a wall (irregular shape), absence of chloroplasts, and presence of multiple small vacuole-like structures point to an animal cell.', 'plant-animal-cells'),
  multi('pa14', P, 'Select ALL structures that are part of a typical plant cell\'s distinguishing features in this unit.', [
    'Cellulose cell wall',
    'One large central vacuole',
    'Chloroplasts',
    'Centrioles',
  ], [0, 1, 2], 'Centrioles are the animal-specific structure in this comparison, not a plant feature.'),
  multi('pa15', P, 'Select ALL structures that are part of a typical animal cell\'s distinguishing features in this unit.', [
    'No cell wall (irregular, flexible shape)',
    'Multiple small vacuoles',
    'Lysosomes and centrioles',
    'Chloroplasts',
  ], [0, 1, 2], 'Chloroplasts are exclusive to photosynthetic organisms (plants, algae) and are not found in typical animal cells.'),
  mc('pa16', P, 'A plant wilting after several days without water is directly explained by which structural/osmotic connection?', [
    'The central vacuole loses water and shrinks, reducing turgor pressure that normally presses the membrane against the rigid cell wall',
    'The cellulose wall dissolves completely, causing the cell to collapse',
    'Chloroplasts stop functioning entirely, causing water loss',
    'Lysosomes digest the missing water molecules',
  ], 0, 'Without adequate water, the central vacuole shrinks, turgor pressure drops, and the flexible membrane no longer pushes firmly against the rigid wall — this loss of turgor is what makes the plant visibly wilt.'),
  mc('pa17', P, 'Why does a typical animal cell placed in a very hypotonic solution face a greater risk of bursting than a plant cell placed in the same solution?', [
    'Animal cells have no cell wall to physically resist the swelling caused by incoming water, unlike plant cells which are constrained by their wall',
    'Animal cells actively pump water in, while plant cells pump water out',
    'Plant cells have no plasma membrane, so water cannot enter them at all',
    'Animal cells contain more solute than plant cells under all conditions',
  ], 0, 'The rigid wall gives plant cells a hard physical limit on expansion (turgor pressure counters further swelling), a safeguard animal cells simply do not have.'),
  mc('pa18', P, 'Which organelle in plant cells is functionally linked to the process of photosynthesis first introduced with Unit 1 macromolecule and energy concepts?', [
    'Lysosome',
    'Chloroplast',
    'Centriole',
    'Nucleolus',
  ], 1, 'Chloroplasts capture light energy and convert it into chemical energy (glucose), directly connecting cell structure to whole-organism energy production.'),
  mc('pa19', P, 'Eukaryotic cell walls (in the organisms that have them) are best described as', [
    'located inside the plasma membrane in both plants and fungi',
    'restricted to plants and fungi, positioned outside the plasma membrane, providing structural support that animal cells lack',
    'a universal feature of every eukaryotic cell, including animal cells',
    'made of the exact same molecule (peptidoglycan) in both plants and fungi',
  ], 1, 'Among eukaryotes, only plant and fungal cells have this outer structural layer, and the specific carbohydrate differs between the two (cellulose vs. chitin).'),
  mc('pa20', P, 'A biologist wants to distinguish a plant cell from a fungal cell using only cell wall chemistry. The correct test would look for', [
    'the presence of any cell wall at all',
    'whether the wall is made of cellulose (plant) or chitin (fungus)',
    'whether the wall is made of peptidoglycan (plant) or cellulose (fungus)',
    'whether the cell has a nucleus, since only fungal cells have one',
  ], 1, 'Since both plant and fungal cells have walls, the chemistry of the wall — cellulose vs. chitin — is the distinguishing feature, not the mere presence of a wall.'),
  mc('pa21', P, 'Which of these functions is shared between chloroplasts (plant) and mitochondria (both plant and animal), even though they carry out very different specific reactions?', [
    'Both convert forms of energy that ultimately support the cell\'s energy needs',
    'Both are found exclusively in animal cells',
    'Both are the site of protein digestion',
    'Both are surrounded by a rigid cellulose wall',
  ], 0, 'Chloroplasts capture light energy into chemical energy (glucose); mitochondria (though not detailed in this unit\'s slides) later convert that chemical energy into ATP — both are fundamentally energy-related organelles.'),
]

export const SURFACES_VIRUS_QUESTIONS: BioPracticeQuestion[] = [
  mc('v1', S, 'Tight junctions between animal cells function by', [
    'forming pores that directly connect the cytoplasm of two adjacent cells',
    'using interlocking membrane proteins to physically bind neighboring cells firmly together',
    'allowing cytoplasmic exchange through gaps in a cellulose wall',
    'engulfing neighboring cells through phagocytosis',
  ], 1, 'Tight junctions are built from interlocking proteins that seal cells together, useful for forming barriers like the lining of the digestive tract.'),
  mc('v2', S, 'Gap junctions differ from tight junctions in that gap junctions', [
    'only hold cells together mechanically, without any exchange of material',
    'create direct channels connecting the cytoplasm of two cells, allowing ions, small molecules, and electrical impulses to pass through',
    'are found exclusively in plant cell walls',
    'require ATP-independent osmosis to function',
  ], 1, 'Gap junctions form an actual communication channel between cells, unlike tight junctions, which primarily provide a mechanical, sealing bond.'),
  mc('v3', S, 'Plasmodesmata serve a role in plant cells that is functionally most similar to which animal cell structure?', [
    'Tight junctions, because both only mechanically bind cells',
    'Gap junctions, because both create channels allowing direct exchange of cytoplasm and signals between adjacent cells',
    'Lysosomes, because both digest waste',
    'Centrioles, because both organize cell division',
  ], 1, 'Despite occurring in very different structures (a wall pore vs. a protein channel), plasmodesmata and gap junctions serve an analogous communication function between neighboring cells.'),
  mc('v4', S, 'Why do plant cells specifically need plasmodesmata for intercellular communication, when this is a less urgent problem for many mobile organisms?', [
    'Plants have no plasma membrane, so cells must communicate through the wall alone',
    'Because plant cells are immobile and are also boxed in by a rigid cell wall, they need channels through that wall to exchange cytoplasm, signals, and materials directly with neighbors',
    'Plant cells cannot produce any of their own proteins',
    'Plasmodesmata are required for plant cells to photosynthesize',
  ], 1, 'Being both stationary and enclosed by a wall creates a specific communication challenge for plants; pores through that wall solve the problem the wall itself creates.'),
  mc('v5', S, 'A drug that selectively disables gap junctions between adjacent heart muscle cells would most directly disrupt', [
    'the mechanical adhesion holding the cells together',
    'the direct passage of electrical impulses and ions between neighboring cells, which is essential for coordinated muscle contraction',
    'the cellulose wall structure of the heart cells',
    'the cell\'s ability to import cholesterol',
  ], 1, 'Because gap junctions allow direct electrical/ionic communication between cells, disabling them would interfere with the coordinated signal propagation on which synchronized contraction depends.'),
  mc('v6', S, 'Which of the following correctly matches a structure to the type of cell it is found in?', [
    'Tight and gap junctions — animal cells; plasmodesmata — plant cells',
    'Plasmodesmata — animal cells; tight and gap junctions — plant cells',
    'All three structures are found exclusively in prokaryotic cell walls',
    'All three structures are unique to viruses',
  ], 0, 'Animal cell surfaces use tight and gap junctions; plant cells, bounded by a wall, instead use plasmodesmata (pores through the wall).'),
  mc('v7', S, 'Viruses are best described in this unit as', [
    'fully living cells that reproduce independently by binary fission',
    'infectious particles that display some, but not all, of the characteristics of life',
    'a subtype of prokaryotic cell',
    'the most basic unit of eukaryotic life',
  ], 1, 'Viruses show some traits associated with life (genetic material, evolution) but lack independent metabolism and cellular structure, so they fall short of being classified as fully "alive" or as cells.', 'virus-struct'),
  mc('v8', S, 'Which combination of traits explains why viruses are not considered fully alive under most biological definitions?', [
    'They require a host cell to reproduce, have no cellular structure of their own, and do not carry out independent energy metabolism',
    'They are too large to be considered organisms',
    'They contain no genetic material at all',
    'They can be seen without a microscope',
  ], 0, 'This trio of features — obligate host dependence, lack of cells, and no independent metabolism — is exactly why viruses fall outside standard definitions of life.'),
  mc('v9', S, 'The fact that viruses can evolve extremely rapidly and produce many distinct strains is best explained by', [
    'their large size, which allows more room for mutations',
    'high replication rates combined with a genome that accumulates mutations quickly, generating significant genetic variation over short timescales',
    'their ability to photosynthesize new genetic material',
    'the fact that they are technically classified as eukaryotic cells',
  ], 1, 'Rapid, high-volume replication paired with an error-prone copying process for many viral genomes accelerates the accumulation of genetic variation, producing new strains quickly.'),
  mc('v10', S, 'Comparing typical sizes, which ranking from LARGEST to SMALLEST is correct?', [
    'Virus > prokaryotic cell > eukaryotic cell',
    'Eukaryotic cell > prokaryotic cell > virus',
    'Prokaryotic cell > virus > eukaryotic cell',
    'All three are approximately the same size',
  ], 1, 'Eukaryotic cells are generally the largest, prokaryotic cells are smaller, and viruses are smaller still than either type of cell.'),
  mc('v11', S, 'According to this unit, every virus particle possesses all of the following EXCEPT', [
    'a capsid (protective protein shell)',
    'a nucleic acid genome made of DNA or RNA',
    'ribosomes for independent protein synthesis',
    'in many cases, an outer envelope derived from membrane',
  ], 2, 'Viruses lack their own ribosomes and rely entirely on hijacking a host cell\'s ribosomes and machinery to produce new viral proteins.', 'virus-struct'),
  mc('v12', S, 'The protein shell that encases and protects a virus\'s genetic material is called the', [
    'nucleoid',
    'capsid',
    'cell wall',
    'plasma membrane',
  ], 1, 'The capsid is a defining structural feature of every virus, distinct from any structure found in a true cell.', 'virus-struct'),
  mc('v13', S, 'A virus\'s genome may be composed of', [
    'DNA only, never RNA',
    'either DNA or RNA, depending on the specific virus',
    'protein only, with no nucleic acid',
    'peptidoglycan',
  ], 1, 'Unlike cellular life, which universally uses DNA as its primary genetic material, viruses can have genomes made of either DNA or RNA.'),
  mc('v14', S, 'Because viruses lack their own ribosomes, metabolic machinery, and means of independent reproduction, they must', [
    'reproduce using mitosis, just like eukaryotic cells',
    'hijack a host cell\'s machinery to replicate and produce new viral particles',
    'undergo binary fission independently',
    'perform photosynthesis to generate the energy needed to divide',
  ], 1, 'Because viruses cannot replicate on their own, they redirect a host cell\'s existing ribosomes and enzymes to manufacture new copies of themselves.'),
  mc('v15', S, 'A newly discovered infectious particle is found to have a protein capsid and an RNA genome, but no ribosomes, no cytoplasm, and no ability to reproduce outside of a host cell. Based on cell theory and this unit\'s criteria, this particle should be classified as', [
    'a prokaryotic cell',
    'a eukaryotic cell',
    'a virus, not a cell, and therefore not fully alive under the tenets of cell theory',
    'a plant cell',
  ], 2, 'Lacking cytoplasm, ribosomes, and independent reproduction disqualifies this particle from being a cell — placing it squarely in the "virus" category rather than any cellular classification.', 'virus-struct'),
  mc('v16', S, 'Which of the following is the SMALLEST, based on typical size comparisons covered in this unit?', [
    'A typical eukaryotic cell',
    'A typical prokaryotic cell',
    'A typical virus particle',
    'A single plant leaf',
  ], 2, 'Viruses are smaller than both types of cells, which is part of why they were not directly observable until the invention of the electron microscope.'),
  multi('v17', S, 'Select ALL structures found in animal cell surfaces (not plant cell surfaces) as covered in this unit.', [
    'Tight junctions',
    'Gap junctions',
    'Plasmodesmata',
    'A nucleoid region',
  ], [0, 1], 'Plasmodesmata are specific to plant cell walls; a nucleoid is a prokaryotic structure unrelated to animal cell surfaces.'),
  multi('v18', S, 'Select ALL statements that are true of viruses according to this unit.', [
    'Every virus has a capsid and a DNA or RNA genome',
    'Viruses require a host cell to reproduce and lack independent energy metabolism',
    'Viruses can evolve rapidly and form distinct genetic strains',
    'Viruses satisfy all three parts of cell theory',
  ], [0, 1, 2], 'Because viruses are not classified as cells, they do not satisfy cell theory\'s tenets, which are specifically about cells.'),
  mc('v19', S, 'A researcher notes that removing a specific set of interlocking membrane proteins from an epithelial tissue causes the tissue to become "leaky," allowing fluid to pass between cells that it normally could not. The proteins removed were most likely part of', [
    'plasmodesmata',
    'tight junctions',
    'a virus capsid',
    'a nucleoid region',
  ], 1, 'Tight junctions are specifically responsible for sealing the spaces between cells, preventing fluid from leaking through; removing them would produce exactly this "leaky" effect.'),
  mc('v20', S, 'An electrical impulse needs to pass directly and rapidly from one animal cell\'s cytoplasm into the neighboring cell\'s cytoplasm. This is made possible by', [
    'tight junctions, which only provide mechanical adhesion',
    'gap junctions, which form a direct channel between the two cytoplasms',
    'a rigid cellulose wall',
    'a virus\'s protein capsid',
  ], 1, 'Only gap junctions provide a literal, direct channel connecting two cells\' interiors, enabling fast electrical/chemical signal transfer.'),
  mc('v21', S, 'Plasmodesmata specifically allow plant cells to accomplish which task that would otherwise be difficult given their rigid cell walls?', [
    'Photosynthesis',
    'Exchange of cytoplasm, signals, and materials directly between neighboring, wall-enclosed cells',
    'Producing their own genetic material independently',
    'Engulfing bacteria by phagocytosis',
  ], 1, 'The rigid wall that gives plants structural support also blocks the kind of direct cell-to-cell contact animal cells achieve through their flexible membranes; plasmodesmata solve this by tunneling through the wall.'),
  mc('v22', S, 'Applying cell theory\'s definition strictly, which classification is most appropriate for a virus?', [
    'A fully living, single-celled prokaryote',
    'Not a cell, and therefore outside the scope of cell theory, despite containing genetic material',
    'A fully living eukaryotic cell lacking a nucleus',
    'A basic unit of life, equivalent to a bacterium',
  ], 1, 'Cell theory concerns cells specifically; because a virus lacks cellular structure and independent metabolism, it is excluded from classification as a living cell.'),
]
