import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const H = 'history' as const
const E = 'prok-euk' as const
const P = 'plant-animal' as const
const S = 'surfaces' as const

export const HISTORY_QUESTIONS: BioPracticeQuestion[] = [
  mc('h1', H, 'Robert Hooke (1665) used a primitive microscope to look at', [
    'living bacteria swimming in pond water',
    'cork, and named the empty chambers “cells”',
    'DNA double helices in a nucleus',
    'the lipid envelope around a virus',
  ], 1, 'Those chambers were actually dead plant cells. He named cells; he did not write all of cell theory.'),
  mc('h2', H, 'Anton van Leeuwenhoek was first to', [
    'propose that all plants are made of cells',
    'observe microorganisms and call them animalcules',
    'prove that all cells come from other cells',
    'name the nucleus inside eukaryotes',
  ], 1, 'Animalcules = “little animals” = microbes he saw with better lenses.'),
  mc('h3', H, 'Matthias Schleiden proposed that', [
    'all animals are made of cells',
    'all plants are made of cells',
    'viruses count as living cells',
    'cork is made of animal tissue',
  ], 1, 'Schleiden → plants. Schwann → animals. Do not swap them.'),
  mc('h4', H, 'Theodor Schwann proposed that', [
    'all plants are made of cells',
    'all animals are made of cells (“swan”)',
    'all cells appear from salt crystals',
    'bacteria have membrane-bound nuclei',
  ], 1, 'Schwann → animals. Mnemonic: swan.'),
  mc('h5', H, 'Rudolf Virchow proposed that', [
    'cells spontaneously appear from mud',
    'all cells come from pre-existing cells',
    'only plants, not animals, have cells',
    'viruses are the basic unit of life',
  ], 1, 'No spontaneous generation of cells — cells from cells.'),
  mc('h6', H, 'Cell theory in these notes was built from work by', [
    'Hooke alone, because he named cells',
    'Hooke, Leeuwenhoek, Schleiden, Schwann, and Virchow',
    'Watson and Crick only, for DNA structure',
    'macrophages only, for phagocytosis',
  ], 1, 'History names are fair game. Each person added a different piece.'),
  mc('h7', H, 'The three parts of cell theory are', [
    'living things are cellular; cell = basic unit; cells come from cells',
    'all cells have chloroplasts; all cells have walls; all cells are bacteria',
    'viruses are fully alive; cells appear from salt; energy use is optional',
    'only animals have cells; plants, fungi, and bacteria do not',
  ], 0, 'Memorize all three exactly: all living things are made of cells; cells are the basic unit of life; all cells come from other cells. Bacteria are cells. Viruses are not.'),
  mc('h8', H, '“Cells are the basic unit of life” means', [
    'organs are smaller than individual atoms',
    'the cell is the smallest living/functional unit',
    'viruses count as complete living cells',
    'only cork tissue is considered alive',
  ], 1, 'Tissues and organs are made OF cells.'),
  mc('h9', H, 'Which scientist matches “all plants are made of cells”?', [
    'Schwann',
    'Schleiden',
    'Virchow',
    'Leeuwenhoek',
  ], 1, 'Schleiden plants, Schwann animals.'),
  mc('h10', H, 'Which scientist matches “all animals are made of cells”?', [
    'Schleiden',
    'Schwann',
    'Hooke',
    'Virchow',
  ], 1, 'Swan → Schwann → animals.'),
  mc('h11', H, 'Which scientist matches “all cells come from cells”?', [
    'Hooke',
    'Virchow',
    'Schleiden',
    'Leeuwenhoek',
  ], 1, 'Virchow. Hooke named cells; he did not add this third point.'),
  mc('h12', H, 'Hooke’s “cells” in cork were', [
    'living animalcules swimming',
    'dead plant cells (empty chambers)',
    'intact virus particles',
    'stained eukaryotic nuclei',
  ], 1, 'Cork is bark — dead plant tissue.'),
  multi('h13', H, 'Choose ALL parts of cell theory.', [
    'All living things are made of cells',
    'Cells are the basic unit of life',
    'All cells come from other cells',
    'All cells are eukaryotic',
  ], [0, 1, 2], 'Bacteria are prokaryotic cells and still count.'),
  mc('h14', H, 'Virchow’s idea rejects spontaneous generation of cells because it says', [
    'new cells only come from cells that already exist',
    'cork chambers create living animals',
    'viruses should be classified as cells',
    'plants do not contain any cells',
  ], 0, 'Life from life, at the cell level.'),
  mc('h15', H, 'Leeuwenhoek’s animalcules were', [
    'empty cork chambers Hooke named',
    'microorganisms he observed',
    'chloroplasts inside plant cells',
    'protein capsids around virus DNA',
  ], 1, 'First look at microbes.'),
  mc('h16', H, 'If a question asks who NAMED cells, pick', [
    'Virchow',
    'Hooke',
    'Schwann',
    'Schleiden',
  ], 1, 'Naming cells ≠ writing all three parts of cell theory.'),
  mc('h17', H, 'Cell theory applies to', [
    'animals, but not plants or fungi',
    'all living things made of cells, including bacteria',
    'viruses, because they have protein capsids',
    'cork only, because Hooke studied cork',
  ], 1, 'Viruses are not cells and are not fully alive by this unit’s rules.'),
  mc('h18', H, 'A new bacterium appearing only after another splits best supports', [
    'Hooke naming empty chambers in cork',
    'Virchow’s “cells from cells,” plus binary fission',
    'Schwann’s animal idea as the entire theory',
    'the claim that viruses are complete cells',
  ], 1, 'Reproduction of cells is part of theory AND prokaryote notes.'),
]

export const PROK_EUK_QUESTIONS: BioPracticeQuestion[] = [
  mc('e1', E, 'Eukaryotes include', [
    'bacteria only, never plants',
    'plants, animals, protists, and fungi',
    'viruses with capsids and envelopes',
    'archaea only, never protists',
  ], 1, 'Eu = true nucleus.'),
  mc('e2', E, 'Prokaryotes in this unit are', [
    'plants, which have cellulose walls',
    'bacteria (and archaea, covered later)',
    'fungi, which have chitin walls',
    'protists, which are all eukaryotic',
  ], 1, 'Pro rhymes with no — no nucleus.'),
  mc('e3', E, 'ALL cells have', [
    'a nucleus, chloroplasts, and a cellulose wall',
    'cytoplasm, ribosomes, a membrane, and DNA or RNA',
    'mitochondria and a nucleolus in every cell',
    'lysosomes and centrioles in every cell',
  ], 1, 'Ribosomes make proteins and are NOT considered an organelle here.'),
  mc('e4', E, 'Ribosomes', [
    'are membrane-bound organelles like mitochondria',
    'make proteins and are not called organelles here',
    'store DNA only inside eukaryotic nuclei',
    'are cellulose stacked in plant cell walls',
  ], 1, 'That is why prokaryotes can still make protein with no nucleus.'),
  mc('e5', E, 'Prokaryotic cells are', [
    'always multicellular tissues with nuclei',
    'unicellular, ~1–10 µm, no nucleus or membrane organelles',
    '10–100 µm with linear DNA in a true nucleus',
    'always packed with chloroplasts for sugar',
  ], 1, 'One slide says 1–5 µm; the comparison table says most bacteria 1–10 µm. Either way they are smaller than typical eukaryotes.'),
  mc('e6', E, 'A nucleoid is', [
    'a true nucleus wrapped in a membrane',
    'the prokaryote region that holds circular DNA',
    'a chloroplast that makes glucose',
    'a protein capsid around a virus',
  ], 1, 'No nuclear membrane. DNA is a loop; plasmids may also be present.', 'prok-cell'),
  mc('e7', E, 'Bacterial cell walls are made of', [
    'cellulose, like plant walls',
    'chitin, like fungal walls',
    'peptidoglycan, often with an outer capsule',
    'cholesterol, like animal membranes',
  ], 2, 'Plants = cellulose. Fungi = chitin. Bacteria = peptidoglycan. Animals = no wall.'),
  mc('e8', E, 'Prokaryotic ribosomes are', [
    '80s, larger than eukaryotic ones',
    '70s, smaller than eukaryotic ones',
    'absent, so bacteria cannot make protein',
    'the same structures as chloroplasts',
  ], 1, '70s vs 80s is a classic honors compare item.'),
  mc('e9', E, 'Prokaryotes reproduce by', [
    'mitosis, because they have a nucleus',
    'binary fission (“b” for bacteria)',
    'endocytosis of a neighboring cell',
    'making spores inside a nucleolus',
  ], 1, 'No mitosis here because there is no nucleus / mitotic spindle like eukaryotes.'),
  mc('e10', E, 'Some prokaryotes move with', [
    'plasmodesmata through a cellulose wall',
    'flagella',
    'tight junctions between cells',
    'chloroplasts pushing the cell',
  ], 1, 'Whip-like flagella.'),
  mc('e11', E, 'Eukaryotic cells', [
    'are unicellular only and never form tissues',
    'may be uni- or multicellular, 10–100 µm, with a nucleus',
    'never have any kind of cell wall at all',
    'have 70s ribosomes sitting in a nucleoid',
  ], 1, 'Eu = true nucleus (with nucleolus). Membrane-bound organelles present. Plant/fungi walls are allowed.'),
  mc('e12', E, 'Eukaryotic ribosomes are', [
    '70s, smaller than bacterial ones',
    '80s, larger than bacterial ones',
    'missing from all plant cells',
    'made of peptidoglycan',
  ], 1, 'Larger than bacterial ribosomes.'),
  mc('e13', E, 'Eukaryotes reproduce using', [
    'binary fission as the notes’ main method',
    'mitosis',
    'only budding of virus capsids',
    'Hooke’s method of naming cork',
  ], 1, 'Mitosis for cell division in this unit.'),
  mc('e14', E, 'Plant and fungal eukaryotic cells have a', [
    'peptidoglycan wall like bacteria',
    'cell wall: cellulose in plants, chitin in fungi',
    'wall made only of cholesterol rings',
    'protein capsid instead of a membrane',
  ], 1, 'Animals: NO cell wall.'),
  mc('e15', E, 'Most eukaryotic cells are about', [
    '1–10 micrometers, like many bacteria',
    '10–100 micrometers (0.01–0.1 mm)',
    'the size of a whole house',
    'always smaller than a bacterial cell',
  ], 1, 'Bacteria ~1–10 µm. Average human hair is about 0.016–0.05 mm thick.'),
  mc('e16', E, '1 micrometer equals', [
    '1 millimeter',
    '0.001 millimeter',
    '1 meter',
    '10 millimeters',
  ], 1, 'Notes: 1–10 µm = 0.001–0.01 mm for many bacteria; 10–100 µm = 0.01–0.1 mm for most eukaryotic cells.'),
  mc('e17', E, 'Circular DNA (nucleoid / plasmids) is a ______ trait.', [
    'eukaryotic',
    'prokaryotic',
    'viral-envelope-only',
    'plant-cell-only',
  ], 1, 'Eukaryotes: linear DNA in a nucleus.'),
  mc('e18', E, 'Linear DNA in a nucleus is a ______ trait.', [
    'prokaryotic',
    'eukaryotic',
    'true of all viruses',
    'peptidoglycan',
  ], 1, 'True nucleus with a nucleolus.'),
  mc('e19', E, 'Unicellular ONLY describes', [
    'eukaryotes in these notes',
    'prokaryotes in these notes',
    'all plant cells in tissues',
    'all animal cells in tissues',
  ], 1, 'Some protists and fungi are unicellular eukaryotes, but eukaryotes can also be multicellular.'),
  mc('e20', E, 'Which can be unicellular OR multicellular?', [
    'prokaryotes only, in these notes',
    'eukaryotes (some protists/fungi stay unicellular)',
    'all bacteria, which form true tissues',
    'all viruses, which are complete cells',
  ], 1, 'Do not say all eukaryotes are multicellular. Plants and animals are multicellular eukaryotes.'),
  mc('e21', E, 'Membrane-bound organelles are found in', [
    'prokaryotes',
    'eukaryotes',
    'all viruses',
    'peptidoglycan',
  ], 1, 'No nucleus OR membrane-bound organelles in prokaryotes.'),
  mc('e22', E, 'Which structure is found in BOTH prokaryotes and eukaryotes?', [
    'nucleus',
    'mitochondria',
    'cell membrane',
    'chloroplasts',
  ], 2, 'Shared: cytoplasm, ribosomes, membrane, genetic material.'),
  mc('e23', E, 'Which is NOT a shared feature of all cells?', [
    'cytoplasm',
    'ribosomes',
    'nucleus',
    'cell membrane',
  ], 2, 'Nucleus is eukaryotic only. Genetic material still exists in prokaryotes as a nucleoid.'),
  mc('e24', E, 'A cell 2 µm across with a nucleoid and peptidoglycan wall is', [
    'a plant cell with cellulose',
    'a prokaryote (bacterium)',
    'an animal cell with centrioles',
    'a virus with only a capsid',
  ], 1, 'Size + no nucleus + peptidoglycan.', 'prok-cell'),
  mc('e25', E, 'A cell 50 µm across with a nucleolus is', [
    'a typical bacterium',
    'eukaryotic',
    'too small to be eukaryotic',
    'a virus particle',
  ], 1, '10–100 µm + true nucleus.'),
  mc('e26', E, 'The three main jobs of cells are', [
    'make energy, make proteins, make more cells',
    'make cork, make animalcules, make viruses',
    'carry out osmosis and nothing else',
    'carry out phagocytosis and nothing else',
  ], 0, 'Energy for activities, proteins do the work, more cells for growth/replacement.'),
  mc('e27', E, 'Cells make proteins because proteins', [
    'are cellulose walls',
    'do the work in cells',
    'are found only in viruses',
    'are the same as cholesterol',
  ], 1, 'Job 2 of cells.'),
  mc('e28', E, 'Cells make more cells for', [
    'capsid assembly in every organism',
    'growth and replacement',
    'osmosis only',
    'making peptidoglycan in animals',
  ], 1, 'Job 3.'),
  multi('e29', E, 'Choose ALL that ALL cells have.', [
    'cytoplasm',
    'ribosomes',
    'cell membrane',
    'nucleus',
  ], [0, 1, 2], 'Genetic material too. Not a nucleus.'),
  multi('e30', E, 'Choose ALL prokaryote traits.', [
    'no nucleus / no membrane-bound organelles',
    'circular DNA in a nucleoid',
    '70s ribosomes and binary fission',
    'cellulose wall and mitosis',
  ], [0, 1, 2], 'Cellulose + mitosis are eukaryotic plant traits.'),
  multi('e31', E, 'Choose ALL eukaryote traits.', [
    'nucleus with linear DNA and nucleolus',
    'membrane-bound organelles',
    '80s ribosomes and mitosis',
    'peptidoglycan wall required in animals',
  ], [0, 1, 2], 'Animal eukaryotes have no wall. Bacteria have peptidoglycan.'),
  mc('e32', E, '“Pro rhymes with no” is a mnemonic for', [
    'no ribosomes, so bacteria cannot make protein',
    'no nucleus and no membrane-bound organelles',
    'no DNA anywhere in a prokaryote',
    'no plasma membrane around bacteria',
  ], 1, 'They still have DNA, ribosomes, cytoplasm, and a membrane.'),
  mc('e33', E, '“Eu = true nucleus” means eukaryotes have', [
    'a nucleoid with no membrane',
    'a membrane-bound nucleus',
    'no DNA at all',
    'only RNA virus genomes',
  ], 1, 'Nucleolus is inside that nucleus.'),
  mc('e34', E, 'Which cell-wall chemistry is matched correctly?', [
    'bacteria — cellulose; plants — peptidoglycan; fungi — chitin',
    'bacteria — peptidoglycan; plants — cellulose; fungi — chitin',
    'all three groups use only chitin',
    'animals — cellulose; plants — none',
  ], 1, 'Animals: no wall.'),
  mc('e35', E, 'Archaea are grouped with', [
    'plants, because they have cellulose walls',
    'prokaryotes (covered later in the notes)',
    'viruses, because they have a capsid',
    'fungi, because they have chitin walls',
  ], 1, 'Prokaryotic type of cell.'),
  mc('e36', E, 'A capsule around a bacterium is', [
    'the membrane-bound nucleus',
    'an extra layer outside the peptidoglycan wall',
    'a chloroplast making glucose',
    'a tight junction between cells',
  ], 1, 'Wall + capsule surround many prokaryotes.'),
  mc('e37', E, 'Which is more complex and larger?', [
    'a typical prokaryote',
    'a typical eukaryote',
    'a virus',
    'a ribosome by itself',
  ], 1, '10–100 µm vs ~1–10 µm. Viruses are even smaller than both.'),
  mc('e38', E, 'If a cell has plasmids (circular extra DNA), you are looking at a typical', [
    'animal nuclear chromosome only',
    'prokaryote trait from the comparison table',
    'plant central vacuole storing water',
    'fungal chitin sheet outside the cell',
  ], 1, 'Comparison table: prokaryotes have circular DNA (plasmids).')
]

export const PLANT_ANIMAL_QUESTIONS: BioPracticeQuestion[] = [
  mc('pa1', P, 'Animal cells have', [
    'a cellulose wall and one huge central vacuole',
    'no wall, irregular shape, small vacuoles, lysosomes, centrioles',
    'chloroplasts that make the cell green',
    'a peptidoglycan wall plus an outer capsule',
  ], 1, 'Lysosomes = digestion/cleaning. Centrioles = reproduction.', 'plant-animal-cells'),
  mc('pa2', P, 'Plant cells have', [
    'centrioles as their unique listed organelle',
    'cellulose wall, fixed shape, one large vacuole, chloroplasts',
    'no plasma membrane, only a cellulose wall',
    'only lysosomes and no vacuole at all',
  ], 1, 'Chloroplasts: green; convert sunlight to food.', 'plant-animal-cells'),
  mc('pa3', P, 'Lysosomes are specialized in', [
    'plant cells, where they run photosynthesis',
    'animal cells, for digestion and cleaning',
    'all bacterial nucleoid DNA regions',
    'viral envelopes stolen from a host',
  ], 1, 'Know which extra organelles each cell type has in this unit.'),
  mc('pa4', P, 'Centrioles are specialized in', [
    'plant cells for photosynthesis',
    'animal cells for reproduction',
    'all prokaryotes for binary fission',
    'viruses for capsid assembly',
  ], 1, 'Animal-cell reproduction structures in these notes.'),
  mc('pa5', P, 'Chloroplasts', [
    'digest bacteria inside animal cells',
    'make plants green and turn sunlight into food',
    'are peptidoglycan in bacterial walls',
    'are found in typical animal muscle cells',
  ], 1, 'Plant specialized organelle.'),
  mc('pa6', P, 'Plant cell walls are', [
    'inside the membrane, made of protein only',
    'outside the membrane, cellulose, for support',
    'chitin, as in all plant tissues',
    'present in typical animal cells too',
  ], 1, 'Fungi: chitin wall. Animals: NOT PRESENT.'),
  mc('pa7', P, 'Fungal cell walls are', [
    'cellulose',
    'chitin',
    'peptidoglycan',
    'absent; fungi are animals',
  ], 1, 'Plants and fungi ONLY have eukaryotic walls in these notes — different carbs.'),
  mc('pa8', P, 'A plant’s large central vacuole', [
    'matches many tiny animal vacuoles in size role',
    'stores water/food/waste and helps turgor/shape',
    'functions as a second membrane-bound nucleus',
    'pumps three Na⁺ ions out of the cell',
  ], 1, 'It also helps prevent bursting in hypotonic environments. Links Part 1 turgor to Part 2 structure.'),
  mc('pa9', P, 'Animal vacuoles are', [
    'one giant central vacuole like plants',
    'lots of small vacuoles that may store nutrients',
    'chloroplasts that capture sunlight',
    'cellulose walls outside the membrane',
  ], 1, 'Protists may use contractile vacuoles to push out extra water in hypotonic environments.'),
  mc('pa10', P, 'Contractile vacuoles in protists', [
    'are the same organelles as plant chloroplasts',
    'push out extra water in hypotonic environments',
    'make cellulose for a rigid plant-style wall',
    'are found in typical animal tissue cells',
  ], 1, 'Part 1: not in animal cells; freshwater protists like Amoeba. They may also help with movement.'),
  mc('pa11', P, 'Plant cells have a more fixed shape because of', [
    'centrioles',
    'the cell wall',
    'lysosomes only',
    'flagella only',
  ], 1, 'Wall = rigid. Animals = irregular, less rigid.'),
  mc('pa12', P, 'Which set is found in plant cells but not typical animal cells?', [
    'chloroplasts, cellulose wall, large central vacuole',
    'lysosomes and centrioles for cleanup/division',
    'a nucleoid region with circular DNA',
    'peptidoglycan wall plus an outer capsule',
  ], 0, 'This unit’s plant extras: wall, huge vacuole, chloroplasts.'),
  mc('pa13', P, 'Which is listed as animal-specialized (not plant)?', [
    'chloroplasts for photosynthesis',
    'lysosomes and centrioles',
    'a cellulose cell wall',
    'a large central vacuole',
  ], 1, 'Cleaning/digestion and reproduction structures.'),
  mc('pa14', P, 'Both plant and animal cells are', [
    'prokaryotic',
    'eukaryotic',
    'viruses',
    'always 1–5 µm',
  ], 1, 'Both have nuclei and membrane-bound organelles.', 'plant-animal-cells'),
  mc('pa15', P, 'A boxy cell with a huge empty center and green ovals is', [
    'an animal cell packed with lysosomes',
    'a plant cell: wall, central vacuole, chloroplasts',
    'a bacterium with a nucleoid region',
    'a virus particle with only a capsid',
  ], 1, 'Recognize diagrams.', 'plant-animal-cells'),
  mc('pa16', P, 'An irregular cell with small digestive dots and no wall is', [
    'a plant cell with cellulose',
    'an animal cell',
    'a prokaryote with peptidoglycan',
    'cork named by Virchow',
  ], 1, 'No wall, many small vacuoles/lysosomes.', 'plant-animal-cells'),
  multi('pa17', P, 'Choose ALL plant-cell features from this unit.', [
    'cellulose wall outside the membrane',
    'one large central vacuole',
    'chloroplasts',
    'centrioles as the unique listed organelle',
  ], [0, 1, 2], 'Centrioles are listed for animals.'),
  multi('pa18', P, 'Choose ALL animal-cell features from this unit.', [
    'no cell wall / irregular shape',
    'many small vacuoles',
    'lysosomes and centrioles',
    'chloroplasts for food',
  ], [0, 1, 2], 'No chloroplasts in typical animal cells.'),
  mc('pa19', P, 'Cell walls are found in eukaryotes in', [
    'animals and plants in equal amounts',
    'plants and fungi ONLY (not animals)',
    'all animal tissues for extra support',
    'viruses, as part of the capsid shell',
  ], 1, 'Outside the membrane. Structure and support.'),
  mc('pa20', P, 'Layers of complex carbohydrates in eukaryotic walls are', [
    'cellulose in plants and chitin in fungi',
    'peptidoglycan in plants, like bacteria',
    'protein capsids around a genome',
    'cholesterol stacked into a bilayer',
  ], 0, 'Do not mix bacterial peptidoglycan into plants.'),
  mc('pa21', P, 'A wilted plant (from Part 1) has lost water from its', [
    'centrioles used in animal reproduction',
    'large central vacuoles, so turgor dropped',
    'protein capsid around a virus genome',
    'nucleoid region of circular DNA',
  ], 1, 'Structure (vacuole/wall) explains osmosis results.'),
  mc('pa22', P, 'Making energy, proteins, and more cells is true of', [
    'viruses living independently',
    'cells in general (the 3 main jobs)',
    'only cork named by Hooke',
    'only animalcules that are not cells',
  ], 1, 'Connect jobs to later organelles: mitochondria/chloroplasts, ribosomes, mitosis/binary fission.'),
]

export const SURFACES_VIRUS_QUESTIONS: BioPracticeQuestion[] = [
  mc('v1', S, 'Tight junctions in animal cell surfaces are', [
    'pores through cellulose plant walls',
    'interlocking proteins that hold cells together',
    'nucleoids holding circular DNA loops',
    'protein capsids around a virus genome',
  ], 1, 'Interlocking proteins stitch neighboring animal cells.'),
  mc('v2', S, 'Gap junctions', [
    'are plant wall pores, also called plasmodesmata',
    'connect animal cytoplasms so ions and impulses can pass',
    'are peptidoglycan in bacterial cell walls',
    'are virus particles stuck between two cells',
  ], 1, 'Direct passage between animal cells.'),
  mc('v3', S, 'Plasmodesmata are', [
    'animal tight junctions of interlocking proteins',
    'pores in the plant wall that interconnect plant cells',
    'bacterial flagella used for swimming',
    'viral envelopes made of stolen membrane',
  ], 1, 'Allow cytoplasmic exchange, transport, and communication.'),
  mc('v4', S, 'Plants need plasmodesmata for communication because', [
    'plants cannot move, so wall pores share cytoplasm/signals',
    'plants have no plasma membranes at all',
    'animals have cellulose walls that need pores',
    'viruses use them to photosynthesize food',
  ], 0, 'Immobile + walls = need tunnels through walls.'),
  mc('v5', S, 'TRACIE “intercellular joining” examples were', [
    'only ribosomes making protein',
    'tight junctions and plasmodesmata',
    'only the sodium-potassium pump',
    'only Hooke’s empty cork chambers',
  ], 1, 'Part 1 mnemonic meets Part 2 structures.'),
  mc('v6', S, 'Gap junctions vs plasmodesmata', [
    'both connect cytoplasm; gap = animals; plasmodesmata = plant walls',
    'both are bacterial peptidoglycan cell walls',
    'gap junctions are found in plant cells only',
    'plasmodesmata zipper animal cells with interlocking proteins',
  ], 0, 'Same goal, different kingdoms/structures.'),
  mc('v7', S, 'Viruses are described as', [
    'cells that divide by binary fission',
    'infectious particles with some, not all, traits of life',
    'the basic unit of life in cell theory',
    'eukaryotes that contain true nuclei',
  ], 1, 'Not full organisms by cell-theory standards.', 'virus-struct'),
  mc('v8', S, 'Viruses need a ______ to survive and have ______ cells of their own.', [
    'host; no',
    'chloroplast; many',
    'nucleus; plant',
    'vacuole; animal',
  ], 0, 'No cells, no independent energy use.'),
  mc('v9', S, 'Viruses can evolve', [
    'never, because they have no genes at all',
    'rapidly and show genetic variation (strains)',
    'only if they photosynthesize sugars',
    'only inside cork named by Hooke',
  ], 1, 'They have some life traits (genetic change) but not all.'),
  mc('v10', S, 'Compared with prokaryotic and eukaryotic cells, viruses are', [
    'larger than both cell types',
    'much smaller than both cell types',
    'the same size as typical plant cells',
    'always 10–100 µm across',
  ], 1, 'Tiny infectious particles.'),
  mc('v11', S, 'According to these notes, all viruses have', [
    'a nucleus plus mitochondria',
    'a capsid, DNA or RNA genome, and an envelope',
    'peptidoglycan walls and 70s ribosomes',
    'chloroplasts that make sugar from light',
  ], 1, 'Match the slide list for the quiz.', 'virus-struct'),
  mc('v12', S, 'A capsid is', [
    'a plant’s large central vacuole',
    'the virus’s protective protein shell',
    'a gap junction between animal cells',
    'cellulose in a plant wall',
  ], 1, 'Shell around the genome.', 'virus-struct'),
  mc('v13', S, 'A virus genome is', [
    'always DNA, never RNA',
    'nucleic acid made of DNA or RNA',
    'cellulose from a plant wall',
    'only protein with no nucleic acid',
  ], 1, 'Either DNA or RNA.'),
  mc('v14', S, 'Viruses “reproduce” by', [
    'binary fission like bacteria',
    'mitosis like eukaryotic cells',
    'hijacking a cell’s machinery',
    'osmosis through a membrane',
  ], 2, 'They are not cells, so they cannot divide like cells.'),
  mc('v15', S, 'Viruses are NOT cells / not fully alive in this unit because they', [
    'have nuclei and make their own ATP independently',
    'need a host, have no cells, and do not use energy alone',
    'are 10–100 µm eukaryotic cells with organelles',
    'have peptidoglycan walls and 70s ribosomes',
  ], 1, 'Cell theory is about cells. Viruses fail that test.'),
  mc('v16', S, 'Which is smallest?', [
    'typical eukaryotic cell',
    'typical bacterium',
    'virus',
    'a whole plant compared with one cell',
  ], 2, 'Euk > prok > virus in size.'),
  multi('v17', S, 'Choose ALL animal surface structures from this unit.', [
    'tight junctions (interlocking proteins)',
    'gap junctions (cytoplasm connected; ions/impulses)',
    'plasmodesmata through cellulose walls',
    'a nucleoid with circular DNA',
  ], [0, 1], 'Plasmodesmata are plants.'),
  multi('v18', S, 'Choose ALL true of viruses in these notes.', [
    'capsid + genome (DNA or RNA) + envelope',
    'need a host; no cells; no independent energy use',
    'evolve rapidly / have strains',
    'are the basic unit of life in cell theory',
  ], [0, 1, 2], 'They are infectious particles, not cells.'),
  mc('v19', S, 'Holding animal cells together like a zipper of proteins is', [
    'plasmodesmata through a plant wall',
    'tight junctions',
    'binary fission of a bacterium',
    'a virus capsid',
  ], 1, 'Interlocking proteins.'),
  mc('v20', S, 'Letting an impulse jump cell-to-cell in animal tissue is most like', [
    'tight junctions that only hold cells',
    'gap junctions',
    'a fungal chitin wall with no pores',
    'Hooke’s cork chambers that were empty',
  ], 1, 'Gate for molecules, ions, electrical impulses.'),
  mc('v21', S, 'A pore through a plant wall connecting cytoplasm is a', [
    'tight junction of interlocking proteins',
    'plasmodesma (plasmodesmata plural)',
    'lysosome used for digestion',
    'centriole used in animal reproduction',
  ], 1, 'Plant cell surfaces.'),
  mc('v22', S, 'A particle with a protein coat and DNA or RNA but no cytoplasm/ribosomes of its own is a', [
    'prokaryote',
    'eukaryote',
    'virus',
    'plant cell',
  ], 2, 'No ribosomes/cytoplasm = not a cell.', 'virus-struct'),
  mc('v23', S, 'Strains of a virus exist because viruses have', [
    'cellulose walls',
    'genetic variation',
    'nucleoli',
    'central vacuoles',
  ], 1, 'They evolve rapidly.'),
  mc('v24', S, 'Cell theory would classify a virus as', [
    'a living cell with cytoplasm',
    'not a cell, so not a full living organism here',
    'a plant with a cellulose wall',
    'a prokaryote with 70s ribosomes',
  ], 1, 'This is a favorite honors compare question.')
]
