import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const M = 'membrane' as const
const P = 'passive' as const
const A = 'active' as const

export const TRANSPORT_QUIZ_QUESTIONS: BioPracticeQuestion[] = [
  mc('q1', P, 'A substance that can dissolve in water is a', [
    'solute',
    'solvent, because water is what gets dissolved',
    'solution, because dissolving creates a new element',
    'catalyst, because dissolving always needs an enzyme',
  ], 0, 'Solute = the stuff that dissolves. Solvent = the liquid that does the dissolving. Solution = the mixture.'),
  mc('q2', P, 'Water is a good ________ because it dissolves many substances.', [
    'solute',
    'solvent',
    'enzyme',
    'ion pump',
  ], 1, 'Water is the solvent. Sugar, salt, or CO₂ would be solutes in that mixture.'),
  mc('q3', P, 'A mixture of solute plus solvent is a', [
    'gradient',
    'solution',
    'vesicle',
    'bilayer',
  ], 1, 'Salt water: salt is solute, water is solvent, the mix is the solution.'),
  mc('q4', P, 'Because water is polar, textbooks call it a universal', [
    'solute',
    'solvent',
    'protein',
    'hormone',
  ], 1, 'Polarity lets water surround ions and other polar molecules. It does not dissolve every nonpolar lipid equally well.'),
  mc('q5', P, 'Which pairing is correct?', [
    'solute = water; solvent = salt',
    'solute = salt; solvent = water',
    'solution = only the salt crystals',
    'solvent = the finished salt-water mix',
  ], 1, 'Water does the dissolving. Salt is dissolved. The finished mix is the solution.'),
  mc('q6', P, '“Soluble in water” means the substance', [
    'can dissolve in water',
    'is the liquid doing the dissolving',
    'cannot mix with water at all',
    'is already a finished solution',
  ], 0, 'Soluble is the adjective. The dissolved substance is the solute.'),
  mc('q7', P, 'In sugar water, water is the', [
    'solute',
    'solvent',
    'membrane',
    'gradient',
  ], 1, 'The liquid present in greater amount that dissolves the sugar is the solvent.'),
  mc('q8', P, 'Particles moving from high concentration to low concentration is', [
    'active transport',
    'diffusion',
    'exocytosis',
    'phagocytosis',
  ], 1, 'Diffusion is downhill. No ATP. Small molecules such as O₂ do this easily.'),
  mc('q9', P, 'Small molecules such as O₂ cross the membrane most easily by', [
    'phagocytosis of oxygen bubbles',
    'diffusion',
    'the Na+/K+ pump',
    'exocytosis of leftover air',
  ], 1, 'Tiny uncharged gases slip through the bilayer. That is simple diffusion.'),
  mc('q10', P, 'This type of transport requires no ATP.', [
    'active transport',
    'passive transport',
    'endocytosis',
    'exocytosis',
  ], 1, 'Passive = high → low. Active, endocytosis, and exocytosis all spend energy.'),
  mc('q11', P, 'Osmosis is a type of', [
    'active transport',
    'passive transport',
    'phagocytosis',
    'protein pumping',
  ], 1, 'Osmosis is water diffusion across a membrane. Still no ATP.'),
  mc('q12', P, 'The movement of water across the cell membrane is', [
    'osmosis',
    'phagocytosis',
    'exocytosis',
    'binary fission',
  ], 0, 'Water only. Solute moving high → low is diffusion, not osmosis.'),
  mc('q13', P, 'Water enters the cell when the surroundings are', [
    'hypertonic',
    'hypotonic',
    'isotonic',
    'frozen solid',
  ], 1, 'Hypotonic outside = lower solute outside = more free water outside. Water slides in.'),
  mc('q14', P, 'Water leaves the cell when the surroundings are', [
    'hypotonic',
    'hypertonic',
    'isotonic',
    'pure distilled water',
  ], 1, 'Hypertonic outside = more solute outside. Water exits to dilute that solute.'),
  mc('q15', P, 'In this solution the cell does not change size.', [
    'hypotonic',
    'hypertonic',
    'isotonic',
    'distilled water',
  ], 2, 'Equal solute in and out. Water still moves, but rates match.'),
  mc('q16', P, 'Water enters and the cell swells in a ________ solution.', [
    'hypertonic',
    'hypotonic',
    'isotonic',
    'nonaqueous',
  ], 1, 'Low solute outside. Animal cells can burst (cytolysis). Plants become turgid.'),
  mc('q17', P, 'Water exits and the cell shrinks in a ________ solution.', [
    'hypotonic',
    'isotonic',
    'hypertonic',
    'pure-water',
  ], 2, 'High solute outside. Animals shrivel; plants plasmolyze.'),
  mc('q18', P, 'When water moves in and out at the same rate, the system is at', [
    'equilibrium',
    'cytolysis',
    'plasmolysis',
    'active transport',
  ], 0, 'Dynamic equilibrium: motion continues, net change is zero.'),
  mc('q19', P, 'A 10% salt cell is placed in 50% salt water. What happens?', [
    'Water enters and the cell bursts',
    'Water leaves and the cell shrinks',
    'Salt simple-diffuses in until both sides are 50%',
    'Nothing, because 10% and 50% are both “salty”',
  ], 1, 'Outside has more solute, so it is hypertonic. Water leaves to dilute the 50% side.'),
  mc('q20', P, '“Dilute the solute” means water moves', [
    'away from the saltier side',
    'toward the side with more solute',
    'only if the cell spends ATP on water',
    'randomly, with no preferred direction',
  ], 1, 'Water dilutes the crowded/salty side. That is osmosis, not active pumping.'),
  mc('q21', P, 'Cell 10% salt, bath 50% salt. The bath is', [
    'hypotonic to the cell',
    'isotonic to the cell',
    'hypertonic to the cell',
    'pure solvent with no solute',
  ], 2, '50% > 10%, so the surroundings have more solute.'),
  mc('q22', P, 'Cell 10% salt, bath 50% salt. Compared with the bath, the cell is', [
    'hypertonic',
    'hypotonic',
    'isotonic',
    'a virus',
  ], 1, 'The cell has lower solute, so the cell is hypotonic to the solution.'),
  mc('q23', P, 'If the cell is 90% water and the beaker is 60% water, water will', [
    'enter the cell',
    'leave the cell',
    'stop moving completely',
    'turn into salt',
  ], 1, 'More free water inside. Water slides out. The outside is the saltier/hypertonic side.'),
  mc('q24', P, 'Transport that uses a protein channel but no ATP is', [
    'the sodium-potassium pump',
    'facilitated diffusion',
    'exocytosis',
    'phagocytosis',
  ], 1, 'Sugar and other larger/polar molecules often need a channel or carrier. Direction is still high → low.'),
  mc('q25', P, 'Larger molecules such as sugar cross through a protein with no energy by', [
    'simple diffusion through the tails',
    'facilitated diffusion',
    'endocytosis of every sugar crystal',
    'the Na+/K+ pump',
  ], 1, 'Glucose is too polar/large for the oily core. Protein help ≠ energy.'),
  mc('q26', P, 'Which process uses protein channels to get molecules in without ATP?', [
    'active transport',
    'facilitated diffusion',
    'exocytosis',
    'phagocytosis',
  ], 1, 'Channel = facilitated if cargo still goes down the gradient.'),
  mc('q27', P, 'Which statement about osmosis is accurate?', [
    'It is active pumping of water by ATP',
    'It is water moving across a membrane down its gradient',
    'It is the same as phagocytosis of food',
    'It only happens in plant cells',
  ], 1, 'Water, membrane, high water → low water. Aquaporins speed it but do not make it active.'),
  mc('q28', P, 'A red blood cell in distilled water will most likely', [
    'shrivel',
    'swell',
    'stay the same size',
    'grow a cell wall',
  ], 1, 'Distilled water is hypotonic. Animals have no wall, so cytolysis is the risk.'),
  mc('q29', P, 'A red blood cell in very salty water will most likely', [
    'burst',
    'shrivel',
    'become turgid',
    'divide',
  ], 1, 'Hypertonic bath. Water leaves. Animal cells prefer isotonic.'),
  mc('q30', P, 'Which environment is isotonic to a typical animal cell?', [
    'distilled water',
    'about 0.9% saline',
    '50% salt water',
    'pure corn oil',
  ], 1, 'Hospital IV fluid is isotonic so red blood cells keep their shape.'),
  mc('q31', P, 'Grocery stores mist vegetables to keep them in a slightly ________ solution so cells stay firm.', [
    'hypertonic',
    'hypotonic',
    'isotonic',
    'nonaqueous',
  ], 1, 'Water enters plant cells. Walls prevent bursting; turgor makes produce look crisp.'),
  mc('q32', P, 'Which molecule can cross by simple diffusion, no protein?', [
    'Na⁺',
    'O₂',
    'glucose',
    'a folded enzyme',
  ], 1, 'Small uncharged gas. Ions, glucose, and proteins need help or vesicles.'),
  mc('q33', P, 'Net diffusion stops when', [
    'ATP runs out',
    'equilibrium is reached',
    'the nucleus turns off',
    'the cell wall dissolves',
  ], 1, 'Molecules still bounce both ways. Net movement is zero.'),
  mc('q34', P, 'A concentration gradient means', [
    'solute is equal on both sides',
    'solute is unequal on the two sides',
    'there is no membrane',
    'the cell has no water',
  ], 1, 'Unequal amounts. Passive net flow needs this difference.'),
  mc('q35', P, 'Which list is only passive transport?', [
    'endocytosis, exocytosis, pumps',
    'diffusion, osmosis, facilitated diffusion',
    'phagocytosis and pinocytosis',
    'Na+/K+ pump and vesicle export',
  ], 1, 'All three go high → low and skip ATP.'),
  mc('q36', P, 'Facilitated diffusion and simple diffusion both', [
    'require ATP',
    'go high → low',
    'use vesicles',
    'move cargo low → high',
  ], 1, 'Only facilitated needs a membrane protein.'),
  mc('q37', P, 'If you only remember one osmosis rule, water moves', [
    'toward higher solute',
    'toward lower solute',
    'only into animal cells',
    'only when a pump fires',
  ], 0, 'Dilute the solute. High water → low water is the same sentence.'),
  mc('q38', P, 'Cell 5% salt in 5% salt water. After 20 minutes the cell should', [
    'burst',
    'shrivel',
    'keep about the same size',
    'lose its membrane',
  ], 2, 'Isotonic. No net water flow.'),
  mc('q39', P, 'Which wording matches a hypotonic solution?', [
    'more solute outside',
    'less solute outside',
    'equal solute both sides',
    'no water anywhere',
  ], 1, 'Hypo = low solute outside. Water in. Swell.'),
  mc('q40', P, 'Which wording matches a hypertonic solution?', [
    'less solute outside',
    'more solute outside',
    'equal solute both sides',
    'only gases outside',
  ], 1, 'Hyper = high solute outside. Water out. Shrink.'),
  mc('q41', P, 'A dialysis bag of 20% starch in a beaker of distilled water. The bag is starch-impermeable, water-permeable. The bag will', [
    'lose starch and collapse',
    'gain water and swell',
    'pump starch out with ATP',
    'stay exactly the same mass',
  ], 1, 'Starch stays. The bag is hypertonic to the beaker, so water enters.'),
  mc('q42', P, 'Same bag: 20% starch in distilled water. The beaker is', [
    'hypertonic to the bag',
    'hypotonic to the bag',
    'isotonic to the bag',
    'impermeable to water',
  ], 1, 'Almost no solute outside. Water rushes toward the starch.'),
  mc('q43', P, 'Elodea in salt water looks wilted because of', [
    'cytolysis',
    'plasmolysis',
    'photosynthesis shutting off instantly',
    'the wall dissolving',
  ], 1, 'Water left. Membrane pulls away from the wall.'),
  mc('q44', P, 'Which cell is happiest in a hypotonic environment?', [
    'animal red blood cell',
    'plant cell',
    'a virus particle',
    'an animal cell with no wall',
  ], 1, 'Wall + large vacuole. Turgid is the healthy plant state. Animals prefer isotonic.'),
  mc('q45', P, 'Which process is NOT passive?', [
    'osmosis',
    'facilitated diffusion of glucose downhill',
    'O₂ diffusion',
    'the sodium-potassium pump',
  ], 3, 'The pump spends ATP and runs against both ion gradients.'),
  mc('q46', P, 'Aquaporins make osmosis faster. That process is still', [
    'active, because a protein is involved',
    'passive',
    'exocytosis',
    'phagocytosis',
  ], 1, 'A protein helper does not automatically mean ATP.'),
  mc('q47', P, 'A U-tube has 8% salt on the left and 2% salt on the right. Membrane lets water only. Net water flow is', [
    'left → right',
    'right → left',
    'zero from the first second',
    'salt crossing to the right',
  ], 1, 'More free water on the 2% side. Water moves left to dilute the 8%.'),
  mc('q48', P, 'Why don’t cells spend ATP to import O₂?', [
    'O₂ cannot cross membranes at all',
    'O₂ already moves in by simple diffusion',
    'O₂ is pumped only by the Na+/K+ pump',
    'O₂ enters only by phagocytosis',
  ], 1, 'If the gradient already favors entry, paying ATP would be waste.'),
  mc('q49', P, 'Which pair both describe the SAME water movement?', [
    'high water → low water, and toward higher solute',
    'high water → low water, and toward lower solute',
    'low water → high water, and no membrane needed',
    'water only moves if a vesicle forms',
  ], 0, 'Those two phrases are the osmosis rule said two ways.'),
  multi('q50', P, 'Choose ALL that are true of a 10% salt cell in 50% salt water.', [
    'The outside solution is hypertonic',
    'Water leaves the cell',
    'The cell shrinks',
    'Water enters and the cell bursts',
  ], [0, 1, 2], 'Dilute the 50% solute. Water out.'),

  mc('q51', A, 'This type of transport requires energy.', [
    'passive transport',
    'osmosis',
    'active transport',
    'simple diffusion',
  ], 2, 'Energy (usually ATP) is the definition of active transport.'),
  mc('q52', A, 'Moving a substance from low concentration to high concentration requires', [
    'no energy',
    'energy',
    'only a cellulose wall',
    'only osmosis',
  ], 1, 'Against the gradient = pay ATP or another energy source.'),
  mc('q53', A, 'Bulk transport of material INTO the cell is', [
    'exocytosis',
    'endocytosis',
    'osmosis',
    'diffusion',
  ], 1, 'Endo = in. Vesicles pinch inward. ATP required.'),
  mc('q54', A, 'When a vesicle fuses and dumps material OUT of the cell, that is', [
    'endocytosis',
    'exocytosis',
    'osmosis',
    'facilitated diffusion',
  ], 1, 'Exo = exiting. Hormones, proteins, and nerve signals use this.'),
  mc('q55', A, 'The bulk transport of material out of the cell is', [
    'phagocytosis',
    'pinocytosis',
    'exocytosis',
    'osmosis',
  ], 2, 'Bulk out = exocytosis. Phago/pino are types of endocytosis (in).'),
  mc('q56', A, 'A cell taking in large debris or food is using', [
    'osmosis',
    'phagocytosis',
    'simple diffusion',
    'facilitated diffusion',
  ], 1, 'Phago = eat. Large particles. Active.'),
  mc('q57', A, 'A protein that pumps ions using energy is doing', [
    'osmosis',
    'facilitated diffusion',
    'active transport',
    'simple diffusion',
  ], 2, 'Pump + ATP + often against the gradient. Not a passive channel.'),
  mc('q58', A, 'Ions moved low → high by a transport protein and ATP is', [
    'osmosis',
    'a pump / active transport',
    'simple diffusion',
    'equilibrium',
  ], 1, 'Classic protein pump. The Na+/K+ pump is the unit example.'),
  mc('q59', A, 'Which process is bulk IN, not bulk OUT?', [
    'exocytosis',
    'endocytosis',
    'diffusion',
    'osmosis',
  ], 1, 'Vesicle from the surface inward.'),
  mc('q60', A, 'Which process is bulk OUT, not bulk IN?', [
    'phagocytosis',
    'pinocytosis',
    'exocytosis',
    'receptor-mediated endocytosis',
  ], 2, 'The other three all bring cargo in.'),
  mc('q61', A, 'Which needs ATP?', [
    'O₂ crossing the bilayer',
    'water through aquaporins',
    '3 Na⁺ out and 2 K⁺ in',
    'glucose high → low on a carrier',
  ], 2, 'Na+/K+ pump is active. The others are passive.'),
  mc('q62', A, 'A macrophage eating a bacterium is', [
    'osmosis',
    'phagocytosis',
    'facilitated diffusion',
    'simple diffusion',
  ], 1, 'Large particle. Immune cell-eating.'),
  mc('q63', A, 'Sipping a bit of extracellular fluid is', [
    'phagocytosis',
    'pinocytosis',
    'osmosis',
    'simple diffusion',
  ], 1, 'Pino = drink. Still endocytosis, still active.'),
  mc('q64', A, 'Which comparison is correct?', [
    'passive: low → high; active: high → low',
    'passive: high → low; active: low → high',
    'both always need ATP',
    'both never use proteins',
  ], 1, 'Direction plus energy is the first test question they write.'),
  mc('q65', A, 'Which uses a vesicle, not just a channel?', [
    'facilitated diffusion of glucose',
    'exocytosis of a protein hormone',
    'osmosis through aquaporins',
    'O₂ leaving a lung cell',
  ], 1, 'Huge cargo → vesicle. Small solutes → protein or bilayer.'),
  mc('q66', A, 'If a poison blocks ATP, which stops first?', [
    'simple diffusion of CO₂',
    'osmosis of water',
    'the sodium-potassium pump',
    'facilitated diffusion of glucose downhill',
  ], 2, 'Only the pump has to pay energy every cycle.'),
  mc('q67', A, 'After exocytosis, the vesicle membrane', [
    'vanishes',
    'becomes part of the plasma membrane',
    'turns into a cell wall',
    'becomes a nucleus',
  ], 1, 'Fusion adds membrane to the surface. Endocytosis does the reverse.'),
  mc('q68', A, 'The Na+/K+ pump moves', [
    '2 Na⁺ out and 3 K⁺ in',
    '3 Na⁺ out and 2 K⁺ in',
    '3 Na⁺ in and 2 K⁺ out',
    'glucose and water together',
  ], 1, '3 out / 2 in. Inside becomes slightly negative. Salty banana: Na⁺ out, K⁺ in.'),
  mc('q69', A, '“Salty banana” reminds you that a resting cell has', [
    'high Na⁺ in and high K⁺ out',
    'high Na⁺ out and high K⁺ in',
    'equal Na⁺ and K⁺ everywhere',
    'no ions at all',
  ], 1, 'Banana = potassium inside. Salty = sodium outside. The pump maintains that.'),
  mc('q70', A, 'Which list is only active transport?', [
    'osmosis and diffusion',
    'endocytosis, exocytosis, and pumps',
    'facilitated diffusion and aquaporins',
    'O₂ and CO₂ crossing the tails',
  ], 1, 'Vesicles and pumps cost energy. The others do not.'),
  mc('q71', A, 'Receptor-mediated endocytosis is used when the cell must', [
    'let O₂ leak through tails',
    'bind one specific molecule, then engulf it',
    'export a hormone it just made',
    'move water through aquaporins',
  ], 1, 'Lock-and-key receptor, then the membrane swallows that cargo. Cholesterol and many hormones use this.'),
  mc('q72', A, 'Which statement is FALSE?', [
    'Endocytosis needs ATP',
    'Exocytosis needs ATP',
    'Facilitated diffusion needs ATP',
    'The Na+/K+ pump needs ATP',
  ], 2, 'Protein help is not the same as energy.'),
  mc('q73', A, 'Nerve cells release signal chemicals by', [
    'osmosis',
    'exocytosis',
    'simple diffusion of whole vesicles through tails',
    'phagocytosis of the synapse',
  ], 1, 'Vesicles fuse at the membrane and dump neurotransmitter out.'),
  mc('q74', A, 'Pinocytosis vs phagocytosis: the difference is mainly', [
    'only phago uses ATP',
    'cargo size: sip of fluid vs large particles',
    'only pino is passive',
    'only phago happens in plants',
  ], 1, 'Both are active endocytosis. Drink vs eat.'),
  multi('q75', A, 'Choose ALL examples of active transport.', [
    'endocytosis',
    'exocytosis',
    'protein pumps',
    'osmosis of water downhill',
  ], [0, 1, 2], 'Osmosis is passive even though water is essential.'),

  mc('q76', M, 'The cell membrane’s job in transport is to be', [
    'fully open to every molecule',
    'selectively permeable',
    'a cellulose wall',
    'a virus capsid',
  ], 1, 'Some things cross easily, some need proteins, some need vesicles. That control is homeostasis.'),
  mc('q77', M, 'Selectively permeable means the membrane', [
    'lets only certain substances through',
    'blocks water permanently',
    'lets every ion through the tails',
    'exists only in plant cells',
  ], 0, 'Also called semipermeable. Size, charge, and polarity decide the path.'),
  mc('q78', M, 'Which set crosses the bilayer with no protein?', [
    'Na⁺ and glucose',
    'O₂ and CO₂',
    'starch and proteins',
    'K⁺ and Cl⁻',
  ], 1, 'Small uncharged gases. Ions and large polar molecules do not.'),
  mc('q79', M, 'Ions need a protein because they are', [
    'gases',
    'charged',
    'identical to cholesterol',
    'too hydrophobic',
  ], 1, 'The nonpolar tail region repels charge. Channels or pumps are required.'),
  mc('q80', M, 'Glucose usually needs a protein because it is', [
    'a tiny uncharged gas',
    'large and polar',
    'already an ion pump',
    'a steroid lipid',
  ], 1, 'Downhill + protein = facilitated diffusion. Uphill + protein + ATP = active.'),
  mc('q81', M, 'Homeostasis at the membrane means the cell', [
    'blocks every molecule forever',
    'keeps a stable inside by controlling traffic',
    'always stays hypertonic to blood',
    'never uses proteins',
  ], 1, 'Right amounts of water, ions, nutrients, and wastes.'),
  mc('q82', M, 'A channel protein is best described as', [
    'a pore molecules can pass through',
    'a vesicle that fuses and dumps cargo',
    'a 4-ring steroid among the tails',
    'cellulose stacked outside the cell',
  ], 0, 'If the cargo still goes high → low, that channel is facilitated diffusion.'),
  mc('q83', M, 'Which membrane part buffers fluidity as temperature changes?', [
    'cellulose',
    'cholesterol',
    'DNA',
    'starch',
  ], 1, 'Steroid lipid among the tails. Too hot or too cold both wreck the bilayer without it.'),
  mc('q84', M, 'Heads face water and tails hide inside because phospholipids are', [
    'fully hydrophobic',
    'amphipathic',
    'nucleic acids',
    'ions',
  ], 1, 'Polar head + nonpolar tails. That oily middle is why the membrane is selective.'),
  mc('q85', M, 'Which molecule is the actual solvent of the cytoplasm?', [
    'cholesterol',
    'water',
    'cellulose',
    'DNA',
  ], 1, 'Water dissolves the cell’s solutes. That is why osmosis matters so much.'),
  mc('q86', P, 'A cell at 2% solute is placed in 2% solute. Net water movement is', [
    'in only',
    'out only',
    'zero net, equal rates both ways',
    'impossible because solute blocks water',
  ], 2, 'Isotonic / equilibrium. Size stays the same.'),
  mc('q87', P, 'Which trap sentence is WRONG?', [
    'Hypotonic: water in, cell swells',
    'Hypertonic: water out, cell shrinks',
    'Isotonic: no net water movement',
    'Hypertonic: water in, cell bursts',
  ], 3, 'Hyper never pulls water in. Hyper pulls water out.'),
  mc('q88', P, 'Cell 12% salt in 4% salt water. Predict.', [
    'Water leaves; cell shrinks',
    'Water enters; cell swells',
    'No water movement is possible',
    'The cell becomes a plant cell',
  ], 1, 'Outside has less solute = hypotonic bath. Dilute the 12% inside by sending water in.'),
  mc('q89', A, 'Which is the best match for “vesicle forces material out”?', [
    'endocytosis',
    'exocytosis',
    'osmosis',
    'facilitated diffusion',
  ], 1, 'Fusion from the inside. Bulk export.'),
  mc('q90', A, 'Which is the best match for “bulk transportation of material into the cell”?', [
    'exocytosis',
    'endocytosis',
    'diffusion',
    'osmosis',
  ], 1, 'Includes pinocytosis, phagocytosis, and receptor-mediated endocytosis.'),
  mc('q91', P, 'Osmosis requires all of the following EXCEPT', [
    'water',
    'a membrane water can cross',
    'a difference in water/solute',
    'ATP',
  ], 3, 'No energy. If they add ATP to the osmosis definition, that item is wrong.'),
  mc('q92', P, 'Facilitated diffusion requires a protein. It does NOT require', [
    'a membrane',
    'a gradient',
    'ATP',
    'the cargo to be able to bind or fit the protein',
  ], 2, 'That is the honors trap: protein ≠ active.'),
  mc('q93', P, 'If both sides already have the same 8% sugar, adding more sugar to the left will make water', [
    'move left',
    'move right',
    'stop existing',
    'require a vesicle',
  ], 0, 'Left just became hypertonic. Water follows the new solute.'),
  mc('q94', A, 'Which process would export a bulky protein the cell just built?', [
    'osmosis',
    'simple diffusion through tails',
    'exocytosis',
    'facilitated diffusion',
  ], 2, 'A folded protein is far too big for a channel. Vesicle fusion dumps it out.'),
  mc('q95', M, 'Which crossing path matches each cargo?', [
    'O₂: diffusion; glucose downhill: facilitated; 3 Na⁺ out: pump',
    'O₂: phagocytosis; glucose: osmosis; Na⁺: simple diffusion',
    'O₂: pump; glucose: osmosis; Na⁺: diffusion through tails',
    'All three must use exocytosis',
  ], 0, 'Match size, charge, and direction to the process. That is the actual quiz skill.'),
  mc('q96', P, 'A plant cell and an animal cell are both put in distilled water. The safer cell is the', [
    'animal cell, because it can burst usefully',
    'plant cell, because wall and vacuole hold the extra water',
    'virus, because it is not a cell',
    'animal cell, because it has centrioles',
  ], 1, 'Same hypotonic bath, different outcome. Know cytolysis vs turgid.'),
  mc('q97', P, 'A plant cell and an animal cell are both put in 20% salt. Both', [
    'burst',
    'lose water',
    'become turgid',
    'gain mass',
  ], 1, 'Hypertonic is bad for both. Animal shrivels; plant plasmolyzes.'),
  mc('q98', P, 'Which number set makes the OUTSIDE hypotonic?', [
    'cell 10% salt, outside 50% salt',
    'cell 10% salt, outside 2% salt',
    'cell 10% salt, outside 10% salt',
    'cell 0% water, outside 0% water',
  ], 1, '2% < 10%, so outside has less solute. Water enters.'),
  mc('q99', A, 'Which sentence correctly uses ALL the quiz verbs?', [
    'Diffusion is passive; pumps and endo/exocytosis are active',
    'Osmosis is active; diffusion is a pump',
    'Phagocytosis is osmosis of food',
    'Facilitated diffusion spends ATP to push sugar uphill',
  ], 0, 'If you can sort those four words, you can pass the transport quiz.'),
  multi('q100', P, 'Choose ALL correct solution vocab.', [
    'Solute dissolves',
    'Solvent does the dissolving',
    'Solution is the mixture',
    'Water is called the universal solute',
  ], [0, 1, 2], 'Water is the universal solvent, not the solute.'),
]
