import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const H = 'history' as const
const E = 'prok-euk' as const
const P = 'plant-animal' as const
const S = 'surfaces' as const

export const HISTORY_QUESTIONS: BioPracticeQuestion[] = [
  mc('h1', H, 'Robert Hooke (1665) used a primitive microscope to look at', [
    'living bacteria swimming',
    'cork and saw tiny chambers he named “cells” (actually dead plant cells)',
    'DNA helices',
    'viruses’ envelopes',
  ], 1, 'He named cells. They were empty dead plant-cell walls in cork.'),
  mc('h2', H, 'Anton van Leeuwenhoek was first to', [
    'say all plants are made of cells',
    'observe microorganisms and call them “animalcules” (little animals)',
    'prove cells come only from cells',
    'name the nucleus',
  ], 1, 'Animalcules = microbes he saw with better lenses.'),
  mc('h3', H, 'Matthias Schleiden proposed that', [
    'all animals are made of cells',
    'all plants are made of cells',
    'viruses are cells',
    'cork is made of animal tissue',
  ], 1, 'Schleiden → plants.'),
  mc('h4', H, 'Theodor Schwann proposed that', [
    'all plants are made of cells',
    'all animals are made of cells (remember “swan”)',
    'all cells come from crystals',
    'bacteria have nuclei',
  ], 1, 'Schwann → animals. Mnemonic: swan.'),
  mc('h5', H, 'Rudolf Virchow proposed that', [
    'cells spontaneously appear from mud',
    'all cells come from pre-existing cells',
    'only plants have cells',
    'viruses are the basic unit of life',
  ], 1, 'No spontaneous generation of cells — cells from cells.'),
  mc('h6', H, 'Cell theory was built by combining work of', [
    'only Hooke',
    'Hooke, Leeuwenhoek, Schleiden, Schwann, and Virchow (among these notes)',
    'only Watson and Crick',
    'only macrophages',
  ], 1, 'History names are fair game on quizzes.'),
  mc('h7', H, 'The three parts of cell theory are', [
    'all living things are made of cells; cells are the basic unit of life; all cells come from other cells',
    'all cells have chloroplasts; all cells have walls; all cells are bacteria',
    'viruses are alive; cells appear from salt; energy is optional',
    'only animals have cells; plants do not; fungi do not',
  ], 0, 'Memorize all three exactly.'),
  mc('h8', H, '“Cells are the basic unit of life” means', [
    'organs are smaller than atoms',
    'the cell is the smallest living/functional unit',
    'viruses are cells',
    'only cork is alive',
  ], 1, 'Tissues and organs are made OF cells.'),
  mc('h9', H, 'Which scientist matches “all plants are cells”?', [
    'Schwann',
    'Schleiden',
    'Virchow',
    'Leeuwenhoek',
  ], 1, 'Schleiden plants, Schwann animals.'),
  mc('h10', H, 'Which scientist matches “all animals are cells”?', [
    'Schleiden',
    'Schwann',
    'Hooke',
    'Virchow',
  ], 1, 'Swan → Schwann → animals.'),
  mc('h11', H, 'Which scientist matches “cells come from cells”?', [
    'Hooke',
    'Virchow',
    'Schleiden',
    'Leeuwenhoek',
  ], 1, 'Virchow.'),
  mc('h12', H, 'Hooke’s “cells” in cork were', [
    'living animalcules',
    'dead plant cells (empty chambers)',
    'viruses',
    'nuclei he stained',
  ], 1, 'Cork is bark — dead plant tissue.'),
  multi('h13', H, 'Choose ALL parts of cell theory.', [
    'All living things are made of cells',
    'Cells are the basic unit of life',
    'All cells come from other cells',
    'All cells are eukaryotic',
  ], [0, 1, 2], 'Bacteria are prokaryotic cells and still count.'),
  mc('h14', H, 'Why is Virchow’s idea a rejection of spontaneous generation of cells?', [
    'It says new cells only come from existing cells',
    'It says cork creates animals',
    'It says viruses are cells',
    'It says plants have no cells',
  ], 0, 'Life from life, at the cell level.'),
  mc('h15', H, 'Leeuwenhoek’s animalcules were', [
    'cork chambers',
    'microorganisms',
    'chloroplasts',
    'capsids',
  ], 1, 'First look at microbes.'),
  mc('h16', H, 'If a question asks who NAMED cells, pick', [
    'Virchow',
    'Hooke',
    'Schwann',
    'Schleiden',
  ], 1, 'Name vs theory contributions are different.'),
  mc('h17', H, 'Cell theory applies to', [
    'animals only',
    'all living things (plants, animals, fungi, protists, bacteria)',
    'viruses because they have capsids',
    'only cork',
  ], 1, 'Viruses are not cells and are not fully alive by this unit’s rules.'),
  mc('h18', H, 'A new bacterium appearing only after another bacterium splits supports', [
    'Hooke naming cork',
    'Virchow / “all cells from cells” and also prokaryotic binary fission',
    'Schwann’s animal-only idea as the whole theory',
    'viruses being cells',
  ], 1, 'Reproduction of cells is part of theory + prokaryote notes.'),
]

export const PROK_EUK_QUESTIONS: BioPracticeQuestion[] = [
  mc('e1', E, 'Eukaryotes include', [
    'bacteria only',
    'plants, animals, protists, and fungi',
    'viruses',
    'only archaea',
  ], 1, 'Eu = true nucleus.'),
  mc('e2', E, 'Prokaryotes in this unit are', [
    'plants',
    'bacteria (and archaea, covered later)',
    'fungi',
    'protists',
  ], 1, 'Pro rhymes with no — no nucleus.'),
  mc('e3', E, 'ALL cells have', [
    'a nucleus, chloroplasts, and a cellulose wall',
    'cytoplasm, ribosomes, a cell membrane, and genetic material (DNA or RNA)',
    'mitochondria and a nucleolus',
    'lysosomes and centrioles',
  ], 1, 'Ribosomes make proteins and are NOT considered an organelle here.'),
  mc('e4', E, 'Ribosomes', [
    'are membrane-bound organelles',
    'make proteins and are NOT considered an organelle in these notes',
    'store DNA in eukaryotes only',
    'are cellulose',
  ], 1, 'That is why prokaryotes can still make protein with no nucleus.'),
  mc('e5', E, 'Prokaryotic cells are', [
    'always multicellular',
    'all unicellular, smaller (about 1–5 µm in one slide; most bacteria 1–10 µm), with NO nucleus or membrane-bound organelles',
    '10–100 µm with linear DNA in a nucleus',
    'always full of chloroplasts',
  ], 1, 'Pro = no nucleus. Comparison slide also lists 1–10 µm.'),
  mc('e6', E, 'A nucleoid is', [
    'a true nucleus with a membrane',
    'the region of a prokaryote that contains circular DNA',
    'a chloroplast',
    'a capsid',
  ], 1, 'No nuclear membrane. DNA is a loop, plus plasmids may be present.', 'prok-cell'),
  mc('e7', E, 'Bacterial cell walls are made of', [
    'cellulose',
    'chitin',
    'peptidoglycan (plus an outer capsule may surround them)',
    'cholesterol only',
  ], 2, 'Plants = cellulose. Fungi = chitin. Bacteria = peptidoglycan.'),
  mc('e8', E, 'Prokaryotic ribosomes are', [
    '80s',
    '70s (smaller than eukaryotic)',
    'absent',
    'the same as chloroplasts',
  ], 1, '70s vs 80s is a classic honors compare item.'),
  mc('e9', E, 'Prokaryotes reproduce by', [
    'mitosis',
    'binary fission (“b” for bacteria)',
    'endocytosis',
    'making spores in a nucleus',
  ], 1, 'No mitosis because no nucleus/mitotic spindle like eukaryotes.'),
  mc('e10', E, 'Some prokaryotes move with', [
    'plasmodesmata',
    'flagella',
    'tight junctions',
    'chloroplasts',
  ], 1, 'Whip-like flagella.'),
  mc('e11', E, 'Eukaryotic cells', [
    'are unicellular only',
    'can be unicellular or multicellular; 10–100 µm; have a nucleus with linear DNA and a nucleolus',
    'never have cell walls',
    'have 70s ribosomes and a nucleoid',
  ], 1, 'Eu = true nucleus. Membrane-bound organelles present.'),
  mc('e12', E, 'Eukaryotic ribosomes are', [
    '70s',
    '80s (larger)',
    'missing',
    'made of peptidoglycan',
  ], 1, 'Larger than bacterial ribosomes.'),
  mc('e13', E, 'Eukaryotes reproduce using', [
    'binary fission as the notes’ main method',
    'mitosis',
    'only budding of capsids',
    'Hooke’s cork method',
  ], 1, 'Mitosis for cell division (this unit).'),
  mc('e14', E, 'Plant and fungi eukaryotic cells have a', [
    'peptidoglycan wall',
    'cell wall (cellulose in plants, chitin in fungi)',
    'wall of cholesterol',
    'capsid',
  ], 1, 'Animals: NO cell wall.'),
  mc('e15', E, 'Most eukaryotic cells are about', [
    '1–10 micrometers',
    '10–100 micrometers (0.01–0.1 mm)',
    'the thickness of a house',
    'always smaller than bacteria',
  ], 1, 'Bacteria ~1–10 µm. Average human hair ~0.016–0.05 mm thick — so many eukaryotic cells are in a similar size ballpark as hair thickness.'),
  mc('e16', E, '1 micrometer equals', [
    '1 mm',
    '0.001 mm',
    '1 m',
    '10 mm',
  ], 1, 'Notes: 1–10 µm = 0.001–0.01 mm for many bacteria; 10–100 µm = 0.01–0.1 mm for most eukaryotic cells.'),
  mc('e17', E, 'Circular DNA (plasmids / nucleoid) is a ______ trait.', [
    'eukaryotic',
    'prokaryotic',
    'viral envelope only',
    'plant-only',
  ], 1, 'Eukaryotes: linear DNA in a nucleus.'),
  mc('e18', E, 'Linear DNA in a nucleus is a ______ trait.', [
    'prokaryotic',
    'eukaryotic',
    'all viruses',
    'peptidoglycan',
  ], 1, 'True nucleus.'),
  mc('e19', E, 'Unicellular ONLY describes', [
    'eukaryotes',
    'prokaryotes (in these notes)',
    'plants',
    'animals',
  ], 1, 'Some protists and fungi are unicellular eukaryotes, but eukaryotes can also be multicellular.'),
  mc('e20', E, 'Which can be unicellular OR multicellular?', [
    'prokaryotes only',
    'eukaryotes (some protists & fungi unicellular; plants/animals multicellular)',
    'all bacteria',
    'all viruses',
  ], 1, 'Do not say all eukaryotes are multicellular.'),
  mc('e21', E, 'Membrane-bound organelles are found in', [
    'prokaryotes',
    'eukaryotes',
    'all viruses',
    'peptidoglycan',
  ], 1, 'No nucleus OR membrane-bound organelles in prokaryotes.'),
  mc('e22', E, 'Which structure is found in BOTH prokaryotes and eukaryotes?', [
    'nucleus',
    'mitochondria',
    'cell membrane',
    'chloroplasts',
  ], 2, 'Shared: cytoplasm, ribosomes, membrane, genetic material.'),
  mc('e23', E, 'Which is NOT a shared feature of all cells?', [
    'cytoplasm',
    'ribosomes',
    'nucleus',
    'cell membrane',
  ], 2, 'Nucleus is eukaryotic only.'),
  mc('e24', E, 'A cell 2 µm across with a nucleoid and peptidoglycan wall is', [
    'a plant cell',
    'a prokaryote (bacterium)',
    'an animal cell',
    'a virus',
  ], 1, 'Size + no nucleus + peptidoglycan.', 'prok-cell'),
  mc('e25', E, 'A cell 50 µm across with a nucleolus is', [
    'a typical bacterium',
    'eukaryotic',
    'too small to be eukaryotic',
    'a virus',
  ], 1, '10–100 µm + true nucleus.'),
  mc('e26', E, 'The three main jobs of cells are', [
    'make energy, make proteins, make more cells',
    'make cork, make animalcules, make viruses',
    'only osmosis',
    'only phagocytosis',
  ], 0, 'Energy for activities, proteins do the work, more cells for growth/replacement.'),
  mc('e27', E, 'Cells make proteins because proteins', [
    'are cellulose walls',
    'do all the work in cells',
    'are only found in viruses',
    'are cholesterol',
  ], 1, 'Job 2 of cells.'),
  mc('e28', E, 'Cells make more cells for', [
    'capsid assembly in all organisms',
    'growth and replacement',
    'osmosis only',
    'making peptidoglycan in animals',
  ], 1, 'Job 3.'),
  multi('e29', E, 'Choose ALL that ALL cells have.', [
    'cytoplasm',
    'ribosomes',
    'cell membrane',
    'nucleus',
  ], [0, 1, 2], 'Genetic material too. Not a nucleus.'),
  multi('e30', E, 'Choose ALL prokaryote traits.', [
    'no nucleus / no membrane-bound organelles',
    'circular DNA in a nucleoid',
    '70s ribosomes and binary fission',
    'cellulose wall and mitosis',
  ], [0, 1, 2], 'Cellulose + mitosis are eukaryotic plant traits.'),
  multi('e31', E, 'Choose ALL eukaryote traits.', [
    'nucleus with linear DNA and nucleolus',
    'membrane-bound organelles',
    '80s ribosomes and mitosis',
    'peptidoglycan wall required in animals',
  ], [0, 1, 2], 'Animal eukaryotes have no wall. Bacteria have peptidoglycan.'),
  mc('e32', E, '“Pro rhymes with no” is a mnemonic for', [
    'no ribosomes',
    'no nucleus (and no membrane-bound organelles)',
    'no DNA',
    'no membrane',
  ], 1, 'They still have DNA, ribosomes, cytoplasm, and a membrane.'),
  mc('e33', E, '“Eu = true nucleus” means eukaryotes have', [
    'a nucleoid only',
    'a membrane-bound nucleus',
    'no DNA',
    'only RNA viruses',
  ], 1, 'Nucleolus is inside that nucleus.'),
  mc('e34', E, 'Which cell-wall chemistry is matched correctly?', [
    'bacteria — cellulose; plants — peptidoglycan; fungi — chitin',
    'bacteria — peptidoglycan; plants — cellulose; fungi — chitin',
    'all three — chitin',
    'animals — cellulose',
  ], 1, 'Animals: no wall.'),
  mc('e35', E, 'Archaea are grouped with', [
    'plants',
    'prokaryotes (notes say they will be covered later)',
    'viruses',
    'fungi',
  ], 1, 'Prokaryotic type of cell.'),
  mc('e36', E, 'A capsule around a bacterium is', [
    'the nucleus',
    'an extra outer layer besides the peptidoglycan wall',
    'a chloroplast',
    'a tight junction',
  ], 1, 'Wall + capsule surround many prokaryotes.'),
  mc('e37', E, 'Which is more complex and larger?', [
    'a typical prokaryote',
    'a typical eukaryote',
    'a virus',
    'a ribosome by itself',
  ], 1, '10–100 µm vs ~1–10 µm. Viruses are even smaller than both.'),
  mc('e38', E, 'If a cell has plasmids (circular extra DNA), you are looking at a typical', [
    'animal nucleus chromosome only',
    'prokaryote feature from the comparison table',
    'plant vacuole',
    'fungal chitin sheet',
  ], 1, 'Comparison table: prokaryotes have circular DNA (plasmids).'),
]

export const PLANT_ANIMAL_QUESTIONS: BioPracticeQuestion[] = [
  mc('pa1', P, 'Animal cells have', [
    'a cellulose wall and one huge vacuole',
    'no cell wall, irregular less-rigid shape, many small vacuoles, lysosomes, and centrioles',
    'chloroplasts for green color',
    'peptidoglycan',
  ], 1, 'Lysosomes = digestion/cleaning. Centrioles = reproduction.', 'plant-animal-cells'),
  mc('pa2', P, 'Plant cells have', [
    'centrioles as their unique organelle listed here',
    'cell walls of cellulose, a fixed shape, ONE LARGE central vacuole, and chloroplasts',
    'no membrane',
    'only lysosomes and no vacuole',
  ], 1, 'Chloroplasts: green; convert sunlight to food.', 'plant-animal-cells'),
  mc('pa3', P, 'Lysosomes are specialized in', [
    'plant cells for photosynthesis',
    'animal cells for digestion and “cleaning”',
    'all bacterial nucleoids',
    'viral envelopes only',
  ], 1, 'Know which extra organelles each kingdom-style cell has in this unit.'),
  mc('pa4', P, 'Centrioles are specialized in', [
    'plant cells',
    'animal cells (reproduction)',
    'all prokaryotes',
    'viruses',
  ], 1, 'Animal-cell reproduction structures in these notes.'),
  mc('pa5', P, 'Chloroplasts', [
    'digest bacteria in animals',
    'give plants their green color and convert sunlight to food',
    'are peptidoglycan',
    'are found in animal muscle',
  ], 1, 'Plant specialized organelle.'),
  mc('pa6', P, 'Plant cell walls are', [
    'inside the membrane',
    'OUTSIDE the membrane and made of cellulose (complex carbohydrate layers) for structure and support',
    'chitin in plants',
    'present in animals too',
  ], 1, 'Fungi: chitin wall. Animals: NOT PRESENT.'),
  mc('pa7', P, 'Fungal cell walls are', [
    'cellulose',
    'chitin',
    'peptidoglycan',
    'absent; fungi are animals',
  ], 1, 'Plants and fungi ONLY have eukaryotic walls in these notes — different carbs.'),
  mc('pa8', P, 'A plant’s large central vacuole', [
    'is identical to many tiny animal vacuoles in size role',
    'holds water, food, waste; helps prevent bursting in hypotonic environments; helps give shape',
    'is a nucleus',
    'pumps 3 Na⁺ out',
  ], 1, 'Links Unit 2 Part 1 turgor to Part 2 structure.'),
  mc('pa9', P, 'Animal vacuoles are', [
    'one giant central vacuole',
    'lots of small vacuoles that may store nutrients',
    'chloroplasts',
    'cell walls',
  ], 1, 'Protists may use contractile vacuoles to push out extra water in hypotonic environments.'),
  mc('pa10', P, 'Contractile vacuoles in protists', [
    'are the same as plant chloroplasts',
    'push out excess water in hypotonic environments (and may help movement)',
    'make cellulose',
    'are found in typical animal tissue cells according to Part 1',
  ], 1, 'Part 1: not in animal cells; freshwater protists like Amoeba.'),
  mc('pa11', P, 'Plant cells have a more fixed shape because of', [
    'centrioles',
    'the cell wall',
    'lysosomes only',
    'flagella only',
  ], 1, 'Wall = rigid. Animals = irregular, less rigid.'),
  mc('pa12', P, 'Which set is found in plant cells but not typical animal cells?', [
    'chloroplasts, cellulose wall, and a large central vacuole',
    'lysosomes and centrioles',
    'a nucleoid',
    'peptidoglycan',
  ], 0, 'This unit’s plant extras: wall, huge vacuole, chloroplasts.'),
  mc('pa13', P, 'Which is listed as animal-specialized (not plant)?', [
    'chloroplasts',
    'lysosomes and centrioles',
    'cellulose wall',
    'central vacuole',
  ], 1, 'Cleaning/digestion and reproduction structures.'),
  mc('pa14', P, 'Both plant and animal cells are', [
    'prokaryotic',
    'eukaryotic',
    'viruses',
    'always 1–5 µm',
  ], 1, 'Both have nuclei and membrane-bound organelles.', 'plant-animal-cells'),
  mc('pa15', P, 'If a diagram shows a boxy cell with a huge empty-looking center and green ovals, it is', [
    'an animal cell',
    'a plant cell (wall + central vacuole + chloroplasts)',
    'a bacterium',
    'a virus',
  ], 1, 'Recognize diagrams.', 'plant-animal-cells'),
  mc('pa16', P, 'If a diagram shows an irregular cell with several small orange dots (lysosomes) and no wall, it is', [
    'a plant cell',
    'an animal cell',
    'a prokaryote with peptidoglycan',
    'cork named by Virchow',
  ], 1, 'No wall, many small vacuoles/lysosomes.', 'plant-animal-cells'),
  multi('pa17', P, 'Choose ALL plant-cell features from this unit.', [
    'cellulose wall outside the membrane',
    'one large central vacuole',
    'chloroplasts',
    'centrioles as the unique listed organelle',
  ], [0, 1, 2], 'Centrioles are listed for animals.'),
  multi('pa18', P, 'Choose ALL animal-cell features from this unit.', [
    'no cell wall / irregular shape',
    'many small vacuoles',
    'lysosomes and centrioles',
    'chloroplasts for food',
  ], [0, 1, 2], 'No chloroplasts in typical animal cells.'),
  mc('pa19', P, 'Cell walls are found in eukaryotes in', [
    'animals and plants',
    'plants and fungi ONLY (not animals)',
    'all animal tissues',
    'viruses',
  ], 1, 'Outside the membrane. Structure and support.'),
  mc('pa20', P, 'Layers of complex carbohydrates in eukaryotic walls are', [
    'cellulose in plants and chitin in fungi',
    'peptidoglycan in plants',
    'protein capsids',
    'cholesterol bilayers',
  ], 0, 'Do not mix bacterial peptidoglycan into plants.'),
  mc('pa21', P, 'A wilted plant (from Part 1) has lost water from its', [
    'centrioles',
    'large central vacuoles, so turgor dropped',
    'capsid',
    'nucleoid',
  ], 1, 'Structure (vacuole/wall) explains osmosis results.'),
  mc('pa22', P, 'Making energy, proteins, and more cells is true of', [
    'viruses independently',
    'cells in general (the 3 main jobs)',
    'only cork',
    'only animalcules that are not cells',
  ], 1, 'Connect jobs to organelles you will learn in more detail later: mitochondria/chloroplasts, ribosomes, mitosis/binary fission.'),
]

export const SURFACES_VIRUS_QUESTIONS: BioPracticeQuestion[] = [
  mc('v1', S, 'Tight junctions in animal cell surfaces are', [
    'pores in cellulose walls',
    'made by interlocking proteins that help hold cells together',
    'nucleoids',
    'capsids',
  ], 1, 'Interlocking proteins stitch neighboring animal cells.'),
  mc('v2', S, 'Gap junctions', [
    'are plant plasmodesmata only',
    'directly connect cytoplasm of two animal cells and allow molecules, ions, and electrical impulses through a gate',
    'are peptidoglycan',
    'are viruses',
  ], 1, 'Direct passage between animal cells.'),
  mc('v3', S, 'Plasmodesmata are', [
    'animal tight junctions',
    'pores in the plant cell wall that interconnect plant cells',
    'bacterial flagella',
    'viral envelopes',
  ], 1, 'Allow cytoplasmic exchange, transport, and communication.'),
  mc('v4', S, 'Why do plants need plasmodesmata for communication?', [
    'Plants are immobile (cannot move) so they need wall pores to share cytoplasm/signals',
    'Plants have no membranes',
    'Animals have cellulose walls',
    'Viruses use them to photosynthesize',
  ], 0, 'Immobile + walls = need tunnels through walls.'),
  mc('v5', S, 'TRACIE “intercellular joining” examples were', [
    'only ribosomes',
    'tight junctions and plasmodesmata',
    'only the Na+/K+ pump',
    'only Hooke’s cork',
  ], 1, 'Part 1 mnemonic meets Part 2 structures.'),
  mc('v6', S, 'Gap junctions vs plasmodesmata', [
    'both connect cytoplasm; gap = animal protein gates; plasmodesmata = plant wall pores',
    'both are bacterial walls',
    'gap junctions are in plants only',
    'plasmodesmata hold animal skin cells with interlocking proteins',
  ], 0, 'Same goal, different kingdoms/structures.'),
  mc('v7', S, 'Viruses are described as', [
    'cells that binary-fission',
    'infectious particles with some BUT NOT ALL characteristics of life',
    'the basic unit of life in cell theory',
    'eukaryotes with nuclei',
  ], 1, 'Not full organisms by cell-theory standards.', 'virus-struct'),
  mc('v8', S, 'Viruses need a ______ to survive and have ______ cells of their own.', [
    'host; no',
    'chloroplast; many',
    'nucleus; plant',
    'vacuole; animal',
  ], 0, 'No cells, no independent energy use.'),
  mc('v9', S, 'Viruses can evolve', [
    'never',
    'RAPIDLY and have genetic variation (“strains”)',
    'only if they photosynthesize',
    'only in cork',
  ], 1, 'They have some life traits (genetic change) but not all.'),
  mc('v10', S, 'Compared with prokaryotic and eukaryotic cells, viruses are', [
    'larger than both',
    'much smaller',
    'the same size as plant cells',
    'always 10–100 µm',
  ], 1, 'Tiny infectious particles.'),
  mc('v11', S, 'According to these notes, all viruses have', [
    'a nucleus and mitochondria',
    'a capsid (protective shell), a nucleic-acid genome (DNA or RNA), and an envelope (layer of membrane)',
    'peptidoglycan walls',
    'chloroplasts',
  ], 1, 'Match the slide list for the quiz.', 'virus-struct'),
  mc('v12', S, 'A capsid is', [
    'a plant vacuole',
    'the virus’s protective protein shell',
    'a gap junction',
    'cellulose',
  ], 1, 'Shell around the genome.', 'virus-struct'),
  mc('v13', S, 'A virus genome is', [
    'always DNA, never RNA',
    'nucleic acid made of DNA or RNA',
    'cellulose',
    'only protein',
  ], 1, 'Either DNA or RNA, not both as the cell’s full genome style.'),
  mc('v14', S, 'Viruses “reproduce” by', [
    'binary fission like bacteria',
    'mitosis',
    'hijacking a cell’s machinery',
    'osmosis',
  ], 2, 'They are not cells, so they cannot divide like cells.'),
  mc('v15', S, 'Why are viruses NOT cells / not fully alive in this unit?', [
    'They have nuclei',
    'They need a host, have no cells, and do not use energy on their own',
    'They are 10–100 µm eukaryotes',
    'They have peptidoglycan and 70s ribosomes',
  ], 1, 'Cell theory is about cells. Viruses fail that test.'),
  mc('v16', S, 'Which is smallest?', [
    'typical eukaryotic cell',
    'typical bacterium',
    'virus',
    'a plant cell’s central vacuole compared as a whole plant',
  ], 2, 'Euk > prok > virus in size.'),
  multi('v17', S, 'Choose ALL animal surface structures from this unit.', [
    'tight junctions (interlocking proteins)',
    'gap junctions (cytoplasm connected; ions/impulses)',
    'plasmodesmata through cellulose walls',
    'a nucleoid',
  ], [0, 1], 'Plasmodesmata are plants.'),
  multi('v18', S, 'Choose ALL true of viruses in these notes.', [
    'capsid + genome (DNA or RNA) + envelope',
    'need a host; no cells; no independent energy use',
    'evolve rapidly / have strains',
    'are the basic unit of life in cell theory',
  ], [0, 1, 2], 'They are infectious particles, not cells.'),
  mc('v19', S, 'Holding animal cells together like a zipper of proteins is', [
    'plasmodesmata',
    'tight junctions',
    'binary fission',
    'a capsid',
  ], 1, 'Interlocking proteins.'),
  mc('v20', S, 'Letting an impulse jump cell-to-cell in animal tissue is most like', [
    'tight junctions only holding',
    'gap junctions',
    'a fungal chitin wall with no pores',
    'Hooke’s cork chambers that were empty',
  ], 1, 'Gate for molecules, ions, electrical impulses.'),
  mc('v21', S, 'A pore through a plant wall connecting cytoplasm is a', [
    'tight junction',
    'plasmodesma (plasmodesmata plural)',
    'lysosome',
    'centriole',
  ], 1, 'Plant cell surfaces.'),
  mc('v22', S, 'If a particle has a protein coat and DNA or RNA but no cytoplasm/ribosomes of its own, it is a', [
    'prokaryote',
    'eukaryote',
    'virus',
    'plant cell',
  ], 2, 'No ribosomes/cytoplasm = not a cell.', 'virus-struct'),
  mc('v23', S, 'Strains of a virus exist because viruses have', [
    'cellulose walls',
    'genetic variation',
    'nucleoli',
    'central vacuoles',
  ], 1, 'They evolve rapidly.'),
  mc('v24', S, 'Cell theory would classify a virus as', [
    'a living cell',
    'not a cell / not made of cells, so not a full living organism by the theory',
    'a plant',
    'a prokaryote with 70s ribosomes',
  ], 1, 'This is a favorite honors compare question.'),
]
