import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'active' as const

export const ACTIVE_QUESTIONS: BioPracticeQuestion[] = [
  mc('a1', T, 'Active transport is defined by which two features?', [
    'Movement down the concentration gradient, no ATP required',
    'Movement against (up) the concentration gradient, powered by ATP',
    'Movement of only water molecules, powered by ATP',
    'Movement of gases only, requiring no energy',
  ], 1, 'Active transport moves solutes from low to high concentration, which is energetically unfavorable and therefore requires ATP.'),
  mc('a2', T, 'A biologist observes a solute moving from a region of low concentration to a region of high concentration across a membrane. This observation alone tells you that', [
    'the process must be simple diffusion',
    'the process must involve energy input, since movement against a gradient cannot happen spontaneously',
    'the process must be osmosis',
    'no protein could possibly be involved',
  ], 1, 'Moving "uphill" against a concentration gradient always requires an energy source — this is a thermodynamic requirement, not just a definition to memorize.'),
  mc('a3', T, 'A researcher treats a cell culture with a drug that blocks ATP synthase, halting ATP production. A transport process that was moving glucose against its concentration gradient stops immediately. This evidence best supports the conclusion that the transport was', [
    'passive, since it stopped when a chemical was added',
    'active, since blocking ATP production halted a process moving material against its gradient',
    'simple diffusion, unaffected by ATP levels',
    'osmosis, which never depends on ATP',
  ], 1, 'Passive transport does not depend on cellular ATP levels at all. A transport process that halts when ATP production is blocked — especially one moving material uphill — is active transport.'),
  mc('a4', T, 'Exocytosis is best described as', [
    'a process where small ions leak passively across the membrane',
    'bulk transport of material out of the cell via vesicles fusing with the plasma membrane, requiring ATP',
    'diffusion of gases out of the cell',
    'a passive process that occurs only in prokaryotes',
  ], 1, 'Exocytosis moves large quantities of material out of the cell using membrane-bound vesicles, which requires energy to form, transport, and fuse.'),
  mc('a5', T, 'Which of the following is the best real-world example of exocytosis?', [
    'A red blood cell shrinking in salt water',
    'A pancreatic cell releasing insulin into the bloodstream via secretory vesicles',
    'Oxygen diffusing from the lungs into the blood',
    'A white blood cell engulfing a bacterium',
  ], 1, 'Hormone secretion is a hallmark example of exocytosis: vesicles packed with insulin fuse with the plasma membrane and release their contents outside the cell.'),
  mc('a6', T, 'Endocytosis differs from exocytosis in that endocytosis', [
    'moves material into the cell using vesicles, while exocytosis moves material out',
    'never requires ATP, while exocytosis always does',
    'only occurs in plant cells',
    'is a form of passive transport',
  ], 0, 'Endo- (into) and exo- (out of) describe opposite directions of bulk vesicle transport; both require ATP.'),
  mc('a7', T, 'A macrophage engulfing an entire bacterium in a large vesicle is an example of', [
    'pinocytosis',
    'phagocytosis',
    'facilitated diffusion',
    'receptor-mediated exocytosis',
  ], 1, '"Phago-" = eating; engulfing large particles (bacteria, cell debris) is phagocytosis, sometimes called "cell-eating."'),
  mc('a8', T, 'A capillary cell taking in a small droplet of extracellular fluid containing dissolved nutrients is an example of', [
    'phagocytosis',
    'pinocytosis',
    'simple diffusion',
    'the sodium-potassium pump',
  ], 1, '"Pino-" = drinking; taking in small amounts of fluid (rather than large particles) is pinocytosis.'),
  mc('a9', T, 'A cell takes up cholesterol-carrying particles from the blood only after specific membrane proteins bind to them; the particles are then engulfed. This process is', [
    'phagocytosis',
    'receptor-mediated endocytosis',
    'simple diffusion',
    'osmosis',
  ], 1, 'Binding to a specific receptor before engulfment (as with LDL cholesterol uptake) is the defining feature of receptor-mediated endocytosis.'),
  mc('a10', T, 'Why is the shape of a receptor protein essential for receptor-mediated endocytosis?', [
    'Shape is irrelevant; any protein can bind any signaling molecule',
    'The receptor\'s shape must precisely match the shape of its target molecule (like a hormone) for binding and uptake to occur',
    'Receptor shape only matters for enzymes, not transport proteins',
    'Receptors do not need a specific shape because they work through simple diffusion',
  ], 1, 'Molecular recognition, like an enzyme-substrate fit, depends on complementary shapes between the receptor and its specific ligand.'),
  mc('a11', T, 'Which of the following correctly distinguishes the three types of endocytosis?', [
    'Pinocytosis takes in large particles; phagocytosis takes in fluid; receptor-mediated requires no binding step',
    'Pinocytosis takes in small amounts of fluid; phagocytosis takes in large particles; receptor-mediated involves binding to a specific receptor first',
    'All three types are identical processes with different names',
    'Only phagocytosis requires ATP; the other two are passive',
  ], 1, 'Each type is defined by what is taken in and how: fluid (pino-), large particles (phago-), or receptor-bound targets (receptor-mediated) — and all three require ATP.'),
  mc('a12', T, 'The sodium-potassium pump moves ions in which pattern per cycle?', [
    '2 Na⁺ out, 3 K⁺ in',
    '3 Na⁺ out, 2 K⁺ in',
    '3 Na⁺ in, 2 K⁺ out',
    '2 Na⁺ in, 2 K⁺ out',
  ], 1, 'For every cycle, 3 sodium ions are pumped out and 2 potassium ions are pumped in — an unequal exchange that requires ATP.', 'nak-pump'),
  mc('a13', T, 'Because the sodium-potassium pump moves 3 positive charges out for every 2 positive charges brought in, the direct result is that', [
    'the inside of the cell becomes slightly more positive than the outside',
    'the inside of the cell becomes slightly more negative than the outside',
    'there is no net effect on charge across the membrane',
    'the cell membrane loses its charge entirely',
  ], 1, 'Since more positive charge leaves than enters each cycle, the cytoplasm ends up slightly negative relative to the extracellular fluid.', 'nak-pump'),
  mc('a14', T, 'After extensive pumping, which describes the resulting distribution of ions, sometimes remembered with the "salty banana" analogy?', [
    'High Na⁺ inside, high K⁺ outside',
    'High Na⁺ outside, high K⁺ inside',
    'Equal Na⁺ and K⁺ on both sides',
    'No Na⁺ or K⁺ present on either side',
  ], 1, 'The pump maintains a steep Na⁺ gradient (high outside) and K⁺ gradient (high inside) at the cost of ATP.'),
  mc('a15', T, 'A cell is treated with ouabain, a drug that specifically blocks the sodium-potassium pump. Which immediate consequence is most likely?', [
    'Na⁺ and K⁺ gradients will be actively strengthened',
    'Na⁺ and K⁺ will gradually diffuse down their gradients until the concentration difference collapses, since nothing is actively restoring it',
    'The cell will immediately begin performing photosynthesis',
    'Water will stop moving across the membrane entirely',
  ], 1, 'Without active pumping to counteract passive leak, ions will slowly equilibrate toward their diffusion gradients, eliminating the carefully maintained Na⁺/K⁺ imbalance.'),
  mc('a16', T, 'The sodium-potassium pump directly supports homeostasis by', [
    'converting light energy into chemical energy',
    'maintaining the specific internal Na⁺ and K⁺ concentrations and membrane charge that cells depend on for functions like nerve signaling',
    'breaking down starch into glucose',
    'building a peptidoglycan wall around the cell',
  ], 1, 'Correct ion balance is essential to processes like nerve impulse transmission and cell volume regulation, both of which depend on this pump\'s activity.'),
  mc('a17', T, 'A transport protein changes shape using ATP to move ions against their gradients. This description matches', [
    'a channel protein performing facilitated diffusion',
    'a carrier protein performing active transport, such as the sodium-potassium pump',
    'simple diffusion of a small gas molecule',
    'osmosis of water molecules',
  ], 1, 'A shape-changing carrier protein powered by ATP that moves ions against their gradients is the defining mechanism of the sodium-potassium pump.', 'nak-pump'),
  mc('a18', T, 'Which of the following would provide the strongest evidence that a given transport process is active rather than passive?', [
    'The solute moves down its concentration gradient',
    'The process continues at the same rate whether or not ATP is available',
    'The process halts as soon as the cell\'s ATP supply is depleted, and the solute is shown to move against its gradient',
    'The solute is a small, uncharged gas',
  ], 2, 'Active transport is uniquely dependent on ATP and uniquely capable of moving solutes against their gradient — both together are strong, direct evidence.'),
  mc('a19', T, 'Which of the following processes does NOT require ATP?', [
    'The sodium-potassium pump',
    'Phagocytosis',
    'Facilitated diffusion of glucose down its gradient',
    'Exocytosis of a hormone',
  ], 2, 'Facilitated diffusion uses a protein but is still passive — no ATP needed as long as the solute moves down its gradient. The other three all involve moving material using cellular energy.'),
  mc('a20', T, 'Bulk transport (moving many molecules or large particles at once using vesicles) includes which two processes?', [
    'Simple diffusion and osmosis',
    'Endocytosis and exocytosis',
    'Facilitated diffusion and the sodium-potassium pump',
    'Osmosis and facilitated diffusion',
  ], 1, 'Endo- and exocytosis both rely on vesicle formation and fusion to move large quantities of material across the membrane at once.', 'endo-exo'),
  mc('a21', T, 'A nerve cell releases neurotransmitter molecules stored in vesicles into the synaptic gap. This process is best classified as', [
    'osmosis',
    'exocytosis',
    'phagocytosis',
    'simple diffusion',
  ], 1, 'Nerve cell communication via vesicle release at the membrane is a textbook example of exocytosis, and it requires ATP.'),
  mc('a22', T, 'An Amoeba engulfing a paramecium for food and a white blood cell engulfing invading bacteria both illustrate', [
    'pinocytosis',
    'phagocytosis',
    'receptor-mediated endocytosis only',
    'passive transport',
  ], 1, 'Both examples involve engulfing large particles/organisms into a vesicle — the defining feature of phagocytosis.'),
  mc('a23', T, 'Which statement about active transport is FALSE?', [
    'It can move solutes against their concentration gradient',
    'It requires ATP',
    'It includes endocytosis, exocytosis, and pump proteins like the sodium-potassium pump',
    'It always moves solutes down their concentration gradient, just like passive transport',
  ], 3, 'This statement contradicts the core definition of active transport — moving against, not down, the gradient — and is therefore the false statement.'),
  mc('a24', T, 'A student argues, "Since facilitated diffusion uses a transport protein, and the sodium-potassium pump also uses a transport protein, both must require ATP." What is wrong with this argument?', [
    'Nothing; the argument is correct',
    'The presence of a protein does not determine whether ATP is needed — direction relative to the gradient does. Facilitated diffusion is passive; the pump is active because it moves against the gradient',
    'Facilitated diffusion never uses a protein',
    'The sodium-potassium pump never uses a protein',
  ], 1, 'Both are protein-mediated, but only one moves solutes uphill. Requiring ATP is determined by whether transport goes against the gradient, not merely by protein involvement.'),
  mc('a25', T, 'If a cell\'s ATP production were completely and permanently shut down, which transport process listed below would be directly and immediately disabled?', [
    'Simple diffusion of oxygen',
    'Osmosis of water',
    'The sodium-potassium pump',
    'Facilitated diffusion of glucose down its gradient',
  ], 2, 'Only the ATP-dependent process (the pump) would be directly disabled. The other three are passive and do not depend on the cell\'s ATP supply.'),
  multi('a26', T, 'Select ALL processes that are classified as active transport.', [
    'Exocytosis of a hormone',
    'Phagocytosis of a bacterium',
    'The sodium-potassium pump',
    'Facilitated diffusion of amino acids down their gradient',
  ], [0, 1, 2], 'Facilitated diffusion, even though protein-assisted, is passive because it moves solutes down their gradient with no ATP.'),
  mc('a27', T, 'Insulin binding to a receptor protein, followed by the insulin-receptor complex being engulfed into the cell, illustrates which specific process?', [
    'Phagocytosis',
    'Receptor-mediated endocytosis',
    'Simple diffusion',
    'Exocytosis',
  ], 1, 'A hormone binding a specific receptor before being taken into the cell is the defining sequence of receptor-mediated endocytosis.'),
  mc('a28', T, 'Which best explains why active transport is essential for maintaining ion gradients that passive diffusion alone would eliminate?', [
    'Passive diffusion always creates gradients on its own',
    'Passive diffusion moves solutes toward equilibrium (evening out gradients), so a continuous energy-requiring process is needed to counteract that natural leak and preserve a gradient',
    'Ion gradients require no maintenance once established',
    'Active transport and passive diffusion always move ions in the same direction',
  ], 1, 'Left alone, passive diffusion will always erode a concentration gradient over time. Only an active, ATP-powered process can continuously restore or maintain a gradient against this natural tendency.'),
  mc('a29', T, 'A vesicle carrying digestive enzymes fuses with the plasma membrane and releases its contents to break down food outside a single-celled organism. This is an example of', [
    'endocytosis',
    'exocytosis',
    'osmosis',
    'facilitated diffusion',
  ], 1, 'Vesicle contents being released to the outside via membrane fusion is exocytosis by definition.'),
  mc('a30', T, 'Which sequence correctly places these transport types in order from requiring the LEAST cellular energy investment to the MOST for the same amount of material moved?', [
    'Simple diffusion → facilitated diffusion → active transport (pump) → bulk vesicle transport (phagocytosis)',
    'Active transport → simple diffusion → facilitated diffusion → phagocytosis',
    'Phagocytosis → active transport → facilitated diffusion → simple diffusion',
    'All four require exactly the same amount of energy',
  ], 0, 'Simple and facilitated diffusion cost no ATP. Pump-based active transport costs ATP per cycle of ions moved. Bulk vesicle transport like phagocytosis is typically the most energetically expensive per event, since it requires vesicle formation, cytoskeletal movement, and membrane fusion.'),
  mc('a31', T, 'Which of the following correctly matches a transport process to whether it moves individual dissolved solutes or bulk material?', [
    'The sodium-potassium pump moves individual ions; phagocytosis moves bulk material via vesicles',
    'Phagocytosis moves individual ions; the sodium-potassium pump moves bulk material',
    'Both move only bulk material',
    'Both move only individual ions',
  ], 0, 'The pump is a carrier protein cycling individual Na⁺/K⁺ ions one at a time (per cycle), while phagocytosis engulfs entire particles or cells at once inside a vesicle.'),
  mc('a32', T, 'Compare passive and active transport in terms of the cellular structures typically involved. Which statement is most accurate?', [
    'Passive transport can involve simple diffusion (no protein), channel proteins, or carrier proteins; active transport can involve pump proteins or vesicles',
    'Passive transport always requires a vesicle; active transport never does',
    'Both transport types always require a nucleus to function',
    'Neither transport type ever involves a protein',
  ], 0, 'Passive routes range from no protein at all (simple diffusion) to protein-assisted (facilitated diffusion). Active routes include pump proteins (like Na⁺/K⁺) and vesicle-based bulk transport (endo-/exocytosis).'),
  mc('a33', T, 'A hormone (a chemical messenger) needs to leave the cell that produced it in large quantities at once. The most efficient transport mechanism for this task is', [
    'simple diffusion',
    'exocytosis, packaging the hormone into vesicles that fuse with the membrane',
    'the sodium-potassium pump',
    'facilitated diffusion through a channel protein',
  ], 1, 'Large, polar signaling molecules produced in bulk are efficiently exported via vesicle-based exocytosis rather than diffusion.'),
  mc('a34', T, 'If a cell needs to import a very large number of low-density lipoprotein (cholesterol-carrying) particles specifically, and ignore other similarly-sized particles nearby, it would rely on', [
    'simple diffusion, since size does not matter for cholesterol',
    'receptor-mediated endocytosis, which uses specific receptor proteins to selectively bind and internalize only the targeted particles',
    'the sodium-potassium pump',
    'osmosis',
  ], 1, 'Selectivity for one specific type of particle among many similar ones requires a specific receptor-ligand interaction, which is the hallmark of receptor-mediated endocytosis.'),
]
