import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'membrane' as const

export const MEMBRANE_QUESTIONS: BioPracticeQuestion[] = [
  mc('m1', T, 'The smallest functional unit of organisms is the', [
    'atom',
    'cell',
    'tissue',
    'organ',
  ], 1, 'The cell is the smallest functional unit of organisms.'),
  mc('m2', T, 'The cell membrane’s main job is to', [
    'store DNA in a nucleoid',
    'regulate entry and exit of molecules',
    'make glucose from sunlight',
    'digest food with enzymes only',
  ], 1, 'It controls what goes in and out so the cell can keep homeostasis.'),
  mc('m3', T, 'Another name for the cell membrane is', [
    'cell wall',
    'plasma membrane or phospholipid bilayer',
    'nuclear envelope only',
    'capsule',
  ], 1, 'Plasma membrane = phospholipid bilayer = cell membrane. It surrounds ALL cells.'),
  mc('m4', T, 'Which cells have a cell membrane?', [
    'animal cells only',
    'plant cells only',
    'eukaryotes only',
    'ALL cells',
  ], 3, 'Prokaryotes and eukaryotes both have a plasma membrane.'),
  mc('m5', T, 'A phospholipid bilayer is made of how many layers of phospholipids?', [
    '1',
    '2',
    '3',
    '4 fused rings',
  ], 1, 'Bi- means two. Two layers of phospholipids form the membrane.'),
  mc('m6', T, 'Plasma-membrane fluidity and flexibility come from unsaturated fatty-acid chains because', [
    'double bonds cause bends so tails can move freely',
    'they have no carbon',
    'they freeze the membrane solid',
    'they remove cholesterol',
  ], 0, 'Kinks from C=C bonds keep phospholipids from packing tightly.'),
  mc('m7', T, 'Fatty-acid chain length also affects the membrane by', [
    'making DNA circular',
    'making the membrane soft and flexible',
    'creating a cell wall of cellulose',
    'pumping sodium',
  ], 1, 'Chain length helps keep the bilayer soft and flexible.'),
  multi('m8', T, 'Choose ALL reasons the plasma membrane is fluid and flexible.', [
    'Unsaturated tails have double-bond kinks and move freely',
    'Fatty-acid chain length keeps it soft/flexible',
    'A peptidoglycan wall holds it rigid',
    'Cholesterol also helps keep it from being too solid or too fluid',
  ], [0, 1, 3], 'Cell walls are outside some cells; they are not why the bilayer itself is fluid.'),
  mc('m9', T, 'Which is NOT one of the six main cell-membrane functions from this unit?', [
    'contains cytoplasm and all cell parts',
    'photosynthesis of glucose',
    'protective barrier between inside and outside',
    'regulates things coming in and out',
  ], 1, 'Chloroplasts do photosynthesis. Membranes contain cytoplasm, protect, regulate, anchor the cytoskeleton, bind enzymes, and join cells.'),
  mc('m10', T, 'The membrane can act as an anchor for the', [
    'cell wall cellulose only',
    'cytoskeleton',
    'capsid of a virus',
    'nucleoid DNA loop only',
  ], 1, 'It anchors the cytoskeleton and also provides binding sites for enzymes.'),
  mc('m11', T, 'Interlocking membrane surfaces (“junctions”) allow nearby cells to', [
    'binary fission',
    'bind together for cell-to-cell recognition',
    'lose their membranes',
    'stop all transport',
  ], 1, 'Junctions hold cells together and help recognition.'),
  multi('m12', T, 'Choose ALL functions of the cell membrane.', [
    'Contains cytoplasm and cell parts',
    'Protective barrier',
    'Regulates entry and exit',
    'Makes all of a plant’s cellulose wall from CO₂',
  ], [0, 1, 2], 'The wall is outside the membrane in plants/fungi/bacteria. Membrane jobs also include cytoskeleton anchor, enzyme binding, and junctions.'),
  mc('m13', T, 'Homeostasis means', [
    'the cell bursting in every hypotonic solution',
    'maintaining a stable internal environment despite external changes',
    'never letting any molecule cross',
    'keeping solute 100% outside forever',
  ], 1, 'The membrane maintains homeostasis by regulating entry and exit so the cell has the right amounts of nutrients, water, proteins, etc.'),
  mc('m14', T, 'How does the cell membrane maintain homeostasis?', [
    'By regulating what enters and exits',
    'By destroying the phospholipid tails',
    'By turning into a cell wall',
    'By stopping all osmosis forever',
  ], 0, 'Correct amounts of water, nutrients, and proteins depend on selective transport.'),
  mc('m15', T, 'Integral proteins', [
    'sit only on the outer edge and never span the bilayer',
    'span the whole membrane from one phospholipid head to the other',
    'are made of cellulose',
    'are only found in viruses',
  ], 1, 'They go all the way across. They help move large molecules that cannot simply pass through.'),
  mc('m16', T, 'A channel protein is a transport protein that', [
    'has a tunnel-like pore so molecules can pass through',
    'is a 4-fused-ring steroid',
    'is DNA',
    'pumps only against a gradient with no pore',
  ], 0, 'Channel = pore/tunnel. Molecules can move randomly through the pore (still high → low in facilitated diffusion).', 'channel-carrier'),
  mc('m17', T, 'A carrier protein is a transport protein that', [
    'is a carbohydrate name tag only',
    'changes shape to move material from one side to the other',
    'is cholesterol',
    'is found only in plant cell walls',
  ], 1, 'Carrier proteins change shape. Some extend through the membrane; others do not.', 'channel-carrier'),
  mc('m18', T, 'A receptor protein', [
    'digests cellulose',
    'binds to signaling molecules such as hormones',
    'is a fatty-acid tail',
    'is peptidoglycan',
  ], 1, 'Receptors bind signals (example: insulin). Shape must match the signal.'),
  mc('m19', T, 'Which integral protein type is matched correctly?', [
    'channel — changes shape only, never has a pore',
    'carrier — tunnel with a permanent open pore and no shape change',
    'receptor — binds hormones / signaling molecules',
    'all three are oligosaccharides',
  ], 2, 'Channel = pore. Carrier = shape change. Receptor = signal binding.'),
  mc('m20', T, 'In the TRACIE jobs of membrane proteins, T stands for', [
    'turgor',
    'transport (channels and pumps)',
    'transcription',
    'thylakoid',
  ], 1, 'TRACIE: Transport, Receptors, Anchorage, Cell recognition, Intercellular joining, Enzyme activity.'),
  mc('m21', T, 'In TRACIE, the R is receptors. An example from the notes is', [
    'cellulose',
    'insulin (a hormone)',
    'peptidoglycan',
    'a capsid',
  ], 1, 'Receptor proteins bind hormones such as insulin.'),
  mc('m22', T, 'Anchorage in TRACIE means proteins help with', [
    'cytoskeleton attachment',
    'binary fission only',
    'making the nucleoid',
    'forming a viral envelope',
  ], 0, 'Membrane proteins attach to the cytoskeleton.'),
  mc('m23', T, 'Cell recognition in TRACIE is especially important for', [
    'gravity',
    'immunity',
    'making starch inside chloroplasts',
    'binary fission',
  ], 1, 'Recognition (“self vs non-self”) is a key immune-system job.'),
  mc('m24', T, 'Intercellular joining in TRACIE includes', [
    'tight junctions and plasmodesmata',
    'only the sodium-potassium pump',
    'only osmosis',
    'only RNA viruses',
  ], 0, 'Tight junctions (animals) and plasmodesmata (plants) join cells.'),
  mc('m25', T, 'Enzyme activity of membrane proteins means they can', [
    'store DNA',
    'speed up chemical reactions',
    'stop all homeostasis',
    'replace the cell wall',
  ], 1, 'Some membrane proteins are enzymes.'),
  multi('m26', T, 'Choose ALL TRACIE membrane-protein jobs.', [
    'Transport: channels and pumps',
    'Receptors: hormones',
    'Anchorage: cytoskeleton attachment',
    'Translation of mRNA inside the nucleus only',
  ], [0, 1, 2], 'Also cell recognition (immunity), intercellular joining, and enzyme activity.'),
  mc('m27', T, 'Peripheral proteins are located', [
    'spanning the entire bilayer like a tunnel',
    'on the interior or exterior surface (edges) of the membrane',
    'only in the nucleoid',
    'inside the phospholipid tails as cholesterol rings',
  ], 1, 'They sit on the edges, not all the way through.'),
  mc('m28', T, 'A main job of peripheral proteins is', [
    'making cellulose walls',
    'cell recognition and hormone recognition',
    'binary fission',
    'forming a capsid',
  ], 1, '“I know you, fellow cell” vs “you could hurt me,” plus reading hormone messages.'),
  mc('m29', T, 'Cholesterol in the membrane is a', [
    'protein pump',
    'steroid (4 fused carbon rings) that keeps the membrane from being too solid or too fluid',
    'oligosaccharide name tag',
    'channel protein',
  ], 1, 'It limits phospholipid movement and acts as a temperature buffer — important for homeostasis.', 'steroid'),
  mc('m30', T, 'Cholesterol provides stability by', [
    'physically limiting movement of the phospholipids',
    'digesting glucose',
    'turning into peptidoglycan',
    'removing all unsaturated tails',
  ], 0, 'Too fluid or too rigid both wreck membrane function. Cholesterol buffers that.'),
  mc('m31', T, 'If a membrane had NO cholesterol, a likely honors-level problem would be', [
    'it could become too fluid when hot or too stiff when cold',
    'it would instantly become a cell wall',
    'osmosis would become active transport',
    'DNA would become RNA',
  ], 0, 'Cholesterol is a temperature buffer that stabilizes fluidity.'),
  mc('m32', T, 'Oligosaccharides are', [
    'long DNA chromosomes',
    'short linked chains of a few monosaccharides that allow cell-to-cell recognition',
    '3 Na⁺ ions',
    'peptidoglycan only',
  ], 1, 'Oligo- = a few. They act like name tags.'),
  mc('m33', T, 'Glycolipids are', [
    'carbs attached to lipids in the bilayer',
    'proteins that pump sodium',
    'steroids with 4 rings and no sugar',
    'circular plasmids',
  ], 0, 'Glyco = sugar. Lipid = fat. Sugar stuck on a membrane lipid.'),
  mc('m34', T, 'Glycoproteins are', [
    'carbs attached to proteins (integral or peripheral)',
    'only DNA',
    'only cholesterol',
    'only cellulose',
  ], 0, 'Sugar + protein. Also provide membrane stability and immune recognition.'),
  mc('m35', T, 'Why are oligosaccharides / glycoproteins important in the immune system?', [
    'They are tiny name tags so the body can tell self from invader',
    'They pump 3 Na⁺ out',
    'They are contractile vacuoles',
    'They are chloroplasts',
  ], 0, 'Recognition molecules let immune cells identify cells.'),
  multi('m36', T, 'Choose ALL macromolecules in the cell membrane.', [
    'Lipids (most abundant, including phospholipids and cholesterol)',
    'Proteins (integral and peripheral)',
    'Carbohydrates (oligosaccharides on lipids or proteins)',
    'Peptidoglycan as the bilayer itself',
  ], [0, 1, 2], 'Peptidoglycan is a bacterial cell-wall material, not the bilayer.'),
  mc('m37', T, 'The membrane is called a fluid mosaic because “fluid” means', [
    'components can move around, allowing substances to pass',
    'the cell is always bursting',
    'DNA flows out constantly',
    'there are no proteins',
  ], 0, 'Fluidity comes from the phospholipid dual nature and cholesterol content.', 'fluid-mosaic'),
  mc('m38', T, 'In the fluid mosaic model, “mosaic” means', [
    'only water is present',
    'a mixture of components: lipids, proteins, and carbohydrates',
    'the membrane is one pure cholesterol crystal',
    'cells have no membrane',
  ], 1, 'Lipids are the most abundant piece of the mosaic.', 'fluid-mosaic'),
  mc('m39', T, 'Amphipathic means', [
    'having both hydrophobic AND hydrophilic properties',
    'being only charged ions',
    'requiring ATP always',
    'being a virus capsid',
  ], 0, 'Phospholipids are amphipathic. That dual nature makes the membrane selective.', 'bilayer'),
  mc('m40', T, 'Phospholipid heads are ______ and tails are ______.', [
    'hydrophobic; hydrophilic',
    'hydrophilic (polar); hydrophobic (nonpolar)',
    'made of DNA; made of RNA',
    'cellulose; chitin',
  ], 1, 'Heads face water (inside and outside). Tails hide from water in the middle.', 'bilayer'),
  mc('m41', T, 'WHY do hydrophilic heads point outward and hydrophobic tails point inward?', [
    'Heads are polar and attracted to water on both sides; tails are nonpolar and avoid water',
    'Heads hate water and tails love water',
    'Cholesterol forces heads inward',
    'DNA polarity pulls tails out',
  ], 0, 'Water is inside the cell (cytoplasm) and outside. Polar heads interact with water; nonpolar tails cluster away from it.', 'bilayer'),
  mc('m42', T, 'Selective permeability means the membrane', [
    'lets every molecule through equally',
    'only lets certain substances through',
    'lets only proteins through and never water',
    'is impermeable to oxygen',
  ], 1, 'Amphipathic structure makes it selective, which is how it maintains homeostasis.'),
  mc('m43', T, 'Which molecules DO pass easily through the bilayer?', [
    'ions such as Na⁺ and K⁺',
    'small uncharged polar molecules like H₂O, gases like O₂ and CO₂, and lipid-soluble / large hydrophobic molecules',
    'glucose (C₆H₁₂O₆) with no protein help',
    'proteins',
  ], 1, 'Small / uncharged / nonpolar / lipid-soluble cross. Charged, large polar, and big proteins do not.', 'bilayer'),
  mc('m44', T, 'Which molecules do NOT pass easily?', [
    'O₂ and CO₂',
    'ions, hydrophilic molecules larger than water (glucose), and large molecules like proteins',
    'small uncharged polar water',
    'lipid-soluble molecules',
  ], 1, 'Charge, polarity, and size block free diffusion.'),
  mc('m45', T, 'WHY can’t ions easily cross the phospholipid bilayer?', [
    'They are too small',
    'They have a + or − charge, so the hydrophobic tail region repels them',
    'They are gases',
    'They are identical to cholesterol',
  ], 1, 'The nonpolar tail core rejects charged particles.'),
  mc('m46', T, 'WHY does glucose need help to cross, while O₂ does not?', [
    'Glucose is a hydrophilic molecule larger than water; O₂ is a small uncharged gas',
    'Glucose is a gas; O₂ is a protein',
    'Glucose is hydrophobic; O₂ is an ion',
    'Both need ATP always',
  ], 0, 'Size + polarity: glucose needs facilitated diffusion (channel or carrier). O₂ uses simple diffusion.'),
  mc('m47', T, 'Water can cross, but slower than through aquaporins, because it is', [
    'an ion with a full charge',
    'a small uncharged polar molecule',
    'larger than a protein',
    'identical to starch',
  ], 1, 'H₂O is small enough to sneak through, but aquaporins speed it up.'),
  mc('m48', T, 'Large hydrophobic molecules generally', [
    'cannot ever approach a membrane',
    'CAN pass more easily than ions because they like the nonpolar tail region',
    'are pumped only by plasmodesmata',
    'are peptidoglycan',
  ], 1, 'Like dissolves like: hydrophobic molecules mix with hydrophobic tails.'),
  mc('m49', T, 'Look at this bilayer. The circles facing water are', [
    'hydrophobic tails',
    'hydrophilic phosphate heads',
    'DNA plasmids',
    'capsids',
  ], 1, 'Blue circles = polar heads. Zigzag lines = nonpolar tails.', 'bilayer'),
  mc('m50', T, 'In this mosaic diagram, the yellow circle in the tail region is most likely', [
    'a channel pore',
    'cholesterol stabilizing fluidity',
    'a plasmid',
    'starch',
  ], 1, 'Cholesterol sits among phospholipids and buffers fluidity.', 'fluid-mosaic'),
  mc('m51', T, 'If the tails packed perfectly straight with no kinks and no cholesterol, the membrane would tend to be', [
    'too rigid / solid, especially when cold',
    'a gas',
    'a cell wall of chitin',
    'unable to have heads',
  ], 0, 'Unsaturated kinks + cholesterol keep it fluid enough to function.'),
  mc('m52', T, 'A test diagram of a phospholipid in the membrane should show', [
    'three fatty-acid tails and no head',
    'a hydrophilic head and TWO hydrophobic tails',
    'four fused rings only',
    'a nucleotide',
  ], 1, 'Membrane lipids are phospholipids (2 tails), not triglycerides (3 tails).', 'phospholipid'),
  mc('m53', T, 'The most abundant macromolecule type in the membrane is', [
    'nucleic acids',
    'lipids',
    'cellulose',
    'peptidoglycan',
  ], 1, 'The bilayer itself is lipid. Proteins and carbs are mixed in (mosaic).'),
  multi('m54', T, 'Choose ALL true of selective permeability and homeostasis.', [
    'Only certain substances cross easily',
    'Polarity and size help decide what crosses',
    'Regulating entry/exit keeps internal conditions stable',
    'Every ion freely simple-diffuses through tails',
  ], [0, 1, 2], 'Ions need proteins. That control is homeostasis.'),
  mc('m55', T, 'A binding site for enzymes on the membrane helps the cell because', [
    'reactions can be organized at the membrane surface',
    'enzymes become DNA',
    'the cell loses its bilayer',
    'osmosis becomes active transport',
  ], 0, 'One of the six listed membrane functions.'),
  mc('m56', T, 'Which pair is amphipathic?', [
    'a fully charged Na⁺ ion',
    'a phospholipid (polar head + nonpolar tails)',
    'O₂ gas',
    'pure cellulose',
  ], 1, 'Amphipathic = both hydrophilic and hydrophobic parts.', 'phospholipid'),
  mc('m57', T, 'Peripheral vs integral: which is correct?', [
    'integral = edges only; peripheral = spans the whole membrane',
    'integral = spans the membrane; peripheral = on interior or exterior surface',
    'both are oligosaccharides',
    'neither can bind anything',
  ], 1, 'Know location AND function for both types.'),
  mc('m58', T, 'Which protein would bind insulin?', [
    'a receptor protein',
    'cellulose',
    'a triglyceride',
    'peptidoglycan',
  ], 0, 'Receptor proteins bind signaling molecules like hormones.'),
  mc('m59', T, 'Why does the dual nature of phospholipids make the membrane “selective”?', [
    'The hydrophobic core blocks many polar/charged substances while letting some small/nonpolar ones through',
    'It dissolves the cell wall',
    'It forces all proteins to leave',
    'It makes ATP from sunlight',
  ], 0, 'Heads love water; tails hate it. That arrangement is a chemical filter.'),
  mc('m60', T, 'Glycolipids and glycoproteins both', [
    'pump 3 Na⁺ out',
    'help with recognition and add stability',
    'are contractile vacuoles',
    'are found only in archaea nucleoids',
  ], 1, 'Carb chains = name tags + stability.'),
  mc('m61', T, 'If a question shows 4 fused rings in the membrane, you should identify', [
    'glucose',
    'cholesterol (a steroid lipid)',
    'a channel pore',
    'peptidoglycan',
  ], 1, 'Cholesterol = steroid = 4 fused C rings.', 'steroid'),
  mc('m62', T, 'Which statement is honors-test precise?', [
    'The membrane surrounds only animal cells',
    'The membrane surrounds ALL cells and is also called the plasma membrane',
    'Prokaryotes have no membrane',
    'Plant cells replace the membrane with cellulose only',
  ], 1, 'Plants have membrane AND wall. Bacteria have membrane AND peptidoglycan wall.'),
  multi('m63', T, 'Choose ALL molecules that pass easily (no protein required).', [
    'O₂',
    'CO₂',
    'Na⁺',
    'a large protein enzyme',
  ], [0, 1], 'Gases yes. Ions and big proteins no.'),
  multi('m64', T, 'Choose ALL that do NOT pass easily.', [
    'Cl⁻',
    'glucose',
    'a polypeptide',
    'O₂',
  ], [0, 1, 2], 'Charged, large polar, and huge molecules need help or bulk transport.'),
  mc('m65', T, 'The interior of the bilayer (where tails meet) is best described as', [
    'hydrophilic and full of water',
    'hydrophobic / nonpolar',
    'a nucleolus',
    'peptidoglycan',
  ], 1, 'That oily core is why charged and large polar molecules struggle.', 'bilayer'),
]
