import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'passive' as const

export const PASSIVE_QUESTIONS: BioPracticeQuestion[] = [
  mc('p1', T, 'A system at dynamic equilibrium is one where', [
    'all molecular motion has permanently stopped and nothing moves at all',
    'concentration is equal throughout, though molecules keep moving both ways at equal rates',
    'every single molecule has moved over to one side of the membrane',
    'the cell has switched entirely away from passive transport toward active transport',
  ], 1, 'Equilibrium is dynamic — net movement is zero, but random motion never actually stops.'),
  mc('p2', T, 'Net passive movement of a solute can only occur when', [
    'ATP happens to be available',
    'a concentration gradient exists across the membrane',
    'the membrane is completely impermeable to that solute',
    'the solute is a large charged protein',
  ], 1, 'Without a gradient, there is nothing to drive net diffusion in either direction.'),
  mc('p3', T, 'Which correctly compares passive and active transport?', [
    'Passive: no ATP, high to low. Active: ATP required, low to high',
    'Passive: ATP required, low to high. Active: no ATP, high to low',
    'Both require ATP but move opposite directions',
    'Neither ever requires ATP',
  ], 0, 'Passive transport is downhill and free. Active transport goes against the gradient and needs ATP.'),
  mc('p4', T, 'Simple diffusion, osmosis, and facilitated diffusion are all classified as passive transport because each', [
    'requires a protein channel to occur, unlike the other two forms',
    'moves a solute down its gradient with no direct ATP cost',
    'occurs only inside eukaryotic cells and never in prokaryotes',
    'moves solutes against their gradient using cellular energy',
  ], 1, 'What unites the three is direction (downhill) and energy source (none) — they differ only in what is moving and whether a protein helps.'),
  mc('p5', T, 'Oxygen and carbon dioxide cross the membrane by simple diffusion mainly because they are', [
    'large, polar molecules that cannot dissolve into the tails',
    'small and uncharged, dissolving directly into the bilayer',
    'fully charged ions that need a specific channel protein',
    'bulky macromolecules that need a vesicle to cross at all',
  ], 1, 'Small, nonpolar, uncharged molecules move directly through the hydrophobic interior unaided.'),
  mc('p6', T, 'A membrane is permeable to starch only. Inside the cell starch is 60% and glucose is 10%; outside starch is 10% and glucose is 40%. What happens?', [
    'Glucose diffuses out of the cell, since it has the steeper overall gradient',
    'Starch diffuses out, from 60% to 10%; glucose does not move at all',
    'Both starch and glucose diffuse out of the cell at the same time',
    'Nothing moves at all, since the two separate gradients simply cancel out',
  ], 1, 'Permeability comes first: since only starch can cross, it moves down its own gradient regardless of the unrelated glucose numbers.', 'diffusion-starch'),
  mc('p7', T, 'A student decides which molecule will diffuse purely by comparing the size of each gradient, without first checking permeability. What is the flaw?', [
    'There is no flaw; gradient size is the only factor that matters',
    'A steep gradient across an impermeable membrane still produces zero net diffusion',
    'Diffusion never actually depends on gradients',
    'Only active transport depends on gradients',
  ], 1, 'Permeability is a prerequisite — a molecule cannot diffuse across a membrane it cannot cross, however large its gradient is.'),
  mc('p8', T, 'Osmosis is best defined as', [
    'active transport of dissolved ions using cellular ATP energy',
    'simple diffusion of water across a selectively permeable membrane',
    'bulk movement of many dissolved solutes at once using vesicles',
    'a type of facilitated diffusion that always requires ATP',
  ], 1, 'Osmosis is diffusion applied specifically to water, moving down its own water-potential gradient.'),
  mc('p9', T, 'A solution with a high solute concentration has', [
    'high water potential, since solutes create free water',
    'low water potential, since dissolved solute reduces free water',
    'no water potential at all',
    'the same water potential as distilled water'
  ], 1, 'Water potential runs opposite solute concentration: more solute means less free water and lower water potential.'),
  mc('p10', T, 'Water always moves during osmosis', [
    'from low water potential to high, using ATP',
    'from high water potential to low, using no ATP',
    'from high solute directly to low solute',
    'wherever a pump happens to direct it',
  ], 1, 'Osmosis follows the water-potential gradient exactly like other passive processes: high to low, no energy needed.'),
  mc('p11', T, 'A dialysis bag holding 0.8 M sucrose is placed in distilled water and weighed periodically. What is the expected result?', [
    'The bag loses mass steadily as water slowly leaves it over time',
    'The bag gains mass as water enters, since the beaker has higher water potential',
    'The bag\'s mass stays exactly fixed, since sucrose cannot cross the membrane',
    'The bag gains mass only because sucrose molecules diffuse outward into the beaker',
  ], 1, 'Distilled water has the highest possible water potential, so water enters the bag while the sucrose stays trapped inside.'),
  mc('p12', T, 'A dialysis bag starts at 22.0 g and after 30 minutes in a hypertonic bath weighs 18.7 g. The percent change in mass is', [
    '+15.0%',
    '−15.0%',
    '−3.3%',
    '+3.3%',
  ], 1, '(18.7 − 22.0) / 22.0 × 100 ≈ −15.0%. The negative sign shows the bag lost mass as water left it.'),
  mc('p13', T, 'Several dialysis bags with sucrose concentrations from 0.0 M to 1.0 M each sit in their own beaker of plain distilled water. As internal molarity rises, percent mass gain also rises. Why?', [
    'A more concentrated bag is more hypertonic to the constant bath, so a bigger gradient pulls in more water',
    'Sucrose molecules are gradually leaking out of the more concentrated bags and into the surrounding water',
    'Higher-molarity bags somehow become steadily less permeable to water as their concentration rises',
    'Molarity has no real relationship at all to water movement in this particular lab setup',
  ], 0, 'Every bag sits in identical distilled water, so a more concentrated bag has a larger solute gap relative to the bath and draws in more water.'),
  mc('p14', T, 'A solution is isotonic to a cell. This means', [
    'outside solute concentration is higher than inside, so water flows steadily out',
    'solute is equal inside and out, so water enters and exits at equal rates',
    'outside solute concentration is lower than inside, so the cell gradually swells',
    'no water at all is present anywhere in the surrounding solution',
  ], 1, 'Isotonic describes equal solute concentrations on both sides — dynamic equilibrium with no net volume change.'),
  mc('p15', T, 'An animal cell placed in a hypotonic solution will most likely', [
    'shrivel as water leaves',
    'swell and risk cytolysis as water enters',
    'stay completely unchanged',
    'immediately grow a protective wall',
  ], 1, 'Lower outside solute means water enters down its water-potential gradient, and an animal cell has no wall to resist swelling.', 'animal-tonicity'),
  mc('p16', T, 'Red blood cells for a transfusion are kept in isotonic saline rather than distilled water because distilled water', [
    'is hypertonic to the cells and would cause them to shrivel up',
    'is hypotonic to the cells and could cause them to swell and burst',
    'contains far too much dissolved salt for the cells to tolerate',
    'actively pumps water out of the cells using cellular ATP energy',
  ], 1, 'Distilled water has essentially no solute, making it hypotonic to the cell interior and risking cytolysis.'),
  mc('p17', T, 'Plasmolysis in a plant cell placed in a hypertonic solution refers to', [
    'the central vacuole swelling until the cell is turgid',
    'the membrane pulling away from the wall as water leaves',
    'complete dissolving of the cell wall',
    'active pumping of water out using ATP',
  ], 1, 'Water exits down its gradient; the flexible membrane shrinks inward, away from the rigid, unchanging wall.', 'plant-tonicity'),
  mc('p18', T, 'A wilted plant perks back up after watering because its cells shift from', [
    'a fully turgid state toward a merely isotonic, limp state',
    'low turgor pressure toward high turgor pressure as water enters a hypotonic soil',
    'a hypertonic soil toward an even more hypertonic one over time',
    'a bursting, animal-like state toward a shriveled, dehydrated state',
  ], 1, 'Plentiful soil water is hypotonic relative to root cells, so water enters the vacuole, turgor rises, and the plant stands upright again.', 'plant-tonicity'),
  mc('p19', T, 'A plant cell can tolerate a hypotonic bath without bursting, while a similar animal cell risks cytolysis, mainly because', [
    'plant cells actively pump all of the incoming water straight back out using ATP',
    'the rigid wall resists expansion once the vacuole is full, generating turgor that opposes further swelling',
    'plant cells simply have no water-potential gradient across their membrane at all',
    'plant cell membranes are completely and permanently impermeable to water molecules',
  ], 1, 'The wall provides a hard physical limit on expansion, a safeguard an animal cell does not have.'),
  mc('p20', T, 'An Amoeba living in pond water, without any specialized organelle, would face', [
    'plasmolysis from a hypertonic pond environment slowly pulling water out',
    'continuous water influx and eventual cytolysis, since pond water is hypotonic to its cytoplasm',
    'immediate and total dehydration of its entire watery cytoplasm',
    'no osmotic risk at all, since pond water is roughly isotonic to it',
  ], 1, 'Freshwater is hypotonic to a protist\'s cytoplasm, creating constant pressure to take in water.'),
  mc('p21', T, 'A contractile vacuole in a freshwater protist functions to', [
    'store extra food reserves for later use by the cell',
    'actively expel the excess water that continuously enters by osmosis',
    'carry out photosynthesis using chlorophyll inside the protist',
    'anchor the cytoskeleton firmly to the plasma membrane',
  ], 1, 'Since freshwater protists constantly gain water by osmosis, the contractile vacuole periodically pumps that excess back out.'),
  mc('p22', T, 'An egg sits in a hypotonic solution. Which other statement about the same pair must also be true?', [
    'The solution is hypertonic to the egg',
    'The egg is hypertonic relative to the solution',
    'The egg and the solution are isotonic',
    'The egg has no solute of its own',
  ], 1, 'Hypo/hypertonic are relative, paired terms. If the solution is hypotonic to the egg, the egg has more solute and is hypertonic relative to it.'),
  mc('p23', T, 'A cell holding 5% solute sits in a bath of 20% solute, with a membrane permeable only to water. What happens?', [
    'The bath is hypotonic, so water enters the cell',
    'The bath is hypertonic, so water leaves and the cell shrinks',
    'The cell and bath are isotonic',
    'The cell swells and bursts',
  ], 1, 'Since 20% > 5%, the bath has more solute and lower water potential, drawing water out of the cell.'),
  mc('p24', T, 'Facilitated diffusion differs from simple diffusion in that facilitated diffusion', [
    'requires a protein channel in order for any movement to occur at all',
    'needs a transport protein but is still powered only by the gradient, not by ATP',
    'always costs ATP energy simply because a protein happens to be involved',
    'is never classified as a genuine form of passive transport in any way',
  ], 1, 'The protein is a helper, not an energy source — movement is still downhill and free.', 'channel-carrier'),
  mc('p25', T, 'Glucose typically enters a cell by facilitated diffusion rather than simple diffusion because glucose is', [
    'a small, nonpolar gas molecule much like oxygen or carbon dioxide',
    'large and polar, unable to cross the bilayer core efficiently on its own',
    'a fully charged ion that always needs a dedicated channel protein',
    'not really considered a true dissolved solute at all',
  ], 1, 'Glucose\'s size and polarity make it a poor candidate for direct diffusion, even though it is still moving downhill.'),
  mc('p26', T, 'A physiologist measures glucose entering red blood cells across a range of outside concentrations. At low concentrations the rate rises steeply; at high concentrations it plateaus. This plateau most strongly suggests', [
    'glucose is diffusing simply, which has no upper limit',
    'the transport proteins moving glucose have become saturated',
    'glucose transport needs ATP and stopped once ATP ran out',
    'the membrane became completely impermeable to glucose',
  ], 1, 'A rate that levels off at high concentration is the signature of a limited number of transport proteins becoming saturated, unlike unassisted diffusion through the lipid bilayer.'),
  mc('p27', T, 'If a molecule crosses purely by simple diffusion rather than through a limited set of transport proteins, its entry rate as concentration rises should', [
    'plateau once carrier proteins are all occupied',
    'keep rising roughly in proportion, without leveling off',
    'immediately drop to zero',
    'require ATP once concentration gets high enough',
  ], 1, 'With no finite number of protein "slots" to saturate, simple diffusion scales with the gradient rather than plateauing.'),
  mc('p28', T, 'Aquaporins speed water movement compared to unassisted diffusion, yet this still counts as passive transport because', [
    'aquaporins actively pump water molecules across using cellular ATP energy',
    'water still moves down its own gradient at no energy cost; the protein only offers a faster route',
    'aquaporins move water molecules uphill, against their own concentration gradient',
    'aquaporins are simply peripheral proteins that have no actual pore at all',
  ], 1, 'Speed does not decide active versus passive — direction and energy use do. Aquaporins just provide a quicker path downhill.'),
  mc('p29', T, 'A membrane divides a beaker into side A (0.5 M sucrose) and side B (0.1 M sucrose) and is permeable to water only. Which side has higher water potential, and which way does water move?', [
    'A is higher; water moves A to B',
    'B is higher; water moves B to A',
    'Both sides are equal; there is no net movement',
    'A is higher, but no water moves since sucrose cannot cross',
  ], 1, 'Side B, with less solute, has more free water and a higher water potential, so water moves toward side A.', 'osmosis-beaker'),
  mc('p30', T, 'A cell holds 90% water while the surrounding solution holds only 10% water, with a membrane permeable to water only. What follows?', [
    'The outside is hypotonic, so water enters the cell',
    'The outside is hypertonic, so water leaves and the cell shrinks',
    'The cell and the outside are isotonic',
    'No water moves, since the solute cannot cross',
  ], 1, 'Less water outside means more solute outside, so the outside is hypertonic and water flows out toward it.', 'hypertonic-cell'),
  mc('p31', T, 'In that same 90%-water-cell / 10%-water-outside scenario, how should the CELL be described relative to the outside?', [
    'The cell is hypertonic to the solution, since it holds noticeably more solute overall',
    'The cell is hypotonic to the solution, since it holds less solute and more water than the bath',
    'The cell is isotonic to the solution, with exactly equal solute on both sides',
    'Tonicity terms can never correctly be used to describe a cell by itself',
  ], 1, 'Tonicity describes whichever side you name. The cell has more water than the bath, so the cell is the hypotonic side, even though water still flows toward the hypertonic outside.', 'hypertonic-cell'),
  mc('p32', T, 'A U-tube membrane, permeable to water only, separates 12% salt water (left) from 3% salt water (right). Net water flow will be', [
    'left to right, toward more free water',
    'right to left, toward the 12% side',
    'zero, since salt cannot cross either side',
    'right to left, because salt actively pumps water',
  ], 1, 'The 3% side has more free water (higher water potential), so water moves passively toward the more concentrated, lower water-potential side.'),
  mc('p33', T, 'Rank water potential from HIGHEST to LOWEST: distilled water, 0.3 M sucrose, 0.9 M sucrose.', [
    '0.9 M, then 0.3 M, then distilled water',
    'Distilled water, then 0.3 M, then 0.9 M',
    'All three are identical',
    '0.3 M, then distilled water, then 0.9 M',
  ], 1, 'Water potential falls as solute rises, so pure water sits highest and the most concentrated solution sits lowest.'),
  mc('p34', T, 'A cucumber soaked overnight in concentrated brine turns limp and shrunken. This is best explained by', [
    'active transport steadily pumping water out of the cells using ATP energy',
    'osmosis: the brine is hypertonic to the cucumber cells, so water leaves them passively',
    'facilitated diffusion of salt molecules directly into the cucumber cells',
    'the cucumber cells slowly undergoing cytolysis and eventually bursting apart',
  ], 1, 'A concentrated brine is hypertonic to plant tissue, so water exits by osmosis with no energy input required.'),
  mc('p35', T, 'Amino acids entering a cell down their gradient, with the help of a membrane protein and no ATP, illustrates', [
    'simple diffusion',
    'facilitated diffusion',
    'active transport',
    'exocytosis',
  ], 1, 'A protein-assisted, downhill, energy-free movement of a solute is facilitated diffusion by definition.'),
  mc('p36', T, 'Which of the following would NOT be explained by passive transport alone?', [
    'Oxygen diffusing in where its concentration is lower outside',
    'Water entering a cell placed in a hypotonic bath',
    'Glucose moving against its own gradient with no ATP used',
    'Glucose moving down its gradient using a carrier protein',
  ], 2, 'Moving a solute uphill with zero energy input violates the basic rule of passive transport and is physically impossible without ATP.'),
  mc('p37', T, 'Simple diffusion, facilitated diffusion, and osmosis are related because', [
    'they are three completely unrelated processes each using a different energy source',
    'all three move down a gradient with no ATP, differing mainly in what moves and whether a protein helps',
    'only osmosis is truly passive; the other two both require ATP to occur',
    'facilitated diffusion moves solutes uphill while the other two move them steadily downhill',
  ], 1, 'All three are passive and gradient-driven, differing only in the identity of what moves and whether a helper protein is involved.'),
  mc('p38', T, 'If solute is already equal on both sides of a membrane, net diffusion of that solute becomes', [
    'reversed, switching direction repeatedly',
    'zero, even though individual molecules keep crossing randomly in both directions',
    'faster, since there is no gradient slowing it down',
    'impossible, because the membrane seals itself',
  ], 1, 'Equal concentrations mean equilibrium: net movement is zero, though molecules never actually stop moving.'),
  multi('p39', T, 'Select ALL of the following classified as passive transport.', [
    'Simple diffusion of oxygen',
    'Osmosis of water',
    'Facilitated diffusion of glucose via a carrier',
    'The sodium-potassium pump',
  ], [0, 1, 2], 'The sodium-potassium pump requires ATP and moves ions against their gradients, making it active, not passive.'),
  multi('p40', T, 'Select ALL correct statements about hypertonic and hypotonic solutions.', [
    'A hypertonic solution has more solute than the cell, so water tends to leave the cell',
    'A hypotonic solution has less solute than the cell, so water tends to enter the cell',
    'These terms describe an absolute property of a solution on its own',
    'A hypotonic environment benefits a healthy, turgid plant cell',
  ], [0, 1, 3], 'Tonicity terms are always relative comparisons between two things, never an absolute property of a single solution.'),
  mc('p41', T, 'Elodea placed in concentrated saltwater shows chloroplasts pulling away from the wall under a microscope. This is best explained by', [
    'cytolysis from a hypotonic environment',
    'plasmolysis from a hypertonic environment pulling water out',
    'active transport of chloroplasts out of the cell',
    'facilitated diffusion of salt into the chloroplasts',
  ], 1, 'Saltwater is hypertonic to the cytoplasm, so water exits by osmosis and the membrane pulls away from the rigid wall.'),
  mc('p42', T, 'To find the sucrose concentration that is isotonic to a plant tissue using the dialysis-bag method, look for the concentration where', [
    'percent change in mass is close to zero',
    'percent change in mass is the largest positive value',
    'percent change in mass is the largest negative value',
    'mass change is irrelevant to tonicity',
  ], 0, 'At the isotonic point, water enters and exits at equal rates, so the bag shows little to no net mass change.'),
  mc('p43', T, 'Predicting the direction and likelihood of net passive movement for a solute requires knowing', [
    'only whether ATP happens to be available in the cell at that moment',
    'both the membrane\'s permeability to that solute and the size of its gradient',
    'only the solute\'s color and nothing else meaningful about it',
    'nothing measurable at all about either the solute or the membrane',
  ], 1, 'A gradient with no permeability, or permeability with no gradient, both produce zero net movement — both factors matter together.'),
  mc('p44', T, 'Which pairing below is mismatched?', [
    'Simple diffusion — no protein needed, small nonpolar molecules',
    'Facilitated diffusion — protein needed, still no ATP',
    'Osmosis — diffusion of water specifically',
    'Osmosis — needs ATP whenever a large volume of water moves',
  ], 3, 'Osmosis never requires ATP, no matter how much water is moving.'),
  mc('p45', T, 'A cell bathed in a solution with solute identical to its cytoplasm will, at that moment,', [
    'progressively swell in volume over a long period of time',
    'progressively shrink in volume over a long period of time',
    'show water moving both directions with no net change in volume',
    'stop all water movement across the membrane completely',
  ], 2, 'Isotonic conditions produce dynamic equilibrium: water keeps moving both ways, but the rates match, so volume stays constant.'),
  mc('p46', T, 'A cell placed in a solution shrinks noticeably over several minutes. The most likely explanation, assuming a water-only-permeable membrane, is that the solution is', [
    'hypertonic to the cell',
    'hypotonic to the cell',
    'isotonic to the cell',
    'made of pure water with zero solute',
  ], 0, 'Shrinking indicates net water loss, which happens only when the surrounding solution is hypertonic (has more solute) relative to the cell.'),
]
