import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'active' as const

export const ACTIVE_QUESTIONS: BioPracticeQuestion[] = [
  mc('a1', T, 'Active transport requires', [
    'no energy, high → low',
    'energy (ATP); molecules move AGAINST / UP the gradient (low → high)',
    'only osmosis',
    'a cell wall of cellulose',
  ], 1, 'If it goes low to high, it costs ATP.'),
  mc('a2', T, 'Passive vs active: direction of molecules', [
    'passive low → high; active high → low',
    'passive high → low (with gradient); active low → high (against gradient)',
    'both only high → low',
    'both only low → high',
  ], 1, 'Gradient direction is the first compare/contrast point.'),
  mc('a3', T, 'Passive vs active: energy', [
    'both need ATP',
    'passive needs none; active needs ATP',
    'active needs none; passive needs ATP',
    'neither ever uses proteins',
  ], 1, 'Energy is the second compare point.'),
  mc('a4', T, 'Structures often involved in bulk active transport are', [
    'cellulose fibers only',
    'vesicles that fuse with or pinch from the membrane',
    'plasmids only',
    'capsids only',
  ], 1, 'Endocytosis and exocytosis use vesicles. Pumps use transport proteins.'),
  mc('a5', T, 'Exocytosis is', [
    'passive osmosis of proteins',
    'active bulk movement OUT of the cell using vesicles that fuse with the membrane',
    'cell-drinking',
    '3 Na⁺ in and 2 K⁺ out',
  ], 1, 'Exo = exiting. Needs ATP. Examples: hormone secretion, protein secretion, nerve-cell communication.', 'endo-exo'),
  mc('a6', T, '“Exo” in exocytosis means', [
    'into the cell',
    'exiting the cell',
    'equilibrium',
    'eukaryote only',
  ], 1, 'Vesicle fuses with plasma membrane and dumps contents outside.'),
  mc('a7', T, 'Which is an exocytosis example from the notes?', [
    'O₂ simple diffusion',
    'hormone or protein secretion, or nerve-cell communication',
    'osmosis into a hypotonic plant cell',
    'binary fission',
  ], 1, 'Bulk export of big stuff cells made.'),
  mc('a8', T, 'Right after an exocytic vesicle fuses, the vesicle membrane', [
    'disappears into the nucleus',
    'becomes part of the plasma membrane',
    'turns into peptidoglycan',
    'becomes a capsid',
  ], 1, 'Fusion adds membrane to the cell surface.', 'endo-exo'),
  mc('a9', T, 'Endocytosis is', [
    'simple diffusion of gases',
    'active bulk movement of large molecules INTO the cell using vesicles',
    'water leaving a hypertonic cell only',
    'facilitated diffusion of glucose',
  ], 1, 'Endo = into the cell. Three types: pinocytosis, phagocytosis, receptor-mediated.', 'endo-exo'),
  mc('a10', T, 'The three types of endocytosis are', [
    'simple, osmosis, facilitated',
    'pinocytosis, phagocytosis, and receptor-mediated',
    'Hooke, Schwann, Virchow',
    'tight, gap, and plasmodesmata',
  ], 1, 'All are active and INTO the cell.'),
  mc('a11', T, 'Pinocytosis means', [
    'cell-eating of bacteria',
    'cell-drinking: taking in a small amount of extracellular fluid with molecules',
    'pumping 2 K⁺ in',
    'making a cell wall',
  ], 1, 'Usually fats, vitamins, or waste molecules.'),
  mc('a12', T, 'Phagocytosis means', [
    'cell-drinking of vitamins',
    'cell-eating: engulfing large particles like food or bacteria into vesicles',
    'osmosis only',
    'cholesterol buffering',
  ], 1, 'Macrophages engulfing bacteria; immune cells engulfing yeast.'),
  mc('a13', T, 'A macrophage engulfing bacteria is', [
    'osmosis',
    'phagocytosis (active endocytosis)',
    'simple diffusion',
    'facilitated diffusion of O₂',
  ], 1, 'Classic immune-system phagocytosis.'),
  mc('a14', T, 'Receptor-mediated endocytosis', [
    'uses receptor proteins (integral) that bind materials like hormones and cholesterol, then the cell engulfs them',
    'is passive and needs no match in shape',
    'is only for O₂',
    'is binary fission',
  ], 0, 'Shape of the receptor is essential — lock and key for the signal.'),
  mc('a15', T, 'WHY does receptor shape matter for receptor-mediated endocytosis?', [
    'It doesn’t',
    'The receptor must fit the molecule (hormone, cholesterol) to recognize and then engulf it',
    'Shape only matters for cellulose',
    'Shape only matters in viruses’ peptidoglycan',
  ], 1, 'Wrong shape = no binding = no intake of that signal/molecule.'),
  mc('a16', T, 'Compare exocytosis and endocytosis.', [
    'Both are passive',
    'Both are active bulk vesicle transport; exo = out, endo = in',
    'Exo is osmosis; endo is diffusion',
    'Both move O₂ only',
  ], 1, 'Direction of the vesicle cargo is the difference.'),
  mc('a17', T, 'The sodium-potassium pump uses ATP to', [
    'simple-diffuse glucose',
    'regulate Na⁺ and K⁺ concentrations (homeostasis of ions)',
    'make cellulose',
    'build a capsid',
  ], 1, 'A transport protein changes shape to move the ions.', 'nak-pump'),
  mc('a18', T, 'For every 2 K⁺ pumped INTO the cell, the pump moves', [
    '2 Na⁺ in',
    '3 Na⁺ OUT',
    '3 Na⁺ in',
    '2 glucose out',
  ], 1, '3 Na⁺ out, 2 K⁺ in. Remember 3 out / 2 in.', 'nak-pump'),
  mc('a19', T, 'The Na+/K+ pump makes the inside of the cell', [
    'slightly positive',
    'slightly negative',
    'have no ions',
    'hypertonic to all plant cells always',
  ], 1, 'More + charges leave (3 Na⁺) than enter (2 K⁺).', 'nak-pump'),
  mc('a20', T, '“Salty banana” means a cell has', [
    'high Na⁺ inside and high K⁺ outside',
    'high Na⁺ outside and high K⁺ inside',
    'equal Na⁺ and K⁺ everywhere',
    'no potassium ever',
  ], 1, 'Banana = potassium inside; salty = sodium outside.', 'nak-pump'),
  mc('a21', T, 'The Na+/K+ pump is a type of', [
    'simple diffusion',
    'active transport using a shape-changing transport protein',
    'osmosis',
    'phagocytosis of sodium metal',
  ], 1, 'Ions cannot simple-diffuse. Going against their gradients costs ATP.'),
  mc('a22', T, 'How does the Na+/K+ pump help homeostasis?', [
    'It keeps Na⁺ and K⁺ at the correct inside/outside concentrations and charge difference',
    'It makes glucose from CO₂',
    'It is a contractile vacuole in animal cells',
    'It builds the cell wall',
  ], 0, 'Nerve signals, cell volume, and ion balance depend on this pump.'),
  mc('a23', T, 'If the pump is blocked (no ATP), Na⁺ would', [
    'still be pumped out',
    'leak toward equilibrium and the “salty banana” gradients would collapse',
    'become O₂',
    'build peptidoglycan',
  ], 1, 'Active transport maintains gradients that diffusion would wipe out.'),
  mc('a24', T, 'Pinocytosis vs phagocytosis', [
    'pino = drinking small fluid/molecules; phago = eating large particles/cells',
    'pino uses ATP; phago does not',
    'both are osmosis',
    'pino is only in plants’ plasmodesmata',
  ], 0, 'Both endocytosis, both active.'),
  mc('a25', T, 'Which process exports a protein the cell just made?', [
    'phagocytosis',
    'exocytosis',
    'osmosis',
    'facilitated diffusion of the entire protein through tails',
  ], 1, 'Proteins are too big to simple-diffuse. Vesicle fusion dumps them out.'),
  mc('a26', T, 'Cholesterol entering after binding a membrane receptor is', [
    'simple diffusion of an ion',
    'receptor-mediated endocytosis',
    'turgor pressure',
    'binary fission',
  ], 1, 'Notes specifically list hormones and cholesterol for this pathway.'),
  mc('a27', T, 'A white blood cell eating a pathogen is closest to', [
    'pinocytosis',
    'phagocytosis',
    'osmosis',
    'the fluid mosaic becoming solid',
  ], 1, 'Cell-eating large particles.'),
  mc('a28', T, 'Capillary cells taking in a sip of extracellular fluid is closest to', [
    'phagocytosis of yeast',
    'pinocytosis',
    'the Na+/K+ pump only',
    'plasmolysis',
  ], 1, 'Notes show pinocytosis across a capillary cell.'),
  mc('a29', T, 'Which statement is false?', [
    'Endocytosis and exocytosis both need ATP',
    'The Na+/K+ pump needs ATP',
    'Facilitated diffusion of glucose down its gradient needs ATP',
    'Phagocytosis uses vesicles',
  ], 2, 'Facilitated diffusion is still passive.'),
  mc('a30', T, 'Bulk transport means', [
    'O₂ sneaking between tails',
    'moving many/large materials with vesicles (endo/exocytosis)',
    'only aquaporins',
    'only peripheral proteins',
  ], 1, 'Pumps move ions; vesicles move bulk cargo.'),
  multi('a31', T, 'Choose ALL that are active transport.', [
    'exocytosis',
    'endocytosis (all 3 types)',
    'sodium-potassium pump',
    'osmosis of water down its gradient',
  ], [0, 1, 2], 'Osmosis is passive.'),
  multi('a32', T, 'Choose ALL true comparisons of passive vs active.', [
    'Passive: high → low, no ATP',
    'Active: low → high, ATP',
    'Active may use pumps or vesicles',
    'Passive includes phagocytosis',
  ], [0, 1, 2], 'Phagocytosis is active bulk intake.'),
  multi('a33', T, 'Choose ALL types of endocytosis.', [
    'pinocytosis',
    'phagocytosis',
    'receptor-mediated',
    'exocytosis',
  ], [0, 1, 2], 'Exocytosis is the opposite direction.'),
  mc('a34', T, 'Insulin being recognized then engulfed would use', [
    'simple diffusion',
    'receptor-mediated endocytosis because insulin is a hormone signal',
    'plasmolysis',
    'binary fission',
  ], 1, 'Receptors exist to bind hormones (TRACIE) and can trigger endocytosis.'),
  mc('a35', T, '3 Na⁺ out / 2 K⁺ in requires the protein to', [
    'stay a rigid open pore like a always-open aquaporin',
    'change shape, using ATP, to move ions against their gradients',
    'dissolve the bilayer',
    'become a chloroplast',
  ], 1, 'Notes: a transport protein (channel or carrier) changes shape to facilitate ion movement — and this pump is active.', 'nak-pump'),
  mc('a36', T, 'After many pump cycles, outside the cell you should find relatively', [
    'high K⁺ and low Na⁺',
    'high Na⁺ and low K⁺',
    'no ions',
    'only glucose',
  ], 1, 'Salty outside, potassium banana inside.'),
  mc('a37', T, 'Nerve-cell communication listed with exocytosis is about', [
    'osmosis of Na⁺ without vesicles',
    'releasing signal chemicals from vesicles at the membrane',
    'building peptidoglycan',
    'Hooke seeing cork',
  ], 1, 'Secretion = exocytosis.'),
  mc('a38', T, 'Which needs a vesicle, not just a pump protein?', [
    'moving 3 Na⁺ across',
    'exporting a large protein hormone',
    'O₂ leaving a lung cell',
    'water leaving via aquaporins',
  ], 1, 'Huge cargo → vesicle. Ions → pump. Gases/water → diffusion/osmosis.'),
  mc('a39', T, 'Endocytosis vs exocytosis membrane-area effect', [
    'endocytosis removes a patch of membrane inward; exocytosis adds membrane',
    'neither touches the membrane',
    'both are simple diffusion',
    'both only happen in viruses',
  ], 0, 'Vesicle traffic remodels the plasma membrane.', 'endo-exo'),
  mc('a40', T, 'If a molecule moves from low concentration to high concentration through a protein, you should assume', [
    'osmosis',
    'active transport (ATP)',
    'simple diffusion',
    'the cell is dead and at equilibrium',
  ], 1, 'Against the gradient = pay ATP.'),
  mc('a41', T, 'Pinocytosis cargo is usually', [
    'whole bacteria',
    'small amounts of fluid with fats, vitamins, or waste',
    'entire organelles ejected',
    'cellulose fibers',
  ], 1, 'Drinking, not eating.'),
  mc('a42', T, 'Phagocytosis cargo is usually', [
    'O₂ molecules',
    'large particles such as food or bacteria',
    'only H₂O',
    'only Na⁺',
  ], 1, 'Eating.'),
  mc('a43', T, 'Which protein type starts receptor-mediated endocytosis?', [
    'an integral receptor protein that binds the target',
    'cellulose synthase only',
    'a capsid',
    'peptidoglycan',
  ], 0, 'Integral receptor binds, then membrane engulfs.'),
  mc('a44', T, 'A test diagram of vesicles approaching the membrane from inside and fusing is', [
    'endocytosis',
    'exocytosis',
    'osmosis',
    'binary fission',
  ], 1, 'Inside → out = exo.', 'endo-exo'),
  mc('a45', T, 'A test diagram of the membrane dimpling inward around cargo is', [
    'exocytosis',
    'endocytosis',
    'simple diffusion of CO₂',
    'turgor',
  ], 1, 'Outside → in = endo.', 'endo-exo'),
  multi('a46', T, 'Choose ALL that correctly describe the Na+/K+ pump.', [
    '3 Na⁺ out, 2 K⁺ in',
    'uses ATP',
    'inside becomes slightly negative',
    'moves ions high → low with no energy',
  ], [0, 1, 2], 'It moves ions against their gradients.'),
  mc('a47', T, 'Facilitated diffusion and the Na+/K+ pump both may use proteins, but they differ because', [
    'only the pump uses ATP and goes against the ion gradients',
    'only facilitated diffusion uses ATP',
    'neither uses a protein',
    'both go low → high',
  ], 0, 'Protein is not the same as energy.'),
  mc('a48', T, 'Which process would a cell use to take in a specific hormone and ignore a similarly sized random molecule?', [
    'simple diffusion',
    'receptor-mediated endocytosis',
    'cytolysis',
    'plasmolysis',
  ], 1, 'Specificity comes from receptor shape.'),
  mc('a49', T, 'Active transport is required to build/keep a gradient. Passive transport', [
    'also builds gradients from nothing',
    'lets substances run down gradients the cell already has',
    'is the Na+/K+ pump',
    'always uses vesicles',
  ], 1, 'Pumps create order; diffusion spends it.'),
  mc('a50', T, 'Which list is only bulk active transport?', [
    'osmosis and simple diffusion',
    'endocytosis and exocytosis',
    'facilitated diffusion and aquaporins',
    'Hooke and Leeuwenhoek',
  ], 1, 'Bulk = vesicles. Pump is active but not “bulk cargo.”'),
]
