import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const R = 'reactions' as const
const C = 'carbs' as const
const L = 'lipids' as const
const P = 'proteins' as const
const N = 'nucleic' as const

export const MACRO_QUESTIONS: BioPracticeQuestion[] = [
  mc('r1', R, 'Organic compounds in biology are mainly', [
    'molecules with carbon-carbon and carbon-hydrogen bonds',
    'anything sold at a grocery store as “organic”',
    'only water and salt',
    'only metals',
  ], 0, 'Organic = carbon-based molecules of life, usually with C–C and C–H bonds. They are often large and contain C, H, O, N, P, and sometimes S.'),
  mc('r2', R, 'Which ones primarily are found in living things?', [
    'Only inorganic salts',
    'Organic compounds (macromolecules)',
    'Only helium gas',
    'Only pure metals',
  ], 1, 'Living things are built from organic macromolecules: carbs, lipids, proteins, nucleic acids.'),
  mc('r3', R, 'Is CO₂ organic or inorganic in this class?', [
    'Organic, because it has carbon',
    'Inorganic — it lacks C–H / C–C organic bonding like biomolecules',
    'A protein',
    'A nucleotide',
  ], 1, 'CO₂ has carbon but is treated as inorganic here. Organic biomolecules have C–C and C–H bonds.'),
  mc('r4', R, 'Carbon can form so many different molecules mainly because it can make how many covalent bonds?', [
    '1',
    '2',
    '4',
    '7',
  ], 2, 'Carbon has 4 valence electrons, so 4 bonding spots. That makes chains, branches, and rings.'),
  mc('r5', R, 'Carbon-based compounds typically come in which shapes?', [
    'Only triangles',
    'Straight chain, branched chain, and ring',
    'Only a double helix',
    'Only a bilayer',
  ], 1, 'Those three carbon skeletons show up over and over in biomolecules.'),
  mc('r6', R, 'The four macromolecules of life are', [
    'acids, bases, salts, and water',
    'carbohydrates, lipids, proteins, and nucleic acids',
    'starch, ice, oil, and glass',
    'H⁺, OH⁻, Na⁺, Cl⁻',
  ], 1, 'Carbs, lipids, proteins, nucleic acids — they run the body, store instructions, and supply energy.'),
  mc('r7', R, 'Macromolecules are made of C, H, O, N, P and sometimes S. That set of letters is', [
    'HONC',
    'CHONPS',
    'DNA only',
    'pH',
  ], 1, 'CHONPS = the elements of biomolecules.'),
  mc('r8', R, 'The single building blocks of macromolecules are called', [
    'polymers',
    'monomers',
    'organelles',
    'isotopes',
  ], 1, 'Monomer = one brick. Polymer = many bricks linked.'),
  mc('r9', R, 'The larger structures made when building blocks are bonded together are called', [
    'monomers',
    'polymers',
    'electrons',
    'solvents',
  ], 1, 'Polymers are many monomers bonded together. Lipids are the awkward exception (no true repeating monomer).'),
  mc('r10', R, 'Anabolic reactions', [
    'break molecules down and release energy',
    'build larger molecules from smaller units and USE energy',
    'are the same as hydrolysis',
    'only happen in dead cells',
  ], 1, 'Anabolic: A + B → AB. They use energy to synthesize large molecules.'),
  mc('r11', R, 'Catabolic reactions', [
    'build polymers and use energy',
    'break reactants down and RELEASE energy',
    'are dehydration synthesis',
    'join amino acids',
  ], 1, 'Catabolic: AB → A + B. Digestion is a classic example.'),
  mc('r12', R, 'Dehydration synthesis is', [
    'when a polymer is broken and water is added',
    'when two monomers are linked and water is removed',
    'ice melting',
    'an acid becoming a base',
  ], 1, 'Build + remove water. It is anabolic. An H comes off one piece and an OH off the other.'),
  mc('r13', R, 'Hydrolysis is', [
    'when two monomers are linked and water is removed',
    'when a polymer is broken into monomers and water is added',
    'cohesion',
    'a hydrogen bond',
  ], 1, 'Hydro- = water, -lysis = to cut. Catabolic. Digestion uses hydrolysis.'),
  mc('r14', R, 'Is hydrolysis anabolic or catabolic?', [
    'Anabolic',
    'Catabolic',
    'Neither — it is cohesion',
    'It is a pH scale',
  ], 1, 'Breaking bigger into smaller = catabolic.'),
  mc('r15', R, 'Is dehydration synthesis anabolic or catabolic?', [
    'Catabolic',
    'Anabolic',
    'Only a lipid reaction',
    'A type of ice',
  ], 1, 'Building larger molecules = anabolic.'),
  mc('r16', R, 'Glucose + fructose → sucrose + H₂O is', [
    'hydrolysis',
    'dehydration synthesis',
    'denaturation',
    'neutralization',
  ], 1, 'Two sugars join and water is produced = dehydration synthesis. The bond is a glycosidic linkage.'),
  mc('r17', R, '1 dipeptide + H₂O → 2 amino acids is', [
    'dehydration synthesis',
    'hydrolysis',
    'anabolic building',
    'ice floating',
  ], 1, 'Water is added and the polymer splits = hydrolysis.'),
  mc('r18', R, 'This diagram shows monomers joining and water leaving. The reaction is', [
    'hydrolysis',
    'dehydration synthesis',
    'adhesion',
    'denaturation',
  ], 1, 'Join two pieces, kick water out = dehydration synthesis (anabolic).', 'dehydration'),
  mc('r19', R, 'This diagram shows water added and a chain splitting. The reaction is', [
    'dehydration synthesis',
    'hydrolysis',
    'capillary action',
    'surface tension',
  ], 1, 'Add water to break = hydrolysis (catabolic).', 'hydrolysis'),
  mc('r20', R, 'In dehydration synthesis, what is removed from the two monomers?', [
    'A full glucose from each',
    'H from one and OH from the other (which become H₂O)',
    'The R groups',
    'All carbon atoms',
  ], 1, 'Every new bond made this way removes one water.'),
  mc('r21', R, 'In a carbon skeleton diagram, carbons are found', [
    'only in the middle of lines',
    'on the ends and bends (each pointy end is a C)',
    'never in lipids',
    'only in water',
  ], 1, 'You will not be asked to draw skeletons, but you should recognize zig-zag lipid/carb diagrams.'),
  multi('r22', R, 'Choose ALL that are organic macromolecules of life.', [
    'Carbohydrates',
    'Lipids',
    'Proteins',
    'NaCl table salt',
  ], [0, 1, 2], 'The big four are carbs, lipids, proteins, and nucleic acids. Table salt is inorganic.'),
  multi('r23', R, 'Choose ALL statements true of dehydration synthesis.', [
    'It is anabolic',
    'Water is removed',
    'It builds larger molecules',
    'It is how digestion breaks food',
  ], [0, 1, 2], 'Digestion is hydrolysis (add water, break down), the opposite reaction.'),
  mc('c1', C, 'Monosaccharides are monomers of', [
    'proteins',
    'nucleic acids',
    'carbohydrates',
    'lipids',
  ], 2, 'Carbs are built from monosaccharides (simple sugars).'),
  mc('c2', C, 'Disaccharides and polysaccharides are polymers of', [
    'lipids',
    'carbohydrates',
    'proteins',
    'nucleic acids',
  ], 1, 'Two sugars = disaccharide. Many sugars = polysaccharide.'),
  mc('c3', C, 'Carbohydrates are made of', [
    'C, H, O, N, P',
    'C, H, and O in a ring (often a CH₂O ratio)',
    'only nitrogen',
    'only phosphorus',
  ], 1, 'Carbs = CHO, often rings, names often end in -ose.'),
  mc('c4', C, 'The typical structure of a monosaccharide is', [
    'four fused rings',
    'a 5- or 6-carbon ring',
    'a phosphate head and two tails',
    'a double helix',
  ], 1, 'Simple sugars form single carbon rings. Glucose is the classic hexose ring.'),
  mc('c5', C, 'The formula for glucose is', [
    'H₂O',
    'C₆H₁₂O₆',
    'NaCl',
    'CH₄',
  ], 1, 'Glucose is C₆H₁₂O₆ — a monosaccharide the body can metabolize.'),
  mc('c6', C, 'Two common monosaccharides are', [
    'starch and cellulose',
    'glucose and fructose',
    'DNA and RNA',
    'estrogen and testosterone',
  ], 1, 'Glucose, galactose, and fructose are the common monosaccharides.'),
  mc('c7', C, 'When two monosaccharides bond through dehydration synthesis they form a ________ held by a ________.', [
    'triglyceride; ester linkage',
    'disaccharide; glycosidic linkage',
    'dipeptide; peptide bond',
    'nucleotide; hydrogen bond',
  ], 1, 'Sugar-to-sugar bond = glycosidic linkage.'),
  mc('c8', C, 'The main job of carbohydrates is', [
    'long-term energy storage',
    'short-term / quick energy',
    'storing DNA',
    'making cell membranes only',
  ], 1, 'Carbs are quick energy. Lipids are long-term storage.'),
  mc('c9', C, 'Quick energy, plant cell walls (cellulose), and cell-surface identification are functions of', [
    'lipids',
    'carbohydrates',
    'nucleic acids',
    'steroids only',
  ], 1, 'Carbs fuel you, cellulose builds plant walls, and some carbs sit on membranes for ID.'),
  mc('c10', C, 'Sugars, fruits, crackers, pasta, and bread are examples of', [
    'proteins',
    'lipids',
    'carbohydrates',
    'nucleic acids',
  ], 2, 'Those foods are carb-heavy.'),
  mc('c11', C, 'Starch is', [
    'animal glucose storage in liver and muscle',
    'plant energy storage',
    'plant cell walls that animals cannot digest',
    'fungi cell walls',
  ], 1, 'Starch = plant energy (potatoes, rice, pasta). Digestible with amylase.'),
  mc('c12', C, 'Glycogen is', [
    'plant cell walls',
    'animal glucose storage in liver and muscle',
    'a steroid hormone',
    'DNA',
  ], 1, 'Glycogen reserves last about 24 hours fasting, or about an hour of hard exercise.'),
  mc('c13', C, 'Cellulose is', [
    'how animals store sugar',
    'plant cell-wall fiber that animals cannot digest',
    'a nucleotide',
    'olive oil',
  ], 1, 'Cellulose is tough and fibrous. Cows need microbes to help break it down.'),
  mc('c14', C, 'Chitin is a polysaccharide found in', [
    'human liver',
    'fungi cell walls and insect/crustacean exoskeletons',
    'olive oil',
    'DNA',
  ], 1, 'Chitin gives structure to fungi and arthropods.'),
  mc('c15', C, 'Peptidoglycan is a polysaccharide in', [
    'plant fruit',
    'bacterial cell walls',
    'butter',
    'RNA',
  ], 1, 'It gives bacteria structural support.'),
  mc('c16', C, 'The body can only metabolize sugars in ______ form.', [
    'polysaccharide',
    'monosaccharide',
    'triglyceride',
    'steroid',
  ], 1, 'Enzymes must hydrolyze starch/glycogen down to monosaccharides first.'),
  mc('c17', C, 'Sucrose, lactose, and maltose are', [
    'monosaccharides',
    'disaccharides',
    'amino acids',
    'fatty acids',
  ], 1, 'Sucrose = table sugar, lactose = milk sugar, maltose = malt sugar.'),
  mc('c18', C, 'This ring-shaped molecule is a', [
    'steroid',
    'monosaccharide (carbohydrate)',
    'nucleotide',
    'triglyceride',
  ], 1, 'A single sugar ring with CH₂OH/OH groups is a monosaccharide.', 'glucose'),
  mc('c19', C, 'Two rings joined by an oxygen bridge is a', [
    'amino acid',
    'disaccharide',
    'phospholipid',
    'steroid',
  ], 1, 'Two monosaccharides + glycosidic linkage = disaccharide.', 'disaccharide'),
  mc('c20', C, 'A long chain of sugar rings is a', [
    'nucleotide',
    'polysaccharide',
    'fatty acid',
    'dipeptide',
  ], 1, 'Starch, glycogen, and cellulose are polysaccharides.', 'polysaccharide'),
  multi('c21', C, 'Choose ALL polysaccharides.', [
    'Starch',
    'Glycogen',
    'Cellulose',
    'Glucose',
  ], [0, 1, 2], 'Glucose is a monosaccharide. The other three are polymers of glucose with different jobs.'),
  multi('c22', C, 'Choose ALL functions of carbohydrates.', [
    'Quick energy',
    'Plant cell walls (cellulose)',
    'Cell identification on membranes',
    'Storing the genetic code',
  ], [0, 1, 2], 'Genetic code is nucleic acids. Carbs are energy + structure + ID tags.'),
  mc('c23', C, 'Who can digest cellulose, and who cannot?', [
    'Animals digest it easily; plants cannot',
    'Animals cannot (cows need microbes); it is indigestible fiber for us',
    'Only viruses digest it',
    'Nobody has cellulose',
  ], 1, 'Cellulose is tough plant fiber. Humans cannot digest it; herbivores rely on microbes.'),
  mc('c24', C, 'Glycogen is stored in', [
    'plant cell walls',
    'liver and muscles',
    'the nucleus as DNA',
    'waxes on leaves',
  ], 1, 'Animal short-term glucose storage lives in liver and muscle.'),
  mc('l1', L, 'Glycerol and fatty acid chains are building blocks of', [
    'carbohydrates',
    'proteins',
    'lipids',
    'nucleic acids',
  ], 2, 'Lipids have no true repeating monomer. Building blocks = glycerol + fatty acids.'),
  mc('l2', L, 'Triglycerides, diglycerides, and phospholipids are large molecules of', [
    'carbohydrates',
    'lipids',
    'proteins',
    'nucleic acids',
  ], 1, 'Those are lipid structures.'),
  mc('l3', L, 'Lipids are made of', [
    'C, H, O, N, P always equally',
    'mostly C and H, with few O — and they are nonpolar',
    'only nitrogen',
    'only sugar rings',
  ], 1, 'All lipids are insoluble in water (hydrophobic/nonpolar).'),
  mc('l4', L, 'All lipids are _______________. This means they _______________ water.', [
    'hydrophilic; mix well with',
    'hydrophobic; do not mix well with',
    'polar; always dissolve in',
    'acids; raise',
  ], 1, 'Nonpolar = hydrophobic = do not mix with water.'),
  mc('l5', L, 'The bond that joins glycerol to fatty acids is a', [
    'peptide bond',
    'glycosidic linkage',
    'ester linkage',
    'phosphodiester bond between bases',
  ], 2, 'Lipids: ester. Carbs: glycosidic. Proteins: peptide. Nucleic acid backbone: phosphodiester.'),
  mc('l6', L, 'Long-term energy storage, insulation, cushion for organs, membranes, waxes, and steroids are functions of', [
    'carbohydrates',
    'lipids',
    'nucleic acids',
    'monosaccharides only',
  ], 1, 'More C–H bonds than carbs = more energy per gram. Also waterproofing and hormones.'),
  mc('l7', L, 'Grease, butter, oils, and waxes are examples of', [
    'proteins',
    'carbohydrates',
    'lipids',
    'nucleic acids',
  ], 2, 'Those are classic lipid examples.'),
  mc('l8', L, 'Compared with carbs, lipids are mainly used for', [
    'short-term energy',
    'long-term energy storage',
    'storing genetic code',
    'making glycosidic linkages',
  ], 1, 'Lipids pack more calories per gram and also insulate and waterproof.'),
  mc('l9', L, 'A triglyceride is built from', [
    '1 glycerol + 3 fatty acids',
    '1 phosphate + 2 fatty acids + glycerol',
    '4 fused rings',
    'phosphate + sugar + base',
  ], 0, 'Glycerol can bond to 3 fatty acid tails. Each ester bond removes one H₂O.'),
  mc('l10', L, 'A phospholipid is built from', [
    '1 glycerol + 3 fatty acids',
    'phosphate + glycerol + 2 fatty acid tails',
    'only 4 fused rings',
    '20 amino acids',
  ], 1, 'Often one tail is saturated (straight) and one is unsaturated (kinked).'),
  mc('l11', L, 'A steroid’s carbon skeleton is', [
    'a long glycogen chain',
    'four fused rings',
    'a nucleotide',
    'cellulose fiber',
  ], 1, 'Steroids have no glycerol or ester bonds. They count as lipids because they are hydrophobic. Examples: cholesterol, estrogen, testosterone.'),
  mc('l12', L, 'Saturated fatty acids', [
    'have C=C double bonds, are kinked, and tend to be liquid at room temp',
    'have only single C–C bonds, are straight, and tend to be solid at room temp',
    'are DNA',
    'are cellulose',
  ], 1, 'Saturated = “bad fats,” like solid bacon grease.'),
  mc('l13', L, 'Unsaturated fatty acids', [
    'have only single bonds and are solid at room temp',
    'contain C=C double bonds, kink, and tend to be liquid at room temp',
    'are glycogen',
    'are peptide bonds',
  ], 1, 'Unsaturated = “good fats,” like olive oil.'),
  mc('l14', L, 'Olive oil is liquid at room temperature. Its fatty acids are mostly', [
    'saturated',
    'unsaturated',
    'cellulose',
    'nucleic acids',
  ], 1, 'Liquid at room temp = unsaturated (kinked double bonds).'),
  mc('l15', L, 'Solid bacon grease is mostly', [
    'unsaturated oil',
    'saturated fat',
    'glycogen',
    'DNA',
  ], 1, 'Straight tails pack tightly → solid at room temp = saturated.'),
  mc('l16', L, 'What lipid makes up the bilayer of cell membranes?', [
    'starch',
    'phospholipid',
    'glycogen',
    'cellulose',
  ], 1, 'Hydrophilic heads face water; hydrophobic tails hide inside. That dual nature makes membranes selectively permeable.'),
  mc('l17', L, 'This E-shaped molecule (glycerol + 3 tails) is a', [
    'nucleotide',
    'triglyceride',
    'monosaccharide',
    'amino acid',
  ], 1, '1 glycerol + 3 fatty acids = triglyceride.', 'triglyceride'),
  mc('l18', L, 'A phosphate head, glycerol, and two tails is a', [
    'steroid',
    'phospholipid',
    'disaccharide',
    'glycogen',
  ], 1, 'That is the membrane lipid.', 'phospholipid'),
  mc('l19', L, 'Four fused rings with no fatty-acid tails is a', [
    'triglyceride',
    'steroid',
    'monosaccharide',
    'nucleotide',
  ], 1, 'Cholesterol, estrogen, and testosterone are steroids.', 'steroid'),
  mc('l20', L, 'The 3-carbon molecule with 3 OH groups is', [
    'glucose',
    'glycerol',
    'an amino acid',
    'a nitrogenous base',
  ], 1, 'Glycerol is the backbone that can hold fatty acids.', 'glycerol'),
  mc('l21', L, 'This fatty acid is', [
    'unsaturated (it has a kink / double bond)',
    'saturated (all single C–C bonds, straight)',
    'a nucleotide',
    'cellulose',
  ], 1, 'No kinks = only single bonds = saturated.', 'sat-fa'),
  mc('l22', L, 'This fatty acid is', [
    'saturated',
    'unsaturated (kink from a C=C double bond)',
    'a polysaccharide',
    'DNA',
  ], 1, 'The kink is where it is unsaturated.', 'unsat-fa'),
  mc('l23', L, 'In this comparison, A is ______ and B is ______.', [
    'unsaturated; saturated',
    'saturated; unsaturated',
    'a protein; DNA',
    'cellulose; starch',
  ], 1, 'Straight chain A = saturated. Kinked chain B = unsaturated.', 'fatty-compare'),
  multi('l24', L, 'Choose ALL functions of lipids.', [
    'Long-term energy storage',
    'Insulation and organ cushioning',
    'Cell membranes (phospholipids)',
    'Carrying the genetic code',
  ], [0, 1, 2], 'Genetic code is nucleic acids. Lipids also make waxes and steroid hormones.'),
  multi('l25', L, 'Choose ALL that are lipids.', [
    'Triglycerides',
    'Phospholipids',
    'Steroids',
    'Glycogen',
  ], [0, 1, 2], 'Glycogen is a carbohydrate (animal sugar storage).'),
  multi('l26', L, 'Choose ALL true of saturated vs unsaturated fats.', [
    'Saturated: single bonds, solid at room temp',
    'Unsaturated: double bonds, liquid at room temp',
    'Saturated tails are straight; unsaturated tails kink',
    'Unsaturated fats are polysaccharides',
  ], [0, 1, 2], 'Both are lipids, not carbs.'),
  mc('l27', L, 'Why do lipids store more energy per gram than carbs?', [
    'They have more C–H bonds that can be broken for energy',
    'They are polar and dissolve better',
    'They contain phosphorus in every molecule',
    'They are made of nucleotides',
  ], 0, 'Lots of C–H bonds = more calories packed in.'),
  mc('l28', L, 'Steroids are classified as lipids because they are', [
    'full of glycerol and ester bonds',
    'hydrophobic even though they have a 4-ring shape',
    'polysaccharides',
    'hydrophilic heads',
  ], 1, 'No fat tails, no glycerol — still lipids because they hate water.'),
  mc('p1', P, 'Amino acids are monomers of', [
    'carbohydrates',
    'lipids',
    'proteins',
    'nucleic acids',
  ], 2, 'Only 20 amino acids make up all life.'),
  mc('p2', P, 'Polypeptide chains are polymers of', [
    'lipids',
    'proteins',
    'carbohydrates',
    'waxes',
  ], 1, 'A protein (polypeptide) is a chain of amino acids.'),
  mc('p3', P, 'Proteins are made of', [
    'only C, H, O',
    'C, H, O, N, and sometimes S (CHONS)',
    'only phosphorus',
    'only fatty acids',
  ], 1, 'The N is in the amino group. S shows up in some R groups (disulfide bridges).'),
  mc('p4', P, 'Amino acids are joined by', [
    'ester linkages',
    'glycosidic linkages',
    'peptide bonds',
    'phosphodiester bonds only',
  ], 2, 'Peptide bonds form between the amino group of one AA and the carboxyl group of the next.'),
  mc('p5', P, 'When two amino acids bond through dehydration synthesis they form a ________ held by a ________.', [
    'disaccharide; glycosidic linkage',
    'dipeptide; peptide bond',
    'triglyceride; ester linkage',
    'nucleotide; hydrogen bond',
  ], 1, 'Two AAs = dipeptide. Many AAs = polypeptide/protein.'),
  mc('p6', P, 'Meats, egg whites, tofu, legumes, fish, and dairy are examples of', [
    'carbohydrates',
    'lipids',
    'proteins',
    'nucleic acids',
  ], 2, 'Those foods are protein-rich.'),
  mc('p7', P, 'Muscle, immunity and repair, enzymes, and cell transport are jobs of', [
    'carbohydrates',
    'lipids',
    'proteins',
    'waxes',
  ], 2, 'Proteins do almost everything. Shape decides the job.'),
  mc('p8', P, 'There are ________ different amino acids. The ________ is the part that differs between each one.', [
    '4; phosphate',
    '20; R group (side chain)',
    '2; glycerol',
    '6; glycosidic linkage',
  ], 1, 'The R group can be hydrophilic or hydrophobic and controls how the protein folds.'),
  mc('p9', P, 'An amino acid’s three parts are', [
    'phosphate, sugar, base',
    'amino group, carboxyl group, and R group',
    'glycerol and three tails',
    'four fused rings',
  ], 1, 'Label NH₂ (amino), COOH (carboxyl), and R (side chain).', 'amino-acid'),
  mc('p10', P, 'In this amino acid diagram, the yellow box is the', [
    'amino group',
    'carboxyl group',
    'R group (side chain)',
    'peptide bond',
  ], 2, 'R is the variable side chain. Amino = H₂N. Carboxyl = COOH.', 'amino-acid'),
  mc('p11', P, 'The bond in the middle of this two-amino-acid molecule is a', [
    'glycosidic linkage',
    'peptide bond',
    'ester linkage',
    'hydrogen bond between bases',
  ], 1, 'Dehydration synthesis between AAs makes a peptide bond and releases water.', 'dipeptide'),
  mc('p12', P, 'The order of amino acids in a chain is the protein’s', [
    'secondary structure',
    'primary structure',
    'quaternary structure',
    'pH',
  ], 1, 'Primary = sequence, held by peptide bonds, determined by DNA.'),
  mc('p13', P, 'An alpha helix or beta pleated sheet is', [
    'primary structure',
    'secondary structure',
    'a nucleotide',
    'a triglyceride',
  ], 1, 'Secondary folds form from backbone hydrogen bonds.'),
  mc('p14', P, 'Tertiary structure comes from interactions between', [
    'two DNA strands',
    'R groups (side chains)',
    'glycerol and fatty acids',
    'plant cell walls',
  ], 1, 'Tertiary = overall 3D shape of one polypeptide. Shape → function.'),
  mc('p15', P, 'Hemoglobin has 4 polypeptide subunits working together. That extra level is', [
    'primary only',
    'secondary only',
    'quaternary structure',
    'a glycosidic linkage',
  ], 2, 'Quaternary = multiple chains. Not every protein has this level.'),
  mc('p16', P, 'Hydrophilic R groups are usually on the ________ of a protein. Hydrophobic R groups are usually on the ________.', [
    'inside; outside',
    'outside; inside',
    'DNA; RNA',
    'ice; oil',
  ], 1, 'Water-loving groups face water. Water-fearing groups hide in the core. That folding is tertiary structure.'),
  mc('p17', P, 'Symmetrical R groups tend to be', [
    'polar / hydrophilic',
    'nonpolar / hydrophobic',
    'nucleotides',
    'acids with pH 1',
  ], 1, 'Study-guide hint: symmetrical molecules tend to be NONPOLAR, so those R groups are hydrophobic.'),
  mc('p18', P, 'Hemoglobin’s job is to', [
    'digest starch',
    'carry substances in blood',
    'store glucose in plants',
    'make insect exoskeletons',
  ], 1, 'Transport protein. Amylase digests. Starch/glycogen store sugar. Chitin is structure in insects/fungi.'),
  mc('p19', P, 'Amylase and pepsin are', [
    'lipids',
    'digestive enzymes (proteins)',
    'nucleic acids',
    'steroids',
  ], 1, 'Enzymes are proteins that break down nutrients so they can be absorbed.'),
  mc('p20', P, 'Antibodies are proteins whose job is', [
    'long-term energy',
    'defense against pathogens',
    'storing glycogen',
    'making cellulose',
  ], 1, 'Defense is one of many protein jobs. Others: keratin/actin (structure), insulin (hormone), myosin (contraction).'),
  mc('p21', P, 'If a protein’s shape breaks, its job fails. Unfolding from heat or extreme pH is', [
    'capillary action',
    'denaturation',
    'adhesion',
    'esterification',
  ], 1, 'Structure = function. Denatured enzymes stop working.'),
  mc('p22', P, 'Primary structure is held together by', [
    'hydrogen bonds in the backbone only',
    'peptide bonds',
    'ester linkages',
    'ionic bonds between DNA bases',
  ], 1, 'Peptide bonds are the backbone of the amino-acid sequence.'),
  mc('p23', P, 'Secondary structure is held in shape by', [
    'peptide bonds only',
    'hydrogen bonds in the backbone',
    'ester linkages',
    'glycosidic linkages',
  ], 1, 'α helix and β pleated sheet = hydrogen bonds along the backbone.'),
  mc('p24', P, 'Which interaction is NOT a typical R-group interaction in tertiary folding?', [
    'hydrophobic interactions',
    'ionic bonding',
    'hydrogen bonding',
    'glycosidic linkages between sugars',
  ], 3, 'Tertiary uses hydrophobic, hydrophilic, ionic, hydrogen bonds, and disulfide bridges — not sugar-sugar glycosidic bonds.'),
  mc('p25', P, 'Disulfide bridges form between R groups that contain', [
    'phosphorus',
    'sulfur',
    'only hydrogen',
    'cellulose',
  ], 1, 'S in CHONS shows up in disulfide bridges (S–S) that stabilize tertiary structure.'),
  mc('p26', P, 'A peptide bond forms between which two groups?', [
    'Two R groups only',
    'The amino group of one AA and the carboxyl group of the next',
    'Glycerol and a fatty acid',
    'Phosphate and a nitrogenous base',
  ], 1, 'That C–N peptide bond is made by dehydration synthesis.'),
  mc('p27', P, 'The N-terminus of a polypeptide is the end with a free', [
    'carboxyl group',
    'amino group',
    'fatty acid tail',
    'phosphate',
  ], 1, 'N-terminus = amino end. C-terminus = carboxyl end.'),
  multi('p28', P, 'Choose ALL that are protein functions.', [
    'Enzymes',
    'Transport (hemoglobin)',
    'Defense (antibodies)',
    'Storing genetic instructions as DNA',
  ], [0, 1, 2], 'DNA/RNA store genetic info. Proteins do the jobs the DNA codes for.'),
  multi('p29', P, 'Choose ALL levels of protein structure.', [
    'Primary (amino acid sequence)',
    'Secondary (helix / pleated sheet)',
    'Tertiary (3D R-group folding)',
    'Capillary (water climbing)',
  ], [0, 1, 2], 'The fourth level, quaternary, is multiple polypeptides together. Capillary action is a water property.'),
  multi('p30', P, 'Choose ALL that can happen between R groups in tertiary structure.', [
    'Hydrophobic interactions',
    'Ionic bonding',
    'Hydrogen bonding',
    'Disulfide bridges',
  ], [0, 1, 2, 3], 'All four (plus hydrophilic interactions) help lock the 3D shape that decides function.'),
  mc('n1', N, 'Nucleotides are monomers of', [
    'proteins',
    'lipids',
    'nucleic acids',
    'cellulose',
  ], 2, 'DNA and RNA are polymers of nucleotides.'),
  mc('n2', N, 'DNA and RNA are polymers of', [
    'amino acids',
    'nucleic acids',
    'fatty acids',
    'glucose only',
  ], 1, 'The two nucleic acid polymers are DNA and RNA.'),
  mc('n3', N, 'Nucleic acids are made of', [
    'only C, H, O',
    'C, H, O, N, and P (CHONP)',
    'only sulfur',
    'only glycerol',
  ], 1, 'The P is in the phosphate of every nucleotide.'),
  mc('n4', N, 'A nucleotide is made of', [
    'glycerol and three fatty acids',
    'phosphate, sugar, and a nitrogenous base',
    'only amino acids',
    'glucose rings only',
  ], 1, 'Three parts: P + sugar + base.', 'nucleotide'),
  mc('n5', N, 'In this diagram, the yellow circle, orange pentagon, and purple rectangle are', [
    'amino, carboxyl, R group',
    'phosphate, sugar, and base',
    'glycerol and two tails',
    'four fused rings',
  ], 1, 'That trio is one nucleotide.', 'nucleotide'),
  mc('n6', N, 'Nucleic acids carry', [
    'only long-term calories',
    'the genetic code / instructions for proteins',
    'only plant cell walls',
    'only sweat',
  ], 1, 'They are the molecule of heredity.'),
  mc('n7', N, 'Bonds in nucleic acids: the backbone uses ________. Bases pair with ________.', [
    'peptide bonds; ester linkages',
    'phosphodiester bonds; hydrogen bonds',
    'glycosidic linkages; peptide bonds',
    'ionic bonds; cellulose',
  ], 1, 'Phosphodiester links nucleotides in a strand. H-bonds hold base pairs together.'),
  mc('n8', N, 'In DNA, adenine (A) pairs with', [
    'guanine (G)',
    'cytosine (C)',
    'thymine (T)',
    'uracil (U) only, even in DNA',
  ], 2, 'DNA: A–T and G–C. Uracil replaces thymine in RNA.'),
  mc('n9', N, 'In RNA, adenine (A) pairs with', [
    'thymine (T)',
    'uracil (U)',
    'guanine (G)',
    'cellulose',
  ], 1, 'RNA: A–U and G–C. DNA uses T instead of U.'),
  mc('n10', N, 'Guanine (G) pairs with', [
    'adenine',
    'thymine only',
    'cytosine',
    'glycerol',
  ], 2, 'G–C pairing is true in both DNA and RNA.'),
  mc('n11', N, 'This twisted double strand is', [
    'a triglyceride',
    'DNA (nucleic acid)',
    'cellulose',
    'a steroid',
  ], 1, 'DNA is a double helix of nucleotides. A–T and G–C are hydrogen-bonded in the middle.', 'dna'),
  mc('n12', N, 'Which elements are in nucleic acids but NOT in a typical carbohydrate?', [
    'only extra oxygen',
    'nitrogen and phosphorus',
    'only extra hydrogen',
    'iron and gold',
  ], 1, 'Carbs = CHO. Nucleic acids = CHONP. Proteins = CHONS (N and sometimes S, but not P as a defining element).'),
  multi('n13', N, 'Choose ALL parts of a nucleotide.', [
    'Phosphate',
    'Sugar',
    'Nitrogenous base',
    'Fatty acid tail',
  ], [0, 1, 2], 'No fatty acid tails — those are lipids.'),
  multi('n14', N, 'Choose ALL correct base pairs.', [
    'A–T in DNA',
    'A–U in RNA',
    'G–C in DNA and RNA',
    'A–G in DNA',
  ], [0, 1, 2], 'A does not pair with G. Complementary pairs are A–T/U and G–C.'),
  mc('n15', N, 'The function of nucleic acids is to', [
    'insulate organs',
    'store genetic information and instructions for making proteins',
    'form plant cell walls',
    'dissolve oil',
  ], 1, 'Heredity + protein recipes. That is DNA/RNA.'),
  mc('x1', R, 'Which macromolecule is CHONP?', [
    'carbohydrates',
    'lipids',
    'proteins',
    'nucleic acids',
  ], 3, 'P for phosphate. Nucleic acids = CHONP.'),
  mc('x2', P, 'Which macromolecule is CHONS?', [
    'carbohydrates',
    'lipids',
    'proteins',
    'cellulose',
  ], 2, 'N in every amino acid; S in some R groups.'),
  mc('x3', C, 'Which macromolecule is CHO in a ring, often in a CH₂O ratio?', [
    'lipids',
    'carbohydrates',
    'proteins',
    'nucleic acids',
  ], 1, 'Lipids are also CHO but with few O and no sugar-ring repeating unit.'),
  mc('x4', L, 'Which macromolecule is CHO with few oxygens and is fully hydrophobic?', [
    'carbohydrates',
    'lipids',
    'proteins',
    'nucleic acids',
  ], 1, 'If it hates water and is mostly C and H, think lipid.'),
  multi('x5', R, 'Choose ALL macromolecules that contain nitrogen.', [
    'Carbohydrates',
    'Proteins',
    'Nucleic acids',
    'Typical triglycerides',
  ], [1, 2], 'Proteins (amino groups) and nucleic acids (bases). Carbs and most fats are CHO only.'),
  multi('x6', R, 'Match building blocks: choose ALL correct pairs.', [
    'Monosaccharides → carbohydrates',
    'Amino acids → proteins',
    'Nucleotides → nucleic acids',
    'Glucose rings → DNA',
  ], [0, 1, 2], 'DNA is built from nucleotides, not from glucose.'),
  mc('x7', R, 'Which food set matches proteins?', [
    'pasta, bread, fruit',
    'meats, egg whites, tofu, legumes, fish, dairy',
    'butter, oil, grease, wax',
    'DNA and RNA',
  ], 1, 'Pasta = carbs. Butter = lipids. Meats/eggs/tofu = proteins.'),
  mc('x8', C, 'Which food set matches carbohydrates?', [
    'meats and egg whites',
    'sugars, fruits, crackers, pasta, bread',
    'olive oil and lard',
    'antibodies',
  ], 1, 'Grain and fruit foods are carb examples from class.'),
  mc('x9', L, 'Which food set matches lipids?', [
    'tofu and fish',
    'grease, butter, oils, and waxes',
    'crackers and pasta',
    'DNA',
  ], 1, 'Fats, oils, and waxes are lipids.'),
]
