import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'passive' as const

export const PASSIVE_QUESTIONS: BioPracticeQuestion[] = [
  mc('p1', T, 'At equilibrium, solute amounts are equal on both sides. That means', [
    'molecules freeze and never move again',
    'net movement is zero; molecules still move both ways',
    'the cell now uses only ATP for every crossing',
    'the cell has expelled all of its water',
  ], 1, 'Cells want equilibrium. Dynamic equilibrium = equal rates in and out, not “stopped.”'),
  mc('p2', T, 'A concentration gradient exists when there are', [
    'equal amounts of solute on each side',
    'unequal amounts of solute on each side',
    'no solutes present on either side',
    'equal water and equal solute on both sides',
  ], 1, 'Passive transport needs a gradient (unequal solute) for net movement.'),
  mc('p3', T, 'Passive transport requires', [
    'ATP to push solutes low → high',
    'no ATP; solutes move high → low',
    'vesicles to carry every molecule',
    'a nucleus to direct each crossing',
  ], 1, 'Down / with the concentration gradient. No energy.'),
  mc('p4', T, 'In passive transport, molecules move', [
    'low → high, against the gradient, using ATP',
    'high → low, with the gradient, without ATP',
    'only by phagocytosis of whole particles',
    'only through plasmodesmata in plant walls',
  ], 1, 'If it goes up/against the gradient, that is active, not passive.'),
  mc('p5', T, 'The three types of passive transport are', [
    'endocytosis, exocytosis, and the Na+/K+ pump',
    'simple diffusion, osmosis, and facilitated diffusion',
    'phagocytosis, pinocytosis, and receptor-mediated',
    'binary fission, mitosis, and budding of cells',
  ], 1, 'All three are high → low and need no ATP.'),
  mc('p6', T, 'Simple diffusion is best defined as', [
    'fluid/gas moving high → low until equilibrium',
    'water only, through aquaporins, using ATP',
    'bulk export of proteins in vesicles',
    '3 Na⁺ out and 2 K⁺ in per ATP',
  ], 0, 'Examples: oxygen, carbon dioxide, and other small molecules.'),
  mc('p7', T, 'The best simple-diffusion example is', [
    'glucose on a carrier, using ATP',
    'O₂ or CO₂ moving high → low through the bilayer',
    'a macrophage engulfing bacteria',
    'insulin binding a receptor, then engulfed',
  ], 1, 'Small uncharged gases simple-diffuse. Glucose needs a protein; eating bacteria is phagocytosis.'),
  mc('p8', T, 'Membrane permeable to starch ONLY. Which molecule can move?', [
    'glucose only, because it has a steeper gradient',
    'starch only, because only starch is allowed through',
    'both, because starch and glucose are both sugars',
    'neither, because no molecule can ever cross',
  ], 1, 'Permeable to starch ONLY means glucose cannot cross even if it has a gradient.', 'diffusion-starch'),
  mc('p9', T, '60% starch in, 10% starch out, starch-only membrane. Starch will', [
    'enter the cell, low → high, using ATP',
    'leave the cell, high → low, no ATP',
    'stay put because starch is always trapped',
    'enter by phagocytosis of starch grains',
  ], 1, 'Passive: 60% → 10%, so starch moves OUT.', 'diffusion-starch'),
  mc('p10', T, 'Why doesn’t the glucose gradient (10% in vs 40% out) decide that diagram?', [
    'Glucose always requires ATP to move anywhere',
    'The membrane is not permeable to glucose',
    'Glucose is a gas that cannot have a gradient',
    'Starch is an ion, so glucose is ignored',
  ], 1, 'Always check permeability before drawing arrows.', 'diffusion-starch'),
  mc('p11', T, 'Osmosis is', [
    'simple diffusion of water across a membrane',
    'simple diffusion of starch across a membrane',
    'active pumping of water that always uses ATP',
    'phagocytosis of water into a vesicle',
  ], 0, 'Water moves high water potential → low water potential. No ATP (“water slide”).'),
  mc('p12', T, 'High water potential means', [
    'high solute concentration, little free water',
    'low solute concentration, more free water',
    'zero water molecules on that side',
    'only ions, with no water present',
  ], 1, 'Lots of solute = low water potential. Water then flows toward the solute.'),
  mc('p13', T, 'Low water potential means', [
    'high solute concentration, less free water',
    'pure distilled water with almost no solute',
    'no membrane separating the two sides',
    'the two sides are already isotonic',
  ], 0, 'Crowded with solute → water flows toward that side.'),
  mc('p14', T, 'During osmosis, water moves', [
    'toward solute: high water → low water, no ATP',
    'away from solute, always using ATP pumps',
    'only through the sodium-potassium pump',
    'from low water potential to high water potential',
  ], 0, 'Water slides toward the saltier/sweeter side.'),
  mc('p15', T, 'In an isotonic solution, solute is equal in and out, so', [
    'more solute outside pulls all water out',
    'water enters and leaves at equal rates',
    'individual water molecules completely stop',
    'only proteins are allowed to cross',
  ], 1, 'Dynamic equilibrium. Happy animal cell. Plant cell is alive but limp.'),
  mc('p16', T, 'A hypotonic solution has', [
    'higher solute outside, so water leaves and the cell shrinks',
    'lower solute outside, so water enters and the cell swells',
    'equal solute in and out, so there is no net water flow',
    'no water outside, so osmosis cannot occur',
  ], 1, 'Hypo = low solute (like hypothermia = low temperature). Hippo = swells.'),
  mc('p17', T, 'A hypertonic solution has', [
    'higher solute outside; water leaves and the cell shrivels',
    'lower solute outside; every kind of cell always bursts',
    'equal solute in and out; the cell is at equilibrium',
    'only oxygen outside; water cannot move',
  ], 0, 'Hyper = high solute. “When you are hyper you sweat and lose water.”'),
  mc('p18', T, 'An egg placed in a hypotonic solution is, compared with that solution,', [
    'also hypotonic, because both have low solute',
    'hypertonic, because the egg has more solute',
    'a prokaryote, because it has no nucleus',
    'isotonic only after the egg bursts',
  ], 1, 'The words describe solute. The egg has more solute than a dilute bath, so the egg is hypertonic to the solution.'),
  mc('p19', T, 'An animal cell in a hypotonic solution', [
    'becomes turgid and is at its happiest',
    'swells and may burst (cytolysis)',
    'plasmolyzes in a healthy, useful way',
    'builds a cellulose wall immediately',
  ], 1, 'No cell wall and no giant vacuole to handle extra water.', 'animal-tonicity'),
  mc('p20', T, 'An animal cell in a hypertonic solution', [
    'becomes turgid from extra water',
    'shrivels; notes also call this plasmolysis',
    'bursts from cytolysis as water rushes in',
    'is in its happiest, preferred state',
  ], 1, 'Water leaves. Animal cells prefer isotonic.', 'animal-tonicity'),
  mc('p21', T, 'An animal cell in an isotonic solution', [
    'bursts because water can only enter the cell',
    'has no net H₂O movement; that is the happy animal cell',
    'wilts the way a plant does in salt water',
    'always plasmolyzes as the membrane pulls inward',
  ], 1, 'Dynamic equilibrium. Best environment for animal cells.', 'animal-tonicity'),
  mc('p22', T, 'Cytolysis is', [
    'an animal cell swelling and bursting in hypotonic solution',
    'a plant becoming turgid in a healthy hypotonic bath',
    'a bacterium splitting itself by binary fission',
    'hormones leaving the cell by vesicle exocytosis',
  ], 0, 'Dead/burst animal cell. Plants resist this with wall + central vacuole.'),
  mc('p23', T, 'Contractile vacuoles', [
    'are in typical animal cells to stop cytolysis',
    'are in freshwater protists like Amoeba, not animal cells',
    'are chloroplasts that make sugar from light',
    'are the peptidoglycan of a bacterial wall',
  ], 1, 'They push out extra water and help prevent cytolysis in those protists.'),
  mc('p24', T, 'A plant cell in a hypertonic solution', [
    'is turgid and standing up firmly',
    'plasmolyzes — membrane pulls in; the plant looks wilted',
    'bursts as easily as a red blood cell would',
    'shows no change in the large central vacuole',
  ], 1, 'Water left. Dead/wilted plant cell in the notes.', 'plant-tonicity'),
  mc('p25', T, 'A plant cell in an isotonic solution', [
    'is in its happiest, most turgid state',
    'has no net H₂O movement; alive but limp',
    'always bursts from too much water',
    'undergoes cytolysis like an animal cell',
  ], 1, 'Plants prefer hypotonic (turgid). Isotonic = limp, not peak health.', 'plant-tonicity'),
  mc('p26', T, 'A plant cell in a hypotonic solution', [
    'bursts because plant cells have no wall',
    'is turgid — slightly swollen, well-watered, happy',
    'plasmolyzes as the membrane pulls inward',
    'loses its large central vacuole entirely',
  ], 1, 'Wall + large central vacuole resist bursting. Turgor helps the plant stand.', 'plant-tonicity'),
  mc('p27', T, 'Turgor pressure is', [
    'fluid pushing the membrane against the cell wall',
    'ATP spent by the sodium-potassium pump',
    'pressure inside a virus’s protein capsid',
    'the force that drives binary fission',
  ], 0, 'Turgid = that pressure is high. Plants hold more water than animal cells because of the wall and large vacuole.'),
  mc('p28', T, 'Plant cells resist bursting in hypotonic solution mainly because', [
    'they have no plasma membrane at all',
    'the wall plus large central vacuole hold extra water',
    'they use only active transport for water',
    'they have centrioles that pump water out',
  ], 1, 'Animal cells lack that wall backup. Turgor is actually useful for plants.'),
  mc('p29', T, 'Beaker, water-only membrane, more red sucrose on A. Highest water potential is', [
    'A, because more sucrose means more water',
    'B, because fewer sucrose dots means more free water',
    'equal, because both sides contain water',
    'neither, because sucrose has replaced all water',
  ], 1, 'Highest water potential = highest water concentration = B.', 'osmosis-beaker'),
  mc('p30', T, 'In that same beaker, highest solute concentration is', [
    'A, where there are more sucrose molecules',
    'B, where there is more free water',
    'equal, because volume is the same',
    'only inside the membrane itself',
  ], 0, 'More red sucrose on A.', 'osmosis-beaker'),
  mc('p31', T, 'In that beaker, water will move', [
    'A → B, toward the side with more free water',
    'B → A, high water → low water, no ATP',
    'not at all, because sucrose blocks water forever',
    'only if a pump spends ATP on water',
  ], 1, 'Osmosis is passive. Water goes toward the sucrose.', 'osmosis-beaker'),
  mc('p32', T, '90% water in the cell, 10% water outside, water-only membrane. The outside solution is', [
    'hypotonic, because outside has more free water',
    'hypertonic, because outside has little water / more solute',
    'isotonic, because both sides already contain water',
    'a gas, so osmosis cannot happen at all',
  ], 1, 'Outside is high solute / low water. Hypertonic solution.', 'hypertonic-cell'),
  mc('p33', T, 'In that 90% vs 10% water diagram, water moves', [
    'into the cell, toward the lower-water side',
    'out of the cell, high water → low water',
    'not at all, because the membrane blocks water',
    'as starch, because starch can also cross',
  ], 1, 'The cell will shrink/shrivel (plasmolysis).', 'hypertonic-cell'),
  mc('p34', T, 'After water leaves that cell, it will', [
    'burst (cytolysis) from extra water',
    'become turgid from a full central vacuole',
    'shrink/shrivel (plasmolysis)',
    'divide immediately by binary fission',
  ], 2, 'Hypertonic surroundings pull water out.', 'hypertonic-cell'),
  mc('p35', T, 'That cell (90% water inside) compared with the solution is', [
    'hypertonic, because the cell has more solute than outside',
    'hypotonic, because the cell has lower solute than outside',
    'a virus, because it has no cytoplasm of its own',
    'isotonic, because both sides already contain water',
  ], 1, 'Notes: HYPOtonic cell (low solute) in a HYPERtonic solution (high solute).', 'hypertonic-cell'),
  mc('p36', T, 'Facilitated diffusion is', [
    'high → low with a channel or carrier; still no ATP',
    'low → high with the Na+/K+ pump and ATP',
    'bulk export of cargo by exocytosis',
    'water moving only when ATP is spent',
  ], 0, 'Proteins help molecules that could not pass or fit. Example: glucose or amino acids.', 'channel-carrier'),
  mc('p37', T, 'Molecules that use facilitated diffusion are typically', [
    'O₂ and CO₂, small uncharged gases',
    'large, polar, and/or charged, such as glucose',
    'entire bacteria engulfed as food',
    'whole nuclei moving between cells',
  ], 1, 'They need a protein helper but still go down the gradient.'),
  mc('p38', T, 'Channel proteins in facilitated diffusion are', [
    'peripheral proteins sitting only on an edge',
    'integral proteins with a pore molecules wander through',
    'pumps that always spend ATP to move cargo',
    'cellulose fibers in a plant cell wall',
  ], 1, 'Embedded in the membrane with a tunnel.', 'channel-carrier'),
  mc('p39', T, 'Aquaporins are', [
    'steroids that buffer membrane fluidity',
    'channel proteins that speed water across',
    'Na+/K+ pumps that spend ATP on ions',
    'protein capsids around a virus genome',
  ], 1, 'Still passive — they just make osmosis faster than leaking through tails.'),
  mc('p40', T, 'Carrier proteins in facilitated diffusion', [
    'change shape to move material across',
    'are four fused rings of cholesterol',
    'are only oligosaccharide name tags',
    'always move cargo low → high with ATP',
  ], 0, 'Some span the membrane; others do not. Still high → low if it is facilitated diffusion.', 'channel-carrier'),
  mc('p41', T, 'Glucose going high → low on a channel or carrier is', [
    'simple diffusion through the lipid tails',
    'facilitated diffusion, still without ATP',
    'phagocytosis of glucose crystals',
    'exocytosis of glucose in a vesicle',
  ], 1, 'Glucose is large enough that it needs help. No ATP if it is down the gradient.'),
  mc('p42', T, 'Glucose HIGH outside, LOW inside. Facilitated diffusion moves it', [
    'out of the cell, against the gradient, with ATP',
    'into the cell, high → low, protein, no ATP',
    'not at all, because glucose never crosses',
    'only if the cell is a prokaryote',
  ], 1, 'Match the arrows to the gradient AND the protein.'),
  mc('p43', T, 'Simple vs facilitated diffusion: both', [
    'require ATP to move cargo uphill against a gradient',
    'go high → low with no ATP; only facilitated needs a protein',
    'use vesicles that fuse with the plasma membrane',
    'move solutes from low concentration up to high',
  ], 1, 'The protein is the difference, not energy or direction.'),
  mc('p44', T, 'Osmosis vs simple diffusion: osmosis is specifically', [
    'ion pumping by the sodium-potassium pump',
    'water moving across a membrane down its gradient',
    'glucose using a carrier protein helper',
    'proteins leaving the cell by exocytosis',
  ], 1, 'Both are passive. Osmosis = water. Aquaporins can speed water but do not make it active.'),
  mc('p45', T, 'A red blood cell in distilled water will', [
    'shrivel as water leaves the cell',
    'take in water and risk cytolysis',
    'grow a wall and become a plant cell',
    'pump three Na⁺ ions inward',
  ], 1, 'Distilled water is hypotonic to the cell. Animals prefer isotonic.'),
  mc('p46', T, 'A red blood cell in very salty water will', [
    'burst as water rushes in',
    'lose water and shrivel',
    'become turgid against a cell wall',
    'grow a cellulose wall for support',
  ], 1, 'Salty water is hypertonic. Water leaves.'),
  mc('p47', T, 'Elodea in salt water looks wilted because of', [
    'cytolysis that bursts the cell wall',
    'plasmolysis: water left and the membrane pulled in',
    'chloroplasts turning into mitochondria',
    'pinocytosis of salt crystals into vesicles',
  ], 1, 'Hypertonic environment. Plant in salt = wilted.'),
  mc('p48', T, 'A well-watered plant stands up because its cells are', [
    'plasmolyzed, with membranes pulled inward',
    'turgid from hypotonic surroundings and turgor',
    'in hypertonic soil that has almost no water',
    'isotonic and in the process of bursting',
  ], 1, 'Happy plant = hypotonic environment.'),
  mc('p49', T, 'If solute is already equal on both sides, net diffusion', [
    'speeds up if the cell spends more ATP on pumps',
    'is zero even though molecules still move randomly',
    'switches over to phagocytosis of solute',
    'flips the plasma membrane inside out',
  ], 1, 'That is equilibrium / dynamic equilibrium.'),
  mc('p50', T, 'Net passive transport cannot occur if', [
    'a concentration gradient is present',
    'there is already no concentration gradient',
    'oxygen gas is present outside the cell',
    'a channel protein exists in the membrane',
  ], 1, 'Notes: must have unequal solute on each side for net movement.'),
  multi('p51', T, 'Choose ALL types of passive transport.', [
    'simple diffusion',
    'osmosis',
    'facilitated diffusion',
    'sodium-potassium pump',
  ], [0, 1, 2], 'The pump is active: ATP, against the gradient.'),
  multi('p52', T, 'Choose ALL true of hypotonic vs hypertonic.', [
    'Hypotonic solution = low solute outside; water in; swell',
    'Hypertonic solution = high solute outside; water out; shrink',
    'The words are adjectives about how much solute is there',
    'Hypotonic solutions always kill plant cells',
  ], [0, 1, 2], 'Hypotonic is actually what plants like (turgid).'),
  multi('p53', T, 'Choose ALL correct animal vs plant comparisons.', [
    'Animals happiest isotonic; plants happiest hypotonic/turgid',
    'Hypotonic can cytolyse animals; plants resist with wall + vacuole',
    'Hypertonic shrivels both (plasmolysis / wilt)',
    'Plant cells prefer dry hypertonic soil with no water',
  ], [0, 1, 2], 'Isotonic plants are limp, not peak health.'),
  mc('p54', T, 'Amino acids entering high → low with a protein helper is', [
    'simple diffusion through the lipid tails',
    'facilitated diffusion with no ATP required',
    'phagocytosis of amino-acid crystals',
    'exocytosis of amino acids in a vesicle',
  ], 1, 'Notes list glucose or amino acids as facilitated-diffusion examples.'),
  mc('p55', T, 'A pore with glucose moving high outside → low inside is a', [
    'steroid lipid buffering the bilayer',
    'channel protein used in facilitated diffusion',
    'vesicle about to fuse in exocytosis',
    'circular plasmid in a nucleoid',
  ], 1, 'Pore = channel. Shape-change blob = carrier.', 'channel-carrier'),
  mc('p56', T, 'A protein changing shape to ferry glucose down its gradient is a', [
    'carrier protein in facilitated diffusion',
    'capsid wrapping a virus genome',
    'cellulose fiber in a plant wall',
    'tight junction holding two cells',
  ], 0, 'Still no ATP if it is down the gradient.', 'channel-carrier'),
  mc('p57', T, 'Water moving toward a high-solute side is the notes’ “water slide”: it goes', [
    'uphill, from low water to high water, using ATP',
    'high water → low water, with no energy needed',
    'into the cell only by phagocytosis',
    'only during binary fission of bacteria',
  ], 1, 'Mnemonic for osmosis from the slides.'),
  mc('p58', T, 'Which environment is bad for BOTH animal and plant cells?', [
    'isotonic, which animals actually prefer',
    'hypertonic, because water leaves both',
    'slightly hypotonic, which plants prefer',
    'the plant’s preferred turgid state',
  ], 1, 'Both lose water. Animal shrivels; plant plasmolyzes/wilts.'),
  mc('p59', T, 'U-tube: left 10% salt, right 2% salt, water-only membrane. Water net-flows', [
    'right → left, toward the higher-solute side',
    'left → right, toward the higher-water side',
    'neither way, because salt simple-diffuses across',
    'both ways equally from the first second',
  ], 0, 'More free water on the 2% side. Salt cannot cross, so only water moves toward 10%.'),
  mc('p60', T, '“The cell is hypotonic” vs “the solution is hypotonic” is a trick because', [
    'the adjective belongs to whichever side has LOWER solute',
    'the two phrases always mean the exact same thing',
    'hypotonic always means high solute, never low',
    'those words apply only to viruses, not cells',
  ], 0, 'Always ask: solute where? Water then goes to the hypertonic side.'),
  mc('p61', T, 'Dynamic equilibrium in an isotonic animal cell means', [
    'water molecules are frozen in place',
    'equal amounts of water enter and leave',
    'the cell uses only exocytosis for water',
    'the Na+/K+ pump has shut off forever',
  ], 1, 'Molecules don’t stop; nets cancel.'),
  mc('p62', T, 'Which still needs a membrane protein but NOT ATP?', [
    'simple diffusion of O₂ through the tails',
    'facilitated diffusion of glucose',
    'the sodium-potassium pump',
    'endocytosis of a whole bacterium',
  ], 1, 'Protein ≠ energy. Direction of the gradient decides passive vs active.'),
  mc('p63', T, 'Cell is 5% salt in 20% salt water, water-permeable only. The outside water is', [
    'hypotonic to the cell',
    'hypertonic to the cell',
    'isotonic to the cell',
    'pure water with no solute',
  ], 1, '20% > 5%, so outside has more solute. Water leaves; cell shrinks.'),
  mc('p64', T, 'Osmosis vs facilitated diffusion: both are passive, but', [
    'both require ATP to move cargo uphill against a gradient',
    'osmosis is water; facilitated uses a protein for other molecules',
    'both move solutes from low concentration to high',
    'neither one needs a membrane in order to occur',
  ], 1, 'Know the 3-way compare: simple vs osmosis vs facilitated.'),
  mc('p65', T, 'Starch cannot cross; water can. A high-starch bag in distilled water will', [
    'lose starch by simple diffusion into the beaker',
    'gain water by osmosis and swell',
    'phagocytose the entire beaker of water',
    'pump starch out automatically with ATP',
  ], 1, 'Starch stays; the bag is hypertonic; water enters.'),
]
