import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const W = 'water' as const

export const WATER_QUESTIONS: BioPracticeQuestion[] = [
  mc('w1', W, 'What does the term polar mean?', [
    'Unequal sharing of electrons',
    'Equal sharing of electrons',
    'No electrons in the molecule',
    'Only ionic bonds are present',
  ], 0, 'Polar means electrons are not shared equally, so one side is slightly negative and the other is slightly positive.'),
  mc('w2', W, 'Water is a ____ molecule.', [
    'nonpolar',
    'polar',
    'ionic metal',
    'radioactive',
  ], 1, 'Water is polar because oxygen pulls electrons harder than hydrogen.'),
  mc('w3', W, 'In a water molecule, which atom has a slight negative charge?', [
    'Hydrogen',
    'Oxygen',
    'Carbon',
    'Nitrogen',
  ], 1, 'Oxygen attracts electrons more strongly, so it is δ−.'),
  mc('w4', W, 'In a water molecule, which atom has a slight positive charge?', [
    'Oxygen',
    'Hydrogen',
    'Phosphorus',
    'Sulfur',
  ], 1, 'The hydrogens are δ+ because oxygen hogs the shared electrons.'),
  mc('w5', W, 'Within a water molecule, the oxygen is partially __________ and the hydrogen is partially __________.', [
    'positive; negative',
    'negative; positive',
    'neutral; neutral',
    'positive; positive',
  ], 1, 'O is δ− and H is δ+. That uneven charge is why water can hydrogen-bond.'),
  mc('w6', W, 'In a polar water molecule, the hydrogen atoms are', [
    'negative',
    'positive',
    'uncharged metals',
    'the same charge as oxygen',
  ], 1, 'Hydrogens are partially positive.'),
  mc('w7', W, 'A molecule of water consists of', [
    '1 hydrogen and 2 oxygens',
    '2 hydrogens and 1 oxygen',
    '3 hydrogens and 1 carbon',
    '2 oxygens and 2 hydrogens',
  ], 1, 'H₂O = two hydrogen atoms and one oxygen atom.'),
  mc('w8', W, 'What two elements make up water?', [
    'carbon and oxygen',
    'hydrogen and oxygen',
    'nitrogen and oxygen',
    'sodium and chlorine',
  ], 1, 'Water is hydrogen and oxygen.'),
  mc('w9', W, 'What holds the H and O atoms together INSIDE one water molecule?', [
    'Hydrogen bonds',
    'Ionic bonds',
    'Covalent bonds',
    'Peptide bonds',
  ], 2, 'Covalent bonds (shared electron pairs) are WITHIN one H₂O. Hydrogen bonds are BETWEEN separate water molecules.'),
  mc('w10', W, 'If two water molecules are close to each other, then', [
    'The two oxygens form a covalent bond',
    'The oxygen of one and a hydrogen of the other form a hydrogen bond',
    'They always explode',
    'They form a peptide bond',
  ], 1, 'Hydrogen bonds form between the δ− oxygen of one water and a δ+ hydrogen of another.'),
  mc('w11', W, 'The _________________ bonds are weak and bond water molecules to other water molecules or polar substances.', [
    'Ionic',
    'Peptide',
    'Hydrogen',
    'Glycosidic',
  ], 2, 'Hydrogen bonds are weaker than covalent or ionic bonds, but they give water its special properties.'),
  mc('w12', W, 'Hydrogen bonds form ______ water molecules. Covalent bonds form ______ one water molecule.', [
    'within; between',
    'between; within',
    'only in ice; only in steam',
    'never; always',
  ], 1, 'Between separate molecules = hydrogen bonds. Within one molecule = covalent bonds.'),
  mc('w13', W, 'When water is heated, the first thing that happens is', [
    'The covalent bonds inside H₂O break',
    'The hydrogen bonds break',
    'Water turns into oil',
    'Oxygen becomes positive',
  ], 1, 'Heat first disrupts the weaker hydrogen bonds between molecules.'),
  mc('w14', W, 'What does the term cohesion mean?', [
    'When different types of molecules stick together',
    'When the same type of molecules stick together',
    'When a polymer is hydrolyzed',
    'When ice sinks',
  ], 1, 'Co- = together. Cohesion = water sticking to water.'),
  mc('w15', W, 'What does the term adhesion mean?', [
    'When the same type of molecules stick together',
    'When different types of molecules stick together',
    'When water freezes',
    'When a solute cannot dissolve',
  ], 1, 'Adhesion = water sticking to a different substance, like glass or a leaf.'),
  mc('w16', W, 'What word describes when water is attracted to other substances?', [
    'cohesion',
    'adhesion',
    'denaturation',
    'hydrolysis',
  ], 1, 'Attraction to a different substance is adhesion.'),
  mc('w17', W, 'With _______________ water forms round spheres of water on a surface.', [
    'adhesion only',
    'cohesion',
    'high pH',
    'peptide bonds',
  ], 1, 'Round droplets happen because water sticks to water (cohesion).'),
  mc('w18', W, 'When water forms a droplet or bulges up off a penny (in a sphere), this is an example of', [
    'Adhesion',
    'Cohesion',
    'Hydrolysis',
    'A base',
  ], 1, 'The bulge is cohesion: water molecules clinging to each other.'),
  mc('w19', W, 'Water can stick to a car windshield due to what property?', [
    'Cohesion',
    'Adhesion',
    'High heat of vaporization only',
    'Being nonpolar',
  ], 1, 'Windshield glass is a different substance, so that is adhesion.'),
  mc('w20', W, 'A meniscus in a glass graduated cylinder forms mainly because of', [
    'Cohesion only',
    'Adhesion',
    'Ice floating',
    'pH 14',
  ], 1, 'Water sticks to the glass (adhesion) and the surface curves. Read the bottom of the curve.'),
  mc('w21', W, 'The surface tension of water is due to cohesion. This is possible because of', [
    'ionic bonds in NaCl',
    'hydrogen bonds between water molecules',
    'peptide bonds',
    'ester linkages',
  ], 1, 'Hydrogen-bond cohesion makes the surface hard to stretch or break.'),
  mc('w22', W, 'Which characteristic of water will allow a paperclip to remain floating when it is gently placed on top of the water?', [
    'low specific heat',
    'surface tension as a result of hydrogen bonds',
    'being a nonpolar molecule',
    'having a pH of 14',
  ], 1, 'High surface tension from H-bond cohesion can support a light paperclip or a water strider.'),
  mc('w23', W, 'A water strider can walk on a pond mainly because water has high', [
    'heat of vaporization',
    'pH',
    'surface tension',
    'salinity',
  ], 2, 'Surface tension is how hard it is to break the surface. Water’s is high because of cohesion.'),
  mc('w24', W, 'Water moving up a piece of paper (against gravity) is displaying the property of water known as', [
    'denaturation',
    'capillary action',
    'hydrophobic exclusion',
    'quaternary structure',
  ], 1, 'Climbing a thin space uses cohesion + adhesion = capillary action.'),
  mc('w25', W, 'What property of water allows capillary action to work in plants?', [
    'Its polarity',
    'It is nonpolar',
    'It has no hydrogen bonds',
    'It is a lipid',
  ], 0, 'Polarity lets water form hydrogen bonds, which create cohesion and adhesion — the two parts of capillary action.'),
  mc('w26', W, 'Capillary action can move water from the roots up to the leaves of a tree through', [
    'cohesion only',
    'adhesion only',
    'both cohesion and adhesion',
    'neither cohesion nor adhesion',
  ], 2, 'Capillary action needs both: water-to-water (cohesion) and water-to-xylem walls (adhesion).'),
  mc('w27', W, 'Large bodies of water, such as lakes and oceans, do not quickly fluctuate in temperature. What is the reason?', [
    'Low specific heat',
    'High heat capacity / high specific heat',
    'Water is nonpolar',
    'Ice is denser than liquid water',
  ], 1, 'Water’s high specific heat (from hydrogen bonds) keeps temperatures more stable.'),
  mc('w28', W, 'What property of water helps moderate the temperature of Earth’s bodies of water?', [
    'surface tension only',
    'specific heat capacity',
    'being hydrophobic',
    'peptide bonding',
  ], 1, 'High specific heat means it takes a lot of energy to change water’s temperature.'),
  mc('w29', W, 'Because of water’s __________ it can absorb a lot of heat during the day and release it at night.', [
    'low density as a liquid',
    'high specific heat capacity',
    'nonpolar tails',
    'glycosidic linkages',
  ], 1, 'High specific heat lets water soak up heat by day and dump it at night, keeping climates steadier.'),
  mc('w30', W, 'Specific heat is the amount of energy required to', [
    'freeze 1 gram of ice',
    'raise 1 gram of a substance by 1°C',
    'break a peptide bond',
    'dissolve oil',
  ], 1, 'That is the definition. Water’s value is high because of hydrogen bonding.'),
  mc('w31', W, 'Ice floats on top of water because ice is', [
    'more dense',
    'less dense',
    'hydrophobic',
    'a protein',
  ], 1, 'Water expands as it freezes, so ice is less dense than liquid water.'),
  mc('w32', W, 'Why does ice float?', [
    'as water freezes, it expands and its density decreases',
    'ice is a lipid so it is hydrophobic',
    'ice has more H⁺ ions',
    'ice is heavier than water',
  ], 0, 'The crystalline lattice spaces molecules out, lowering density so ice sits on top.'),
  mc('w33', W, 'When water freezes into ice, molecules space out in a crystalline lattice, making ice ________________ than liquid water.', [
    'more dense',
    'less dense',
    'more polar',
    'more acidic',
  ], 1, 'Spaced-out molecules = lower density = ice floats and insulates lakes.'),
  mc('w34', W, 'Why does ice floating matter for living things in a lake?', [
    'Ice is hydrophobic so fish can breathe it',
    'The ice layer insulates water below so the lake does not freeze solid',
    'Ice raises the pH to 14',
    'Ice is a nucleic acid',
  ], 1, 'The floating ice lid lets aquatic life survive underneath.'),
  mc('w35', W, 'When you have a container filled with water and you pour oil on top, the oil never mixes because', [
    'oil is a polar substance',
    'oil is a nonpolar substance',
    'oil is an acid',
    'oil is hydrophilic',
  ], 1, 'Oil is hydrophobic/nonpolar, so it does not mix with polar water.'),
  mc('w36', W, 'Water molecules do not mix well with ____________ molecules.', [
    'polar',
    'ionic',
    'nonpolar',
    'hydrophilic',
  ], 2, 'Like dissolves like. Polar water does not mix with nonpolar substances.'),
  mc('w37', W, 'In order for water to form a solution with a substance, that substance must be', [
    'nonpolar',
    'polar (or ionic)',
    'a steroid',
    'a wax',
  ], 1, 'Water dissolves polar molecules and ions. Nonpolar stuff stays separate.'),
  mc('w38', W, 'When a substance is mixed with water, it can only be dissolved if it is', [
    'nonpolar',
    'polar',
    'a triglyceride',
    'oil',
  ], 1, 'Polar (or charged) solutes dissolve in polar water.'),
  mc('w39', W, 'Because water dissolves many substances, it is known as a', [
    'universal solvent',
    'universal solute',
    'nonpolar oil',
    'buffer enzyme',
  ], 0, 'Polarity lets water dissolve lots of ions and polar molecules, so it is called the universal solvent.'),
  mc('w40', W, 'In sugar water, water is the ______ and sugar is the ______.', [
    'solute; solvent',
    'solvent; solute',
    'acid; base',
    'polymer; monomer',
  ], 1, 'Solvent does the dissolving (water). Solute is what gets dissolved (sugar).'),
  mc('w41', W, 'A solution is', [
    'a pure element',
    'a liquid mixture of two or more substances',
    'only an acid',
    'only ice',
  ], 1, 'Example: sugar water. Water = solvent, sugar = solute.'),
  mc('w42', W, 'Hydrophilic substances', [
    'fear water and do not dissolve',
    'love water and usually dissolve in it',
    'are always lipids',
    'are always nonpolar',
  ], 1, 'Hydrophilic = water-loving. Usually polar molecules or ions, like salt and sugar.'),
  mc('w43', W, 'Hydrophobic substances', [
    'dissolve easily in water',
    'do not have an affinity for water',
    'are always acids',
    'are always ions',
  ], 1, 'Hydrophobic = water-fearing. Typically nonpolar, like oil.'),
  mc('w44', W, 'Which pair is correctly matched?', [
    'oil — hydrophilic and polar',
    'salt — hydrophilic and ionic/polar',
    'sugar — hydrophobic',
    'NaCl — nonpolar wax',
  ], 1, 'Salt and sugar are hydrophilic. Oil is hydrophobic.'),
  mc('w45', W, 'Sweating cools you because water has a high', [
    'density as a solid',
    'heat of vaporization',
    'pH',
    'glycosidic linkage',
  ], 1, 'It takes a lot of heat to evaporate water. That heat leaves your skin, so you cool down (evaporative cooling).'),
  mc('w46', W, 'Heat of vaporization is the amount of energy required to', [
    'raise 1 g by 1°C',
    'turn a liquid into a gas',
    'freeze water',
    'form a peptide bond',
  ], 1, 'Water’s high heat of vaporization also helps keep water liquid on Earth and in your body.'),
  mc('w47', W, 'Water dissociates into', [
    'Na⁺ and Cl⁻',
    'H⁺ and OH⁻',
    'CO₂ and O₂',
    'amino acids',
  ], 1, 'H₂O ⇌ H⁺ + OH⁻. Pure water has equal amounts of both (pH 7).'),
  mc('w48', W, 'Acids have a pH ______ and a high concentration of ______.', [
    '> 7; OH⁻',
    '< 7; H⁺',
    '= 14; lipids',
    '= 7; salt only',
  ], 1, 'Acids: pH below 7, extra H⁺, sour/tart (citrus, gastric acid).'),
  mc('w49', W, 'Bases (alkaline solutions) have a pH ______ and a high concentration of ______.', [
    '< 7; H⁺',
    '> 7; OH⁻',
    '= 0; sugar',
    '= 7; oil',
  ], 1, 'Bases: pH above 7, extra OH⁻, bitter (soap, bleach).'),
  mc('w50', W, 'Lemon juice tastes sour and has lots of H⁺ ions. It is', [
    'a base with pH 10',
    'neutral water',
    'an acid with pH below 7',
    'a lipid',
  ], 2, 'High H⁺ and sour taste = acid.'),
  mc('w51', W, 'Soap tastes bitter and has lots of OH⁻. It is', [
    'an acid',
    'a base (alkaline)',
    'pure water',
    'a carbohydrate ring',
  ], 1, 'Bitter + OH⁻ = base. Basic can also be called alkaline.'),
  mc('w52', W, 'A pH that is way too acidic or basic can unfold proteins. That unfolding is called', [
    'capillary action',
    'denaturation',
    'dehydration synthesis',
    'adhesion',
  ], 1, 'Most cells like pH near 7. Extreme pH denatures proteins and wrecks their shape/function.'),
  mc('w53', W, 'Pure water is ______ because it has equal H⁺ and OH⁻.', [
    'a strong acid',
    'a strong base',
    'neutral (pH 7)',
    'hydrophobic',
  ], 2, 'Equal H⁺ and OH⁻ = pH 7 = neutral.'),
  mc('w54', W, 'pH measures the concentration of', [
    'OH⁻ only, never H⁺',
    'H⁺ ions',
    'glucose rings',
    'fatty acid tails',
  ], 1, 'pH ranks acidity/alkalinity by H⁺ concentration. Most values fall from 0–14, but outside that is possible.'),
  mc('w55', W, 'Look at this water molecule. Why is the oxygen side slightly negative?', [
    'Hydrogen pulls electrons harder than oxygen',
    'Oxygen pulls electrons harder than hydrogen',
    'Water has no charges at all',
    'Ice is denser than liquid water',
  ], 1, 'Oxygen hogs the shared electrons, so oxygen is δ− and the hydrogens are δ+.', 'water-polar'),
  mc('w56', W, 'The dashed line between these two water molecules is a', [
    'covalent bond inside one H₂O',
    'hydrogen bond between molecules',
    'peptide bond',
    'glycosidic linkage',
  ], 1, 'Dashed H-bonds connect separate waters. Solid covalent bonds are inside each H₂O.', 'water-hbonds'),
  multi('w57', W, 'Choose ALL properties that come from water’s hydrogen bonding / polarity.', [
    'Cohesion and surface tension',
    'High specific heat',
    'Being less dense as a solid',
    'Having peptide bonds',
  ], [0, 1, 2], 'Hydrogen bonding explains cohesion/surface tension, high specific heat, ice floating, capillary action, and the solvent ability. Peptide bonds are for proteins, not water.'),
  multi('w58', W, 'Choose ALL statements that are true of cohesion.', [
    'Same-type molecules stick together',
    'It helps water form round droplets',
    'It is a cause of high surface tension',
    'It means water sticks to glass',
  ], [0, 1, 2], 'Water-to-glass is adhesion, not cohesion. Cohesion is water-to-water.'),
  multi('w59', W, 'Choose ALL that are hydrophilic.', [
    'Salt (NaCl)',
    'Sugar',
    'Olive oil',
    'Wax',
  ], [0, 1], 'Salt and sugar dissolve in water. Oil and wax are hydrophobic/nonpolar.'),
  multi('w60', W, 'Choose ALL that correctly describe capillary action.', [
    'Water can move upward in a thin tube',
    'It uses both cohesion and adhesion',
    'It helps water climb plant vessels',
    'It is caused by water being nonpolar',
  ], [0, 1, 2], 'Capillary action depends on polarity and hydrogen bonds, not on water being nonpolar.'),
  mc('w61', W, 'Which example best shows high specific heat?', [
    'A paperclip sitting on water',
    'A pond staying about the same temperature from day to night',
    'Oil sitting on water',
    'A meniscus in a cylinder',
  ], 1, 'Land/air swing more than water because water resists temperature change.'),
  mc('w62', W, 'Which example best shows adhesion?', [
    'A round raindrop',
    'Water climbing a paper towel',
    'Two water molecules hydrogen-bonding only to each other, ignoring the towel',
    'Ice floating',
  ], 1, 'Climbing paper needs adhesion (water to paper) plus cohesion. A round drop is mainly cohesion.'),
  mc('w63', W, 'Why is water called polar instead of nonpolar?', [
    'Electrons are shared equally between O and H',
    'Electrons are shared unequally, making opposite partial charges',
    'Water contains only carbon',
    'Water has peptide bonds',
  ], 1, 'Unequal sharing → partial charges → polar.'),
  mc('w64', W, 'Which bond is strongest in water-related chemistry from this unit?', [
    'Hydrogen bonds between waters',
    'Covalent bonds within one H₂O',
    'The attraction of oil to water',
    'A dashed line in a diagram',
  ], 1, 'Covalent > hydrogen > the very weak interactions nonpolar oil has with water.'),
  mc('w65', W, 'Read a meniscus in a glass graduated cylinder at', [
    'the top of the curve',
    'the bottom of the curve',
    'the middle of the lab table',
    'wherever the oil floats',
  ], 1, 'Adhesion pulls water up the glass. Measure from the bottom of the curve.'),
  mc('w66', W, 'Evaporative cooling happens because', [
    'the slowest molecules leave first and heat the surface',
    'the fastest (hottest) molecules leave as gas and the remaining liquid is cooler',
    'ice sinks',
    'pH jumps to 14',
  ], 1, 'The remaining liquid has lost its hottest molecules, so the surface cools — that is why sweat works.'),
  mc('w67', W, 'Most cells exist near pH ______ . Far from that, proteins may denature.', [
    '1',
    '7',
    '14',
    '0',
  ], 1, 'Near-neutral pH is where most cell chemistry works. Extreme acid or base unfolds proteins.'),
  mc('w68', W, 'Which is a correct acid vs base pair?', [
    'Lemon juice = base; bleach = acid',
    'Gastric acid = acid; soap = base',
    'Both lemon and soap are pH 7',
    'Bleach is pH 2',
  ], 1, 'Citrus/stomach acid = acids. Soap/bleach = bases.'),
]
