import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const S = 'structures' as const

export const STRUCTURE_QUESTIONS: BioPracticeQuestion[] = [
  mc('s1', S, 'Which macromolecule group does this ring-shaped sugar belong to?', [
    'lipid',
    'carbohydrate',
    'protein',
    'nucleic acid',
  ], 1, 'A single carbon ring with OH/CH₂OH is a monosaccharide (carbohydrate).', 'glucose'),
  mc('s2', S, 'This molecule is specifically a', [
    'fatty acid',
    'monosaccharide',
    'nucleotide',
    'steroid',
  ], 1, 'One sugar ring = monosaccharide. Names often end in -ose (glucose, fructose).', 'glucose'),
  mc('s3', S, 'Which group does this two-ring molecule belong to?', [
    'protein',
    'nucleic acid',
    'carbohydrate',
    'lipid',
  ], 2, 'Two sugar rings joined by a glycosidic linkage = disaccharide (carb).', 'disaccharide'),
  mc('s4', S, 'The labeled oxygen bridge between the two rings is a', [
    'peptide bond',
    'ester linkage',
    'glycosidic linkage',
    'hydrogen bond between bases',
  ], 2, 'Sugar-to-sugar bonds are glycosidic linkages.', 'disaccharide'),
  mc('s5', S, 'A long chain of these rings is which macromolecule group?', [
    'lipid',
    'carbohydrate (polysaccharide)',
    'protein',
    'nucleic acid',
  ], 1, 'Starch, glycogen, and cellulose look like repeating sugar rings.', 'polysaccharide'),
  mc('s6', S, 'This chain of sugar rings could be any of these EXCEPT', [
    'starch',
    'glycogen',
    'cellulose',
    'a triglyceride',
  ], 3, 'Triglycerides are glycerol + three fatty acid tails, not sugar rings.', 'polysaccharide'),
  mc('s7', S, 'Which macromolecule group is this (amino group, central C, carboxyl, R)?', [
    'carbohydrate',
    'lipid',
    'protein',
    'nucleic acid',
  ], 2, 'That is an amino acid, the monomer of proteins.', 'amino-acid'),
  mc('s8', S, 'Label the blue H₂N, red COOH, and yellow R. They are', [
    'phosphate, sugar, base',
    'amino group, carboxyl group, R group',
    'glycerol, tail, phosphate',
    'A, T, and G',
  ], 1, 'Every amino acid has those three parts. R is the only part that changes.', 'amino-acid'),
  mc('s9', S, 'Two amino acids joined with water released is a', [
    'disaccharide',
    'dipeptide (protein)',
    'triglyceride',
    'nucleotide',
  ], 1, 'Peptide bond + leftover water = dehydration synthesis of a dipeptide.', 'dipeptide'),
  mc('s10', S, 'Which macromolecule group is glycerol + three zigzag tails?', [
    'carbohydrate',
    'lipid (triglyceride)',
    'protein',
    'nucleic acid',
  ], 1, 'Classic fat diagram: glycerol backbone and three fatty acids.', 'triglyceride'),
  mc('s11', S, 'Count the tails on this lipid. It is a', [
    'phospholipid (2 tails)',
    'triglyceride (3 tails)',
    'steroid (0 tails)',
    'nucleotide',
  ], 1, '3 tails = triglyceride. 2 tails + phosphate head = phospholipid.', 'triglyceride'),
  mc('s12', S, 'Which group is a phosphate head plus two tails?', [
    'carbohydrate',
    'protein',
    'lipid (phospholipid)',
    'nucleic acid',
  ], 2, 'Membrane lipids. Heads love water, tails hate it.', 'phospholipid'),
  mc('s13', S, 'How many fatty acid tails does a phospholipid have?', [
    '1',
    '2',
    '3',
    '4',
  ], 1, 'Phosphate + glycerol + TWO tails. One is often kinked (unsaturated).', 'phospholipid'),
  mc('s14', S, 'Four fused rings = which macromolecule group?', [
    'carbohydrate',
    'lipid (steroid)',
    'protein',
    'nucleic acid',
  ], 1, 'Cholesterol, estrogen, testosterone. Hydrophobic, so they count as lipids.', 'steroid'),
  mc('s15', S, 'This 4-ring lipid does NOT contain', [
    'a hydrophobic carbon skeleton',
    'glycerol and fatty-acid tails',
    'examples like cholesterol',
    'a shape used for some hormones',
  ], 1, 'Steroids have no glycerol and no ester-bonded tails.', 'steroid'),
  mc('s16', S, 'A straight zigzag with a COOH end and no kinks is a', [
    'unsaturated fatty acid',
    'saturated fatty acid (lipid)',
    'monosaccharide',
    'nucleotide',
  ], 1, 'Single bonds only → straight → solid at room temp.', 'sat-fa'),
  mc('s17', S, 'A zigzag with a kink / C=C is a', [
    'saturated fatty acid',
    'unsaturated fatty acid (lipid)',
    'cellulose',
    'amino acid',
  ], 1, 'Double bond → kink → liquid at room temp.', 'unsat-fa'),
  mc('s18', S, 'If a test asks you to mark where a fatty acid is unsaturated, you point to', [
    'the COOH acid group only',
    'the C=C double bond / kink',
    'the phosphate head',
    'the R group',
  ], 1, 'Unsaturated means a double bond that bends the tail.', 'unsat-fa'),
  mc('s19', S, 'This 3-carbon backbone with 3 OH groups is', [
    'glucose',
    'glycerol (lipid building block)',
    'an amino acid',
    'a nitrogenous base',
  ], 1, 'Glycerol holds fatty acids in fats and phospholipids.', 'glycerol'),
  mc('s20', S, 'Phosphate + sugar + base belongs to which group?', [
    'carbohydrate',
    'lipid',
    'protein',
    'nucleic acid',
  ], 3, 'That trio is a nucleotide, monomer of DNA/RNA.', 'nucleotide'),
  mc('s21', S, 'The pentagon in a nucleotide is the', [
    'nitrogenous base',
    'sugar',
    'phosphate',
    'R group',
  ], 1, 'Sugar is a 5-sided ring. Phosphate is the P circle. Base is the bigger rectangle.', 'nucleotide'),
  mc('s22', S, 'A double helix with A–T and G–C is', [
    'protein',
    'lipid',
    'nucleic acid (DNA)',
    'cellulose',
  ], 2, 'DNA stores genetic information. Bases pair with hydrogen bonds.', 'dna'),
  mc('s23', S, 'Look at A vs B. Which is unsaturated?', [
    'A (straight)',
    'B (kinked)',
    'both are glycogen',
    'neither is a lipid',
  ], 1, 'Kink = double bond = unsaturated.', 'fatty-compare'),
  mc('s24', S, 'Water leaving as two pieces join is which reaction, and which macromolecules use it?', [
    'hydrolysis — only lipids',
    'dehydration synthesis — carbs, lipids, and proteins all use a version of it',
    'adhesion — only water',
    'denaturation — only DNA',
  ], 1, 'Carbs (glycosidic), lipids (ester), proteins (peptide) all form by removing water.', 'dehydration'),
  mc('s25', S, 'Adding water to split a polymer is', [
    'dehydration synthesis',
    'hydrolysis',
    'cohesion',
    'quaternary structure',
  ], 1, 'This is how you digest starch, fat, and protein.', 'hydrolysis'),
  mc('s26', S, 'If a diagram shows H₂N–C–COOH, you are looking at a', [
    'lipid',
    'protein building block',
    'nucleotide',
    'monosaccharide',
  ], 1, 'Amino + carboxyl = amino acid = protein monomer.', 'amino-acid'),
  mc('s27', S, 'If a diagram shows a phosphate circle stuck to a 5-carbon sugar and a base, it is a', [
    'amino acid',
    'nucleotide',
    'triglyceride',
    'steroid',
  ], 1, 'P + sugar + base = nucleotide.', 'nucleotide'),
  mc('s28', S, 'If a diagram shows four fused rings and no tails, pick the group', [
    'carbohydrate',
    'lipid',
    'protein',
    'nucleic acid',
  ], 1, 'Steroid lipids. Do not confuse the rings with sugar rings — steroids are 4 fused rings.', 'steroid'),
  multi('s29', S, 'Choose ALL structures that are lipids.', [
    'Triglyceride (glycerol + 3 tails)',
    'Phospholipid (head + 2 tails)',
    'Steroid (4 fused rings)',
    'Glucose ring',
  ], [0, 1, 2], 'Glucose is a carbohydrate.', 'triglyceride'),
  multi('s30', S, 'Choose ALL structures that are carbohydrates.', [
    'Monosaccharide ring',
    'Disaccharide (two rings)',
    'Polysaccharide chain',
    'Amino acid with an R group',
  ], [0, 1, 2], 'Amino acids are proteins.', 'glucose'),
  multi('s31', S, 'Choose ALL that you should be able to identify by sight for this test.', [
    'Amino acid (NH₂, COOH, R)',
    'Nucleotide (P, sugar, base)',
    'Triglyceride vs phospholipid vs steroid',
    'A country on a world map',
  ], [0, 1, 2], 'Honors Bio Test 1 wants monomer/polymer structures by look and characteristics — not geography.'),
  mc('s32', S, 'You want to bond two glucose molecules. What is released, and what bond forms?', [
    'A fatty acid; ester linkage',
    'H₂O; glycosidic linkage',
    'CO₂; peptide bond',
    'A phosphate; hydrogen bond',
  ], 1, 'Dehydration synthesis of carbs: water out, glycosidic linkage in.', 'disaccharide'),
  mc('s33', S, 'To build a phospholipid you need', [
    'two amino acids',
    'phosphate + glycerol + two fatty acids',
    'four nucleotides',
    'only glucose rings',
  ], 1, 'Memorize the recipe: head, backbone, two tails.', 'phospholipid'),
  mc('s34', S, 'To build a dipeptide you need', [
    'two amino acids (and you lose one water)',
    'three fatty acids',
    'two nucleotides only',
    'cellulose',
  ], 0, 'Two AAs → peptide bond + H₂O.', 'dipeptide'),
  mc('s35', S, 'To build a disaccharide you need', [
    'two monosaccharides (and you lose one water)',
    'one glycerol and three tails',
    'four fused rings',
    'hemoglobin subunits',
  ], 0, 'Two sugars → glycosidic linkage + H₂O.', 'disaccharide'),
  mc('s36', S, 'A test picture of DNA will usually show', [
    'three fatty tails',
    'a double helix and base pairs',
    'only one sugar ring',
    'a meniscus',
  ], 1, 'Recognize the twisted ladder / two backbones with A–T and G–C.', 'dna'),
  mc('s37', S, 'Which diagram is hydrophilic on one end and hydrophobic on the other?', [
    'glucose only',
    'phospholipid',
    'glycogen chain',
    'a fully polar salt crystal',
  ], 1, 'Phosphate head = hydrophilic. Fatty tails = hydrophobic. That is why membranes form.', 'phospholipid'),
  mc('s38', S, 'Which structure has a peptide bond you should be able to point to?', [
    'disaccharide',
    'dipeptide',
    'triglyceride',
    'steroid',
  ], 1, 'Peptide bonds are C–N links between amino acids. Also know N-terminus vs C-terminus.', 'dipeptide'),
]
