import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'passive' as const

export const PASSIVE_QUESTIONS: BioPracticeQuestion[] = [
  mc('p1', T, 'Equilibrium means', [
    'all molecules stop moving forever',
    'equal concentration of solutes on both sides of the membrane',
    'only ATP is used',
    'the cell has no water',
  ], 1, 'Cells want to reach equilibrium. Molecules still move; net movement is zero (dynamic equilibrium).'),
  mc('p2', T, 'A concentration gradient is', [
    'equal amounts of solute on each side',
    'unequal amounts of solute on each side',
    'a type of virus',
    'a cell wall sugar',
  ], 1, 'Passive transport needs a gradient: high vs low solute.'),
  mc('p3', T, 'Passive transport requires', [
    'ATP',
    'no energy; molecules move high → low (down/with the gradient)',
    'vesicles only',
    'a nucleus',
  ], 1, 'Down the concentration gradient. No ATP.'),
  mc('p4', T, 'In passive transport, molecules move', [
    'low → high, against the gradient, using ATP',
    'high → low, down/with the gradient, without ATP',
    'only by phagocytosis',
    'only through plasmodesmata',
  ], 1, 'If it says up/against the gradient, that is active, not passive.'),
  mc('p5', T, 'The three types of passive transport are', [
    'endocytosis, exocytosis, and the Na+/K+ pump',
    'simple diffusion, osmosis, and facilitated diffusion',
    'phagocytosis, pinocytosis, and receptor-mediated',
    'binary fission, mitosis, and budding',
  ], 1, 'All three are high → low and need no ATP.'),
  mc('p6', T, 'Simple diffusion is', [
    'movement of molecules (fluid or gas) from HIGH to LOW concentration until equilibrium',
    'water only, using aquaporins and ATP',
    'bulk vesicle export',
    '3 Na⁺ out and 2 K⁺ in',
  ], 0, 'Examples: oxygen, carbon dioxide, and other small molecules.'),
  mc('p7', T, 'Which is the best simple-diffusion example?', [
    'glucose through a carrier with ATP',
    'O₂ or CO₂ moving high → low through the bilayer',
    'a macrophage eating bacteria',
    'insulin binding a receptor then being engulfed',
  ], 1, 'Small uncharged gases simple-diffuse.'),
  mc('p8', T, 'This cell’s membrane is permeable to starch ONLY. Which molecule moves?', [
    'glucose only',
    'starch only',
    'both equally because both are sugars',
    'neither; the membrane is closed',
  ], 1, 'Permeable to starch ONLY means glucose cannot cross, even if it has a gradient.', 'diffusion-starch'),
  mc('p9', T, '60% starch inside, 10% starch outside, permeable to starch only. Starch will', [
    'enter the cell (low → high)',
    'leave the cell (high → low), no ATP',
    'stay put because starch is always trapped',
    'require phagocytosis',
  ], 1, 'Passive: 60% → 10%, so starch moves OUT.', 'diffusion-starch'),
  mc('p10', T, 'In that starch diagram, why doesn’t glucose’s 10% inside vs 40% outside decide the answer?', [
    'Glucose always uses ATP',
    'The membrane is not permeable to glucose, so glucose cannot move',
    'Glucose is a gas',
    'Starch is an ion',
  ], 1, 'Always check permeability before drawing arrows.', 'diffusion-starch'),
  mc('p11', T, 'Osmosis is', [
    'simple diffusion of water across the cell membrane',
    'diffusion of starch only',
    'active pumping of water with ATP always',
    'phagocytosis of water',
  ], 0, 'Water moves high water potential → low water potential. No ATP (“water slide”).'),
  mc('p12', T, 'High water potential means', [
    'high solute concentration',
    'low solute concentration',
    'no water at all',
    'only ions present',
  ], 1, 'Water potential is about how much free water. Lots of solute = low water potential.'),
  mc('p13', T, 'Low water potential means', [
    'high solute concentration',
    'pure distilled water with zero solute',
    'no membrane',
    'isotonic always',
  ], 0, 'Crowded with solute → less “room” for water → water flows toward that side.'),
  mc('p14', T, 'During osmosis, water moves', [
    'toward solutes: HIGH water concentration → LOW water concentration',
    'away from solutes always using ATP',
    'only through the Na+/K+ pump',
    'from low water potential to high water potential',
  ], 0, 'Water slides toward the saltier/sweeter side.'),
  mc('p15', T, 'An isotonic solution has', [
    'more solute outside than inside',
    'equal solute in and out; water moves in AND out at equal rates (dynamic equilibrium)',
    'no water movement of any kind, even individual molecules',
    'only proteins crossing',
  ], 1, 'Happy animal cell. Plant cell is alive but limp.'),
  mc('p16', T, 'A hypotonic solution has', [
    'higher solute outside than inside',
    'lower solute outside than inside, so water rushes IN and the cell swells like a hippo',
    'equal solute',
    'no water',
  ], 1, 'Hypo = low solute (like hypothermia = low temperature). Water enters.'),
  mc('p17', T, 'A hypertonic solution has', [
    'higher solute outside; water leaves and the cell shrivels',
    'lower solute outside; the cell bursts immediately in every organism',
    'equal solute',
    'only oxygen outside',
  ], 0, 'Hyper = high solute. “When you are hyper you sweat and lose water.”'),
  mc('p18', T, 'An egg in a hypotonic solution is ______ compared to that solution.', [
    'also hypotonic',
    'hypertonic (more solute inside than in the solution)',
    'a prokaryote',
    'isotonic only if it bursts',
  ], 1, 'The three words are adjectives about solute. The egg has more solute than a dilute solution, so the egg is hypertonic to the solution.'),
  mc('p19', T, 'Animal cell in hypotonic solution', [
    'is turgid and happiest',
    'swells and may burst (cytolysis)',
    'is always plasmolyzed in a good way',
    'makes a cellulose wall instantly',
  ], 1, 'No cell wall + no giant vacuole to handle extra water well.', 'animal-tonicity'),
  mc('p20', T, 'Animal cell in hypertonic solution', [
    'becomes turgid',
    'shrivels (notes also call this plasmolysis) and is in trouble',
    'bursts from cytolysis',
    'is happiest',
  ], 1, 'Water leaves. Animal cells like isotonic.', 'animal-tonicity'),
  mc('p21', T, 'Animal cell in isotonic solution', [
    'bursts',
    'has no net H₂O movement and is the happy animal cell',
    'is wilted like a plant in hypertonic solution',
    'always plasmolyzes',
  ], 1, 'Dynamic equilibrium. Best environment for animal cells.', 'animal-tonicity'),
  mc('p22', T, 'Cytolysis is', [
    'the cell swelling and bursting',
    'the plant cell becoming turgid in a healthy way',
    'binary fission',
    'exocytosis of hormones',
  ], 0, 'Dead/burst animal cell in hypotonic solution.'),
  mc('p23', T, 'Contractile vacuoles', [
    'are found in animal cells to prevent cytolysis',
    'are NOT in animal cells; freshwater protists like Amoeba use them to push out extra water',
    'are chloroplasts',
    'make peptidoglycan',
  ], 1, 'They help prevent cytolysis in those protists.'),
  mc('p24', T, 'Plant cell in hypertonic solution', [
    'is turgid and happy',
    'shrivels (plasmolysis) = wilted/dead-looking plant cell',
    'bursts easily like a red blood cell',
    'has no vacuole change',
  ], 1, 'Membrane pulls away from the wall.', 'plant-tonicity'),
  mc('p25', T, 'Plant cell in isotonic solution', [
    'is the happiest, most turgid state',
    'has no net H₂O movement; alive but limp',
    'always bursts',
    'undergoes cytolysis',
  ], 1, 'Plants prefer hypotonic (turgid). Isotonic = meh/limp.', 'plant-tonicity'),
  mc('p26', T, 'Plant cell in hypotonic solution', [
    'bursts because plants have no wall',
    'is turgid = alive, happy, slightly swelled and well-watered',
    'plasmolyzes',
    'loses its central vacuole',
  ], 1, 'Wall + large central vacuole resist bursting.', 'plant-tonicity'),
  mc('p27', T, 'Turgor pressure is', [
    'the force of fluid pushing the membrane against the cell wall',
    'ATP used in the Na+/K+ pump',
    'the pressure of a viral capsid',
    'binary fission force',
  ], 0, 'Turgid = that pressure is high. Plants hold more water than animal cells because of the wall and large vacuole.'),
  mc('p28', T, 'Why don’t plant cells burst in hypotonic solutions as easily as animal cells?', [
    'They have no membrane',
    'Large central vacuole + cell wall resist bursting; turgor actually helps the plant stand up',
    'They use only active transport for water',
    'They have centrioles',
  ], 1, 'Animal cells lack that wall backup.'),
  mc('p29', T, 'This beaker is split by a membrane permeable to water only. Side A has more red sucrose. Highest water potential is', [
    'A',
    'B',
    'equal',
    'neither has water',
  ], 1, 'Fewer sucrose dots on B = more free water = higher water potential.', 'osmosis-beaker'),
  mc('p30', T, 'In that same beaker, highest solute concentration is', [
    'A',
    'B',
    'equal',
    'only in the membrane',
  ], 0, 'More red sucrose on A.', 'osmosis-beaker'),
  mc('p31', T, 'Water will move', [
    'A → B',
    'B → A (high water → low water), no ATP',
    'not at all because sucrose blocks water forever',
    'only if a pump uses ATP',
  ], 1, 'Osmosis is passive. Water goes toward the sucrose.', 'osmosis-beaker'),
  mc('p32', T, 'Cell has 90% water; surroundings have 10% water; membrane permeable to water only. The solution outside is', [
    'hypotonic',
    'hypertonic (high solute / low water outside)',
    'isotonic',
    'a gas',
  ], 1, 'Outside has little water → lots of solute relatively. Hypertonic solution.', 'hypertonic-cell'),
  mc('p33', T, 'In that 90% vs 10% water diagram, water moves', [
    'into the cell',
    'out of the cell (high water → low water)',
    'not at all',
    'as starch',
  ], 1, 'The cell will shrink/shrivel (plasmolysis).', 'hypertonic-cell'),
  mc('p34', T, 'After water leaves that cell, it will', [
    'burst (cytolysis)',
    'become turgid',
    'shrink/shrivel (plasmolysis)',
    'divide by binary fission',
  ], 2, 'Hypertonic surroundings pull water out.', 'hypertonic-cell'),
  mc('p35', T, 'The cell in that diagram (90% water inside) is ______ compared with the solution.', [
    'hypertonic',
    'hypotonic (LOW solute inside relative to the salty outside)',
    'a virus',
    'isotonic',
  ], 1, 'Notes: HYPOtonic cell (low solute) in a HYPERtonic solution (high solute).', 'hypertonic-cell'),
  mc('p36', T, 'Facilitated diffusion is', [
    'simple diffusion but with channel or carrier proteins; still HIGH → LOW; still no ATP',
    'the Na+/K+ pump',
    'exocytosis',
    'water moving with ATP only',
  ], 0, 'Proteins facilitate molecules that could not pass or fit. Example: glucose or amino acids.', 'channel-carrier'),
  mc('p37', T, 'Molecules that use facilitated diffusion are typically', [
    'O₂ and CO₂',
    'large, polar, and/or charged (example: glucose)',
    'entire bacteria',
    'whole nuclei',
  ], 1, 'They need a protein helper but still go down the gradient.'),
  mc('p38', T, 'Channel proteins in facilitated diffusion', [
    'are peripheral only',
    'are integral proteins with a pore; molecules move randomly through',
    'always require ATP',
    'are cellulose',
  ], 1, 'Embedded in the membrane with a tunnel.', 'channel-carrier'),
  mc('p39', T, 'Aquaporins are', [
    'steroids',
    'channel proteins that let water pass faster than simple osmosis',
    'Na+/K+ pumps',
    'viral capsids',
  ], 1, 'Still passive — they just speed water movement.'),
  mc('p40', T, 'Carrier proteins in facilitated diffusion', [
    'change shape to move material across',
    'are 4 fused rings',
    'are only oligosaccharides',
    'always move low → high with ATP',
  ], 0, 'Some extend through the membrane; others do not. Still high → low if it is facilitated diffusion.', 'channel-carrier'),
  mc('p41', T, 'Glucose crossing high → low using a channel or carrier is', [
    'simple diffusion',
    'facilitated diffusion',
    'phagocytosis',
    'exocytosis',
  ], 1, 'Glucose is large enough that it needs help. No ATP if it is down the gradient.'),
  mc('p42', T, 'If glucose is HIGH outside and LOW inside, facilitated diffusion moves glucose', [
    'out of the cell with ATP',
    'into the cell, high → low, using a protein, no ATP',
    'not at all',
    'only if the cell is prokaryotic',
  ], 1, 'Match the arrows to the gradient AND the protein.'),
  mc('p43', T, 'Simple diffusion vs facilitated diffusion: both', [
    'require ATP',
    'move high → low with no ATP; facilitated needs a protein, simple does not',
    'use vesicles',
    'move low → high',
  ], 1, 'The protein is the difference, not energy or direction.'),
  mc('p44', T, 'Osmosis vs simple diffusion: osmosis is specifically', [
    'ion pumping',
    'water moving across a membrane down its own gradient',
    'glucose using a carrier',
    'exocytosis of protein',
  ], 1, 'Both are passive. Osmosis = water version of simple diffusion (though aquaporins can speed water).'),
  mc('p45', T, 'A red blood cell in distilled water (almost no solute) will', [
    'shrivel',
    'take in water and risk cytolysis',
    'become a plant cell',
    'pump 3 Na⁺ in',
  ], 1, 'Distilled water is hypotonic to the cell.'),
  mc('p46', T, 'A red blood cell in very salty water will', [
    'burst',
    'lose water and shrivel',
    'become turgid',
    'grow a cell wall',
  ], 1, 'Salty water is hypertonic.'),
  mc('p47', T, 'Elodea (plant) in salt water looks wilted because', [
    'cytolysis burst the wall',
    'plasmolysis: water left and the membrane pulled inward',
    'chloroplasts became mitochondria',
    'it used pinocytosis of salt crystals',
  ], 1, 'Hypertonic environment.'),
  mc('p48', T, 'A well-watered plant stands up because cells are', [
    'plasmolyzed',
    'turgid from hypotonic surroundings and turgor pressure',
    'in a hypertonic soil with no water',
    'isotonic and bursting',
  ], 1, 'Happy plant = hypotonic environment.'),
  mc('p49', T, 'If two sides are already equal in solute, net diffusion', [
    'speeds up with more ATP',
    'is zero even though molecules still randomly move',
    'becomes phagocytosis',
    'reverses the membrane',
  ], 1, 'That is equilibrium / dynamic equilibrium.'),
  mc('p50', T, 'Passive transport CANNOT happen if', [
    'there is a concentration gradient',
    'there is no concentration gradient (already equal)',
    'O₂ is present',
    'a channel exists',
  ], 1, 'Notes: must have unequal solute on each side to occur (net).'),
  multi('p51', T, 'Choose ALL types of passive transport.', [
    'simple diffusion',
    'osmosis',
    'facilitated diffusion',
    'sodium-potassium pump',
  ], [0, 1, 2], 'The pump is active (ATP, against the gradient).'),
  multi('p52', T, 'Choose ALL true of hypotonic vs hypertonic.', [
    'Hypotonic solution = low solute outside; water in; swell/hippo',
    'Hypertonic solution = high solute outside; water out; shrink',
    'The terms describe solute amount, not a magic third kind of molecule',
    'Hypotonic always kills plant cells',
  ], [0, 1, 2], 'Hypotonic is actually what plants like (turgid).'),
  multi('p53', T, 'Choose ALL differences: animal vs plant in the same solutions.', [
    'Animals are happiest isotonic; plants are happiest hypotonic/turgid',
    'Hypotonic can cytolyse animals; plants resist bursting with wall + vacuole',
    'Hypertonic shrivels both (plasmolysis / wilt)',
    'Plant cells prefer hypertonic soil with no water',
  ], [0, 1, 2], 'Isotonic plants are limp, not peak health.'),
  mc('p54', T, 'Amino acids entering a cell high → low with a protein helper is', [
    'simple diffusion',
    'facilitated diffusion',
    'phagocytosis',
    'exocytosis',
  ], 1, 'Notes list glucose or amino acids as facilitated-diffusion examples.'),
  mc('p55', T, 'If a diagram shows a pore and glucose moving high outside → low inside, it is a', [
    'steroid',
    'channel protein used in facilitated diffusion',
    'exocytic vesicle',
    'plasmid',
  ], 1, 'Pore = channel. Shape-change blob = carrier.', 'channel-carrier'),
  mc('p56', T, 'If a diagram shows a protein changing shape to ferry glucose down its gradient, it is a', [
    'carrier protein (facilitated diffusion)',
    'capsid',
    'cellulose microfibril',
    'tight junction only',
  ], 0, 'Still no ATP if it is down the gradient.', 'channel-carrier'),
  mc('p57', T, 'Water moving toward a high-solute side is sometimes remembered as', [
    'water running uphill with ATP',
    'a water slide: high → low water, no energy needed',
    'phagocytosis',
    'binary fission',
  ], 1, 'Notes’ mnemonic for osmosis.'),
  mc('p58', T, 'Which environment is worst for an animal cell AND a plant cell?', [
    'isotonic',
    'hypertonic (water leaves both)',
    'slightly hypotonic for the plant only',
    'the plant’s preferred turgid state',
  ], 1, 'Both lose water. Animal shrivels; plant plasmolyzes/wilts.'),
  mc('p59', T, 'U-tube: left 10% salt, right 2% salt, membrane water-only. Water net-flows', [
    'right → left',
    'left → right',
    'neither; salt simple-diffuses',
    'both ways equally from the start',
  ], 0, 'More water on the 2% side. Salt cannot cross, so only water moves toward 10%.'),
  mc('p60', T, 'Why do honors tests trick you with “the cell is hypotonic” vs “the solution is hypotonic”?', [
    'The adjective attaches to whichever side has the LOWER solute',
    'They mean the same thing always',
    'Hypotonic means high solute',
    'They only apply to viruses',
  ], 0, 'Always ask: solute where? Water then goes to the hypertonic side.'),
  mc('p61', T, 'Dynamic equilibrium in an isotonic animal cell means', [
    'water is frozen',
    'equal amounts of water enter and leave',
    'only exocytosis occurs',
    'the Na+/K+ pump stops forever',
  ], 1, 'Molecules don’t stop; nets cancel.'),
  mc('p62', T, 'Which process still needs a membrane protein but NOT ATP?', [
    'simple diffusion of O₂',
    'facilitated diffusion of glucose',
    'the sodium-potassium pump',
    'endocytosis of a bacterium',
  ], 1, 'Protein ≠ energy. Direction of the gradient decides passive vs active.'),
  mc('p63', T, 'A cell 5% salt in 20% salt water (water-permeable only): the water outside is', [
    'hypotonic to the cell',
    'hypertonic to the cell',
    'isotonic',
    'pure water',
  ], 1, '20% > 5%, so outside has more solute. Water leaves; cell shrinks.'),
  mc('p64', T, 'Compare osmosis and facilitated diffusion.', [
    'Both need ATP',
    'Both are passive; osmosis is water (sometimes faster via aquaporins); facilitated is other molecules via channel/carrier',
    'Both move low → high',
    'Neither needs a membrane',
  ], 1, 'Know the 3-way compare: simple vs osmosis vs facilitated.'),
  mc('p65', T, 'If starch cannot cross and water can, a high-starch bag in distilled water will', [
    'lose starch by simple diffusion',
    'gain water by osmosis and swell',
    'use phagocytosis on the beaker',
    'pump starch with ATP automatically',
  ], 1, 'Starch stays; water enters the hypertonic bag.'),
]
