import { mc, multi, type BioPracticeQuestion } from './bioQuiz'

const T = 'membrane' as const

export const MEMBRANE_QUESTIONS: BioPracticeQuestion[] = [
  mc('m1', T, 'The smallest functional unit of organisms is the', [
    'atom',
    'cell',
    'tissue',
    'organ',
  ], 1, 'Notes: the cell is the smallest functional unit of organisms.'),
  mc('m2', T, 'The cell membrane’s primary job is to', [
    'store circular DNA in a nucleoid region',
    'regulate which molecules enter and exit',
    'convert sunlight into glucose sugars',
    'digest food using lysosome enzymes',
  ], 1, 'It controls entry and exit so the cell can keep homeostasis.'),
  mc('m3', T, 'Another correct name for the cell membrane is the', [
    'cellulose cell wall of plants',
    'plasma membrane / phospholipid bilayer',
    'nuclear envelope around DNA',
    'peptidoglycan bacterial capsule',
  ], 1, 'Plasma membrane = phospholipid bilayer. It surrounds ALL cells.'),
  mc('m4', T, 'Which cells have a cell membrane?', [
    'animal cells, but not plant cells',
    'plant cells, but not bacteria',
    'eukaryotes, but not prokaryotes',
    'all cells, prokaryote and eukaryote',
  ], 3, 'Prokaryotes and eukaryotes both have a plasma membrane. Walls are extra, not a replacement.'),
  mc('m5', T, 'A phospholipid bilayer contains how many phospholipid layers?', [
    'one layer of heads only',
    'two layers of phospholipids',
    'three stacked lipid sheets',
    'four fused cholesterol rings',
  ], 1, 'Bi- means two. Heads face water on both sides; tails face inward.'),
  mc('m6', T, 'Unsaturated fatty-acid tails help the membrane stay fluid mainly because', [
    'double-bond kinks keep the tails from packing tightly',
    'the tails contain no carbon atoms at all',
    'the tails freeze the bilayer into a solid sheet',
    'the tails pull all cholesterol out of the membrane',
  ], 0, 'C=C bends let phospholipids move. Chain length also keeps it soft/flexible.'),
  mc('m7', T, 'Fatty-acid chain length affects the plasma membrane by', [
    'forcing bacterial DNA into a circular nucleoid',
    'helping keep the bilayer soft and flexible',
    'building a cellulose wall outside the cell',
    'pumping three sodium ions out per cycle',
  ], 1, 'Notes list two fluidity causes: unsaturated kinks AND chain length.'),
  multi('m8', T, 'Choose ALL that actually make the plasma membrane fluid/flexible.', [
    'Unsaturated tails have kinks and can move',
    'Fatty-acid chain length keeps it flexible',
    'A peptidoglycan wall is the bilayer itself',
    'Cholesterol buffers the membrane’s fluidity',
  ], [0, 1, 3], 'Cell walls sit outside some cells. They are not why the bilayer is fluid.'),
  mc('m9', T, 'Which is NOT one of the six membrane functions in the notes?', [
    'contains cytoplasm and the cell’s parts',
    'carries out photosynthesis of glucose',
    'acts as a barrier between in and out',
    'regulates what comes in and goes out',
  ], 1, 'Photosynthesis is chloroplasts. Membrane jobs: contain cytoplasm, barrier, regulate, cytoskeleton anchor, enzyme binding, junctions.'),
  mc('m10', T, 'The membrane can serve as an attachment site for the', [
    'cellulose fibers of a plant cell wall',
    'cytoskeleton inside the cytoplasm',
    'protein capsid around a virus genome',
    'circular DNA loop in a nucleoid',
  ], 1, 'It anchors the cytoskeleton and also provides enzyme binding sites.'),
  mc('m11', T, 'Interlocking membrane “junctions” let nearby cells', [
    'split by binary fission like bacteria',
    'bind together for cell recognition',
    'drop their plasma membranes entirely',
    'block every form of transport',
  ], 1, 'Junctions hold cells together and help recognition (TRACIE: intercellular joining).'),
  multi('m12', T, 'Choose ALL functions of the cell membrane from this unit.', [
    'Contains cytoplasm and cell parts',
    'Protective barrier for the cell',
    'Regulates entry and exit of materials',
    'Builds the plant cellulose wall from CO₂',
  ], [0, 1, 2], 'The wall is outside the membrane. Also: cytoskeleton anchor, enzyme binding, junctions.'),
  mc('m13', T, 'Homeostasis means a cell is', [
    'bursting in every hypotonic environment',
    'keeping a stable inside despite outside change',
    'blocking every molecule from ever crossing',
    'pushing all solute permanently to the outside',
  ], 1, 'The membrane maintains this by regulating entry and exit of water, nutrients, proteins, etc.'),
  mc('m14', T, 'The membrane maintains homeostasis mainly by', [
    'controlling what enters and what exits',
    'destroying its own phospholipid tails',
    'turning itself into a cellulose wall',
    'stopping osmosis in every situation',
  ], 0, 'Correct amounts of water, nutrients, and proteins depend on selective transport.'),
  mc('m15', T, 'Integral proteins are located', [
    'only on the outer edge, never spanning',
    'across the bilayer, head to opposite head',
    'only in cellulose of plant cell walls',
    'only in the capsid of a virus particle',
  ], 1, 'They span the whole membrane and help move large molecules that cannot simply pass through.'),
  mc('m16', T, 'A channel protein is an integral protein that', [
    'has a pore/tunnel molecules can pass through',
    'changes shape to ferry cargo across',
    'binds hormones such as insulin first',
    'is a 4-ring steroid sitting among tails',
  ], 0, 'Channel = pore. Carrier = shape change. Receptor = signal binding.', 'channel-carrier'),
  mc('m17', T, 'A carrier protein is an integral protein that', [
    'is only a carbohydrate name-tag chain',
    'changes shape to move cargo across',
    'is cholesterol buffering the bilayer',
    'is cellulose stacked in a plant wall',
  ], 1, 'Some carriers span the membrane; others do not. Shape change is the key.', 'channel-carrier'),
  mc('m18', T, 'A receptor protein’s job is to', [
    'digest cellulose in plant cell walls',
    'bind signaling molecules like hormones',
    'form the hydrophobic fatty-acid tails',
    'make up bacterial peptidoglycan walls',
  ], 1, 'Example from the notes: insulin. Shape must match the signal.'),
  mc('m19', T, 'Which pairing of integral protein and job is correct?', [
    'channel — changes shape, never a pore',
    'carrier — open tunnel, never changes shape',
    'receptor — binds hormones / other signals',
    'all three — oligosaccharide name tags',
  ], 2, 'Channel = pore. Carrier = shape change. Receptor = signal binding.'),
  mc('m20', T, 'In TRACIE, T stands for', [
    'turgor pressure in plant vacuoles',
    'transport by channels and pumps',
    'transcription of DNA into mRNA',
    'thylakoid membranes in chloroplasts',
  ], 1, 'TRACIE: Transport, Receptors, Anchorage, Cell recognition, Intercellular joining, Enzyme activity.'),
  mc('m21', T, 'The R in TRACIE is receptors. The notes’ example is', [
    'cellulose in a plant cell wall',
    'insulin, which is a hormone signal',
    'peptidoglycan in a bacterial wall',
    'the protein capsid of a virus',
  ], 1, 'Receptor proteins bind hormones such as insulin.'),
  mc('m22', T, 'Anchorage in TRACIE means membrane proteins', [
    'attach to the cytoskeleton network',
    'carry out binary fission in bacteria',
    'build the nucleoid region of DNA',
    'assemble a viral envelope outside',
  ], 0, 'Anchorage = cytoskeleton attachment.'),
  mc('m23', T, 'Cell recognition in TRACIE matters most for', [
    'detecting gravity in plant stems',
    'immunity (self vs not-self cells)',
    'storing starch inside chloroplasts',
    'splitting cells by binary fission',
  ], 1, 'Oligosaccharides/glycoproteins act like name tags for the immune system.'),
  mc('m24', T, 'Intercellular joining in TRACIE includes', [
    'tight junctions and plasmodesmata',
    'only the sodium-potassium ion pump',
    'only osmosis of water through tails',
    'only RNA genomes inside a capsid',
  ], 0, 'Tight junctions (animals) and plasmodesmata (plants) join cells.'),
  mc('m25', T, 'Enzyme activity of membrane proteins means they', [
    'store the cell’s genetic material',
    'speed up chemical reactions',
    'shut down all homeostasis control',
    'replace the need for a cell wall',
  ], 1, 'Some membrane proteins are enzymes. That is the E in TRACIE.'),
  multi('m26', T, 'Choose ALL TRACIE jobs of membrane proteins.', [
    'Transport: channels and pumps',
    'Receptors: hormones such as insulin',
    'Anchorage: cytoskeleton attachment',
    'Translation of mRNA only in a nucleus',
  ], [0, 1, 2], 'Also cell recognition (immunity), intercellular joining, and enzyme activity.'),
  mc('m27', T, 'Peripheral proteins are found', [
    'spanning the bilayer like a full tunnel',
    'on the interior or exterior membrane edge',
    'only inside a prokaryotic nucleoid',
    'as 4-ring steroids among the tails',
  ], 1, 'Edges, not all the way through. Jobs include cell recognition and hormone recognition.'),
  mc('m28', T, 'A main job of peripheral proteins is', [
    'building cellulose plant cell walls',
    'cell and hormone recognition',
    'splitting cells by binary fission',
    'forming a virus’s protein capsid',
  ], 1, '“I know you, fellow cell” vs “you could hurt me,” plus reading hormone messages.'),
  mc('m29', T, 'Cholesterol in animal membranes is a', [
    'channel protein with an open pore',
    'steroid that buffers how fluid the bilayer is',
    'oligosaccharide used as a name tag',
    'carrier protein that changes shape',
  ], 1, '4 fused C rings. It limits phospholipid movement and acts as a temperature buffer.', 'steroid'),
  mc('m30', T, 'Cholesterol stabilizes the membrane by', [
    'limiting how freely phospholipids move',
    'digesting glucose as it enters',
    'turning into peptidoglycan walls',
    'removing every unsaturated tail',
  ], 0, 'Too fluid or too rigid both wreck function. Cholesterol is a temperature buffer.'),
  mc('m31', T, 'If cholesterol were missing, the bilayer would most likely', [
    'get too fluid when hot and too stiff when cold',
    'turn into a cellulose cell wall immediately',
    'change osmosis into active transport',
    'convert all of its DNA into RNA',
  ], 0, 'That temperature-buffer job is how cholesterol helps homeostasis.'),
  mc('m32', T, 'Oligosaccharides on the membrane are', [
    'full-length DNA chromosomes',
    'short sugar chains used as name tags',
    'three sodium ions leaving the cell',
    'the peptidoglycan of a bacterial wall',
  ], 1, 'Oligo- = a few monosaccharides. They allow cell-to-cell recognition.'),
  mc('m33', T, 'A glycolipid is', [
    'a carbohydrate attached to a membrane lipid',
    'a protein that pumps sodium ions out',
    'a 4-ring steroid with no sugar attached',
    'a circular plasmid in the nucleoid',
  ], 0, 'Glyco = sugar. Lipid = fat. Sugar stuck on a bilayer lipid.'),
  mc('m34', T, 'A glycoprotein is', [
    'a carbohydrate attached to a membrane protein',
    'a DNA strand stored in the nucleoid',
    'cholesterol sitting among the lipid tails',
    'cellulose stacked in a plant cell wall',
  ], 0, 'Can be integral or peripheral. Adds stability and immune recognition.'),
  mc('m35', T, 'Why do oligosaccharides / glycoproteins matter for immunity?', [
    'They tag cells so self can be told from invader',
    'They pump three Na⁺ ions out per cycle',
    'They act as contractile vacuoles in animals',
    'They function as chloroplasts in plants',
  ], 0, 'Notes call them tiny name tags. That is cell recognition in TRACIE.'),
  multi('m36', T, 'Choose ALL macromolecules actually in the cell membrane.', [
    'Lipids, including phospholipids and cholesterol',
    'Proteins, both integral and peripheral',
    'Carbohydrates as oligosaccharide chains',
    'Peptidoglycan making up the bilayer itself',
  ], [0, 1, 2], 'Lipids are most abundant. Peptidoglycan is a bacterial cell-wall material, not the bilayer.'),
  mc('m37', T, 'In “fluid mosaic,” fluid means', [
    'components can move, so substances can pass',
    'the cell is constantly bursting by cytolysis',
    'DNA is continuously leaking out of the cell',
    'proteins are absent from the membrane',
  ], 0, 'Fluidity comes from phospholipid dual nature plus cholesterol content.', 'fluid-mosaic'),
  mc('m38', T, 'In “fluid mosaic,” mosaic means', [
    'the membrane is made of water only',
    'lipids, proteins, and carbs are mixed',
    'the membrane is a pure cholesterol crystal',
    'living cells do not have membranes',
  ], 1, 'Lipids are the most abundant piece of that mixture.', 'fluid-mosaic'),
  mc('m39', T, 'Amphipathic means a molecule', [
    'has both hydrophobic and hydrophilic parts',
    'is fully charged like Na⁺ or Cl⁻',
    'always requires ATP to move anywhere',
    'is only found in a virus capsid',
  ], 0, 'Phospholipids are amphipathic. That dual nature makes the membrane selective.', 'bilayer'),
  mc('m40', T, 'Phospholipid heads are ______ and tails are ______.', [
    'hydrophobic / nonpolar; hydrophilic / polar',
    'hydrophilic / polar; hydrophobic / nonpolar',
    'made of DNA; made of RNA nucleotides',
    'cellulose in plants; chitin in fungi',
  ], 1, 'Heads face water (cytoplasm and outside). Tails hide from water in the middle.', 'bilayer'),
  mc('m41', T, 'Heads face out and tails face in because', [
    'heads are polar and contact water; tails avoid water',
    'heads hate water and tails are attracted to it',
    'cholesterol physically flips every head inward',
    'DNA charge pulls the hydrophobic tails outward',
  ], 0, 'Water is both inside (cytoplasm) and outside. Polar heads interact with it; nonpolar tails cluster away.', 'bilayer'),
  mc('m42', T, 'Selective permeability means the membrane', [
    'lets every solute cross at the same rate',
    'lets only certain substances through',
    'lets only proteins through, never water',
    'blocks oxygen from ever entering cells',
  ], 1, 'Amphipathic structure makes it selective, which is how it maintains homeostasis.'),
  mc('m43', T, 'Which set crosses the bilayer most easily (no protein)?', [
    'Na⁺ and K⁺, because they are tiny ions',
    'O₂, CO₂, and other small uncharged gases',
    'glucose, with no channel or carrier help',
    'folded proteins, because they are enzymes',
  ], 1, 'Also: small uncharged polar H₂O, lipid-soluble molecules, and large hydrophobic molecules. Ions, glucose, and proteins do not pass easily.', 'bilayer'),
  mc('m44', T, 'Which set does NOT pass easily through the bilayer?', [
    'O₂ and CO₂, which are small gases',
    'ions, glucose, and large proteins',
    'water, a small uncharged polar molecule',
    'lipid-soluble hydrophobic molecules',
  ], 1, 'Charge, polarity, and size block free diffusion. Glucose is hydrophilic and larger than water.'),
  mc('m45', T, 'Ions cannot easily cross the bilayer because they', [
    'are too large to fit between any heads',
    'are charged, so the hydrophobic core repels them',
    'are gases that must use aquaporins',
    'are chemically identical to cholesterol',
  ], 1, 'The nonpolar tail region rejects +/− charges. Ions need protein help.'),
  mc('m46', T, 'Glucose needs a protein but O₂ does not, because', [
    'glucose is large and hydrophilic; O₂ is a small gas',
    'glucose is a gas; O₂ is a folded protein',
    'glucose is hydrophobic; O₂ is a full ion',
    'both molecules always require ATP to move',
  ], 0, 'Size + polarity: glucose uses facilitated diffusion. O₂ uses simple diffusion.'),
  mc('m47', T, 'Water can leak through slowly (faster via aquaporins) because it is', [
    'an ion carrying a full positive charge',
    'a small uncharged polar molecule',
    'larger than most cellular proteins',
    'chemically the same molecule as starch',
  ], 1, 'H₂O is on the “passes easily” list, but aquaporins are channels that speed it.'),
  mc('m48', T, 'Large hydrophobic molecules generally', [
    'cannot get anywhere near a membrane',
    'cross more easily than ions (like-dissolves-like)',
    'move only through plant plasmodesmata',
    'are identical to peptidoglycan walls',
  ], 1, 'They mix with the nonpolar tail region. Charged ions do not.'),
  mc('m49', T, 'In this bilayer diagram, the circles facing water are', [
    'hydrophobic fatty-acid tails',
    'hydrophilic phosphate heads',
    'circular DNA in a nucleoid',
    'protein capsids of a virus',
  ], 1, 'Polar heads contact water. Nonpolar tails hide in the middle.', 'bilayer'),
  mc('m50', T, 'The yellow circle among the tails is most likely', [
    'the open pore of a channel protein',
    'cholesterol buffering membrane fluidity',
    'a plasmid loop of circular DNA',
    'a starch grain stored for energy',
  ], 1, 'Cholesterol (steroid) sits among phospholipids and limits their movement.', 'fluid-mosaic'),
  mc('m51', T, 'Straight saturated tails plus no cholesterol would make the membrane', [
    'too rigid, especially as temperature drops',
    'a gas that cannot hold cytoplasm',
    'a chitin wall like a fungal cell',
    'unable to form hydrophilic heads',
  ], 0, 'Unsaturated kinks AND cholesterol keep it fluid enough to function.'),
  mc('m52', T, 'A membrane phospholipid diagram should show', [
    'three fatty-acid tails and no phosphate head',
    'one hydrophilic head plus TWO hydrophobic tails',
    'four fused rings and no fatty-acid tails',
    'phosphate, sugar, and a nitrogenous base',
  ], 1, 'Phospholipid = 2 tails. Triglyceride = 3 tails. Steroid = 4 fused rings.', 'phospholipid'),
  mc('m53', T, 'The most abundant macromolecule type in the membrane is', [
    'nucleic acids storing the genome',
    'lipids making up the bilayer',
    'cellulose of a plant cell wall',
    'peptidoglycan of a bacterial wall',
  ], 1, 'The mosaic also includes proteins and carbohydrates, but lipids dominate.'),
  multi('m54', T, 'Choose ALL true of selective permeability and homeostasis.', [
    'Only certain substances cross easily',
    'Size and polarity help decide what crosses',
    'Regulating traffic keeps insides stable',
    'Every ion simple-diffuses through the tails',
  ], [0, 1, 2], 'Ions need proteins. That control is how the membrane maintains homeostasis.'),
  mc('m55', T, 'Enzyme binding sites on the membrane help because', [
    'reactions can be organized at the surface',
    'the enzymes are converted into DNA',
    'the cell no longer needs a bilayer',
    'osmosis is changed into active transport',
  ], 0, 'One of the six listed membrane functions.'),
  mc('m56', T, 'Which molecule is amphipathic?', [
    'Na⁺, a fully charged sodium ion with no tails',
    'a phospholipid, polar head plus nonpolar tails',
    'O₂, a small uncharged gas with no head',
    'cellulose, a plant-wall polysaccharide',
  ], 1, 'Amphipathic = both hydrophilic and hydrophobic parts.', 'phospholipid')
  mc('m57', T, 'Integral vs peripheral — which is accurate?', [
    'integral on edges only; peripheral spans fully',
    'integral spans; peripheral sits on a surface',
    'both are oligosaccharide name-tag chains',
    'neither type can bind any molecule',
  ], 1, 'Know location AND function for both. Integral includes channel, carrier, and receptor.'),
  mc('m58', T, 'Which protein would bind insulin?', [
    'a receptor protein in the membrane',
    'cellulose fibers in a plant wall',
    'a triglyceride used for energy storage',
    'peptidoglycan in a bacterial wall',
  ], 0, 'Receptors bind signaling molecules. Insulin is the notes’ hormone example.'),
  mc('m59', T, 'Phospholipids make the membrane selective because', [
    'the hydrophobic core blocks many polar/charged solutes',
    'they dissolve the cell wall into free sugars',
    'they force every protein out of the bilayer',
    'they produce ATP directly from sunlight',
  ], 0, 'Heads love water; tails hate it. That oily middle is a chemical filter.'),
  mc('m60', T, 'Glycolipids and glycoproteins both', [
    'pump three Na⁺ ions out per ATP',
    'help recognition and add some stability',
    'act as contractile vacuoles in animals',
    'occur only in archaeal nucleoid DNA',
  ], 1, 'Carb chains = name tags + stability. Immune system uses them.'),
  mc('m61', T, 'Four fused rings in the membrane should be identified as', [
    'glucose, a carbohydrate monomer',
    'cholesterol, a steroid lipid',
    'the pore of a channel protein',
    'peptidoglycan in a bacterial wall',
  ], 1, 'Cholesterol = steroid = 4 fused C rings. No glycerol, no fatty-acid tails.', 'steroid'),
  mc('m62', T, 'Which statement is the precise one for this unit?', [
    'Only animal cells have a plasma membrane',
    'ALL cells have a plasma membrane / bilayer',
    'Prokaryotes have walls but no membrane',
    'Plant cells replace the membrane with cellulose',
  ], 1, 'Plants have membrane AND wall. Bacteria have membrane AND peptidoglycan wall.'),
  multi('m63', T, 'Choose ALL that pass easily with no protein required.', [
    'O₂',
    'CO₂',
    'Na⁺',
    'a large protein enzyme',
  ], [0, 1], 'Gases yes. Ions and big proteins no. Water can sneak through but is slower than via aquaporins.'),
  multi('m64', T, 'Choose ALL that do NOT pass easily.', [
    'Cl⁻',
    'glucose',
    'a polypeptide',
    'O₂',
  ], [0, 1, 2], 'Charged, large polar, and huge molecules need help or bulk transport.'),
  mc('m65', T, 'The interior of the bilayer (where tails meet) is', [
    'hydrophilic and packed with water',
    'hydrophobic / nonpolar',
    'a nucleolus making ribosomes',
    'peptidoglycan from a bacterial wall',
  ], 1, 'That oily core is why charged and large polar molecules struggle.', 'bilayer'),
]
