export type BioVisualId =
  | 'life-list'
  | 'cells'
  | 'energy'
  | 'growth'
  | 'homeostasis'
  | 'stimulus'
  | 'evolution'
  | 'virus'
  | 'graph'
  | 'graph-types'
  | 'data-types'
  | 'observe'
  | 'variables'
  | 'experiment'
  | 'water'
  | 'polar'
  | 'hydro'
  | 'capillary'
  | 'surface'
  | 'specific-heat'
  | 'ice'
  | 'solvent'
  | 'sweat'
  | 'ph'
  | 'organic'
  | 'carbon'
  | 'mono-poly'
  | 'anabolic'
  | 'catabolic'
  | 'dehydration'
  | 'hydrolysis'
  | 'carbs'
  | 'poly-carbs'
  | 'lipids'
  | 'fatty-acids'
  | 'phospholipid'
  | 'protein'
  | 'protein-levels'
  | 'nucleic'

export interface BioTeachStep {
  type: 'teach'
  id: string
  chapter: string
  chapterNum: number
  title: string
  plain: string
  points: string[]
  visual: BioVisualId
  remember?: string
}

export interface BioQuestionStep {
  type: 'question'
  id: string
  chapter: string
  chapterNum: number
  prompt: string
  options: string[]
  correctIndex: number
  explain: string
}

export type BioLessonStep = BioTeachStep | BioQuestionStep

export const BIO_UNIT_1_LESSON: BioLessonStep[] = [
  {
    type: 'teach',
    id: 'life-intro',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: 'The big rule',
    plain: 'Living things have to pass every test on the list — not most of them.',
    points: [
      'There are 7 characteristics of life.',
      'To count as living, something must show ALL 7. Not 5. Not 6. All of them.',
      'We will learn each one with a simple meaning, then check if you got it.',
    ],
    visual: 'life-list',
    remember: 'If even one trait is missing, it is not classified as living.',
  },
  {
    type: 'teach',
    id: 'cells',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '1. Cellular organization',
    plain: 'Every living thing is made of cells — the tiny rooms that run life.',
    points: [
      'Unicellular = one cell (bacteria, amoeba). That one cell can still be a whole organism.',
      'Multicellular = many cells (you, plants, dogs).',
      'Cells can live on their own or in colonies (groups).',
      'All cells share the same basic structure.',
    ],
    visual: 'cells',
  },
  {
    type: 'question',
    id: 'q-cells',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    prompt: 'A bacterium is one cell that can live on its own. What is it?',
    options: ['Multicellular', 'Unicellular', 'Not made of cells', 'A virus'],
    correctIndex: 1,
    explain: 'Uni means one. A bacterium is a unicellular organism: one cell that can live by itself.',
  },
  {
    type: 'teach',
    id: 'energy',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '2. Energy utilization',
    plain: 'Living things need energy, and metabolism is the word for ALL of those chemical reactions.',
    points: [
      'Metabolism = every chemical reaction in an organism — getting energy and using it.',
      'Autotroph: makes its own food (plants using sunlight). Auto = self.',
      'Heterotroph: must eat other organisms (animals, fungi). Hetero = other.',
      'Energy is also used to build new tissues and destroy pathogens (invaders).',
    ],
    visual: 'energy',
    remember: 'Auto = I make it. Hetero = I have to eat it.',
  },
  {
    type: 'question',
    id: 'q-energy',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    prompt: 'A mushroom cannot make its own food, so it eats dead stuff. What is it?',
    options: ['Autotroph', 'Heterotroph', 'Virus', 'Inorganic'],
    correctIndex: 1,
    explain: 'Heterotrophs must consume other organisms. Mushrooms do not photosynthesize, so they are heterotrophs.',
  },
  {
    type: 'teach',
    id: 'growth',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '3. Growth and development',
    plain: 'Growth is getting bigger. Development is changing as you go through life.',
    points: [
      'Growth = more living material and new structures (you get taller, a tree adds wood).',
      'Development = the changes during a lifetime (a tadpole becoming a frog, a baby becoming an adult).',
      'All living organisms grow.',
    ],
    visual: 'growth',
  },
  {
    type: 'question',
    id: 'q-growth',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    prompt: 'A caterpillar turning into a butterfly is mainly an example of…',
    options: ['Growth only', 'Development', 'Homeostasis', 'A graphing skill'],
    correctIndex: 1,
    explain: 'That is a life-cycle change, so it is development. Growth would be the caterpillar just getting larger.',
  },
  {
    type: 'teach',
    id: 'repro',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '4. Reproduction and heredity',
    plain: 'Living things pass DNA to offspring so the species can keep going.',
    points: [
      'The goal of reproduction is to pass genetic material to offspring.',
      'It is essential for the species, not for one individual (you can live without having kids).',
      'Sexual reproduction = 2 parents. Asexual = 1 parent.',
      'Genes (in DNA) decide the offspring’s characteristics.',
    ],
    visual: 'life-list',
  },
  {
    type: 'teach',
    id: 'homeostasis',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '5. Internal regulation (homeostasis)',
    plain: 'Homeostasis means keeping your insides stable even when the outside world changes.',
    points: [
      'Inside cells: water/salt levels, waste, and more stay in a safe range.',
      'Inside organisms: body temperature, blood sugar, and similar things.',
      'Organisms have an “optimal range” (best temperature, pH, water level).',
      'Homeostasis is the system that keeps you in that range.',
    ],
    visual: 'homeostasis',
    remember: 'Think of a thermostat: if you get too hot, you sweat. Too cold, you shiver.',
  },
  {
    type: 'question',
    id: 'q-homeo',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    prompt: 'You sweat on a hot day so your body temperature stays around 98.6°F. This is…',
    options: ['Evolution', 'A stimulus only', 'Homeostasis', 'Reproduction'],
    correctIndex: 2,
    explain: 'Sweating helps keep internal temperature stable. That is homeostasis.',
  },
  {
    type: 'teach',
    id: 'stimulus',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '6. Response to the environment',
    plain: 'Something happens (stimulus), and the organism does something back (response).',
    points: [
      'Stimulus = a factor that makes an organism need to adjust (light, heat, a predator).',
      'Response = how the organism reacts (plants lean toward light, you pull your hand off a stove).',
      'Living things respond so they can survive.',
    ],
    visual: 'stimulus',
  },
  {
    type: 'question',
    id: 'q-stimulus',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    prompt: 'A loud noise is the _______. Covering your ears is the _______.',
    options: [
      'response ; stimulus',
      'stimulus ; response',
      'adaptation ; evolution',
      'hypothesis ; law',
    ],
    correctIndex: 1,
    explain: 'The noise is the stimulus (the thing that happens). Covering your ears is the response (what you do).',
  },
  {
    type: 'teach',
    id: 'evolution',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: '7. Evolution and adaptation',
    plain: 'Populations change over many generations. The traits that help survival stick around.',
    points: [
      'Evolution = changes in a population’s characteristics over multiple generations.',
      'Adaptation = a trait that helps an organism fit its environment.',
      'The best-suited organisms survive and reproduce (so their genes become more common).',
      'One giraffe stretching its neck is not evolution. A population changing over time is.',
    ],
    visual: 'evolution',
  },
  {
    type: 'teach',
    id: 'virus',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    title: 'Are viruses alive?',
    plain: 'Viruses fail the “ALL 7” test, so they are classified as nonliving.',
    points: [
      'Viruses have genetic material and can evolve.',
      'They are not made of cells.',
      'They cannot reproduce or use energy on their own — they hijack a host cell.',
      'Missing even one characteristic means: not living.',
    ],
    visual: 'virus',
    remember: 'Virus = genetic hitchhiker. Needs a host. Not a cell. Not alive.',
  },
  {
    type: 'question',
    id: 'q-virus',
    chapter: 'Characteristics of Life',
    chapterNum: 1,
    prompt: 'Why are viruses usually called nonliving?',
    options: [
      'They have DNA or RNA',
      'They can evolve',
      'They are not made of cells and cannot reproduce without a host',
      'They are bigger than bacteria',
    ],
    correctIndex: 2,
    explain: 'Having genes is not enough. They miss cellular organization and independent metabolism/reproduction, so they fail the ALL 7 rule.',
  },
  {
    type: 'teach',
    id: 'graph-intro',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'How to read a graph',
    plain: 'X is what you change. Y is what you measure.',
    points: [
      'X-axis (horizontal) = independent variable. “I changed this” — time, amount of medicine, etc.',
      'Y-axis (vertical) = dependent variable. “I measured this” — height, gas produced, etc.',
      'Every axis needs a title, labels, and units.',
      'Scale matters. A bad scale can hide the real pattern or fake a dramatic one.',
    ],
    visual: 'graph',
    remember: 'DRY MIX: Dependent / Responding on Y. Manipulated / Independent on X.',
  },
  {
    type: 'question',
    id: 'q-axis',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: 'In an experiment, time is what you change and plant height is what you measure. Where does time go?',
    options: ['Y-axis', 'X-axis', 'The title only', 'The legend only'],
    correctIndex: 1,
    explain: 'Time is the independent variable (you set the times), so it goes on the X-axis. Height is dependent, so it goes on Y.',
  },
  {
    type: 'teach',
    id: 'graph-types',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Pick the right graph',
    plain: 'Line = change over time. Bar = compare groups. Pie = parts of a whole.',
    points: [
      'Line graph: relationship between two variables. ALWAYS use a line graph for change over time. Most common in science.',
      'Bar graph: compare a measured amount between categories (plants vs animals, brand A vs brand B).',
      'Pie graph: percentages / how something breaks into parts.',
      'If the scale unit is too big, the graph looks squished. Too small, it runs off the page. Multiples of 1, 2, 5, or 10 are easiest.',
    ],
    visual: 'graph-types',
  },
  {
    type: 'question',
    id: 'q-graph-type',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: 'You track a student’s heart rate every minute during a workout. Which graph?',
    options: ['Pie graph', 'Bar graph', 'Line graph', 'No graph — just a table'],
    correctIndex: 2,
    explain: 'Change over time = line graph. Always.',
  },
  {
    type: 'teach',
    id: 'science-method',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Science is a process',
    plain: 'The scientific method is a repeatable way to ask questions and test ideas.',
    points: [
      'Science is built by experiments. New findings keep updating what we know.',
      'Qualitative data = qualities (green, sour, large). No numbers required.',
      'Quantitative data = numbers (4 feet, 7.2 grams, 100 mL).',
      'A good observation is objective (the ground is wet). An inference is a guess based on it (it rained).',
    ],
    visual: 'data-types',
  },
  {
    type: 'question',
    id: 'q-data',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: '“The leaf is 8 cm long and pale yellow.” Which part is quantitative?',
    options: ['Pale yellow', '8 cm long', 'The word leaf', 'None — both are qualitative'],
    correctIndex: 1,
    explain: '8 cm is a number measurement = quantitative. Pale yellow is a quality = qualitative.',
  },
  {
    type: 'teach',
    id: 'observe',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Observation vs inference',
    plain: 'See it with your senses first. Then guess why.',
    points: [
      'Observation: something you can see, smell, taste, touch, or hear. Not an opinion.',
      'Example observation: the ground is wet.',
      'Inference: a guess about why, based on observations.',
      'One observation can support many inferences (rain, sprinkler, spilled water).',
    ],
    visual: 'observe',
  },
  {
    type: 'question',
    id: 'q-obs',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: 'Which sentence is an observation, not an inference?',
    options: [
      'The dog is hungry.',
      'It must have rained last night.',
      'The sidewalk is wet.',
      'Someone probably spilled a drink.',
    ],
    correctIndex: 2,
    explain: 'Wet sidewalk is something you can see. The others are guesses about why.',
  },
  {
    type: 'teach',
    id: 'law-theory',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Law vs theory',
    plain: 'A law says WHAT happens. A theory explains WHY. A theory never “graduates” into a law.',
    points: [
      'Law: a broad principle that describes a pattern in nature (HOW it behaves). Often treated as facts. Example: Law of Conservation of Mass.',
      'Theory: an explanation of an observed phenomenon. It organizes lots of research to explain WHY. Example: evolutionary theory.',
      'Theories do not become laws. They are different jobs.',
    ],
    visual: 'observe',
  },
  {
    type: 'question',
    id: 'q-law',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: '“Mass is not created or destroyed in a chemical reaction” is best called a…',
    options: ['Hypothesis', 'Theory', 'Law', 'Inference'],
    correctIndex: 2,
    explain: 'That describes a pattern in nature (how mass behaves). That is a law, not a why-explanation.',
  },
  {
    type: 'teach',
    id: 'hypothesis',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Hypothesis and variables',
    plain: 'A hypothesis is a testable “if this, then that” prediction — not a random guess.',
    points: [
      'Format: If (independent variable), then (dependent variable).',
      'Independent variable (IV) = what YOU deliberately change. Goes on the X-axis. Should be the ONLY difference between groups.',
      'Dependent variable (DV) = what you measure. Goes on the Y-axis.',
      'Example: If the drink before a race changes, then running speed changes. IV = drink. DV = race time.',
    ],
    visual: 'variables',
  },
  {
    type: 'question',
    id: 'q-iv',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: 'You test whether the drink before a race affects how quickly someone runs. What is the independent variable?',
    options: ['Running speed', 'The drink', 'Shoe brand, if it also changes', 'The hypothesis'],
    correctIndex: 1,
    explain: 'You are choosing/changing the drink. Speed is what you measure (DV). Shoes should stay constant.',
  },
  {
    type: 'teach',
    id: 'groups',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Control, experiment, constants',
    plain: 'The control group is the “normal” comparison. Constants keep everything else fair.',
    points: [
      'Experimental group: gets the treatment / is exposed to the IV. You can have more than one.',
      'Control group: no treatment. Used for comparison. A difference makes the IV more likely to be the cause (it still does not “prove” it).',
      'Constants: everything you keep the same (age, breakfast, shoes, puzzle type…).',
      'Repeat trials so results are not just luck, errors get spotted, and data is precise.',
    ],
    visual: 'experiment',
  },
  {
    type: 'teach',
    id: 'bears',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    title: 'Practice experiment: caffeinated bears',
    plain: 'Same puzzle, different caffeine amounts. Measure how long the puzzle takes.',
    points: [
      'Group A: 0 mg caffeine. Groups B/C/D: 100, 200, 400 mg.',
      'Control group = A (no treatment).',
      'Experimental groups = B, C, D.',
      'IV = amount of caffeine. DV = time to solve the puzzle.',
      'Constants = same kind of bear, same puzzle, same number of bears, same way of giving caffeine.',
    ],
    visual: 'experiment',
    remember: 'Control = 0 treatment. IV = what you changed. DV = what you timed.',
  },
  {
    type: 'question',
    id: 'q-bears',
    chapter: 'Graphing & Experiments',
    chapterNum: 2,
    prompt: 'In the bear-caffeine experiment, what is the dependent variable?',
    options: [
      'Amount of caffeine',
      'Type of bear',
      'Time to solve the puzzle',
      'Group A',
    ],
    correctIndex: 2,
    explain: 'They measured puzzle time. Caffeine amount is the IV. Bear type is a constant. Group A is the control.',
  },
  {
    type: 'teach',
    id: 'water-intro',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Water is the molecule of life',
    plain: 'Inside one water molecule, atoms share electrons. Between water molecules, they cling with hydrogen bonds.',
    points: [
      'A water molecule is H₂O: two hydrogens, one oxygen.',
      'Covalent bonds (sharing electron pairs) hold H and O together INSIDE one molecule.',
      'Hydrogen bonds attract SEPARATE water molecules to each other.',
      'Hydrogen bonds are weaker than covalent or ionic bonds, but they are strong enough to give water its special properties.',
    ],
    visual: 'water',
    remember: 'Covalent = within one H₂O. Hydrogen bond = between two H₂Os.',
  },
  {
    type: 'question',
    id: 'q-bonds',
    chapter: 'Properties of Water',
    chapterNum: 3,
    prompt: 'What holds two different water molecules together?',
    options: ['Ionic bonds', 'Covalent bonds', 'Hydrogen bonds', 'Peptide bonds'],
    correctIndex: 2,
    explain: 'Covalent bonds are inside one molecule. Hydrogen bonds form between molecules.',
  },
  {
    type: 'teach',
    id: 'polar',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Water is polar',
    plain: 'Electrons are not shared fairly, so water has a slightly negative oxygen side and slightly positive hydrogen side.',
    points: [
      'Oxygen pulls electrons harder than hydrogen.',
      'Oxygen side = partially negative (δ−). Hydrogen side = partially positive (δ+).',
      'That uneven charge is why water can form hydrogen bonds and dissolve lots of stuff.',
      'Hydrophilic (“water-loving”) = polar or ions, dissolve in water (salt, sugar).',
      'Hydrophobic (“water-fearing”) = nonpolar, do not dissolve (oil).',
    ],
    visual: 'polar',
  },
  {
    type: 'question',
    id: 'q-hydro',
    chapter: 'Properties of Water',
    chapterNum: 3,
    prompt: 'Oil sits on top of water and does not mix. Oil is…',
    options: ['Hydrophilic and polar', 'Hydrophobic and nonpolar', 'An acid', 'A solute that water always dissolves'],
    correctIndex: 1,
    explain: 'Oil is nonpolar, so it does not mix with polar water. That is hydrophobic = water-fearing.',
  },
  {
    type: 'teach',
    id: 'capillary',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Property 1: Capillary action',
    plain: 'Water can climb thin tubes because it sticks to itself AND to other surfaces.',
    points: [
      'Cohesion = water sticks to water (co- = together). That makes droplets and high surface tension.',
      'Adhesion = water sticks to something else (glass, plant vessels). That makes a meniscus in a graduated cylinder.',
      'Capillary action = climbing upward from cohesion + adhesion. Plants drink this way. Straws do too.',
      'Read a meniscus at the BOTTOM of the curve.',
    ],
    visual: 'capillary',
  },
  {
    type: 'question',
    id: 'q-adhesion',
    chapter: 'Properties of Water',
    chapterNum: 3,
    prompt: 'Water climbing a paper towel or a plant stem is mostly…',
    options: ['pH', 'Capillary action', 'Freezing', 'A chemical reaction called hydrolysis'],
    correctIndex: 1,
    explain: 'Climbing thin spaces uses cohesion + adhesion together, which is capillary action.',
  },
  {
    type: 'teach',
    id: 'surface',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Property 2: Surface tension',
    plain: 'The top of water acts like a tight skin because water molecules cling to each other.',
    points: [
      'Surface tension = how hard it is to stretch or break the surface.',
      'Water’s surface tension is high because of cohesion from hydrogen bonds.',
      'That is why some bugs can walk on water.',
    ],
    visual: 'surface',
  },
  {
    type: 'teach',
    id: 'specific-heat',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Property 3: High specific heat',
    plain: 'Water is stubborn about changing temperature.',
    points: [
      'Specific heat = energy needed to raise 1 gram of a substance by 1°C.',
      'Water’s specific heat is high because of hydrogen bonds.',
      'A pond stays more stable from day to night than air or land.',
      'That stability is a big reason life can live in water.',
    ],
    visual: 'specific-heat',
  },
  {
    type: 'teach',
    id: 'ice',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Property 4: Ice floats',
    plain: 'Solid water is less dense than liquid water, so ice sits on top instead of sinking.',
    points: [
      'Most substances get denser when they freeze. Water expands.',
      'Ice floating insulates the water below, so lakes do not freeze solid.',
      'Fish and other life can survive under the ice.',
    ],
    visual: 'ice',
  },
  {
    type: 'question',
    id: 'q-ice',
    chapter: 'Properties of Water',
    chapterNum: 3,
    prompt: 'Why does ice floating matter for living things in a lake?',
    options: [
      'Ice is hydrophobic so fish can breathe it',
      'The ice layer insulates water below so the lake does not freeze solid',
      'Ice raises the pH to 14',
      'Ice is a protein',
    ],
    correctIndex: 1,
    explain: 'Because ice is less dense, it forms a lid on top. Life can keep going underneath.',
  },
  {
    type: 'teach',
    id: 'solvent',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Property 5: Universal solvent',
    plain: 'Water dissolves many things because of its charges.',
    points: [
      'Solution = mixture of substances in a liquid (sugar water).',
      'Solvent = the dissolver (water). Solute = the thing dissolved (sugar).',
      'Water is called the universal solvent because polarity lets it dissolve many ions and polar molecules.',
    ],
    visual: 'solvent',
  },
  {
    type: 'teach',
    id: 'vapor',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'Property 6: High heat of vaporization',
    plain: 'It takes a lot of energy to turn water into gas — that is why sweat cools you.',
    points: [
      'Heat of vaporization = energy to go from liquid to gas.',
      'Evaporative cooling: the leftover liquid is cooler after the fastest molecules leave.',
      'Sweat steals heat from your skin to evaporate, so you cool down.',
      'This also helps keep water on Earth (and in your body) as a liquid.',
    ],
    visual: 'sweat',
  },
  {
    type: 'teach',
    id: 'ph',
    chapter: 'Properties of Water',
    chapterNum: 3,
    title: 'pH: acids and bases',
    plain: 'pH is a ranking of how many H⁺ ions are in a solution.',
    points: [
      'Water can split: H₂O ⇌ H⁺ + OH⁻.',
      'Pure water has equal H⁺ and OH⁻ (neutral, pH 7).',
      'Acid: pH < 7, extra H⁺, sour/tart (citrus, stomach acid).',
      'Base (alkaline): pH > 7, extra OH⁻, bitter (soap, bleach).',
      'Most cells like pH near 7. Extreme pH can denature (unfold) proteins.',
      'The scale is usually 0–14, but values outside that are possible.',
    ],
    visual: 'ph',
  },
  {
    type: 'question',
    id: 'q-ph',
    chapter: 'Properties of Water',
    chapterNum: 3,
    prompt: 'Lemon juice tastes sour and has lots of H⁺ ions. It is…',
    options: ['A base with pH 10', 'Neutral water', 'An acid with pH below 7', 'A lipid'],
    correctIndex: 2,
    explain: 'High H⁺ and sour taste = acid. Acids are below 7 on the pH scale.',
  },
  {
    type: 'teach',
    id: 'organic',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Organic compounds',
    plain: 'Organic in biology means carbon-based molecules that build living things — not “organic grocery.”',
    points: [
      'Organic compounds have carbon-carbon and carbon-hydrogen bonds, usually with lots of carbons.',
      'They are often huge and can include C, H, O, N, P, and sometimes S (CHONPS).',
      'Macromolecules are the large organic molecules of life: carbs, lipids, proteins, nucleic acids.',
      'They run your body, store instructions, and supply energy.',
      'Carbon skeletons in diagrams are zig-zags: every end and bend is a carbon. You do not have to draw them, but you should recognize them.',
    ],
    visual: 'organic',
  },
  {
    type: 'teach',
    id: 'carbon',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Why carbon is the building superstar',
    plain: 'Carbon has 4 open bonding spots, so it can make chains, branches, and rings.',
    points: [
      'Carbon has 4 valence electrons, so it can form 4 covalent bonds.',
      'That is why molecules can be so many shapes and sizes.',
      'Common shapes: straight chain, branched chain, ring.',
      'Inorganic compounds lack those carbon-carbon / carbon-hydrogen organic setups.',
    ],
    visual: 'carbon',
  },
  {
    type: 'teach',
    id: 'mono-poly',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Monomers and polymers',
    plain: 'Monomers are LEGO bricks. Polymers are the castle you build.',
    points: [
      'Monomer = small building block.',
      'Polymer = many monomers bonded together.',
      'Most macromolecules are polymers made of monomers. Lipids are the awkward exception (no true repeating monomer).',
    ],
    visual: 'mono-poly',
  },
  {
    type: 'teach',
    id: 'ana-cata',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Build up vs break down',
    plain: 'Anabolic builds (uses energy). Catabolic breaks (releases energy).',
    points: [
      'Anabolic: A + B → AB. Uses energy to make bigger molecules.',
      'Catabolic: AB → A + B. Breaks molecules and releases energy.',
      'Dehydration synthesis is anabolic: join monomers, water leaves as waste. An H comes off one, an OH off the other.',
      'Hydrolysis is catabolic: water is added to cut a polymer. Hydro = water, lysis = split.',
    ],
    visual: 'dehydration',
    remember: 'Dehydration = take water out to build. Hydrolysis = add water to break. Digestion is hydrolysis.',
  },
  {
    type: 'question',
    id: 'q-hydrolysis',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'Your body breaks a starch chain into sugar pieces by adding water. That reaction is…',
    options: ['Dehydration synthesis', 'Hydrolysis', 'A hydrogen bond', 'Neutralization'],
    correctIndex: 1,
    explain: 'Adding water to split a polymer is hydrolysis. Dehydration synthesis would join pieces and release water.',
  },
  {
    type: 'question',
    id: 'q-anabolic',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'Linking amino acids into a protein uses energy and removes water. This is…',
    options: [
      'Catabolic hydrolysis',
      'Anabolic dehydration synthesis',
      'Capillary action',
      'A pH change only',
    ],
    correctIndex: 1,
    explain: 'Building a bigger molecule = anabolic. Removing water to make the bond = dehydration synthesis.',
  },
  {
    type: 'teach',
    id: 'carbs',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Carbohydrates = quick energy',
    plain: 'Carbs are sugars. Names often end in -ose. They are for short-term energy.',
    points: [
      'Elements: C, H, O. Building blocks: monosaccharides (one sugar ring, ratio like CH₂O).',
      'The body can only metabolize sugars as monosaccharides.',
      'Bond between sugars: glycosidic linkage.',
      'Monosaccharides: glucose, galactose, fructose.',
      'Disaccharides (2 sugars): sucrose (table sugar), lactose (milk), maltose.',
      'Polysaccharides (long chains): starch, cellulose, glycogen, chitin, peptidoglycan.',
    ],
    visual: 'carbs',
  },
  {
    type: 'teach',
    id: 'poly-carbs',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'The famous polysaccharides',
    plain: 'Same glucose bricks, different jobs: store energy or build walls.',
    points: [
      'Starch: plant energy storage (potatoes, rice, pasta). Digestible with amylase.',
      'Cellulose: plant cell walls. Tough fiber. Animals cannot digest it (cows need microbes to help).',
      'Glycogen: animal glucose storage in liver and muscle. Lasts about 24 hours fasting, or about an hour of hard exercise.',
      'Chitin: fungi cell walls and insect/crustacean exoskeletons.',
      'Peptidoglycan: bacterial cell walls.',
    ],
    visual: 'poly-carbs',
  },
  {
    type: 'question',
    id: 'q-glycogen',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'Which polysaccharide stores glucose in YOUR liver and muscles?',
    options: ['Cellulose', 'Starch', 'Glycogen', 'Chitin'],
    correctIndex: 2,
    explain: 'Glycogen is animal storage. Starch is plant storage. Cellulose is plant structure. Chitin is fungi/insects.',
  },
  {
    type: 'teach',
    id: 'lipids',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Lipids = long-term energy and waterproofing',
    plain: 'Fats, oils, waxes, steroids, and phospholipids. They hate water.',
    points: [
      'Elements: lots of C and H, few O. All lipids are insoluble (nonpolar).',
      'No true monomer. Building blocks: glycerol + fatty acids. Bond: ester linkage (dehydration, one H₂O per bond).',
      'Jobs: long-term energy (more C–H bonds than carbs = more energy per gram), insulation (blubber), waterproof coatings, steroid hormones.',
      'Examples: butter, olive oil, triglycerides, phospholipids, steroids, waxes.',
    ],
    visual: 'lipids',
  },
  {
    type: 'teach',
    id: 'fatty',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Saturated vs unsaturated fats',
    plain: 'Single bonds only = solid “bad fats.” Double bonds = liquid “good fats.”',
    points: [
      'Fatty acids are long C–H chains.',
      'Saturated: only single C–C bonds, straight, solid at room temp (bacon grease). Called “bad fats.”',
      'Unsaturated: has C=C double bonds, kinks, liquid at room temp (oils). Called “good fats.”',
      'Steroids are lipids with four fused rings (testosterone, estrogen, cholesterol). No glycerol, no ester/glycosidic bonds. Still lipids because they are hydrophobic.',
    ],
    visual: 'fatty-acids',
  },
  {
    type: 'question',
    id: 'q-sat',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'Olive oil is liquid at room temperature. Its fatty acids are mostly…',
    options: ['Saturated', 'Unsaturated', 'Cellulose', 'Nucleic acids'],
    correctIndex: 1,
    explain: 'Liquid at room temp = unsaturated (kinked double bonds). Saturated fats tend to be solid.',
  },
  {
    type: 'teach',
    id: 'phospholipid',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Phospholipids build cell membranes',
    plain: 'A phosphate head loves water. Fatty tails hate water. Together they make a two-layer fence.',
    points: [
      'Three parts: phosphate group, glycerol backbone, two fatty acid tails (often one straight saturated, one kinked unsaturated).',
      'Heads face water. Tails hide inside. That is the bilayer.',
      'This dual nature makes the membrane selectively permeable (picky about what goes through).',
    ],
    visual: 'phospholipid',
  },
  {
    type: 'question',
    id: 'q-membrane',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'What lipid makes up the bilayer of cell membranes?',
    options: ['Starch', 'Phospholipid', 'Glycogen', 'DNA'],
    correctIndex: 1,
    explain: 'Phospholipids have a hydrophilic head and hydrophobic tails, so they form the membrane bilayer.',
  },
  {
    type: 'teach',
    id: 'protein',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Proteins do almost everything',
    plain: 'Proteins are chains of amino acids. Shape = job.',
    points: [
      'Elements: C, H, O, N, and sometimes S (CHONS).',
      'Only 20 amino acids make up all life. Bond: peptide bond (amino group + carboxyl group).',
      'A polypeptide is a chain of amino acids. Amino acid parts: amino group, carboxyl group, and R group (side chain).',
      'No single “main function.” They build/repair tissue, and more:',
      'Enzymes (amylase, pepsin) digest. Hemoglobin transports. Keratin/actin structure. Insulin signals. Antibodies defend. Myosin contracts muscle.',
    ],
    visual: 'protein',
    remember: 'Diverse shapes = diverse functions. If the shape breaks (denature), the job fails.',
  },
  {
    type: 'teach',
    id: 'levels',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Four levels of protein structure',
    plain: 'Letters → local folds → 3D blob → team of blobs.',
    points: [
      'Primary: the amino acid sequence, held by peptide bonds. DNA decides this order. This is the backbone.',
      'Secondary: backbone folds into an alpha helix (coil) or beta pleated sheet (zigzag), held by hydrogen bonds.',
      'Tertiary: the overall 3D shape from R-group interactions.',
      'Quaternary: more than one polypeptide chain sticking together (hemoglobin has 4 subunits). Not every protein has this level.',
      'Core idea: structure = function.',
    ],
    visual: 'protein-levels',
  },
  {
    type: 'question',
    id: 'q-primary',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'The order of amino acids in a chain is the protein’s…',
    options: ['Secondary structure', 'Primary structure', 'Quaternary structure', 'pH'],
    correctIndex: 1,
    explain: 'Primary = sequence of amino acids (peptide bonds). Secondary is helices/sheets. Quaternary is multiple chains.',
  },
  {
    type: 'teach',
    id: 'nucleic',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'Nucleic acids: DNA and RNA',
    plain: 'These store the instructions for proteins — the molecule of heredity.',
    points: [
      'Elements: CHONP. Monomer: nucleotide (phosphate + sugar + base).',
      'Polymers: DNA and RNA. Backbone bonds: phosphodiester. Bases stick with hydrogen bonds.',
      'Function: genetic info and instructions for making proteins.',
      'Bases: A pairs with T (DNA) or U (RNA). G pairs with C.',
    ],
    visual: 'nucleic',
    remember: 'A-T (or A-U) and G-C. Nucleotide = phosphate + sugar + base.',
  },
  {
    type: 'question',
    id: 'q-dna',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    prompt: 'In DNA, adenine (A) pairs with…',
    options: ['Guanine (G)', 'Cytosine (C)', 'Thymine (T)', 'Uracil (U) only, even in DNA'],
    correctIndex: 2,
    explain: 'DNA: A-T and G-C. Uracil replaces thymine in RNA, not DNA.',
  },
  {
    type: 'teach',
    id: 'wrap',
    chapter: 'Reactions & Biomolecules',
    chapterNum: 4,
    title: 'You just learned the whole unit',
    plain: 'If you can explain these four ideas in your own words, you are in great shape.',
    points: [
      'Life = all 7 characteristics. Viruses miss some, so they are not living.',
      'Experiments: change IV, measure DV, keep constants, compare to a control, graph it honestly.',
      'Water is polar, hydrogen-bonded, and weird in the best way (ice floats, sweat cools, it dissolves a lot).',
      'CHONPS molecules: carbs (quick energy), lipids (long-term + membranes), proteins (shape = job), nucleic acids (instructions).',
      'Build with dehydration. Break with hydrolysis.',
    ],
    visual: 'organic',
    remember: 'More of this unit can be added later. This study path covers the slideshow you have now.',
  },
]

export function getBioQuestionCount(steps: BioLessonStep[] = BIO_UNIT_1_LESSON): number {
  return steps.filter((step) => step.type === 'question').length
}
