export type BioVisualId =
  | 'life-list'
  | 'cells'
  | 'energy'
  | 'growth'
  | 'homeostasis'
  | 'stimulus'
  | 'evolution'
  | 'virus'
  | 'graph'
  | 'graph-types'
  | 'data-types'
  | 'observe'
  | 'variables'
  | 'experiment'
  | 'water'
  | 'polar'
  | 'hydro'
  | 'capillary'
  | 'surface'
  | 'specific-heat'
  | 'ice'
  | 'solvent'
  | 'sweat'
  | 'ph'
  | 'organic'
  | 'carbon'
  | 'mono-poly'
  | 'anabolic'
  | 'catabolic'
  | 'dehydration'
  | 'hydrolysis'
  | 'carbs'
  | 'poly-carbs'
  | 'lipids'
  | 'fatty-acids'
  | 'phospholipid'
  | 'protein'
  | 'protein-levels'
  | 'nucleic'

export interface BioTeachStep {
  type: 'teach'
  id: string
  chapter: string
  chapterNum: number
  title: string
  plain: string
  points: string[]
  visual: BioVisualId
  remember?: string
}

export interface BioQuestionStep {
  type: 'question'
  id: string
  chapter: string
  chapterNum: number
  prompt: string
  options: string[]
  correctIndex: number
  explain: string
}

export type BioLessonStep = BioTeachStep | BioQuestionStep

export const BIO_UNIT_1_CHAPTER_COUNT = 2
export const BIO_UNIT_1_PROGRESS_KEY = 'bio-unit-1-study-progress-v2'

const W = 'Properties of Water'
const M = 'Reactions & Biomolecules'

export const BIO_UNIT_1_LESSON: BioLessonStep[] = [
  {
    type: 'teach',
    id: 'water-intro',
    chapter: W,
    chapterNum: 1,
    title: 'Water is the molecule of life',
    plain: 'Inside one water molecule, atoms share electrons. Between water molecules, they cling with hydrogen bonds.',
    points: [
      'A water molecule is H₂O: two hydrogens, one oxygen.',
      'Covalent bonds (sharing electron pairs) hold H and O together INSIDE one molecule.',
      'Hydrogen bonds attract SEPARATE water molecules to each other.',
      'Hydrogen bonds are weaker than covalent or ionic bonds, but they are strong enough to give water its special properties.',
    ],
    visual: 'water',
    remember: 'Covalent = within one H₂O. Hydrogen bond = between two H₂Os.',
  },
  {
    type: 'question',
    id: 'q-bonds',
    chapter: W,
    chapterNum: 1,
    prompt: 'What holds two different water molecules together?',
    options: ['Ionic bonds', 'Covalent bonds', 'Hydrogen bonds', 'Peptide bonds'],
    correctIndex: 2,
    explain: 'Covalent bonds are inside one molecule. Hydrogen bonds form between molecules.',
  },
  {
    type: 'teach',
    id: 'polar',
    chapter: W,
    chapterNum: 1,
    title: 'Water is polar',
    plain: 'Electrons are not shared fairly, so water has a slightly negative oxygen side and slightly positive hydrogen side.',
    points: [
      'Oxygen pulls electrons harder than hydrogen.',
      'Oxygen side = partially negative (δ−). Hydrogen side = partially positive (δ+).',
      'That uneven charge is why water can form hydrogen bonds and dissolve lots of stuff.',
    ],
    visual: 'polar',
  },
  {
    type: 'question',
    id: 'q-polar',
    chapter: W,
    chapterNum: 1,
    prompt: 'Why is the oxygen side of water slightly negative?',
    options: [
      'Hydrogen pulls electrons harder than oxygen',
      'Oxygen pulls electrons harder than hydrogen',
      'Water has no charges at all',
      'Ice is denser than liquid water',
    ],
    correctIndex: 1,
    explain: 'Oxygen hogs the shared electrons, so oxygen is δ− and the hydrogens are δ+.',
  },
  {
    type: 'teach',
    id: 'hydro',
    chapter: W,
    chapterNum: 1,
    title: 'Hydrophilic vs hydrophobic',
    plain: 'Water-loving stuff mixes in. Water-fearing stuff will not.',
    points: [
      'Hydrophilic (“water-loving”) = polar molecules or ions. They dissolve in water. Examples: salt and sugar.',
      'Hydrophobic (“water-fearing”) = nonpolar. They do not dissolve. Example: oil.',
    ],
    visual: 'hydro',
  },
  {
    type: 'question',
    id: 'q-hydro',
    chapter: W,
    chapterNum: 1,
    prompt: 'Oil sits on top of water and does not mix. Oil is…',
    options: ['Hydrophilic and polar', 'Hydrophobic and nonpolar', 'An acid', 'A solute that water always dissolves'],
    correctIndex: 1,
    explain: 'Oil is nonpolar, so it does not mix with polar water. That is hydrophobic = water-fearing.',
  },
  {
    type: 'teach',
    id: 'cohesion',
    chapter: W,
    chapterNum: 1,
    title: 'Cohesion',
    plain: 'Cohesion means water sticks to other water.',
    points: [
      'Co- = with or together. Cohesion = molecules of the same substance attracting each other.',
      'Water-to-water cohesion makes round droplets on leaves.',
      'It also causes high surface tension.',
    ],
    visual: 'surface',
  },
  {
    type: 'question',
    id: 'q-cohesion',
    chapter: W,
    chapterNum: 1,
    prompt: 'Water forming a round droplet on a leaf is mainly…',
    options: ['Adhesion', 'Cohesion', 'An acid-base reaction', 'Hydrolysis'],
    correctIndex: 1,
    explain: 'Droplets happen because water sticks to water. That is cohesion.',
  },
  {
    type: 'teach',
    id: 'adhesion',
    chapter: W,
    chapterNum: 1,
    title: 'Adhesion',
    plain: 'Adhesion means water sticks to a different substance.',
    points: [
      'Example: water sticking to glass in a graduated cylinder, which makes a meniscus.',
      'Read a meniscus at the BOTTOM of the curve for the real volume.',
    ],
    visual: 'capillary',
  },
  {
    type: 'question',
    id: 'q-adhesion',
    chapter: W,
    chapterNum: 1,
    prompt: 'A meniscus forms in a glass graduated cylinder mainly because of…',
    options: ['Cohesion only', 'Adhesion', 'Ice floating', 'pH'],
    correctIndex: 1,
    explain: 'Water sticks to the glass (a different substance). That is adhesion. Read the bottom of the curve.',
  },
  {
    type: 'teach',
    id: 'capillary',
    chapter: W,
    chapterNum: 1,
    title: 'Property 1: Capillary action',
    plain: 'Water can climb thin tubes because cohesion and adhesion work together.',
    points: [
      'Capillary action = water moving upward in a thin space.',
      'Examples: water up plant vessels, water up a drinking straw or paper towel.',
    ],
    visual: 'capillary',
  },
  {
    type: 'question',
    id: 'q-capillary',
    chapter: W,
    chapterNum: 1,
    prompt: 'Water climbing a paper towel or a plant stem is…',
    options: ['pH', 'Capillary action', 'Freezing', 'Hydrolysis'],
    correctIndex: 1,
    explain: 'Climbing thin spaces uses cohesion + adhesion together, which is capillary action.',
  },
  {
    type: 'teach',
    id: 'surface',
    chapter: W,
    chapterNum: 1,
    title: 'Property 2: Surface tension',
    plain: 'The top of water acts like a tight skin because water molecules cling to each other.',
    points: [
      'Surface tension = how hard it is to stretch or break the surface of a liquid.',
      'Water’s surface tension is high because of cohesion from hydrogen bonds.',
      'That is why some bugs can walk on water.',
    ],
    visual: 'surface',
  },
  {
    type: 'question',
    id: 'q-surface',
    chapter: W,
    chapterNum: 1,
    prompt: 'A bug can walk on a pond mainly because water has high…',
    options: ['Heat of vaporization', 'pH', 'Surface tension', 'Salinity'],
    correctIndex: 2,
    explain: 'Hydrogen-bond cohesion makes the surface hard to break. That is surface tension.',
  },
  {
    type: 'teach',
    id: 'specific-heat',
    chapter: W,
    chapterNum: 1,
    title: 'Property 3: High specific heat',
    plain: 'Water is stubborn about changing temperature.',
    points: [
      'Specific heat = energy needed to raise 1 gram of a substance by 1°C.',
      'Water’s specific heat is high because of hydrogen bonds.',
      'A pond stays more stable from day to night than air or land.',
      'That stability is a big reason life can live in water.',
    ],
    visual: 'specific-heat',
  },
  {
    type: 'question',
    id: 'q-specific-heat',
    chapter: W,
    chapterNum: 1,
    prompt: 'A pond stays closer to the same temperature day and night than the air does. That is because water has…',
    options: ['Low specific heat', 'High specific heat', 'No hydrogen bonds', 'A pH of 14'],
    correctIndex: 1,
    explain: 'High specific heat means water takes a lot of energy to heat up or cool down, so habitats stay more stable.',
  },
  {
    type: 'teach',
    id: 'ice',
    chapter: W,
    chapterNum: 1,
    title: 'Property 4: Ice floats',
    plain: 'Solid water is less dense than liquid water, so ice sits on top instead of sinking.',
    points: [
      'Most substances get denser when they freeze. Water expands.',
      'Ice floating insulates the water below, so lakes do not freeze solid.',
      'Fish and other life can survive under the ice.',
    ],
    visual: 'ice',
  },
  {
    type: 'question',
    id: 'q-ice',
    chapter: W,
    chapterNum: 1,
    prompt: 'Why does ice floating matter for living things in a lake?',
    options: [
      'Ice is hydrophobic so fish can breathe it',
      'The ice layer insulates water below so the lake does not freeze solid',
      'Ice raises the pH to 14',
      'Ice is a protein',
    ],
    correctIndex: 1,
    explain: 'Because ice is less dense, it forms a lid on top. Life can keep going underneath.',
  },
  {
    type: 'teach',
    id: 'solvent',
    chapter: W,
    chapterNum: 1,
    title: 'Property 5: Universal solvent',
    plain: 'Water dissolves many things because of its charges.',
    points: [
      'Solution = mixture of substances in a liquid (sugar water).',
      'Solvent = the dissolver (water). Solute = the thing dissolved (sugar).',
      'Water is called the universal solvent because polarity lets it dissolve many ions and polar molecules.',
    ],
    visual: 'solvent',
  },
  {
    type: 'question',
    id: 'q-solvent',
    chapter: W,
    chapterNum: 1,
    prompt: 'In sugar water, water is the ______ and sugar is the ______.',
    options: ['solute ; solvent', 'solvent ; solute', 'acid ; base', 'polymer ; monomer'],
    correctIndex: 1,
    explain: 'Solvent does the dissolving (water). Solute is what gets dissolved (sugar).',
  },
  {
    type: 'teach',
    id: 'vapor',
    chapter: W,
    chapterNum: 1,
    title: 'Property 6: High heat of vaporization',
    plain: 'It takes a lot of energy to turn water into gas — that is why sweat cools you.',
    points: [
      'Heat of vaporization = energy to go from liquid to gas.',
      'Evaporative cooling: the leftover liquid is cooler after the fastest molecules leave.',
      'Sweat steals heat from your skin to evaporate, so you cool down.',
      'This also helps keep water on Earth (and in your body) as a liquid.',
    ],
    visual: 'sweat',
  },
  {
    type: 'question',
    id: 'q-vapor',
    chapter: W,
    chapterNum: 1,
    prompt: 'Sweating cools you because water has a high…',
    options: ['Density as a solid', 'Heat of vaporization', 'pH', 'Glycosidic linkage'],
    correctIndex: 1,
    explain: 'It takes a lot of heat to evaporate water. That heat leaves your skin, so you cool down.',
  },
  {
    type: 'teach',
    id: 'ph',
    chapter: W,
    chapterNum: 1,
    title: 'pH: acids and bases',
    plain: 'pH ranks how many H⁺ ions are in a solution.',
    points: [
      'Water can split: H₂O ⇌ H⁺ + OH⁻.',
      'Pure water has equal H⁺ and OH⁻ (neutral, pH 7).',
      'Acid: pH < 7, extra H⁺, sour/tart (citrus, stomach acid).',
      'Base (alkaline): pH > 7, extra OH⁻, bitter (soap, bleach).',
      'Most cells like pH near 7. Extreme pH can denature (unfold) proteins.',
      'The scale is usually 0–14, but values outside that are possible.',
    ],
    visual: 'ph',
  },
  {
    type: 'question',
    id: 'q-ph',
    chapter: W,
    chapterNum: 1,
    prompt: 'Lemon juice tastes sour and has lots of H⁺ ions. It is…',
    options: ['A base with pH 10', 'Neutral water', 'An acid with pH below 7', 'A lipid'],
    correctIndex: 2,
    explain: 'High H⁺ and sour taste = acid. Acids are below 7 on the pH scale.',
  },
  {
    type: 'question',
    id: 'q-denature',
    chapter: W,
    chapterNum: 1,
    prompt: 'A pH that is way too acidic or basic can unfold proteins. That unfolding is called…',
    options: ['Capillary action', 'Denaturation', 'Dehydration synthesis', 'Adhesion'],
    correctIndex: 1,
    explain: 'Extreme pH can denature proteins, which wrecks their shape and their job.',
  },
  {
    type: 'teach',
    id: 'organic',
    chapter: M,
    chapterNum: 2,
    title: 'Organic compounds',
    plain: 'Organic in biology means carbon-based molecules that build living things — not “organic grocery.”',
    points: [
      'Organic compounds have carbon-carbon and carbon-hydrogen bonds, usually with lots of carbons.',
      'They often include C, H, O, N, P, and sometimes S (CHONPS).',
      'Macromolecules are the large organic molecules of life: carbs, lipids, proteins, nucleic acids.',
      'They run your body, store instructions, and supply energy.',
      'Carbon skeletons in diagrams are zig-zags: every end and bend is a carbon. You do not have to draw them, but you should recognize them.',
    ],
    visual: 'organic',
  },
  {
    type: 'question',
    id: 'q-organic',
    chapter: M,
    chapterNum: 2,
    prompt: 'Which list is the four macromolecules of life?',
    options: [
      'Acids, bases, salts, water',
      'Carbs, lipids, proteins, nucleic acids',
      'Starch, ice, oil, glass',
      'H⁺, OH⁻, Na⁺, Cl⁻',
    ],
    correctIndex: 1,
    explain: 'The big four are carbohydrates, lipids, proteins, and nucleic acids.',
  },
  {
    type: 'teach',
    id: 'carbon',
    chapter: M,
    chapterNum: 2,
    title: 'Why carbon is the building superstar',
    plain: 'Carbon has 4 open bonding spots, so it can make chains, branches, and rings.',
    points: [
      'Carbon has 4 valence electrons, so it can form 4 covalent bonds.',
      'That is why molecules can be so many shapes and sizes.',
      'Common shapes: straight chain, branched chain, ring.',
      'Inorganic compounds lack those carbon-carbon / carbon-hydrogen organic setups.',
    ],
    visual: 'carbon',
  },
  {
    type: 'question',
    id: 'q-carbon',
    chapter: M,
    chapterNum: 2,
    prompt: 'Carbon can form so many different molecules mainly because it can make how many covalent bonds?',
    options: ['1', '2', '4', '7'],
    correctIndex: 2,
    explain: 'Four valence electrons = four bonding spots. That is why carbon can make chains, branches, and rings.',
  },
  {
    type: 'teach',
    id: 'mono-poly',
    chapter: M,
    chapterNum: 2,
    title: 'Monomers and polymers',
    plain: 'Monomers are LEGO bricks. Polymers are the castle you build.',
    points: [
      'Monomer = small building block.',
      'Polymer = many monomers bonded together.',
      'Most macromolecules are polymers made of monomers. Lipids are the awkward exception (no true repeating monomer).',
    ],
    visual: 'mono-poly',
  },
  {
    type: 'question',
    id: 'q-mono',
    chapter: M,
    chapterNum: 2,
    prompt: 'A polymer is…',
    options: [
      'One small building block',
      'Many monomers bonded together',
      'Only found in water',
      'Always a lipid',
    ],
    correctIndex: 1,
    explain: 'Mono = one brick. Poly = many bricks linked together. Lipids do not follow this repeating-monomer pattern.',
  },
  {
    type: 'teach',
    id: 'anabolic',
    chapter: M,
    chapterNum: 2,
    title: 'Anabolic reactions',
    plain: 'Anabolic reactions build bigger molecules and use energy.',
    points: [
      'Anabolic: A + B → AB.',
      'They USE energy to synthesize large molecules.',
    ],
    visual: 'anabolic',
  },
  {
    type: 'question',
    id: 'q-anabolic',
    chapter: M,
    chapterNum: 2,
    prompt: 'A reaction that uses energy to join small pieces into a bigger molecule is…',
    options: ['Catabolic', 'Anabolic', 'Neutralization', 'Evaporation'],
    correctIndex: 1,
    explain: 'Anabolic = build up. Catabolic = break down.',
  },
  {
    type: 'teach',
    id: 'catabolic',
    chapter: M,
    chapterNum: 2,
    title: 'Catabolic reactions',
    plain: 'Catabolic reactions break molecules apart and release energy.',
    points: [
      'Catabolic: AB → A + B.',
      'They RELEASE energy by making smaller molecules.',
    ],
    visual: 'catabolic',
  },
  {
    type: 'question',
    id: 'q-catabolic',
    chapter: M,
    chapterNum: 2,
    prompt: 'Digestion breaking a big food molecule into smaller pieces is…',
    options: ['Anabolic', 'Catabolic', 'Adhesion', 'A law of motion'],
    correctIndex: 1,
    explain: 'Breaking bigger into smaller and releasing energy = catabolic.',
  },
  {
    type: 'teach',
    id: 'dehydration',
    chapter: M,
    chapterNum: 2,
    title: 'Dehydration synthesis',
    plain: 'Join two pieces. Water gets kicked out.',
    points: [
      'This is anabolic: it creates new bonds and larger molecules.',
      'It is a condensation reaction (two molecules become one).',
      'An H comes off one molecule and an OH comes off the other. That H₂O leaves as waste.',
      'Every new bond made this way removes one water.',
    ],
    visual: 'dehydration',
    remember: 'Dehydration = take water out to build.',
  },
  {
    type: 'question',
    id: 'q-dehydration',
    chapter: M,
    chapterNum: 2,
    prompt: 'Linking two monomers together and releasing water is…',
    options: ['Hydrolysis', 'Dehydration synthesis', 'Capillary action', 'Denaturation'],
    correctIndex: 1,
    explain: 'Build + remove water = dehydration synthesis.',
  },
  {
    type: 'teach',
    id: 'hydrolysis',
    chapter: M,
    chapterNum: 2,
    title: 'Hydrolysis',
    plain: 'Add water. The chain splits.',
    points: [
      'This is catabolic: bigger molecules become smaller ones.',
      'Hydro- = water. -lysis = to cut / break down.',
      'Water is added as a reactant. H goes to one piece, OH goes to the other.',
      'Digestion of food polymers is hydrolysis.',
    ],
    visual: 'hydrolysis',
    remember: 'Hydrolysis = add water to break.',
  },
  {
    type: 'question',
    id: 'q-hydrolysis',
    chapter: M,
    chapterNum: 2,
    prompt: 'Your body breaks a starch chain into sugar pieces by adding water. That reaction is…',
    options: ['Dehydration synthesis', 'Hydrolysis', 'A hydrogen bond', 'Neutralization'],
    correctIndex: 1,
    explain: 'Adding water to split a polymer is hydrolysis.',
  },
  {
    type: 'teach',
    id: 'carbs',
    chapter: M,
    chapterNum: 2,
    title: 'Carbohydrates = quick energy',
    plain: 'Carbs are sugars. Names often end in -ose. They are for short-term energy.',
    points: [
      'Elements: C, H, O.',
      'Building blocks: monosaccharides (one sugar ring, ratio like CH₂O).',
      'The body can only metabolize sugars as monosaccharides.',
      'Bond between sugars: glycosidic linkage.',
      'Monosaccharides: glucose, galactose, fructose.',
      'Disaccharides (2 sugars): sucrose (table sugar), lactose (milk), maltose.',
    ],
    visual: 'carbs',
  },
  {
    type: 'question',
    id: 'q-carbs',
    chapter: M,
    chapterNum: 2,
    prompt: 'The monomer (building block) of a carbohydrate is a…',
    options: ['Amino acid', 'Nucleotide', 'Monosaccharide', 'Fatty acid'],
    correctIndex: 2,
    explain: 'Carbs are built from monosaccharides. The bond between them is a glycosidic linkage.',
  },
  {
    type: 'question',
    id: 'q-carb-job',
    chapter: M,
    chapterNum: 2,
    prompt: 'The main job of carbohydrates is…',
    options: ['Long-term energy storage', 'Short-term / quick energy', 'Storing DNA', 'Making cell membranes only'],
    correctIndex: 1,
    explain: 'Carbs are the quick-energy molecules. Lipids are the long-term storage ones.',
  },
  {
    type: 'teach',
    id: 'poly-carbs',
    chapter: M,
    chapterNum: 2,
    title: 'Polysaccharides',
    plain: 'Same sugar bricks, different jobs: store energy or build walls.',
    points: [
      'Polysaccharides = long chains of monosaccharides held by glycosidic linkages.',
      'Starch: plant energy storage (potatoes, rice, pasta). Digestible with amylase.',
      'Cellulose: plant cell walls. Tough fiber. Animals cannot digest it (cows need microbes to help).',
      'Glycogen: animal glucose storage in liver and muscle. About 24 hours if fasting, about an hour of hard exercise.',
      'Chitin: fungi cell walls and insect/crustacean exoskeletons.',
      'Peptidoglycan: bacterial cell walls.',
    ],
    visual: 'poly-carbs',
  },
  {
    type: 'question',
    id: 'q-glycogen',
    chapter: M,
    chapterNum: 2,
    prompt: 'Which polysaccharide stores glucose in YOUR liver and muscles?',
    options: ['Cellulose', 'Starch', 'Glycogen', 'Chitin'],
    correctIndex: 2,
    explain: 'Glycogen is animal storage. Starch is plant storage. Cellulose is plant structure. Chitin is fungi/insects.',
  },
  {
    type: 'question',
    id: 'q-cellulose',
    chapter: M,
    chapterNum: 2,
    prompt: 'Which polysaccharide makes plant cell walls and is not digestible by animals?',
    options: ['Glycogen', 'Starch', 'Cellulose', 'Triglyceride'],
    correctIndex: 2,
    explain: 'Cellulose is the tough plant-wall fiber. Starch is how plants store energy.',
  },
  {
    type: 'teach',
    id: 'lipids',
    chapter: M,
    chapterNum: 2,
    title: 'Lipids = long-term energy and waterproofing',
    plain: 'Fats, oils, waxes, steroids, and phospholipids. They hate water.',
    points: [
      'Elements: lots of C and H, few O. All lipids are insoluble (nonpolar).',
      'No true monomer. Building blocks: glycerol + fatty acids. Bond: ester linkage (one H₂O removed per bond).',
      'Jobs: long-term energy (more C–H bonds than carbs = more energy per gram), insulation (blubber), waterproof coatings, steroid hormones.',
      'Examples: butter, olive oil, triglycerides, phospholipids, steroids, waxes.',
    ],
    visual: 'lipids',
  },
  {
    type: 'question',
    id: 'q-lipids',
    chapter: M,
    chapterNum: 2,
    prompt: 'Compared with carbs, lipids are mainly used for…',
    options: ['Short-term energy', 'Long-term energy storage', 'Storing genetic code', 'Making glycosidic linkages'],
    correctIndex: 1,
    explain: 'More C–H bonds = more energy per gram, so lipids are the long-term storage molecules. They also insulate and waterproof.',
  },
  {
    type: 'question',
    id: 'q-ester',
    chapter: M,
    chapterNum: 2,
    prompt: 'The bond that joins glycerol to fatty acids is a…',
    options: ['Peptide bond', 'Glycosidic linkage', 'Ester linkage', 'Hydrogen bond between bases'],
    correctIndex: 2,
    explain: 'Lipids use ester linkages. Carbs use glycosidic linkages. Proteins use peptide bonds.',
  },
  {
    type: 'teach',
    id: 'fatty',
    chapter: M,
    chapterNum: 2,
    title: 'Saturated vs unsaturated fats',
    plain: 'Single bonds only = solid “bad fats.” Double bonds = liquid “good fats.”',
    points: [
      'Fatty acids are long C–H chains.',
      'Saturated: only single C–C bonds, straight, solid at room temp (bacon grease). Called “bad fats.”',
      'Unsaturated: has C=C double bonds, kinks, liquid at room temp (oils). Called “good fats.”',
    ],
    visual: 'fatty-acids',
  },
  {
    type: 'question',
    id: 'q-sat',
    chapter: M,
    chapterNum: 2,
    prompt: 'Olive oil is liquid at room temperature. Its fatty acids are mostly…',
    options: ['Saturated', 'Unsaturated', 'Cellulose', 'Nucleic acids'],
    correctIndex: 1,
    explain: 'Liquid at room temp = unsaturated (kinked double bonds). Saturated fats tend to be solid.',
  },
  {
    type: 'teach',
    id: 'steroids',
    chapter: M,
    chapterNum: 2,
    title: 'Steroids',
    plain: 'Steroids are lipids with four fused rings — no fat tails, still hydrophobic.',
    points: [
      'Carbon skeleton = four fused rings.',
      'No glycosidic or ester bonds. No glycerol.',
      'They still count as lipids because they are hydrophobic.',
      'Examples: testosterone, estrogen, cholesterol.',
    ],
    visual: 'lipids',
  },
  {
    type: 'question',
    id: 'q-steroid',
    chapter: M,
    chapterNum: 2,
    prompt: 'Cholesterol, estrogen, and testosterone are lipids because they are hydrophobic. Their shape is…',
    options: ['A long glycogen chain', 'Four fused rings', 'A nucleotide', 'A cellulose fiber'],
    correctIndex: 1,
    explain: 'Steroids have four fused rings. They do not have glycerol or ester bonds.',
  },
  {
    type: 'teach',
    id: 'phospholipid',
    chapter: M,
    chapterNum: 2,
    title: 'Phospholipids build cell membranes',
    plain: 'A phosphate head loves water. Fatty tails hate water. Together they make a two-layer fence.',
    points: [
      'Three parts: phosphate group, glycerol backbone, two fatty acid tails (often one straight saturated, one kinked unsaturated).',
      'Heads face water. Tails hide inside. That is the bilayer.',
      'This dual nature makes the membrane selectively permeable (picky about what goes through).',
    ],
    visual: 'phospholipid',
  },
  {
    type: 'question',
    id: 'q-membrane',
    chapter: M,
    chapterNum: 2,
    prompt: 'What lipid makes up the bilayer of cell membranes?',
    options: ['Starch', 'Phospholipid', 'Glycogen', 'DNA'],
    correctIndex: 1,
    explain: 'Phospholipids have a hydrophilic head and hydrophobic tails, so they form the membrane bilayer.',
  },
  {
    type: 'teach',
    id: 'protein',
    chapter: M,
    chapterNum: 2,
    title: 'Proteins are amino acid chains',
    plain: 'Only 20 amino acids make all life. Peptide bonds link them.',
    points: [
      'Elements: C, H, O, N, and sometimes S (CHONS).',
      'Building blocks: amino acids (AAs).',
      'Bond: peptide bond between the amino group and the carboxyl group.',
      'A polypeptide is a chain of many amino acids.',
      'Amino acid parts: amino group, carboxyl group, and R group (side chain).',
    ],
    visual: 'protein',
  },
  {
    type: 'question',
    id: 'q-peptide',
    chapter: M,
    chapterNum: 2,
    prompt: 'Amino acids are joined by…',
    options: ['Ester linkages', 'Glycosidic linkages', 'Peptide bonds', 'Phosphodiester bonds only'],
    correctIndex: 2,
    explain: 'Proteins: peptide bonds. Carbs: glycosidic. Lipids: ester. Nucleic acid backbones: phosphodiester.',
  },
  {
    type: 'teach',
    id: 'protein-jobs',
    chapter: M,
    chapterNum: 2,
    title: 'Proteins do almost everything',
    plain: 'There is no single “main function.” Shape decides the job.',
    points: [
      'They build and repair tissue after damage (like after exercise).',
      'CORE IDEA: diverse shapes = diverse functions.',
      'Enzymes (amylase, pepsin) break down nutrients.',
      'Hemoglobin transports substances in blood.',
      'Actin and keratin build structures. Insulin is a hormone signal. Antibodies defend. Myosin contracts muscle.',
    ],
    visual: 'protein',
    remember: 'If the shape breaks (denature), the job fails.',
  },
  {
    type: 'question',
    id: 'q-protein-job',
    chapter: M,
    chapterNum: 2,
    prompt: 'Hemoglobin’s job is to…',
    options: ['Digest starch', 'Carry substances in blood', 'Store glucose in plants', 'Make up insect exoskeletons'],
    correctIndex: 1,
    explain: 'Hemoglobin is a transport protein in blood. Amylase digests. Starch/glycogen store sugar. Chitin is structure in insects/fungi.',
  },
  {
    type: 'teach',
    id: 'primary',
    chapter: M,
    chapterNum: 2,
    title: 'Primary protein structure',
    plain: 'Primary structure is just the amino acid order — the backbone sequence.',
    points: [
      'Held together by peptide bonds.',
      'The sequence is determined by your DNA.',
      'This is the starting “bead string” every other level is built on.',
    ],
    visual: 'protein-levels',
  },
  {
    type: 'question',
    id: 'q-primary',
    chapter: M,
    chapterNum: 2,
    prompt: 'The order of amino acids in a chain is the protein’s…',
    options: ['Secondary structure', 'Primary structure', 'Quaternary structure', 'pH'],
    correctIndex: 1,
    explain: 'Primary = sequence of amino acids, held by peptide bonds.',
  },
  {
    type: 'teach',
    id: 'secondary',
    chapter: M,
    chapterNum: 2,
    title: 'Secondary protein structure',
    plain: 'The backbone folds into a coil or a zigzag sheet.',
    points: [
      'These folds form from interactions between atoms of the backbone.',
      'Two types: alpha (α) helix and beta (β) pleated sheet.',
      'They are held in shape by hydrogen bonds.',
    ],
    visual: 'protein-levels',
  },
  {
    type: 'question',
    id: 'q-secondary',
    chapter: M,
    chapterNum: 2,
    prompt: 'An alpha helix or beta pleated sheet is…',
    options: ['Primary structure', 'Secondary structure', 'A nucleotide', 'A triglyceride'],
    correctIndex: 1,
    explain: 'Secondary structure = helix or pleated sheet, held by hydrogen bonds in the backbone.',
  },
  {
    type: 'teach',
    id: 'tertiary',
    chapter: M,
    chapterNum: 2,
    title: 'Tertiary protein structure',
    plain: 'Tertiary structure is the overall 3D blob of one polypeptide.',
    points: [
      'It comes from interactions between R groups (side chains).',
      'This 3D shape is a huge reason the protein can do its job.',
    ],
    visual: 'protein-levels',
  },
  {
    type: 'question',
    id: 'q-tertiary',
    chapter: M,
    chapterNum: 2,
    prompt: 'Tertiary structure comes from interactions between…',
    options: ['Two DNA strands', 'R groups (side chains)', 'Glycerol and fatty acids', 'Plant cell walls'],
    correctIndex: 1,
    explain: 'Tertiary = overall 3D shape from R-group interactions.',
  },
  {
    type: 'teach',
    id: 'quaternary',
    chapter: M,
    chapterNum: 2,
    title: 'Quaternary protein structure',
    plain: 'Some proteins are a team of more than one polypeptide chain.',
    points: [
      'Quaternary structure = chains interacting with each other.',
      'Only possible if the protein has multiple subunits.',
      'Example: hemoglobin has 4 subunits.',
      'Not every protein has this level.',
    ],
    visual: 'protein-levels',
    remember: 'Structure = function. Shape decides the job.',
  },
  {
    type: 'question',
    id: 'q-quaternary',
    chapter: M,
    chapterNum: 2,
    prompt: 'Hemoglobin has 4 polypeptide subunits working together. That extra level is…',
    options: ['Primary only', 'Secondary only', 'Quaternary structure', 'A glycosidic linkage'],
    correctIndex: 2,
    explain: 'Multiple chains sticking together = quaternary. Not all proteins have this.',
  },
  {
    type: 'teach',
    id: 'nucleic',
    chapter: M,
    chapterNum: 2,
    title: 'Nucleic acids: DNA and RNA',
    plain: 'These store the instructions for proteins — the molecule of heredity.',
    points: [
      'Elements: CHONP.',
      'Building blocks: nucleotides. A nucleotide has 3 parts: phosphate, sugar, and base.',
      'Polymers: DNA and RNA.',
      'Backbone bonds: phosphodiester. Bases stick with hydrogen bonds.',
      'Function: genetic info and instructions for making proteins.',
    ],
    visual: 'nucleic',
  },
  {
    type: 'question',
    id: 'q-nucleotide',
    chapter: M,
    chapterNum: 2,
    prompt: 'A nucleotide is made of…',
    options: [
      'Glycerol and three fatty acids',
      'Phosphate, sugar, and a base',
      'Only amino acids',
      'Glucose rings only',
    ],
    correctIndex: 1,
    explain: 'Nucleotide = phosphate + sugar + base. That is the monomer of DNA and RNA.',
  },
  {
    type: 'teach',
    id: 'base-pairs',
    chapter: M,
    chapterNum: 2,
    title: 'Base pairing',
    plain: 'The bases pair up in a fixed way.',
    points: [
      'Adenine (A) pairs with Thymine (T) in DNA, or Uracil (U) in RNA.',
      'Guanine (G) pairs with Cytosine (C).',
      'Those base pairs are held by hydrogen bonds.',
    ],
    visual: 'nucleic',
    remember: 'DNA: A-T and G-C. RNA: A-U and G-C.',
  },
  {
    type: 'question',
    id: 'q-dna',
    chapter: M,
    chapterNum: 2,
    prompt: 'In DNA, adenine (A) pairs with…',
    options: ['Guanine (G)', 'Cytosine (C)', 'Thymine (T)', 'Uracil (U) only, even in DNA'],
    correctIndex: 2,
    explain: 'DNA: A-T and G-C. Uracil replaces thymine in RNA, not DNA.',
  },
]

export function getBioQuestionCount(steps: BioLessonStep[] = BIO_UNIT_1_LESSON): number {
  return steps.filter((step) => step.type === 'question').length
}
