import { mc, multi, typed, type GeoMathPracticeQuestion } from './geoMathQuiz'

const V = 'volume' as const
const D = 'density' as const

export const VOLUME_QUESTIONS: GeoMathPracticeQuestion[] = [
  mc(
    'v1e',
    V,
    'A cylinder with diameter 20 m and height 7 m. What is the exact volume?',
    ['700π m³', '2800π m³', '140π m³', '70π m³'],
    0,
    'r = 10. V = πr²h = π·100·7 = 700π.',
    { figure: { kind: 'cylinder', r: '10 m', h: '7 m' } },
  ),
  typed(
    'v1a',
    V,
    'A cylinder with diameter 20 m and height 7 m. Approximate the volume to three decimal places.',
    ['2199.115', '2199.114'],
    '700π ≈ 2199.115.',
    {
      prefix: 'V ≈',
      unit: 'm³',
      value: 700 * Math.PI,
      tolerance: 0.01,
      figure: { kind: 'cylinder', r: '10 m', h: '7 m' },
    },
  ),
  typed(
    'v2',
    V,
    'A pyramid 10 m tall has a right-triangle base with sides 6 m, 8 m, and 10 m. Find the volume.',
    ['80'],
    'Base area = ½·6·8 = 24. V = (1/3)·24·10 = 80.',
    {
      prefix: 'V =',
      unit: 'm³',
      value: 80,
      figure: { kind: 'pyramid', base: '6-8-10 right Δ', h: '10 m' },
    },
  ),
  mc(
    'v3e',
    V,
    'A cone has slant height 15 in and diameter 12 in. Find the exact volume.',
    ['36π√21 in³', '180π in³', '540π in³', '12π√21 in³'],
    0,
    'r = 6, h = √(15² − 6²) = √189 = 3√21. V = (1/3)πr²h = (1/3)π·36·3√21 = 36π√21.',
    { figure: { kind: 'cone', r: '6 in', slant: '15 in' } },
  ),
  typed(
    'v4',
    V,
    'A cone with a base angle of 26° and radius 8 cm. Approximate the volume to three decimal places. (h = r tan 26°.)',
    ['261.501', '261.500', '261.502', '261.499'],
    'h = 8 tan 26° ≈ 3.902. V = (1/3)π·64·h ≈ 261.501.',
    {
      prefix: 'V ≈',
      unit: 'cm³',
      value: (1 / 3) * Math.PI * 64 * 8 * Math.tan((26 * Math.PI) / 180),
      tolerance: 0.05,
      figure: { kind: 'cone', r: '8 cm', angle: '26°' },
    },
  ),
  typed(
    'v5',
    V,
    'Find the radius of a sphere that has volume 164.636 in³. Round to the nearest tenth.',
    ['3.4'],
    'V = (4/3)πr³ = 164.636 → r³ ≈ 39.27 → r ≈ 3.4.',
    {
      prefix: 'r =',
      unit: 'in',
      value: 3.4,
      tolerance: 0.08,
      figure: { kind: 'sphere', v: '164.636 in³' },
    },
  ),
  typed(
    'v6',
    V,
    'Find the height of a cone with volume 1104.031 cm³ and radius 5 cm. Round to three decimal places.',
    ['42.171', '42.170', '42.172'],
    'V = (1/3)πr²h → h = 3V/(π·25) ≈ 42.171.',
    {
      prefix: 'h =',
      unit: 'cm',
      value: (3 * 1104.031) / (25 * Math.PI),
      tolerance: 0.02,
      figure: { kind: 'cone', r: '5 cm', h: '?' },
    },
  ),
  multi(
    'v7',
    V,
    'Which solids have the same volume by Cavalieri’s Principle? Choose all that apply.',
    [
      'A right rectangular prism with cross-section B and height h',
      'A right cylinder with cross-section B and height h',
      'A pyramid with base area B and height h',
      'A right rectangular prism with cross-section 2B and height h/2',
      'An oblique cylinder with cross-section B and height h',
    ],
    [0, 1, 3, 4],
    'Cavalieri: same cross-sectional area at every height ⇒ same volume. Prism, cylinder, and oblique cylinder all have area B through height h (volume Bh). The 2B by h/2 prism also has volume Bh. A pyramid’s cross-section shrinks, so its volume is (1/3)Bh.',
  ),
  mc(
    'v8',
    V,
    'A right triangular prism and a right rectangular prism have the same volume by Cavalieri’s Principle. A plane parallel to the bases cuts a rectangle of area 48. Which triangle could be that cross-section?',
    ['h = 8, b = 12', 'h = 4, b = 12', 'h = 4, b = 8', 'h = 8, b = 14'],
    0,
    'The triangular cross-section must also have area 48: (1/2)bh = 48 → bh = 96. Only 8 × 12 works.',
  ),
  mc(
    'v9',
    V,
    'Find the exact volume of a cylinder with radius 4 and height 9.',
    ['144π', '36π', '72π', '16π'],
    0,
    'V = π·16·9 = 144π.',
    { figure: { kind: 'cylinder', r: '4', h: '9' } },
  ),
  typed(
    'v9b',
    V,
    'Approximate the volume of a cylinder with radius 4 and height 9 to three decimal places.',
    ['452.389', '452.390'],
    '144π ≈ 452.389.',
    {
      prefix: 'V ≈',
      value: 144 * Math.PI,
      tolerance: 0.01,
      figure: { kind: 'cylinder', r: '4', h: '9' },
    },
  ),
  mc(
    'v10a',
    V,
    'A pipe is 1/2 inch thick with inside diameter 3 inches. Find the shaded (ring) area in terms of π.',
    ['(7/4)π', '(5/4)π', '4π − 2.25π', '2π'],
    0,
    'Inner r = 1.5, outer r = 2. Area = π(4 − 2.25) = 1.75π = (7/4)π.',
    { figure: { kind: 'annulus', inner: '3 in', thick: '½ in' } },
  ),
  typed(
    'v10b',
    V,
    'The same pipe is 18 inches long. Type the coefficient of π for the shaded volume (so if the answer is 31.5π, type 31.5).',
    ['31.5', '63/2', '31.50'],
    'Volume = (7/4)π · 18 = 31.5π.',
    {
      prefix: 'coefficient of π =',
      value: 31.5,
      tolerance: 0.05,
      figure: { kind: 'annulus', inner: '3 in', thick: '½ in' },
    },
  ),
  mc(
    'v11',
    V,
    'A sphere of radius 6 has exact volume',
    ['288π', '144π', '36π', '864π'],
    0,
    'V = (4/3)πr³ = (4/3)π·216 = 288π.',
    { figure: { kind: 'sphere', r: '6' } },
  ),
  typed(
    'v12',
    V,
    'A cone has radius 3 and height 8. Find the exact volume as a coefficient of π (type the number in front of π).',
    ['24'],
    'V = (1/3)π·9·8 = 24π.',
    { prefix: 'coefficient of π =', value: 24, figure: { kind: 'cone', r: '3', h: '8' } },
  ),
  mc(
    'v13',
    V,
    'Cavalieri’s Principle says two solids have equal volume when',
    [
      'every plane parallel to the bases cuts equal-area cross-sections, and the solids have the same height',
      'they have the same base shape',
      'they are both prisms',
      'their surface areas are equal',
    ],
    0,
    'Equal corresponding cross-sectional areas and the same height imply equal volume.',
  ),
]

export const DENSITY_QUESTIONS: GeoMathPracticeQuestion[] = [
  typed(
    'd1',
    D,
    'Paula measured this block and found its mass is 400 g. The edges are 8 cm, 5 cm, and 4 cm. Find the density.',
    ['2.5'],
    'V = 8·5·4 = 160 cm³. Density = mass/volume = 400/160 = 2.5 g/cm³.',
    {
      prefix: 'density =',
      unit: 'g/cm³',
      value: 2.5,
      tolerance: 0.02,
      figure: { kind: 'prism', l: '8 cm', w: '5 cm', h: '4 cm' },
    },
  ),
  typed(
    'd2',
    D,
    'A block of wood has density 0.8 g/cm³ and volume 1.5 cm³. What is the mass of the block?',
    ['1.2'],
    'mass = density × volume = 0.8 × 1.5 = 1.2 g.',
    { prefix: 'mass =', unit: 'g', value: 1.2, tolerance: 0.02 },
  ),
  typed(
    'd3',
    D,
    'A 1000 g boulder has density 10 g/cm³. What is the volume of the boulder?',
    ['100'],
    'V = m/d = 1000/10 = 100 cm³.',
    { prefix: 'volume =', unit: 'cm³', value: 100 },
  ),
  typed(
    'd4',
    D,
    'A cube of ice has side length 5 cm. The mass is 114.5 g. Find the density of ice. Round to three decimal places.',
    ['0.916'],
    'V = 125 cm³. d = 114.5/125 = 0.916 g/cm³.',
    {
      prefix: 'density =',
      unit: 'g/cm³',
      value: 0.916,
      tolerance: 0.005,
      figure: { kind: 'prism', l: '5 cm', w: '5 cm', h: '5 cm' },
    },
  ),
  typed(
    'd5',
    D,
    'A solid carbon cylinder has radius 3 cm and height 10 cm. Density of carbon is 1.95 g/cm³. Find the mass rounded to three decimal places.',
    ['551.349', '551.350', '551.348'],
    'V = π·9·10 = 90π. mass = 1.95·90π ≈ 551.349 g.',
    {
      prefix: 'mass =',
      unit: 'g',
      value: 1.95 * 90 * Math.PI,
      tolerance: 0.02,
      figure: { kind: 'cylinder', r: '3 cm', h: '10 cm' },
    },
  ),
  mc(
    'd6',
    D,
    'Wood floats if density is under 1 g/cm³. Piece 1: V = 400 cm³, m = 450 g. Piece 2: V = 0.02 m³, m = 8 kg. Piece 3: V = 1000 cm³, m = 1.03 kg. Which piece is most suitable for a toy boat?',
    ['Piece 2', 'Piece 1', 'Piece 3', 'All three float'],
    0,
    'Piece 1: 450/400 = 1.125 (sinks). Piece 2: 8000 g / 20 000 cm³ = 0.4 (floats). Piece 3: 1030/1000 = 1.03 (sinks). Piece 2 is the only one under 1 g/cm³.',
  ),
  typed(
    'd6p2',
    D,
    'Piece 2 has volume 0.02 m³ and mass 8 kg. Type its density in g/cm³.',
    ['0.4'],
    '0.02 m³ = 20 000 cm³ and 8 kg = 8000 g, so 8000/20000 = 0.4 g/cm³.',
    { prefix: 'density =', unit: 'g/cm³', value: 0.4, tolerance: 0.02 },
  ),
  typed(
    'd7',
    D,
    'A man weighs 79378.6 grams. His volume is modeled by a cylinder of height 170 cm and radius 12 cm. Body fat % is BF = (4.57/p − 4.142) × 100, where p is density in g/cm³. Find BF to the nearest percent.',
    ['28'],
    'V = π·144·170 = 24480π ≈ 76899.6. p ≈ 79378.6/76899.6 ≈ 1.0322. BF ≈ (4.57/1.0322 − 4.142)×100 ≈ 28%.',
    {
      prefix: 'BF ≈',
      unit: '%',
      value: 28,
      tolerance: 1.2,
      figure: { kind: 'cylinder', r: '12 cm', h: '170 cm' },
      math: 'BF = (4.57 / p − 4.142) × 100',
    },
  ),
  mc(
    'd8',
    D,
    'Density is defined as',
    ['mass ÷ volume', 'volume ÷ mass', 'mass × volume', 'weight ÷ area'],
    0,
    'ρ = m / V.',
  ),
  typed(
    'd9',
    D,
    'A cube 4 cm on a side has mass 192 g. Find the density.',
    ['3'],
    'V = 64. d = 192/64 = 3 g/cm³.',
    { prefix: 'density =', unit: 'g/cm³', value: 3, figure: { kind: 'prism', l: '4 cm', w: '4 cm', h: '4 cm' } },
  ),
  mc(
    'd10',
    D,
    'Two objects have the same mass. The one with greater volume has',
    ['smaller density', 'greater density', 'the same density', 'greater weight'],
    0,
    'ρ = m/V, so larger V with fixed m means smaller density.',
  ),
  typed(
    'd11',
    D,
    'A cylinder of radius 2 cm and height 5 cm has mass 94.248 g. Find density rounded to three decimals (use π ≈ 3.1416 if needed).',
    ['1.500', '1.5', '1.50'],
    'V = π·4·5 = 20π ≈ 62.832. d ≈ 94.248/62.832 ≈ 1.500 g/cm³.',
    {
      prefix: 'density =',
      unit: 'g/cm³',
      value: 1.5,
      tolerance: 0.02,
      figure: { kind: 'cylinder', r: '2 cm', h: '5 cm' },
    },
  ),
]
