import { circleFig, mc, typed, type GeoMathPracticeQuestion } from './geoMathQuiz'

const M = 'measure' as const

function pts(list: [string, number, number?][]) {
  return list.map(([id, deg, dist]) => (dist == null ? { id, deg } : { id, deg, dist }))
}

export const MEASURE_QUESTIONS: GeoMathPracticeQuestion[] = [
  mc(
    'm1',
    M,
    'Find the circumference of a circle with radius 7. Round to three decimal places.',
    ['43.982', '153.938', '21.991', '14.000'],
    0,
    'C = 2πr = 14π ≈ 43.982.',
    {
      figure: circleFig({
        points: pts([['A', 0]]),
        lines: [['O', 'A']],
        lengthLabels: [{ from: 'O', to: 'A', text: '7' }],
      }),
    },
  ),
  typed(
    'm2',
    M,
    'Find the circumference of a circle with diameter 10. Round to three decimal places. Do not type units.',
    ['31.416', '31.415'],
    'C = πd = 10π ≈ 31.416.',
    {
      prefix: 'C =',
      unit: 'units',
      value: 10 * Math.PI,
      tolerance: 0.01,
      figure: circleFig({
        points: pts([['A', 180], ['B', 0]]),
        lines: [['A', 'B']],
        lengthLabels: [{ from: 'A', to: 'B', text: '10' }],
      }),
    },
  ),
  typed(
    'm3',
    M,
    'The area of a circle is 153.9 mi². Find the circumference. Round to three decimal places.',
    ['43.982', '43.981', '44.000'],
    'A = πr² → r = √(153.9/π) ≈ 7. Then C = 2πr ≈ 43.982.',
    {
      prefix: 'C =',
      unit: 'mi',
      value: 43.982,
      tolerance: 0.05,
    },
  ),
  mc(
    'm4',
    M,
    'Find the area of a circle with radius 5. Round to three decimal places.',
    ['78.540', '31.416', '15.708', '25.000'],
    0,
    'A = πr² = 25π ≈ 78.540.',
    {
      figure: circleFig({
        points: pts([['A', 0]]),
        lines: [['O', 'A']],
        lengthLabels: [{ from: 'O', to: 'A', text: '5' }],
      }),
    },
  ),
  typed(
    'm5',
    M,
    'Find the area of a circle with diameter 16. Round to three decimal places.',
    ['201.062', '201.061'],
    'r = 8, A = 64π ≈ 201.062.',
    {
      prefix: 'A =',
      unit: 'sq units',
      value: 64 * Math.PI,
      tolerance: 0.01,
    },
  ),
  typed(
    'm6',
    M,
    'The circumference is 25.8 m. Find the area. Round to three decimal places.',
    ['53.010', '53.009', '53.011'],
    'C = 2πr → r = 25.8/(2π) ≈ 4.107. A = πr² ≈ 53.010.',
    {
      prefix: 'A =',
      unit: 'm²',
      value: 53.01,
      tolerance: 0.05,
    },
  ),
  typed(
    'm7',
    M,
    'Given an area of 452.4 in², find the radius. Round to the nearest tenth.',
    ['12', '12.0'],
    'r = √(A/π) = √(452.4/π) ≈ 12.0.',
    {
      prefix: 'r =',
      unit: 'in',
      value: 12,
      tolerance: 0.15,
    },
  ),
  mc(
    'm8',
    M,
    'Find the exact area of a 90° sector with radius 6.',
    ['9π', '36π', '3π', '12π'],
    0,
    'Sector area = (θ/360)πr² = (90/360)π·36 = 9π.',
    {
      figure: { kind: 'sector', radiusLabel: 'r = 6', angleLabel: '90°', degrees: 90 },
    },
  ),
  typed(
    'm9',
    M,
    'A 60° sector has radius 9. Find the sector area rounded to three decimal places.',
    ['42.412', '42.411'],
    '(60/360)π·81 = 13.5π ≈ 42.412.',
    {
      prefix: 'area =',
      unit: 'sq units',
      value: 13.5 * Math.PI,
      tolerance: 0.01,
      figure: { kind: 'sector', radiusLabel: 'r = 9', angleLabel: '60°', degrees: 60 },
    },
  ),
  mc(
    'm10',
    M,
    'r = 12 mi, θ = 315°. Find the exact sector area.',
    ['126π mi²', '144π mi²', '315π mi²', '42π mi²'],
    0,
    '(315/360)π·144 = (7/8)·144π = 126π.',
  ),
  typed(
    'm10b',
    M,
    'r = 12 mi, θ = 315°. Find the sector area rounded to three decimal places.',
    ['395.841', '395.840'],
    '126π ≈ 395.841.',
    { prefix: 'area =', unit: 'mi²', value: 126 * Math.PI, tolerance: 0.01 },
  ),
  mc(
    'm11',
    M,
    'd = 8 m, θ = 120°. Find the exact sector area.',
    ['16π/3 m²', '16π m²', '8π/3 m²', '32π/3 m²'],
    0,
    'r = 4. (120/360)π·16 = (1/3)·16π = 16π/3.',
  ),
  typed(
    'm11b',
    M,
    'd = 8 m, θ = 120°. Find the approximate sector area rounded to three decimal places.',
    ['16.755', '16.756'],
    '16π/3 ≈ 16.755.',
    { prefix: 'area =', unit: 'm²', value: (16 * Math.PI) / 3, tolerance: 0.01 },
  ),
  mc(
    'm12',
    M,
    'Find the exact length of a 120° arc in a circle of radius 9.',
    ['6π', '12π', '3π', '18π'],
    0,
    'Arc length = (θ/360)·2πr = (120/360)·18π = 6π.',
    {
      figure: circleFig({
        points: pts([['A', 0], ['B', 120]]),
        lines: [['O', 'A'], ['O', 'B']],
        lengthLabels: [{ from: 'O', to: 'A', text: '9' }],
        angleLabels: [{ vertex: 'O', from: 'A', to: 'B', text: '120°' }],
      }),
    },
  ),
  typed(
    'm12b',
    M,
    'Find the length of a 120° arc in a circle of radius 9, rounded to three decimal places.',
    ['18.850', '18.849'],
    '6π ≈ 18.850.',
    { prefix: 'arc =', unit: 'units', value: 6 * Math.PI, tolerance: 0.01 },
  ),
  typed(
    'm13',
    M,
    'Two circles each with radius 8 inches are inscribed in a rectangle so they touch the rectangle and each other. Find the area between the circles and the rectangle. Round to the nearest thousandth.',
    ['109.876', '109.875'],
    'Rectangle is 32 by 16, area 512. Two circles: 128π. Shaded = 512 − 128π ≈ 109.876.',
    {
      prefix: 'area =',
      unit: 'in²',
      value: 512 - 128 * Math.PI,
      tolerance: 0.02,
      figure: { kind: 'rect-circles', r: '8 in' },
    },
  ),
  mc(
    'm14a',
    M,
    'Tire A has spoke length 5 in and tire width 1.5 in. How many revolutions does it make traveling 25 feet? Round to three decimals. (25 ft = 300 in; outer radius = spoke + width.)',
    ['7.348', '9.549', '4.775', '15.915'],
    0,
    'Outer r = 6.5 in. C = 13π. Revolutions = 300/(13π) ≈ 7.348.',
    { figure: { kind: 'tire', spoke: '5 in', width: '1.5 in', label: 'Tire A' } },
  ),
  typed(
    'm14b',
    M,
    'Tire B has spoke length 8 in and tire width 2 in. How many revolutions does it make traveling 25 feet? Round to three decimals.',
    ['4.775', '4.774'],
    'Outer r = 10 in. C = 20π. 300/(20π) ≈ 4.775.',
    {
      prefix: 'revolutions =',
      value: 300 / (20 * Math.PI),
      tolerance: 0.01,
      figure: { kind: 'tire', spoke: '8 in', width: '2 in', label: 'Tire B' },
    },
  ),
  mc(
    'm15',
    M,
    'Find the area of the shaded segment: a 90° sector of radius 8 minus the triangular part. Exact answer.',
    ['16π − 32', '16π', '32 − 16π', '8π − 32'],
    0,
    'Sector = (90/360)π·64 = 16π. Isosceles right triangle area = ½·8·8 = 32. Segment = 16π − 32.',
    {
      figure: circleFig({
        points: pts([['A', 0], ['B', 90]]),
        lines: [['O', 'A'], ['O', 'B'], ['A', 'B']],
        shadeSegment: { from: 'A', to: 'B' },
        lengthLabels: [{ from: 'O', to: 'A', text: '8' }],
        angleLabels: [{ vertex: 'O', from: 'A', to: 'B', text: '90°' }],
      }),
    },
  ),
  mc(
    'm16',
    M,
    'AC is tangent at B and ∠ABE = 70°. The shaded region is a sector from the chord/tangent setup. What is m arc BE if ∠ABE is a tangent-chord angle?',
    ['140°', '70°', '35°', '110°'],
    0,
    'A tangent-chord angle equals half its intercepted arc, so the arc is 2 × 70° = 140°.',
    {
      figure: circleFig({
        points: pts([
          ['A', 180, 1.65],
          ['B', 180],
          ['E', 40],
          ['C', 180, 0.4],
        ]),
        lines: [
          ['A', 'B'],
          ['B', 'E'],
        ],
        angleLabels: [{ vertex: 'B', from: 'A', to: 'E', text: '70°' }],
      }),
    },
  ),
  mc(
    'm17',
    M,
    'A circle has circumference 18π. What is its radius?',
    ['9', '18', '6', '36'],
    0,
    'C = 2πr = 18π → r = 9.',
  ),
  typed(
    'm18',
    M,
    'A 45° arc has length 5π. Find the radius.',
    ['20'],
    '(45/360)·2πr = 5π → (1/4)r = 5 → r = 20.',
    { prefix: 'r =', value: 20 },
  ),
  mc(
    'm19',
    M,
    'If radius doubles, area becomes',
    ['4 times as large', '2 times as large', 'the same', '8 times as large'],
    0,
    'Area scales with r², so doubling r multiplies area by 4.',
  ),
  typed(
    'm20',
    M,
    'A sector of 40° in a circle of radius 18 has area kπ. What is k?',
    ['36'],
    '(40/360)π·324 = 36π, so k = 36.',
    { prefix: 'k =', value: 36 },
  ),
]
